### ISSUE TITLE
Not able to enable ;-)

### ISSUE THREAD

**Issue by sysadmama** [Icinga/icingaweb2-module-director#1]
Getting the following error: 
Fatal error: Call to undefined method Icinga\Application\Modules\Module::provideHook() in /usr/share/icingaweb2/modules/director/run.php on line 3

Using icinga2-r2.4.0-1 on Ubuntu 14.04.3

**Comment by lippser** [comment]
Hi,

Which version of Icinga Web 2 are you using? The director module requires Icinga Web 2 version 2.1.0.

Cheers,
Eric

**Comment by dnsmichi** [comment]
Sorry I forgot to disable the issues feature over here, doing that as we speak. Please proceed over here as usual: https://dev.icinga.org/projects/icingaweb2-module-director

Kind regards,
Michael

**Comment by dnsmichi** [comment]
https://dev.icinga.org/issues/10686

**Comment by Thomas-Gelf** [comment]
Guess this can be closed
