### ISSUE TITLE
Timeperiod square on the Icinga Infrastructure page

### ISSUE THREAD

**Issue by NetVicious** [Icinga/icingaweb2-module-director#1001]
If we press on the IcingaWeb2 the Icinga Director menu we go to one Overview tab.

There is a Icinga Infrastructure square.

If we press on it we should be on: /icingaweb2/director#!/icingaweb2/director/dashboard?name=infrastructure

Here we see:
- Kickstart Wizard
- Api Users
- Endpoints
- Zones

If you click on one of they we can see another tab called Timeperiods which doesn't appears in the Infrastructure page.
## Your Environment

* Director version (System - About): 1.3.1
* Icinga Web 2 version and modules (System - About): 2.4.1
* Icinga 2 version (`icinga2 --version`): version: r2.6.0-1
* Operating System and version: Debian GNU/Linux 9
* Webserver, PHP versions: Apache 2.4.25-3+deb9u1, PHP 7.0.19-1

**Comment by Thomas-Gelf** [comment]
Timeperiod is no longer reachable via Infrastructure in `next`.
