### ISSUE TITLE
Timeperiod form needs a zone combobox to select it

### ISSUE THREAD

**Issue by NetVicious** [Icinga/icingaweb2-module-director#1002]
I think I changed or deleted the default icinga-director zone called _director-global_ when it's installed for the first time.

Now I'm creating timeperiods and when I go to deploy they I got this error:

```
critical/config: Error: Validation failed for object '24hx7' of type 'TimePeriod'; Attribute 'zone': Object 'director-global' of type 'Zone' does not exist.
Location: in [stage]/zones.d/director-global/timeperiods.conf: 1:0-1:24
[stage]/zones.d/director-global/timeperiods.conf(1): object TimePeriod "24hx7" {
                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^
[stage]/zones.d/director-global/timeperiods.conf(2):     import "legacy-timeperiod"
[stage]/zones.d/director-global/timeperiods.conf(3):     import "MyTemplate"
```

I see on the table `icinga_timeperiod` a field to set the zone, but this field it's not populated by icinga-director in it's timeperiod form.

## Expected Behavior
Have a zone field on the timeperiod template or timeperiod object to set if.

## Current Behavior
Deployment fails due to a non-existed default zone I renamed or deleted.

## Possible Solution
Add field in timeperiod form

## Your Environment

* Director version (System - About): 1.3.1
* Icinga Web 2 version and modules (System - About): 2.4.1
* Icinga 2 version (`icinga2 --version`): version: r2.6.0-1
* Operating System and version: Debian GNU/Linux 9
* Webserver, PHP versions: Apache 2.4.25-3+deb9u1, PHP 7.0.19-1

**Comment by NetVicious** [comment]
My zone it's id=1, that says I edited time ago the zone name.

I set on the database the zone to 1 and now it deploys perfectly.

**Comment by Thomas-Gelf** [comment]
A lot changed sin
