### ISSUE TITLE
Feature Request: icinga director host append <hostname> --json '{"vars":{"something":"something"}}'

### ISSUE THREAD

**Issue by fireheadman** [Icinga/icingaweb2-module-director#1004]
On the latest version of director/icinga2.

I looked around and didn't see anything in regards to this.   Would it be possible and/or is there value to others to have an append function in director?

I currently see the "set" cmd to modify existing vars, but this ends up wiping out vars I already have set.      For example, Lets sayI have host config with:
host.var.os
host.var.disk
host.var.location
... and later on I want to add host.var.backup_downtime.   If I use the "set" cmd, this accomplishes the update, but also wipes the other vars from the host config.

If there was something like:
`icinga director host append <hostname> --json '{"vars":{"something":"something"}}'`
...Then I could simply retain my existing vars and add the new one.

Again, If this already exists, I apologize in advance and would greatly appreciate a documentation link/pointer as I am not finding anything.

**Comment by Thomas-Gelf** [comment]
Hi @fireheadman,

if you set `vars` you'll override that property - and this means all vars. Setting a single var is as easy as:

    icingacli director host set <hostname> --vars.something something

Of course, also JSON is valid:

    icingacli director host set <hostname> --json '{"vars.something": "something"}'

Both examples should do the trick for you.

Cheers,
Thomas

**Comment by fireheadman** [comment]
Hi Thomas,   I appreciate the quick response...   
Was able to run the cmd/syntax you mentioned, which worked great!   THank you.

Out of curiosity, (quick question) Do you think there will ever be a way to remove/delete a VAR from director?...without having to remove a host entirely and recreate w/o the VAR you want removed?

**Comment by Thomas-Gelf** [comment]
> Hi Thomas, I appreciate the quick response...

You're welcome.

> Do you think there will ever be a way to remove/delete a VAR from director?

JSON-Syntax definitively works:

    icingacli director host set <hostname> --json '{"vars.special": null}'

In theory, an emtpy string should also do the job:

    icingacli director host set <hostname> --vars.special ''

But this last example seems to be broken, I therefore opened #1007. The JSON variant should be fine.
