### ISSUE TITLE
"Run on agent: no" does not overwrite imports

### ISSUE THREAD

**Issue by widhalmt** [Icinga/icingaweb2-module-director#1013]
Hi,

In Director 1.3.1 when I import a template with "Run on agent: Yes" in a template with "Run on agent: No" there is still set a `command_endpoint` in the resulting service.

I hit this with the `cluster_zone` check. I have a "Icinga 2 Agent" Host template, where I set "Run on agent: Yes". Not for a technical reason but for visibility I put "Cluster Zone" there as well but set "Run on agent: No" and set the "Zone" to "master". Then I assigned this service template to all hosts with Icinga 2 agent. When I run `icinga2 object list` I see that `zone` is correctly set to `master` but there's a `command_endpoint` set as well.

The workaround is to just not import a zone with "Run on agent: Yes" so I don't think this issue has a high priority.

Cheers,
Thomas

**Comment by Thomas-Gelf** [comment]
I'm not able to reproduce this with the current master. Could you please give it a try and let me know whether it works there for you?

**Comment by widhalmt** [comment]
I found this in a customers setup. I will try to reproduce.

**Comment by awshew** [comment]
Looks like the issue I filed a few months ago https://github.com/Icinga/icingaweb2-module-director/issues/921

**Comment by Thomas-Gelf** [comment]
Thanks @awshew, I slowly re-read that issue and now finally understood the "inherit Yes, then say No" part of this. In the Director itself it is shown and used correctly everywhere, at least I hope so. The error was that the rendered config still inherited `command_endpoint = host_name` - and this wasn't overwritten anywhere.

I'm now rendering `command_endpoint = null` when an explicit `No` has been set on that specific Service or Temlate and if no other specific endpoint has been given. Only issue I see with this is someone inheriting one template defining a specific `command_endpoint` and THEN says `use_agent = No` - or inherits such a template. But I guess that can then be explained as "works as designed".

I'll immediately push a fix, please let me know whether the rendered config is fine for your Icinga and whether it executes the checks as expected. I gave the rendered result a try on the Icinga console, and it looked good to me.
