### ISSUE TITLE
Add a way to hide templates from the drop down menu some users see

### ISSUE THREAD

**Issue by widhalmt** [Icinga/icingaweb2-module-director#1020]
I'm afraid some uses will find searching through all the configured templates a bit too confusing. So I'd like to see a way I can hide templates from some users alltogether. Maybe a permission with a filter on some custom variable? e.g. `show_to_user`.

**Comment by Thomas-Gelf** [comment]
@widhalmt: what's the purpose of hiding them? Do they have a special meaning? Might adding them to "choices" help in you case (they will no longer be available as "normal" imports)?

**Comment by widhalmt** [comment]
The whole idea is to have a deeper template tree without confusing users. Imagine a tree like "OS/Unix/Linux/RHEL/7". I want users to add "7", not "OS" to a host so I want to hide all but the leaves from dropdown menus. Maybe sometimes it might be useful to have "non-leaf" templates available as well. 
Having different options for different roles would be great.

**Comment by Thomas-Gelf** [comment]
You should give the upcoming [Template Choices](https://github.com/Icinga/icingaweb2-module-director/issues/899) a try. They are already in the current master and will be part of 1.4.0 and should mostly provide what you're asking for. In case you need more flexibility (like offering some choices only based on other choices) please create specific distinct feature requests.

Just, the shown example should have better been solved with fields depending on each other. Please note that templates are (IMHO) NOT the right tool to model a tree view. They have been built for config inheritance and not to solve UI shortcomings. It is NOT a good idea to misuse them just to get an LConf-like tree shown somewhere. In your example Linux/RHEL/7 should be three distinct custom vars, OS and UNIX are pointless in this example.

I'll close this issue so far.

NB: Regarding the "filter on some custom variable" -> that works perfectly with fields. And for your example, just in case you need to allow people to choose only from a restricted sub-set of operating systems: it is now possible to restrict data list entries based on roles.
