### ISSUE TITLE
Services and Host Groups on icinga2 database are not in director

### ISSUE THREAD

**Issue by NetVicious** [Icinga/icingaweb2-module-director#1023]
Looking at the processes my server runs I saw some _check_ping_ processes which I don't have set up on director.

Looking on the icinga2 tables I see that services on the _icinga_services_ table, and I also see some rows in _icinga_hostgroups_ and some rows on _icinga_servicegroups_ which are not in the director database.

I don't know if I skipped something on the director installation, but I'm reading the documentation and I don't see any option to do this importation.

**## Your Environment**
* Director version (System - About): 1.3.1
* Icinga Web 2 version and modules (System - About): 2.4.1
* Icinga 2 version (`icinga2 --version`): r2.6.0-1
* Operating System and version: Debian 9
* Webserver, PHP versions: apache2  2.4.25-3+deb9u1, php 7.0.19-1

**Comment by Thomas-Gelf** [comment]
@NetVicious: I guess this comes from an apply rule in your `/etc/icinga2/conf.d`. That directory contains sample config. This is IMO not the best place to provide such, but for legacy reasons it is there. I usually completely remove the reference to `conf.d` from my `icinga2.conf`, as there is no other safe way to get a clean and upgrade-safe config.

In case you're using the sample mail notification commands please do not forget to either move `commands.conf` to a custom directory or to directly reference just that single file. All other files in `conf.d` should be useless in any real world environment.

**Comment by NetVicious** [comment]
It seems that elements were created by this config file:

**/etc/icinga2/conf.d/groups.conf**
```
/**
 * Host group examples.
 */

object HostGroup "linux-servers" {
  display_name = "Linux Servers"

  assign where host.vars.os == "Linux"
}

object HostGroup "windows-servers" {
  display_name = "Windows Servers"

  assign where host.vars.os == "Windows"
}

/**
 * Service group examples.
 */

object ServiceGroup "ping" {
  display_name = "Ping Checks"

  assign where match("ping*", service.name)
}

object ServiceGroup "http" {
  display_name = "HTTP Checks"

  assign where match("http*", service.check_command)
}

object ServiceGroup "disk" {
  display_name = "Disk Checks"

  assign where match("disk*", service.check_command)
}
```

**Comment by Thomas-Gelf** [comment]
@NetVicious: exactly. And it rarely helps. It might change on upgrades. It's dangerous. Drop it.

**Comment by NetVicious** [comment]
Yes, thanks for answer.

That files should be provided by the Debian package. I emptied they to get a warning when the package it's upgraded.

The problem it's the icinga2 database it's not updated when I deleted that files. So I should need to delete that rows by hand.

Thx for the info.
Regards,

**Comment by Thomas-Gelf** [comment]
@NetVicious: emptying them helps, at least unless Debian or Icinga people decide to ship new files with new names ;-) I'd strongly suggest to go to your `icinga2.conf`, remove:

    include_recursive "repository.d"
    include_recursive "conf.d"

...and add:

    include "conf.d/commands.conf"

To get rid of those services just restart Icinga or re-deploy your config. The database should be fine afterwards, no need to clean it up manually.

**Comment by NetVicious** [comment]
After the restart of icinga and the the deployment from director that services were not deleted from the icinga table. But they're not checked by the icinga2 daemon, so it worked.

And the changes I need to do in the `icinga2.conf` were these:

I removed `include "conf.d/api-users.conf"` as you said.

And I added this:
```
include "conf.d/commands.conf"
include "conf.d/api-users.conf"

The `api-users.conf` contains the Icinga2 API user which director uses. And without that I cannot do a deployment from director.
```

**Comment by Thomas-Gelf** [comment]
@NetVicious: as long as those services vanished from Icinga Web 2, everything should be fine - they become `is_active = 0` in the `icinga_objects` table. If that's not the case, please open related issues in the related trackers ;-)
