### ISSUE TITLE
Unable to change variables on imported commands

### ISSUE THREAD

**Issue by athornhill** [Icinga/icingaweb2-module-director#1024]
I am attempting to create a service that will check interface states where the description on the interface starts with a specific character.  When installing, the Kickstarter imported commands although I no longer see these commands listed where it says it imported them from. 

When using these commands, I cannot modify variables that are defined in the imported command.

Example:

object CheckCommand "interfaces" {
    import "plugin-check-command"
    command = [ PluginDir + "/check_interfaces" ]
    timeout = 1m
    arguments += {
        "--aliases" = {
            description = "Retrieves the interface description."
            set_if = "$interfaces_aliases$"
        }
        "--auth-phrase" = {
            description = "SNMPv3 Auth Phrase"
            value = "$interfaces_auth_phrase$"
        }
        "--auth-proto" = {
            description = "SNMPv3 Auth Protocol (SHA|MD5)"
            value = "$interfaces_auth_proto$"
        }
        "--bandwidth" = {
            description = "Bandwidth warn level in percent."
            value = "$interfaces_bandwidth$"
        }
        "--community" = {
            description = "The community string (default public)."
            value = "$interfaces_community$"
        }
        "--down-is-ok" = {
            description = "Disables critical alerts for down interfaces."
            set_if = "$interfaces_down_is_ok$"
        }
        "--errors" = {
            description = "Number of in errors (CRC errors for cisco) to consider a warning (default 50)."
            value = "$interfaces_errors$"
        }
        "--exclude-regex" = {
            description = "Interface list negative regexp."
            value = "$interfaces_exclude_regex$"
        }
        "--hostname" = "$interfaces_address$"
        "--lastcheck" = {
            description = "Last checktime (unixtime)."
            value = "$interfaces_lastcheck$"
        }
        "--match-aliases" = {
            description = "Also match against aliases (Option --aliases automatically enabled)."
            set_if = "$interfaces_match_aliases$"
        }
        "--mode" = {
            description = "Special operating mode (default,cisco,nonbulk,bintec)."
            value = "$interfaces_mode$"
        }
        "--out-errors" = {
            description = "Number of out errors (collisions for cisco) to consider a warning (default same as in errors)."
            value = "$interface_out_errors$"
        }
        "--perfdata" = "$interfaces_perfdata$"
        "--prefix" = {
            description = "Prefix interface names with this label."
            value = "$interfaces_prefix$"
        }
        "--priv-phrase" = {
            description = "SNMPv3 Privacy Phrase"
            value = "$interfaces_priv_phrase$"
        }
        "--priv-proto" = {
            description = "SNMPv3 Privacy Protocol (AES|DES)"
            value = "$interfaces_priv_proto$"
        }
        "--regex" = {
            description = "Interface list regexp."
            value = "$interfaces_regex$"
        }
        "--sleep" = {
            description = "Sleep between every SNMP query (in ms)."
            value = "$interfaces_sleep$"
        }
        "--speed" = {
            description = "Override speed detection with this value (bits per sec)."
            value = "$interfaces_speed$"
        }
        "--timeout" = {
            description = "Sets the SNMP timeout (in ms)."
            value = "$interfaces_timeout$"
        }
        "--trim" = {
            description = "Cut this number of characters from the start of interface descriptions."
            value = "$interfaces_trim$"
        }
        "--user" = {
            description = "SNMPv3 User"
            value = "$interfaces_user$"
        }
    }
    vars.check_address = {
        type = "Function"
    }
    vars.check_ipv4 = false
    vars.check_ipv6 = false
    vars.interfaces_address = "$check_address$"
    vars.interfaces_aliases = false
    vars.interfaces_down_is_ok = false
    vars.interfaces_match_aliases = false
}

Yet when trying to define or override these variables and make them available to the service in director, they are not listed as available ($interfaces_aliases$, $interfaces_match_aliases$, etc) :

![image](https://user-images.githubusercontent.com/30294488/28372946-02e0803c-6c6f-11e7-9f78-e3d958277cb5.png)

Any thoughts or should I set up the commands differently?  Is there a proper way to bring in the default check commands?

Thanks

## Your Environment

* Director version (System - About):  1.3.1
* Icinga Web 2 version and modules (System - About):  2.4.1
* Icinga 2 version (`icinga2 --version`):   r2.6.3-1
* Operating System and version:  Ubuntu 16.04.2
* Webserver, PHP versions: 7

**Comment by umchik** [comment]
Hey, i'm new to icinga director, so I don't know how well does my answer comply to icinga director design, but the workaround i've found consists of following steps:

1. You create a new command, which imports the command you want to change fields in
2. Click on the newly created command, then go to 'arguments' tab on the right hand side 
3. You add arguments you need in the new command (argument name should be, for instance, **check_ipv4**)
3. Assign values you want to the arguments, and that should solve your issue. (for example **true**)

**Comment by Thomas-Gelf** [comment]
The given answer is correct.
