### ISSUE TITLE
Configuation page for director on the module page is missing

### ISSUE THREAD

**Issue by paladox** [Icinga/icingaweb2-module-director#1025]
## Expected Behavior
It to show the configuration page (kickstart page)

## Current Behavior
Fails with a 404. Page not found.

## Steps to Reproduce (for bugs)

1. Go to <url?/config/modules#!/director/settings

## Context
We were trying to do the kickstart thing from the docs 

## Your Environment

* Director version (System - About):latest from master
* Icinga Web 2 version and modules (System - About) 2.4.1
* Icinga 2 version (`icinga2 --version`): icinga2 - The Icinga 2 network monitoring daemon (version: r2.6.3-1)
* Operating System and version: debian stretch 9
* Webserver, PHP versions: 7

**Comment by Thomas-Gelf** [comment]
This happens with the current master, not with the latest release - correct?

**Comment by Thomas-Gelf** [comment]
@paladox: fixed in current master

**Comment by paladox** [comment]
thankyou for the fast fix

**Comment by Thomas-Gelf** [comment]
You're welcome!
