### ISSUE TITLE
Documentation exporter

### ISSUE THREAD

**Issue by widhalmt** [Icinga/icingaweb2-module-director#1029]
During consulting projects some of our colleagues take configuration details from customer setups with them if they are allowed to.

While Icinga 2 configuration is easy to copy and Directors output can be copied as well, we talked about how nice it could be to have a complete Director output with the details that don't get exported, like service sets, etc.

This issue should be a reminder to talk about some details later.

**Comment by xtruthx** [comment]
Great idea. A tool like this would be a good solution to aware a complete documentation about the customer setup.

**Comment by Thomas-Gelf** [comment]
Part of this will be covered by #1409

**Comment by Thomas-Gelf** [comment]
The Rest comes with #1629, and #1630 will hopefully be absolutely amazing and more than you expected. Closing this as it duplicates the linked issues.

**Comment by Thomas-Gelf** [comment]
@widhalmt, @xtruthx: the linked issues are now both in the master. It's now possible to put some Commands, Templates, ImportSources or whatever (no single Hosts or Services) in a basket. Create snapshots of those objects at any time. This basket can be exported or diffed against another configured Director Database - and you can restore those configuration objects to any of those DB resources.

**Comment by widhalmt** [comment]
Sounds wonderful! I'm very curious about what format they will have. As far as I know your style I'm quite positive they will be human-readable. (Not only machine and super-human readable ;-) )

**Comment by Thomas-Gelf** [comment]
Try it out :stuck_out_tongue:

Spoiler: pretty-printed JSON

**Comment by widhalmt** [comment]
Yeah! I will. :-)
