### ISSUE TITLE
Failed to connect to host: Permission denied

### ISSUE THREAD

**Issue by berthalan** [Icinga/icingaweb2-module-director#1030]
Currently I am trying to use Icinga2 Monitoring and come to find this Icinga Director.
I am a newcomer and a newbie in system administration and just start to learn Icinga2 with CentOS 7.

I met an error and I have no clue how to solve it since I am very new to this field.
After using this tutorial: https://github.com/Icinga/icingaweb2-module-director/blob/master/doc/02-Installation.md

Success to install the icinga director into icingaweb2, then comes the kickstart wizard, and I start to configure it like this
> Endpoint Name: IcingaMaster
> Icinga Host: 172.20.10.5 (my icinga master ip node)
> Port: 5665
> API user: administrator
> Password: *********

=> Run Import

but suddenly got into this error:
CURL ERROR: Failed to connect to 172.20.10.5: Permission denied

how to resolve that?
Sorry for my English, and thank you before :)

* Director version (System - About): 1.3.1
* Icinga Web 2 version and modules (System - About): 2.4.1
* Icinga 2 version (`icinga2 --version`): 2.6.3
* Operating System and version: CentOS 7
* Webserver, PHP versions: Apache 2.4.6, PHP 5.4.16

**Comment by lazyfrosch** [comment]
SELinux?

**Comment by berthalan** [comment]
the status?
it's enforcing.
should I change it to permissive?

if I make it permissive,
the error change to:
CURL ERROR: Failed connect to 172.20.10.5:5665; Connection refused

**Comment by lazyfrosch** [comment]
Well, hopefully you have installed `icingaweb2-selinux`, which adds policies for the basic icingaweb2 Framework and it's interactions with external resources.

But since director is an addon module, it would require additional policies, e.g. for allowing outbound network connections.

It should work in permissive.

Contributions for a SELinux policy are welcome :smile: 

Poking @dgoetz

**Comment by berthalan** [comment]
I've tried to install icingaweb2-selinux but got the same error:
CURL ERROR: Failed connect to 172.20.10.5:5665; Connection refused

What kind of policy is that?
Would you give me an example or a guide link about that?
This my first time touching and configure a system so I really have no idea what to do.
Thank you :))

**Comment by lazyfrosch** [comment]
As I said, it would require additional policies, e.g. for network connections.

I'm no SELinux specialist, so I can't provide it sadly.

**Comment by dgoetz** [comment]
It is actually in the icinga2-selinux package, provided by the boolean httpd_can_connect_icinga2_api which by default is true, so installation of the package should provide everything you need.

But if you still get an error in permissive mode, there has to be another problem. Could be Icinga 2 not running or having the API not enabled or firewalld blocking the access. 
Verify in the order: 
* `systemctl status icinga2.service` -> will show you service is running
* `netstat -taupen | grep 5665` -> will show you icinga2 is listening on port 5665, if not enable the API feature and restart the service
* `iptables -nvL` -> if you see rules firewall is active and you have to disable or configure it, e.g. `firewall-cmd --add-port 5665/tcp --permanent && firewall-cmd --add-port 5665/tcp`

**Comment by berthalan** [comment]
It works!
Thank you so much @lazyfrosch @dgoetz for the help! :D

It turned out that I don't have an icinga2 API feature and haven't add the firewall rule for 5665 port, I also haven't create any endpoint and zone too.
So I follow @dgoetz instruction, and follow this instruction to add zone and endpoint:
https://www.icinga.com/docs/icinga2/latest/doc/06-distributed-monitoring/#top-down-command-endpoint
and now it works like a spell 😄

**Comment by Thomas-Gelf** [comment]
Guess we should add more links pointing to the [Getting started](https://github.com/Icinga/icingaweb2-module-director/blob/master/doc/04-Getting-started.md) section of the documentation.
