### ISSUE TITLE
Apply rule necessary when editing service in a service set

### ISSUE THREAD

**Issue by tobiasvdk** [Icinga/icingaweb2-module-director#1031]
When editing an already existing service in a service set you need to provide an apply rule config.

## Expected Behavior
Apply rule is not necessary.

## Current Behavior
Apply rule is necessary.

## Steps to Reproduce (for bugs)

1. Create service set
2. Add service - apply rule is not needed
3. Nagivate back to the service set and the service
4. Apply rule is needed

## Context
This makes no sense since you apply the whole service set.

## Your Environment

* Director version (System - About): latest master (2d802128ac9629dce18d6f1bc2e2a1c308805ff7)
* Icinga Web 2 version and modules (System - About): 2.4.1
* Icinga 2 version (`icinga2 --version`): 2.6.3
* Operating System and version:
* Webserver, PHP versions:

**Comment by Thomas-Gelf** [comment]
Thanks for reporting this, will be fixed!
