### ISSUE TITLE
User templates are not editable

### ISSUE THREAD

**Issue by tobiasvdk** [Icinga/icingaweb2-module-director#1032]
When trying to access an already defined user template the pane on the right site shows an error with "Page not found".

## Expected Behavior
Show the user template form.

## Current Behavior
Shows an error.

## Steps to Reproduce (for bugs)

1. Open user templates list
2. Click on a user template
3. Error is shown

## Your Environment

* Director version (System - About): 2d802128ac9629dce18d6f1bc2e2a1c308805ff7
* Icinga Web 2 version and modules (System - About): 2.4.1
* Icinga 2 version (`icinga2 --version`): 2.6.3
* Operating System and version:
* Webserver, PHP versions:

**Comment by tobiasvdk** [comment]
Current URL: icingaweb2/director/usertemplate/usage?name=support-user
Correct URL: icingaweb2/director/user?name=support-user

**Comment by Thomas-Gelf** [comment]
Fixes with #1028

**Comment by Thomas-Gelf** [comment]
Sorry, not fixed - pushed only the one for timeperiods
