### ISSUE TITLE
Provide a failsafe "you need PHP 5.3" error

### ISSUE THREAD

**Issue by Thomas-Gelf** [Icinga/icingaweb2-module-director#1033]
## Expected Behavior

Director v1.4.0 requires PHP 5.4. When upgrading on 5.3, I expect to see a meaningful error message.

## Current Behavior

All kind of parse errors, like this:

    Parse error: syntax error, unexpected '[' in [...]/ConfigController.php 

## Possible Solution

There is no easy way to fix this. 5.4 has new language constructs 5.3 is not able to parse, with `array('bla')` VS `['bla']` being the most prominent one. I'll try to re-route all requests to a legacy controller showing an error message for any route on 5.3.

## Steps to Reproduce (for bugs)

`git pull` on PHP 5.3

**Comment by dnsmichi** [comment]
Perfect 👍

**Comment by aflatto** [comment]
Thank you

**Comment by Thomas-Gelf** [comment]
Will look like this:

![director_php53error](https://user-images.githubusercontent.com/553008/28614923-ab66f6b8-71f7-11e7-96ce-ce52282d154b.png)

**Comment by Thomas-Gelf** [comment]
@aflatto: should look like in the above screenshot. Could you please give it a try on CentOS to make sure that I didn't oversee anything?
