### ISSUE TITLE
Cannot change mandatory option in command fields

### ISSUE THREAD

**Issue by frayber** [Icinga/icingaweb2-module-director#1034]
When I change the mandatory value from "y" to "n" in a command field, it looks like correct value is saved, but watching preview the value does not change, it always display "required = true".
I solved changing values in db, in table "icinga_command_argument".

* Director version (System - About): 1.3.1
* Icinga Web 2 version and modules (System - About): 2.4.1
* Icinga 2 version (`icinga2 --version`): 2.6.3
* Operating System and version: Centos 7.3.1611
* Webserver, PHP versions: Apache 2.4.6, PHP 5.4.16, MariaDB 5.5.52

**Comment by Thomas-Gelf** [comment]
@frayber: can you reproduce this with the current master? Works fine here

**Comment by frayber** [comment]
Sorry I haven't 1.3.2 in repository for upgrade, I can't upgrade. I'll test it when I'll do upgrade.

**Comment by Thomas-Gelf** [comment]
Should work fine, closing this for now. In case you're still facing related issues please let me know!
