### ISSUE TITLE
Section "Check Execution" is missing in Services

### ISSUE THREAD

**Issue by tobiasvdk** [Icinga/icingaweb2-module-director#1035]
The section "Check Execution" is missing in Services. It's visible in "Service Templates".

## Expected Behavior
Be able to change "Check Execution" settings in the service definition.

## Current Behavior
Only in service template it's possible to change the "Check Execution" config.

## Steps to Reproduce (for bugs)

1. Create a service from a template
2. See that there is no section "Check Execution"

## Your Environment

* Director version (System - About): 75ca51e85b4823f79564248ef7ef01c448b374f9
* Icinga Web 2 version and modules (System - About): 2.4.1
* Icinga 2 version (`icinga2 --version`): 2.6.3
* Operating System and version:
* Webserver, PHP versions:

**Comment by Thomas-Gelf** [comment]
Hi @tobiasvdk,

that's intended. Check execution settings are dangerous and might allow one to run a DoS attack against your systems. In Director, Templates are for admins only, "normal" objects might be created by other users. In case you want to make those settings available to your users in a comfortable way please consider using the new [Choices](https://github.com/Icinga/icingaweb2-module-director/issues/899) mechanism.

Cheers,
Thomas

**Comment by Thomas-Gelf** [comment]
I'll close this issue, please do not hesitate to reopen it in case you have more related questions!

**Comment by tobiasvdk** [comment]
Thanks @Thomas-Gelf for the clarification.

**Comment by rafiwui** [comment]
Sorry for posting sth here again but I don't want to open a new issue for this:
I was wondering if it would be able to at least make the check_period accessible to each service. Because that is sth that has to be altered very often in our environment and it is annoying to always create a new template for each timeperiod and asign this as additional template to a service.
