### ISSUE TITLE
Unable to set states when adding new Icinga User template

### ISSUE THREAD

**Issue by chrisg86** [Icinga/icingaweb2-module-director#1037]
I am trying to create a new Icinga User template via Users / Contacts. Whenever I select anything for fields `State` or `Transition types`, it will highlight it red and showing following error message (this message is dynamic, in this case I've chosen `Up/Down` for `States`):

```
Got invalid property "Hosts", allowed are: (Up, Down, OK, Warning, Critical, Unknown) (ExtensibleSet.php:472)
```

I expand `State and transition type filters` and try to select anything from the list for field `States`. What

## Expected Behavior
It should let me select items from the lists.

## Current Behavior
It show different values after I select an item from the list and highlights whatever I select in red. Besides I see an error message.

## Possible Solution
The values of this select box might have gotten mixed up.

## Steps to Reproduce (for bugs)

1. Icinga Director -> Users / Contacts -> Tab Templates -> Add
2. Expand `State and transition type filters`
3. Select any value for `State` or `Transition types`
4. See error message

## Context
I was trying to add a new user template.

## Your Environment
* Director version (System - About): 1.3.1
* Icinga Web 2 version and modules (System - About): 2.4.1
* Icinga 2 version (`icinga2 --version`): r2.6.3-1
* Operating System and version: Ubuntu 16.04.2 LTS
* Webserver, PHP versions: nginx/1.10.3 PHP 7.0.18

**Comment by Thomas-Gelf** [comment]
Oh, I see - thanks for reporting this. Will be fixed

**Comment by vittel1** [comment]
I guess when you fix the user state problem, this will be fixed as well?!

![selection_172](https://user-images.githubusercontent.com/10963772/28673224-5356a234-72e2-11e7-814c-844ceedee5fc.png)

**Comment by Thomas-Gelf** [comment]
Yes, that's the same issue

**Comment by chrisg86** [comment]
@Thomas-Gelf Exactly

**Comment by lonelyadmin** [comment]
I still see this exact same thing in 1.4.1...should I be checking out a different revision?
