### ISSUE TITLE
Error is shown when adding a field to a service template

### ISSUE THREAD

**Issue by tobiasvdk** [Icinga/icingaweb2-module-director#1043]
When adding a field to a service template the following error is shown but the field is added.
```
Trying to get invalid property "id" (DbObject.php:260)
```

## Expected Behavior
No error is shown.

## Current Behavior
An error is shown.

## Steps to Reproduce (for bugs)

1. Open a service template
2. Try to add a custom field
3. See the error message

## Your Environment

* Director version (System - About): b2736e17766ffac3ebd1f03c9e02185c569fe955
* Icinga Web 2 version and modules (System - About): 2.4.1
* Icinga 2 version (`icinga2 --version`): 2.6.3
* Operating System and version:
* Webserver, PHP versions:

**Comment by Thomas-Gelf** [comment]
It fails to build the redirect URL, thanks for reporting this!
