### ISSUE TITLE
can't delete data list entry with key zero

### ISSUE THREAD

**Issue by wols** [Icinga/icingaweb2-module-director#1045]
A selected data list entry with key "0" shows not the [store/delete] buttons and can't deleted:

![director-datalistentry_zero](https://user-images.githubusercontent.com/764167/28756293-b8c9d1be-756b-11e7-9a8e-d22522507928.png)

* Director version (System - About): 1.3.1
* Icinga Web 2 version and modules (System - About): 2.4.1
* Icinga 2 version (`icinga2 --version`): r2.6.3-1
* Operating System and version: Gentoo Linux 4.4.21
* Webserver, PHP versions: apache-2.4.27, php-5.6

**Comment by Thomas-Gelf** [comment]
Thanks @wols for reporting this, will be fixed.
