### ISSUE TITLE
Syncing datalists fails with "Trying to recreate director_datalist_entry"

### ISSUE THREAD

**Issue by cyberkov** [Icinga/icingaweb2-module-director#1048]
Hello!
## Expected Behavior

Syncing Director Datalist entries should sync and purge on import.
## Current Behavior

Instead an error is thrown on the second import:
```
This Sync Rule failed when last checked at 2017-07-31 15:41:51: 
Trying to recreate director_datalist_entry ({"list_id":"4","entry_name":"92033000344"})
```
## Steps to Reproduce (for bugs)

1. Create an import source ( I used an sql select). For example
```
SELECT 'customer1' AS entry_name, 'customer1_name' AS entry_value, '3' AS list_id
UNION SELECT 'customer2' AS entry_name, 'customer2_name' AS entry_value, '3' AS list_id
UNION SELECT 'customer3' AS entry_name, 'customer3_name' AS entry_value, '3' AS list_id
```
2. Create a syncrule "Datalists from DB"
```
Rule name: Datalists from DB
Object Type: Datalist entry
Update policy: doesn't matter, none work
Purge: yes
```

3. As properties i used:

Source field | Destination
------------- | -------------
${entry_name} |  entry_name
${list_id} | list_id
${entry_value} | entry_value
string | format

4. The first run works fine, all items are imported.
The second run, fails with 
```
This Sync Rule failed when last checked at 2017-07-31 15:41:51: Trying to recreate director_datalist_entry ({"list_id":"4","entry_name":"92033000344"})
```

## Context

The source is a Postgresql database. Icingaweb Backend is Mysql. But I don't think that this relates to the problem.

## Your Environment

* Director version (System - About): 1.3.1 (master branch - 5ccb94dfbdf8bb3ed337679bf74579c3c95744e8 )
* Icinga Web 2 version and modules (System - About): 2.4.1
* Icinga 2 version (`icinga2 --version`): r2.6.3-1
* Operating System and version: Ubuntu 16.04.2
* Webserver, PHP versions: Nginx 1.10.3 with php7.0-fpm

Thanks for your help!

Cheers Hannes

**Comment by lazyfrosch** [comment]
Whoopsie, looks like my change.

**Comment by lazyfrosch** [comment]
Could you guys try the patch in #1492 ?

**Comment by Thomas-Gelf** [comment]
Wait, this only fixes the error shown by @tobiasvdk. @cyberkov: in your case, the key column definition of your import source could be the problem. Could you please show me what it looks like?

Thanks,
Thomas

**Comment by lazyfrosch** [comment]
This could be a problem with combined Keys, I think I broke something too.

**Comment by lazyfrosch** [comment]
IMHO We should remove `removeForeignListEntries` - we are not doing it for any other object currently.

@Thomas-Gelf ok?

**Comment by tobiasvdk** [comment]
Using latest git master I get the following error:
```
Uncaught Error: Call to undefined method Icinga\Module\Director\Import\Sync::singleObjectsAreAllowedToFail() in /usr/share/icingaweb2/modules/director/library/Director/Import/Sync.php:756
Stack trace:
#0 /usr/share/icingaweb2/modules/director/library/Director/Objects/SyncRule.php(135): Icinga\Module\Director\Import\Sync->apply()
#1 /usr/share/icingaweb2/modules/director/library/Director/Objects/SyncRule.php(171): Icinga\Module\Director\Objects\SyncRule->checkForChanges(true)
#2 /usr/share/icingaweb2/modules/director/application/forms/SyncRunForm.php(31): Icinga\Module\Director\Objects\SyncRule->applyChanges()
#3 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/QuickForm.php(381): Icinga\Module\Director\Forms\SyncRunForm->onSuccess()
#4 /usr/share/icingaweb2/modules/director/application/controllers/SyncruleController.php(36): Icinga\Module\Director\Web\Form\QuickForm->handleRequest()
#5 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Director\Controllers\Sync
```

**Comment by Thomas-Gelf** [comment]
@tobiasvdk: my fault, please try again

**Comment by tobiasvdk** [comment]
Ok, now I get the same error message as the author
```
This Sync Rule failed when last checked at 2018-05-22 10:28:32: Trying to recreate director_datalist_entry ({"list_id":36,"entry_name":"my_entry"})
```

**Comment by Thomas-Gelf** [comment]
We are getting closer :laughing:

**Comment by Thomas-Gelf** [comment]
@tobiasvdk: could you please share more related details? I tried to reproduce this using the sample import shown by @cyberkov - works fine for me. Authors example also doesn't fit the error message:

    ...Trying to recreate director_datalist_entry ({"list_id":"4","entry_name":"92033000344"})

Strange...

**Comment by lazyfrosch** [comment]
@Thomas-Gelf I can reproduce it, as said this happens when `list_id` is not numeric, but an expression...

**Comment by Thomas-Gelf** [comment]
@lazyfrosch: thanks, got it. We have two options here:
a) do not allow expressions and eventually provide a dropdown allowing one to choose a list instead of giving us an ID
b) allow to define sync rules allowing to theoretically write entries to multiple lists with a single sync rule

b) feels scary, I'd opt for a)

**Comment by lazyfrosch** [comment]
@Thomas-Gelf I'd opt for removing `removeForeignListEntries` since we don't do it for any other object...

**Comment by Thomas-Gelf** [comment]
I like that proposal, but that will probably break "purge" for all setups with an "invalid" key column definition. And as for datalist entries this always "just worked" there might be a lot.

**Comment by lazyfrosch** [comment]
It would only purge when the key combination disappears from the import source, that is not different as for other syncs :thinking:

**Comment by tobiasvdk** [comment]
I have a data list (id=36) with location mapping (key -> value):
* de-foo -> de-foo
* de-bar -> de-bar

My sync rule is (source field -> destination)
* ${name} -> entry_name
* ${name} -> entry_value
* ${list_id} -> list_id

The import source is a sql query giving ${name} and (statically) 36 as
```
select name, 36 as list_id from ...
```

**Comment by Thomas-Gelf** [comment]
@lazyfrosch: sure, that's how it should be. Problem is that syncing data lists is older, purge always worked fine because of this hard-coded list_id/entry_name combination and probably no one cared about creating a combined column (via the Combine property modifier or similar) to then use it as a key column. You just used entry_name and things went fine.

Technically dropping it would be correct, but it wouldn't be very friendly. Especially given that combined keys are a complicated and not so well known thing.

**Comment by Thomas-Gelf** [comment]
@tobiasvdk: thanks. I imagine if you change `${list_id} -> list_id` to `42 => list_id` with 42 being "Custom Expression" and your list id, things work fine?

**Comment by lazyfrosch** [comment]
@Thomas-Gelf Get your point, but you don't need to create a dedicated combined column, unless you have to deduplicate your input list, afaik this should not matter for the Sync itself...

This should only be important when switching to a multi-datalist import when keys are identical.

**Comment by Thomas-Gelf** [comment]
@lazyfrosch: well, I didn't try it out - but I imagine that once we remove that hard-coded logic purge strategy will no longer work if your key column is not correct.

**Comment by tobiasvdk** [comment]
@Thomas-Gelf : yes, using a custom expression works

**Comment by Thomas-Gelf** [comment]
Form will be changed accordingly.
