### ISSUE TITLE
Usability of "imports" in templates/services/hosts/commands limited

### ISSUE THREAD

**Issue by sahnd** [Icinga/icingaweb2-module-director#1051]
After updating to latest master commit (from 4d24097 to 5ccb94d) the usability of the drop-down lists provided to import templates to a service/host/commands/other template is very limited. The list is now cut after 30 elements.
Working with many templates forces the user to know about the other names of the templates to search for them by typing some letters into the "imports" field.
Combined with #1047 it e.g. makes connecting services to host templates very complicated.

## Expected Behavior
drop-down lists of templates to import should provide a full view of available templates.

## Current Behavior
The list of templates to import to a service/host/command/other template is cut after 30 elements.

## Possible Solution
Restore old behavior or maybe load another 30 elements when scrolling down to the end of the list.

## Steps to Reproduce (for bugs)
1. Have more than 30 templates
2. Create object or template
3.  try to import a template
4. scroll down to end of drop down list and see what is missing

## Context
Our setup has several host and service templates. 
When trying to connect a service to a host template the list of available service templates to import is not very usable if you don't know the name of the service template to import.
When adding a new host template importing a given host template is limited in the same way.

## Your Environment
* Director version (System - About): master branch (5ccb94d)
* Icinga Web 2 version and modules (System - About): 2.4.1
* Icinga 2 version (`icinga2 --version`): 2.6.3
* Operating System and version: Ubuntu 16.04
* Webserver, PHP versions: Apache 2.4, PHP 7.0

**Comment by LordHepipud** [comment]
Is this issue still up-to-date? I have tested it with latest master of the Director and it works very well.
To get a full list of templates or imports in general, simply type * into the text field to receive a full list. If you wish to filter more detailed, like for "ping" for example, typing that one into the text field will result in all templates containing "ping".

**Comment by Thomas-Gelf** [comment]
Not the full list, but limit has been raised to 100 templates. Search should work fine and in case you have even more templates it could be worth the effort to give the new "Template Choices" a look. I consider this fixed, but please do not hesitate to re-open this or a related issue in case you're still facing problems.
