### ISSUE TITLE
preg_match() expects parameter 2 to be string, object given

### ISSUE THREAD

**Issue by TheFlyingCorpse** [Icinga/icingaweb2-module-director#1052]
## Expected Behavior

Display the list of applied services to the host under the Services tab on the host object.
If the network_parents is non-existing, the tab Services on the relevant hosts works as expected.
## Current Behavior

Error message, no stack trace:
```
preg_match() expects parameter 2 to be string, object given
```

## Steps to Reproduce (for bugs)

1. Host1
```
object Host "sw6004.inf.labdomain.net" {
    import "CiscoPrime_Device"
 
    address = "172.19.4.60"
    groups = [ "CiscoPrime-Loc1" ]
    vars.appliance_type = "CiscoSwitch"
    vars.cisco_devicetype = "Cisco Catalyst 2960-8TC Compact Switch"
    vars.cisco_node = "true"
    vars.cisco_productFamily = "Switches and Hubs"
    vars.cisco_version = "12.2(43)SE"
    vars.dtap = "PRODUCTION"
    vars.hostname = "sw6004"
    vars.icinga_node = "false"
    vars.object_type = "Metal Network Switch"
}
```

2. Host2
```
object Host "sw6077.inf.labdomain.net" {
    import "CiscoPrime_Device"
 
    address = "172.19.77.60"
    groups = [ "CiscoPrime-Loc1" ]
    vars.appliance_type = "CiscoSwitch"
    vars.cisco_devicetype = "Cisco Catalyst 2960-8TC Compact Switch"
    vars.cisco_node = "true"
    vars.cisco_productFamily = "Switches and Hubs"
    vars.cisco_version = "12.2(41)SE"
    vars.dtap = "PRODUCTION"
    vars.hostname = "sw6077"
    vars.icinga_node = "false"
    vars.network_parents = [
        {
        nearEndInterface = "GigabitEthernet0/1"
        neighborDeviceFQDN = "sw6004.inf.labdomain.net"
        neighborDeviceName = "sw6004"
    }
    ]
    vars.object_type = "Metal Network Switch"
}
```
3. Service Apply for
```
apply Service for (config in host.vars.network_parents) {
    name = "snmp-cisco-parent - " + config.neighborDeviceName + " - " + config.nearEndInterface
    check_command = "lab-cisco-ifHC"
    max_check_attempts = "3"
    check_interval = 5m
    retry_interval = 5m
    zone = "master"
    assign where match("*", host.vars.network_parents) && host.vars.cisco_productFamily != "Third Party Device"
    vars.lab_service_type = "Server"
    vars.snmp_community = LabSnmpCommunity
    vars.snmp_interface_name = config.nearEndInterface
 
    import DirectorOverrideTemplate
}
```

## Context

View applied services on the host.
Since this is a "for", if it just displays once for being applied to it, that works too, as it is currently I do not see anything since it errors out on over 800 of my hosts.

## Your Environment

* Director version (System - About): latest from git, seen since before 1.3.1
* Icinga Web 2 version and modules (System - About): snapshot from july, seen since may.
* Icinga 2 version (`icinga2 --version`): 2.6.3 vanilla and latest from git
* Operating System and version: Debian 8.9
* Webserver, PHP versions: Apache2

**Comment by Thomas-Gelf** [comment]
@TheFlyingCorpse: what's your intention with using match("*") with an array? Is that a workaround for some limitation in the available filter possibilities? Director still expects "match" to work with strings only, but sure, this could be fixed.

**Comment by dnsmichi** [comment]
Not sure if related, but v2.7.0 added match() for arrays too in #5264.

**Comment by Thomas-Gelf** [comment]
@dnsmichi: it is related, thanks. That's what I was referring to with

> Director still expects "match" to work with strings only, but sure, this could be fixed

Just, I guess match("*", host.vars.some_array) is a workaround for a limitation we currently have in the filters provided by the Director. Probably @TheFlyingCorpse was looking for an "is set" or "is not empty" operator.

**Comment by dnsmichi** [comment]
Hm, could be `host.vars.some_array.len()` or `len(host.vars.some_array)`, yep.

**Comment by Thomas-Gelf** [comment]
Yeah, and it's getting ugly when we do not know what data type to expect

**Comment by Thomas-Gelf** [comment]
We have explicit `is [not] set` right now.
