### ISSUE TITLE
Reorder sync rule properties

### ISSUE THREAD

**Issue by TheFlyingCorpse** [Icinga/icingaweb2-module-director#1053]
## Expected Behavior

Be able to move the properties of the sync rules internally up or down. Especially useful if adding a new attribute and moving it before the final rules in that sync rule.

## Current Behavior

New sync rules are added at the end. Since last import source in the sync rules, wins, it should be possible to move it in front of other rules if applicable.

## Possible Solution

Add a way to order the properties sync in relation to eachother, such as move it down or up.

## Context

Example:
- Import Source: CiscoPrime (database)
- Import Source: RackTables
- Sync Rule: A
 -- RackTables.FQDN as host.name
 -- CiscoPrime.FQDN as host.name
 -- RackTables.Zone as host.zone
 -- ...
 -- import template CiscoPrime if import source CiscoPrime
 -- import template RackTables if import source RackTables

We use RackTables to override or add on some information to objects that might appear from other sources, however it should only add to and not overwrite/replace.
When the properties of the sync rule are inheriting on the order of this, it creates a precedent to be able to order them. As it is now, if new attributes are added, some of the properties are re-created to be able to handle these scenarios.

## Your Environment

* Director version (System - About):
* Icinga Web 2 version and modules (System - About):
* Icinga 2 version (`icinga2 --version`):
* Operating System and version:
* Webserver, PHP versions:

**Comment by Thomas-Gelf** [comment]
I got confused by the example, @tobiasvdk is right - the linked issue is a duplicate. So, this should have been implemented in the current master.

**Comment by TheFlyingCorpse** [comment]
Actually, it is not fixed, let me try to rephrase the example:

```
RackTables.FQDN as host.name
CiscoPrime.FQDN as host.name
RackTables.Zone as host.zone
RackTables.address as host.address
CiscoPrime.ipaddress as host.address
CiscoPrime.dtap as host.vars.dtap
RackTables.dtap as host.vars.dtap
```

Objects have the same name between CiscoPrime and RackTables, so it merges the object attributes between the two sources.

The experienced behavior is that the last winner sets the winner on all attributes, regardless of ordering on the preceding attributes.
The expected behavior is that the last winner sets the winner on just itself and that ordering is honored.
