### ISSUE TITLE
Infrastructure Tab

### ISSUE THREAD

**Issue by R00T88** [Icinga/icingaweb2-module-director#1054]
## Expected Behavior
Clicking on Director settings in Infrastructure Tab i should see settings

## Current Behavior
Instead it give me an error

Undefined index: director-global

#0 /usr/share/icingaweb2/modules/director/application/forms/SettingsForm.php(144): Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(8, 'Undefined index...', '/usr/share/icin...', 144, Array)
#1 /usr/share/icingaweb2/modules/director/application/forms/SettingsForm.php(26): Icinga\Module\Director\Forms\SettingsForm->eventuallyConfiguredEnum('default_global_...', Array)
#2 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/QuickForm.php(356): Icinga\Module\Director\Forms\SettingsForm->setup()
#3 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/QuickForm.php(495): Icinga\Module\Director\Web\Form\QuickForm->prepareElements()
#4 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/QuickForm.php(508): Icinga\Module\Director\Web\Form\QuickForm->setRequest(Object(Icinga\Web\Request))
#5 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/QuickForm.php(367): Icinga\Module\Director\Web\Form\QuickForm->getRequest()
#6 /usr/share/icingaweb2/modules/director/application/controllers/ConfigController.php(172): Icinga\Module\Director\Web\Form\QuickForm->handleRequest()
#7 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Director\Controllers\ConfigController->settingsAction()
#8 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('settingsAction')
#9 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#10 /usr/share/php/Icinga/Application/Web.php(389): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#11 /usr/share/php/Icinga/Application/webrouter.php(109): Icinga\Application\Web->dispatch()
#12 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...')
#13 {main}

## Steps to Reproduce (for bugs)
Icinga Director -> Activity Log -> infrastructure -> Direct Settings

## Your Environment

* Director version (System - About):
* Icinga Web 2 version and modules (System - About):
* Icinga 2 version (`icinga2 --version`):
* Operating System and version:
* Webserver, PHP versions:

**Comment by Thomas-Gelf** [comment]
Hi @R00T88,

I'll immediately push a fix checking for 'director-global' not being in your available global zones. Guess you have chosen a custom global zone and not the one that has been suggested in the [Getting started](https://github.com/Icinga/icingaweb2-module-director/blob/master/doc/04-Getting-started.md) part of our documentation?

Cheers,
Thomas
