### ISSUE TITLE
Trying to get invalid property "id" (DbObject.php:260) - error message after adding any Data List entry

### ISSUE THREAD

**Issue by bigshadow** [Icinga/icingaweb2-module-director#1055]
I have fresh and clean Icinga 2 installation.
After adding any Data List entry by Icinga2 Director module I have error message below: 
Trying to get invalid property "id" (DbObject.php:260)

## Steps to Reproduce (for bugs)

1. Open Icinga Director -> Data lists -> Add
2. Input to 'Key' field fo example value "1"
3. Input to 'Label' field fo example value "one"
4. Press button 'Add'

## My Environment

* Director version 1.3.1
* Icinga Web 2 version and modules 2.4.1
* Icinga 2 version r2.6.3-1
* Operating System and version:  Debian 9 (4.9.0-3-amd64)
* Webserver, PHP versions: Apache 2.4.25, PHP 7.0.19-1

At first I installed all Icinga 2 components from Debian repository.
When I met this problem then I upgraded all components from Icinga repository.

**Comment by Thomas-Gelf** [comment]
@bigshadow: works fine here. Are you using the 1.3.1 release version or did you download it from our master branch? You'll find this information going to System -> About -> director. It might show a 'Git commit'.

**Comment by bigshadow** [comment]
Git commit ecd91d8bffac20608fced3b60aa697880cda8171

**Comment by Thomas-Gelf** [comment]
Could you please `git pull` and try again?

**Comment by bigshadow** [comment]
This is great - it work without error now)
My first experience with git system for problem solving really excellent - thanks a lot!

**Comment by Thomas-Gelf** [comment]
Glad to hear that, you're welcome!
