### ISSUE TITLE
unable to edit "command templates"

### ISSUE THREAD

**Issue by yodaaut** [Icinga/icingaweb2-module-director#1060]
When trying to edit a custom command template, it says "page not found"
## Expected Behavior

Show the command template form

## Current Behavior

Shows error "Page not found"
## Possible Solution

Maybe it could be solved like #1032
## Steps to Reproduce (for bugs)

1. Click on "Commands" in Director
2. Click on "Command Templates"
3. Click on any Custom Command Template
4. Error on the right

## Your Environment

* Director version (System - About): 1.3.1
* Icinga Web 2 version and modules (System - About): 2.4.1
* Icinga 2 version (`icinga2 --version`): r2.7.0-1
* Operating System and version: Debian Jessie
* Webserver, PHP versions: Nginx, php5
* Database: PostgreSQL 9.6

Thanks in advance

**Comment by vita2** [comment]
can confirm this issue as well. i am using the latest master commit (71ab8b4663b799d45bac42b366d21575fb755d0e)

![command-templates-page-not-found](https://user-images.githubusercontent.com/25298055/29603787-bf11a39e-87e5-11e7-9f0b-8ee139065d1e.png)

**Comment by Thomas-Gelf** [comment]
There is a controller missing
