### ISSUE TITLE
Assigning import template to user not working

### ISSUE THREAD

**Issue by Tuxdiver** [Icinga/icingaweb2-module-director#1061]
We sync users with an Active Directory and import a "Standard User" template in the sync rule.
The  "Imports" property does not work, generated config files does not have the import statement. When editing the imported users, the "Imports" field is empty and nothing can be selected. 

For local users this does also not work. The import field of the users can't be changed, because nothing is shown in the selection box.

## Expected Behavior
- Import statement is added to users in SyncRule
- Allow selection of templates for the "Imports"-field at user edit

## Current Behavior
- user templates are not selectable at user edit
- config file zones.d/master-zone/users.conf does not include the import statement anymore for imported users

## Steps to Reproduce (for bugs)
1. Import User
2. Sync User with "import" property fixed i.e. to "Standard User", selected from popup
3. Edit User or generate config and check zones.d/master-zone/users.conf
4. Edit any user, delete the import entries and try to add one

## Your Environment
* Director version (System - About):  
  * 7fd94fb5bdb63057916f18e541654fc30143a9e2
* Icinga Web 2 version and modules (System - About): 2.4.1
* Icinga 2 version (`icinga2 --version`): r2.7.0-1
* Operating System and version: Ubuntu 16.04
* Webserver, PHP versions:  Apache  2.4.18-2ubuntu3.4, PHP 7.0.18-0ubuntu0.16.04.1

**Comment by Tuxdiver** [comment]
The problem seems to be in application/controllers/SuggestController.php: there is no function for getting suggests for usertemplates, should be named suggestUsertemplates

Please have a look at this try, but I am not sure, if it is correct! (seems to work for me)
```
    protected function suggestUsertemplates()
    {
        $this->assertPermission('director/users');
        $db = $this->db()->getDbAdapter();
        $query = $db->select()
            ->from('icinga_user', 'object_name')
            ->order('object_name')
            ->where("object_type = 'template'");
        return $db->fetchCol($query);
    }
```

**Comment by tobiasvdk** [comment]
Do you also sync hosts with imports? Maybe it's related to #1062 since you also use the current master. I think the suggest* functions are used in the gui.

**Comment by Tuxdiver** [comment]
Yes, I think this issue has two part: one is the suggest-Problem, the other seems to be related to #1062 - but I import user, not hosts. But the imports are also not set in the sync rule.

**Comment by Thomas-Gelf** [comment]
@Tuxdiver: the Sync-related part should have been fixed today, I'll immediately push the missing suggestion method - thanks for reporting this!
