### ISSUE TITLE
Service conf file created by Director in a wrong zone folder and not replicated on a Satellite

### ISSUE THREAD

**Issue by fabrital** [Icinga/icingaweb2-module-director#1064]
When we create with Director either a service or a service template, and we assign it to a cluster zone, the related configuration file is created on the Master in a wrong folder of the file system.
Instead of creating the conf file in the /zones.d/MY-ZONE-NAME/ folder, it creates the file always in the /zones.d/director-global/ folder.
Then, the conf file is not replicated in the file system of the Satellite.

## Expected Behavior
We need to distribute either a service or a service template to a Satellite zone. We create the service with Director, we assign it to a cluster zone, and we expect to see it replicated on the Satellite.

## Current Behavior
Unfortunately, neither the service nor the service template is replicated on the Satellite. We have noticed that the related configuration file is created on the Master always in the /zones.d/director-global/ folder.
Is it a bug, or we miss anything?

## Possible Solution
Obviously is not a structural solution, but if we copy the conf file to the Satellite in the right folder (/var/lib/icinga2/api/zones/MY-ZONE-NAME/director), it works.

## Your Environment

* Director version 1.3.2:
* Icinga Web 2 version and modules (System - About): 2.4.1
* Icinga 2 version (`icinga2 --version`): r2.6.0-1
* Operating System and version: Debian 9

**Comment by fabrital** [comment]
We think to have solved editing the zones.conf file, both on the Master and on the Satellite, specifying:

object Zone "director-global" {
global = true
}

Anybody can confirm that it's the right configuration?

**Comment by lippserd** [comment]
Yep, that is the right configuration: https://github.com/Icinga/icingaweb2-module-director/blob/398fa3622090ba0759e5628deeb9f9b758d8e621/doc/04-Getting-started.md
