### ISSUE TITLE
Service Sets aren't fully restored if one is accidentally deleted.

### ISSUE THREAD

**Issue by dubidubiduuu** [Icinga/icingaweb2-module-director#1065]
If I accidentally klick on the delete Button of a service set and try to "restore former object" only an empty service set is restored. 

"Restore former object" should restore the complete director configuration.

## Steps to Reproduce (for bugs)
Create a service set "test_service_set" and add one or more services to it
Deploy Config
delete service set "test_service_set"
Go to Acitivity log and click on "Restore former object"

The service set is recreated empty.

## Your Environment
* Director version (System - About): 1.3.1
* Icinga Web 2 version and modules (System - About): 2.4.1
* Icinga 2 version (`icinga2 --version`): v2.6.3
* Operating System and version: Red Hat Enterprise Linux Server 7.3
* Webserver, PHP versions: httpd-2.4.6-45.el7 php-5.4.16-42

**Comment by Thomas-Gelf** [comment]
There will be the new Configuration Basket in v1.6, which will make this possible. Moving this to v1.7, at it's a too late for 1.6

**Comment by Thomas-Gelf** [comment]
This should have been fixed, with and without baskets. In case you're still facing problems with the current master please let me know.

**Comment by afeefghannam89** [comment]
This Problem still existing in the actual master ref/NC/#732413
