### ISSUE TITLE
Can't activate director module in icinga web!

### ISSUE THREAD

**Issue by hyperIite** [Icinga/icingaweb2-module-director#1067]
Hey Guys,

I'm really new to this, so maybe its a dumb mistake I'm making. I got icinga2 and web installed and working. Now i tried to install the director module. 

So i installed PHP5 curl, did the API setup, and changed the api-users.conf.
i restarted icinga2, web and apache2 just to be sure. 

i then went on and cloned the git into /usr/share/icingaweb2/modules

after that i created the database in mysql and granted permission.

then i went into the browser and opened icingaweb2 and under modules i can see director and when i click enable, the pop up at the bottom of the screen says that it has been activated. After that nothing happens. i tried this process like three times, deleting everything and starting from scratch... but i have no idea why i can't activate the module. 

Can anyone help me please?

Best Regards
Marv

**Comment by vittel1** [comment]
Did you add the resource of the director at icingaweb? (Configuration -> Application -> Resources)

**Comment by hyperIite** [comment]
Yes i did that :/

**Comment by lippserd** [comment]
Did you rename `icingaweb2-module-director` to `director`?

**Comment by hyperIite** [comment]
Yes i did that too :S

**Comment by lippserd** [comment]
Ok. Then please show the output of `ls -l /etc/icingaweb2/enabledModules/` and `ls -l /usr/share/icingaweb2/modules`.

Just to be sure, nothing happens means here that the module remains deactivated after you've activated it, right?

**Comment by hyperIite** [comment]
Yes, when i press the "Enabled" Button. Theres a banner at the bottom which says it has been activated, but nothing happens.

here is the output: 

root@icinga2-virtual-machine:/etc/icingaweb2/enabledModules# ls -l
total 4
drwxr-sr-x 11 root     icingaweb2 4096 Jul 25 12:36 director
lrwxrwxrwx  1 www-data icingaweb2   33 Jul 12 11:11 doc -> /usr/share/icingaweb2/modules/doc
lrwxrwxrwx  1 www-data icingaweb2   38 Aug  2 12:16 graphite -> /usr/share/icingaweb2/modules/graphite
lrwxrwxrwx  1 www-data icingaweb2   40 Jul 12 11:11 monitoring -> /usr/share/icingaweb2/modules/monitoring



root@icinga2-virtual-machine:/etc/icingaweb2/enabledModules# ls -l /usr/share/icingaweb2/modules
total 28
drwxr-xr-x 11 root root 4096 Aug  9 12:41 director
drwxr-xr-x  6 root root 4096 Jul 12 10:01 doc
drwxr-xr-x  5 root root 4096 Aug  2 11:28 graphite
drwxr-xr-x  7 root root 4096 Jul 12 10:01 monitoring
drwxr-xr-x  5 root root 4096 Jul 12 10:01 setup
drwxr-xr-x  3 root root 4096 Jul 12 10:01 test
drwxr-xr-x  5 root root 4096 Jul 12 10:01 translation

**Comment by lippserd** [comment]
Did you clone the `director` module to [/etc/icingaweb2/enabledModules](url) as well? Try to remove `director` from `/etc/icingaweb2/enabledModules` and enable it again from the web interface.

**Comment by hyperIite** [comment]
Yes there is a copy of the folder in that directory.

**Comment by hyperIite** [comment]
OMG! It worked! I deleted the folder in /etc/icingaweb2/enabledModules. Reenabled in the frontend and it worked 💃  
Thank you very much :)

**Comment by lazyfrosch** [comment]
Very nice!

In `/etc` there should not be any code, `enabledModules` is a symlink method of enabling modules, `modules` in `/etc/icingaweb2` contains config, if the modules has any.

Glad this helped you :smile:
