### ISSUE TITLE
Custom expression for assign_filter in sync rule for Hostgroups is not rendered correctly

### ISSUE THREAD

**Issue by dgoetz** [Icinga/icingaweb2-module-director#1070]
## Expected Behavior
`host.vars.PRIMARY_SUPPORT_GROUP == "${SUPPORT_GROUP_NAME}"` is rendered e.g. as `host.vars.PRIMARY_SUPPORT_GROUP == "Active Directory Services"`

## Current Behavior
`host.vars.PRIMARY_SUPPORT_GROUP == "${SUPPORT_GROUP_NAME}"` is rendered as `host.vars.PRIMARY_SUPPORT_GROUP == null` while `${SUPPORT_GROUP_NAME}` is rendered as `Active Directory Services`.

## Possible Solution
No idea, whats wrong here.

## Steps to Reproduce (for bugs)
1. Create a SQL-Import
2. Create a Sync-Rule for Hostgroups
3. As one property set `object_name` to the source columns (in my case `SUPPORT_GROUP_NAME`)
4. Add another property `assign_filter` as custom expression containing the same field (in my case `host.vars.PRIMARY_SUPPORT_GROUP == "${SUPPORT_GROUP_NAME}"`) 

## Context
I want to import this groups as user groups and host groups and hosts will have the same group name as custom variable so group assignment can be done and used in notification logic and filtering in the web interface. 

## Your Environment
* Director version (System - About): 1.3.1
* Icinga Web 2 version and modules (System - About): 2.4.1
* Icinga 2 version (`icinga2 --version`): r2.7.0-1
* Operating System and version: RHEL 7 (latest updates)
* Webserver, PHP versions: Apache HTTPd + 5.4.16 (RHEL 7 default version)

**Comment by dgoetz** [comment]
Found some not rendered null, but also not correct, e.g.:

```
object HostGroup "Operations Design & Resourceplanning, Housing NA" {
    assign where host.vars.PRIMARY_SUPPORT_GROUP == null && Resourceplanning, Housing NA" == 1
}

object HostGroup "Windows / VM Architecture & Concepts" {
    assign where host.vars.PRIMARY_SUPPORT_GROUP == null && Concepts" == 1
}
```

**Comment by Thomas-Gelf** [comment]
assign_filter must be a valid (eventually nested) Icinga Web 2 Filter with the right-hand side being JSON + url-encoded. Similar to this example:

`host.vars.PRIMARY_SUPPORT_GROUP=%22${SUPPORT_GROUP_NAME}%22`

**Comment by dgoetz** [comment]
Also to add for my examples containing `&` it was required to add a regex modifier to the import replacing `&` with `%26`. So perhaps if others encounter the same problem an urlencode modifier instead of manually urlencoding via regex would be cool.

Thanks for your help!

**Comment by dgoetz** [comment]
Here is another example for getting a filter for in array like `"${APPLICATION}" in host.vars.APPLICATIONS` which has to be `%22${APPLICATION}%22=host.vars.APPLICATIONS`. 

Also I found I have to urlencode `(` and `)`.

So I think this feature needs some documentation and an urlencode modifier in my opinion. Perhaps I can do this on my own and create a PR.

**Comment by dgoetz** [comment]
I decided to do to separate PRs, one for urlencode modifier, one for documentation.
So the first one only contains the modifier.
