### ISSUE TITLE
Properties for sync rule is quite slow when using SQL

### ISSUE THREAD

**Issue by dgoetz** [Icinga/icingaweb2-module-director#1071]
## Expected Behavior
Selecting the Destination Field as Custom Variable and selecting the Source Column is fast and not depending on database performance 

## Current Behavior
Selecting the Destination Field as Custom Variable and selecting the Source Column takes up to 50s, which is caused by the database being slow.

## Possible Solution
Do not execute the full query for this.

## Context
Creation of Sync rules makes the administrator not happy if it is so slow.

## Your Environment
* Director version (System - About): 1.3.1
* Icinga Web 2 version and modules (System - About): 2.4.1
* Icinga 2 version (`icinga2 --version`): 2.7.0
* Operating System and version: RHEL 7
* Webserver, PHP versions: Apache + 5.4 (RHEL default)

**Comment by Thomas-Gelf** [comment]
50s is insanely slow, you should look for a better DBA. I'll add a column cache to this import source, that will cause `listColumns()` to issue the query only once, or better each time when changing the query.
