### ISSUE TITLE
How can I set a Custom Variable from a host template

### ISSUE THREAD

**Issue by hboetes** [Icinga/icingaweb2-module-director#1074]
I just upgraded to the latest release in git. I used to be able to set default values for a custom variable, whereever I wanted but no more. How can I set the default value for a custom variable in a host template for instance?
The only way I can find to set those custom variables is on a per host basis. That would not be practical.

**Comment by Thomas-Gelf** [comment]
@hboetes: GUI slightly changes when it comes to templates, but everything should still be there. Go to a host template, you'll now see it's usage. You have to click "modify" to get to the old template edit form.

**Comment by Thomas-Gelf** [comment]
@hboetes: please let me know in case you're still facing issues, I'll close this so far.

**Comment by hboetes** [comment]
Thanks for your reply, Thomas. Yes I found out how to set those variable. But I still have to click around a lot to find what I want. Often I have to grep the generated config to find back how I actually configured something.
