### ISSUE TITLE
Language in last director master doesn't german 

### ISSUE THREAD

**Issue by winter1967** [Icinga/icingaweb2-module-director#1076]
## Expected Behavior
Calling the module director, in the past, the text were translated in german.

## Current Behavior
All director text is in english, only some entries in the menu left (icingaweb -> direcor) are still in german.

## Steps to Reproduce (for bugs)

1. unzip the current master of director
2. copy it to /usr/share/icingaweb2/modules/director
3. launch icingaweb2 -> director
3. update the  database in the director gui
4. all entries are in english

## Your Environment

* Director version (System - About): 1.3.1 (but the master of 15.08.2017)
* Icinga Web 2 version and modules (System - About):  2.4.1 (cube, director,fileshipper,logstash,pnp, monitoring
* Icinga 2 version (`icinga2 --version`): 2.6.2
* Operating System and version: SLES 11 SP4
* Webserver, PHP versions: apache2, PHP 5.6.22

**Comment by Thomas-Gelf** [comment]
We changed how translations are triggered internally. Currently there are a lot of English-only parts, will be smoothened with 1.4.0. The latest release v1.3.2 should be fine.
