### ISSUE TITLE
Sync property are uses in opposite order than expected

### ISSUE THREAD

**Issue by dgoetz** [Icinga/icingaweb2-module-director#1077]
## Expected Behavior
I can disable and enable hosts during configuration sync.

## Current Behavior
I can only disable hosts during configuration sync as it seems destination_field `disabled` and source_expression `0` gets ignored.  

My properties are meant to disable hosts from source_id 22 (which only should add data to existing hosts and not new hosts) and enable hosts from source_id 4 (which is the CMDB containing the host). So hosts only in source_id 22 should be disabled, hosts in both sources or only in source_id 4 should be enabled. If a change the second property to disable all, it would disable all hosts. If I change the first one it would not enable the hosts. This is what makes me think `disabled = 0` is simply ignored.

```
select * from sync_property where rule_id = 4 and destination_field = "disabled";
+-----+---------+-----------+-------------------+-------------------+----------+-------------------+--------------+
| id  | rule_id | source_id | source_expression | destination_field | priority | filter_expression | merge_policy |
+-----+---------+-----------+-------------------+-------------------+----------+-------------------+--------------+
| 122 |       4 |        22 | 1                 | disabled          |       54 | NULL              | override     |
| 124 |       4 |         4 | 0                 | disabled          |       55 | NULL              | override     |
+-----+---------+-----------+-------------------+-------------------+----------+-------------------+--------------+
2 rows in set (0.00 sec)
```

## Possible Solution
I have no idea.

## Steps to Reproduce (for bugs)
1. Create two import sources containing a slightly different group of hosts.
2. Create two sync rules, one to disable hosts from one source, the other to enable hosts from the other source.

## Context
Hosts from the second source do not provide all required attributes but some additional data, but are not set to be monitored in the CMDB so should not be created in Icinga, so not created via import and sync at all or only as disabled objects.

## Your Environment
* Director version (System - About): 1.3.2
* Icinga Web 2 version and modules (System - About): 2.4.1
* Icinga 2 version (`icinga2 --version`): 2.7.0
* Operating System and version: RHEL 7
* Webserver, PHP versions: Apache - PHP 5.4.16

**Comment by dgoetz** [comment]
I changed the title as @lazyfrosch helped me debugging and found that the sync properties are simply executed in opposite order than expected. Properties get there priority increased with every new property created, so newest one has the highest priority, but then they are executed from high to low which is counterintuitive.

**Comment by lazyfrosch** [comment]
This was set in c6842520d9b8de63599fe59e8a3ac53a10b0c2e9.

But I'm not sure why explicitly reverse order here.

One would expect that the Rules are processed in the order shown - even when the user doesn't have easy control of the order (yet?).

**Comment by lazyfrosch** [comment]
Here is a director mysqldump that allows to easily test the behavior with a simple SQL query import from a pseudo database:

[mysqldump.sql.txt](https://github.com/Icinga/icingaweb2-module-director/files/1230454/mysqldump.sql.txt)

**Comment by tobiasvdk** [comment]
I already changed this month ago in our environment - looks like I forgot to open an issue.
```diff
diff --git a/library/Director/Objects/ImportSource.php b/library/Director/Objects/ImportSource.php
index d197863..25f42c7 100644
--- a/library/Director/Objects/ImportSource.php
+++ b/library/Director/Objects/ImportSource.php
@@ -164,7 +164,7 @@ class ImportSource extends DbObjectWithSettings
             $db->select()
                ->from('import_row_modifier')
                ->where('source_id = ?', $this->id)
-               ->order('priority DESC')
+               ->order('priority ASC')
         );
     }
 
diff --git a/library/Director/Objects/SyncRule.php b/library/Director/Objects/SyncRule.php
index a9e006b..664ca28 100644
--- a/library/Director/Objects/SyncRule.php
+++ b/library/Director/Objects/SyncRule.php
@@ -374,7 +374,7 @@ class SyncRule extends DbObject
             $db->select()
                ->from('sync_property')
                ->where('rule_id = ?', $this->get('id'))
-               ->order('priority DESC')
+               ->order('priority ASC')
         );
     }
 }
```

**Comment by Thomas-Gelf** [comment]
Any idea how to do so without breaking lot's of environments when they `git pull` the next time? Order can now be tweaked in the GUI, but changing that line would mean changing order for a lot of automated setups...

**Comment by Thomas-Gelf** [comment]
@tobiasvdk: I already changed it in ImportSource, you opened an issue for that one. But there it was easiery, priority was never auto-increased. So the effective sort order for most environments should be the row order on disk. I pushed a related schema migration and changed the query accordingly. So with some luck it shouldn't hurt most people. Sync is trickier.

**Comment by Thomas-Gelf** [comment]
One option could be something like:

```sql
UPDATE sync_property SET priority = 10000 - priority;
```

So after the upgrade and the change they would run in opposite order with reverted priority. This means in the same order as before. But from then on, it would "feel right". Any related thoughts?

**Comment by lazyfrosch** [comment]
@Thomas-Gelf I like the idea, cleaning the values and letting user change it if required.

**Comment by Thomas-Gelf** [comment]
@lazyfrosch: ok, deal :)
