### ISSUE TITLE
Create Template Error if using Command Drop Down with mouse

### ISSUE THREAD

**Issue by vittel1** [Icinga/icingaweb2-module-director#1078]
Hi,

I hope this error is not known yet. 
If I am clicking on "hostalive" in the drop down menu with my mouse I get the error output on the second picture.
It works when I am using the keyboard only.

![selection_184](https://user-images.githubusercontent.com/10963772/29365601-e0600b74-8297-11e7-8584-b2fca2623261.png)

![selection_182](https://user-images.githubusercontent.com/10963772/29365587-d4a6b710-8297-11e7-94ac-a070ae56ec61.png)

Director Version: 1.3.1

**Comment by Thomas-Gelf** [comment]
While there are still some improvements for this kind of field in the pipeline, this error should no longer appear in current master.
