### ISSUE TITLE
Feature Request: Allow Field of Type Array to attach DataList

### ISSUE THREAD

**Issue by Zappo-II** [Icinga/icingaweb2-module-director#1080]
## User Story
1. Create a DataList in Director GUI (already possible)
2. Add a List of available Entries (already possible)
3. Create a DataField of Type Array (already possible)
4. Attach a DataList to the DataField of type Array (__not jet implemented__)
5. Assign the Field to appropriate Director Object (already possible)
6. Edit the Director Object with the Assigned DataField of type Array with attached DataList (__not jet implemented__)
    1. ...When Focus on the DataField...
    2. ...The Multi Edit Control (already implemented for Type Array) expands...
    3. ...Instead of `Add a new one...` (already implemented for Array) a `please choose` DropDown Control (already implemented for List) appears...

## Expected Behavior
* Select multiple Values from DropDown Control (ether one at a time or multiple at once) to populate Array Field Elements.

## Current Behavior
* Either Select one Element (ListField) from a List of potential Entries...
    * Convenient but Restricted to exactly one Value...
* Or free Text enter Multiple arbitrary Entries (ArrayField)...
    * Inconvenient (Spelling, Case, Value, Mistakes) but possible to store more than one value...

## Context
* If one would like to provide a controlled vocabulary for specific Values one has to explicitly name exactly one Attribute...
* In some (in my case many) cases one would like to have multiple values from a controlled list of potentials...
* Example:
    * I have multiple Application Deployments on one Host
    * I want to have one Attribute (aka `host.var.my_application = [ ]`)
    * I have a List of Applications like (pseudocode) `{ "ListName":"MyApplications, "List":{"portal":"PortalApp", "booking":"BookingApp", "complaint":"ServiceApp"}}`
    * I want to assign `host.var.my_application = [ "booking", "complaint"]`
* Benefit:
    * Convenience (Workaround is using Array Type Filed)...
    * Controlled Vocabulary, eleminating the Fuss and Hussle with any Case Combination / Typos / Remembering the right Value / etc...
* Use Case Examples:
    * Reporting --> Cube --> Dimension
    * Apply Rules for Service Set targeting the specific Application

**Comment by dgoetz** [comment]
I think this is a duplicate to https://github.com/Icinga/icingaweb2-module-director/issues/560

**Comment by Zappo-II** [comment]
Right you are, thought I did a sensitive search but must have missed on #560 ...
