### ISSUE TITLE
Director API does not support listing services defined in Director

### ISSUE THREAD

**Issue by jwilliams-shadowsoft** [Icinga/icingaweb2-module-director#1081]
There is no way in the Director API to list all services applied to Hosts in Director, all services defined in Director, or all services that have been applied to a specific Host in Director.

## Expected Behavior
Normally REST APIs provide methods to list all objects of a given type.

## Current Behavior
The v1.3.1 Director API supplies methods to list some endpoints but not others. 
For instance Hosts created in Director can be listed using `GET 'director/hosts'`.
There is not equivalent functionality for Services, such as `GET 'director/services'`.
(This results in a 404 error.)

## Possible Solution
Code should be added to the Director API that supports:
* Listing all Services applied to Hosts via Director
* Listing all Services defined in Director
* Listing all Services applied to a specific Host in Director.

## Steps to Reproduce (for bugs)
(feature request)

## Your Environment
* Director version (System - About): 1.3.1

**Comment by Thomas-Gelf** [comment]
The current master now supports `director/hosts` and `director/services`. This will be part of v1.4.0, documentation will be extended accordingly. Extra parameters to tweak the output have been adjusted to fit those for single objects. This should happily be able to send LOTS of objects in a memory-efficient way. In a test environment I was able to retrieve 100,000 hosts in 3 seconds. Most of them being pretty simple, but there where also some complicated ones. 2,000 hosts: 0,09s. It takes three times more to dump them with `json_pp` :laughing:.

It is currently possible to use `director/services?host=some.example.com` to fetch services bound to a single host. In future there might also be `director/host/services?name=some.example.com`. Other routes that will probably be exposed: `director/services/templates`, `director/services/applyrules` and similar for all object types.

@jwilliams-shadowsoft: It's pretty easy to extend this and related features right now, so in case you have urgent need for one of the above or another route just let me know. Current main focus is on fixing the latest issues blocking v1.4.0.
