### ISSUE TITLE
Wrong fields included in service-template

### ISSUE THREAD

**Issue by GWereld** [Icinga/icingaweb2-module-director#1084]
Fields from another service-template are included in a service-template while the fields are not shown on the fields-tab. This happens when the check_command_id of the service-template matches the service_id of another service-template.

![service](https://user-images.githubusercontent.com/31139878/29470947-89770c6e-844e-11e7-9e96-414a5548cd77.png)
The marked fields are included in the service-template, but they are not visible on the fields tab:
![fields](https://user-images.githubusercontent.com/31139878/29470998-afa82ca6-844e-11e7-97b2-6a655815ba85.png)

When i look in the database at the table icinga_service i see the following information for this service:
```
+-----+-------------+-------------+------------------+
| id  | object_name | object_type | check_command_id |
+-----+-------------+-------------+------------------+
| 261 | SAP health  | template    |              215 |
+-----+-------------+-------------+------------------+
```

When i lookup the check_command_id in this table, i get the following information:
```
+-----+-------------+-------------+------------------+
| id  | object_name | object_type | check_command_id |
+-----+-------------+-------------+------------------+
| 215 | SSH         | template    |              112 |
+-----+-------------+-------------+------------------+
```
Looking further at the table icinga_service_field, the following fields are assigned to service_id 261:
```
+------------+--------------+---------------------+
| service_id | datafield_id | varname             |
+------------+--------------+---------------------+
|        261 |          244 | sap_health_ashost   |
|        261 |          245 | sap_health_client   |
|        261 |          246 | sap_health_mode     |
|        261 |          247 | sap_health_password |
|        261 |          248 | sap_health_username |
|        261 |          249 | sap_health_sysnr    |
|        261 |          253 | sap_health_timeout  |
+------------+--------------+---------------------+
```
When i look for the fields defined for service_id 215 i see the fields which are wrongly added to the service-template:
```
+------------+--------------+-------------+
| service_id | datafield_id | varname     |
+------------+--------------+-------------+
|        215 |          237 | ssh_address |
|        215 |          238 | ssh_port    |
|        215 |          239 | ssh_timeout |
+------------+--------------+-------------+
```

I think that the fields are included from the wrong table, because when you assign fields to a command, they are not included in the service-template when you select the command.

**Comment by GWereld** [comment]
I was not able to test the current master, because we are php-5.3.3 and php-5.4 is required.
So i checked which version we were running and saw it was 1.3.0, while i assumed it was the latest version.
I've upgraded to 1.3.2 and see that the problem is already fixed there and the right fields, including the fields assigned to the check_command are included.

Sorry for the inconvenience, but it seems like it was already fixed.

**Comment by Thomas-Gelf** [comment]
@GWereld: even better, thank you anyways!
