### ISSUE TITLE
Allow to re-order sync properties

### ISSUE THREAD

**Issue by Thomas-Gelf** [Icinga/icingaweb2-module-director#1085]
It should be possible to re-arrange their execution order

**Comment by tobiasvdk** [comment]
This is a duplicate of #1053, isn't it?

**Comment by Thomas-Gelf** [comment]
@tobiasvdk: more or less, yes, think so. Btw, this has already been implemented. I didn't push new code since two weeks, but this doesn't mean I that I did nothing:

    git status
    On branch master
    Your branch is ahead of 'origin/master' by 95 commits.

    git diff origin/master master | wc -l
    11850

;-) Sync Rule properties look like this right now:

![director_reorder_sync_properties](https://user-images.githubusercontent.com/553008/29497703-093ac31a-85ed-11e7-98ed-2634ec739b14.png)

I guess I should be able to push the current state tomorrow.

Cheers,
Thomas

**Comment by tobiasvdk** [comment]
Great!
