### ISSUE TITLE
Apply services to hosts or host templates not working anymore

### ISSUE THREAD

**Issue by sahnd** [Icinga/icingaweb2-module-director#1087]
After upgrading from 7fd94fb director does nothing when clicking on "Add service" in "Services" tab under "Icinga Director -> Hosts -> Hosts/Host Templates".
The page changes from showing all assigned services to only having these links:
![add-service-error](https://user-images.githubusercontent.com/25293122/29523903-b2a15648-868e-11e7-9c18-f64d112c2c1a.png)

Maybe this is related to this new behavior under "Icinga Director -> Services -> Single Services"
![service-link-broken](https://user-images.githubusercontent.com/25293122/29524037-1d43c1ca-868f-11e7-8457-5bffad8b2f5d.png)
Here all services derived from applied services to host templates are listed with "none" in host column.

**Comment by Thomas-Gelf** [comment]
@sahnd: all those red ones are broken, they just haven't been shown in former releases. I guess when you deploy your config Icinga 2 should complain about those, so it  should be safe to delete them. Thanks for pointing me to that white page when adding single services, I'll fix this.

**Comment by Thomas-Gelf** [comment]
@sahnd: fixed single services, sets will follow

**Comment by Thomas-Gelf** [comment]
Ok, sets should also be fine right now.
