### ISSUE TITLE
Adding a range to a TimePeriod does not work

### ISSUE THREAD

**Issue by tobiasvdk** [Icinga/icingaweb2-module-director#1088]
## Expected Behavior
Add the new range to the TimePeriod

## Current Behavior
Nothing happens

## Steps to Reproduce (for bugs)

1. Create a TimePeriod (a template or an object)
2. Click on "Ranges"
3. Add "monday" / "00:00-24:00"
![timeperiod_range1](https://user-images.githubusercontent.com/3541433/29534321-d53d1c92-86b5-11e7-91a0-3c2bad733d93.png)
4. Click "Add"
5. The right pane is empty
![timeperiod_range2](https://user-images.githubusercontent.com/3541433/29534320-d53af71e-86b5-11e7-9b6d-41a23dc8ae7a.png)

## Your Environment

* Director version (System - About): 6ba0e8e924a52b5d867da07d799035b79669d45f
* Icinga Web 2 version and modules (System - About): 2.4.1
* Icinga 2 version (`icinga2 --version`): 2.6.3
* Operating System and version: Ubuntu 17.04
* Webserver, PHP versions: 2.4.25-3ubuntu2.2,, 7.0.22-0ubuntu0.17.04.1

**Comment by Thomas-Gelf** [comment]
That's a newly introduced bug, thanks for catching this one!
