### ISSUE TITLE
Removing a range from a TimePeriod is not shown as a change in the activity log

### ISSUE THREAD

**Issue by tobiasvdk** [Icinga/icingaweb2-module-director#1089]
## Expected Behavior
The removal of a range from a TimePeriod is shown as a change in the activity log.

## Current Behavior
The removal of a range from a TimePeriod is not shown as a change in the activity log.

## Steps to Reproduce (for bugs)

1. Create a Timeperiod
2. Add a range
3. Two changes are shown in the activity log 
4. Remove the range
5. No change is shown in the activity log

## Your Environment

* Director version (System - About): fc9425ee894d8935c03fa291e459d718f5614ef7
* Icinga Web 2 version and modules (System - About): 2.4.1
* Icinga 2 version (`icinga2 --version`): 2.6.3
* Operating System and version: Ubuntu 17.04
* Webserver, PHP versions: 2.4.25-3ubuntu2.2,, 7.0.22-0ubuntu0.17.04.1

**Comment by Thomas-Gelf** [comment]
This seems to be a pretty old bug - thanks for reporting it!
