### ISSUE TITLE
Unable to delete/modify service template

### ISSUE THREAD

**Issue by bunghi** [Icinga/icingaweb2-module-director#1090]
## Current Behavior

When I go to Icinga Director -> Services -> Service Templates I see a template named **APP_Switch_Config** duplicated. When selected it doesn't show any information in the right panel and I can't remove or modify it. If I try to deploy any change I get this error:

```
information/cli: Icinga application loader (version: r2.7.0-1)
information/cli: Loading configuration file(s).
critical/config: Error: Object 'APP_Switch_Config' of type 'Service' re-defined: in [stage]/zones.d/director-global/service_templates.conf: 1369:1-1369:36; previous definition: in [stage]/zones.d/director-global/service_templates.conf: 1320:1-1320:36
Location: in [stage]/zones.d/director-global/service_templates.conf: 1369:1-1369:36
[stage]/zones.d/director-global/service_templates.conf(1367): }
[stage]/zones.d/director-global/service_templates.conf(1368): 
[stage]/zones.d/director-global/service_templates.conf(1369): template Service "APP_Switch_Config" {
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[stage]/zones.d/director-global/service_templates.conf(1370):     import "AIX"
[stage]/zones.d/director-global/service_templates.conf(1371): 
```

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

I can't deploy any change

## Your Environment

* Director version (System - About): 1.3.1
* Icinga Web 2 version and modules (System - About): 2.4.1
* Icinga 2 version (`icinga2 --version`): r2.7.0-1
* Operating System and version: Debian 9
* Webserver, PHP versions: Apache 2.4.25

**Comment by Thomas-Gelf** [comment]
You should be able to first rename and then delete one of them.

**Comment by bunghi** [comment]
I can't, when I select it i don't see any option in the right panel:
![image](https://user-images.githubusercontent.com/31234197/29551665-848bbb48-871c-11e7-8e85-11ed0d865065.png)

**Comment by Thomas-Gelf** [comment]
Oh, seems that you're running some state of the GIT master. Could you please `git pull` and try again?

**Comment by bunghi** [comment]
I am using a cluster of two servers, this is the output on both of them:

```
root@mqde01icinga2cl01:/var/log/icinga2# git pull
fatal: Not a git repository (or any parent up to mount point /var)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
root@mqde01icinga2cl01:/var/log/icinga2# df
Filesystem                   1K-blocks    Used Available Use% Mounted on
udev                           1014576       0   1014576   0% /dev
tmpfs                           205256   21368    183888  11% /run
/dev/mapper/rootvg-root        1273432  528944    661752  45% /
/dev/mapper/rootvg-usr         4452864 1859508   2344116  45% /usr
tmpfs                          1026268       0   1026268   0% /dev/shm
tmpfs                             5120       0      5120   0% /run/lock
tmpfs                          1026268       0   1026268   0% /sys/fs/cgroup
/dev/mapper/rootvg-usr+local   1273432   95480   1095216   9% /usr/local
/dev/mapper/rootvg-var         7386176 2546772   4498296  37% /var
/dev/mapper/rootvg-home        2224440    3408   2088324   1% /home
/dev/mapper/rootvg-opt         2550972  763096   1638580  32% /opt
/dev/sda1                       322023   59205    241673  20% /boot
tmpfs                           205252       0    205252   0% /run/user/0
root@mqde01icinga2cl01:/var/log/icinga2#

root@mqde01icinga2cl02:/var/lib/icinga2# git pull
fatal: Not a git repository (or any parent up to mount point /var)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
root@mqde01icinga2cl02:/var/lib/icinga2# df
Filesystem                   1K-blocks    Used Available Use% Mounted on
udev                           1014576       0   1014576   0% /dev
tmpfs                           205256   21356    183900  11% /run
/dev/mapper/rootvg-root        1273432  513412    677284  44% /
/dev/mapper/rootvg-usr         4452864 1528948   2674676  37% /usr
tmpfs                          1026268       0   1026268   0% /dev/shm
tmpfs                             5120       0      5120   0% /run/lock
tmpfs                          1026268       0   1026268   0% /sys/fs/cgroup
/dev/mapper/rootvg-var         2224440  420160   1671572  21% /var
/dev/mapper/rootvg-opt         2550972  763096   1638580  32% /opt
/dev/mapper/rootvg-home        2224440    3408   2088324   1% /home
/dev/mapper/rootvg-usr+local   1273432   93264   1097432   8% /usr/local
/dev/sda1                       322023   59197    241681  20% /boot
tmpfs                           205252       0    205252   0% /run/user/0
root@mqde01icinga2cl02:/var/lib/icinga2#

```

**Comment by Thomas-Gelf** [comment]
@bunghi: how did you retrieve/install your current Director version?

**Comment by bunghi** [comment]
I downloaded the director zip file and unzipped it.

**Comment by Thomas-Gelf** [comment]
@bunghi: so I guess you downloaded the latest development master and not the latest release. Could you please replace your version with the current master and test again?

**Comment by bunghi** [comment]
Well, I downloaded and unzipped the current master but still have the same problem. The strange thing is that when I click on one of the two APP_Switch_Config service templates it automatically selects both of them:
![image](https://user-images.githubusercontent.com/31234197/29600310-c35db134-87dd-11e7-8842-41ee0f435f12.png)

I have a similar problem with the service apply rule below, it doesn't show anything when I select it:

![image](https://user-images.githubusercontent.com/31234197/29600367-10939a04-87de-11e7-9f6d-f70c3dcfcab6.png)

**Comment by Thomas-Gelf** [comment]
Do you see more when you then close the left section? Eventually then reload the page? Anything in your web-servers error-log?

**Comment by bunghi** [comment]
When I close the left section it shows me this error:
![image](https://user-images.githubusercontent.com/31234197/29602025-002415f0-87e7-11e7-9195-7fd504968624.png)

This is the line 244 of the file TemplateTree.php:
![image](https://user-images.githubusercontent.com/31234197/29602068-3008092a-87e7-11e7-8b8e-c7509efcecc2.png)

In apache error.log I see these lines:
```
[Wed Aug 23 08:30:50.004150 2017] [mpm_prefork:notice] [pid 1736] AH00169: caught SIGTERM, shutting down
[Wed Aug 23 08:31:02.796693 2017] [mpm_prefork:notice] [pid 4069] AH00163: Apache/2.4.25 (Debian) configured -- resuming normal operations
[Wed Aug 23 08:31:02.796738 2017] [core:notice] [pid 4069] AH00094: Command line: '/usr/sbin/apache2'

mmap() failed: [12] Cannot allocate memory

mmap() failed: [12] Cannot allocate memory

mmap() failed: [12] Cannot allocate memory

mmap() failed: [12] Cannot allocate memory

mmap() failed: [12] Cannot allocate memory

mmap() failed: [12] Cannot allocate memory

```

**Comment by bunghi** [comment]
By the way, this is how deployments started failing, may be a hint the recursion level too deep message:

![image](https://user-images.githubusercontent.com/31234197/29602169-ad3be7ae-87e7-11e7-991d-47f9676ca740.png)

**Comment by Thomas-Gelf** [comment]
@bunghi: oh, I see - loop detection is missing here. Seems that one of your APP_Switch_Config is inheriting from the other one. In the meantime please run this query:

```sql
DELETE FROM icinga_service_inheritance WHERE parent_service_id IN (
    SELECT id FROM icinga_service WHERE object_name = 'APP_Switch_Config'
) AND service_id IN (
    SELECT id FROM icinga_service WHERE object_name = 'APP_Switch_Config'
);
```

Then you should be able to edit/delete one of those templates. In case you want to provide me some related defaults, you could also first run:

```sql
SELECT id, object_name FROM icinga_service WHERE object_name = 'APP_Switch_Config';
SELECT * FROM icinga_service_inheritance WHERE parent_id IN (
    SELECT id FROM icinga_service WHERE object_name = 'APP_Switch_Config'
);
```

Btw, current master should allow you to still create duplicate services, but not in a way inheriting from each other. In theory :laughing: - at least some related bugs have been fixed. At least I haven't been able to reproduce your error by "clicking around".

In addition, I'll add a loop detection at the place in code you showed.

**Comment by bunghi** [comment]
Select queries output (there are 3 objects with the same name: 2 service templates and 1 service apply rule):

```
MariaDB [director]> SELECT id, object_name FROM icinga_service WHERE object_name = 'APP_Switch_Config';
+-----+-------------------+
| id  | object_name       |
+-----+-------------------+
| 428 | APP_Switch_Config |
| 429 | APP_Switch_Config |
| 441 | APP_Switch_Config |
+-----+-------------------+
3 rows in set (0.05 sec)

MariaDB [director]> SELECT * FROM icinga_service_inheritance WHERE parent_id IN (
    ->     SELECT id FROM icinga_service WHERE object_name = 'APP_Switch_Config'
    -> );
ERROR 1054 (42S22): Unknown column 'parent_id' in 'IN/ALL/ANY subquery'
MariaDB [director]>

```

**Comment by Thomas-Gelf** [comment]
Sorry, please replace `parent_id` with `parent_service_id`

**Comment by bunghi** [comment]
```
MariaDB [director]> SELECT * FROM icinga_service_inheritance WHERE parent_service_id IN (
    ->     SELECT id FROM icinga_service WHERE object_name = 'APP_Switch_Config'
    -> );
+------------+-------------------+--------+
| service_id | parent_service_id | weight |
+------------+-------------------+--------+
|        428 |               428 |      1 |
|        429 |               428 |      1 |
+------------+-------------------+--------+
2 rows in set (0.02 sec)

MariaDB [director]>

```

**Comment by Thomas-Gelf** [comment]
Ok, then please:

```sql
DELETE FROM icinga_service_inheritance WHERE parent_service_id = 428;
```

**Comment by bunghi** [comment]
Deployments work now!! Thanks again for you great help.

**Comment by Thomas-Gelf** [comment]
Glad to hear that, you're welcome!

**Comment by bunghi** [comment]
Hmm.. I don't know if it has something to do with the delete query but since then I see object id instead of object name:

![image](https://user-images.githubusercontent.com/31234197/29610086-cbfccec8-8801-11e7-959a-16ba0d69cd11.png)

Should I open a new issue?

**Comment by Thomas-Gelf** [comment]
This issue should have been fixed yesterday, please download the latest master once again ;) A lot of changes are going on these days to finalize v1.4.0 - sorry for the noise
