### ISSUE TITLE
Services applied to host templates are listed with host "none" under single services

### ISSUE THREAD

**Issue by sahnd** [Icinga/icingaweb2-module-director#1091]
After upgrading from 7fd94fb director lists all services applied to host templates under "Icinga Director -> Services -> Single Services" with "none" in host column.
![service-link-broken](https://user-images.githubusercontent.com/25293122/29554876-0b9437a6-8721-11e7-86db-b6837003775a.png)

## Expected Behavior
Services applied to host templates should not be listed with host = "none" under single services. 

## Current Behavior
After upgrading from 7fd94fb director lists all services applied to host templates under "Icinga Director -> Services -> Single Services" with "none" in host column.
![service-link-broken](https://user-images.githubusercontent.com/25293122/29554876-0b9437a6-8721-11e7-86db-b6837003775a.png)

## Possible Solution
Filter those services and do not display them in single services or change host column value from "none" to host template name.

## Steps to Reproduce (for bugs)
1. apply a service to a host template
2. go to "Icinga Director -> Services -> Single Services"
3. look for service name and see result.

## Your Environment
* Director version (System - About): current master 29410a2
* Icinga Web 2 version and modules (System - About): 2.4.1
* Icinga 2 version (`icinga2 --version`): r2.7.0-1
* Operating System and version: Ubuntu 16.04 
* Webserver, PHP versions: Apache 2.4, PHP 7.0

**Comment by Thomas-Gelf** [comment]
@sahnd: hey, good catch. I can reproduce this, thank you!
