### ISSUE TITLE
templates inheritance: inherited fields shows the id of the imported template, not the name

### ISSUE THREAD

**Issue by vita2** [Icinga/icingaweb2-module-director#1093]
## Expected Behavior
if a field inherit a value from a template then the name of the imported template should appear in the text field next to the value.

## Current Behavior
if a field inherit a value from a template then the id of the imported template will appear in the text field next to the value.

![templates-inheritance](https://user-images.githubusercontent.com/25298055/29557697-34957e68-872a-11e7-9bd2-345c2e287f58.png)

## Context
i found the issue at the notification templates but i discovered the same behavior at other objects like hosts, host templates, services, service templates, contacts and so on.

## Your Environment
* Director version (System - About): commit 29410a2079b17aac0b2280168f75e545114a9df0 master branch
* Icinga Web 2 version and modules (System - About): 2.4.1
* Icinga 2 version (`icinga2 --version`): r2.7.0-1
* Operating System and version: Debian Jessie 8.9 (3.16.0-4-amd64)
* Webserver, PHP versions: nginx 1.6.2-5 + php5-fpm 5.6.30

**Comment by mwaldmueller** [comment]
+1

**Comment by Thomas-Gelf** [comment]
@vita2: thanks for reporting this, should be fixed - please try again!

**Comment by vita2** [comment]
you've fixed it. thanks tom! :wink:
