### ISSUE TITLE
False-positive caching on duplicate names

### ISSUE THREAD

**Issue by lazyfrosch** [Icinga/icingaweb2-module-director#1094]
@Thomas-Gelf I noticed an interesting behavior on 1.3.2, not sure if you seen something like that, or it is different in 1.4.

Let's say I have:

* A template called nrpe (yes I know)
* A apply rule under that templates called "load"

Now I create a new template called "load".

The detail area, and call via name `?name=load` will bring up the apply, and not the new template.

Once I edit the apply rule called `load` the cache get's updated and the template can be accessed.

**Comment by Thomas-Gelf** [comment]
@lazyfrosch: can be reproduced, even in the master - thanks for reporting it!

**Comment by Thomas-Gelf** [comment]
@lazyfrosch: should now work as expected. That's been a dangerous one, thanks again! As you mentioned `v1.3.2` I also back-ported it to the `support/1.3` branch.
