### ISSUE TITLE
Host is mandatory for service of a serviceset

### ISSUE THREAD

**Issue by mwaldmueller** [Icinga/icingaweb2-module-director#1097]
## Expected Behavior
A service of a serviceset should not need a Host, because there's a global assign in the serviceset for that. 

## Current Behavior
Currently a Host is mandatory for services in a serviceset. If you set a Host the service is treated as single service.

![bildschirmfoto 2017-08-23 um 08 15 06](https://user-images.githubusercontent.com/3973350/29601444-db33cce6-87db-11e7-8c3a-70e6006cbc15.png)

## Your Environment
* Director version (System - About): master, Git commit: 15c26b97dbe00082a91d7cefb181f53bed47a5ea
* Icinga Web 2 version and modules (System - About): 2.4.1
* Icinga 2 version (`icinga2 --version`): r2.7.0-1
* Operating System and version: CentOS Linux release 7.3.1611 (Core)
* Webserver, PHP versions: PHP 5.4.16

**Comment by Thomas-Gelf** [comment]
@mwaldmueller: thanks for reporting this, should be fixed!
