### ISSUE TITLE
Service sets not visible / editable after creation

### ISSUE THREAD

**Issue by bstorp** [Icinga/icingaweb2-module-director#1098]
Hi,

currently we can not edit service sets. Service sets are not visible in the overview after creation.

## Expected Behavior
Service set should be visible and editable

## Current Behavior
Service set is not listed

## Steps to Reproduce (for bugs)
1. create service set
2. save
3. show overview

## Select on Database
Currently there is only one service set.
MariaDB [<DB>]> select * from icinga_service_set;
+----+------------------+-------------+---------+-------------------------------+--------------------------+
| id | object_name      | object_type | host_id | description                   | assign_filter            |
+----+------------------+-------------+---------+-------------------------------+--------------------------+
|  1 | default-linux | object      |    NULL | Linux Server  | host.vars.os=%22Linux%22 |
+----+------------------+-------------+---------+-------------------------------+--------------------------+
![image](https://user-images.githubusercontent.com/28394117/29605399-ff2e871c-87ea-11e7-97ad-def1763a09e0.png)

## Your Environment
* Director version (System - About): Current commit / master
* Icinga Web 2 version and modules (System - About): 2.4.1
* Icinga 2 version (`icinga2 --version`): r2.7.0-1
* Operating System and version: Ubuntu 16.04
* Webserver, PHP versions: Apache, PHP7

**Comment by Thomas-Gelf** [comment]
This should have been fixed in fc9d40c and related commits. In case you're still facing problems please let me know.
