### ISSUE TITLE
unexpected new sorting in auto-suggestion form element

### ISSUE THREAD

**Issue by vita2** [Icinga/icingaweb2-module-director#1099]
i have discovered an unexpected re-ordering of entries in auto-suggestion form element which is used for imports. after removing any entry there is a alphabetical sorting of all entries.

## Expected Behavior
no new sorting after remove a entry from the import form element.

## Current Behavior
there is a alphabetical sorting of all entries after removing any entry from the import form element.

![removing-a-entry-from-imports-step-1](https://user-images.githubusercontent.com/25298055/29608459-7aa372c8-87f4-11e7-95a1-df1d2106319d.png)
![removing-a-entry-from-imports-step-2](https://user-images.githubusercontent.com/25298055/29608460-7aec7e96-87f4-11e7-9c52-d5d7032d84c8.png)
![removing-a-entry-from-imports-step-3](https://user-images.githubusercontent.com/25298055/29608458-7a9816c6-87f4-11e7-9507-1696a6954047.png)

## Steps to Reproduce (for bugs)
1. create a new host or edit an existing host
2. add few templates which should be imported, at least two entries
3. remove any entry
4. the list will be sorted alphabetically 

## Context
i guess it isn't a desired behavior because it also changes the sequence of imported field values. it could break values which should overwritten by inheritance.

## Your Environment
* Director version (System - About): commit 71ab8b4663b799d45bac42b366d21575fb755d0e master branch
* Icinga Web 2 version and modules (System - About): 2.4.1
* Icinga 2 version (`icinga2 --version`): r2.7.0-1
* Operating System and version: Debian Jessie 8.9 (3.16.0-4-amd64)
* Webserver, PHP versions: nginx 1.6.2-5 + php5-fpm 5.6.30
* Webbrowser: Firefox 55.0.2 (32-Bit)

**Comment by Thomas-Gelf** [comment]
@vita2: thanks for reporting this, can be reproduced.
