### ISSUE TITLE
Agent Tab is shown although not assigned

### ISSUE THREAD

**Issue by vittel1** [Icinga/icingaweb2-module-director#1103]
## Expected Behavior

I followed the documentation: https://github.com/Icinga/icingaweb2-module-director/blob/master/doc/24-Working-with-agents.md

> Once you import the "Icinga Agent" template, you'll see a new "Agent" tab. It tries to assist you with the initial Agent setup by showing a sample config:

## Current Behavior

The "Agent Tab" is shown at all hosts. Just importet a template for the hostalive-check and not a Template or other things where I assigned information about the agent.

When I am running the Powershell Module to configure a client, the Script notice that the Host is not really an agent. That is fine.

I guess maybe you just have to hide the agent tab?

## Your Environment

* Director version (System - About): master, 3c72cb9062dfd714b35b1f83aa672fa0f48bc7b5
* Icinga Web 2 version and modules (System - About): 2.4.1
* Icinga 2 version (`icinga2 --version`):  r2.7.0-1
* Operating System and version: Ubuntu 16.04
* Webserver, PHP versions: Apache2, PHP7

If you need further information, please ask.

**Comment by Thomas-Gelf** [comment]
Plans where to always show this tab and give related instructions, regardless of whether `has_agent` had been enabled or not. It might still need some love, but I'm currently convinced that keeping it always there is the better option. So, I'm rejecting this for now. But please do not hesitate to re-open this or a new related issue in case you don't agree!
