### ISSUE TITLE
Merge policy and filters

### ISSUE THREAD

**Issue by mwaldmueller** [Icinga/icingaweb2-module-director#1104]
When I use a sync rule with update policy "merge" the result isn't as expected when there are changes in my data source.

# Details

## Import source

My import source is a SQL database with the following content:
```
MariaDB [cmdb]> select * from SMT_Hosts;
+----+------------+----------+----------+
| id | hostname   | address  | region   |
+----+------------+----------+----------+
|  1 | testhost01 | 10.0.0.1 | emea     |
|  2 | testhost02 | 10.0.0.2 | apac     |
|  3 | testhost03 | 10.0.0.3 | americas |
|  4 | testhost04 | 10.0.0.4 | typo     |
+----+------------+----------+----------+
```

## Sync rule

My sync rule includes a filter, that should only disable Hosts that are not from region "emea", "apac" or "americas":

![bildschirmfoto 2017-08-24 um 10 08 38](https://user-images.githubusercontent.com/3973350/29656248-39824a9c-88b4-11e7-8cf9-0db4712a885d.png)

![bildschirmfoto 2017-08-24 um 09 51 31](https://user-images.githubusercontent.com/3973350/29655613-e9c2b746-88b1-11e7-8844-5a3a89c33544.png)

## 1st run

The first run of import source and sync rule works as expected:
![bildschirmfoto 2017-08-24 um 09 55 44](https://user-images.githubusercontent.com/3973350/29655789-6d914e48-88b2-11e7-8ff1-3255e18289e4.png)

* testhost04 is disabled, because it's region is "typo"

## 1st change

The region of testhost01 is changed from "emea" to "typo":
```
MariaDB [cmdb]> select * from SMT_Hosts;
+----+------------+----------+----------+
| id | hostname   | address  | REGION   |
+----+------------+----------+----------+
|  1 | testhost01 | 10.0.0.1 | typo     |
|  2 | testhost02 | 10.0.0.2 | apac     |
|  3 | testhost03 | 10.0.0.3 | americas |
|  4 | testhost04 | 10.0.0.4 | typo     |
+----+------------+----------+----------+
```

## 2nd run

The second run of import source and sync rule works as expected:
![bildschirmfoto 2017-08-24 um 09 59 36](https://user-images.githubusercontent.com/3973350/29655999-2ef426aa-88b3-11e7-90a9-ff2046594c2e.png)

* testhost01 is also disabled, because it's region is "typo"

## 2nd change

The region of testhost01 is changed from "typo" to "apac":
```
MariaDB [cmdb]> select * from SMT_Hosts;
+----+------------+----------+----------+
| id | hostname   | address  | REGION   |
+----+------------+----------+----------+
|  1 | testhost01 | 10.0.0.1 | apac     |
|  2 | testhost02 | 10.0.0.2 | apac     |
|  3 | testhost03 | 10.0.0.3 | americas |
|  4 | testhost04 | 10.0.0.4 | typo     |
+----+------------+----------+----------+
```

## 3rd run

The third run of import source and sync rule doesn't work as expected:
![bildschirmfoto 2017-08-24 um 10 03 59](https://user-images.githubusercontent.com/3973350/29656102-9481e548-88b3-11e7-9305-5287e9ddb339.png)

* Only the region of testhost01 is changed, but it's still disabled

## Tests

I added a reverse filter in order to enable Hosts with region "emea", "apac" or "americas", but also without success:

![bildschirmfoto 2017-08-24 um 10 17 22](https://user-images.githubusercontent.com/3973350/29656686-7a5a72b4-88b5-11e7-94ff-b3e08631a131.png)

## Environment
* Director version (System - About): master and 1.3.2
* Icinga Web 2 version and modules (System - About): 2.4.1
* Icinga 2 version (`icinga2 --version`): r2.7.0-1
* Operating System and version: CentOS Linux release 7.3.1611 (Core)
* Webserver, PHP versions: PHP 5.4.16

**Comment by mkayontour** [comment]
same issue, I'm having with the vsphere import. Object's which are no longer available or shouldn't be available through the filter won't get modified or deleted.

**Comment by Thomas-Gelf** [comment]
@mwaldmueller: your configuration looks good, I'll try to reproduce this.

@mkayontour: I guess you're describing something different. @mwaldmueller is talking about the filter on a single Sync property, you're talking about filtering at Sync rule level. These are completely different beasts.

The "Sync" filter makes Sync blind for all but matching elements. So it doesn't even look at non-matching elements - and they would never be purged. At the moment, this is how it works. I'll have a look, but I'm not sure whether it would be possible to change this.

When having the requirement to filter imported data, this should happen at import time. Sync is too late in the game here. So, just in case @mwaldmueller would need to do something as you're asking for, for his query this would mean to configure:

    SELECT * FROM SMT_Hosts WHERE REGION IN ('emea', 'apac', ...);

This way, purge works perfectly. As the vmware module doesn't allow to filter imported data, please open a dedicated feature request for the related project.

Cheers,
Thomas

**Comment by Thomas-Gelf** [comment]
@mwaldmueller: this was a tricky one, thanks for reporting it. I double-checked, it should only have had effect on the `disabled` property as it is the only property carrying a `default` value (`n` instead of `null`) in our sync-able objects. Please let me know whether your problem is now fixed!

**Comment by Thomas-Gelf** [comment]
@mwaldmueller: I pushed it to the support/1.3 branch. I'll not re-tag 1.3.2 as that would lead to confusion, but we could eventually release 1.3.3 shortly after 1.4.0 if you want. Anyways, it's absolutely safe to use `support/1.3`.

Cheers,
Thomas
