### ISSUE TITLE
Own Command: Argument is not transfer to Command

### ISSUE THREAD

**Issue by vittel1** [Icinga/icingaweb2-module-director#1106]
## Current Behavior

The Agent on the Windows-Host do not get the value of the argument (e.g Watchdog).

Command:
```
zones.d/director-global/commands.conf

object CheckCommand "Windows-Check-Process" {
    import "plugin-check-command"
    command = [
        "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
        "-ExecutionPolicy",
        "ByPass",
        "-NonInteractive",
        "-NoProfile",
        "-Command",
        "C:\\PROGRA~2\\ICINGA2\\sbin\\windows_check_process.ps1"
    ]
    timeout = 30s
    arguments += {
        processname = {
            required = false
            value = "$win_proc_name$"
        }
    }
}
```
Service-Template
```
template Service "Windows-Watchdog-Template" {
    check_command = "Windows-Check-Process"
    max_check_attempts = "3"
    check_interval = 1m
    retry_interval = 30s
    command_endpoint = host_name
    vars.win_proc_name = "watchdog"
}
```
Serivce-Apply
```
zones.d/director-global/service_apply.conf

apply Service "Windows-Watchdog" {
    import "Windows-Watchdog-Template"

    assign where host.name == "HOSTNAME"

    import DirectorOverrideTemplate
}
```
Plugin-Output

> Get-Process : Cannot find a process with the name "processname".

## Your Environment

* Director version (System - About): master, 71ab8b4663b799d45bac42b366d21575fb755d0e 
* Icinga Web 2 version and modules (System - About): 2.4.1
* Icinga 2 version (`icinga2 --version`): r2.7.0-1
* Operating System and version: Ubuntu 16.04.1
* Webserver, PHP versions: Apache2, PHP7

**Comment by Thomas-Gelf** [comment]
Are you sure that you want to call it this way:

    windows_check_process.ps1 processname watchdog

What does your `windows_check_process.ps1` look like?

**Comment by vittel1** [comment]
You are totally right...silly mistake...

I changed the argument name to "-processname" and not it works.

Thanks for your help!

**Comment by Thomas-Gelf** [comment]
You're welcome!
