### ISSUE TITLE
Unable to create host template

### ISSUE THREAD

**Issue by sysadmama** [Icinga/icingaweb2-module-director#1108]
I killed my test setup with mixing branches, so I started from scratch: new git clone, new database, new kickstart. Now I'd like to create a first host template, but that's not possible because I... well, should create a host template fist. (Clicking next leads to "No Host template has been chosen". Haha.)

Cheers,
  Marianne

![screen shot 2017-08-24 at 21 11 30](https://user-images.githubusercontent.com/11242139/29684200-6b5e0008-8911-11e7-9874-2770628a9263.jpg)

## Expected Behavior

I'd like to see a host template form.

## Current Behavior

Recursive prompt.

## Your Environment

* Director version (System - About): f55a672d48235bf6ef18af303e299bc11b3a46ff
* Icinga Web 2 version and modules (System - About): eb343009bb696e155897dda4decef532242cf9fa
* Icinga 2 version (`icinga2 --version`): 2.7.0-1
* Operating System and version: Debian 8
* Webserver, PHP versions: apache2, php5-5.6.30

**Comment by Thomas-Gelf** [comment]
@sysadmama: sorry for this, got broken when I pushed some changes a few hours ago!
