### ISSUE TITLE
Field "Zone" from Host missing in Director

### ISSUE THREAD

**Issue by cptnkoiz** [Icinga/icingaweb2-module-director#1110]
## Expected Behavior
There is a Field with the Name "Zone" where a Host can be placed in the correct Zone

## Current Behavior
The Field is missing
![bildschirmfoto 2017-08-25 um 10 58 01](https://user-images.githubusercontent.com/24245068/29707118-73294cb6-8984-11e7-9e45-689852cfa91a.png)

## Your Environment

* Director version (System - About): Master
* Icinga Web 2 version and modules (System - About): 2.4.1
* Icinga 2 version (`icinga2 --version`): 2.7.0
* Operating System and version: CentOS7
* Webserver, PHP versions: Apache2/HTTPD

**Comment by Thomas-Gelf** [comment]
@cptnkoiz: thanks for reporting this, should now be available again.

**Comment by cptnkoiz** [comment]
Works again! Need to send some Gin to Nürnberg ;D 🥇

**Comment by Thomas-Gelf** [comment]
Just go ahead, our Gin pipes are wide open :laughing: Glad to hear that it works, sorry for accidentally dropping this.
