### ISSUE TITLE
Service Overrides are not saved

### ISSUE THREAD

**Issue by cptnkoiz** [Icinga/icingaweb2-module-director#1111]
## Expected Behavior
Overrides are changed and by clicking on "Override vars" saved
## Current Behavior
Changes are somehow not recognized, therefore no changin/setting of overrides not possible

## Steps to Reproduce (for bugs)
1. 
![bildschirmfoto 2017-08-25 um 11 13 52](https://user-images.githubusercontent.com/24245068/29707752-bb35d41e-8986-11e7-9f58-42491d64c325.png)

2. Change or set new Overrides
![bildschirmfoto 2017-08-25 um 11 14 13](https://user-images.githubusercontent.com/24245068/29707755-bee0ea7c-8986-11e7-9739-1be1e923655f.png)

3. After clicking on "Override vars" the system tells me that nothing has changed
![bildschirmfoto 2017-08-25 um 11 14 22](https://user-images.githubusercontent.com/24245068/29707765-c58f0174-8986-11e7-9583-59c30a321eb0.png)

4. back where we started  ¯\_(ツ)_/¯
![bildschirmfoto 2017-08-25 um 11 14 27](https://user-images.githubusercontent.com/24245068/29707774-ceb0689c-8986-11e7-9f5b-a507a59e4298.png)

## Your Environment

* Director version (System - About): Master
* Icinga Web 2 version and modules (System - About): 2.4.1
* Icinga 2 version (`icinga2 --version`):2.7.0
* Operating System and version:CentOS7
* Webserver, PHP versions:Apache2/HTTPD
* Browser: Chrome60 Windows/Mac, FF (recent), IE11, Edge

**Comment by Thomas-Gelf** [comment]
Can be reproduced, thanks for reporting this!

**Comment by Tuxdiver** [comment]
Can I upvote this issue to be looked at earlier? Currently this really bites me...

**Comment by sysadmama** [comment]
+1
