### ISSUE TITLE
API call GET config/activities deploys the config

### ISSUE THREAD

**Issue by matthenningDBK** [Icinga/icingaweb2-module-director#1113]
## Expected Behavior

Return pending changes

## Current Behavior

Pending changes are deployed

## Steps to Reproduce (for bugs)

`curl -H 'Accept: application/json' -u 'director:*******' 'https://hostname/icingaweb2/director/config/activities'`

## Context

Calling the endpoint `GET director/config/activities` should show pending changes or at least the amount of pending changes.
Currently calling `GET director/config/activities` (or `GET director/config/deployments`) triggers a config deployment.
This shouldn't happen with GET requests in the first place.

## Your Environment

* Director version (System - About): master (commit 71ab8b4)
* Icinga Web 2 version and modules (System - About): 2.4.1
* Icinga 2 version (`icinga2 --version`): r2.7.0-1
* Operating System and version: SLES 12-SP2
* Webserver, PHP versions: Apache2, PHP 5.5.14

**Comment by Thomas-Gelf** [comment]
@matthenningDBK: config/activities is not yet available through the API, a related feature request should already exist. The deployment should not happen at all, will be fixed immediately.
