### ISSUE TITLE
Director Job Problem (probably caused by sync rule)

### ISSUE THREAD

**Issue by sysadmama** [Icinga/icingaweb2-module-director#1114]
Hi,

we're successfully using our Director Jobs for months now, but one of the last git pulls (I'm not sure which; problem started on 2017/08/11 ~11h00) broke them. The configured jobs are

1. Import: imports users from a LDAP source
2. Sync: every user imported from LDAP should now import a specified user template (update policy *merge*)
3. Deploy: rendering is not forced, but modified config gets deployed

So what's happening now?
* Director shows me hundreds of un-deployed changes
* These changes are always referencing the user template import; the "former object" supposedly imports two templates (namely the template defined in sync rule (LDAP template) AND **its** import (the Base User Template)), the "new object" only imports the template defined in sync rule (LDAP template)

### Former object
```
object User "marianne" {
  import "Generic User"
  import "LDAP Mitarbeiter"

  display_name = "Marianne Spiller"
  email = "blablabla"
  vars.fachbereich = "ISG"
}
```

### New object
```
object User "marianne" {
  import "LDAP Mitarbeiter"
    
  display_name = "Marianne Spiller"
  email = "blablabla"
  vars.fachbereich = "ISG"
}
```

* The deploy job seems to run - at least the time stamp on *last attempt succeeded*  is okay - and nothing gets deployed
* When I deploy manually, it succeeds and the next sync run triggers hundreds of changes again - >500 when looking at the bubble in the sidebar, >1200 when looking at "check for changes" in sync rule (which is also confusing)
* The manually triggered deploys all have the same ID (see screenshot)

I'm stuck at the moment; do you have an idea what could cause this - and where to start debugging?

Cheers,
  Marianne

![screen shot 2017-08-25 at 11 58 45](https://user-images.githubusercontent.com/11242139/29709535-ef714726-898c-11e7-8065-09b593286863.jpg)

## Your Environment

* Director version (System - About): e05c3a8556ad1451921b92efaa9f5b01b0a9389a but started on 2017/08/11
* Icinga Web 2 version and modules (System - About): b7639651e80e85b81d9fb92c1db77e90c3754d2d
* Icinga 2 version (`icinga2 --version`): r2.7.0-1
* Operating System and version: Ubuntu 16.04.3 LTS
* Webserver, PHP versions: 2.4.18 / 7.0.22

**Comment by Thomas-Gelf** [comment]
@sysadmama: could you please try to check out 94ac505 and let me know whether it behaves different?

**Comment by Thomas-Gelf** [comment]
In the meantime, I'll follow another suspicion that might be related...

**Comment by Thomas-Gelf** [comment]
@sysadmama: could you please pull the current master and try again?

**Comment by sysadmama** [comment]
@Thomas-Gelf: I pulled current master. It seems to work now, but on an Friday evening I'm a bit unmotivated to do tests with comprehensive LDAP changes, so I'll observe until next week...

Question to inconsistent timestamps:
* **Import:** This Import Source was last found to be in sync at 2017-08-25 22:24:59.
* **Sync:** This Sync Rule was last found to by in Sync at 2017-08-25 **11:57:42**.

When looking at Automation / Import source / Sync rules:
```
Last sync run details
Start time          2017-08-25 11:57:42
```

When looking at the jobs:
* **Import:** The last attempt succeeded at 2017-08-25 22:24:59
* **Sync:** The last attempt succeeded at 2017-08-25 **22:25:08**
* **Render config/ deploy:** The last attempt succeeded at 2017-08-25 22:25:14

Who's the liar? When manually "Check for changes", timestamp in Sync rule tab is updated to current time.
