### ISSUE TITLE
Kickstart wizard tells he is not prepared for deployment even during later runs

### ISSUE THREAD

**Issue by dgoetz** [Icinga/icingaweb2-module-director#1116]
## Expected Behavior
No warning banner is shown after configuration.

## Current Behavior
Banner tells you the installation is not prepared for deployment, but running imports and deployment works fine.
![grafik](https://user-images.githubusercontent.com/3658213/29713003-e7d7631e-899c-11e7-86f6-11a6d98a88af.png)

## Your Environment
* Director version (System - About): 1.3.1+
* Icinga Web 2 version and modules (System - About): 2.4.1
* Icinga 2 version (`icinga2 --version`): 2.7.0

**Comment by Thomas-Gelf** [comment]
Hehe... this text has been written at times when it wasn't possible to re-run the Kickstart :D Thanks for pointing this out, will be addressed.

**Comment by Thomas-Gelf** [comment]
Oops
