### ISSUE TITLE
Config preview of ApiUsers fails

### ISSUE THREAD

**Issue by mwaldmueller** [Icinga/icingaweb2-module-director#1117]
Config preview of users fails:

![bildschirmfoto 2017-08-25 um 14 46 56](https://user-images.githubusercontent.com/3973350/29714639-5eca8e40-89a4-11e7-8e49-263f19b5abc0.png)

## Environment
Director version (System - About): master, Git commit: 1a08b90c7a43a190c15e544f1602aa6e7cc821dd
Icinga Web 2 version and modules (System - About): 2.4.1
Icinga 2 version (icinga2 --version): r2.7.0-1
Operating System and version: CentOS Linux release 7.3.1611 (Core)
Webserver, PHP versions: PHP 5.4.16

**Comment by Thomas-Gelf** [comment]
Thanks for pointing this out!
