### ISSUE TITLE
missing column headings in usage tables

### ISSUE THREAD

**Issue by vita2** [Icinga/icingaweb2-module-director#1119]
it's just a small ui issue. there are no column headings at the new usage tables. i've seen the headings in your last blog post at the netways website so i guess you only have forgotten to push some code :wink: 

## Expected Behavior
![director_service-template-usage](https://user-images.githubusercontent.com/25298055/29715791-0ee87e82-89a9-11e7-9c5d-82f33dba6027.png)

## Current Behavior
![usage-tables-missing-column-headings](https://user-images.githubusercontent.com/25298055/29715790-0ee75cdc-89a9-11e7-862f-3d96f2e7d619.png)

## Your Environment
* Director version (System - About): commit f8445ca1ef0ac2c4fdec29bc225900086429af42 master branch
* Icinga Web 2 version and modules (System - About): 2.4.1
* Icinga 2 version (`icinga2 --version`): r2.7.0-1
* Operating System and version: Debian Jessie 8.9 (3.16.0-4-amd64)
* Webserver, PHP versions: nginx 1.6.2-5 + php5-fpm 5.6.30

**Comment by Thomas-Gelf** [comment]
@vita2: thanks a lot, you're right!
