### ISSUE TITLE
service sets: custom properties won't show

### ISSUE THREAD

**Issue by vita2** [Icinga/icingaweb2-module-director#1121]
i have created a service set for several mysql checks and added it to some hosts. currently it isn't possible anymore to change the custom properties of single services which was applied using the service set. the fields for the custom properties won't show.

![service-set-01](https://user-images.githubusercontent.com/25298055/29741551-99999680-8a6f-11e7-8d4a-43a9a5091086.png)

![service-set-02](https://user-images.githubusercontent.com/25298055/29741552-999c4eca-8a6f-11e7-9ad6-12e59af5b53c.png)

if a service was add with a apply-rule it's still possible to override certain custom properties. so it seems the issue exists only with service sets.

## Steps to Reproduce (for bugs)
1. create a service template
2. add some fields to the template
3. create a service set with certain services (at least one service should have a custom field)
4. add the service set to a host (host -> tab: "Services" -> button "Add service set")
5. try to override a property of a service from the service set at the services tab

## Your Environment
* Director version (System - About): commit da2968a6d3657e20a5695823a80f9f29e6c13e56 master branch
* Icinga Web 2 version and modules (System - About): 2.4.1
* Icinga 2 version (`icinga2 --version`): r2.7.0-1
* Operating System and version: Debian Jessie 8.9 (3.16.0-4-amd64)
* Webserver, PHP versions: nginx 1.6.2-5 + php5-fpm 5.6.30

**Comment by Thomas-Gelf** [comment]
@vita2: while I'm still working on an issue with variable overrides (#1111), they should at least be shown for sets. Are you sure that this is da2968a6? Because then the text with the light blue background should show the name of the set with a link pointing to that set.

**Comment by vita2** [comment]
oh, justified doubts 😨  i guess i copied the commit checksum in the same moment while you have uploaded your last changes.

meanwhile i can see the link which is pointing to the service-set but the fields for the custom properties are still missing. it only affects service sets. fields of applied and individual services can be overriden.

**Comment by vita2** [comment]
it's strange. i've created another service set for two services regarding nginx.

one of them shows the service properties. at the other service i can't see any properties.

here are some screenshots of my service set, called "nginx".

- service set assignment rule:
![service-set-assign-rule](https://user-images.githubusercontent.com/25298055/30268580-7e9df47e-96e6-11e7-8eee-b1db22f4152c.png)
- services (members) of service set:
  - nginx-status
  - procs-nginx

  ![service-set-services](https://user-images.githubusercontent.com/25298055/30268582-7ed2e652-96e6-11e7-9650-ea729a10b568.png)
- services with custom properties:
  - nginx-status
![service-set-service-nginx-status](https://user-images.githubusercontent.com/25298055/30268579-7e9974da-96e6-11e7-8a6b-452d64d6b12c.png)
  - procs-nginx
![service-set-service-procs-nginx](https://user-images.githubusercontent.com/25298055/30269557-7ca48090-96e9-11e7-8168-e08c70462813.png)
- now have a look to a host which gets the service set in cause of the assignment rule:
![host-applied-service-set](https://user-images.githubusercontent.com/25298055/30268577-7e95a116-96e6-11e7-96d3-f153696d56ea.png)
  - try to edit custom properties
    - nginx-status
![host-applied-service-nginx-status](https://user-images.githubusercontent.com/25298055/30268576-7e92b2d0-96e6-11e7-96e3-342cb0db9c94.png)
    - procs-nginx
![host-applied-service-procs-nginx](https://user-images.githubusercontent.com/25298055/30269940-128737d2-96eb-11e7-99f7-74def4a05999.png)

finally, the service configuration created by the director (424fc3136356f6725505567d37f7d4b7ce71fe46):
```
zones.d/director-global/servicesets.conf
/** Service Set 'nginx' **/

apply Service "nginx-status" {
    import "nginx-status"

    assign where "nginx" in host.vars.tags
    vars.tags = [ "web" ]

    import DirectorOverrideTemplate
}

apply Service "procs-nginx" {
    import "procs"

    assign where "nginx" in host.vars.tags
    vars.procs_argument = "/usr/sbin/nginx"
    vars.procs_command = "nginx"
    vars.procs_critical = "1:1"
    vars.tags = [ "web" ]

    import DirectorOverrideTemplate
}
```
```
zones.d/director-global/service_templates.conf
template Service "nginx-status" {
    import "generic-service-template"

    check_command = "nginx_status"
    enable_notifications = true
    enable_perfdata = true
    command_endpoint = host_name
    vars.nginx_status_disable_sslverify = true
    vars.nginx_status_host_address = "localhost"
    vars.nginx_status_port = 8888
    vars.nginx_status_url = "/nginx_status"
    vars.tags = [ "web" ]
}

template Service "procs" {
    import "generic-service-template"

    check_command = "procs"
    enable_notifications = true
    enable_perfdata = true
    command_endpoint = host_name
}

template Service "generic-service-template" {
    max_check_attempts = "3"
    check_period = "24x7"
    check_interval = 5m
    retry_interval = 1m
    enable_notifications = false
    enable_active_checks = true
    enable_passive_checks = false
    enable_event_handler = false
    enable_perfdata = false
    volatile = false
    icon_image = "services"
}
```

**Comment by vita2** [comment]
i've found out that it will work if there is a service template with same name as the service. the properties are visible after linking all the needed fields to the new template "procs-nginx".

btw ... in services tab i can see the two services (nginx-status and procs-nginx) as unassigned services. when choosing the procs-nginx service i get the error:
```
Failed to load icinga_service for host_id IS NULL AND service_set_id IS NULL AND object_name = 'procs-nginx' AND object_type = 'template'
```

it's gone once the above-named service template was created. so i guess the problem is related to issue #1170 and #1172.

**Comment by Thomas-Gelf** [comment]
@vita2: thanks for the hint with the "template name fitting the service", I'll try to reproduce this.

Regarding that error, formerly it could have happened to generate invalid services, being neither a template nor a host object or set member. Director is now more strict about this and also shows invalid services. I'll fix #1172, the problem there is that this strictness now doesn't even allow one to access those services :laughing:

Could you please let me have more details related to your services? The output of the following queries would be helpful:

```sql
SELECT id, object_name, object_type, host_id, service_set_id
  FROM icinga_service WHERE object_name like '%nginx%';
SELECT si.* FROM icinga_service_inheritance si
  JOIN icinga_service s ON s.id = si.parent_service_id OR s.id = si.service_id
  WHERE s.object_name like '%nginx%';
```

**Comment by vita2** [comment]
sure, here is the output:
```sql
SELECT id, object_name, object_type, host_id, service_set_id
  FROM icinga_service WHERE object_name like '%nginx%'
```
id | object_name | object_type | host_id | service_set_id
------------ | ------------- | ------------- | ------------- | -------------
63 | nginx-status | template | NULL | NULL
166 | nginx-status | object | NULL | 2
171 | procs-nginx | object | NULL | 2
```sql
SELECT si.* FROM icinga_service_inheritance si
  JOIN icinga_service s ON s.id = si.parent_service_id OR s.id = si.service_id
  WHERE s.object_name like '%nginx%';
```
service_id | parent_service_id | weight
------------ | ------------- | -------------
63 | 1 | 1
63 | 161 | 2
166 | 63 | 1
166 | 63 | 1
171 | 8 | 1

and here the remaining two parent services with id 1, 8 and 161: 
```sql
SELECT id, object_name, object_type, host_id, service_set_id
  FROM icinga_service WHERE id in (1, 8, 161);
```
id | object_name | object_type | host_id | service_set_id
------------ | ------------- | ------------- | ------------- | -------------
1 | generic-service-template | template | NULL | NULL
8 | procs | template | NULL | NULL
161 | Slow checks (5m) | template | NULL | NULL

**Comment by Thomas-Gelf** [comment]
Thanks, one more please:

```sql
SELECT sf.service_id, sf.is_required, sf.var_filter, df.varname
  FROM icinga_service_field sf JOIN director_datafield df ON df.id = sf.datafield_id
  WHERE sf.service_id IN (1, 8, 63, 161, 166, 171);
```

In case you defined those fields on your command, it would be great to see them too.

**Comment by vita2** [comment]
```sql
SELECT sf.service_id, sf.is_required, sf.var_filter, df.varname
  FROM icinga_service_field sf JOIN director_datafield df ON df.id = sf.datafield_id
  WHERE sf.service_id IN (1, 8, 63, 161, 166, 171);
```

service_id | is_required | var_filter | varname
-- | -- | -- | --
1 | n | NULL | tags
8 | n | NULL | procs_argument
8 | n | NULL | procs_command
8 | n | NULL | procs_critical
8 | n | NULL | procs_user
63 | n | NULL | nginx_status_critical
63 | n | NULL | nginx_status_disable_sslverify
63 | n | NULL | nginx_status_host_address
63 | n | NULL | nginx_status_port
63 | n | NULL | nginx_status_servername
63 | n | NULL | nginx_status_ssl
63 | n | NULL | nginx_status_url
63 | n | NULL | nginx_status_warn

the commands of these services are external commands. i know it is possible but until now i didn't add the fields to external commands. just to service-/host-templates 😃

**Comment by Thomas-Gelf** [comment]
@vita2: hard to track down, but easy to fix. At least I hope so ;-) Please let me know whether it now works as expected.

**Comment by vita2** [comment]
great, you've fixed it! thanks a lot 😃🍻

**Comment by Thomas-Gelf** [comment]
Glad to hear that, thank you for your help and patience!
