### ISSUE TITLE
running icingacli director kickstart run fails

### ISSUE THREAD

**Issue by paladox** [Icinga/icingaweb2-module-director#1123]
## Expected Behavior
I am really unsure what it should look like, but looks like this is an error.

## Current Behavior
root@gerrit-mysql:/etc/icinga2/conf.d# icingacli director kickstart run
ERROR: Icinga\Exception\IcingaException in /usr/share/icingaweb2/modules/director/library/Director/Data/Db/DbObject.php:794 with message: Storing icinga_apiuser[] failed: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'object_name' cannot be null, query was: INSERT INTO icinga_apiuser (object_name, object_type, disabled, password, client_dn, permissions) VALUES (?, ?, ?, ?, ?, ?) {array (
  'id' => NULL,
  'object_name' => NULL,
  'object_type' => 'external_object',
  'disabled' => 'n',
  'password' => NULL,
  'client_dn' => NULL,
  'permissions' => NULL,
)}
## Steps to Reproduce (for bugs)

1. run on a brand new icinga master host, setup the director, icinga2 and icingaweb2 db's.
2. run icingacli director kickstart run
3.
4.

## Your Environment

* Director version (System - About):
* Icinga Web 2 version and modules (System - About):
* Icinga 2 version (`icinga2 --version`):
* Operating System and version:
* Webserver, PHP versions:

php is php7.0

os is debian stretch

icinga2 version: r2.7.0-1

icingaweb2 version 2.4.1

webserver is apache2.

**Comment by Thomas-Gelf** [comment]
@paladox: guess you missed the [documentation](https://github.com/Icinga/icingaweb2-module-director/blob/master/doc/03-Automation.md#kickstart-an-empty-director-database) part mentioning `kickstart.ini`?

**Comment by paladox** [comment]
thanks. it now works.
