### ISSUE TITLE
External defined zones are not visible

### ISSUE THREAD

**Issue by mwaldmueller** [Icinga/icingaweb2-module-director#1125]
External defined zones are not visible:

![bildschirmfoto 2017-08-28 um 08 58 02](https://user-images.githubusercontent.com/3973350/29762518-1e0a5994-8bcf-11e7-86f9-74905b2aff5d.png)

# Environment
Director version (System - About): master, Git commit: fc9d40ceff5d51546de10b5d2c14d1825f596d25
Icinga Web 2 version and modules (System - About): 2.4.1
Icinga 2 version (icinga2 --version): r2.7.0-1
Operating System and version: CentOS Linux release 7.3.1611 (Core)
Webserver, PHP versions: PHP 5.4.16

**Comment by Thomas-Gelf** [comment]
@mwaldmueller: thanks!
