### ISSUE TITLE
Sync Rule: Sync delete a Host will raise SQL Exception

### ISSUE THREAD

**Issue by Naro370** [Icinga/icingaweb2-module-director#1126]
My Windows Active Directory (LDAP) sync rule have no problems with new hosts or modifed host, but when I delete a host it will fail with following error:
``
This Sync Rule failed when last checked at 2017-08-28 10:19:09: Exception while syncing Icinga\Module\Director\Objects\IcingaHost <hostname>: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails ("icinga_director"."icinga_hostgroup_host_resolved", CONSTRAINT "icinga_hostgroup_host_resolved_host" FOREIGN KEY ("host_id") REFERENCES "icinga_host" ("id") ON DELETE CASCADE ON UPDATE CASCADE), query was: INSERT INTO icinga_hostgroup_host_resolved (hostgroup_id, host_id) VALUES (?, ?)
``
## Expected Behavior
Deleting a Host in Windows AD, Sync rule should delete the host in Icinga Director.

## Current Behavior
The sync rule fail. Then I have to manuel delete the hosts in Icinga Director (without any errors). Then the sync rule works again, because no more changes are necessary.

## Steps to Reproduce (for bugs)
1. Create Import source with LDAP to an Windows AD (keycolumname: dnshostname, Objectclass: computer, properties: cn, dnshostname, operatingSystem, operatingSystemVersion, distinguishedName)
2. Lets assume you see HostA and HostB in the Preview
3. Create Sync rule for Hosts and create some properties
4. Trigger this Sync (this should create HostA and HostB)
5. Delete HostB in Windows AD
6. Trigger Import Source
7. Preview should now only show HostA
8. Trigger Sync Rule -> Error

## Your Environment
* Director version: master (last update: 27.08.2017)
* Icinga Web 2 version and modules: 2.4.1-2.stretch
* Icinga 2 version: 2.7.0-1.stretch
* Operating System and version: Debian 9 (stretch)
* Webserver, PHP versions: Apache 2.4.25-3+deb9u2, PHP 7.0.19-1

**Comment by Thomas-Gelf** [comment]
Should not happen, I'll try to reproduce this

**Comment by magheinz** [comment]
Something is realy broken with imports from external databases.
This problem only exists if a host is a hostgroup-member.

**Comment by Thomas-Gelf** [comment]
@Naro370: I tried hard to reproduce this, but failed. Still, I absolutely believe you that the issue exists, as I have seen something similar before. Do you (or @magheinz) have any idea that could help me? How did you configure related host groups? Via apply rule or directly on the object, manually or via sync? I tried to combine quite some variants, but "unfortunately" it always worked fine for me.

Thanks,
Thomas

**Comment by Naro370** [comment]
Thanks for testing this. I also tried to dig in deeper into this.
What I forgot to say:
I also have a Hostgroup "windows-servers" which have this assign filter: "host.vars.os=Windows Server *"
The custvariable "os" will be filled from the sync with the Windows AD variable ${operatingSystem}

But I don't understand the stacktrace at this point:
", query was: INSERT INTO icinga_hostgroup_host_resolved (hostgroup_id, host_id) VALUES (?, ?)"
Why hey try a INSERT INTO when he want to delete the host and why he tries to add "?" as a value?
I don't know the code exactly, but maybe hey delete the host and after this he try to assign the hostgroup to a host that doesn't exists anymore?

**Comment by Thomas-Gelf** [comment]
@Naro370: I tried something similar, had a an assign filter based on `address`, with `address` being filled via Sync. Will try again with a custom variable, should not differ - but who knows, there is a lot of caching involved. `?` is just a placeholder, you do not see the real value here. The host is definitively going to be deleted. Those `*_resolved`-tables are there to speed up things, otherwise it wouldn't be able to provide permissions based on hostgroups with those groups being dynamically assigned. So, when changing a host or a hostgroup, filters are re-evaluated for all possible candidates.

As this would hurt badly when executed for every single object on sync, it is deferred and happens just once after sync occurred. And it usually seems to work fine, but there must be an issue with this I'm unable to see right now. Definitively somehow related to Caching, thanks for the hint with the assign based on the Custom Variable, that could explain it. CustomVariables have their own cache... just - this shouldn't matter at all, as the host should be killed. I'll give it a try...

**Comment by Naro370** [comment]
Thanks for that info!
I just tested the other way around, when I delete the host group assign filter the sync can delete the host without any problems.

**Comment by Thomas-Gelf** [comment]
@Naro370: I think I got it. Could you please try as follows:

`library/Director/Objects/GroupMembershipResolver.php`, function `addMembershipWhere`, line 366:

```php
         $ids = array();
         foreach ($objects as $object) {
+            if ($object->shouldBeRemoved()) {
+                continue;
+            }
             $ids[] = (int) $object->get('id');
         }
```

**Comment by Naro370** [comment]
sure, I will try this on monday

**Comment by Naro370** [comment]
@Thomas-Gelf 
I am in sync with master branch, and add this lines. I also recreate the assign rule of the host group, so all dependencies ids are new.
But nothing changed, still the same error msg.

Can I provide you more debug infos?

**Comment by Thomas-Gelf** [comment]
@Naro370: that's not what I wanted to hear :p

**Comment by Naro370** [comment]
Sry ;)
But I just found something.
It is only a problem when it is the only change the sync try to make:
Array
(
    [create] => 0
    [modify] => 0
    [delete] => 1
)

In case of more changes (one create or one modify extra) it run flawless.
example: 2 objects have been modified: 1 created, 1 deleted

**Comment by Thomas-Gelf** [comment]
Yeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeah :stuck_out_tongue_closed_eyes: :stuck_out_tongue_closed_eyes: :stuck_out_tongue_closed_eyes:

**Comment by Naro370** [comment]
I can confirm that fix 👍 
Thank you very much.
