### ISSUE TITLE
nscp-local arguments "-a" error

### ISSUE THREAD

**Issue by lamaratonaug** [Icinga/icingaweb2-module-director#1127]
With Director I'm trying to add 2 arguments (warning, critical), but it always has an error

## Expected Behavior

Set in nscp_arguments

warn=uptime<7d crit=uptime<60h 

error : 
Plugin Output
Failed to validate filter see log for details: Warning expression is not valid

## Current Behavior

I cannot enter 2 arguments in the same field "-a"

## Possible Solution
nothing !

## Your Environment

* Director version (System - About): 1.3.1
* Icinga Web 2 version and modules (System - About): 2.7
* Icinga 2 version (`icinga2 --version`): 2.7
* Operating System and version: debian 8
* Webserver, PHP versions: Apache/2.4.25

**Comment by lamaratonaug** [comment]
![image 2](https://user-images.githubusercontent.com/5113761/29771493-60c2eb5a-8bf4-11e7-9698-c04a49a93013.jpg)

**Comment by vita2** [comment]
you have to set the data type of your custom field to array. after that you can add multiple arguments for nscp.

example:
```
object Service "nscp-XYZ" {
  ...
  vars.nscp_arguments = [ "warn=uptime<7d", "crit=uptime<60h" ]
}
```

**Comment by lamaratonaug** [comment]
Should I not use the default "nscp_arguments" custom field of the nsp-local-uptime command?

**Comment by lazyfrosch** [comment]
You have to change the data type of that field to `Array`, so you can fill in multiple arguments

**Comment by lazyfrosch** [comment]
Unfortunately this is not selectable on field creation from commands right now

**Comment by lamaratonaug** [comment]
Fantastic !!! work !!! thank youuu
