### ISSUE TITLE
template choices: error message in activity log

### ISSUE THREAD

**Issue by vita2** [Icinga/icingaweb2-module-director#1129]
i'm testing the new template-choices and it seems i've found a dead link in the activity log. i have created a choice for host templates and tried to see the corresponding entry in the activity log.

## Expected Behavior
i expected to see some details and have the possibility to undo the changes. a config diff would be nice but it isn't absolutely necessary.

## Current Behavior
clicking the name of the host template choice shows a "page not found" message:
![activity-log-host-template-choices-02](https://user-images.githubusercontent.com/25298055/29811873-303ced30-8ca5-11e7-81e3-011b4f28c75d.png)

another click on the entry line throws the following error:
```
Fatal error: Class 'Icinga\Module\Director\Objects\IcingaHost_template_choice' not found in /usr/share/icingaweb2/modules/director/library/Director/Objects/IcingaObject.php on line 2334
```
![activity-log-host-template-choices-01](https://user-images.githubusercontent.com/25298055/29811872-303c650e-8ca5-11e7-816f-b5cb1c458f41.png)

## Steps to Reproduce (for bugs)
1. create a host or a service template choice
2. switch to the activity log and try to view the details of the changes

## Your Environment
* Director version (System - About): commit da2968a6d3657e20a5695823a80f9f29e6c13e56 master branch
* Icinga Web 2 version and modules (System - About): 2.4.1
* Icinga 2 version (`icinga2 --version`): r2.7.0-1
* Operating System and version: Debian Jessie 8.9 (3.16.0-4-amd64)
* Webserver, PHP versions: nginx 1.6.2-5 + php5-fpm 5.6.30

**Comment by Thomas-Gelf** [comment]
Should be fixed. In addition to this, there are more places in activity log that might lead to a dead place. So we should better link to an intermediate page first, whose responsibility would be to first check whether the target is available and then decide whether to immediately redirect or whether to show a nice and helpful error message like "The object you're trying to reach does no longer exist".

**Comment by Thomas-Gelf** [comment]
Fixing just the error for now, restore will not work as expected - it will restore an empty Choice. In case you want that too, it would be great if you could open a dedicated issue. It's a little bit tricky, as this must check for conflicts: an involved template might make part of another choice in the meantime.
