### ISSUE TITLE
View only role is not configurable

### ISSUE THREAD

**Issue by tobiasvdk** [Icinga/icingaweb2-module-director#1132]
I try to configure a role which is able to only view the director config.
```none
[user]
users = "user"
permissions = "module/director, director/showconfig, module/monitoring"
```

## Expected Behavior
The user "user" should see the configuration.

## Current Behavior
The user "user" gets the error message "No dashboard available, you might have not enough permissions" when accessing the director module.

## Steps to Reproduce (for bugs)

1. Create a user
2. Create a role and add the new user to this role
3. Configure the following permissions
3.1 module/director
3.2 director/showconfig
3.3 module/monitoring
4. Log in as user

## Your Environment

* Director version (System - About): a9b562421275d250eb071547eac7ba062b70a848
* Icinga Web 2 version and modules (System - About): 2.4.1
* Icinga 2 version (`icinga2 --version`): 2.6.3
* Operating System and version:
* Webserver, PHP versions:

**Comment by fl0wx** [comment]
Are there any news? Im facing the same issue

**Comment by Thomas-Gelf** [comment]
`showconfig` is not a "view only" permission, as it's description says:

> Allow to show configuration (could contain sensitive information)

So this is an additional permission you might only grant to users who should be able to see ALL the details related to their objects. There is no full "read only" access, but eventually `director/monitoring/services-ro` is what you're looking for. It allows one to see where configured services come from by clicking the "Configuration" Link in the monitoring module.
