### ISSUE TITLE
Template results are limited

### ISSUE THREAD

**Issue by mwaldmueller** [Icinga/icingaweb2-module-director#1135]
Template results are limited:
![bildschirmfoto 2017-08-29 um 15 34 19](https://user-images.githubusercontent.com/3973350/29823653-978ce70e-8ccf-11e7-9c16-f49c835b8afb.png)

# Environment
Director version (System - About): master, Git commit: a9b562421275d250eb071547eac7ba062b70a848
Icinga Web 2 version and modules (System - About): 2.4.1
Icinga 2 version (icinga2 --version): r2.7.0-1
Operating System and version: CentOS Linux release 7.3.1611 (Core)
Webserver, PHP versions: PHP 5.4.16

**Comment by Thomas-Gelf** [comment]
@mwaldmueller: works fine here. Do you really have more templates?

**Comment by mwaldmueller** [comment]
In my demosystem I only have 2 templates (screenshot) that works, but at customer's site there are much more templates and it stopped at "K". I think there is a fixed limitation number.

**Comment by Thomas-Gelf** [comment]
Limit should be 30 or so, I have to check this. Just type some characters to search - and it should ship more results.

**Comment by mwaldmueller** [comment]
Yes, I can confirm that it works when you type in the first letters. But so you have to know each single template name...

**Comment by Thomas-Gelf** [comment]
Have no problem with raising this to 50 or 100 or so, just: there has to be a limit. There are people who believe that thousands of templates would make sense. Usually their reasoning is weird, like "I had a similar structure in LConf". Still, I do not want them to complain about a slow GUI.

Would it be ok for you if I leave it as is, but raise the default limit to 100?

**Comment by mwaldmueller** [comment]
I agree with you, 100 is okay for me.

**Comment by Thomas-Gelf** [comment]
Deal. Pushed a related change, will close this issue. In addition, someone with LOTS of templates without knowing which ones he has might prefer to first go to the templates list, click around to find the correct one and then use the plus sign to create such a host. Also, adding single hosts changed recently. There you will now always be prompted to choose a single template from a full, not shortened list first.

People with lots of templates should be pushed towards using the new "Template Choices" mechanism. This allows you to group templates into single/multiple selection groups with a related name and description. All templates that are part of a choice will no longer show up in the full "imports" list. Please see #899 for related screen-shots.
