### ISSUE TITLE
dependencies: missing quotation marks in configuration rendering 

### ISSUE THREAD

**Issue by vita2** [Icinga/icingaweb2-module-director#1136]
i want to create a dependency with the upcoming dependency feature but unfortunately the deployment fails.

## Current Behavior
the director renders my configuration as follows:
```
apply Dependency "disable-nginx-checks" to Service {
    disable_checks = true
    disable_notifications = true
    assign where service.name == "nginx-status"
    parent_service_name = procs-nginx
    states = [ OK ]
}
```

now when i try to deploy the configuration it will fail in cause of an unsuccessfully config validation:
```
critical/config: Error: Error while evaluating expression: Tried to access undefined script variable 'procs'
Location: in [stage]/zones.d/director-global/dependency_apply.conf: 21:27-21:31
[stage]/zones.d/director-global/dependency_apply.conf(19): 
[stage]/zones.d/director-global/dependency_apply.conf(20):     assign where service.name == "nginx-status"
[stage]/zones.d/director-global/dependency_apply.conf(21):     parent_service_name = procs-nginx
                                                                                     ^^^^^
[stage]/zones.d/director-global/dependency_apply.conf(22):     states = [ OK ]
[stage]/zones.d/director-global/dependency_apply.conf(23): }
```

## Possible Solution
icinga2 assumes that `procs-nginx` is an constant. put the name of the parent service in quotation marks and it should work:
```
apply Dependency "disable-nginx-checks" to Service {
    ...
    parent_service_name = "procs-nginx"
    ...
}
```

## Context
the attribute `parent_host` isn't affected. the configuration will be properly rendered with hostname in quotation marks.

## Your Environment
* Director version (System - About): 8b0fe4f466f0e4c8e6af4ced5fc69abb3fc42d50 feature/dependencies-1096
* Icinga Web 2 version and modules (System - About): 2.4.1
* Icinga 2 version (`icinga2 --version`): r2.7.0-1
* Operating System and version: Debian Jessie 8.9 (3.16.0-4-amd64)
* Webserver, PHP versions: nginx 1.6.2-5 + php5-fpm 5.6.30

**Comment by Thomas-Gelf** [comment]
Thanks for reporting this!

**Comment by Thomas-Gelf** [comment]
@vita2: could you please try again?

**Comment by vita2** [comment]
of course!

i've just tested the fix. now the rendered configuration looks as expected 
```
apply Dependency "disable-nginx-checks" to Service {
    disable_checks = true
    disable_notifications = true
    assign where service.name == "nginx-status"
    parent_service_name = "procs-nginx"
    states = [ OK ]
}
```
thanks tom 🍻
