### ISSUE TITLE
dependencies: error message when filling the fields parent host and parent service at the same time

### ISSUE THREAD

**Issue by vita2** [Icinga/icingaweb2-module-director#1137]
currently it isn't possible to fill out the fields `Parent Host` and `Parent Service` at the same time. 

## Current Behavior
after choosing a service which belongs to the selected host the director will show the following error instantly:
```
Fatal error: Call to undefined method stdClass::get() in /usr/share/icingaweb2/modules/director/library/Director/Objects/IcingaDependency.php on line 398
```

![dependencies-parent-host-parent-service](https://user-images.githubusercontent.com/25298055/29828237-69bf4832-8cdc-11e7-8ae9-b7fb5e51fd28.png)

![dependencies-parent-host-parent-service-02](https://user-images.githubusercontent.com/25298055/29828320-ad56a7fc-8cdc-11e7-80bc-6fb62520be1d.png)

## Steps to Reproduce (for bugs)
1. add a dependency object
2. choose a parent host
3. after that, select a service which belongs to the host

## Your Environment
* Director version (System - About): 8b0fe4f466f0e4c8e6af4ced5fc69abb3fc42d50 feature/dependencies-1096
* Icinga Web 2 version and modules (System - About): 2.4.1
* Icinga 2 version (`icinga2 --version`): r2.7.0-1
* Operating System and version: Debian Jessie 8.9 (3.16.0-4-amd64)
* Webserver, PHP versions: nginx 1.6.2-5 + php5-fpm 5.6.30

**Comment by Thomas-Gelf** [comment]
Sorry, I broke this

**Comment by Thomas-Gelf** [comment]
@vita2: should be fixed

**Comment by vita2** [comment]
yes, it is. the error message is gone but there is a unrelated new one. i will open a new ticket with details.

thanks tom 👍
