### ISSUE TITLE
Template selection from import droplist doesn't work

### ISSUE THREAD

**Issue by bunghi** [Icinga/icingaweb2-module-director#1143]
Everytime I try to import an existing template it clear all the filled fields when I select it. The only way to import it correctly is typing the full name of the template and click on the "plus" button.

## Expected Behavior

Click on any template of the drop-list and auto fill all the corresponding fields

## Current Behavior

When clicked it automatically clear all the form fields 

## Possible Solution

No idea, I think it worked with a previous version of the director.

## Steps to Reproduce (for bugs)

With screenshots it's easier to understand:
1. I fill some fields before selecting the template:
![image](https://user-images.githubusercontent.com/31234197/29871358-22cf957c-8d94-11e7-8339-06d244af1967.png)

2. Let's say I want to select template named "MQDE01_Host_AIX" from the droplist:
![image](https://user-images.githubusercontent.com/31234197/29871437-6376a11a-8d94-11e7-80ea-0bd95644ef07.png)

3. This is what happens after clicking on it:
![image](https://user-images.githubusercontent.com/31234197/29871466-8165ced0-8d94-11e7-95bf-dd4a7f0f78f7.png)

4. The only way to do it is typing the exact name of the template and click on the plus icon (not clicking over the name of the template):
![image](https://user-images.githubusercontent.com/31234197/29871563-e267e4fc-8d94-11e7-820a-0e638223a746.png)

## Your Environment

![image](https://user-images.githubusercontent.com/31234197/29871601-1123902a-8d95-11e7-8a99-e76578643e95.png)

* Operating System and version: Debian 9
* Webserver, PHP versions: Apache/2.4.25 (Debian)

**Comment by Thomas-Gelf** [comment]
@bunghi: click handling has slightly been modified recently. As you're using the GIT master, what exact GIT commit/hash are you using? Should be shown when choosing the Director module from the About page.

**Comment by bunghi** [comment]
I can't see any hash/commit but I can tell you that I manually downloaded the master zip from GitHub on August 23.
![image](https://user-images.githubusercontent.com/31234197/29872791-b3578c76-8d99-11e7-892b-3828abd9ea3d.png)

**Comment by Thomas-Gelf** [comment]
In that case the last commit isn't shown. The fix I mentioned has been pushed on August 24th - so please try again with the current master!

**Comment by bunghi** [comment]
Ok, I just downloaded the last master version. I see that when you create a new host first of all it asks for the host template. So good so far but after template is selected there is no option to import any other template. I have to save the host and after that I have the option to import new template **but still have the same selection problem**, it clears all the fields when any is selected from the autocomplete droplist.

The problem with the droplist template selection happens with services too, not only with hosts.

**Comment by bunghi** [comment]
It works now. Thanks.

**Comment by Thomas-Gelf** [comment]
Glad to hear that, you're welcome!
