### ISSUE TITLE
Host Config will not show inherited Hostgroup from Hosttemplate

### ISSUE THREAD

**Issue by Naro370** [Icinga/icingaweb2-module-director#1144]
When you configure a Hostgroup in a Hosttemplate, a new Host with that Hosttemplate it will not show the inherited Hostgroup from the template.

## Expected Behavior
Host Config should show inherited Hostgroup from the Hosttemplate.

## Current Behavior
A new Host always show no Hostgroups.

## Steps to Reproduce (for bugs)
1. Create a Hostgroup
2. Create a Hosttemplate
3. Configure the Hostgroup in the Hosttemplate
4. Create a new Host based on the Hosttemplate
5. Store it, but no inherited Hostgroup will displayed

//Edit: Only Display Problem

## Your Environment
* Director version: master (last update: 30.08.2017)
* Icinga Web 2 version and modules: 2.4.1-2.stretch
* Icinga 2 version: 2.7.0-1.stretch
* Operating System and version: Debian 9 (stretch)
* Webserver, PHP versions: Apache 2.4.25-3+deb9u2, PHP 7.0.19-1

**Comment by lazyfrosch** [comment]
Looks like a problem in inheritance, so it's more or less a display problem in Director.

Not visible at:
* resolved preview of a host
* in forms (where the default value is usually visible)

**Comment by Naro370** [comment]
I rechecked that, you are right, in the backend it will set the hostgroup.
It is only a display problem.

**Comment by Naro370** [comment]
In the Hostgroup -> Members tab the info of all members are also missing.
I can only see the template as "direct" member, but imho I also should see all hosts which get the group over the template with the type "inherited from <template>".

**Comment by Thomas-Gelf** [comment]
@Naro370: that's a very good catch, thanks for reporting this. It's hard to explain why, but what you're describing is a completely different issue than what this one is all about - even if it sounds similar. It would be great if you could open a dedicated issue for this!

**Comment by Naro370** [comment]
Sure no problem, I created a new issue: #1148

**Comment by Thomas-Gelf** [comment]
This should have been solved with v1.4.0, inherited and applied (and overridden) groups are now shown at host level.
