### ISSUE TITLE
"Merge" in Sync Rule does a replace in fact

### ISSUE THREAD

**Issue by sysadmama** [Icinga/icingaweb2-module-director#1146]
Hi,

I was wondering why my great notification setup is broken... And I found the explanation for this:
* Import rule imports users from LDAP
* I added all admin users manually to local group `admin-people`
* Sync Rule has update policy "merge", so this associated group remained on every import-sync-config-deploy game; worked for months.

But now, the Sync Rule seems to replace instead, and my user belongs to no group; as the notification object is assigned `where true` for `user_groups = [ "admin-people" ]` - no notifications anymore.

The silence is very soothing indeed, but: can you please have a look at that? I stopped `service director-jobs` now.

Cheers,
  Marianne

## Your Environment

* Director version (System - About): 168369e738b7f60ffc154ce03db56dbc1d2729e2
* Icinga Web 2 version and modules (System - About): b7639651e80e85b81d9fb92c1db77e90c3754d2d
* Icinga 2 version (`icinga2 --version`): r2.7.0-1
* Operating System and version: Ubuntu 16.04.3 LTS
* Webserver, PHP versions: apache2-2.4.18, php7-7.0.22

**Comment by Thomas-Gelf** [comment]
@sysadmama: sorry I'm not able to follow you. Could you please show me a concrete example of

* a change issued by sync
* the related sync property definition
* your assignment rule

In case those contain information you do not want to share here, please mail me those details.

**Comment by sysadmama** [comment]
You've got mail. Hope it makes things clearer...

**Comment by Thomas-Gelf** [comment]
@sysadmama: I pushed a related change, could you please try again?

**Comment by sysadmama** [comment]
@Thomas-Gelf - your commit seems to solve this issue - thank you!

**Comment by Tuxdiver** [comment]
Maybe related (and not fixed by this commit): sync merge also drops "imports" in sync rule for Hosts?

**Comment by mbassett** [comment]
I'm having similar issue with merge of LDAP users dropping their manually assigned groups, and disabled nodes being re-enabled.

**Comment by Thomas-Gelf** [comment]
There used to be a bug related to `disabled` that has been fixed. Could it eventually be that it used to be wrong and has now been corrected? Groups should not be dropped. Also here, there used to be bugs - but they should have been fixed. Could you please share some details regarding your Sync Rule configuration? Especially merge policy and similar...
