### ISSUE TITLE
Duplicate check command, can't deploy or remove duplicate

### ISSUE THREAD

**Issue by pillbug22** [Icinga/icingaweb2-module-director#1147]
Background - for Windows servers, the load-windows check command was providing OK/green, even if CPU was at 100%. Was attempting to create a new check command that inherited load-windows, then provide custom warning and critical arguments in the new command. (75% for warning, 90% for critical).

I now have 2 "load-windows" commands listed in Director, and I cannot edit either. Under preview, they both now show the static values for -c and -w, instead of the variables found in the default load-windows command.

When I go to deploy, it of course tells me of a duplicate command, but I can't find a way to remove the duplicate or reset to default. I tried to rollback through the activity log, but even going all the way back to before I started editing, the duplicate persists.

## Expected Behavior
Was attempting to setup a custom check command for load-windows to use different thresholds. 

## Current Behavior
Managed to create a duplicate load-windows command, not can't deploy config or get rid of the duplicate. When selecting one of the load-windows commands in the list, it highlights both of them.

## Possible Solution
?

## Context
Attempting to find a solution to use different thresholds on load-windows command

## Your Environment
* Director version (System - About): 2.3.1
* Icinga Web 2 version and modules (System - About): 2.4.1
* Icinga 2 version (`icinga2 --version`): r2.7.0-1
* Operating System and version: Ubuntu 16.04.2 Server
* Webserver, PHP versions:  Apache/2.4.18 (Ubuntu), PHP Version 7.0.22

Screen caps/messages:
![load-windows](https://user-images.githubusercontent.com/4721980/29933836-addcce14-8e3e-11e7-9b19-468167f6d6dc.png)

When attempting to deploy:
`information/cli: Icinga application loader (version: r2.7.0-1)
information/cli: Loading configuration file(s).
critical/config: Error: Object 'load-windows' of type 'CheckCommand' re-defined: in [stage]/zones.d/director-global/commands.conf: 3:1-3:34; previous definition: in /usr/share/icinga2/include/command-plugins-windows.conf: 54:1-54:34
Location: in [stage]/zones.d/director-global/commands.conf: 3:1-3:34
[stage]/zones.d/director-global/commands.conf(1): library "methods"
[stage]/zones.d/director-global/commands.conf(2): 
[stage]/zones.d/director-global/commands.conf(3): object CheckCommand "load-windows" {
                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[stage]/zones.d/director-global/commands.conf(4):     import "plugin-check-command"
[stage]/zones.d/director-global/commands.conf(5):     import "load-windows"
`

**Comment by Thomas-Gelf** [comment]
@pillbug22: I didn't even know that this was possible. Seems that for whatever reason we relaxed uniqueness for commands to uniqueness per zone, but with zone allowing null values DB constraints are failing here.

To solve your issue please run the following query on your database:

 ```sql
DELETE FROM icinga_command WHERE object_type = 'object' AND object_name = 'load-windows';
```
The command shipped in the ITL should be `object_type = 'external_object'` and not be matched by above query.

**Comment by pillbug22** [comment]
1. I did a "simulate query" in phphMyAdmin on the above query, and it confirmed only finding 1 matching row
2. Ran the query for real
3. Back through Director -> Commands, now shows only the default check command

Thank you!

Now, I guess the 2nd part of the question on what I did wrong...is there a better way to try and achieve custom thresholds, or is creating a new command the correct way and I just did it wrong?

**Comment by Thomas-Gelf** [comment]
Just add Fields for load_win_crit and similar and you should be able to override the thresholds on any Service and/or Service Template.

**Comment by pillbug22** [comment]
Got it. That worked well. Thank you @Thomas-Gelf !

**Comment by ant0nwax** [comment]
Actually this is a bug report, and you closed it by a workaround, I would like to request reopen, since we ran into the same error... or please provide a more understandable solution to the topic than:

To solve your issue please run the following query on your database:
SELECT FROM icinga_command WHERE object_type = 'object' AND object_name = 'ssl_cert';

I am missing the database name (director/icingaweb/icinga_ido)
I am missing the exact way to enter this query (icingawebgui/ssh_andifyes_whichuser)

So could you please provide more accurate steps for this?

Thanks a lot in advance that I do not have to invent the wheel again

**Comment by ant0nwax** [comment]
critical/config: Error: Object 'ssl_cert' of type 'CheckCommand' re-defined: in [stage]/zones.d/director-global/commands.conf: 526:1-526:30; previous definition: in /usr/share/icinga2/include/plugins-contrib.d/web.conf: 369:1-369:30
Location: in [stage]/zones.d/director-global/commands.conf: 526:1-526:30

**Comment by Thomas-Gelf** [comment]
Hi ant0nwax,

what Director version are you using and how did you manage to get there? Different safety measures have been put in place to avoid running into this problem, so in theory there should be no need to document any workaround. I tried hard to reproduce your issue and haven't been able to do so.

Cheers,
Thomas

**Comment by ant0nwax** [comment]
Hi Thomas, Thanks for getting in touch so fast, actually that is awesum!

I added a check command called check_ssl_certs and accidentially modified the name to a already existing check commands name that is inside the vmware folder: modified name of the new check command: check_ssl

maybe you cannot create new duplicate check commands, but at the modify the error handling is missing...

director: 1.4.2

Icinga Web 2 Version
    2.5.0
Git commit
    ebe1917b152b786cc708abe5215fd0c4be7c4237
Git commit date
    2017-11-27
Copyright
    © 2013-2018 The Icinga Project

**Comment by Thomas-Gelf** [comment]
@ant0nwax: I created #1496 to solve this, so there will be definitively no more need for a workaround. Have you been able to fix your own issue, or do you need assistance with the query?

**Comment by ant0nwax** [comment]
Thanks Thomas, 

i would really appreciate steps to clen the database, since I would not like to corrupt this database

maybe something like

ssh icingaserver
su - which user?
which sql to start? which database? which database user?
which "select from" to start to check that really one data line is selected
replace the select with "delete from"

maybe there is a gui version that is more simple than my approach, just my experience is that usually it is done like i wrote it... i just do not know exactly the database, users and so on

**Comment by Thomas-Gelf** [comment]
Well... this depends :laughing:
How did you create your Director database?

**Comment by ant0nwax** [comment]
root@monitoringsrv ~ # ps -ef | grep -i sql
postgres  1975     1  0 Apr17 ?        00:00:52 /usr/pgsql-9.6/bin/postmaster -D /var/lib/pgsql/9.6/data

The director database is called "director" and the user is called "director"

i think it is listening on port 5432

**Comment by ant0nwax** [comment]
root@monitoringsrv ~ # **su - postgres**
-bash-4.1$ **psql -U director -d director**
psql (9.6.6)
Type "help" for help.

director=> **SELECT FROM icinga_command WHERE object_type = 'object' AND object_name = 'ssl_cert';**
--
(1 row)

director=> **DELETE FROM icinga_command WHERE object_type = 'object' AND object_name = 'ssl_cert';**
DELETE 1
director-> **\q**
-bash-4.1$ **logout**
root@monitoringsrv ~ #

**Comment by Thomas-Gelf** [comment]
Perfect! I wanted to send you a rename command, but have been blocked by other tasks. Glad to see that you've managed to fix this on your own! Please follow the issue linked above for a final fix. I pinned it on the v1.5.0 milestone, this could be released by the end of Mai.

**Comment by ant0nwax** [comment]
thanks a lot Thomas, i think after that i will upgrade our icinga since it is a november 2017 state, have a great day, Anton
