### ISSUE TITLE
Hostgroup - Members tab show direct, but no inherited members

### ISSUE THREAD

**Issue by Naro370** [Icinga/icingaweb2-module-director#1148]
## Expected Behavior
Hostgroup - Members tab should show all Members.

## Current Behavior
Only direct assigned Members are shown in this tab. Members how are assigned via a template are not shown.

## Possible Solution
Members which are assigned via templates should have the type: "inherited from -templatename-"

## Steps to Reproduce (for bugs)
1. Create a hosttemplate and assign a hostgroup
2. Create a host with that hosttemplate
3. In the Members tab of that hostgroup you only see the template as member, but not the host.

## Your Environment
* Director version: master (last update: 30.08.2017)
* Icinga Web 2 version and modules: 2.4.1-2.stretch
* Icinga 2 version: 2.7.0-1.stretch
* Operating System and version: Debian 9 (stretch)
* Webserver, PHP versions: Apache 2.4.25-3+deb9u2, PHP 7.0.19-1

**Comment by Thomas-Gelf** [comment]
Fixed in current master
