### ISSUE TITLE
Command Fields: set_if arguments not in fields list

### ISSUE THREAD

**Issue by Naro370** [Icinga/icingaweb2-module-director#1149]
## Expected Behavior
When I have arguments in my commands which have an variable ($example$) in the "Condition (set_if)", I also want to pick them as possible Field in the "Fields" tab.

## Current Behavior
I can't pick the field in the easy way as a "Argument macros". First I have to go to the "Define Data Fields" menu and manuel create a variable with that same name as the needed argument set_if name. Then I can go back to the command fields, and can pick that variable from "Other available fields".

## Possible Solution
As with a variable in the Value field, a variable in the Condition field should also shown in the Fields tab in the Field list under "Argument macros".

## Steps to Reproduce (for bugs)
1. Create a command
2. Create an argument with "$test1$" as Value.
3. Create an argument with "$test2$" as Condition (set_if).
4. Go to Fields tab, there you will only see $test1$ as a possible "Argument macros"

## Context
This happens on both, external and director commands.

## Your Environment
* Director version: master (last update: 30.08.2017)
* Icinga Web 2 version and modules: 2.4.1-2.stretch
* Icinga 2 version: 2.7.0-1.stretch
* Operating System and version: Debian 9 (stretch)
* Webserver, PHP versions: Apache 2.4.25-3+deb9u2, PHP 7.0.19-1

**Comment by Thomas-Gelf** [comment]
This duplicates #250 and is scheduled for v1.4.0. Problem is that vars used in `set_if` are preferably booleans, and the form there just offers to create Strings. So, it should be extended to get as powerful as the Form you have available when going directly to `DataFields`. Will be extended, I'll close this as the mentioned duplicate already exists.
