### ISSUE TITLE
Command Arguments: Condition (set_if) field could not be cleared 

### ISSUE THREAD

**Issue by Naro370** [Icinga/icingaweb2-module-director#1150]
## Expected Behavior
Deleting all chars in the "Condition (set_if)" field and click on the Button Store will lead to the unset of the "Condition (set_if)" field of that argument.

## Current Behavior
I can edit the "Condition (set_if)" of an argument, but I can't remove it, because when I click on Store and then select this argument again, it show that the "Condition (set_if)" field is still set.

## Steps to Reproduce (for bugs)
1. Add an new argument to a command and set the Condition (set_if) to "$test$"
2. Reselect that argument
3. Delete the "$test$" in the Condition (set_if) and store that
4. Reselect that argument -> "$test$" is still in the Condition (set_if) field.

## Context
Workaround: Delete the whole argument and recreate with no "Condition (set_if)".

## Your Environment
* Director version: master (last update: 30.08.2017)
* Icinga Web 2 version and modules: 2.4.1-2.stretch
* Icinga 2 version: 2.7.0-1.stretch
* Operating System and version: Debian 9 (stretch)
* Webserver, PHP versions: Apache 2.4.25-3+deb9u2, PHP 7.0.19-1

**Comment by Thomas-Gelf** [comment]
Can be reproduced, thanks for reporting this.

Reason (hint for myself) -> CommandArguments overrides toPlainObject, doesn't handle skipDefaults and so when reverting back to the default value (null) the new value gets lost.

**Comment by Thomas-Gelf** [comment]
Should have been fixed with 4c46f07
