### ISSUE TITLE
Custom command argument-value separator

### ISSUE THREAD

**Issue by bunghi** [Icinga/icingaweb2-module-director#1152]
I'm facing an issue that I am unable to sort out. I want create a new plugin check command. The script has this syntax:

```
Usage: tsmmonitor [options] [check] [options_check]

Options

-u, --user          tsm user to connect to the tsm server
-p, --pass          tsm user password to connect to the tsm server
-s, --servername    specify tsm servername
-m, --mail          mail addresses separated by blank space
-q, --quiet         quiet mode, suppress all output (except errors)
-S, --source        print the check source code
-h, --help          print this help information and exit
-V, --version       print program version and exit

The following checks are available:

help, db, log, scratch, drive, path, dbfrag, unav, stgpool, volerr, volreclaim, tapeslib, tapesown, tapesstgpool, dbbkp, numsess, numnodes, nodeslocked, diskvol, dbvol, logvol, searchanr, inavol, drmvol, sched, lic, dailybackup, falseprivate
```
The problem is that the options can't have blank spaces between the option and the value. Example:

tsmmonitor -u=username -p=password -s=servername check_name

When I try to build the command Icinga uses blank separator instead of "=" symbol.

This is how I tried to define the arguments:

![image](https://user-images.githubusercontent.com/31234197/30052393-f4ebc5ce-922d-11e7-8871-d18d2a4dae63.png)

This way the command executed is, which is incorrect:

tsmmonitor -u -u=username -p -p=password -s -s=servername check_name

Any idea how to do it?

## Your Environment

* Director version (System - About): master (August 29th)
* Icinga Web 2 version and modules (System - About):
![image](https://user-images.githubusercontent.com/31234197/30052571-8a50c024-922e-11e7-855c-a5db48ae2af9.png)

* Icinga 2 version (`icinga2 --version`): 2.4.1
* Operating System and version: Debian 9
* Webserver, PHP versions: Apache/2.4.25, PHP 7.0.19-1

**Comment by Thomas-Gelf** [comment]
@bunghi: leave the argument name empty, it will set "skip_key" - or just manually set skip_key to Yes. Then set `-x=$varname$` as your argument value

**Comment by bunghi** [comment]
I already tried to leave it blank but it shows me an error whan I try to store the change. I don't se the skip_key field:
![image](https://user-images.githubusercontent.com/31234197/30052834-8d81ddea-922f-11e7-9d0a-696eb6663e74.png)

**Comment by Thomas-Gelf** [comment]
This should have been fixed yesterday, please pull the current master ;-)

**Comment by bunghi** [comment]
It works now!!! Thanks again

**Comment by Thomas-Gelf** [comment]
You're welcome!
