### ISSUE TITLE
Inherited values not shown in service set

### ISSUE THREAD

**Issue by paolozuliani** [Icinga/icingaweb2-module-director#1154]
Inherited values in single sevice of a service set were shown as .. inherited(value). Now these values are not shown even if they are still defined (monitoring is still working correctly...).

## Expected Behavior
Inherited value shown

## Current Behavior
Fields are empty even if a default value is present.

## Steps to Reproduce (for bugs)
1. Define a service set 
2. Define some values in one or more service 
3. Apply the service set to a host

## Your Environment
* Director version: master, updated today with git pull
* Icinga Web 2 version and modules (System - About): 2.4.0
* Icinga 2 version (`icinga2 --version`): r2.7.0-1
* Operating System and version: CentOS Linux release 7.3.1611

**Comment by paolozuliani** [comment]
Updated today via git pull. The problem is fixed

**Comment by Thomas-Gelf** [comment]
Glad to hear that. Thanks for reporting the issue - and for letting us know that it now works again!
