### ISSUE TITLE
Timeperiods arn't sorted

### ISSUE THREAD

**Issue by TBonin** [Icinga/icingaweb2-module-director#1155]
## Expected Behavior
Timeperiods should be sorted by the object name

## Current Behavior
Timeperiods are sorted by ID

## Possible Solution
[icingaweb2-module-director/application/tables/IcingaTimePeriodTable.php](https://github.com/Icinga/icingaweb2-module-director/blob/29b917dd186a2aceb179c560c666b25d8c6635c9/application/tables/IcingaTimePeriodTable.php)

`    public function getBaseQuery()
    {
        return $this->db()->select()->from(
            array('t' => 'icinga_timeperiod'),
            array()
        )**->order('t.object_name');;**
    }
`

## Steps to Reproduce (for bugs)
...

## Context
...

## Your Environment
* Director version (System - About): 1.3.1
* Icinga Web 2 version and modules (System - About): 2.4.1
* Icinga 2 version (`icinga2 --version`): r2.7.0-1
* Operating System and version: Red Hat Enterprise Linux Server release 7.3 (Maipo)
* Webserver, PHP versions:

**Comment by Thomas-Gelf** [comment]
Tables have been re-implemented with v1.4.0, this has been fixed.
