### ISSUE TITLE
templatetree undefined offset

### ISSUE THREAD

**Issue by mbassett** [Icinga/icingaweb2-module-director#1156]
```
#0 /usr/share/icingaweb2/modules/director/library/Director/Resolver/TemplateTree.php(186): Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(8, 'Undefined offse...', '/usr/share/icin...', 186, Array)
#1 /usr/share/icingaweb2/modules/director/library/Director/Resolver/TemplateTree.php(126): Icinga\Module\Director\Resolver\TemplateTree->getParentsById('83')
#2 /usr/share/icingaweb2/modules/director/library/Director/Resolver/TemplateTree.php(105): Icinga\Module\Director\Resolver\TemplateTree->getParentsFor(Object(Icinga\Module\Director\Objects\IcingaServiceSet))
#3 /usr/share/icingaweb2/modules/director/library/Director/Repository/IcingaTemplateRepository.php(40): Icinga\Module\Director\Resolver\TemplateTree->listParentIdsFor(Object(Icinga\Module\Director\Objects\IcingaServiceSet))
#4 /usr/share/icingaweb2/modules/director/library/Director/Repository/IcingaTemplateRepository.php(79): Icinga\Module\Director\Repository\IcingaTemplateRepository->getTemplatesFor(Object(Icinga\Module\Director\Objects\IcingaServiceSet), false)
#5 /usr/share/icingaweb2/modules/director/library/Director/Objects/IcingaObjectImports.php(278): Icinga\Module\Director\Repository\IcingaTemplateRepository->getTemplatesIndexedByNameFor(Object(Icinga\Module\Director\Objects\IcingaServiceSet))
#6 /usr/share/icingaweb2/modules/director/library/Director/Objects/IcingaObjectImports.php(350): Icinga\Module\Director\Objects\IcingaObjectImports->loadFromDb()
#7 /usr/share/icingaweb2/modules/director/library/Director/Objects/IcingaObject.php(806): Icinga\Module\Director\Objects\IcingaObjectImports::loadForStoredObject(Object(Icinga\Module\Director\Objects\IcingaServiceSet))
#8 /usr/share/icingaweb2/modules/director/library/Director/Objects/IcingaServiceSet.php(73): Icinga\Module\Director\Objects\IcingaObject->imports()
#9 /usr/share/icingaweb2/modules/director/library/Director/Objects/IcingaServiceSet.php(121): Icinga\Module\Director\Objects\IcingaServiceSet->getServiceObjects()
#10 /usr/share/icingaweb2/modules/director/library/Director/IcingaConfig/IcingaConfig.php(695): Icinga\Module\Director\Objects\IcingaServiceSet->renderToConfig(Object(Icinga\Module\Director\IcingaConfig\IcingaConfig))
#11 /usr/share/icingaweb2/modules/director/library/Director/IcingaConfig/IcingaConfig.php(673): Icinga\Module\Director\IcingaConfig\IcingaConfig->createFileForObjects('serviceSet', Array)
#12 /usr/share/icingaweb2/modules/director/library/Director/IcingaConfig/IcingaConfig.php(476): Icinga\Module\Director\IcingaConfig\IcingaConfig->createFileFromDb('serviceSet')
#13 /usr/share/icingaweb2/modules/director/library/Director/IcingaConfig/IcingaConfig.php(269): Icinga\Module\Director\IcingaConfig\IcingaConfig->generateFromDb()
#14 /usr/share/icingaweb2/modules/director/library/Director/IcingaConfig/IcingaConfig.php(305): Icinga\Module\Director\IcingaConfig\IcingaConfig->hasBeenModified()
#15 /usr/share/icingaweb2/modules/director/library/Director/IcingaConfig/IcingaConfig.php(258): Icinga\Module\Director\IcingaConfig\IcingaConfig->storeIfModified()
#16 /usr/share/icingaweb2/modules/director/application/controllers/ConfigController.php(281): Icinga\Module\Director\IcingaConfig\IcingaConfig::generate(Object(Icinga\Module\Director\Db))
#17 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Director\Controllers\ConfigController->storeAction()
#18 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('storeAction')
#19 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#20 /usr/share/php/Icinga/Application/Web.php(389): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#21 /usr/share/php/Icinga/Application/webrouter.php(109): Icinga\Application\Web->dispatch()
#22 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...')
#23 {main}
```

## Expected Behavior
Configuration deploys / renders

## Current Behavior
undefined offset in templatetree:186

## Context
After pulling to latest master branch (was using master branch from several months ago) unable to push/render configuration.  

## Your Environment

* Director version (System - About):master
* Icinga Web 2 version and modules (System - About):2.4.1
* Icinga 2 version (`icinga2 --version`):v2.6.3

* Operating System and version:
System information:
  Platform: CentOS Linux
  Platform version: 7 (Core)
  Kernel: Linux
  Kernel version: 3.10.0-514.6.1.el7.x86_64
  Architecture: x86_64

* Webserver, PHP versions:
httpd-2.4.6-45.el7.centos.4.x86_64
php-5.4.16-42.el7.x86_64

**Comment by mbassett** [comment]
This was a production system so I couldn't really leave it this way.  Reverted to mysql backups and checkout branch support/1.3  resolved the issue.

**Comment by Thomas-Gelf** [comment]
@mbassett: sorry, I cannot reproduce this issue. Could you please let me somehow have the content of your `iicinga_service_set` and `icinga_service_set_inheritance` tables?

**Comment by mbassett** [comment]
Emailed the results to your email listed on github.

**Comment by Thomas-Gelf** [comment]
Thank you! There is one strange / messed up entry in your inheritance table:

"Icinga-Agent-Default" is the culprit. It's there three times (this is legal), one of them is a template, two of them are objects related to a host. Now, the problem is that instead of inheriting from the template, one of the sets assigned to a host inherits from the other one.

Please run this query to clean up your setup:

```sql
UPDATE icinga_service_set_inheritance SET parent_service_set_id = 85
  WHERE parent_service_set_id = 1 AND service_set_id = 83;
```

I do not know how this happened, but there have been related (fixed) bugs that might have caused this wrong relation. Did you create those Sets in the GUI or in an automated way?

**Comment by mbassett** [comment]
Created via the gui.

The revision of master branch I was on was pretty stale, I haven't touched it in quite a while.  I really don't even know what rev it was on, but when the machine was built it was built with master at the time.  Everything has been working fairly well though we have noticed bugs.  Figured there had been so much movement it was time to pull the trigger ;) 


The box was built January 10, 2017, so it could be a master snapshot from that date.

**Comment by Thomas-Gelf** [comment]
Inheritance lookup changed to be more strict, expect from two exceptions only templates are now considered valid parents. Your relations used to be wrong, but it wasn't an issue with older versions as you didn't realize it as the have the same name - and Icinga is also fine, as it doesn't have to deal with Service Sets. But Director v1.4.0 will fail, and that's a good thing. DB migration takes care about some related errors, but it's not possible to fix all weird errors in an automated way - sorry for that.

Could you please check whether the master works now for you?

**Comment by mbassett** [comment]
I believe that corrected the show stopping issue with the gui.  I seem to have to drop a couple tables to get the migration to work.   now i'm getting a missing table.

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'director.icinga_hostgroup_host_resolved' doesn't exist, query was: SELECT hgh.hostgroup_id AS group_id, hgh.host_id AS object_id FROM icinga_hostgroup_host_resolved AS hgh WHERE (host_id = 559) (Pdo.php:225)

**Comment by mbassett** [comment]
created that table from the mysql schema file and now things are looking pretty good.

**Comment by Thomas-Gelf** [comment]
Manually interfering with the migration is not a good idea :skull_and_crossbones: - and deleting tables shouldn't be required at all. Please let me know what manual steps you took, I'll try to help you with cleaning things up.

**Comment by mbassett** [comment]
icingacli director migration run --verbose
ERROR: Icinga\Exception\IcingaException in /usr/share/icingaweb2/modules/director/library/Director/Db/Migration.php:50 with message: Migration 132 failed (SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'icinga_host_template_choice' already exists) while running CREATE TABLE icinga_host_template_choice (
  id INT(10) UNSIGNED AUTO_INCREMENT NOT NULL,
  object_name VARCHAR(64) NOT NULL,
  description TEXT DEFAULT NULL,
  min_required SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  max_allowed SMALLINT UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY (id),
  UNIQUE KEY (object_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
[mbassett@icinga-master01 director]$ sudo icingacli director migration run --verbose
ERROR: Icinga\Exception\IcingaException in /usr/share/icingaweb2/modules/director/library/Director/Db/Migration.php:50 with message: Migration 133 failed (SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'icinga_service_template_choice' already exists) while running CREATE TABLE icinga_service_template_choice (
  id INT(10) UNSIGNED AUTO_INCREMENT NOT NULL,
  object_name VARCHAR(64) NOT NULL,
  description TEXT DEFAULT NULL,
  min_required SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  max_allowed SMALLINT UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY (id),
  UNIQUE KEY (object_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8

**Comment by Thomas-Gelf** [comment]
When "rolling back" to 1.3.x - what did you do? Did you delete entries from the migraitons table?

**Comment by mbassett** [comment]
I restored from sql backup that was made prior to the git pull.

**Comment by Thomas-Gelf** [comment]
That's perfect, that's exactly how it should be done. No idea why you then had the icinga_host_template_choice table still there?! So, is everything clean and fine right now?

**Comment by mbassett** [comment]
Looks like it, though I see now that all the imports have changed order and hope that does not effect things.

**Comment by Thomas-Gelf** [comment]
Imports have changed order?

**Comment by mbassett** [comment]
![screenshot_2017-09-05_15-12-09](https://user-images.githubusercontent.com/2250654/30085671-773ed034-924c-11e7-8d3f-0dabf3c1ed49.png)

**Comment by Thomas-Gelf** [comment]
Did this happen because of an Automation/Sync Rule?

**Comment by mbassett** [comment]
Seems to yes, I'm trying to change the priorities of the sync in order to make it appear as before.

**Comment by mbassett** [comment]
I believe I have that corrected now also by adjusting the priority ordering of the sync properties.   Huzzah!  Thanks Thomas.

**Comment by Thomas-Gelf** [comment]
@mbassett: you're welcome! In case you think the changed order is a bug, please let me have your `sync_rule` and `sync_property` tables from your backup. Eventually first check whether they contain sensible information. Order has been flipped, but migration should also have flipped the sync property order in the DB. So in case this didn't work correctly for you I'd really love to investigate this.

**Comment by mbassett** [comment]
I noticed this changed behavior upon change to support/1.3 also, so it's likely an old bug.  

Also I noticed the merge problems with support/1.3 as well, but not previously.  
manually disabling a node via icinga web ui  the node then gets re-added from the sync rule as enabled.

adding a user group on a ldap sync'd user, the user group gets removed on next sync

**Comment by Thomas-Gelf** [comment]
Just for the records:
* disable used to be formerly buggy, is now working correct
* there was still a bug related to "merge" and imports, causing the issue with those groups - this has now been fixed.
