### ISSUE TITLE
Fatal error: Interface 'ipl\Web\Widget\ControlsAndContent' not found

### ISSUE THREAD

**Issue by swizzly** [Icinga/icingaweb2-module-director#1159]
After upgrading Icinga Director from a Version 2017-03-29 to the current version https://github.com/Icinga/icingaweb2-module-director/commit/424fc3136356f6725505567d37f7d4b7ce71fe46
I get the error `Fatal error: Interface 'ipl\Web\Widget\ControlsAndContent' not found in /usr/local/src/icingaweb2-module-director-master-424fc31/library/Director/Web/Controller/ActionController.php on line 27`.

I have the IPL Module installed. (Version https://github.com/Thomas-Gelf/ipl/commit/adfaa9b5e7e00cdf7c38289d72d1bbc39d0c26bc)
I have Icingaweb2 v2.4.1

**Comment by vita2** [comment]
disable or remove the ipl-module. currently you didn't need it for the icinga director :)

**Comment by swizzly** [comment]
Ok, thanks that solved the Problem.
