### ISSUE TITLE
Space in import source results in duplicate

### ISSUE THREAD

**Issue by mwaldmueller** [Icinga/icingaweb2-module-director#1161]
If entries in the import source end with a space, they are treated than without a space.

# Behaviour

This is my cmdb:

```
MariaDB [cmdb]> select * from hosts;
+----+----------+----------+---------+
| id | hostname | address  | os      |
+----+----------+----------+---------+
|  1 | web2     | 1.2.3.4  | Windows |
|  2 | srv-web1 | 8.8.8.8  | Linux   |
|  3 | web2     | 10.2.3.5 | Windows |
+----+----------+----------+---------+
```

There is "web2" (= without space) and "web2 " (= with space).

In my import source I've specified "hostname" as key column name, it runs without any problems.

The sync rule aborts with the following error:

> This Sync Rule failed when last checked at 2017-09-06 16:30:22: Exception while syncing Icinga\Module\Director\Objects\IcingaHost web2 : Trying to recreate icinga_host (web2 )

# Environment

Director version (System - About): master, Git commit: 424fc3136356f6725505567d37f7d4b7ce71fe46
Icinga Web 2 version and modules (System - About): 2.4.1
Icinga 2 version (icinga2 --version): r2.7.0-1
Operating System and version: CentOS Linux release 7.3.1611 (Core)
Webserver, PHP versions: Apache, PHP 5.4.16

**Comment by Thomas-Gelf** [comment]
There is not much I can do about this, trailing spaces are a special beast in relational databases, especially MySQL. So, no way as long as this is the *expected* behavior:

```
MariaDB [director_a1]> SELECT 'a' = 'a ', 'a' = ' a';
+------------+------------+
| 'a' = 'a ' | 'a' = ' a' |
+------------+------------+
|          1 |          0 |
+------------+------------+
```

Please clean up your import source, eventually use property modifiers. I have to reject this issue.
