### ISSUE TITLE
Director job should run at a specific time

### ISSUE THREAD

**Issue by mwaldmueller** [Icinga/icingaweb2-module-director#1162]
It would be nice if specific director jobs would be able to run at a specific time. For example: An import job should run once a week, at Monday 10am.

**Comment by Thomas-Gelf** [comment]
@mwaldmueller: define a TimePeriod, then you should be able to tell the job to run only in that period.

**Comment by mwaldmueller** [comment]
Timeperiod:

```
object TimePeriod "directorjob" {
    import "legacy-timeperiod"
    import "director-timeperiod"

    ranges = {
        "monday"	= "10:00-10:01"
    }
}
```

And the run interval at the job is "61s".

I don't find it very elegant. I can't event trigger a single job via cronjob and "icingacli director jobs run".

**Comment by Thomas-Gelf** [comment]
Sorry, I did overlook the `once`. Triggering at a specific time: that's not official, but possible: `icingacli director jobs run 42` with 42 being your jobs ID. However, there are CLI commands for various tasks that are available through jobs - what exactly do you want to run once? A config deployment would for example be as simple as `icingacli director config deploy`.

**Comment by Thomas-Gelf** [comment]
Then I'd suggest to define three jobs, and let's say their IDs are 1, 2 an 3 just run:

```
icingacli director jobs run 1 \
&& icingacli director jobs run 2 \
&& icingacli director jobs run 3
```

But Jobs have not been built with that use-case in mind. They make sure themselves to not do anything if nothing changed. To delay a deployment in case one already happened a few minutes ago and similar. So, keep in mind that running those jobs only once might not have the expected result, depending on various circumstances. Running the Deployment Job is not the same as running the Deployment.

Just wanted to let you know that this sounds weird to me. If you want, please mail me the your use-case with more details regarding your requirements. Eventually I can come up with a better idea.

Cheers,
Thomas

**Comment by Thomas-Gelf** [comment]
"specific time" will not happen for now, as it would require a different scheduling architecture - I have to reject this, sorry. Please use one of the proposed workarounds.
