### ISSUE TITLE
How do I add repeat_key arguments?

### ISSUE THREAD

**Issue by hboetes** [Icinga/icingaweb2-module-director#1167]
Been looking for quite some time but I just can't find it.

I have a few partitions which should not be checked by check_disk, so I created a field and I added value and yes the first value was accepted. And then I wanted to add the second value which should be possible somehow so I tried

"value1 value2"
"value*"
"value1,value2"
"[value1,value2]"

They all didn't work. So I tried adding an aditional field, which also isn't possible. Please tell me how I should make this work.

```
        "-X" = {
            description = "Ignore all filesystems of indicated type (may be repeated)"
            repeat_key = true
            value = "$disk_exclude_type$"
```

**Comment by Thomas-Gelf** [comment]
@hboetes: make sure that the field for `disk_exclude_type` is of type Array.

**Comment by hboetes** [comment]
Hello Thomas,

Thanks! That got me thinking. Is it perhaps an idea to automatically select the Array incase the field has a repeat_key? I bet you find a clever way how to display it so people can automatically use multiple fields.

**Comment by hboetes** [comment]
And how exactly do I set the type? It used to be in this window, where I can define the field. But it's no longer there.
![selection_003](https://user-images.githubusercontent.com/2285225/30261268-0e7a8faa-96cc-11e7-9c97-a3a32f11ec7c.png)

**Comment by Thomas-Gelf** [comment]
Dashboard -> Data Fields

**Comment by hboetes** [comment]
Ah thanks. One does have to remember all the various places to find the settings.

**Comment by Thomas-Gelf** [comment]
@hboetes: automatically proposing an Array for Arguments with repeat_key makes sense. There is a related ticket asking for a completely refactoring of that initial form (the one that suggests fields based on Arguments). I'll keep this in mind when tackling that.
