### ISSUE TITLE
Kickstart Wizard - Can not import data

### ISSUE THREAD

**Issue by emissary77** [Icinga/icingaweb2-module-director#1169]
Attempting to import data prints an error message:

`Storing icinga_command[vmware-esx-soap-host-storage-adapter] failed: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails ("director"."icinga_command_var", CONSTRAINT "icinga_command_var_command" FOREIGN KEY ("command_id") REFERENCES "icinga_command" ("id") ON DELETE CASCADE ON UPDATE CASCADE), query was: INSERT INTO icinga_command_var (command_id, varname, varvalue, format) VALUES (?, ?, ?, ?) {array ( 'id' => '2492', 'object_name' => 'vmware-esx-soap-host-storage-adapter', 'object_type' => 'external_object', 'disabled' => 'n', 'methods_execute' => 'PluginCheck', 'command' => 'check_vmware_esx', 'timeout' => 60, 'zone_id' => NULL, )} (DbObject.php:794)`

https://ibb.co/cfCHGv

* Director version: master
* Icinga Web 2 version and modules: 2.4.1, doc 2.4.1, monitoring, 2.4.1, translation 2.4.1
* Icinga 2 version: r2.7.0-1
* Operating System and version: Debian GNU/Linux 9.1 (stretch)
* Webserver, PHP versions: Apache/2.4.25 (Debian), PHP 7.0.19-1 (cli)

**Comment by iamhamidmousavi** [comment]
I am getting the same error on the similar environment. 
Were you able to find the cause of this issue?

**Comment by emissary77** [comment]
[image](https://ibb.co/isY6B5)

Persistent: "NO"

Then it does not work properly. At least with me.

**Comment by iamhamidmousavi** [comment]
Man that was a huge help.
It worked here too.
Thanks a lot.

**Comment by emissary77** [comment]
You are welcome.  ;)
