### ISSUE TITLE
Service template choices doesn't work with Single Service

### ISSUE THREAD

**Issue by Naro370** [Icinga/icingaweb2-module-director#1171]
I have created a Service template choices "Check Execution Speed", with that I easy can set the check interval of a service. This works perfekt for apply rules, but not for single services.

## Expected Behavior
Service template choice should work like on a service apply rule.

## Current Behavior
When I add a single service, I see my "Check Execution Speed" combobox, I also can pick something, but after the click on add, it doesn't show up anymore and it also doesn't set this template.
To get it worse, when I want to manuelly set a template in the import list which is configured in that "Check Execution Speed", it immediately disappear.
icingaweb2 confirm that no check_interval is modifed, so it isn't only a display bug.

## Steps to Reproduce (for bugs)
1. Create 2 service templates one for 10m check_interval and one for 60m check_interval
2. Create a Service template choices "Check Execution Speed" with that 2 templates configured
3. Create a new single service.
-> Now you should have "Current Behavior"

## Your Environment
* Director version: master (last update: 08.09.2017)
* Icinga Web 2 version and modules: 2.4.1-2.stretch
* Icinga 2 version: 2.7.0-1.stretch
* Operating System and version: Debian 9 (stretch)
* Webserver, DB, PHP versions: Apache 2.4.25-3+deb9u2, mariadb-10.1.26-0+deb9u1, PHP 7.0.19-1

**Comment by Naro370** [comment]
I can confirm the fix, thank you!

**Comment by Thomas-Gelf** [comment]
You're welcome, thanks for reporting this!
