### ISSUE TITLE
Unassigned single services

### ISSUE THREAD

**Issue by mwaldmueller** [Icinga/icingaweb2-module-director#1172]
![bildschirmfoto 2017-09-11 um 13 10 55](https://user-images.githubusercontent.com/3973350/30271999-bf05ccc4-96f2-11e7-9236-3fb91032ccdb.png)

# Environment

Director version (System - About): master, Git commit: 424fc3136356f6725505567d37f7d4b7ce71fe46
Icinga Web 2 version and modules (System - About): 2.4.1
Icinga 2 version (icinga2 --version): r2.7.0-1
Operating System and version: CentOS Linux release 7.3.1611 (Core)
Webserver, PHP versions: Apache, PHP 5.4.16

**Comment by Thomas-Gelf** [comment]
This feature (showing invalid services) is new, it should however be possible to delete them :laughing:
