### ISSUE TITLE
import source add "director." to tablename

### ISSUE THREAD

**Issue by magheinz** [Icinga/icingaweb2-module-director#1173]
Error when modifing SQL-Statment for import-source
`Error: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'director.glpi_computers' doesn't exist, query was: foobar
`
The table is glpi_computers in database glpi. Before update (git pull) it works, now its not working anymore

## Your Environment
* Director version (System - About): master
* Icinga Web 2 version and modules (System - About): 2.4.1
* Icinga 2 version (`icinga2 --version`): r2.7.0-1
* Operating System and version: debian stretch
* Webserver, PHP versions:apache 2.4.25-3+deb9u2, php 5.6.30+dfsg-0+deb8u1

**Comment by Thomas-Gelf** [comment]
@magheinz: sorry, my fault - please try again!
