### ISSUE TITLE
Data Field as Boolean wont work

### ISSUE THREAD

**Issue by TheCry** [Icinga/icingaweb2-module-director#1184]
## Expected Behavior
If i set a datafield to true or false in the config have to be like:
vars.server_hardware_ilo = true

## Current Behavior
In the current version the datfield writes 
vars.server_hardware_ilo = "true"
I can't assign a service if the datafield is set true

## Possible Solution
Remove the double quote if you use datafield as Boolean

## Steps to Reproduce (for bugs)
1. Add a datafield as boolean
2. Add the new datafield to a host and set to true
3. Add a service with Service Apply Rules (assign where host.vars.server_hardware_ilo == true)

## Context
It is not possible to create an apply rule with a boolean datafield

## Your Environment
* Director version (System - About): master
* Icinga Web 2 version and modules (System - About):
director	master
doc	2.4.1
grafana	1.1.10
map	1.0.3
monitoring	2.4.1
setup	2.4.1
translation	2.4.1
* Icinga 2 version (`icinga2 --version`): icinga2 - The Icinga 2 network monitoring daemon (version: r2.7.0-1)
* Operating System and version: Debian 9
* Webserver, PHP versions: PHP 7.0.19-1
Server built: 2017-07-18T18:37:33

**Comment by tobiasvdk** [comment]
It's working correctly for me using f7353b66283ee3f11e15fd5d616a690ac7b72c4c.

The configuration:
![director_bool](https://user-images.githubusercontent.com/3541433/30442191-fcedfa80-997b-11e7-8e3d-3c5d59c81ef0.png)

Is rendered to:
![director_bool2](https://user-images.githubusercontent.com/3541433/30442192-fcf270f6-997b-11e7-8fa5-b66594b14b11.png)

**Comment by TheCry** [comment]
Mhhh.. I'd updated to the master and the bool is now without double quote.. But to assign a service wont work. This is the config:
object Host "my-server.tld" {
    display_name = "my-server.tld (Backup-Server)"
    address = "***.***.***.***"
    check_command = "hostalive"
    max_check_attempts = "5"
    check_period = "zeitperiode-24x7"
    check_interval = 5m
    retry_interval = 1m
    enable_notifications = true
    enable_active_checks = true
    enable_passive_checks = true
    enable_event_handler = false
    enable_perfdata = true
    volatile = false
    icon_image = "img/icons/serverOS/debian.png"
    icon_image_alt = "Debian"
    vars.ILO_BOARD_VERSION = 4
    vars.ILO_IPADDRESS = "***.***.***.***"
    vars.ILO_PASSWORD = "******"
    vars.ILO_USERNAME = "*******"
    vars.SERVER_ASSIGNMENTGROUP = "*********"
    vars.SERVER_LOCATION = "************"
    vars.icinga_master_zone = "false"
    vars.os = "Linux"
    vars.server_hardware = "HP"
    vars.server_hardware_ilo = true
}


apply Service "HP-Hardware-ILO" {
    check_command = "check_ilo3_health"
    max_check_attempts = "3"
    check_period = "zeitperiode-24x7"
    check_interval = 15m
    retry_interval = 1m
    enable_notifications = true
    enable_active_checks = true
    enable_passive_checks = false
    enable_event_handler = true
    enable_perfdata = true
    volatile = false
    assign where host.vars.server_hardware == "HP" && host.vars.server_hardware_ilo && host.vars.ILO_BOARD_VERSION > 2

    import DirectorOverrideTemplate
}
