### ISSUE TITLE
Import source: Can't change the priority of modifiers

### ISSUE THREAD

**Issue by Naro370** [Icinga/icingaweb2-module-director#1187]
When I try to change the priority of modifiers in an import source, I got following stacktrace:
```
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '5-2' for key 'idx_prio', query was: UPDATE import_row_modifier m SET priority = CASE WHEN id = 17 THEN 2 ELSE 1 END WHERE id IN (17, 18) AND (m.source_id = '5') (Pdo.php:225)

#0 /usr/share/icingaweb2/library/vendor/Zend/Db/Statement.php(297): Zend_Db_Statement_Pdo->_execute(Array)
#1 /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Abstract.php(470): Zend_Db_Statement->execute(Array)
#2 /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Pdo/Abstract.php(232): Zend_Db_Adapter_Abstract->query('UPDATE import_r...', Array)
#3 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Web/Table/Extension/ZfSortablePriority.php(132): Zend_Db_Adapter_Pdo_Abstract->query('UPDATE import_r...')
#4 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Web/Table/Extension/ZfSortablePriority.php(41): Icinga\Module\Director\Web\Table\PropertymodifierTable->moveRow(17, 'down')
#5 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Web/Table/Extension/ZfSortablePriority.php(188): Icinga\Module\Director\Web\Table\PropertymodifierTable->reallyHandleSortPriorityActions()
#6 /usr/share/icingaweb2/modules/director/library/Director/Web/Table/PropertymodifierTable.php(42): Icinga\Module\Director\Web\Table\PropertymodifierTable->renderWithSortableForm()
#7 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Html/Html.php(171): Icinga\Module\Director\Web\Table\PropertymodifierTable->render()
[...]
```

## Expected Behavior
A click on the little arrows in the prio column, should change position.

## Current Behavior
Stacktrace (I tested on multiple types of import sources)

## Steps to Reproduce (for bugs)
1. Create Import source of any typ, but for example with ldap an fill out the form.
2. Create two modifer
3. Try to change prio with that arrow symbols

## Your Environment
* Director version: master (last update: 14.09.2017)
* Icinga Web 2 version and modules: 2.4.1-2.stretch
* Icinga 2 version: 2.7.0-1.stretch
* Operating System and version: Debian 9 (stretch)
* Webserver, DB, PHP versions: Apache 2.4.25-3+deb9u2, mariadb-10.1.26-0+deb9u1, PHP 7.0.19-1

**Comment by Thomas-Gelf** [comment]
F***. Thanks @Naro370 for reporting this. From [MySQL - InnoDB foreign key constraints](https://dev.mysql.com/doc/refman/5.7/en/innodb-foreign-key-constraints.html):

> Like MySQL in general, in an SQL statement that inserts, deletes, or updates many rows, InnoDB checks UNIQUE and FOREIGN KEY constraints row-by-row. [..]  According to the SQL standard, the default behavior should be deferred checking. That is, constraints are only checked after the entire SQL statement has been processed.

Well. Good to learn that they at least know what the default behavior SHOULD be :-/

**Comment by Naro370** [comment]
Maybe you can put all in one transaction?
To clarify that, properties of a sync rule, can move without a problem. Only the modifiers in the import source have that problem. In my mind the code for that up/down move should be very similar, so maybe the answer for the fix is already in the code of the sync rule.

**Comment by Thomas-Gelf** [comment]
Sync rule has no unique constraint for historic reasons. Sooner or later it will be adjusted, there is no more reason other than "the migration is complicated" for keeping the status quo. Just, right now this has the effect that re-ordering priorities works for Sync properties and doesn't for Import modifiers. A transaction wouldn't help. All one can do is changing one of the affected rows to "some other, unused value", then change the other one, then once again the first one. Problem: that number could already be in use by another row. We could "set A to zero, B to former A, A to former B". Would work, but is not correct, as in theory someone else could switch order for another pair of rows - and you would experience a collision. Setting both to negative numbers first would also be an option, but require another DB migration as that field is unsigned. I will fix this in some way, but I really hate it being forced to something so stupid :-(

**Comment by Thomas-Gelf** [comment]
Stupid database - stupid solution.
