### ISSUE TITLE
Director jobs run --forever failing silently 

### ISSUE THREAD

**Issue by mbassett** [Icinga/icingaweb2-module-director#1194]
Ever since upgrading to latest master branch a few weeks ago my director job runner has been dying unexpectedly.   It always worked perfectly before but now after a day or so it seems to just die.   I launched a screen session and ran it interactively with icingacli director jobs run --forever --verbose    and I just get logs like  
```
Director JobRunner is starting "Import EC2 Hosts"
Director JobRunner is starting "Sync VPC Hosts"
Director JobRunner is starting "Sync Ldap"
Director JobRunner is starting "Import EC2 Hosts"
Director JobRunner is starting "Sync VPC Hosts"
Director JobRunner is starting "Sync Ldap"
```

Then it just stops working.  No error output, nothing, it just isn't running anymore.

## Expected Behavior
Jobs run every 900s

## Current Behavior
Jobs run every 900seconds... until the runner dies and then no more jobs get run.

## Possible Solution
?

## Your Environment

* Director version (System - About): master
* Icinga Web 2 version and modules (System - About): 2.4.1
* Icinga 2 version (`icinga2 --version`):  v2.6.3
* Operating System and version: Centos 7.3.1611 x86_64 
* Webserver, PHP versions: httpd-2.4.6-45,  php 5.4.16

**Comment by Thomas-Gelf** [comment]
This has been improved with the new background daemon in v1.7
