### ISSUE TITLE
Kickstart Assistant with PostgreSQL Database

### ISSUE THREAD

**Issue by pseudoab80** [Icinga/icingaweb2-module-director#1196]
- fresh icinga installation
- when do an import  with the Kickstart Assistant, one of the following two errors occur everytime I click the Import-Button:
```
Storing director_activity_log[] failed: SQLSTATE[23514]: Check violation: 7 ERROR:
new row for relation "director_activity_log" violates check constraint
"director_activity_log_check" DETAIL: Failing row contains (1, icinga_endpoint,
myhost.domain.de, create, null, {"apiuser":"director","host":"myhost.domain.de",
"l..., xxx, 2017-09-20 10:48:25+02, \x0e663562303365306532323234666363323337383065663761666132303964..., \x78).,
query was: INSERT INTO director_activity_log (object_name, action_name,
object_type, old_properties, new_properties, author, change_time, checksum,
parent_checksum) VALUES (?, ?, ?, ?, ?, ?, ?,
'\x0ef5b03e0e2224fcc23780ef7afa209d5e0e1896', '\x') {array ( 'id' => NULL,
'object_name' => 'myhost.domain.de', 'action_name' =>
'create', 'object_type' => 'icinga_endpoint', 'old_properties' => NULL, 'new_properties' =>
'{"apiuser":"director","host":"myhost.domain.de","log_duration":86400,"object_name":
"myhost.domain.de","object_type":"external_object","port":"5665","zone":"myhost.domain.de"}',
'author' => 'xxx', 'change_time' => '2017-09-20 10:48:25', 'checksum' =>
'��>"$��7��z� �^�', 'parent_checksum' => NULL, )} (DbObject.php:794)
```
```
Storing director_activity_log[] failed: SQLSTATE[22021]: Character not in repertoire:
7 ERROR: invalid byte sequence for encoding "UTF8": 0x82, query was:
INSERT INTO director_activity_log (object_name, action_name, object_type, old_properties,
new_properties, author, change_time, checksum, parent_checksum) VALUES (?, ?, ?, ?, ?, ?, ?,
'\x824e1f172f65e252ae9f0b7158e81dae945d163b', '\x') {array ( 'id' => NULL, 'object_name' =>
'global-templates', 'action_name' => 'create', 'object_type' => 'icinga_zone', 'old_properties' =>
NULL, 'new_properties' => '{"is_global":true,"object_name":"global-templates",
"object_type":"external_object"}','author' =>'xxx', 'change_time' => '2017-09-20 10:42:09', 'checksum' =>
'�N/e�R��qX���];', 'parent_checksum' => NULL, )} (DbObject.php:794)
```

## Expected Behavior

Import finishes without errors

## Current Behavior

Errors during Import with kickstart assistant

## Possible Solution

?

## Context

Additional to the PostgreSQL-Installation I installed MariaDB and put the director-Database there. In this constellation the import finishes without errors.

## Your Environment

* Director version (System - About): master
* Icinga Web 2 version and modules (System - About): 2.4.1
* Icinga 2 version (`icinga2 --version`): r2.7.0-1
* Operating System and version: Ubuntu 16.04.3 LTS (Xenial Xerus)
* Webserver, PHP versions: Apache/2.4.18 (Ubuntu), PHP 7.0.22
* DBMS: PostgreSQL 9.6.5 installed from Source

**Comment by mbassett** [comment]
This sounds like the encoding of your database was not set to UTF-8

when creating the db you need to do something like...
```
CREATE DATABASE "director_db"
    WITH OWNER "postgres"
    ENCODING 'UTF8'
    LC_COLLATE = 'en_US.UTF-8'
    LC_CTYPE = 'en_US.UTF-8'
    TEMPLATE template0;
```

**Comment by pseudoab80** [comment]
Encoding is already set to UTF8. Only Collate and Ctype was set to de_DE.UTF-8. I even tested with Collate and Ctype set to 'en_US.UTF-8' but Error-Message remains the same.

When you analyze the first Error-Message: Here the Table-Constraint 'director_activity_log_check' is violated. Definition of Constraint is:
```
CONSTRAINT director_activity_log_check CHECK (parent_checksum IS NULL OR length(checksum) = 20)
```
When I look at Database-Log following INSERT-Statement is executed:
```
INSERT INTO director_activity_log (object_name, action_name,
object_type, old_properties, new_properties, author, change_time, checksum,
parent_checksum) VALUES 
('myhost.domain.de',
'create',
'icinga_endpoint',
NULL,
'{"apiuser":"director","host":"myhost.domain.de","log_duration":86400,"object_name":
"myhost.domain.de","object_type":"external_object","port":"5665","zone":"myhost.domain.de"}',
'fab',
'2017-09-20 10:48:25',
'\x0ef5b03e0e2224fcc23780ef7afa209d5e0e1896',
'\x');
```
The attribute 'checksum' has not a length of 20 characters and also the 'parent_checksum' is not NULL as expected by the constraint 'director_activity_log_check'

**Comment by pseudoab80** [comment]
Sorry, there was no solution. A few days ago I buried my icinga testserver :-(

**Comment by jamescalver** [comment]
Dang! Not what I was hoping to hear. Since you tried it on a non-postgres DB and it worked, it makes me think it's something with postgres, but my debugging skills can't take me farther than that.

**Comment by nbuchwitz** [comment]
Just tried a fresh postgres database with latest release and even master of the director - both are working as expected. Which postgres version do you use? What does the output of ``sudo -u postgres psql postgres -c "\l"`` look like?
