### ISSUE TITLE
Config sync between directors

### ISSUE THREAD

**Issue by matthenning** [Icinga/icingaweb2-module-director#1197]
We have multiple deployment stages in our environment and in many cases we build a lot of templates, commands, etc in our integration environment and at some point need to merge all changes to our production environment.

It would be nice to have this automated in some way.

One option would be an incremental sync by pushing deployments to another director.
Maybe this could be implemented by adding another director DB as a resource and a job which performs the sync.

I'd be happy to help building a solution for this but at this point I'm not sure where to start.

**Comment by mbassett** [comment]
Seems like the easiest way to accomplish this would just be doing a sql/pg dump of the director database and restore it into your other environments.  If you want it automated you can use a cron job with the appropriate permissions, or write a small shell script that can be executed to dump and restore from one env to another.

**Comment by matthenning** [comment]
I only want to sync templates though. Not the entire configuration including hosts etc.

**Comment by mbassett** [comment]
Well that's fine, just dump the tables that you really care about and restore those.

**Comment by matthenning** [comment]
In that case I would need to export all items from icinga_host of type template to avoid exporting host objects which will lead to ID conflicts with the host objects in the target db and broken assignments of service templates.

**Comment by Thomas-Gelf** [comment]
IMHO [v1.6.0](https://icinga.com/2018/12/10/director-v1-6-0-is-available/) implemented what you have been looking for.
