### ISSUE TITLE
Use OpenAPI-Specification (Swagger) for the Definition of the REST-API

### ISSUE THREAD

**Issue by AdaptiveThinking** [Icinga/icingaweb2-module-director#1198]
Right now there is only a very basic Documentation for the REST-API.
Using a Standard like https://www.openapis.org/, which is also backed by Major Companies, sould make this easier, because there are well define Tools for this. (e.g. https://swagger.io/swagger-codegen/)

Documentation ist then created automatically, see e.g. https://code.vmware.com/apis/62/vcenter-management#/ or http://petstore.swagger.io/

**Comment by Thomas-Gelf** [comment]
Thanks for the suggestion, but we're not going to use swagger for now.
