### ISSUE TITLE
Icingaweb2 Director - Activity Log - Undefined offset when attempting to deploy changes

### ISSUE THREAD

**Issue by opticgeist** [Icinga/icingaweb2-module-director#1206]
Icingaweb2 Director - Activity Log - Undefined offset: 384 (TemplateTree.php:186)
Failed to load icinga_service for host_id IS NULL AND service_set_id IS NULL AND object_name = 'HTTP - Custom Service check' AND object_type = 'template'

This issue references to #1115 

```
#0 /usr/share/icingaweb2/modules/director/library/Director/Resolver/TemplateTree.php(186): Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(8, 'Undefined offse...', '/usr/share/icin...', 186, Array)
#1 /usr/share/icingaweb2/modules/director/library/Director/Resolver/TemplateTree.php(126): Icinga\Module\Director\Resolver\TemplateTree->getParentsById('384')
#2 /usr/share/icingaweb2/modules/director/library/Director/Resolver/TemplateTree.php(105): Icinga\Module\Director\Resolver\TemplateTree->getParentsFor(Object(Icinga\Module\Director\Objects\IcingaServiceSet))
#3 /usr/share/icingaweb2/modules/director/library/Director/Repository/IcingaTemplateRepository.php(40): Icinga\Module\Director\Resolver\TemplateTree->listParentIdsFor(Object(Icinga\Module\Director\Objects\IcingaServiceSet))
#4 /usr/share/icingaweb2/modules/director/library/Director/Repository/IcingaTemplateRepository.php(79): Icinga\Module\Director\Repository\IcingaTemplateRepository->getTemplatesFor(Object(Icinga\Module\Director\Objects\IcingaServiceSet), false)
#5 /usr/share/icingaweb2/modules/director/library/Director/Objects/IcingaObjectImports.php(278): Icinga\Module\Director\Repository\IcingaTemplateRepository->getTemplatesIndexedByNameFor(Object(Icinga\Module\Director\Objects\IcingaServiceSet))
#6 /usr/share/icingaweb2/modules/director/library/Director/Objects/IcingaObjectImports.php(350): Icinga\Module\Director\Objects\IcingaObjectImports->loadFromDb()
#7 /usr/share/icingaweb2/modules/director/library/Director/Objects/IcingaObject.php(815): Icinga\Module\Director\Objects\IcingaObjectImports::loadForStoredObject(Object(Icinga\Module\Director\Objects\IcingaServiceSet))
#8 /usr/share/icingaweb2/modules/director/library/Director/Objects/IcingaServiceSet.php(73): Icinga\Module\Director\Objects\IcingaObject->imports()
#9 /usr/share/icingaweb2/modules/director/library/Director/Objects/IcingaServiceSet.php(121): Icinga\Module\Director\Objects\IcingaServiceSet->getServiceObjects()
#10 /usr/share/icingaweb2/modules/director/library/Director/IcingaConfig/IcingaConfig.php(696): Icinga\Module\Director\Objects\IcingaServiceSet->renderToConfig(Object(Icinga\Module\Director\IcingaConfig\IcingaConfig))
#11 /usr/share/icingaweb2/modules/director/library/Director/IcingaConfig/IcingaConfig.php(674): Icinga\Module\Director\IcingaConfig\IcingaConfig->createFileForObjects('serviceSet', Array)
#12 /usr/share/icingaweb2/modules/director/library/Director/IcingaConfig/IcingaConfig.php(476): Icinga\Module\Director\IcingaConfig\IcingaConfig->createFileFromDb('serviceSet')
#13 /usr/share/icingaweb2/modules/director/library/Director/IcingaConfig/IcingaConfig.php(269): Icinga\Module\Director\IcingaConfig\IcingaConfig->generateFromDb()
#14 /usr/share/icingaweb2/modules/director/library/Director/IcingaConfig/IcingaConfig.php(305): Icinga\Module\Director\IcingaConfig\IcingaConfig->hasBeenModified()
#15 /usr/share/icingaweb2/modules/director/library/Director/IcingaConfig/IcingaConfig.php(258): Icinga\Module\Director\IcingaConfig\IcingaConfig->storeIfModified()
#16 /usr/share/icingaweb2/modules/director/application/controllers/ConfigController.php(283): Icinga\Module\Director\IcingaConfig\IcingaConfig::generate(Object(Icinga\Module\Director\Db))
#17 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Director\Controllers\ConfigController->storeAction()
#18 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('storeAction')
#19 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#20 /usr/share/php/Icinga/Application/Web.php(389): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#21 /usr/share/php/Icinga/Application/webrouter.php(109): Icinga\Application\Web->dispatch()
#22 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...')
#23 {main}

```

## Expected Behavior

Remove service set from Host Template.  

## Current Behavior

Remove service set from Host Template.  However it removed the service set completely - creates pending delete serviceset  in Activity Log

## Steps to Reproduce (for bugs)

1.  Search for host = somehostname
`https://icingaserver.somewhere.com/icingaweb2/search?q=hostname01`
2. Click on Hostname
`https://icingaserver.somewhere.com/icingaweb2/monitoring/host/show?host=hostname01.somewhere.com`
3. Click on Host Object, From Problem Handling > Actions: click Modify, then click Services tab in right pane
`https://icingaserver.somewhere.com/icingaweb2/monitoring/host/show?host=hostname01.somewhere.com#!/icingaweb2/director/host/services?name=hostname01.somewhere.com`
4.  Drill down to someService set (This set has been inherited from TemplateName_03)
HTTP - Custom Service check
`https://icingaserver.somewhere.com/icingaweb2/director/host/services?name=hostname01.somewhere.com#!/icingaweb2/director/host/services?name=TemplateName_03`
This is the Template: TemplateName_03, Services tab
click remove someService (Service set), 
This did not simply remove the service set from the Template: TemplateName_03,  it deleted the service-set, which then deleted the service.   Which should 'Remove this set from this host'
`https://icingaserver.somewhere.com/icinagweb2/director/host/removeset?name=TemplateName_03&setId=384`

THE NEXT STEP IS WHERE I MADE CRUCIAL ERROR. That compounded  the issue.

5. I saw the Activity Log with a pending update to delete the service set "someService"
_x [opticgeist] delete the service set "someService"  15:36:17_ 
If you click on the word 'delete' that then  Show details related to this change

6. I then chose the action to 'Restore former object'.   That created the second Staged Configuration change in the Activity Log
_+ [opticgeist] create service set "someService" 15:58:48_

7. I attempted to deploy 2 pending changes - voila it failed to deply
**Undefined offset: 384 (TemplateTree.php:186)**
Failed to load icinga_service for host_id IS NULL AND service_set_id IS NULL AND object_name = 'HTTP - Custom Service check' AND object_type = 'template'

## Context

Unable to deploy an further pending changes.

## Your Environment

* Director version (System - About): master << last git lists as master instead of version number
* Icinga Web 2 version and modules (System - About): 2.4.1
* Icinga 2 version (`icinga2 --version`):  version: v2.6.2 
* Operating System and version: CentOS Linux release 7.3.1611 (Core) - kernel 3.10.0-514.6.1.el7.x86_64
* Webserver, PHP versions:  PHP 5.4.16 (cli) (built: Nov  6 2016 00:29:02), Zend Engine v2.4.0,

**Comment by opticgeist** [comment]
## Possible Solution


Work-around:
I had to enlist the help of Unix sysadmin, and he performed restored a backup of /var/lib/mysql from CommVault from two days prior.  Then started up a fresh install of MySQL into that directory and created a SQL dump of the director database.


The sysadmin then restored that version of director into the director database on icingaserver.somewhere.com.   Due to some schema changes that were performed in the interim, the sysadmin had to do another work-around by creating a new database: director1.  Director on icingaserver.somewhere.com now uses director1.

**Comment by ktella** [comment]
I just got hit with this BUG in my PROD env with no backups :(. I need some help here.

**Comment by ktella** [comment]
Fixed it manually in DB with update queries.

**Comment by jschoone** [comment]
We have the same problem. What update queries did you do?

**Comment by Wintermute2k6** [comment]
Is this Issue still persistent with the Director Release Version 1.4.2 ?
Regards

David

**Comment by jschoone** [comment]
No, is fixed for us. Thank you.

Jan

**Comment by ThorHammerTime** [comment]
FWIW The SQL error we found was a matching service_set_id and parent_service_set_id in the icinga_service_set_inheritance table. The matching service and parent id was causing the error. Updating this table cleared the error message.

```
mysql> SELECT * FROM icinga_service_set_inheritance;
+----------------+-----------------------+--------+
| service_set_id | parent_service_set_id | weight |
+----------------+-----------------------+--------+
|              2 |                     1 |      1 |
|              5 |                     3 |      1 |
|              6 |                     6 |      1 |
+----------------+-----------------------+--------+
```

**Comment by opticgeist** [comment]
I have not experiencing issues since restoring, but have not attempted to recreate due to production systems.

**Comment by Mike-Benoit** [comment]
We were just hit by this same bug as well. :( 

Icinga Web: v2.5.0 and Director: v1.4.3

**Comment by syrof** [comment]
@ThorHammerTime
Thanks for your tip.

@Mike-Benoit
No **service_set_id** can be a **parent_service_set_id** for itself.
Find your _object_ and _template_ in **icinga_service_set** and assign _object_ to appropriate _template_ in **icinga_service_set_inheritance** table.
