### ISSUE TITLE
missing select service. *property* with v1.4.0 master

### ISSUE THREAD

**Issue by michaeleino** [Icinga/icingaweb2-module-director#1207]
there is no service property can be selected there is only host properties, but when it is manually typed it works great

Just revoking to version 1.3.2 all properties all applicable (hosts/services/hosts custom vars)

##Environment
* Director version (System - About): master/ commit d41fbbf63499eba86fe85f835cde5fa8d34a1f39
* Icinga Web 2 version and modules (System - About): 2.4.2
* Icinga 2 version (`icinga2 --version`):  r2.7.1-1
* Operating System and version: Ubuntu 16.04.3 LTS
* Webserver, PHP versions: nginx/1.10.3, PHP 7.0.22-0ubuntu0.16.04.1

**Comment by Thomas-Gelf** [comment]
Thanks for reporting this!

**Comment by michaeleino** [comment]
thanks a lot Thomas,
I have pulled 9e193dbc6b2f3600d393eaf9c9c8668d40c5e7ef ... it is partially solved.
There is no service property list on "host groups" and "service set" forms.

**Comment by Thomas-Gelf** [comment]
@michaeleino: thanks fot this hint!

**Comment by Thomas-Gelf** [comment]
@michaeleino: wait... assigning Hostgroups and ServiceSet based on service properties? r u sure?

**Comment by michaeleino** [comment]
:D
@Thomas-Gelf yup you are right, this is disordered with me.. I'll close it :)
Thanks a lot :+1:
