### ISSUE TITLE
Allow sync for object type dependency

### ISSUE THREAD

**Issue by dgoetz** [Icinga/icingaweb2-module-director#1209]
## Expected Behavior
Allow to sync dependency with all its attributes and assign where filters.

## Current Behavior
Sync rules do not allow to select the object type dependency.

## Context
In the import source are a couple of routers which are the parent host for other hosts in the same location. Creating and maintaining them automatically instead of manually would reduce the workload.

## Your Environment
* Director version (System - About): Git Master 6980544
* Icinga Web 2 version and modules (System - About): 2.4.1
* Icinga 2 version (icinga2 --version): 2.7.1
* Operating System and version: RHEL 7
* Webserver, PHP versions: Apache 2.4, PHP 5.4.45

**Comment by darkounet** [comment]
+1 👍

**Comment by bahamut45** [comment]
+1 👍

**Comment by vita2** [comment]
sorry for the ref spam. there is something gone wrong :confused:
