### ISSUE TITLE
Fatal Error when selecting a Service Template

### ISSUE THREAD

**Issue by fideldidum** [Icinga/icingaweb2-module-director#1210]
after pulling the latest version of director, when i select a service template the following error is displayed:
(this happens only with service templates, single services, apply rules, etc. seem to work...)

Fatal error: Uncaught ErrorException: Creating default object from empty value in /usr/share/php/Icinga/Web/Controller/ActionController.php:113 Stack trace: #0 /usr/share/php/Icinga/Web/Controller/ActionController.php(113): Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(2, 'Creating defaul...', '/usr/share/php/...', 113, Array) #1 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(59): Icinga\Web\Controller\ActionController->__construct(Object(Icinga\Web\Request), Object(Icinga\Web\Response), Array) #2 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response)) #3 /usr/share/php/Icinga/Application/Web.php(389): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response)) #4 /usr/share/php/Icinga/Application/webrouter.php(109): Icinga\Application\Web->dispatch() #5 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...') #6 {main} Next Zend_Co in /usr/share/icingaweb2/library/vendor/Zend/Controller/Plugin/Broker.php on line 332

## Environment
* Director version (System - About): master
* Icinga Web 2 version and modules (System - About): 2.4.2
* Icinga 2 version (`icinga2 --version`): 2.7.1-1
* Operating System and version: ubuntu 16.04.3
* Webserver, PHP versions: apache 2.4.18 , 7.0.22

let me know if more information is needed

**Comment by Thomas-Gelf** [comment]
Sorry, my fault - broke it this morning

**Comment by fideldidum** [comment]
work again, thanx! :)
