### ISSUE TITLE
set_if option does not result in field

### ISSUE THREAD

**Issue by hboetes** [Icinga/icingaweb2-module-director#1221]
In the `nginx_status` command there is this section:
```
        "--ssl" = {
            description = "Wether we should use HTTPS instead of HTTP"
            set_if = "$nginx_status_ssl$"
        }
```
Alas this does not provide a boolean variable/field which I can set. Even after running the kickstart wizard again. Am I missing something or should this result in field in `/icingaweb2/director/command/fields`?

**Comment by Thomas-Gelf** [comment]
This duplicates #514. As a workaround please go from your Director Dashboard to your Data Fields, create a boolean field for `nginx_status_ssl` with a nice label and description - and then go back to your command. You'll be allowed to add your new field and everything should work as expected. To make this step easier we'll combine those two forms in future.

Cheers,
Thomas

**Comment by hboetes** [comment]
Thanks Thomas, that works indeed.
