### ISSUE TITLE
Inheritance Loop (Vererbungsschleife Director)

### ISSUE THREAD

**Issue by kevinstiller** [Icinga/icingaweb2-module-director#1229]
Im Director ist es möglich ein Template innerhalb eines anderes wieder in sich selbst zu vererben.
Praktisch:
- Oberes Template
-- Zweites das vom oberen Template erbt

Das obere Template hat als Vorlage das untere, und das untere hat das obere...
Ich kann leider keine Screenshots dazu liefern, da ich folgende Fehler bekomme:

`Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 130968 bytes) in /usr/share/icingaweb2/modules/director/library/Director/Resolver/TemplateTree.php on line 243
`

Wenn ich via Director die kaputte Config ausrollen will kommt:

`Fatal error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 130968 bytes) in /usr/share/icingaweb2/modules/director/library/Director/Objects/IcingaObject.php on line 158
`

Aufbau:
Single Instanz
CentOS 7 (aktuell)
Icinga2 (aktuell)
Icingaweb2 (aktuell)
Director (aktuell)

**Comment by kevinstiller** [comment]
https://monitoring-portal.org/index.php?thread/42087-vererbungsschleife-director/#post257213

**Comment by Thomas-Gelf** [comment]
We'll address this with #1631
