### ISSUE TITLE
Can't test for null in Sync rule properties Filter Expression

### ISSUE THREAD

**Issue by druchoo** [Icinga/icingaweb2-module-director#1230]
## Expected Behavior

And Filter Expression of `my_column=null` should work

## Current Behavior

Doesn't work

## Steps to Reproduce (for bugs)

1. Ensure import source has column with null value
2. Create Sync rule property Filter Expression like `my_column=null`
3.
4.

## Context

Trying to apply properties where for columns with null values and cannot. I'm not able to change import data at this time.

## Your Environment

* Director version (System - About): c9c59b3f0324838b858a8a66ee5f81f7d69e6a32
* Icinga Web 2 version and modules (System - About): 2.4.2
* Icinga 2 version (`icinga2 --version`): 2.7.1-1
* Operating System and version: CentOS Linux release 7.2.1511 (Core)
* Webserver, PHP versions: nginx-1.12, PHP 5.4.16

**Comment by Thomas-Gelf** [comment]
The shown expression checks for the string value "null" and therefore doesn't match, writing `!my_column` might work. But still, filters at a Sync Rule level are a special beast, you should try to avoid using them. They make Director "blind" for matching objects, and when it goes to purging them they might not have the desired effect. In the current master there is a property modifier allowing you to black- or whitelist rows based on a specific property with a dedicated NULL check. It will be part of v1.5.0 and should be your tool of choice for this task.

**Comment by NeverUsedID** [comment]
I'am on the same problem here.

I have a mysql hostlist where on some devices a value is NULL. F.e. i have a custom vars "provider" and on some hosts this information is missing. The import run will create a host with a 'customvar vars.provider = ""' which will break applyrules, as now the custom var exists. I havn't found a way to not add the custom var if it is NULL.

**Comment by rikustm** [comment]
Accidently figured it out. To exclude null values use !property= 
(no wildcard or quotation marks)

![image](https://user-images.githubusercontent.com/39823818/161292592-63201c12-cae6-40e2-a211-a5f6f2f0d9c5.png)
