### ISSUE TITLE
Array of Datalist-Objects

### ISSUE THREAD

**Issue by chas0rde** [Icinga/icingaweb2-module-director#1233]
Director currently only allows one item per datalist to be selected (e.g. on Host field)

## Expected Behavior
Director should allow Datafields of type Datalist to be either single (drop down) or multiple item (like array type).

## Current Behavior
Datafields of type Datalist are always Drop-Down selections in objects

## Possible Solution
see Expected Behavior

## Steps to Reproduce (for bugs)

1.Create a datalist with multiple values
2.Create a datafield of the datalist
3.Assign e.g. to host

## Context
Trying to e.g. create a datalist of "common SNMP OIDs" which should then be multi-selectable per host.
Service checks should then created via apply-for

## Your Environment

* Director version (System - About): 1.3.1
* Icinga Web 2 version and modules (System - About): 2.4.2
* Icinga 2 version (`icinga2 --version`):  r2.7.1-1
* Operating System and version: ubuntu 16.04.3 LTS
* Webserver, PHP versions: apache 2.4.18-2ubuntu3.5, php 7.0+35ubuntu6

**Comment by Thomas-Gelf** [comment]
This duplicates #1080, has been implemented for v1.4.0.

**Comment by chas0rde** [comment]
Searched but did not find ;) Sorry and great to hear that it is in the 1.4.0 :)
