### ISSUE TITLE
Make info bubbles hideable

### ISSUE THREAD

**Issue by widhalmt** [Icinga/icingaweb2-module-director#1239]
While the blue bubbles on forms are really useful for showing details about configurable options, in some cases they get in the way. (e.g. you have to use a workstation with an old projector as monitor which restricts the maximum resolution)

Please add a way to hide these bubbles temporarily.

**Comment by Thomas-Gelf** [comment]
Sadly I had the same experience and I really regret to have switched from the former variant (directly below the field) to the current one. This happened on behalf of users working mostly with their mouse while being unable to focus and click the next form element within the predefined 2 second delay :-/ Using the TAB key would probably be too efficient :imp:

I hear you. Eventually I'll revert to the former styling and add a toggle allowing one to switch context help on or off.

**Comment by linuxmail** [comment]
hi,

I have the same problem. The bubble is a bit annoying ... take a look on the picture.
![bildschirmfoto von 2018-02-09 15-09-05](https://user-images.githubusercontent.com/1276233/36031507-43ff0d8a-0dab-11e8-85d9-aab132518556.png)

**Comment by doctore74** [comment]
+1!

**Comment by cstegm** [comment]
+1

**Comment by freddy4711** [comment]
+1

**Comment by Thomas-Gelf** [comment]
Listening to requests that asked for moving form element descriptions away has been an error, the fix for this will be a revert of the former change in #1510.
