### ISSUE TITLE
Data field of type Array from Datalist not shown in apply for

### ISSUE THREAD

**Issue by chas0rde** [Icinga/icingaweb2-module-director#1241]
Since version 1.4.0 it is possible to create data fields of type Datalist that are represented as arrays.
Those fields cannot be used for apply-for services

## Expected Behavior
Director should allow Datafields of type Datalist to be either single (drop down) or multiple item (like array type).
Director should allow apply for services based on custom datafields 

## Current Behavior
Datafields of type Datalist are always Drop-Down selections in objects

Only other array type datafields are shown in apply-for dropdown

## Possible Solution
see Expected Behavior

## Steps to Reproduce (for bugs)

1.Create a datalist with multiple values
![image](https://user-images.githubusercontent.com/5859679/31609081-0a1863c0-b273-11e7-8e92-545c50b19059.png)
2.Create a datafield of the datalist select target data type array
![image](https://user-images.githubusercontent.com/5859679/31609106-1e57c4f2-b273-11e7-8015-365620c40593.png)
3.Assign e.g. to host and fill with values
![image](https://user-images.githubusercontent.com/5859679/31609142-43988558-b273-11e7-9bc6-c466ce1be8db.png)
4. Try creating a service apply-for and see datafield not being listed:
![image](https://user-images.githubusercontent.com/5859679/31609181-65afaaa4-b273-11e7-9e41-333344ac7b29.png)

## Context
Trying to e.g. create a datalist of "common SNMP OIDs" which should then be multi-selectable per host.
Service checks should then created via apply-for

## Your Environment

* Director version (System - About): 1.4.0
* Icinga Web 2 version and modules (System - About): 2.4.2
* Icinga 2 version (`icinga2 --version`):  r2.7.1-1
* Operating System and version: ubuntu 16.04.3 LTS
* Webserver, PHP versions: apache 2.4.18-2ubuntu3.5, php 7.0+35ubuntu6

**Comment by NeverUsedID** [comment]
Just to be sure: you already have a host that is using this array ? You can't create a "apply for", before the custom variable is used by at least one host.

**Comment by chas0rde** [comment]
Hello
yes I have. I am aware that otherwise it wouldn't be available.
Also added a second value to ensure it really is an array.

Preview of host config shows the var as array ("[....]" in definition)

**Comment by NeverUsedID** [comment]
Hi,

so, I tested it myself and I can reproduce the issue.

I wasn't aware that this feature now exist but it is a very nice feature that would make some things a lot easier. I would love to see my "services" custom var as array with predefined list :)

**Comment by chas0rde** [comment]
Yes this feature, once fixed, will be quite nice :) Would allow the icinga-admin to define preselections for "users" (normal admins ;) ) easing the process of service definition and limiting error-proness

**Comment by NeverUsedID** [comment]
Look like you can still use it by just type it in completely. Only the filtered view doesn't work.

**Comment by dheule** [comment]
Vote for this bug, we need this to.

**Comment by dheule** [comment]
Thank you !

**Comment by Thomas-Gelf** [comment]
You're welcome!

**Comment by necarnot** [comment]
> Just to be sure: you already have a host that is using this array ? You can't create a "apply for", before the custom variable is used by at least one host.

Hi,

Sorry for digging out this topic, but I found myself stopped by this issue today, on a very recent version of icinga+director (now, in 2023 dec.) : I had to

- create a fake host and add it the custom variable I intended to use in the "For" dropdown of an apply rule
- finally get access to this new custom variable in the dropdown of the apply rule
- remove the fake host

I had no other mean, it was not possible to write in this field, this was a choose-only dropdown.

This is not ideal.
