### ISSUE TITLE
Fatal error: Allowed memory size of 3221225472 bytes exhausted (tried to allocate 262144 bytes)

### ISSUE THREAD

**Issue by rmalenko** [Icinga/icingaweb2-module-director#1247]
I had created in Host template choices two choices and try edit already enabled Host template choices then I see this error 

```
Fatal error: Allowed memory size of 3221225472 bytes exhausted (tried to allocate 262144 bytes) in /usr/share/icingaweb2/modules/director/library/Director/Resolver/TemplateTree.php on line 222
```
## Your Environment

* Director version: 1.4.0
* Icinga Web 2 version: 2.4.2
* Icinga 2 version: r2.7.1-1
* Operating System and version: Ubuntu 16
* Webserver, PHP versions: PHP 7.0.22-0ubuntu0.16.04.1 (cli) ( NTS )

Application information:
  Installation root: /usr
  Sysconf directory: /etc
  Run directory: /run
  Local state directory: /var
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

System information:
  Platform: Ubuntu
  Platform version: 16.04.3 LTS (Xenial Xerus)
  Kernel: Linux
  Kernel version: 4.4.0-1022-aws
  Architecture: x86_64

Build information:
  Compiler: GNU 5.3.1
  Build host: a9edf83df4f7

**Comment by rmalenko** [comment]
I have the same error trying to deploy...

**Comment by rmalenko** [comment]
I had updated Director and switch to PHP 7.1.11 but the error still presents.

**Comment by wols** [comment]
...also on RH ELS 7.4, PHP 7.1.11

**Comment by Thomas-Gelf** [comment]
That's a lot of memory :p Blind guess: you guys created an inheritance loop. There used to be in place a dedicated safety guard with nice error messages, but it seems that one of the recent caching strategies broke this. Could I be right?

**Comment by wols** [comment]
A Service Template can import itself? My typo :-(

**Comment by wols** [comment]
The error "hides" the 'Delete' button :-(
Should I `delete from icinga_service where id = BAD_ID` ?

**Comment by Thomas-Gelf** [comment]
This should help, yes. You could also clean up the related entry in the `icinga_service_inheritance` table. Do you feel comfortable with this, or do you need some help? And sorry for the inconvenience, it shouldn't happen at all. Just: no easy/nice way to enforce this in the schema (it is possible, sure - but ugly), and "userspace" failed to apply it's checks in your case. My fault, will be fixed.

**Comment by wols** [comment]
No problem. Perfect support here.
`delete from icinga_service_inheritance where service_id = BAD_ID` solves.

**Comment by wols** [comment]
I did it again and must find the `BAD_ID`:
`select * from icinga_service_inheritance where service_id = parent_service_id`

**Comment by mtdeguzis** [comment]
Facing this issue myself

```
Allowed memory size of 1073741824 bytes exhausted (tried to allocate 20480 bytes)

#0 [internal function]: Icinga\Application\Web->Icinga\Application\{closure}()
#1 {main}
```

**Comment by Thomas-Gelf** [comment]
#1631 will address this.
