### ISSUE TITLE
missing sanity check allows a loop

### ISSUE THREAD

**Issue by hboetes** [Icinga/icingaweb2-module-director#1253]
I accidentally added the command itself to the "imports" when creating a new command, which resulted in a forkbomb:

```
Fatal error: Out of memory (allocated 33554432) (tried to allocate 262144 bytes) in /usr/share/icingaweb2/modules/director/library/Director/Resolver/TemplateTree.php on line 176
```

How do I get rid of this command, BTW?

**Comment by hboetes** [comment]
I found out how to get rid of it:

1. c&p the sql from the webinterface:
```
SELECT o.object_name, o.disabled, o.command FROM icinga_command AS o WHERE
                               (object_type = 'object') ORDER BY o.object_name ASC LIMIT 100
```
2. rewrite it a bit so it also shows id
3. now remove the id:
```
SET FOREIGN_KEY_CHECKS=0;
delete FROM icinga_command WHERE id = '219'
SET FOREIGN_KEY_CHECKS=1;
```
4. remove the generated code from the active director directory: `icinga01-1508484763-16/zones.d/director-global/commands.conf`
5. kill and then start icinga2

Is that more or less correct?

**Comment by lazyfrosch** [comment]
Also see #1229 (german language)

**Comment by leeclemens** [comment]
This seems similar to the issue I encountered when I accidentally added the same Host Template to the Includes of a new Host Template. Unfixable through the UI, needed to `delete from icinga_host_inheritance where host_id = parent_host_id`. Maybe a db contraint could prevent this in addition to a future UI fix (do not display/allow self in Includes)?

**Comment by widhalmt** [comment]
Since we had this twice in a customer setup I'd really like to see a way to prevent it from happening.

**Comment by Thomas-Gelf** [comment]
Changed the topic, nothing forks here

**Comment by lazyfrosch** [comment]
:fork_and_knife:

**Comment by Thomas-Gelf** [comment]
We'll address this with #1631
