### ISSUE TITLE
No autocomplete on imports/ check command 

### ISSUE THREAD

**Issue by sysadmama** [Icinga/icingaweb2-module-director#1254]
Hi,

when adding new services/ service templates, there's no autocomplete/ dropdown/ whatever for the fields *Imports* and *Check command*. I have to fill in manually. The only feedback is a red error message when trying to use non existent templates and hitting `TAB` (for check command analogue):
```
Failed to load icinga_service for host_id IS NULL AND service_set_id IS NULL AND object_name = 'test' AND object_type = 'template' (DbObject.php:610)
```

Cheers,
Marianne

## Your Environment

* Director version (System - About): bbb180bb6e67eaa5739e649556c622838c6bb39a
* Icinga Web 2 version and modules (System - About): eb343009bb696e155897dda4decef532242cf9fa
* Icinga 2 version (`icinga2 --version`): r2.7.1-1
* Operating System and version: Debian Jessie
* Webserver, PHP versions: php-5.6.30, apache-2.4.10

**Comment by widhalmt** [comment]
Have you been able to fix this? While imports, etc. are working fine on most installations I know, I just stumbled upon one with the same behavior like you are describing. It's on openSuSE Leap 42.3

**Comment by widhalmt** [comment]
I had the same problem on openSuSE LEAP 42.3 with 

    php -v
    PHP 7.0.7 (cli) ( NTS )
    Copyright (c) 1997-2016 The PHP Group
    Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies

With Director release 1.4.2. 

Opening the browser developer tools and doing a cache-clearing reload of Icinga Web 2 fixed the issue. I'm not sure if I really was too tired to think of emptying the cache myself or if it was @Thomas-Gelf  's magical powers over the internet but fact is, it now works.
