### ISSUE TITLE
a individual service-object can't resolve custom host vars

### ISSUE THREAD

**Issue by vita2** [Icinga/icingaweb2-module-director#1257]
hello tom,

i have created a service-object for a host and would like to fill up some fields with custom host vars. after the deployment i saw that the director doesn't recognizes the constants and puts the host variable into quotation marks.

## Current Behavior
```
object Host "ds111" {
    import "generic-host"
    import "fields-snmp"
    ...

    ...
    vars.snmp_version = "3"
    vars.snmpv3_auth = "abc"
    ...
    vars.snmpv3_user = "xyz"
    ...
}
```
```
object Service "snmp_synology" {
    host_name = "ds111"
    import "snmp_synology"

    vars.snmp_synology_password = "$host.vars.snmpv3_auth$"
    vars.snmp_synology_username = "$host.vars.snmpv3_user$"
}
```

## Your Environment
* Director version (System - About): commit 567d972739aded9b1b40f8eed5fe98986d96da60
* Icinga Web 2 version and modules (System - About): 2.4.2
* Icinga 2 version (`icinga2 --version`): r2.7.1-1
* Operating System and version: Debian Jessie 8.9 (3.16.0-4-amd64)
* Webserver, PHP versions: nginx 1.6.2-5 + php5-fpm 5.6.30

**Comment by Thomas-Gelf** [comment]
Sorry, I'm unable to understand the issue?!

**Comment by vita2** [comment]
regarding my above mentioned configuration the director renders the constants `$host.vars.snmpv3_auth$` and `$host.vars.snmpv3_user$` as string with quotation marks. it doesn't recognizes it as constants so the check-command will get empty strings.

this happens only at individual service-objects assigned to one host. constants in service-apply-rules and service-templates aren't affected.

**Comment by Thomas-Gelf** [comment]
Got confused because of the naming. These are not constants but macros/custom variables in Icinga 2. And they should work as expected this way. Did you try it out?

**Comment by Thomas-Gelf** [comment]
We discussed this elsewhere and have been able to track it down, thanks @vita2! Part of this is a caching issue when the same variable has before been used in a different context. Other part is Icinga 2 behaving differently in objects and apply rules, the host object is not always available as one might expect.

**Comment by vita2** [comment]
thank you so much for helping me with this issue, tom :+1: :beers:

**Comment by Thomas-Gelf** [comment]
You're welcome, thank you for your troubleshooting time helping me to track it down.
