### ISSUE TITLE
Icinga segfault with host in global zone defined

### ISSUE THREAD

**Issue by Mikesch-mp** [Icinga/icingaweb2-module-director#1258]
Yesterday i accidentally configured a host in director-global zone via host tepmplate. This leads to a crash of Icinga during config check.

![image](https://user-images.githubusercontent.com/6574967/31958875-756ebaee-b8f3-11e7-903c-012b229bc44b.png)

## Expected Behavior
Director should tell about error, but not crash icinga.

## Current Behavior
Icinga crashes during config test from director

## Possible Solution
Catch stupid user configuration, so icinga will not crash

## Steps to Reproduce (for bugs)
1. Create a host template with default zone to director-global
2. Create host with that uses this template only adding name & ip
3. deploy config

## Your Environment

* Director version (System - About):  1.4.1
* Icinga Web 2 version and modules (System - About): 2.4.2
* Icinga 2 version (`icinga2 --version`): r2.7.1-1
* Operating System and version: Centos 7.4.1708
* Webserver, PHP versions: 7.1.10

**Comment by Thomas-Gelf** [comment]
Don't worry, Icinga didn't crash. Still, this stack trace shouldn't be there. Please open a related issue in the Icinga 2 [issue tracker](https://github.com/Icinga/icinga2/issues). And Director shouldn't allow you to choose a global zone for checkable objects, that's right.

**Comment by Thomas-Gelf** [comment]
Director allows global zones only for Host Templates, not for Host Objects. Sometimes it might be necessary for Templates, so there will be no related change.
