### ISSUE TITLE
Suggestion: Allow to select parts of a string from imported value based on regex 

### ISSUE THREAD

**Issue by NeverUsedID** [Icinga/icingaweb2-module-director#1262]
There is the Regular Expression based Replacement Modifer.
It would be great to have an Regular Expression based Selection Modifier where You can select a part of the Value with regular expression. Thats a lot easier vor RegEx beginners, than inverting the replacement modifier.

**Comment by tobiasvdk** [comment]
In the "Replacement" field you can use the groups which where captured by the regular expression, e.g. add something to the short hostname:
* Regex: /^([a-z0-9-]+)/
* Replacement: $1-something

**Comment by NeverUsedID** [comment]
Thanks for your reply,

yes, i use it that way at the moment, but f.e. i had an Icinga1 environment, where a hostname was like "location-type-os-hostname" and I wanted to take the "type" for a custom variable. It would be a lot easier to select just the type, instead of "select everything else before the first and after the second "-" and replace it with nothing. Select everything and replace it with what is between first and second "-" does not work in the director. (at least not the way i have tried it)

It would simplify the regex syntax a lot, if there would be such an option. Maybe there is a way to invert the selection, but i have not found a way to do so in the director. Something like: select everything between first and second "-" > invert the selection > replace selection with nothing.

**Comment by Thomas-Gelf** [comment]
Well, you can do as @tobiasvdk, you can tell the modifier to write matched data to other fields. Or, since today you could also first split the value via regex or string (`-` in your case) and then "Get a specific Array Element".
