### ISSUE TITLE
Servicesets - generated configuration file is invalid

### ISSUE THREAD

**Issue by terra-nova** [Icinga/icingaweb2-module-director#1263]
After disabling a host in Icinga Director, deployment of the configuration failed with a strange error message indicating a syntax error. 

```
information/cli: Icinga application loader (version: r2.7.1-1)
information/cli: Loading configuration file(s).
critical/config: Error: syntax error, unexpected $undefined
Location: in [stage]/zones.d/.../servicesets.conf: 76:53-76:53
[stage]/zones.d/.../servicesets.conf(76):     vars.os400_activejob_include_sbs = [ "^.*/BUS400\\.SBSD$$" ]
                                                                                              ^
```

I found that director generates a servicesets.conf file with services commented out C-style, like this:

```
/* --- This services host has been disabled ---
object Service "some service" {
...
}
*/
```

Which works fine... unless you have some service variable containing the token for closing a C comment (`*/`). Like the service in question does:

```
vars.os400_activejob_include_sbs = [ "^.*/BUS400\\.SBSD$$" ]
```

Given that many check commands allow for regular expressions for arguments, Director should generate configuration files that are immune to this kind of issue.

## Expected Behavior

Director generates valid Icinga configuration files.

## Current Behavior

Director may generate invalid Icinga configuration files.

## Possible Solution

Maybe just omit object definitions for disabled objects instead of enclosing them in C-style comments? Or prefix the lines with C++ comments (`//`) instead. Whatever works :)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Director version (System - About):
* Icinga Web 2 version and modules (System - About):
* Icinga 2 version (`icinga2 --version`):
* Operating System and version:
* Webserver, PHP versions:

**Comment by Thomas-Gelf** [comment]
Thanks for reporting this, will be fixed.
