### ISSUE TITLE
How to migrate icinga2 to new server

### ISSUE THREAD

**Issue by dejokuondi** [Icinga/icingaweb2-module-director#1266]
Hi all,
I installed icinga2 on a docker container. But I want to install icinga2 on a new server.
I just copy file config (commands.conf, hosts.conf, host_templates.conf, notification, users.conf...) from old server to /var/lib/icinga2/api/zones/director on new server.
But after I restart icinga2, all file config is reset to previous version before I copy.

Because I have many config, i want to migrate to new server.

Please help me to migrate icinga2 to new server.
Thanks

**Comment by dejokuondi** [comment]
@Thomas-Gelf Please help me to resolve this issue.
Thanks

**Comment by yoshi314** [comment]
Try dropping it in /etc/icinga2/conf.d , if you never messed around too much with the configuration.

**Comment by dejokuondi** [comment]
@yoshi314 Icinga service can't start...
It use /etc/icinga2/icinga2.conf and failed...

**Comment by thammw** [comment]
have you excluded the */conf.d in /etc/icinga2/icinga2.conf ?
Could you should show us the output of "icinga2 daemon -C" ?

**Comment by cptnkoiz** [comment]
/var/log/icinga2/icinga2.log will tell you whats wrong, i guess you did not migrate the database and/or the director properly. You also have to Migrate the certificates and other things.

**Comment by Thomas-Gelf** [comment]
Just dump your Director database and apply this dump to your new system, you shouldn't touch `/var/lib/icinga2/api/zones/director`.
