### ISSUE TITLE
Not able to create host

### ISSUE THREAD

**Issue by Dentaku1992** [Icinga/icingaweb2-module-director#1267]
I'm not able to create a new host in Icinga Director. When I try to add the new host (see screen) I got the message: "Trying to recreate icinga_host (lemmings.tp.testnet.banksys.be) (DbObject.php:780)". 

image : http://gertjanandries.com/images/icinga_bug.PNG

## Your Environment
* Director version (System - About): 1.4.1
* Icinga 2 version (`icinga2 --version`): 2.4.2
* Operating System and version: Ubuntu 16.04

**Comment by thammw** [comment]
The host is already present. At least in the director database. The Host Name has to be unique.  

It should be findable via the search from icingaweb2 director module.
If not:
Try "select * from %directordatabasename%.icinga_host where object_name = "lemmings.tp.testnet.banksys.be" "  while %directordatabasename% is the name of your director db.
