### ISSUE TITLE
Feature Request / Enhancement: More than one deployment queue, eventually user specific

### ISSUE THREAD

**Issue by tlo8640** [Icinga/icingaweb2-module-director#1271]
Hello,

This is more an feature request than a bug and from my sight as a non developer, it would lead into a lot of work in implementation... :-)

## Current Behavior
When two or more people (people could also mean automatic imports or API calls) are working on director for configuring checks and host, the config in the director itseilf can be in an "undefined" state during the work, where no deploy is possible. If some other guy (or automatic process) wants to do another config change during this "undefined" state, and starts a deploy, it will fail. Because all config changes will be deployed (try to deploy).
It's really hard to establish an automatic deploy for new Servers (using API or Sync jobs) on one side and doing configuratons and developing manually inside the director, because temporary undefined states during manually configuration work would break automatic deploys.

## Possible Solution
At least, it could help, if there would be different deployment queues for different users(API Users, Sync Jobs as well). You as the Monitoring Admin/Engineer could work on the config in your queue, not caring about undefined states while you are working on your changes. During this time automatic deployments can run and add servers to Icinga and deploy them to the icinga2 system using there own deployment queue(s).
When the engineer has finished his work he could "commit" his changes to the "global" Icinga director config.
At least every user(API User and Syncjobs) could/should have their own qeues.
While I'm writing this I feel like writing a specification for something like git... :-)

Do not having this feature is no showstopper for us in using director for icinga, as far I'm using it, it's a great tool for configuring icinga2. Thanks a lot for this!

But I think, my wished behavior could be wished by a lot of people. I'm quite sure, I already red about this feature wish in an older issue here, but I couldn't found it.

Thank you 
Thomas

**Comment by thammw** [comment]
Could be done with the State "disabled" until the user who modified it presses "roll-out" changes. The Activity Log "knows" who has done the changes and who didn't. The only tricky thing is if 2 people want to use a just created object, so there should be a global option to suppress this "feature". As a normal user you could just set the objects you want to define/customize to a disabled state and once you're done you can enable them. Just my 2 cents. :)

**Comment by tlo8640** [comment]
Hello,

does not work if you change existing objects wich are needed for automatic deploy, or if you built objects with dependencies, for instance if you create command, create service basing on this command and at least create template basing on this service.
Thomas

**Comment by friesoft** [comment]
@Thomas-Gelf as issue #458 is solved (teams using director with permissions using hostgroups) how is this solved in production systems? 
We will often have the usecase that changes made by one team shouldn't be deployed just because another team wants to deploy their changes.

Is this something which could be done in the near future? I guess this also needs the tag "sponsoring" ;)

**Comment by Thomas-Gelf** [comment]
@friesoft: this does usually not cause any problems, as teams allowed to clone existing hosts and to choose services for their own hosts can hardly generate an invalid configuration. If they are able to do so, you should tweak your templates and fields.

@tlo8640 talked about API users, such users are to be considered admins - as they are not restricted in many ways and able to create "incomplete" objects, like hosts inheriting templates with no check command. He also correctly pointed out some problems such a branched system (like GIT) would imply. Implementation details apart, I'm not sure whether adding the complexity of rebasing VS merging branches do a monitoring configuration GUI would make things easier to understand for most people. But sure, it would be pretty cool.

Such conflicts usually only happen when building your initial setup or when introducing a bunch of new commands and/or templates. I rarely see them in the daily business, and when I see broken deployments it is mostly a host or service without a command. That one should be easy to catch at an earlier stage.

What can however be a problem are automated deployments triggering immediately after your first change, with the next deployment then being delayed for 15mins or so. This can often be not what you expected, and I already blueprinted a solution for that. It would introduce shadow branches for each user, and you have to "merge" them into "master" once you're done.

Just one branch per user, to keep things simple. Users without merge/deployment permissions will create "Merge requests", and someone has to give his diff a look - and must then either confirm or reject those changes. @friesoft: I'd love to implement this that way, and I already know how to build it without harming performance. Just, it has it's level of complexity. We talked about this internally many times, just: it never was considered important enough to put it on the road-map. Sponsoring would definitively help to push this. In case you're interested in doing so please let me know. We could then also try to find other sponsors for this feature to share the cost.

Cheers,
Thomas
