### ISSUE TITLE
parsing $-sign (dollar sign) in service config 

### ISSUE THREAD

**Issue by viaLAN-joh** [Icinga/icingaweb2-module-director#1272]
I created a service MSSQL-Server-Instance with the names of the instances as an array.
So the name of the instance is config and the service to check should be MSSQL$ + config

## Expected Behavior
Render MSSQL$$$config$ => MSSQL$ + config

## Current Behavior
MSSQL$config$ => MSSQL + config
MSSQL$$$config$ => MSSQL$$$config$

## Your Environment

* Director version (System - About): 1.4.1
* Icinga Web 2 version and modules (System - About): 2.4.2
* Icinga 2 version (`icinga2 --version`): 2.7.1
* Operating System and version: Debian 8.9
* Webserver, PHP versions: Apache 2.4.10, PHP 5.6.0

**Comment by xam-stephan** [comment]
I have the same Problem.
$config$ is just the (MSSQL) DB SID.
Is there any other way to join 2 variables?

**Comment by c-kr** [comment]
As workaround (until this is fixed) you can use the nsclient regexp feature to get rid of the $:

filter=name regexp 'SQLAgent.$config$'

**Comment by Thomas-Gelf** [comment]
@SimonHoenscheid: I picked this for you to make it part of v1.5.0, will immediately push a fix. As it is a tricky one it would be great if you could give it a try. Anyways, a lot of tests are involved - so it should be fine.

Thanks,
Thomas

**Comment by SimonHoenscheid** [comment]
Thx Tom, this works fine!

**Comment by Thomas-Gelf** [comment]
Glad to hear that, you're welcome!
