### ISSUE TITLE
Pagination does not work correctly for Import Sources

### ISSUE THREAD

**Issue by tobiasvdk** [Icinga/icingaweb2-module-director#1273]
The pagination for Import Sources does not work correctly beginning with page 2. Here are screenshots for

page 1:
![director_page_1](https://user-images.githubusercontent.com/3541433/32409172-0af3c030-c1a7-11e7-9568-315eba4f472e.png)

page 2:
![director_page_2](https://user-images.githubusercontent.com/3541433/32409171-0ad57300-c1a7-11e7-9a05-faef9ca08060.png)

page 3:
![director_page_3](https://user-images.githubusercontent.com/3541433/32409170-0ab12a68-c1a7-11e7-83e6-d17afd795481.png)

## Expected Behavior
Pagination works correctly also for Import Sources.

## Current Behavior
Trying to go to page 3 does not work.

## Possible Solution
No idea.

## Steps to Reproduce (for bugs)
1. Go to an import source
2. Click to go to page 2
3. Click to got to page 3
4. See strange URL

## Context
Checking the imported data.

## Your Environment

* Director version (System - About): 1.4.1
* Icinga Web 2 version and modules (System - About): 2.4.1
* Icinga 2 version (`icinga2 --version`): 2.7.1
* Operating System and version: Debian Jessie
* Webserver, PHP versions: Apache, PHP 5.6.30

**Comment by swizzly** [comment]
I have the same issue with the current Director (commit 44c2a1b7db659df647af93794c5d848f5b01d80c).
As a workaround I can manually page by entering page number in the URL.

**Comment by lazyfrosch** [comment]
Confirmed
