### ISSUE TITLE
Windows Kickstart Script - FIPS Compliant

### ISSUE THREAD

**Issue by mvangoor** [Icinga/icingaweb2-module-director#1274]
Hi,

The generated powershell script for the Windows Kickstart script uses 'System.Security.Cryptography.SHA1Managed' in function 'getHashFromString'.
This is not FIPS compliant and can be easily swapped out for 'SHA256CryptoServiceProvider'

For security purposes FIPS compliancy has been enabled (forced) from the domain using group policies, so disabling this is not an option.

Any other solution using a FIPS compliant library is fine by me too the SHA256 just seemed to work.

Thanks

**Comment by Thomas-Gelf** [comment]
ping @LordHepipud

**Comment by Thomas-Gelf** [comment]
Nice, thank you. I had the plan to ship the latest one with v1.5.0, but forgot about it - sorry for that. I scheduled #1632 for v1.6.0.
