### ISSUE TITLE
Install icinga on a Citrix provisioned xenapp server

### ISSUE THREAD

**Issue by paolozuliani** [Icinga/icingaweb2-module-director#1275]
We have Citrix XenApp Farm that uses a provisioning technology, i.e. Operating System is not installed on the hardware but the hardware makes something similar to a network boot. As a consequence we have more than 20 server that have the same image and that image is refreshed whenever the server reboot.

The question is: how can we install icinga on those servers?

**Comment by lazyfrosch** [comment]
Sorry this is more like a support request...

* Unrelated to director
* No distinct technical issue
* Not a feature request

You should check https://www.icinga.com/support/ - one of our partners or of the community might help you
