### ISSUE TITLE
Can't open "Show detailed information about.." LDAP users

### ISSUE THREAD

**Issue by TheCry** [Icinga/icingaweb2-module-director#1276]
## Current Behavior
``#0 /usr/share/php/Icinga/Exception/IcingaException.php(41): ReflectionClass->newInstanceArgs(Array)
#1 /usr/share/php/Icinga/Web/Controller.php(78): Icinga\Exception\IcingaException::create(Array)
#2 /usr/share/icingaweb2/application/controllers/UserController.php(94): Icinga\Web\Controller->httpNotFound('User "CN=Bay.Sa...')
#3 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Controllers\UserController->showAction()
#4 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('showAction')
#5 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#6 /usr/share/php/Icinga/Application/Web.php(389): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#7 /usr/share/php/Icinga/Application/webrouter.php(109): Icinga\Application\Web->dispatch()
#8 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...')
#9 {main}``

## Steps to Reproduce (for bugs)

1. Icinga Director
2. Configuration
3. Authentication
4. User groups
5. select User Group Backend => LDAP user groups
6. Click on a ldap user group
7. Click on an user which is in the user group (right window) 

## Your Environment

* Director version (System - About):
* Icinga Web 2 version and modules (System - About):
director	master
doc	2.4.1
grafana	1.1.10
map	1.0.3
monitoring	2.4.1
setup	2.4.1
translation	2.4.1
* Icinga 2 version (`icinga2 --version`): icinga2 - The Icinga 2 network monitoring daemon (version: r2.7.1-1)
* Operating System and version: Debian 9
* Webserver, PHP versions: 
Server version: Apache/2.4.25 (Debian)
PHP 7.0.19-1
Server built:   2017-07-18T18:37:33

**Comment by Thomas-Gelf** [comment]
Not related to Director.
