### ISSUE TITLE
Undo change before deploying it

### ISSUE THREAD

**Issue by bunghi** [Icinga/icingaweb2-module-director#1284]
By mistake I entered a special char in some field when modifying one of my service apply rule and now when I select it to modify back I have this error:

![image](https://user-images.githubusercontent.com/31234197/32824388-775d2712-c9e9-11e7-95c1-06d3832949c2.png)

I don't really know which is the char I typed, I think it was a key close to Enter (maybe ' or \). The thing is that now I have to deploy changes but I don't want to apply this change. Any way to undo it?

## Your Environment

* Director version (System - About): master version of September 5th 2017
* Icinga Web 2 version and modules (System - About): 2.4.2
* Icinga 2 version (`icinga2 --version`): r2.7.2-1
* Operating System and version: Debian 9
* Webserver, PHP versions: Apache/2.4.25 (Debian), PHP 7.0.19-1 (cli) (built: May 11 2017 14:04:47)

**Comment by thammw** [comment]
Hey, I always delete it by deleting the corresponding object in the director database.

Not pretty, but it works :)

**Comment by bunghi** [comment]
And how you did it exactly? I have never modified the director database manually, and to be honest, I don't want to do it unless is the only solution. :)

**Comment by thammw** [comment]
If you have phpmyadmin on the server installed you can do it via gui. Otherwise you need to do it via cli...

`mysql -p`
##Your password goes here##
`delete from director.icinga_service where icinga_service.object_name = 'SAP_Enqueue_Utilisation_Granule_Entries';` 
I didn't break anything with it !yet!.

**Comment by thammw** [comment]
Can you "Restore Former Object" in the activity log?
That would be the easy way...

**Comment by bunghi** [comment]
No, I cant:

![image](https://user-images.githubusercontent.com/31234197/32827111-afe791a8-c9f3-11e7-9c08-76d94e9acdec.png)

**Comment by thammw** [comment]
@Thomas-Gelf  any ideas other than the SQL-thingy-thing?

**Comment by bunghi** [comment]
I have finally fixet it by updating the SAP_Enqueue_Utilisation_Granule_Entries row and setting null value to the field with the wrong values. Thanks for the hint @thammw 

I wait for @Thomas-Gelf to see if is there any other solution.

**Comment by Thomas-Gelf** [comment]
Restore works now for Services in v1.5.0. If you're able to reproduce the initial Apply Rule error please let us know in a dedicated issue with instructions explaining us how to reproduce this.
