### ISSUE TITLE
Activity log doesn't work for services from Service Sets

### ISSUE THREAD

**Issue by mwaldmueller** [Icinga/icingaweb2-module-director#1287]
The "Diff"-tab of the activity log isn't complete and "New object" or "Former object" are not working for services that are defined in a Service Set.

<img width="483" alt="bildschirmfoto 2017-11-15 um 13 46 52" src="https://user-images.githubusercontent.com/3973350/32836993-0d1d0070-ca0c-11e7-9f0e-a499fc7ad5b9.png">

## Environment

* Director version (System - About): 1.4.2
* Icinga Web 2 version and modules (System - About): 2.4.2
* Icinga 2 version (`icinga2 --version`): 2.7.2
* Operating System and version: CentOS 7.4

**Comment by tobiasvdk** [comment]
Any chance to get this after v1.6.0?

**Comment by Thomas-Gelf** [comment]
Sure! The changes we implemented for the basket will allow us to re-think parts of the Activity Log.
