### ISSUE TITLE
Improve displaying of tooltips

### ISSUE THREAD

**Issue by mwaldmueller** [Icinga/icingaweb2-module-director#1288]
Improve displaying of tooltips, e.g. at host templates:

<img width="409" alt="bildschirmfoto 2017-11-15 um 13 55 19" src="https://user-images.githubusercontent.com/3973350/32837164-c44697ca-ca0c-11e7-9dfc-2b01a398656c.png">

## Environment
* Director version (System - About): 1.4.2
* Icinga Web 2 version and modules (System - About): 2.4.2
* Icinga 2 version (`icinga2 --version`): 2.7.2
* Operating System and version: CentOS 7.4

**Comment by Thomas-Gelf** [comment]
Revert is the new fix :laughing: - this duplicates #1510
