### ISSUE TITLE
Data lists in Data field array

### ISSUE THREAD

**Issue by MuadDib81** [Icinga/icingaweb2-module-director#1289]
Using https://github.com/Icinga/icingaweb2-module-director/blob/master/doc/14-Fields-example-interfaces-array.md I'm not 100% able to select multiple field entries at service properties.
![image](https://user-images.githubusercontent.com/21058376/32839875-31eff254-ca16-11e7-860d-e75d991ac587.png)
![image](https://user-images.githubusercontent.com/21058376/32839923-559b636e-ca16-11e7-95e5-8188f0163d13.png)
![image](https://user-images.githubusercontent.com/21058376/32839993-9467f3b4-ca16-11e7-8827-751ca180d9cb.png)

## Expected Behavior
I expected to have an "- add more -" field, where you can select more predefined objects to add to this array (notifications_field).

## Current Behavior

At the moment you can select one entry or remove it but can't add another one to the field.

## Possible Solution

If the field is an array with a data list as source, create the GUI to be able to behave as "Groups" field from the service and/or host.

## Steps to Reproduce (for bugs)

1. Create an "Data list"
2. Create a "Data field" and select "Datalist" at "Data type"  and "Array" at "Target data type"
3. Create a Service Template
4. Add the created Data field to the Service Template under Fields (Mandatory = Optional)
5. Try to add multiple entries to the template under "Custom properties"

## Context

I would like to create a field with different notifications to notify different users for different services (multiple too - sms + email to get a ticket created).

## Your Environment

* Director version (System - About): 1.4.2
* Icinga Web 2 version and modules (System - About): 2.4.2
* Icinga 2 version (`icinga2 --version`): r2.7.2-1
* Operating System and version: CentOS Linux release 7.4.1708 (Core)
* Webserver, PHP versions: Apache/2.4.6 (CentOS) PHP/5.4.16

**Comment by offsides** [comment]
I'm having the same problem trying to create a host template.  The 'States' and 'Transition types' selection drop downs only allow you to select a single item, but no other selection list is shown after.  There is a '-click to add more-' selection in the drop down after '-add more-', but clicking it does nothing.  I suspect that this isn't supposed to be in the drop down itself, but after the last selected item...

**Comment by offsides** [comment]
Following up, it looks like this has something to do with the class 'active' not being toggled when the focus goes into the selection.  This also affects a bunch of other places that should have drop downs.  I'm going to have to see if 1.4.1 has the problem, and if not downgrade to that...

**Comment by offsides** [comment]
OK, that's REALLY weird.  When I set up Icinga2, I had set the timezone in php.ini, but apparently made a typo when I did it.  Icinga2 told me it was fine when I refreshed the checks, so I assumed it was all good.  Testing just now with wget just to see what I could find threw a PHP error at me about the timezone, and when I fixed it the drop-downs in Director work properly...

**Comment by MuadDib81** [comment]
@offsides Strange... My timezone is set to UTC and my icinga2 account too. Have you downgraded to 1.4.1?

**Comment by offsides** [comment]
@MuadDib81 No, fixing the timezone issue solved the problem I was having.  I'm literally just starting up with Icinga2 and Director (I have an existing Icinga1 setup using NConf, but it's time to upgrade everything about them :)), so I haven't played with where you're seeing the error.  Just to test, try 'wget -O - http://localhost/icingaweb2' from your icingaweb2 box and see if it shows you a PHP error or not - that's how I found my problem.  If it doesn't, then I don't know what to suggest.

**Comment by MuadDib81** [comment]
@offsides I tried it out with Chrome 62 and IE11, no luck. But I think we are talking about different things. The fields 'States' and 'Transition types' are working normal in my case.

**Comment by MuadDib81** [comment]
'wget -O - http://localhost/icingaweb2' showed no problems with the PHP.

**Comment by Thomas-Gelf** [comment]
@offsides: your problem might eventually have been related to your browser still running outdated CSS/JavaScript after upgrading your system, so after a full refresh you were covered. Timezone should not be related at all.

@MuadDib81: what you're describing should work fine. Could you please share some related screen-shot? At least the Data Field definition and the failing form?

**Comment by MuadDib81** [comment]
I've attached 3 screenshots:

1st - Creating the list entries
2nd - Creating the data list and adding the entries
3rd - Showing the problem

Are this screen shots enough or do you need some more?

**Comment by MuadDib81** [comment]
After the update of Icinga Web 2 to 2.5.0, Icinga 2 to 2.8.0 and PHP to 7.1 the issue has been resolved!
