### ISSUE TITLE
Custom var rendering issue 

### ISSUE THREAD

**Issue by ktella** [Icinga/icingaweb2-module-director#1290]
Using the version 1.4.2 i had issue with rendering the customvar. see the below screenshot.

![image](https://user-images.githubusercontent.com/19876555/32848320-25b1cb5a-c9fa-11e7-8771-28996ab825a3.png)

![image](https://user-images.githubusercontent.com/19876555/32848476-a4f2ed7c-c9fa-11e7-9eab-8f996f5d8544.png)

I rolled back to my 1.4.0 version which is working fine. Did not test current master.

## Expected Behavior

should be "$check_address$"

## Current Behavior

Rendering as check_address

## Possible Solution

Don't know

## Steps to Reproduce (for bugs)

1. 
2.
3.
4.

## Your Environment

* Director version (System - About): 1.4.0
* Icinga Web 2 version and modules (System - About): 2.4.2
* Icinga 2 version (`icinga2 --version`): r2.7.1-1
* Operating System and version: RHEL 7
* Webserver, PHP versions: httpd-2.4.6-40.el7.x86_64 & PHP 5.4.16

**Comment by Thomas-Gelf** [comment]
@ktella: did you test 1.4.1?

**Comment by ktella** [comment]
I did not test in 1.4.1 and i just tested it in current master. I see issue in master.

Will test in 1.4.1 and let you know in a minute.

**Comment by ktella** [comment]
Tested again.

I confirm that master and 1.4.2 got the issue, and 1.4.1 is clean.

**Comment by Thomas-Gelf** [comment]
Thank you! Strange thing, at first sight it looks like a different bug that didn't bit you because another bug protected you :laughing:. The latter one has been fixed in 1.4.2 - and now you should see the correct wrong rendering. I'll have to do some tests with this before heading to the wrong direction, this is a little bit weird. Thanks a lot for reporting it!

**Comment by Thomas-Gelf** [comment]
This should have been fixed in the current master and will be part of v1.5.0
