### ISSUE TITLE
Recreating host with variable combinations from import sources

### ISSUE THREAD

**Issue by aflatto** [Icinga/icingaweb2-module-director#1291]
When importing hosts and creating the host name from a combination of to variables [ ex. {zone_{ip} ]
the sync rule fails to recreate the host even when the policy is "replace"

## Expected Behavior

when syncing the modified rule , the existing recored should be removed and the new one created.

## Current Behavior

when a host is already present and you try to change the import rule you get the error:
failed to recreate host "foo.bar"
in order to be able to re-sync the import source there is a need to delete the item manually.

## Steps to Reproduce (for bugs)

1.Define an import source with multiple fields
2.define sync rule where the object_name is build of a combination of fields ( i used zone and address) 
3.Sync the hosts once and see they are deployed
4. Change the sync rule to add/alter some paraeters
5. Sync the rule.

## Context

I am trying to migrate an old system (manual configuration ) to Director based and need to import all the hosts/groups/user/Switchs/pdu etc and when ever this issue occurs I have to delete all the nodes related in order to proceed.

## Your Environment

* Director version (System - About): master
* Icinga Web 2 version and modules (System - About):2.4.1
* Icinga 2 version (`icinga2 --version`):2.7.1
* Operating System and version: Centos 6.9
* Webserver, PHP versions: Apache 2 , PHP 7.1

**Comment by Thomas-Gelf** [comment]
Stumbled over this issue as it has been referenced by another one. Having multiple import rows referencing the same object is not allowed and might result in the above error. Also, when combining fields having a correct Import Source "Key Column" is crucial, eventually the "Combine" property modifier might help. In case the problem persists please provide more related information, I'll close this issue so far.
