### ISSUE TITLE
Variable display_name in apply rule

### ISSUE THREAD

**Issue by carraroj** [Icinga/icingaweb2-module-director#1295]
In icinga 2 core its possible to add a variable display_name in a service appy-rule like this:

    apply Service "events_termsv_perflib" {
        display_name = "EVENTS: PERFLIB"
    }   
It would be good to have this in the director (customer wish) to set a good naming designation in apply-rules.

## Your Environment

* Director version (System - About): 1.4.2

**Comment by Thomas-Gelf** [comment]
While you're not the first one asking for this, just being curious: why do you want to have two distinct names for the very same thing? Why don't you just name your Service "EVENTS: PERFLIB" in the above example, like this:

```
apply Service "events_termsv_perflib" {
    display_name = "EVENTS: PERFLIB"
}
```

**Comment by Thomas-Gelf** [comment]
(updated the example)

**Comment by carraroj** [comment]
The customer had in the object-name a technical name and wants to have it more readable for better understanding to other employees without changing the object-name.

**Comment by Thomas-Gelf** [comment]
I can preach and preach and preach and beg people to use meaningful names... and they still insist on having technical names differing from "real names" :-/

I'll close this issue, as at least one duplicate definitively exists. Not scheduled so far.
