### ISSUE TITLE
SelfService API: Service User is not working

### ISSUE THREAD

**Issue by LordHepipud** [Icinga/icingaweb2-module-director#1297]
The SelfService API is allowing the definition of the Service User the Icinga Agent is started with on Windows System. The argument is however not doing anything

## Expected Behavior

The Icinga Director should provide the variable

icinga_service_user

with the defined user once beeing requested. In case the Service User is empty, it should not be send.
## Current Behavior

The property is simply ignored by the Icinga Director
## Possible Solution

Add the icinga_service_user variable to the API request output
## Steps to Reproduce (for bugs)

1. Call the Self-Service API self-service/powershell-parameters?key=<host-key>
2. icinga_service_user is missing there

## Context

Changing Service Users over Self-Service API is not yet possible
## Your Environment

* Director version (System - About): current master
* Icinga Web 2 version and modules (System - About): 2.4.2

**Comment by Thomas-Gelf** [comment]
Wanted to have this in v1.5.0 - forgot about it, sorry.
