### ISSUE TITLE
Buttons (e.g. "Move up/down" have weird captions

### ISSUE THREAD

**Issue by simonszu** [Icinga/icingaweb2-module-director#1298]
## Expected Behavior
1. Edit a host
2. Buttons under "Imports" should have proper captions

## Current Behavior
The Buttons have some kind of asian letter caption, the only way to get their behaviour explained is via the tool tips.

## Possible Solution
Rename them, or fix the charset issue

## Steps to Reproduce (for bugs)
Look under "Expected behaviour"

## Context
This issue affects me when i try to edit a host, or a group, or whatever. It is still possible to get all stuff done with the help of the tool tips, anyway

## Your Environment
* Director version (System - About): git master, cloned around 14:00 CET today (2017-11-20)
* Icinga Web 2 version and modules (System - About):  2.4.1
* Icinga 2 version (`icinga2 --version`): r2.6.0-1
* Operating System and version: Debian Stretch on a Raspberry Pi 3
* Webserver, PHP versions: Apache2 from the Debian Stable repos (2.4.25-3+deb9u3), reverse proxied via an nginx 1.10.3

**Comment by Thomas-Gelf** [comment]
Please try to SHIFT-Reload your page, to me this sounds like something being wrong with your CSS

**Comment by simonszu** [comment]
Oh. Yes. It was. I'm sorry for bothering you with this. :(
