### ISSUE TITLE
Agent kickstart script does not respect "Establish connection: no"

### ISSUE THREAD

**Issue by simonszu** [Icinga/icingaweb2-module-director#1303]
## Expected Behavior
When one creates an agent host, and sets it to "Establish connection: no", he wants the agent connect to the master, and not vice versa. This is the only acceptable way in some firewall setups or similar. The Agent kickstart script should deploy a config to the agents, so that they are configured to actively start a connection to the master. 

## Current Behavior
Even if "Establish connection: no", the kickstart script configures the agents to only accept connections from the master, but not vice versa. 

## Possible Solution
According to [this post](https://monitoring-portal.org/index.php?thread/40545-agent-hinter-firewall-ohne-portfreigabe/&postID=247995#post247995), the essential config is to create a new line in the zones.conf, in the "Object Endpoint "master.host"" block where a host-key points to the value of the master host's FQDN (or anything which can respond to an API call). I have tested it with entering this key-value-pair in a zones.conf created by Director's kickstart script, and it works. 

A solution would be to create an if-else-switch in the kickstart script generator, and create this key-value-pair when "Establish connection" is set to no. I do not know if one can always have this line in their config, but according to what i interpreted in the documentation, this could work. The connection would be agent->master, or master->agent, depending on what node initiates the session first, and succeeds. 

## Steps to Reproduce (for bugs)
1. Create a new Agent host, set "Establish connection" to "no"
2. Kickstart the Agent via Director's script
3. Error message in the hosts view of icinga: No connection from agent to master
4. Add the host-config in the zones.conf and restart icinga on the agent host
5. Agent initiates connection to the master

## Context
I have some disjunct subnets, only connected via "the internet", and instead of opening the API port on each agent's firewall, so that the master can connect to each agent, i only want to open the firewall port on the master's firewall, so that the agents can connect to the master. So i can reduce the number of open ports visible to "the internet" from n to 1. 

## Your Environment

* Director version (System - About): git master, checked out today
* Icinga Web 2 version and modules (System - About): 
* Icinga 2 version (`icinga2 --version`): 2.4.1
* Operating System and version: Debian Stretch
* Webserver, PHP versions: Apache 2 in the Debian stable repositories, PHP 7 in the debian stable repositories

**Comment by Thomas-Gelf** [comment]
This changed a lot in v1.5.x - and in theory this should be fixed. In case it isn't, please let us know.
