### ISSUE TITLE
Preserve _override_servicevars on sync, even when replacing vars

### ISSUE THREAD

**Issue by carraroj** [Icinga/icingaweb2-module-director#1307]
preserve _host_override when replacing vars.* on sync

**Comment by friesoft** [comment]
The same applies to vars["_override_servicevars"] 
Having a sync with merge strategy leads to entries from arrays not being deleted (even though they are gone in the import source). 
Using replace they are correctly removed but the overriden variables are removed.

**Comment by widhalmt** [comment]
+1 from me. This seems to hit a lot people.

**Comment by phil-or** [comment]
+1
