### ISSUE TITLE
Can't see imported properties from host template

### ISSUE THREAD

**Issue by bunghi** [Icinga/icingaweb2-module-director#1310]
## Expected Behavior

I am using different host templates when creating new hosts in Icinga2. For instance, I have a basic template for AIX hosts where I am setting properties like operating system. The thing is that some AIX servers are using Oracle database and for that I have another template which adds new properties to the host like setting the application to "oracle" or adding field for oracle sid.  And there is where I get into problems. The **application** propertie is data type array (so I can have more then one application for a host), but the "oracle" is not visible into the application field after importing the template:

![image](https://user-images.githubusercontent.com/31234197/33360481-86a18d46-d4dc-11e7-864a-707b277e1164.png)

Strange thing is that when I go to the preview tab and click on Show resolved I see oracle application:

![image](https://user-images.githubusercontent.com/31234197/33360509-a42be820-d4dc-11e7-8987-7136049f2287.png)

I have this problem only with array data type properties. Is there any solution?

## Steps to Reproduce (for bugs)

1. Create a host template with one custom propertie with array data type and leave it empty
2. Create a new host template importing the preview one and add some string to the array 
3. Create a host from the last template
4. The array field is not filled, altough in the hosts.conf file seems to be present.

## Your Environment

* Director version (System - About): master version downloaded on 29.11.2017
* Icinga Web 2 version and modules (System - About): 2.4.2
* Icinga 2 version (`icinga2 --version`): r2.8.0-1
* Operating System and version: Debian 9
* Webserver, PHP versions: Apache/2.4.25 (Debian), PHP 7.0.19-1

**Comment by Thomas-Gelf** [comment]
Note: inherited arrays in fields should behave similar to the groups "property"
