### ISSUE TITLE
Adjust ServiceSet tabs

### ISSUE THREAD

**Issue by mwaldmueller** [Icinga/icingaweb2-module-director#1312]
* When you select a service of a service set, the first tab is renamed from "ServiceSet" to "Serviceset" (German: "ServiceSet" -> "Service-Set")
* Furthermore the "Preview"-tab is missing, that makes it harder to navigate

![bildschirmfoto 2017-11-29 um 11 15 20](https://user-images.githubusercontent.com/3973350/33370080-c51f2e9c-d4f6-11e7-9e3d-a7cf8e5b57c6.png)

![bildschirmfoto 2017-11-29 um 11 15 36](https://user-images.githubusercontent.com/3973350/33370088-cb780174-d4f6-11e7-87fc-7e81ff665903.png)

## Environment
* Director version (System - About): 1.4.2
* Icinga Web 2 version and modules (System - About): 2.4.2
* Icinga 2 version (`icinga2 --version`): 2.7.2
* Operating System and version: CentOS 7.4
* Webserver, PHP versions: Apache, 5.4.16

**Comment by Thomas-Gelf** [comment]
Missing Preview-Tab is intentional, it's... complicated. Tab name will be fixed, thanks for pointing this out.
