### ISSUE TITLE
Flap Detection for existing/new hosts/services

### ISSUE THREAD

**Issue by agconstantin** [Icinga/icingaweb2-module-director#1313]
## Expected Behavior

Flapping detection should be a tick-able option in the host template, within icinga director, so you could enable this feature for all the hosts assigned to the template.

## Current Behavior

There is no option to (bulk) enable flapping feature for the hosts/services.

## Possible Solution

Add flapping option menu in the host/service templates (eg. /icingaweb2/director/host/edit?name=host_template_name) or /icingaweb2/director/service/edit?name=service_template_name

## Context

Flapping detection feature in the latest director version there is not available, therefor you only enable this feature by going to each host individually, within icinga overview page. 

## Your Environment

* Director version (System - About): master (commit 05081961d5ccb082b37f421fd4616f7be27f647a)
* Icinga Web 2 version and modules (System - About): 2.42
* Icinga 2 version (`icinga2 --version`): 2.4.2 (commit 7cec28a31fdff0feb470ec001838bc1dec9c4b69)
* Operating System and version: Red Hat Enterprise Linux Server version: 7.4 (Maipo)
* Webserver, PHP versions: , HTTP 2.2.1, PHP 5.4.16
MODULE         VERSION   STATE     DESCRIPTION
businessprocess 2.1.0     enabled   A Business Process viewer and modeler
director       master    enabled   Director - Config tool for Icinga 2
doc            2.4.2     enabled   Documentation module
monitoring     2.4.2     enabled   Icinga monitoring module
nagvis         1.1.1     enabled   NagVis integration
pnp            1.0.1     enabled   Timeseries grapher integration for PNP4Nagios

**Comment by lazyfrosch** [comment]
duplicates #503

**Comment by agconstantin** [comment]
@lazyfrosch how is this a duplicate with #503 ?
Also, #503 Status changed from Assigned to Resolved.
How is this resolved, since I am using the current master version?
Can you please review this issue? I believe you have misplaced or misunderstood the problem.

**Comment by lazyfrosch** [comment]
Sorry it is a duplicate of #330

**Comment by agconstantin** [comment]
@lazyfrosch thanks for the update, but..
Please have a look:
https://github.com/Icinga/icingaweb2-module-director/blob/master/doc/02-Installation.md
Requirements:
Icinga 2 (>= 2.6.0). All versions sinve 2.4.3 should also work fine, but we do no longer test and support them.
Icinga Web 2 (>= 2.4.1). All versions since 2.2 should also work fine, but might show smaller UI bugs and are not actively tested
A database, MySQL (>= 5.1) or PostgreSQL (>= 9.1). MariaDB and other MySQL forks are also fine. Mentioned versions are the required minimum, for MySQL we suggest using at least 5.5.3, for PostgreSQL 9.4.
PHP (>= 5.4). For best performance please consider use 7.x
php-curl

I comply with all of these.
Why would I be forced to upgrade to a higher version of Icinga (eg. 2.8) to benefit from a missing feature within Icinga Director? Besides this, the newer Icinga version introduced a bunch of changes, which will required a lot of work. I feel this is a problem that should be fixed within Director.

**Comment by lazyfrosch** [comment]
Please discuss in #1319

**Comment by Thomas-Gelf** [comment]
@agconstantin: Director didn't offer support for flapping as it used to be a slightly broken feature in Icinga 2. This should have been fixed with v2.8.0, so there is no remaining show stopper. @lazyfrosch already created a related pull request, #1319.

Director still allows you to stay on Icinga 2.6, unless you use the upcoming flapping settings.

**Comment by agconstantin** [comment]
@Thomas-Gelf I fully understand what you are saying, but let's have a look at a real life scenario, where you already have hundred of Icinga clients, running. Now just because of the flapping feature, we would have to upgrade to version =>2.8, where, just one example, the pki certificates path has been changed, you can imagine how much work this mean, just because a feature which normally would be part of the Director, like the other options exist under "Check excecution tab": icingaweb2/director/service/edit?name=service_name

**Comment by lazyfrosch** [comment]
@agconstantin btw. you can set these values internally right now, just not via the UI

    icingacli director host set "default host" --enable_flapping

Or even inside the database...

**Comment by Thomas-Gelf** [comment]
@agconstantin: we hear you, and we'll try to ship a good solution addressing all your concerns. As you've seen, @lazyfrosch already implemented large parts of this. We talked off-line to sharpen the latest details, here a rough summary:

* this feature used to be broken in Icinga 2 before v2.8.x, and therefore never has been offered by the Icinga Director
* I hope no one did, but some people might have used workarounds like shown by @lazyfrosch, enabling the "legacy" flapping configuration through Icinga Director. So, Director upgrade/migration should preserve `enable_flapping` and drop the broken threshold value (thus, such objects will get default thresholds)
* you mentioned the problem with a master running v2.8.x and some/all Agents/Satellites still running older versions. @lazyfrosch will now try to implement threshold property rendering for #1319 in a failsafe way, writing a condition like `if (X >= v2.8) { flapping_... = ... }` into the rendered configuration.

So, once the feature has been finished and merged, you should be able to use the `enable_flapping` flag in the GUI. It will work with all supported Core versions, not break when replicated to older versions and configure thresholds only on nodes >= 2.8. This would be easier if Icinga [feature #5784](https://github.com/Icinga/icinga2/issues/5784) already was a thing, but I'm sure @lazyfrosch will come up with a good a workaround.

**Comment by agconstantin** [comment]
@Thomas-Gelf thanks for the heads-up,
I will try to make use of the @lazyfrosch recommendations in the mean time.
