### ISSUE TITLE
Updating certain properties via API fails

### ISSUE THREAD

**Issue by matthenning** [Icinga/icingaweb2-module-director#1315]
## Expected Behavior
Updating objects via POST request to the Director updates all properties.

## Current Behavior
Some properties show up in the activity log, but aren't actually stored.

## Steps to Reproduce (for bugs)
Create an object within the Director and retrieve it using the REST API:

```
template Service "REMOTE Some Service" {
    import "REMOTE Service"
    
    check_command = "nscp-local-service"
    command_endpoint = host_name
    vars.nscp_service_name = "SomeService"
}
```

In another Director instance the service already exists with slightly different properties
Now POST the retrieved JSON to update the service in the other Director instance **two times**.

The first POST works as expected and the properties are updated:
![first_post](https://user-images.githubusercontent.com/5699183/33433559-51c83c7c-d5dc-11e7-8d22-049434277150.png)

The second POST for some reason assumes that check_command and command_endpoint are not present and adds them.
![second_post](https://user-images.githubusercontent.com/5699183/33433562-52178f70-d5dc-11e7-9e6a-64c7e9770b22.png)

The activity log doesn't reflect what actually happens though:  The second POST **removes** the two properties from the object.
Before and after the first POST the preview of the object shows the expected result. After the second POST the two properties are gone. Everytime you POST the same object again there will be a new entry in the activity log which looks like the second screenshot.

This only seems to happen with specific attributes. In my case the following:

max_check_attempts,
check_command,
command_endpoint,

## Your Environment (updated)
* Director version (System - About): 1.4.2
* Icinga Web 2 version and modules (System - About): ~~2.4.1~~ 2.5.0
* Icinga 2 version (`icinga2 --version`):  ~~r2.7.0-1~~ r2.8.0-1
* Operating System and version: ~~SLES12 SP1~~ SLES12 SP2
* Webserver, PHP versions: Apache2 2.4.16-19.1, PHP 5.5.14

**Comment by Thomas-Gelf** [comment]
@matthenning: those two properties refer related objects, thats what makes them different from other options. There is quite some lazy-loading and caching involved, short: those properties are tricky. But because of that, there are a bunch of automated tests in place, trying to assure correct behavior of those components.

Also, I tried to simulate what you're seeing (changes shown in the activity log while there where no such), but I haven't been able to reproduce your issue. Could you please provide me some more context, ideally sample API requests allowing me to reproduce it?

Thanks,
Thomas

**Comment by Thomas-Gelf** [comment]
Wait... now I got it. The problem appears, when your net change involves only such relations to other objects, without changing any other "real" property. No need for a sample, I'm now able to reproduce this!

**Comment by matthenning** [comment]
After I identified an additional issue on my end I can confirm my tests are positive. Thanks!

**Comment by Thomas-Gelf** [comment]
Glad to hear that, thanks for your feedback!
