### ISSUE TITLE
Mandatory data fields are double-mandatory when service is applied to host via rules

### ISSUE THREAD

**Issue by simonszu** [Icinga/icingaweb2-module-director#1316]
I have created a data field which is marked as mandatory in a service template. This service template is applied to several hosts with an apply rule based on their group membership. 

## Expected Behavior
I enter the value of the data field into the host's settings, since it's value is host dependant. I apply the service, it gets its mandatory value via each host's settings, and everyone is happy. 

## Current Behavior
After entering a value in each host settings, i try to create an apply rule for the service template. The apply rule settings page has the field marked as mandatory as well, and forces me to enter a value, regardless of the fact that this field already has a value via the host's settings page. When entering a value, it overrides the custom value for each host in their own settings page. So it currently is not possible to apply a service template to a host group with mandatory settings, if one of the host in the groups requires a different setting. 

## Possible Solution
The apply rule could inherit the mandatory value from each host the rule is applied to, and only sets its own value to hosts which don't have the value already set. 

## Steps to Reproduce (for bugs)
1. Create a new service template for checking the swap.
2. Choose the predefined "swap" command as the check command. The plugin accepts a value for it's "-u" flag, which can be provided via the swap_noswap variable
3. Create a data field called swap_noswap and mark it as mandatory (it should be important to specify for each host, if it is intended to run without a swap)
4. Visit each host's settings page, and set swap_noswap to "critical", but set it to "ok" on one host only, since it is allowed to run without swap
5. Create a group containing all hosts
6. Create a service apply rule, applying the swap service to this group
7. This apply rule needs an input for swap_noswap as well, it is marked as mandatory
8. For testing, set this value to "ok"
9. Deploy everything
10. All hosts have defined swap_noswap as ok, although some hosts _must_ run with swap. The host's setting is ignored. 

## Context
I have a bunch of servers, which all should be monitored with the same commands, check_load, check_procs, and so on. They are packed in a common group. Due to technical limitations, one of these hosts is running without swap. When applying the check_swap to this group, i cannot differentiate this. For now, i have to split the group into "hosts with swap" and "hosts without swap", and have to create nearly identical apply rules and everything. 

## Your Environment
* Director version (System - About): master
* Icinga Web 2 version and modules (System - About): 2.4.1
* Icinga 2 version (`icinga2 --version`): 2.6.0
* Operating System and version: Debian Stretch
* Webserver, PHP versions: Apache 2.4, PHP 7

**Comment by Thomas-Gelf** [comment]
I'm sorry, the current behavior is the expected one. I understand where you're coming from, but in my believes it will not work out that way. Also, usability would IMO suffer. However, I believe that what Director ships with Custom Variable overrides (allowing you to tweak thresholds at a host level for every applied service) is much better than the proposal explained here.

As always, in case you don't agree - please let us know!
