### ISSUE TITLE
Expand command-templates tree without existing template

### ISSUE THREAD

**Issue by carraroj** [Icinga/icingaweb2-module-director#1318]
expand command-templates tree without existing template, shows error message in php.

It displays the error-message, see screenshot and i think it should show like 'No Template available', add one. something like that instead of this message.

## Steps to Reproduce (for bugs)

1. open Director Commands
2. choose Templates
3. choose tree
4. choose a check command

## Your Environment

* Director version (System - About): v.1.4.2 and master
* Icinga Web 2 version and modules (System - About): 1..4.2
* Icinga 2 version (`icinga2 --version`): 2.8.0

![screenshot_20171205_135258](https://user-images.githubusercontent.com/25805027/33608141-e7b7e350-d9c3-11e7-8444-38a65e602072.png)

**Comment by Thomas-Gelf** [comment]
Can be reproduced with v1.5.x

**Comment by Thomas-Gelf** [comment]
Fixed with 280ed44
