### ISSUE TITLE
[dev.icinga.com #11332] Support dependencies

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#132]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11332

**Created by tgelf on 2016-03-08 16:24:01 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-11-30 09:00:58 +00:00 (in Redmine)_

---

They have been forgotten...

**Changesets**

_2016-12-29 22:07:12 +00:00_ by _mdetrano_ cb6f04cf524f5280f0d660c645b0186efd19ccef

    Implement Icinga Dependency Configuration
    
    refs #11332

---

**Relations**:

* duplicates [#11332](https://dev.icinga.com/issues/11332)

**Comment by Links2004** [comment]
any news on this?
its impossible to user nagvis automap without the parents / hostdependency.

**Comment by melaniebauer** [comment]
I would also appreciate news on this, we need this feature...

**Comment by Hipska** [comment]
Ping @Thomas-Gelf and @mdetrano

**Comment by dheule** [comment]
For us, this is a necessary condition, please increase the priority

**Comment by mdetrano** [comment]
The latest update to the pull request should allow that branch to merge cleanly with latest Director.

https://github.com/Icinga/icingaweb2-module-director/pull/39

..for anyone who'd like to test it out.  As for the issue of it being slow...I've used this in a ~1500 host system and it seems ok for a system of that size.  Ultimately, a new form component may be needed to more dynamically allow for host/service lookups so that things remain smooth on huge systems as well.

**Comment by eoinkim** [comment]
@mdetrano Hi, if you don't mind, could you please tell me how to test the dependencies in Director? I actually downloaded this - https://github.com/Icinga/icingaweb2-module-director/tree/5e8361d55b4c0d1e7a049a7251d7c2c6eda23d04 and checked the icingaweb2 interface but looks the same. I thought maybe some menus would be added into director. I could see dependency option has been added in icingacli director command though.

I am actually a total novice with this GitHub so need a bit of help regarding test. If you could show me how to a bit more, I'd really appreciate it. Thanks again.

**Comment by mdetrano** [comment]
On 06/01/2017 03:17 PM, eoinkim wrote:
>
> @mdetrano <https://github.com/mdetrano> Hi, if you don't mind, could 
> you please tell me how to test the dependencies in Director? I 
> actually downloaded this - 
> https://github.com/Icinga/icingaweb2-module-director/tree/5e8361d55b4c0d1e7a049a7251d7c2c6eda23d04 
> and checked the icingaweb2 interface but looks the same. I thought 
> maybe some menus would be added into director. I could see dependency 
> option has been added in icingacli director command though.
>
> I am actually a total novice with this GitHub so need a bit of help 
> regarding test. If you could show me how to a bit more, I'd really 
> appreciate it. Thanks again.
>

I am not sure why "Dependencies" didn't show up in your Director (on the 
initial dashboard screen when you open Director), but in any case I'd 
usually do something like the following steps to setup Director and test 
the branch:

cd /usr/share/icingaweb2/modules
git clone https://github.com/Icinga/icingaweb2-module-director.git director
cd director/
git remote add mdetrano 
https://github.com/mdetrano/icingaweb2-module-director.git
git fetch mdetrano
git merge Feature_11332_Support_Dependencies_20161118


... and it may ask you to setup the  user name and email information 
before actually doing the merge step.

Support for the database changes is only present in the mysql version of 
the schema script: 
/usr/share/icingaweb2/modules/director/schema/mysql.sql.  If you are 
having issues you may want to verify that the tables icinga_dependency , 
icinga_dependency_inheritance , and icinga_dependency_states_set have 
been created in your Director DB. The "upgrade_dependencies.sql" file 
under mysql-migrations may help get those added if they are not yet there.

Thanks for interest in having a look at this implementation.

Marc

**Comment by eoinkim** [comment]
@mdetrano Thanks a lot, I'll have a try again. Cheers.

**Comment by eoinkim** [comment]
@mdetrano Hi, I just made a change as you said and I can see the new menu in director. Really appreciate it. However, when I test the dependency it doesn't look working well. I expected the notification for child host should not arrive when parent host is down. But I am receiving notifications for both hosts. I made dependency configuration like below:

zones.d/director-global/dependency_apply.conf
apply Dependency "host-dependency" to Host {
    disable_checks = true
    disable_notifications = true
    ignore_soft_states = false
    assign where host.vars.parent != ""
}

And I created a test host with the following setting:

zones.d/master/hosts.conf
object Host "TESTHOST.TEST.LAB" {
    display_name = "Dependency test host"
    address = "10.10.10.1"
    check_command = "hostalive"
    max_check_attempts = "3"
    check_period = "24x7-timeperiod"
    check_interval = 1m
    retry_interval = 30s
    enable_notifications = true
    zone = "master"
    vars.notification_icingaweb2url = "http://ip_address/icingaweb2"
    vars.notification_level = "1"
    vars.notification_method = "email"
    vars.notification_number = "$notification.notification_number$"
    vars.parent = "parenthost"
}

If I am missing something, could you please advise regarding this? Sorry for bothering you.

**Comment by mdetrano** [comment]
@eoinkim , One way to verify the dependency was actually created is to use the commandline interface of icinga2:

Example:

icinga2 object list --type dependency --name "host-dependency"

should show your dependency (after you deploy it from Director).

If that dependency is in fact there, and has the fields as configured...then the problem you are having is an Icinga issue.  If its not there, then something strange is happening and the object is not making it from Director to you configuration.

**Comment by eoinkim** [comment]
@mdetrano Thanks. I was considering using director web interface only. But I found that using command is a bit necessary. Yes, I checked if the dependency shows up via the command line and it does. Thanks again. Cheers.

**Comment by odrino14** [comment]
i am trying Dependencies but i am not getting how this is working.
i create a object Dependency 
`
zones.d/master/dependencys.conf

object Dependency "host-dependency" {
    parent_host = "webserver"
    child_host_name = "test-dependency"
    disable_checks = true
    disable_notifications = false
    ignore_soft_states = false
    period = "24x7_director"
    states = [ Up ]
}
`
i have not output on my host
how can i use this ?
thx

**Comment by eoinkim** [comment]
@odrino14 Hi mate, I think you need apply rule to see the effect. Have you created any apply rules?

**Comment by odrino14** [comment]
Hi @eoinkim,
I found how to create an apply rules? and istworking but just for Host and it i can't see it in icingaweb2 just wenn i run the cli-Command.
I can't make Service Dependency. the field Parent Service is missing.

**Comment by eoinkim** [comment]
@odrino14 Sorry mate, I am also in learning phase of this so can't help you much. Maybe you can ask @mdetrano about this. Cheers.

**Comment by mdetrano** [comment]
@odrino14  , the field parent_service should appear on the form after selecting a parent_host (the list is populated after the system knows which host to list services for).  Did this not happen?

**Comment by odrino14** [comment]
@mdetrano , no it is not working. i just have parent_host even if i choose one.
it is possible to see dependencies in icingaweb2 like classic ui not just with
the Iicnga2 cli ?

**Comment by mdetrano** [comment]
@odrino14 
As far as I know, web2 doesn't have anything for showing dependencies..but if you're familiar with Nagvis you can set something up with automaps and a host "shared navigation" item.

I am not sure why the services won't display..how do you define services for the hosts?  directly, via a host template, or via Apply rules (apply rule generated services may not be presented in the list).

**Comment by scavara** [comment]
@mdetrano , 
you wrote: "Support for the database changes is only present in the mysql version of the schema script: /usr/share/icingaweb2/modules/director/schema/mysql.sql.  If you are having issues you may want to verify that the tables icinga_dependency , icinga_dependency_inheritance , and icinga_dependency_states_set have been created in your Director DB. The "upgrade_dependencies.sql" file under mysql-migrations may help get those added if they are not yet there."
I would like to try out the Feature_11332_Support_Dependencies_20161118 but I guess me using postgresql is a showstopper?

Btw, I hope that your https://github.com/Icinga/icingaweb2-module-director/pull/39 will be accepted soon.

**Comment by odrino14** [comment]
@mdetrano , 
Thanks! i will take a look at it...i define services via Apply rules

**Comment by cflinspach** [comment]
> cd /usr/share/icingaweb2/modules
> git clone https://github.com/Icinga/icingaweb2-module-director.git director
> cd director/
> git remote add mdetrano
> https://github.com/mdetrano/icingaweb2-module-director.git
> git fetch mdetrano
> git merge Feature_11332_Support_Dependencies_20161118

@mdetrano I tried following these instructions but I don't see any new menu item, and actually lost the first row of icons on the Director dashboard. My director DB is missing the tables too. I switched to the latest from icinga/icingaweb2-module-director after seeing #28 and #39 but still no dependencies, even after trying the upgrades from mysql-migrations. 

![schema](https://user-images.githubusercontent.com/4700533/28231951-fc758b40-68a2-11e7-811a-1bed12c76b16.png)

![director_module](https://user-images.githubusercontent.com/4700533/28231807-40175e6a-68a2-11e7-8f44-ff5714a535d8.png)

![startup_log](https://user-images.githubusercontent.com/4700533/28231765-1a0f7022-68a2-11e7-91f7-7abe35aba34d.png)

**Comment by cflinspach** [comment]
FYI Here's what it looks like after following the git instructions.

![mdetrano_feature_11332_support_dependencies_20161118](https://user-images.githubusercontent.com/4700533/28274213-2a736a16-6ac5-11e7-864f-0097b43222a0.png)

**Comment by mdetrano** [comment]
It's possible there have been some updates upstream and that branch is no longer merge-able.  I'll try to check on it soon.

Another issue I can see cropping up in the discussion here...linking services.  Hosts are so much easier because you know you have a host-name to work with...services can be setup in so many different ways, and when it comes to apply rules, and especially apply-for rules, determining the service name may not be practical from the Director database.  It may be better to lose the fixed-link back to a configured service and simply make the service an editable field.  Or , I could allow some combination of bother.

**Comment by cflinspach** [comment]
@mdetrano Aren't the services already linked to their hosts?

**Comment by mdetrano** [comment]
Since there had been quite a bit of updates upstream, I created a completely updated branch and submitted a new pull request for this feature.

I was able to handle some of the issues that have been brought up here...faster form loads, using services that are "applied" to a host for child or parent relations, and using the "same host" ability for Dependencies setup via Apply rules.

Again, for anyone who wants to test it out, here is an example of how to merge in the changes:

cd /usr/share/icingaweb2/modules 
git clone https://github.com/Icinga/icingaweb2-module-director.git director 
cd director/ 
git remote add mdetrano https://github.com/mdetrano/icingaweb2-module-director.git 
git fetch mdetrano 
git merge Feature_11332_Support_Dependencies

There are a couple of sql scripts to manually update the database (mysql only...if someone can port this to Postgresql, that would be great).

schema/mysql-migrations/upgrade_dependencies.sql
then
schema/mysql-migrations/upgrade_dependencies_2.sql

**Comment by Thomas-Gelf** [comment]
This has been merged to master, still flagged "experimental". For those who already have been experimenting with this branch: please drop dependency-related tables before applying the new migrations. They slightly differ from the former feature branch.

**Comment by Thomas-Gelf** [comment]
@mdetrano: thanks a lot for the hard work. It would be great if you could check whether everything still works as expected in the current master. I disabled "single dependency objects" for now, only templates and apply rules are allowed - but that should suffice for most users. Some constraints are now "hard", you are no longer allowed to remove parents being used by dependency rules. Deleting childs is fine and will also silently drop related dependencies.
