### ISSUE TITLE
Undefined offset: 1 (TemplateTree.php:186)

### ISSUE THREAD

**Issue by jschoone** [Icinga/icingaweb2-module-director#1323]
We updated our Icinga Director and now we aren't able to deploy new config. The error
Undefined offset: 1 (TemplateTree.php:186) comes up.
It is possible to redeploy. The database schema is the newest.

The error also comes up if I execute 
\# icingacli director config render 
ERROR: ErrorException in /usr/share/icingaweb2/modules/director/library/Director/Resolver/TemplateTree.php:186 with message: Undefined offset: 1

I saw some related issues related to database problems, but I  don't get what to fix on the database.

## Your Environment

* Icinga Web 2 version and modules (System - About):
* Version used (`icinga2 --version`): icinga2 - The Icinga 2 network monitoring daemon (version: r2.8.0-1)
* Operating System and version: CentOS 7
* Enabled features (`icinga2 feature list`): Disabled features: compatlog debuglog elasticsearch gelf influxdb livestatus opentsdb perfdata statusdata syslog
Enabled features: api checker command graphite ido-mysql mainlog notification
* Config validation (`icinga2 daemon -C`):
[root@server1 icingaweb2]# icinga2 daemon -C
information/cli: Icinga application loader (version: r2.8.0-1)
information/cli: Loading configuration file(s).
information/ConfigItem: Committing config item(s).
warning/ApiListener: Attribute 'key_path' for object 'api' of type 'ApiListener' is deprecated and should not be used.
warning/ApiListener: Attribute 'ca_path' for object 'api' of type 'ApiListener' is deprecated and should not be used.
warning/ApiListener: Attribute 'cert_path' for object 'api' of type 'ApiListener' is deprecated and should not be used.
warning/ApiListener: Please read the upgrading documentation for v2.8: https://www.icinga.com/docs/icinga2/latest/doc/16-upgrading-icinga-2/
information/ApiListener: My API identity: server1
warning/ApplyRule: Apply rule 'mail-icingaadmin' (in /etc/icinga2/conf.d/notifications.conf: 11:1-11:45) for type 'Notification' does not match anywhere!
warning/ApplyRule: Apply rule 'mail-icingaadmin' (in /etc/icinga2/conf.d/notifications.conf: 23:1-23:48) for type 'Notification' does not match anywhere!
information/ConfigItem: Instantiated 1 ApiListener.
information/ConfigItem: Instantiated 2 Zones.
information/ConfigItem: Instantiated 2 Endpoints.
information/ConfigItem: Instantiated 3 ApiUsers.
information/ConfigItem: Instantiated 1 FileLogger.
information/ConfigItem: Instantiated 21 UserGroups.
information/ConfigItem: Instantiated 7 NotificationCommands.
information/ConfigItem: Instantiated 10197 Notifications.
information/ConfigItem: Instantiated 205 CheckCommands.
information/ConfigItem: Instantiated 1 IcingaApplication.
information/ConfigItem: Instantiated 1034 Hosts.
information/ConfigItem: Instantiated 58 HostGroups.
information/ConfigItem: Instantiated 2 Downtimes.
information/ConfigItem: Instantiated 17 TimePeriods.
information/ConfigItem: Instantiated 34 Users.
information/ConfigItem: Instantiated 51 Comments.
information/ConfigItem: Instantiated 17 ServiceGroups.
information/ConfigItem: Instantiated 8621 Services.
information/ConfigItem: Instantiated 1 CheckerComponent.
information/ConfigItem: Instantiated 1 ExternalCommandListener.
information/ConfigItem: Instantiated 2 GraphiteWriters.
information/ConfigItem: Instantiated 1 IdoMysqlConnection.
information/ConfigItem: Instantiated 1 NotificationComponent.
information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
information/cli: Finished validating the configuration file(s).

**Comment by Thomas-Gelf** [comment]
Problem used to be a wrong Service Set relation in the database, probably created by a former version of Director. v1.4.x comes with more strictness when it comes to inheritance and therefor threw above (not very meaningful) Exception. As we solved this through a dedicated support issue, I'll close this one. In case you're still facing related problems please let me know.
