### ISSUE TITLE
Questions: Can Director output to /etc/icinga/ 

### ISSUE THREAD

**Issue by stoivo** [Icinga/icingaweb2-module-director#1326]
This is more of a question than a request

## Questions
Today I am adding settings to Icinga with Director.  The settings are applied like is should and the config files appear in `/var/lib/icinga2/api/packages/director/monitor.no-1512731864-3/`.  I like to write/change settings with vim as well. In those cases, I would like if the settings were located in ` /etc/icinga2/`. 
This might be that I want to copy something from staging environment or something I cant defined in Director. Like string functions.

Director is very cool. 

## Expected Behavior

Director deploys changes to /etc/icinga/.
Me login to the director and run the `Kickstart Wizard` to sync the handcrafted files to the master.

## Current Behavior

Director deploys changes to `/var/lib/icinga2/api/packages/director/monitor.no-1512731864-3`.

## Possible Solution

Director deploys changes to `/etc/icinga2/`.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Director version (System - About): master 16729a98ecdfd1a11a3f8da54182047b756c22a5
* Icinga Web 2 version and modules (System - About):

Name | Version
-- | --
director | master
doc | 2.5.0
monitoring | 2.5.0
translation | 2.5.0

* Icinga 2 version (`icinga2 --version`): 2.8.0-1
* Operating System and version: Ubuntu 16.04
* Webserver, PHP versions: apache2, php5.6

**Comment by mcktr** [comment]
Short answer: No, the Director can not write to /etc/icinga2.
Long answer: https://github.com/Icinga/icingaweb2-module-director/blob/master/doc/10-How-it-works.md

**Comment by stoivo** [comment]
Thanks, @mcktr.
I think I will stick with writing most files by hand.
