### ISSUE TITLE
Re-deploy of old Config State does not re-create DB Entries

### ISSUE THREAD

**Issue by Wintermute2k6** [Icinga/icingaweb2-module-director#1327]
## Issue general summary: 
When redeploying old configuration via the Config Tab in Deployments.
The Configuration gets successfully restored but the Director DB Entries are not recreate to show the refreshed Config.

## Expected Behavior
When clicking 'Re-Deploy' it should also re-create the former DB Objects for the config which it is re-creating.

## Current Behavior
When clicking 'Re-Deploy' it successfully re-creates the former config files but does not re-create the former DB director objects. 

## Possible Solution
Maybe a further DB Colum with stores the diff/entries which need to be restored. 

## Steps to Reproduce (for bugs)
1.Fresh Icinga 2 Setup with Web 2 and Director Module and DB.
2. Create Host Template & Service Template
3. Create Testhost
4. Create Set with Apply for the Testhost
5. Deploy the Config via Director
6. Restore Config via Config Deployment -> Deployments -> Config(fsdfsdf) -> Config -> Re-Deploy Now
7. Check if Conf files are restored -> ls -l /var/lib/icinga2/api/packages/director/xxx.xxxxxx-1512729182-0/zones.d/director-global/
8. Check if DB Entries are restored ->
mysql director
select * from director.icinga_service_set;
Empty set (0.00 sec)

## Context
Issue was affecting while unintenionally deleting a large Service Set and after the restore realizing that there is the need for manually recreating the Set and the Services because they vanished from the Director DB even when the Conf files are actually restored.

## Your Environment
* Director version (System - About): Director Module 1.4.2 
* Icinga Web 2 version and modules (System - About): Icinga 2.5
* Icinga 2 version (`icinga2 --version`): 
icinga2 - The Icinga 2 network monitoring daemon (version: r2.8.0-1)

Copyright (c) 2012-2017 Icinga Development Team (https://www.icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Application information:
  Installation root: /usr
  Sysconf directory: /etc
  Run directory: /run
  Local state directory: /var
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

System information:
  Platform: CentOS Linux
  Platform version: 7 (Core)
  Kernel: Linux
  Kernel version: 3.10.0-693.11.1.el7.x86_64
  Architecture: x86_64

Build information:
  Compiler: GNU 4.8.5
  Build host: unknown
* Operating System and version:
cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

* Webserver, PHP versions:
httpd.x86_64                     2.4.6-67.el7.centos.6    @updates              
httpd-tools.x86_64               2.4.6-67.el7.centos.6    @updates 
rh-php71-php-cli.x86_64          7.1.8-1.el7              @centos-sclo-rh       
rh-php71-php-common.x86_64       7.1.8-1.el7              @centos-sclo-rh       
rh-php71-php-fpm.x86_64          7.1.8-1.el7              @centos-sclo-rh       
rh-php71-php-gd.x86_64           7.1.8-1.el7              @centos-sclo-rh       
rh-php71-php-intl.x86_64         7.1.8-1.el7              @centos-sclo-rh       
rh-php71-php-json.x86_64         7.1.8-1.el7              @centos-sclo-rh       
rh-php71-php-ldap.x86_64         7.1.8-1.el7              @centos-sclo-rh       
rh-php71-php-mbstring.x86_64     7.1.8-1.el7              @centos-sclo-rh       
rh-php71-php-mysqlnd.x86_64      7.1.8-1.el7              @centos-sclo-rh       
rh-php71-php-pdo.x86_64          7.1.8-1.el7              @centos-sclo-rh       
rh-php71-php-pgsql.x86_64        7.1.8-1.el7              @centos-sclo-rh       
rh-php71-php-xml.x86_64          7.1.8-1.el7              @centos-sclo-rh       
rh-php71-php-zip.x86_64          7.1.8-1.el7              @centos-sclo-rh       
rh-php71-runtime.x86_64          1-1.el7                  @centos-sclo-rh 

![redeploy](https://user-images.githubusercontent.com/7203835/33766448-c1dbe300-dc1d-11e7-87c6-02bdbb916416.jpg)
![restore1](https://user-images.githubusercontent.com/7203835/33766449-c1fa7716-dc1d-11e7-8373-1563ff7ec49b.jpg)
![restore2](https://user-images.githubusercontent.com/7203835/33766450-c217f03e-dc1d-11e7-9173-f9b298539b84.jpg)

**Comment by Thomas-Gelf** [comment]
The current behavior is what should be expected. Re-deploying old configuration is NOT to be confused with rolling back all changes in Director. It will deploy an old configuration byte-wise as it was at the time being. No matter whether in the meantime you upgraded Director a couple of times and therefore the config right now would be rendered in a completely different manner.

This is a feature that should for example help in disaster situations where some automatism broke your production and your monitoring, making you basically blind. It allows you to quickly restore a former state, Activity Log will then show all activities since then as being un-deployed. But it will not roll back those changes, that's not what this feature has been designed for.
