### ISSUE TITLE
Prpoerty modifier to assign value from source2 if source1 is not set

### ISSUE THREAD

**Issue by swizzly** [Icinga/icingaweb2-module-director#1329]
Hi
I would need a property modifier that would assign the value to target property from source1 if it is defined, or from source2 if source1 is not available. Or something like this.
Cheers

**Comment by Thomas-Gelf** [comment]
Hi @swizzly,

you can mix two sources in one Sync Rule and define the same Sync Property multiple times in a single rule. Last one wins, NULL values have no effect. So, in your example setting `vars.target = source2` and then `vars.target = source1` should have the desired outcome: it will first pick the value from source2, and then override it with the one from source1 - but only if source1 doesn't give `NULL`.

Could this help to address your use-case?

**Comment by swizzly** [comment]
That works even with Import Source, and that's enough for me.
Thanks!
