### ISSUE TITLE
Add search filter for templates which are not in use

### ISSUE THREAD

**Issue by SimonHoenscheid** [Icinga/icingaweb2-module-director#1339]
## Expected Behavior
For templates a filter would be nice, to show just the ones which are not in use

## Current Behavior
not in use status is visible in list, but filtering is not possible

## Possible Solution
add filter

## Context
Host-, Service-, notification-,...Templates

* Director version (System - About): master

**Comment by Thomas-Gelf** [comment]
A similar feature has been implemented for commands: #1480

**Comment by Thomas-Gelf** [comment]
Optional candidate for v1.6.0
