### ISSUE TITLE
the connection to the Icinga webserver was lost at $CURRENTTIME

### ISSUE THREAD

**Issue by ant0nwax** [Icinga/icingaweb2-module-director#1340]
I was clicking and cloning and deleting and renaming quite fast at the icinga director gui, suddenly the connection to the Icinga webserver was lost (red error that appears at the bootom on the GUI) 
A reboot shows me that PSQL server cannot startup without problems, machine hangs, in single user mode i deactivated the psql service and after normal boot, I needed to run psql server in background manually with &, the normal process startup gets stuck, freezes, SQL problem? 

## Expected Behavior
If I click the special command "check_generic" in director at Commands/Commands the command appears on the the right side and I can edit it.

## Current Behavior
If I click the special command "check_generic" in director at Commands/Commands the command appears NOT on the the right side and I cannot edit it. The right side of the GUI just gets white and then there is the error message from the topic:
...
the connection to the Icinga webserver was lost at $CURRENTTIME
...

## Possible Solution
My Idea: Find the error inside the SQL Database?

## Steps to Reproduce (for bugs)

1. Have an Icinga setup with director and 10 commands, command templates, services, service templates and service sets running with PSQL and centos 6.9
2. Click Fastest you can on the commands, clone them, delete them, rename them, also add those to the services, organize in service sets, and so on, maybe director has a log and you will see what exactly was the order in which I clicked the commands
3. Database will get corrupted most likely

## Context

I cannot Deploy/Commit anymore since this command check_generic that causes the issue is also inside the deploy queue. Could I remove until we find the SQL bug, one line from Director Deploy Queue, or all Lines? Is that possible? I have 11 lines waiting for deploy, the oldest 11th causes the trouble.

## Your Environment

If it is important I will collect the requested information, just please tell me if there are director logs, and If I am able to change the deploy queue somehow, remove items for example.

**Comment by ant0nwax** [comment]
I found a thread that mentiones a pop up blocker, this is not the cause here. I also found the developer tools console in chrome browser, so i could provide some logs, they are big and might provide private information, so to send, i would need an email address or something similar.

**Comment by Thomas-Gelf** [comment]
Are your still able to reproduce this? Regarding 3) -> that's not gonna happen.

**Comment by Thomas-Gelf** [comment]
Guess I understand what happened: command form allows you to click commands inheriting from themselves. As we broke our loop detection there is nothing protecting you from this.

You can fix such issues in your database via:
```sql
DELETE FROM icinga_command_inheritance
  WHERE command_id = parent_command_id;
```

To solve this specific issue: command form shouldn't show ancestors as import/parent candidates. I created #1631 to get rid of similar issues.

**Comment by ant0nwax** [comment]
Hi Thomas
I solved this by some SQL fix that you mentioned long ago, maybe one day after reporting this. Still thanks for showing that it was the right direction.
Since then in director I click slowly and wait until browser wheel finishes after each click, so it did not happen again luckily.

I would like to update Icinga and director and grafana, since it is again a long time, maybe I wait for your information that #1631 is merged into stable and then I do the update, I will watch that issue, this one we could close

Have a good ongoing day
