### ISSUE TITLE
Error import, first install

### ISSUE THREAD

**Issue by jkvint** [Icinga/icingaweb2-module-director#1347]
Storing icinga_command[vmware-esx-soap-host-runtime-health-nostoragestatus] failed: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails ("directordb"."icinga_command_var", CONSTRAINT "icinga_command_var_command" FOREIGN KEY ("command_id") REFERENCES "icinga_command" ("id") ON DELETE CASCADE ON UPDATE CASCADE), query was: INSERT INTO icinga_command_var (command_id, varname, varvalue, format) VALUES (?, ?, ?, ?) {array ( 'id' => '172', 'object_name' => 'vmware-esx-soap-host-runtime-health-nostoragestatus', 'object_type' => 'external_object', 'disabled' => 'n', 'methods_execute' => 'PluginCheck', 'command' => 'check_vmware_esx', 'timeout' => 60, 'zone_id' => NULL, )} (DbObject.php:814)

The first installation I enter the data api and Endpoint Name, I press import the error pops out.

## Current Behavior

Installation has occurred, it seems to work, but there are no commands in the external commands.

## Steps to Reproduce (for bugs)

I downloaded the module of the director, installed it started import and error.
Installed in a directory /usr/share/icingaweb2/modules/director

## Context

The database is located remotely on the freebsd, is on another server.

## Your Environment

* Director version (System - About): master
* Icinga Web 2 version and modules (System - About): 2.5.0
* Icinga 2 version (`icinga2 --version`): r2.8.0-1
* Operating System and version: Debian 9
* Webserver, PHP versions: 2.4.25 apache, php 7.0

**Comment by svenvoss** [comment]
Hi,
I'm facing the same problem. I found following workaround:
- move/rename the file /usr/share/icinga2/include/plugins-contrib.d/vmware.conf so that icinga isn't loading it any more
- do the import

Cheers,
Sven

**Comment by TonyBostonTB** [comment]
this is still an issue here for me as well, see #1302

**Comment by chrnie** [comment]
The problem occurs only with "persistent" flag set on director's database resource. 

It's already mentioned in issue https://github.com/Icinga/icingaweb2-module-director/issues/1169 with a [nice picture](https://ibb.co/isY6B5):


It's reproducable on 
OS: CentOS7
icinga2.8.2
icingaweb2: 2.5.1
director: 1.4.3 + master

Error message:
`Storing icinga_command[vmware-esx-soap-host-net-usage] failed: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails ("director"."icinga_command_var", CONSTRAINT "icinga_command_var_command" FOREIGN KEY ("command_id") REFERENCES "icinga_command" ("id") ON DELETE CASCADE ON UPDATE CASCADE), query was: INSERT INTO icinga_command_var (command_id, varname, varvalue, format) VALUES (?, ?, ?, ?) {array ( 'id' => '167', 'object_name' => 'vmware-esx-soap-host-net-usage', 'object_type' => 'external_object', 'disabled' => 'n', 'methods_execute' => 'PluginCheck', 'command' => 'check_vmware_esx', 'timeout' => 60, 'zone_id' => NULL, )} (DbObject.php:814)`

**Comment by Gammenon** [comment]
I've noticed the same thing. The topic is also discussed in #1169 .
Kickstart via icingacli would also be a possibility, but first the /etc/icingaweb2/modules/director/config.ini must be filled according to the [documentation](https://github.com/Icinga/icingaweb2-module-director/blob/master/doc/03-Automation.md).
