### ISSUE TITLE
Create check for Director jobs

### ISSUE THREAD

**Issue by widhalmt** [Icinga/icingaweb2-module-director#1352]
It would be useful to have a dedicated way for Icinga 2 to check whether Director jobs ran succesfully or failed.
I think of a "catchall" check that checks for all defined jobs with the option to specify single jobs so I can have Services for each Job.

This could help with #1194  and #596 as well.

**Comment by Thomas-Gelf** [comment]
@widhalmt: is [this](https://github.com/Icinga/icingaweb2-module-director/blob/master/doc/60-CLI.md#health-check-plugin) what you're looking for?

**Comment by widhalmt** [comment]
Damn.... @Thomas-Gelf I even used our Team Chat to verify that there is no Check like this and we all agreed that it would be useful. X-) Sorry for the fuzz. I'll talk to the Icinga 2 developers if we want this within the ITL.

**Comment by Thomas-Gelf** [comment]
:laughing: 

@widhalmt: there is a colored screen-shot on page 29 in [this slides](https://de.slideshare.net/NETWAYS/osmc-2017-thomas-gelfautomated-monitoring-in-heterogeneous-environment)

**Comment by widhalmt** [comment]
I even was in this talk at OSMC 2017... shame on me.

**Comment by Thomas-Gelf** [comment]
:muscle: jetz glab i's oba! :smiling_imp:
