### ISSUE TITLE
Unable to fetch the -C parameter from by_ssh external command

### ISSUE THREAD

**Issue by bleizg** [Icinga/icingaweb2-module-director#1356]
Icinga Director cannot fetch the "by_ssh_command" parameters from by_ssh external command.

## Expected Behavior
We should be able to choose "by_ssh_command" from the "Fieds" tab.

## Current Behavior
The director show
```
"-C" = {{
            /* Unable to fetch function body through API */
        }}
```
And the field is not present here:
![director fields](https://dl.plik.ovh/file/q6GVApxzuK34TUwP/khIOHINR3fat60L1/2018-01-05%2016_20_20-Icinga%20Web.png)

## Steps to Reproduce (for bugs)
1. Click on 'by_ssh' external command
2. Select 'Fields' tab

## Context
I tried to implement a new check by using by_ssh.

## Your Environment

* Director version (System - About):
* Icinga Web 2 version and modules (System - About): 2.5.0
* Icinga 2 version (`icinga2 --version`): r2.8.0-1

**Comment by Thomas-Gelf** [comment]
There is nothing I can do about this, -C is an anonymous function and Icinga 2 cannot export such through it's API. If you look at the definition of `by_ssh` on your Icinga node you'll see that it makes use of the `by_ssh_command` macro. So, please create a data field with such name in your Director and then add that field to the Command.

You might want to open a dedicated feature request asking for a more generic support for such proxy/transport-like command behavior, something similar could help to hide complexity that comes with such wrappers.

Cheers,
Thomas
