### ISSUE TITLE
Incomplete instructions on agent deployment??

### ISSUE THREAD

**Issue by MrMEEE** [Icinga/icingaweb2-module-director#1358]
Hi

Trying to follow: 24-Working-with-agents.md.. I can get the script from director to run my client, but it ends with:

information/pki: Writing certificate to file '/etc/icinga2/pki/trusted-master.crt'.
information/cli: Writing CA certificate to file '/etc/icinga2/pki/ca.crt'.
information/cli: !!!!!!
information/cli: !!! Certificate request for CN 'hexia.casalogic.lan' is pending. Waiting for approval from the parent Icinga instance.
information/cli: !!!!!!

Can't find anything about approval of the parent in the docs.. What do I do from here... ????

Thanks

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Director version (System - About):
* Icinga Web 2 version and modules (System - About):
* Icinga 2 version (`icinga2 --version`):
* Operating System and version:
* Webserver, PHP versions:

**Comment by bl4kd3th** [comment]
On the master, run `icinga2 ca list` and the client should appear. You then run `icinga2 ca sign {ticket}`, where `{ticket}` corresponds to the host in the previous output. You could also use `icinga2 pki request --host {hostname}` and enter that ticket salt on the agent during icinga2 node wizard. I believe this image https://github.com/Icinga/icingaweb2-module-director/blob/master/doc/screenshot/director/24-agents/2403_show_agent_instructions_1.png on that documentation page explains it.
