### ISSUE TITLE
apply rules for host templates

### ISSUE THREAD

**Issue by SimonHoenscheid** [Icinga/icingaweb2-module-director#1359]
## Expected Behavior
director would allow applying services to host templates

```
apply Service "foobar" {
  import "generic-service"

  assign where "templatename" in host.templates
}
```
## Current Behavior
Its not possible

## Possible Solution
implement feature

## Context
The users get a minimalized frontend and can just assign a single template to a host. As every template represents a role, I could add a host var called role to the template to reach this goal.The  apply rule would make it easier to apply same service to multiple templates without manageing it on multiple places

## Your Environment
* Director version (System - About): master

**Comment by lazyfrosch** [comment]
Uhm why do you think this does not work. AFAIK it is just not in the autocompletion...

![bildschirmfoto von 2018-01-12 16-19-09](https://user-images.githubusercontent.com/121874/34881651-6972262c-f7b4-11e7-86c5-530ccba19b08.png)

```
apply Service "ssh-by-template" {
    import "ssh"

    assign where "linux-server" in host.templates

    import DirectorOverrideTemplate
}
```

**Comment by SimonHoenscheid** [comment]
I dont get managed to pass by the autocompletion

**Comment by lazyfrosch** [comment]
Browser? Screenshot?

**Comment by SimonHoenscheid** [comment]
Firefox 52.4.1 (ESR)
Director: master

![director_apply_host_template](https://user-images.githubusercontent.com/4162281/34935722-1ce1bee4-f9df-11e7-9ec8-2cfd7a5fc75f.PNG)

**Comment by lazyfrosch** [comment]
Oh right, the new input style here is blocking that.

There is a discrepancy between some filter inputs:
* apply -> dropdown
* serviceset -> autocomplete

@Thomas-Gelf opinion on that?

**Comment by SimonHoenscheid** [comment]
Can we mark this as bug then? @lazyfrosch @Thomas-Gelf

**Comment by Thomas-Gelf** [comment]
Why don't you just go to the Host Template and add a Service (or Set) directly on it's Services tab?

**Comment by SimonHoenscheid** [comment]
Because of the flexibiliy of the apply rules

**Comment by sahnd** [comment]
+1

Adding a service to a host template does not allow you to do this in combination with conditions. I have faced this problem several time. The only workaround is to introduce some helper variable/data field, which is set at the host template and can be used for an apply rule.
This is some ugly workaround and you have to define one extra data field per host template, to be able to handle this with apply rules.
#890 was there to enable director to use host templates in apply rules, but it's not working anymore with current versions of director. 

It would make life much more easy if host.template would be available for apply rules, at least with some free text field to fill in the template name. I don't think it is a must to have all the template names in a drop down box or something like that.

Regards,
Sebastian

**Comment by Thomas-Gelf** [comment]
The combination with conditions makes sense. The form field is easy to fix, we should however check whether host.template is interpreted when filters are evaluated correctly when previewing assigned services for a Host.

**Comment by Thomas-Gelf** [comment]
What I mentioned in the last note could impact performance. This feature will be considered for v1.5.0, but might be postponed in case it cannot easily be implemented in an efficient way.

**Comment by Thomas-Gelf** [comment]
Wrote some tests today, looks good to me, please expect this to be implemented within this week.

**Comment by SimonHoenscheid** [comment]
Hi Tom, 

thx for implementation! I tried this out today and it looks like the config is not build the right way:

exspected config
```

apply Service "check" {
    import "check"

    assign where "templatename" in host.templates

    import DirectorOverrideTemplate
}
```

generated  config
```
apply Service "check" {
    import "check"

    assign where host.templates in [ "templatename" ]

    import DirectorOverrideTemplate
}
```

**Comment by Thomas-Gelf** [comment]
Hi @SimonHoenscheid,

could you please show me how you clicked your filter? It should read `host.templates` **contains** `templatename`.

Cheers,
Thomas

**Comment by SimonHoenscheid** [comment]
Thank you Tom, works this way!
