### ISSUE TITLE
icinga agent script failing

### ISSUE THREAD

**Issue by fireba11** [Icinga/icingaweb2-module-director#1360]
I got some (as in two) of my dozen or so debian hosts where i can't get the icinga agent script to set up the agent. I can't really tell what the actual issue is so any pointers would be appreciated.

## Context
check: icinga2 installed - OK
ERROR: couldn't find your Icinga2 sysconfig file
./icinga: line 39: : No such file or directory
ERROR: $ICINGA2_USER has not been defined

## Your Environment
* Director version (System - About): 1.4.0
* Icinga Web 2 version and modules (System - About): 2.5.0
* Icinga 2 version (`icinga2 --version`): r2.8.0-1
* Operating System and version: debian 9

Agent:
icinga2 r2.1.1-1
debian 8.10

**Comment by fireba11** [comment]
so the current script fails on debian oldstable (8, jessie).
any way to fix it/get an alternative version? it might still be a bit untill i can finally upgrade those :-D

**Comment by RogerSik** [comment]
Have this issue also now with the conjunction of
* Ubuntu 18.04.
* Icinga2 r2.9.1-1
* Icinga Director git pull Stand 01.08.2018

Happens for me when I want to execute the agent bash script from director.

**Comment by rmalenko** [comment]
I have the issue too

- Ubuntu 18.04.
- director | 1.4.3
- Icinga:

```
Application information:
  Installation root: /usr
  Sysconf directory: /etc
  Run directory: /run
  Local state directory: /var
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

System information:
  Platform: Ubuntu
  Platform version: 18.04.1 LTS (Bionic Beaver)
  Kernel: Linux
  Kernel version: 4.15.0-29-generic
  Architecture: x86_64

Build information:
  Compiler: GNU 7.3.0
  Build host: 8213f0f5ca15

```

**Comment by RogerSik** [comment]
With the upgrade to to the Icinga Director 1.5.1 the issue was solved for me.

**Comment by Thomas-Gelf** [comment]
Thanks for letting us know!
