### ISSUE TITLE
API - 401 Unauthorized

### ISSUE THREAD

**Issue by Hagislav** [Icinga/icingaweb2-module-director#1362]
I am not sure if I am at the right place to ask this, but I have a problem accessing the Director API.
I am using the icinga2x vagrant box (for testing). 
I have installed the director module and there are no problem using it and deploying configuration via the Web Interface. 
But when I am trying to use the REST API I always get a 401 Unauthorized error:

curl -H 'Accept: application/json' -u 'icingaadmin:icinga' -X GET -i http://localhost/icingaweb2/director/host -k
HTTP/1.1 401 Unauthorized
Date: Wed, 17 Jan 2018 14:11:14 GMT
Server: Apache/2.4.6 (CentOS)
X-Powered-By: PHP/7.1.8
Www-Authenticate: Basic realm="Icinga Web 2"
Content-Length: 381
Connection: close
Content-Type: text/html; charset=iso-8859-1

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">

401 Unauthorized

Unauthorized
This server could not verify that you
are authorized to access the document
requested.  Either you supplied the wrong
credentials (e.g., bad password), or your
browser doesn't understand how to supply
the credentials required.

Am I getting something wrong?
I read the docu and think I have to use a icinga web user to authenticate.
The default user icingaadmin:icinga has Permissions "*"...

Anybody has a solution for my problem?

Cheers

## Your Environment

* Director version: latest
* Icinga 2 vagrant box (icinga2x)

**Comment by lazyfrosch** [comment]
Please see https://github.com/Icinga/icingaweb2/issues/3173 - this can be fixed locally or icingaweb2.conf rolled out with the upcoming release
