### ISSUE TITLE
Inheritence of Choices

### ISSUE THREAD

**Issue by dgoetz** [Icinga/icingaweb2-module-director#1363]
## Expected Behavior
Choices are overwritten if set on a template and overwritten on a object.

## Current Behavior
Choices are added if set on a template and overwritten on a object.

## Steps to Reproduce (for bugs)
1. Create a choice (e.g. teams)
2. Create a template (e.g. Windows Server)
3. Select a choice on the template (e.g. Windows Team on Windows Server)
4. Create a host using the template but change the choice (e.g. Windows Server using the Template but another team is responsible)

## Context
Using the example above and assign rules based on the templates (e.g. Windows Team in host.templates) will also match on hosts where it is expected to be overwritten.

## Your Environment
* Director version (System - About): support/1.4.2+Cherrypick of the Excel Modifier
* Icinga Web 2 version and modules (System - About): 2.4.1
* Icinga 2 version (`icinga2 --version`): 2.8.1
* Operating System and version: RHEL 7
* Webserver, PHP versions: HTTPD + FPM, PHP 7.1

**Comment by Thomas-Gelf** [comment]
Hint for myself: choices shouldn't be available on templates at all. If they're shown, that's a bug.
