### ISSUE TITLE
import zone attribute for hosts doesnt work when its not set

### ISSUE THREAD

**Issue by marcelfischer** [Icinga/icingaweb2-module-director#1367]
We're trying to import the zone attribute via csv file because some hosts cannot directly reached from the masters. Everything is working fine for newly imported hosts. But when we try to update a hosts to the "extra" zone with import, its not working.

## Expected Behavior
I would expect that I can set the zone attribute via import whether its already set or not.

## Current Behavior
We're trying to import the zone attribute via csv file because some hosts cannot directly reached from the masters. Everything is working fine for newly imported hosts. But when we try to update a hosts to the "extra" zone with import, its not working.
Most of our hosts have no zone attribute because we let the director decide the zone. So Zone is set to "- please choose -"

As workaround, you have to choose "master" as zone for every host, then the importer could update the attribute to something else.

## Possible Solution
Don't know

## Steps to Reproduce (for bugs)
1. Setup some hosts and dont choose a zone manually
2. Setup import via director and try to change the zone attribute for hosts
3. Run the import

## Your Environment

* Director version (System - About): 1.4.1
* Icinga Web 2 version and modules (System - About): 2.4.2
* Icinga 2 version (`icinga2 --version`): 2.7.2
* Operating System and version: RHEL 7.4
* Webserver, PHP versions:

**Comment by Thomas-Gelf** [comment]
As mentioned in January, this should be fixed. In case this problem persists please let me know.
