### ISSUE TITLE
RestApi not use handleApiRequest method

### ISSUE THREAD

**Issue by lipazsolt** [Icinga/icingaweb2-module-director#1373]
RestApi not use handleApiRequest method therefore the exceptions not seen in JSON API. 

## Expected Behavior
```
$ ./director-curl POST director/host '{
        "object_name": "host1",
...
        }'
HTTP/1.1 422 Unprocessable Entity
Date: Thu, 25 Jan 2018 13:32:58 GMT
Server: Apache
Strict-Transport-Security: max-age=15768000
Content-Length: 63
Content-Type: application/json

{
    "error": "Trying to recreate icinga_host (host1)"
}
```
## Current Behavior
```
~$ ./director-curl POST director/host '{
        "object_name": "host1",
...
        }'
HTTP/1.1 500 Internal Server Error
Date: Thu, 25 Jan 2018 12:54:55 GMT
Server: Apache
Strict-Transport-Security: max-age=15768000
Content-Length: 31
Connection: close
Content-Type: application/json

{"status":"error","message":""}
```
## Possible Solution
It easy to fix this with one row change:
```
$ diff RequestHandler_orig.php RequestHandler_new.php
32c32
<         $this->processApiRequest();
---
>         $this->handleApiRequest();
```

## Steps to Reproduce (for bugs)
1. Create a host via API (POST) 
2. Create again with same name

## Your Environment
* Director version (System - About): 1.4.3
* Icinga Web 2 version and modules (System - About): 2.5.1
* Icinga 2 version (`icinga2 --version`): r2.8.1-1)
* Operating System and version: 16.04.3 LTS (Xenial Xerus)
* Webserver, PHP versions: Apache/2.4.18 (Ubuntu), PHP 7.0.22-0ubuntu0.16.04.1

**Comment by Thomas-Gelf** [comment]
Absolutely right, thanks for reporting this!
