### ISSUE TITLE
Services Sets cause UI issue on Single Services tab

### ISSUE THREAD

**Issue by philomory** [Icinga/icingaweb2-module-director#1374]
## Expected Behavior
Service Apply Rules defined in a Service Set should show up only under that Service Set (or maybe also under the Service Apply Rules tab); they should not show up as part of the 'Single Services' list.

## Current Behavior
Services that are defined as part of a Service Set, with an Apply Rule on that Service Set (and the Service Set not manually assigned to any hosts) show up on the 'Single Services' tab, with a listed host of `- none -` in red.

![image](https://user-images.githubusercontent.com/200123/35468227-fb27b99c-02bd-11e8-904c-54498f5822c5.png)

## Possible Solution
Services created as part of Service Sets shouldn't show up under the 'Single Services' tab at all, certainly not if they are only applied by Apply Rules on those Service Sets. If, as an implementation detail, Service records exist in the Director database for these definitions, those records should be filtered out before the list of Single Services is displayed in the UI.

## Steps to Reproduce (for bugs)
1. Create a Service Set
2. Set an apply rule for the Service Set
3. Create a service in that Service Set
4. Switch to the Single Services tab and observe the service you just created is listed there.

## Your Environment
* Director version (System - About): 1.4.2
* Icinga Web 2 version and modules (System - About): 2.5.0
  * fileshipper: 1.0.1
  * monitoring: 2.5.0
  * puppetdb: 1.0.0
* Icinga 2 version (`icinga2 --version`):
```
icinga2 - The Icinga 2 network monitoring daemon (version: r2.8.0-1)

Copyright (c) 2012-2017 Icinga Development Team (https://www.icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Application information:
  Installation root: /usr
  Sysconf directory: /etc
  Run directory: /run
  Local state directory: /var
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

System information:
  Platform: CentOS Linux
  Platform version: 7 (Core)
  Kernel: Linux
  Kernel version: 3.10.0-693.5.2.el7.x86_64
  Architecture: x86_64

Build information:
  Compiler: GNU 4.8.5
  Build host: unknown
```
* Operating System and version: CentOS 7
* Webserver, PHP versions:
  * Apache: 2.4.6
  * PHP: 7.1.3

**Comment by Thomas-Gelf** [comment]
Thanks for reporting this! Has already been fixed with dbe8aee for #1299.
