### ISSUE TITLE
Undefined offset: 166 (TemplateTree.php:186) after upgrade from 1.3.1 to 1.4.3

### ISSUE THREAD

**Issue by marcinkorzycki** [Icinga/icingaweb2-module-director#1375]
## Expected Behavior
Deploying changes should work normally

## Current Behavior
Deploying changes from activity log cause undefined offset: 166 (TemplateTree.php:186)

## Possible Solution
?

## Steps to Reproduce (for bugs)
Upgrade Director from 1.3.1 to 1.4.3, do a migration job, then change smth on host and try to deploy changes.

## Your Environment

* Director version (System - About): 1.4.3
* Icinga Web 2 version and modules (System - About): 2.5.1
* Icinga 2 version (`icinga2 --version`): 2.8.1-1
* Operating System and version: Debian 8
* Webserver, PHP versions: Apache/2.4.10, PHP 5.6.33-0+deb8u1

**Comment by bargru** [comment]
Maybe these can help you: https://github.com/Icinga/icingaweb2-module-director/issues/1156#issuecomment-327305290 and https://github.com/Icinga/icingaweb2-module-director/issues/1156#issuecomment-327311348

**Comment by marcinkorzycki** [comment]
> Maybe these can help you: #1156 (comment) and #1156 (comment)

Nope... problem still occurs...

**Comment by lazyfrosch** [comment]
This is most likely a problem caused be restoring a service set for a host.

Can you verify with https://github.com/Icinga/icingaweb2-module-director/issues/1115#issuecomment-402648585

If it is this issue it duplicates #1115

**Comment by lazyfrosch** [comment]
I'm going to close this issue, in case your problem is not related to #1115, please re-open and add a stack trace.
