### ISSUE TITLE
 Fatal error: Trait 'dipl\Web\Controller\Extension\ControlsAndContentHelper' not found in /usr/share/icingaweb2/modules/director/library/Director/Web/Controller/ActionController.php on line 31

### ISSUE THREAD

**Issue by dtinaquero** [Icinga/icingaweb2-module-director#1383]
After install Icinga Director I get this error:

Fatal error: Trait 'dipl\Web\Controller\Extension\ControlsAndContentHelper' not found in /usr/share/icingaweb2/modules/director/library/Director/Web/Controller/ActionController.php on line 31

I found the ControlsAndContentHelper in the folder 
/usr/share/icingaweb2/modules/director/library/vendor/**ipl**/Web/Controller/Extension/

I renamed the folder to **dipl** but the error continues.

## Environment

* Director version (System - About): 1.4.3
* Icinga Web 2 version and modules (System - About): 2.5.1
* Icinga 2 version (`icinga2 --version`): r2.8.1-1
* Operating System and version: Ubuntu 16.04 Server
* Webserver, PHP versions:  Apache, PHP 7.0.22

Thank you.

**Comment by thammw** [comment]
How did you "install" director? 
Renaming the folder doesn't matter since its just a namespace named dipl.

**Comment by dtinaquero** [comment]
To install Director I have followed the following instructions. https://github.com/Icinga/icingaweb2-module-director/blob/master/doc/02-Installation.md

I have checked the file and the line "trait ControlsAndContentHelper" is present.

Thank you

**Comment by thammw** [comment]
Did you use git clone for the process of dropping the folder?

And when do you get this message?

**Comment by dtinaquero** [comment]
I downloaded Director from the following URL https://github.com/Icinga/icingaweb2-module-director/releases
I get the message when I click on the Icinga Director link.

**Comment by thammw** [comment]
so you downloaded the file, unpacked it fully, copied it into /usr/share/icingaweb2/modules and renamed it into "director" ? Could you actually just redo all of that. I just set up a Ubuntu Server with icinga2 and icingaweb2 and did all of the setup and it just works... :(

The File in the folder does have the ending ".php", right?
I only would get the error if i either remove it or rename it in any way, shape or Form. " /usr/share/icingaweb2/modules/director/library/vendor/ipl/Web/Controller/Extension/ ControlsAndContentHelper.php" (Case-sensitive) should be the Filename/path. Rights are rw-r--r-- (0644) with root:root .

**Comment by dtinaquero** [comment]
Thank you for your help.
The permissions of the file are rights.
What version of PHP have you installed?

Thank you.

**Comment by thammw** [comment]
php 7.1.11

**Comment by Thomas-Gelf** [comment]
Does this issue still exist?
