### ISSUE TITLE
provider_class limitation

### ISSUE THREAD

**Issue by darkounet** [Icinga/icingaweb2-module-director#1388]
## Expected Behavior

Trying to add a new PropertyModifier via an external module ( it works with a name <72char )
but the field provider_class is limiting to 72char in the table import_row_modifier

## Current Behavior

Get this message : 

Storing import_row_modifier[] failed: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'provider_class' at row 1
Name of the provider : 

\Icinga\Module\Filtermansfriend\ProvidedHook\Director\PropertyModifierArrayKeyValue

## Possible Solution

Increase the provider_class limit to varchar 255 ?

## Steps to Reproduce (for bugs)

Try adding a new module with a providedHook and a long name 

## Your Environment
* Director version (System - About): master 
* Icinga Web 2 version and modules (System - About):     2.5.0
* Icinga 2 version (`icinga2 --version`):  r2.8.1-1
* Operating System and version: Debian GNU/Linux 8 (jessie)
* Webserver, PHP versions: Apache2.4 & php5.6

**Comment by bahamut45** [comment]
👍

**Comment by SoulKyu** [comment]
👍

**Comment by Thomas-Gelf** [comment]
Makes sense. As a workaround, you can of course shorten the class name, move it to another namespace (`ProvidedHook\Director` is not a hard requirement, you can also pass the full class name in run.php) and implement `getName()` to still visualize a meaningful name. I'll close this as a duplicate exists in #1022, will be part of v1.5.0.

Thanks,
Thomas
