### ISSUE TITLE
Service template/host template should not allow to import itself

### ISSUE THREAD

**Issue by reachmenetym** [Icinga/icingaweb2-module-director#1391]
## Expected Behavior

Service template should not allow to import itself. Remove service template in the import suggestion list which is matching current service template name. 
<h4>i.e If you create a service template called "test_service_template" then, "test_service_template" should not be listed in import suggestion list for the template. </h4>
<h4>This issue is also with host template</h4>

## Current Behavior

If user is accidentally import service template itself and store the configuration, next time nothing they can do with the service template. Which is causing a loop and crashing the server with memory exhaust issue. Even the service template can't be deleted after that.  

## Possible Solution

Remove the service template from import drop-down list if it matches name with name of the editing service template.

## Steps to Reproduce (for bugs)

1. Icinga Director -> Monitored Service -> Service Templates -> Add -> <service_template_name> -> Add

2. Icinga Director -> Monitored Service -> Service Templates -> service_template_name -> Modify -> Imports -> service_template_name -> Store

3. Icinga Director -> Monitored Service -> Service Templates -> service_template_name

## Your Environment

* Director version (System - About): master (Commit: a011cace483ee4ebb6a396510fd6edd8c0c69bd1)
* Icinga Web 2 version and modules (System - About): 2.5.1
* Icinga 2 version (`icinga2 --version`): r2.8.1-1
* Operating System and version: Ubuntu 16 Server
* Webserver, PHP versions: 7.0.25

**Comment by matthenning** [comment]
I'd like to help with a pull request @Thomas-Gelf but I'm struggling.
My idea was to use the current object name and remove it from the suggestions provided in the "Inherits" form field.
To do that I was looking at the data available in SuggestController->indexAction() but the autocomplete xhr request only sends the `context` and `value` parameters.
Is there a clean way of sending additional data so you can use them in the SuggestController?

**Comment by Thomas-Gelf** [comment]
#1631 will address the root issue here. @matthenning: you're absolutely right, suggestions need to be filtered, elements from the ancestor tree should not be offered. However, as one would still be able to manually write one of those name it wouldn't be completely safe. I'll close this in favor of #1631. We are currently working on a new and more flexible Form implementation, I guess once we have that we'll also address the Suggest-problem - giving it more power and context.

**Comment by ariesow** [comment]
Hi @Thomas-Gelf , Good day to you.
If accident does happen and below already in director, how can i revert this ?

`template Service "check_fortigate_ses" {
    max_check_attempts = "3"
    check_interval = 1m
    retry_interval = 30s
    check_timeout = 30s
}

template Service "check_fortigate_ses" {
    import "check_fortigate_ses"

    check_command = "check_fortigate_ses"
}
`
