### ISSUE TITLE
Selfservice API fails to return Powershell parameters

### ISSUE THREAD

**Issue by dgoetz** [Icinga/icingaweb2-module-director#1394]
## Expected Behavior
Selfservice API return Powershell parameters correctly.

## Current Behavior
```
curl -k -H "Accept: application/json" -X POST "http://example.com/icingaweb2/director/self-service/powershell-parameters?key=83221a83ac2f80b273e34723f189024643a22d7f"
<br />
<b>Fatal error</b>:  Uncaught Error: Call to a member function getZoneName() on null in /usr/share/icingaweb2/modules/director/library/Director/Objects/IcingaObject.php:1582
Stack trace:
#0 /usr/share/icingaweb2/modules/director/application/controllers/SelfServiceController.php(291): Icinga\Module\Director\Objects\IcingaObject-&gt;getRenderingZone()
#1 /usr/share/icingaweb2/modules/director/application/controllers/SelfServiceController.php(265): Icinga\Module\Director\Controllers\SelfServiceController-&gt;addHostToParams(Object(Icinga\Module\Director\Objects\IcingaHost), Array)
#2 /usr/share/icingaweb2/modules/director/application/controllers/SelfServiceController.php(193): Icinga\Module\Director\Controllers\SelfServiceController-&gt;shipPowershellParams()
#3 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Director\Controllers\SelfServiceController-&gt;powershellParametersAction()
#4 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action-&gt;dispatch('powershellParam...')
#5 /usr/shar in <b>/usr/share/icingaweb2/modules/director/library/Director/Objects/IcingaObject.php</b> on line <b>1582</b><br />
```

## Possible Solution
If I am correct the call to getRenderingZone in `application/controllers/SelfServiceController.php` is the only one which does not pass the config, so it falls back to null which causes the error.
```
$zoneName = $host->getRenderingZone();
```

## Steps to Reproduce (for bugs)
1. Configure Selfservice API
2. Create API key on a template
3. Register a host with the API key
4. Try to get the powershell parameters (via the powershell module or simply via curl from linux)

## Your Environment
* Director version (System - About): 1.4.3
* Icinga Web 2 version and modules (System - About): 2.5.1
* Icinga 2 version (`icinga2 --version`): 2.8.1
* Operating System and version: CentOS 7
* Webserver, PHP versions: PHP-FPM 7.1

**Comment by Thomas-Gelf** [comment]
@dgoetz: this should be fixed, in case it isn't please let me know!
