### ISSUE TITLE
Allow to skip failing rows on Import

### ISSUE THREAD

**Issue by Thomas-Gelf** [Icinga/icingaweb2-module-director#1395]
One might want to skip rows matching certain criteria on import, even for bad ones like duplicate keys. They might be purged, and no precedence can be guaranteed. So, care should be taken. Still, this is a feature often asked by people importing from multiple sources not being under their direct control. Short use case: "someone messing up an import for his own servers should not delay other changes". In such cases, the Import should turn into a warning state, and Health Check should tell about such state.

Reminder:

```patch
--- a/schema/mysql.sql
+++ b/schema/mysql.sql
@@ -1324,6 +1324,7 @@ CREATE TABLE import_run (
   start_time DATETIME NOT NULL,
   end_time DATETIME DEFAULT NULL,
   succeeded ENUM('y', 'n') DEFAULT NULL,
+  warning_messages MEDIUMTEXT DEFAULT NULL, -- array, json-encoded
   PRIMARY KEY (id),
   CONSTRAINT import_run_source
     FOREIGN KEY import_source (source_id)
```

**Comment by Mordecaine** [comment]
We would appreciate this feature. Is this feature still on your roadmap?

**Comment by Thomas-Gelf** [comment]
Not with warnings, but there are now Modifiers to reject rows and there is one that allows to skip duplicates: #2215 - so this issue is resolved :-)

**Comment by Thomas-Gelf** [comment]
NB: I'll showcase this feature (next to many others) today in my talk at [Icinga Insights](https://icinga.com/events/icinga-insights-2020-12/) - eventually you might want to join us ;-)
