### ISSUE TITLE
Selfservice API does not allow to configure which global zones to use

### ISSUE THREAD

**Issue by dgoetz** [Icinga/icingaweb2-module-director#1399]
## Expected Behavior
The administrator can configure which global zones are used on environment or API key / template level.

## Current Behavior
There is no possibility to change the default.

## Possible Solution
A multiselect box should allow to select which global zones should be used for a system and so exposed via Selfservice API (/director/self-service/powershell-parameters). Having director-global as default is fine, overwriting with an environment specific default on the settings tab for self-service (director/settings/self-service) and overwriting per API key / template (director/host/agent) would allow to have specific global zones for Linux and Windows agents which reduces the number of reloads and network traffic for agents. 

## Your Environment
* Director version (System - About): 1.4.3
* Icinga Web 2 version and modules (System - About): 2.5.1
* Icinga 2 version (`icinga2 --version`): 2.8.1
* Operating System and version: CentOS 7
* Webserver, PHP versions: PHP-FPM 7.1

**Comment by Thomas-Gelf** [comment]
Setting is available, but only when the package is going to be installed. Should be made available even for those who prefer not to install the package.
