### ISSUE TITLE
Selfservice API: Service UserAccount not working

### ISSUE THREAD

**Issue by TobiasKneidl** [Icinga/icingaweb2-module-director#1405]
## Current Behavior
The Icinga 2 Service is always installed as NT AUTHORITY\NetworkService.

Any changes in Service-Useraccount are ignored.

## Your Environment
* Director version (System - About): master, checkout c4e9f7a
* Icinga Web 2 version and modules (System - About): 2.5.1
* Icinga 2 version (`icinga2 --version`): 2.5.1

**Comment by Thomas-Gelf** [comment]
We'll track this in #1297
