### ISSUE TITLE
Introduce a "Back Button" Functionality

### ISSUE THREAD

**Issue by widhalmt** [Icinga/icingaweb2-module-director#1406]
Hi,

While having the possibility to redeploy old, working, configuration to have extra time for fixing the configuration in Director it would be nice to have the possibility to restore old states of the Director Database as well.

Maybe more of a way to jump into a specific point in the activity log than a back button.

I know you can restore single configuration objects which is really great, but sometimes you created or deleted several objects and lost track about the interactions which makes problems hard to dissolve.

I imagine it being quite convenient to have a way to jump back to say before "started working on ESX Monitoring". This would be extra useful with #249 .

Cheers,
Thomas

**Comment by Thomas-Gelf** [comment]
You are asking for mysqldump.
