### ISSUE TITLE
Datafield with SQL Datatype cannot fetch data offset 1

### ISSUE THREAD

**Issue by mkayontour** [Icinga/icingaweb2-module-director#1415]
I want to provide all servicesets at a host variable, so I tried to use sql to query all 180 ServiceSets. 

First defined a datafield:
![datafield](https://user-images.githubusercontent.com/7584938/36832949-050d8f92-1d2e-11e8-8330-29c0e32cbdf4.PNG)

And then I tried to select the servicesets at hostcreation. 
![fetch-data](https://user-images.githubusercontent.com/7584938/36832963-15cfb4ae-1d2e-11e8-98d1-153691f1bf16.PNG)

## Current Behavior
Cannot select ServiceSets cause by error: 
Unable to fetch data: Undefined offset: 1

## Your Environment

* Director version (System - About): 1.4.3
* Icinga Web 2 version and modules (System - About): 2.5.1
* Icinga 2 version (`icinga2 --version`):  2.8.1
* Operating System and version: Crentos 6.9
* Webserver, PHP versions: Apache 2.2, PHP 7.0

**Comment by Thomas-Gelf** [comment]
The description of the `DB Query` field reads:

> This query should return exactly two columns, value and label

Cheers,
Thomas

**Comment by Thomas-Gelf** [comment]
NB: In case you want to use `object_name` both as your stored key and your shown value, you could alias the column like this:

```sql
SELECT object_name AS val, object_name AS label FROM icinga_service_set ORDER BY object_name;
```
