### ISSUE TITLE
Sync rule (merge) failed: Trying to recreate icinga_host

### ISSUE THREAD

**Issue by wols** [Icinga/icingaweb2-module-director#1419]
Six hosts are imported (created) from MySQL `import source` with "Key column name" `id`.

One host (name) was changed in database.

## Expected Behavior
Sync rule with "Update Policy" `Merge` should update the Icinga host object.
Button "Check for changes" should show:
```
Array
(
    [create] => 0
    [modify] => 1
    [delete] => 0
)
```

## Current Behavior
"Check for changes":
```
Array
(
    [create] => 6
    [modify] => 0
    [delete] => 0
)
```

```
This Sync Rule failed when last checked at 2018-03-02 18:57:36:
Exception while syncing Icinga\Module\Director\Objects\IcingaHost my_changed_host:
Trying to recreate icinga_host (my_changed_host)
```

## Environment
* Director version: master / d69c5a7cc7c6c2ed32056e175fa5aef6b05e02d5
* Icinga Web 2 version: 2.5.1
* Icinga 2 version: 2.8.1-1
* Operating System and version: Oracle Linux 7
* Webserver, PHP versions: apache-2.4.6, rh-php71-php-fpm

**Comment by Thomas-Gelf** [comment]
> "Key column name" `id`.

The key column field help says:
> This must be a column containing unique values like hostnames. Unless otherwise specified this will then be used as the object_name for the syncronized Icinga object. Especially when getting started with director please make sure to strictly follow this rule. Duplicate values for this column on different rows will trigger a failure, your import run will not succeed. Please pay attention when synching services, as "purge" will only work correctly with a key_column corresponding to host!name. Check the "Combine" property modifier in case your data source cannot provide such a field

...and the German translation:
> Muss eine Spalte sein, die eindeutige Werte wie Hostnamen enthält. Wenn nicht anders angegeben, wird dieser Wert dann als object_name für die synchronisierten Icinga Objekte verwendet. Insbesondere Benutzer mit wenig Erfahrung mit dem Director sollten sich unbedingt an diese Regel halten. Doppelte Werte in dieser Spalte erzeugen einen Fehler und der gesamte Importlauf schlägt fehl. Bitte beim Synchronisieren von Services Acht geben, "bereinigen" wird nur mit einer der host!name Syntax entsprechenden Schlüsselspalte funktionieren. Nutze den Eigenschaftsmodifikator "Kombinieren", falls die gegebenen Datenquelle keine solche Spalte bereitstellen kann

**Comment by wols** [comment]
I understand and thought exactly how to implement it: `id` is a unique value (but not a hostname), is never duplicated and `object_name` is specified separately.

Source is my table `peer`:

![01_import_source_modify](https://user-images.githubusercontent.com/764167/36932799-2b7b86d2-1ecf-11e8-8fca-8e87e97f4854.png)

Preview looks as desired:

![03_import_source_preview](https://user-images.githubusercontent.com/764167/36932803-34103072-1ecf-11e8-99e6-5933f6691f6c.png)

The columns are already oriented to `icinga_host` and Director holds a host template `ntpstatsng_peer` to import:

![02_syncrule_properties](https://user-images.githubusercontent.com/764167/36932801-313bb7a4-1ecf-11e8-91ef-9211c9611121.png)

**Comment by Thomas-Gelf** [comment]
Hi @wols,

set your key column to `object_name` and it will work (given your object_name column is unique). It doesn't matter that your source's primary key is another column.

Cheers,
Thomas

**Comment by wols** [comment]
### UPDATE
Regardless of "Update Policy" (Merge, Replace, Ignore) in the UI - column `sync_property.merge_policy` contains value `override` ever?

**Comment by Thomas-Gelf** [comment]
?

**Comment by wols** [comment]
A `test_rule` created with "Update Policy" = 'Merge'...

![10_sync_rule-test_modify](https://user-images.githubusercontent.com/764167/36933452-16e6f242-1ed9-11e8-8501-63d0b33f6185.png)

...only a test...

![10_sync_rule-properties](https://user-images.githubusercontent.com/764167/36933456-2582747a-1ed9-11e8-97e5-8a76e83d8187.png)

```
SELECT * FROM icingaweb2director.sync_property WHERE rule_id = 4
```
```
id   rule_id   source_id   source_expression   destination_field   priority   filter_expression   merge_policy
13   4         1           ${disabled}         disabled            1          NULL                override
```
I would have expected the value `merge` in column `merge_policy`.

https://github.com/Icinga/icingaweb2-module-director/blob/0bd2a328ed68d3a471c0e5995d09dc2e18ff3100/application/forms/SyncPropertyForm.php#L119-L121

**Comment by Thomas-Gelf** [comment]
The shown update policy affects the rule and is therefore stored in the `sync_rule` table. The `override` property in the `sync_property` table affects only this single property. `merge` only makes sense for properties like custom variables, as they can be structured data types. Properties like `disabled` can only have one value, so in case your import source ships this value it is going to be replaced.

**Comment by Thomas-Gelf** [comment]
Did changing the key column solve your original problem?

**Comment by wols** [comment]
Yes, I have tried various modifications - everything works. "Key column name" = `object_name` now.
Thank you so much!

**Comment by Thomas-Gelf** [comment]
You're welcome!
