### ISSUE TITLE
Director Job "config" not working

### ISSUE THREAD

**Issue by fmuell** [Icinga/icingaweb2-module-director#1421]
## Expected Behavior
Director Job type "config" can deploy new config to icinga2

## Current Behavior
Job is in error state because of:

(CURL ERROR: Received HTTP code 403 from proxy after CONNECT)

manual deployment of config works fine

## Steps to Reproduce (for bugs)
- create icinga director task with type config
- run "icingacli director jobs run"

## Your Environment
* Director version (System - About): 2.4.3
* Icinga Web 2 version and modules (System - About): 2.40
* Icinga 2 version (`icinga2 --version`): 2.6.1
* Operating System and version: centos 7

**Comment by lazyfrosch** [comment]
Do you have a proxy configured in your environment, or where you are running the jobs daemon?

Please check environment vars like `HTTPS_PROXY`

**Comment by fmuell** [comment]
Yes running printenv from Commandline shows a http_proxy and a https_proxy. But if i unset them its the same behaviour.

Strange thing is: manual export works every time without error. I checked the last runs of the job and sometimes its working now, but most of the time it brings die curl error.

I checked the icingaweb2 user for a .curlrc file, but did not find anything

**Comment by lazyfrosch** [comment]
I guess you are doing a manually export with the Webinterface. If you would set https_proxy in your webserver or fpm environment you'd also have problems connecting to HTTPs.

You should make sure to run Director's Job daemon with systemd, and without any proxy configured.

**Comment by lazyfrosch** [comment]
See https://www.icinga.com/docs/director/latest/doc/79-Jobs/#execution-methods
