### ISSUE TITLE
Update certificate path for icinga v2.8+

### ISSUE THREAD

**Issue by willhseitz** [Icinga/icingaweb2-module-director#1425]
## Expected Behavior

Certification path should be `/var/lib/icinga2/certs` as of icinga v2.8

## Current Behavior

Director's current version still has pre-v2.8 path of `/etc/icinga2/pki`

## Possible Solution

Update cert paths according to v2.8 changelogs: https://www.icinga.com/docs/icinga2/latest/doc/16-upgrading-icinga-2/#changed-certificate-paths

Should be just the 2 agent installers:
`/contrib/linux-agent-installer/Icinga2Agent.bash`
`/contrib/windows-agent-installer/Icinga2Agent.psm1`

## Your Environment

* Director version (System - About): 
* Icinga Web 2 version and modules (System - About):
* Icinga 2 version (`icinga2 --version`):
* Operating System and version:
* Webserver, PHP versions:

**Comment by Thomas-Gelf** [comment]
Director is still compatible with v2.6.x, that's why we didn't change this yet.

**Comment by Thomas-Gelf** [comment]
Will be fixed with #1504.
