### ISSUE TITLE
Deployment won't work Communication Link failure

### ISSUE THREAD

**Issue by mkayontour** [Icinga/icingaweb2-module-director#1430]
Hi There, 

we tried to deploy our configuration with massive changes and about 6000 Hosts "which are currently disabled" 

We do have about 300 ServiceSets which aren't filled with services yet, just about 40 Sets of them. 
Around 30 Service- and 20 Hosttemplates.
6000 Hosts currently disabled over Automation, every host hast about 5 custom vars. 

And now there's this error, I might think the director has some issues with such a big deployment.

![grafik](https://user-images.githubusercontent.com/7584938/37521241-4ae89194-2920-11e8-924b-73b305779a60.png)

![grafik](https://user-images.githubusercontent.com/7584938/37521227-37ef7756-2920-11e8-93b1-2be21ce34822.png)

## Your Environment

* Director version (System - About): 1.4.2
* Icinga Web 2 version and modules (System - About): 2.5.1
* Icinga 2 version (`icinga2 --version`): 2.8.1
* Operating System and version: Centos 6.9
* Webserver, PHP versions: Apache 2.4 PHP 7.0

**Comment by mkayontour** [comment]
False Alarm! 

max_allowed_packet=32M into mysql cnf and works great ;)

**Comment by Thomas-Gelf** [comment]
That's what I wanted to suggest :) Director should have no problem with that amount of hosts.
