### ISSUE TITLE
import from ldap source

### ISSUE THREAD

**Issue by lager1** [Icinga/icingaweb2-module-director#1432]
Hello,

im trying to migrate quite complex older nagios setup to icinga2. I have a fresh icinga2 and icinga2web install. I would like to automatically (or on demand) synchronize ldap to icinga2. I've managed to set up ldap source and use it as import source.

I've run into problem probably because our ldap schema. I need to synchronize ldap entries, where each entry may contain multiple attributes of same name. In the import source preview this results in ifferent data types (string or array). Example:

one entry contains:
```
cn: abc.com   
cn: abc1.com   
cn: abc2.com   
```   

this maps to array:
```
cn: [ "abc.com", "abc1.com" , "abc2.com" ]   
```   

But if the entry contains only one attribute, it looks like this: 

```
cn: abc3.com    
```   

this maps to string:
```
cn: "abc3.com"
```   

I am not able to transform values to same data type. It would be possible with modifiers, but they would have to be called conditionally for array or for string.

In ideal case i would like to take only the first (or the only one) value, that would be totally sufficient.
Is this somehow possible with this approach without changing the ldap schema?

The only other approach to this problem i think might work is using a script, which pregenetares the data needed and then i would feed it to the director using its api. This seems to me as a not so good path to resolve this, but im not sure. Suggestions are welcome. 

## Your Environment

* Director version (System - About):
```
master @ 1e7f0f962bf83be4590a211e96ab146ba3d0a65a
```
* Icinga Web 2 version and modules (System - About):
```
2.4.1
```
* Icinga 2 version (`icinga2 --version`):
```
icinga2 - The Icinga 2 network monitoring daemon (version: r2.6.0-1)

Copyright (c) 2012-2016 Icinga Development Team (https://www.icinga.org/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Application information:
  Installation root: /usr
  Sysconf directory: /etc
  Run directory: /run
  Local state directory: /var
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

System information:
  Platform: Debian GNU/Linux
  Platform version: 9 (stretch)
  Kernel: Linux
  Kernel version: 4.9.0-5-amd64
  Architecture: x86_64

Build information:
  Compiler: GNU 6.2.1
  Build host: amalia
```
* Operating System and version:
```
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.4 (stretch)
Release:	9.4
Codename:	stretch
```
* Webserver, PHP versions:
Webserver:
```
Server version: Apache/2.4.25 (Debian)
Server built:   2017-09-19T18:58:57
```

PHP:
```
PHP 7.0.27-0+deb9u1 (cli) (built: Jan  5 2018 13:51:52) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.27-0+deb9u1, Copyright (c) 1999-2017, by Zend Technologies
```

**Comment by Thomas-Gelf** [comment]
Hi Václav,

we could easily implement kind of a "Make Array" Property Modifier. 
Please open a related feature request in case you want to have such. As 
a quick solution for now you could use a hidden feature in the Director.

while defining your Sync Rules, I guess you're writing your cn list to a 
custom variable. Now, instead of syncing to my_var type my_var[] into 
the "Custom Variable" field. This should give the expected result.

Cheers,
Thomas

Am 18.03.2018 um 14:42 schrieb Václav Mach:

**Comment by lazyfrosch** [comment]
Well, the object_key is supposed to be a unique entry, we can't expand multiple entries from an LDAP search.

You could use modifiers:
* Extract from DN (to get only the object name)
* Filter array values + Join

**Comment by lager1** [comment]
Thanks for your replies.

I'm aware, that the ldap schema may not be considered valid, but this is just the way it was designed and it is now used. I would be possible to transform it, but it's a last resort option.

The modifier Extract from DN seems to do exactly what i am looking for. 

When i hit the preview tab of the import source with this modifier defined i get:
```
Invalid argument supplied for foreach() (LdapUtils.php:30)
#0 /usr/share/php/Icinga/Protocol/Ldap/LdapUtils.php(30): Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(2, 'Invalid argumen...', '/usr/share/php/...', 30, Array)
#1 /usr/share/icingaweb2/modules/director/library/Director/PropertyModifier/PropertyModifierExtractFromDN.php(49): Icinga\Protocol\Ldap\LdapUtils::explodeDN('domain.com')
#2 /usr/share/icingaweb2/modules/director/library/Director/Objects/ImportSource.php(147): Icinga\Module\Director\PropertyModifier\PropertyModifierExtractFromDN->transform('domain.com')
#3 /usr/share/icingaweb2/modules/director/library/Director/Objects/ImportSource.php(107): Icinga\Module\Director\Objects\ImportSource->applyPropertyModifierToRow(Object(Icinga\Module\Director\PropertyModifier\PropertyModifierExtractFromDN), 'cn', Object(stdClass))
#4 /usr/share/icingaweb2/modules/director/library/Director/Web/Table/ImportsourceHookTable.php(101): Icinga\Module\Director\Objects\ImportSource->applyModifiers(Array)
#5 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Web/Table/QueryBasedTable.php(213): Icinga\Module\Director\Web\Table\ImportsourceHookTable->fetchQueryRows()
#6 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Web/Table/QueryBasedTable.php(152): dipl\Web\Table\QueryBasedTable->fetch()
#7 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Web/Table/QueryBasedTable.php(116): dipl\Web\Table\QueryBasedTable->fetchRows()
#8 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Html/BaseElement.php(135): dipl\Web\Table\QueryBasedTable->renderContent()
#9 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Html/Html.php(171): dipl\Html\BaseElement->render()
#10 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Html/BaseElement.php(107): dipl\Html\Html->render()
#11 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Html/BaseElement.php(135): dipl\Html\BaseElement->renderContent()
#12 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Html/Html.php(259): dipl\Html\BaseElement->render()
#13 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Zf1/SimpleViewRenderer.php(47): dipl\Html\Html->__toString()
#14 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Zf1/SimpleViewRenderer.php(66): dipl\Zf1\SimpleViewRenderer->render()
#15 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/HelperBroker.php(272): dipl\Zf1\SimpleViewRenderer->postDispatch()
#16 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(518): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
#17 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('previewAction')
#18 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#19 /usr/share/php/Icinga/Application/Web.php(389): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#20 /usr/share/php/Icinga/Application/webrouter.php(109): Icinga\Application\Web->dispatch()
#21 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...')
#22 {main}
```

From this stacktrace is seems, that the value i want to preserve (`domain.com`) gets correctly parsed, but i'm not able to tell why it fails. It seems that the #0 stacktrace functions expects and array, but gets a string. 

I've also set logging to debug, but that did not help at all with this.

Am i using the modifier somehow wrong?

**Comment by Thomas-Gelf** [comment]
Seems that you're feeding the wrong column to the Property Modifier. Fetch and use the `dn`, and it should work fine. Not sure where your `domain.com` comes from, but it is defintively not a Distinguished Name in LDAP and therefore it doesn't qualify as an Input for the "Extract from DN" modifier.

**Comment by lager1** [comment]
You are totally right. I was using the `cn` attribute as s source propery. Using `dn` solved it. Thanks for help.

**Comment by Thomas-Gelf** [comment]
You're welcome!
