### ISSUE TITLE
defined hostgroup with apply, wrong inside director, working in icinga2

### ISSUE THREAD

**Issue by tlo8640** [Icinga/icingaweb2-module-director#1440]
Hello,

We have two hostgroup definitions with apply rules for defining group memberships.
Hostgroup1:
```
object HostGroup "new_staged" {
    display_name = "autoprov group new staged server"
    assign where host.vars.new_staged
}
```
Hostgroup2:
```
object HostGroup "PRODUCTION" {
    display_name = "PRODUCTION"
    assign where ! (host.vars.new_staged)
}
```
the second group apply rule was quite hard to implement, because I didn't found a "true or is set" opposite like "is false or not set". At least I created it in this way:
![production_apply_definition](https://user-images.githubusercontent.com/740897/37836074-e6adf13c-2eb1-11e8-9f97-f6dd3c92cbae.png)

Don't know if there are better ways to do it.

The variable "host.vars.new_staged" is defined in a host template and set to "true" and will be imported by the host_definition. 

## Expected Behavior
New staged Server has this variable set to true an so the server should be in the "new_staged" group and NOT in the "PRODUCTION" group. If someone decides to change this, he can simply change the boolean in the host definition to "false" and the server disappears from "new_staged" and occurs in "Production".

In Icinga director the hostgroup membership should be shown the right membership depending on the value of the boolean host variable 

## Current Behavior
But in Icinga Director the following happens:
If the boolean is set to true (doesn't matter if this value comes from the imported hsot template or it is set dirct in the host defnition), the host belongs to both hostgroups. In the host defnition you can see both hostgroups in "Applied Hostgroups" and in the hostgroup definition you will find the host in both hostgroup members.

BUT
When you deploy the host config to icinga2 everything is fine!
If var.new_staged is set to true, the host is member of the "new_staged" group and no member of "PRODUCTION".
If var.new_staged is set to false, the host is member of "PRODUCTION" and no meber of "new_staged"

That means it's wrong in Icinga Director but works as expected after deploy.

## Steps to Reproduce (for bugs)
Create two hostgroups with the mentioned apply rules, a custom boolean variable and a host definition with this boolean variable. 
if set to true, the server is member of both hostgroups, if set to false, the server is member of none hostgroup(s) -> ONLY iIN ICINGA DIRECTOR
If you run a deploy the server is meber of one of both hostgroups depending of the value of the boolean variable.

## Your Environment

* Director version (System - About): 1.4.1
* Icinga Web 2 version and modules (System - About): 2.4.1
* Icinga 2 version (`icinga2 --version`): 2.8.2
* Operating System and version: RHEL 7 64 BIt
* Webserver, PHP versions:

**Comment by offsides** [comment]
FYI, I created a pull request (#1436) to add that exact condition.  I hadn't realized I could do it with a NOT like that, though it does look like it's more complicated when combining a NOT with an AND.

**Comment by tlo8640** [comment]
thanks for the info about this pull request.
Finding out my "solution" was more playing around than know what to do...

**Comment by tlo8640** [comment]
I found out that with director Version 1.6.3 (or earlier) "my workaround" for "is false or not set" doesn't work anymore. It is been rendered correct now and so it's double negation in icinga2:
!(!(host.vars.new_staged))
Fortunately an entry for "is false (or not set)" was added in an update before, so my workaround isn't needed anymore

**Comment by tlo8640** [comment]
following my previous comment. this ticket will be closed, because now it's working as expected
