### ISSUE TITLE
How do you delete the audit log?

### ISSUE THREAD

**Issue by greenaar** [Icinga/icingaweb2-module-director#1442]
## Expected Behavior
I would like to have some way to remove the audit log (which continues to grow), or to limit it to a certain period of time.

## Current Behavior
There does not seem to be:
1. documentation on how to remove the audit log contents
2. a method in the ui to purge
3. a way to do it from the commandline.

## Possible Solution
Either a script to do a purge, or even just a few safe sql statements.

## Your Environment
* Director version (System - About): 1.4.3
* Icinga Web 2 version and modules (System - About): 2.5.1-1.xenial
* Icinga 2 version (`icinga2 --version`): 2.8.2-1.xenial
* Operating System and version: Ubuntu 16.04
* Webserver, PHP versions: Apache 2.4, Php 7.1

**Comment by Thomas-Gelf** [comment]
Usually other tables should grow faster, and even a million activities shouldn't be a problem at all. Anyways, a safe query should be:

```sql
DELETE FROM director_activity_log WHERE change_time < NOW() - INTERVAL 30 DAY;
```

There should be a configurable job and related documentation for this, so I'll keep this issue open.

**Comment by greenaar** [comment]
Thanks for your quick response.  Unfortunately, that doesn't work:

ERROR 1451 (23000): Cannot delete or update a parent row: a foreign key constraint fails (`icinga2`.`director_generated_config`, CONSTRAINT `director_generated_config_activity` FOREIGN KEY (`last_activity_checksum`) REFERENCES `director_activity_log` (`checksum`))

And from painful experience, touching director_generated_config breaks things in a more permanent fashion.

**Comment by Thomas-Gelf** [comment]
Oh, sure :see_no_evil:. No guarantee that this works, but in theory it should:

```sql
DELETE FROM director_deployment_log WHERE start_time < NOW() - INTERVAL 30 DAY;
DELETE FROM director_activity_log WHERE change_time < NOW() - INTERVAL 30 DAY;
```

Otherwise please let me know, I'll let you have a better query. Once executed, this will leave some traces (like related configs) in your database, but the housekeeping job should take care of them. You can configure it as a background job or actively run it via:

```sh
icingacli director housekeeping run
```

Once you did so, please run:

```sql
OPTIMIZE TABLE director_deployment_log;
OPTIMIZE TABLE director_generated_config;
OPTIMIZE TABLE director_generated_config_file;
OPTIMIZE TABLE director_generated_file;
OPTIMIZE TABLE director_activity_log;
```

This will give you back space on disk. `innodb_file_per_table` is a requirement.

**Comment by Thomas-Gelf** [comment]
Wait...

**Comment by Thomas-Gelf** [comment]
First delete from deployment_log, then run housekeeping, and then delete from activity_log. After all this: optimize.

**Comment by greenaar** [comment]
I still run into: ERROR 1451 (23000): Cannot delete or update a parent row: a foreign key constraint fails (`icinga2`.`director_generated_config`, CONSTRAINT `director_generated_config_activity` FOREIGN KEY (`last_activity_checksum`) REFERENCES `director_activity_log` (`checksum`))

**Comment by Thomas-Gelf** [comment]
Did housekeeping finish fine AFTER deleting from deployment_log and BEFORE deleting from activity_log?

**Comment by greenaar** [comment]
The command 'icingacli director housekeeping run' threw this error:

ERROR: Icinga\Exception\NotFoundError in /usr/share/icingaweb2/modules/director/library/Director/Db/Housekeeping.php:87 with message: There is no such task: all

Running it as 'icingacli director housekeeping run ALL' ran and returned with no messages (which i assumed to mean success).  This was run after deleting from the deployment log, and before running the delete on the activity log.

**Comment by greenaar** [comment]
I would be happy to try something else if there are any recommendations. As it stands, the above suggestions do not work.  Thank you.

**Comment by greenaar** [comment]
I'm in a state where I'd be happy to test any suggestions, I can (currently) bring my db back to a safe point in a few minutes.  I can see lots of cases where I'd want an audit long enabled, but it's a permanent item that continues to grow, and that's not useful.

I would be happy to even have some manual way to do this (that doesn't result in a totally broken db).. ie delete this, unlink that, delete that, link this, etc.

As it stands, the best I can be sure of doing by attempting to delete the audit log is to break it.

**Comment by mbassett** [comment]
I can confirm that the steps @Thomas-Gelf described work to clean up the old entries for me.  (skipping the housekeeping step I got foreign constraint, with housekeeping step everything worked)

DELETE FROM director_deployment_log WHERE start_time < NOW() - INTERVAL 30 DAY;
icingacli director housekeeping run ALL
DELETE FROM director_activity_log WHERE change_time < NOW() - INTERVAL 30 DAY;
OPTIMIZE TABLE director_deployment_log;
OPTIMIZE TABLE director_generated_config;
OPTIMIZE TABLE director_generated_config_file;
OPTIMIZE TABLE director_generated_file;
OPTIMIZE TABLE director_activity_log;

**Comment by greenaar** [comment]
Ok, I can confirm the steps @mbassett listed (in that order) work and do not error for me. Closing this ticket.

**Comment by austinjhunt** [comment]
@mbassett Thank you! 5 years later, still no official docs on the clearing of Icinga Director deployment history. This works beautifully.

**Comment by edpstiffel** [comment]
Just stumbled upon this issue while searching for reducing our 50GB director database a bit.
We have a 19GB activity log table, but also a 17GB director_generated_file table.
Is there a way to truncate the second table also?
