### ISSUE TITLE
PHP Exception on command delete

### ISSUE THREAD

**Issue by hydrian** [Icinga/icingaweb2-module-director#1443]
## Expected Behavior
Delete icinga internal command or block because it has to be deferenced

## Current Behavior

SQLSTATE[23503]: Foreign key violation: 7 ERROR: update or delete on table "icinga_command" violates foreign key constraint "icinga_service_check_command" on table "icinga_service"
DETAIL: Key (id)=(215) is still referenced from table "icinga_service"., query was: DELETE FROM icinga_command WHERE (id = 215)

#0 /usr/share/icingaweb2/library/vendor/Zend/Db/Statement.php(297): Zend_Db_Statement_Pdo->_execute(Array)
#1 /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Abstract.php(470): Zend_Db_Statement->execute(Array)
#2 /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Pdo/Abstract.php(232): Zend_Db_Adapter_Abstract->query(String, Array)
#3 /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Abstract.php(652): Zend_Db_Adapter_Pdo_Abstract->query(String)
#4 /etc/icingaweb2/modules/director/library/Director/Data/Db/DbObject.php(837): Zend_Db_Adapter_Abstract->delete(String, String)
#5 /etc/icingaweb2/modules/director/library/Director/Data/Db/DbObject.php(960): Icinga\Module\Director\Data\Db\DbObject->deleteFromDb()
#6 /etc/icingaweb2/modules/director/library/Director/Web/Form/DirectorObjectForm.php(855): Icinga\Module\Director\Data\Db\DbObject->delete()
#7 /etc/icingaweb2/modules/director/library/Director/Web/Form/DirectorObjectForm.php(789): Icinga\Module\Director\Web\Form\DirectorObjectForm->deleteObject(Object(Icinga\Module\Director\Objects\IcingaCommand))
#8 /etc/icingaweb2/modules/director/library/Director/Web/Form/DirectorObjectForm.php(775): Icinga\Module\Director\Web\Form\DirectorObjectForm->handlePost()
#9 /etc/icingaweb2/modules/director/library/Director/Web/Form/QuickForm.php(518): Icinga\Module\Director\Web\Form\DirectorObjectForm->onRequest()
#10 /etc/icingaweb2/modules/director/library/Director/Web/Form/QuickForm.php(530): Icinga\Module\Director\Web\Form\QuickForm->setRequest(Object(Icinga\Web\Request))
#11 /etc/icingaweb2/modules/director/library/Director/Web/Form/QuickForm.php(367): Icinga\Module\Director\Web\Form\QuickForm->getRequest()
#12 /etc/icingaweb2/modules/director/library/Director/Web/Controller/ObjectController.php(418): Icinga\Module\Director\Web\Form\QuickForm->handleRequest()
#13 /etc/icingaweb2/modules/director/library/Director/Web/Controller/ObjectController.php(113): Icinga\Module\Director\Web\Controller\ObjectController->addObjectForm(Object(Icinga\Module\Director\Objects\IcingaCommand))
#14 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Director\Web\Controller\ObjectController->editAction()
#15 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch(String)
#16 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#17 /usr/share/php/Icinga/Application/Web.php(407): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#18 /usr/share/php/Icinga/Application/webrouter.php(104): Icinga\Application\Web->dispatch()
#19 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#20 {main}

## Steps to Reproduce (for bugs)
1. Create icinga internal command
2. Create service template with that command
3. Try to delete command

A. If you try to deference the service from the command you get this error also:
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 262144 bytes) in /etc/icingaweb2/modules/director/library/Director/Resolver/TemplateTree.php on line 222

## Your Environment

* Director version (System - About):
* Icinga Web 2 version and modules (System - About): Master  as Mar 12 11:12:22 2018 +0100
* Icinga 2 version (`icinga2 --version`): 2.8.2-1  (via official ppa)
* Operating System and version: Ubuntu 16.04.4 LTS
* Webserver, PHP versions:
Apache2 - 2.4.18-2ubuntu3.5
PHP -  7.0.28-0ubuntu0.16.04.1

**Comment by Thomas-Gelf** [comment]
![director_command_delete_forbidden](https://user-images.githubusercontent.com/553008/39625133-6cb7f6e6-4f9c-11e8-9b48-ccedc9d9ea59.png)

**Comment by Thomas-Gelf** [comment]
It's no longer possible to delete commands which are still being used. The shown memory error is not related, if that one persists please open a dedicated issue.
