### ISSUE TITLE
Assign rules not only for is-set but also for is-not-set

### ISSUE THREAD

**Issue by rafiwui** [Icinga/icingaweb2-module-director#1444]
This issue is very close to issue #339.
The only difference is that I am missing an option to check if some value is false instead of true.
Especially when it comes to services that are based on commands with different flags this is something very important.
Because with the current options I must create different service templates for one command.
So my idea was that you would have only the **is** as comparator and then can select **true** or **false**.

**Comment by Thomas-Gelf** [comment]
Fixed with #1436
