### ISSUE TITLE
Wrap json_encode to emit errors

### ISSUE THREAD

**Issue by psi-4ward** [Icinga/icingaweb2-module-director#1445]
I had some invalid utf8 characters in the database. 
This should not happen, of course, but it breaks director with some confusing behavior. 
It leads to `API request failed: Stage creation failed.` on config deployments.

I could track down to `json_encode($body)` which returns `false` if the content object is not valid (in my case invalid utf8 chars) and so the body of the API-Request to Icinga2 is empty.
To make director more robust we should wrap `json_encode()` and evaluate `json_last_error()` to throw a real error on problems.

**Comment by Thomas-Gelf** [comment]
Throwing an error at that stage absolutely makes sense, Director expects data in it's database to be clean. How did you manage it to get those characters in there, as this shouldn't happen?!

**Comment by psi-4ward** [comment]
It's a (very) old Icinga2 installation.
I don't know why I got invalid chars, perhaps the charset has changed in some sql upgrade scripts from latin1 to utf8_mb4 or smth like that.
It's one of these bugs who happen rarely but take a huge amount of time to solve cause of misleading errors like `API request failed: Stage creation failed.`

**Comment by Thomas-Gelf** [comment]
Director never used `latin1`, it was `utf8` from the beginning

**Comment by Thomas-Gelf** [comment]
Don't worry, there will be an exception. But do not expect Director to protect people who manually mess up their data from themselves :p

**Comment by Thomas-Gelf** [comment]
Also: mysqldump/import will not mess up your character set unless being forced to do so

**Comment by Thomas-Gelf** [comment]
It would be great if you could figure out how this happened, because if this somehow was possible through the UI we need to put stricter validation in place.

**Comment by psi-4ward** [comment]
I've really no idea why the charsets was messed up but I'm sure it's not a director bug.

**Comment by psi-4ward** [comment]
Only the error message on config-deploy was very very confusing :)

**Comment by Thomas-Gelf** [comment]
And how did you fix it?

**Comment by psi-4ward** [comment]
corrected the charset to utf8_general_ci and removed the dead characters form the rows.

**Comment by Thomas-Gelf** [comment]
> corrected the charset to utf8_general_ci

Was this a manually crafted thing? This should never have been anything but utf8. I pushed a wrapper for those errors to master, could you please give it a try? Honestly, I didn't even test it - but it looks like it could work ;-) In case it does, I'll apply it in other places too.

**Comment by psi-4ward** [comment]
Cause I've corrected the errors I don't have a test env anymore.

**Comment by lippserd** [comment]
Hi Tom,

In our Web 2 library we have a `Json` util which nearly does the same thing as your implementation. I would rather not introduce new code for that in the director.

Cheers,
Eric

**Comment by Thomas-Gelf** [comment]
@lippserd: I wanted to use it - but unfortunately it's not possible as long as Director supports Icinga Web >= 2.4.1
