### ISSUE TITLE
Performance Issues when Importing and Syncing from slow or big import source

### ISSUE THREAD

**Issue by fmuell** [Icinga/icingaweb2-module-director#1447]
## Expected Behavior
When creating import job modifiers or sync rule properties the creation of those objects will not reload the import source. It should use a precached state of the source which is locally in the director db

## Current Behavior
When creating import job modifiers or sync rule properties the director module reloads the import source on every creation which leads to massive performance issues when impoting from a slow or very big import source. We use one import source which needs approx. 60-90 seconds for one import.

## Possible Solution
Cache the Importsource state (especially the colums / source fields) in locally director db. Use the cached state for import source modifier and sync rule property creation. Only load from Import source when using import or preview.

## Steps to Reproduce (for bugs)
- create import job from slow / very big import source
- add import job modifiers
- add sync rule with properties from slow import source

## Your Environment
* Director version (System - About): 1.4.3
* Icinga Web 2 version and modules (System - About): 2.4.0
* Icinga 2 version (`icinga2 --version`): 2.6.1
* Operating System and version: centos 7

**Comment by Thomas-Gelf** [comment]
What kind of Import Source are you using? The explained behavior should be shown only by ImportSources with not efficient `listColumns()` implementation. The SQL import had that problem, but since we fixed this in #1071 it now caches the columns every time you store the Import Source itself.

**Comment by Thomas-Gelf** [comment]
No feedback.
