### ISSUE TITLE
HostGroup assigned via HostTemplate is not considered for authentication role

### ISSUE THREAD

**Issue by zampat** [Icinga/icingaweb2-module-director#1449]
## Current Behavior / How to reproduce:
Defining in Icinga Authentication -> Roles a filter "director/filter/hostgroups" a host group.
Assign the hostgroup the hosts via template
The hosts having this hostgroup assigned for via host template are not visible in director

## Expected Behavior
The rights should be granted to hosts as if hostgroup is assigned directly to host.

Environment: Director 1.4.2

**Comment by lazyfrosch** [comment]
Could you please share an example for objects and filters?

Is the assigned hostgroup shown beneath a host? (in the form should be "assigned hostgroups") - when browsing without restrictions.

**Comment by zampat** [comment]
Hello Markus:

sure, here I show you a definition of a host group and a template having this host group assigned and the definition of a host, importing this hostgroup:

The Hostgroup definition used to grant monitoring view and edit rights in director:
zones.d/director-global/hostgroups.conf
object HostGroup "Windows Hosts Rome" {
}

The Host Template:
zones.d/director-global/host_templates.conf
template Host "generic-windows-rome" {
    check_command = "hostalive"
    max_check_attempts = "3"
    check_interval = 5m
    retry_interval = 1m
    check_timeout = 1m
    enable_notifications = true
    enable_active_checks = true
    enable_passive_checks = true
    enable_event_handler = true
    enable_perfdata = true
    volatile = false
    icon_image = "win.png"
    groups = [ "Windows Hosts Rome" ]
}

The Host Definition:
zones.d/master/hosts.conf

object Host "host_rome_dummy" {
    import "generic-windows-rome"
    address = "10.0.0.1"
}

The View in Director (logged in as Administrator): Yes, the Host Group appears to be assigend:
![image](https://user-images.githubusercontent.com/3853721/40602192-f666fb1c-6257-11e8-8824-d3682bcd9a8b.png)

Here I show how ROLE for administrator for Hosts of Hostgroup "Windows Hosts Rome" is defined:
![image](https://user-images.githubusercontent.com/3853721/40602243-2b481474-6258-11e8-9ae6-1cb8472d9a77.png)

When logging in as user "rome" I see the host in monitoring, but not in director:
![image](https://user-images.githubusercontent.com/3853721/40602304-60ec6f8a-6258-11e8-9247-aa05adf22eb3.png)


![image](https://user-images.githubusercontent.com/3853721/40602277-4ce31e4e-6258-11e8-8514-d3de8610068e.png)

When Host Group is directly assigened to Host, then host is shown in Director:
![image](https://user-images.githubusercontent.com/3853721/40602498-1e51a6f8-6259-11e8-9034-2348ebd246d8.png)

![image](https://user-images.githubusercontent.com/3853721/40602507-244b24d0-6259-11e8-843c-bca5228805c1.png)

**Comment by Thomas-Gelf** [comment]
Thanks @zampat! Will be fixed within this week and released with v1.5.0
