### ISSUE TITLE
Rename a command to the same name an external command have

### ISSUE THREAD

**Issue by Naro370** [Icinga/icingaweb2-module-director#1452]
## Expected Behavior
Renaming an existing command to the name of an existing external command should fail with an error message.

## Current Behavior
Renaming an existing command to the name of an existing external command disturb the config so far, that you can't rename the command any more (because it is now a half external command) and the fields of the external command are moved to the new command. Maybe there are more problems with that DB inconsistent.

I had to fix it in the database directly.

## Possible Solution
Fail with a appropriate error message bevor it can do bad things.

## By the way
Creating a new object with a name of an existing external command will fail with that error message "Trying to recreate icinga_command (http) (DbObject.php:777)". So no problem, but a more appropriate error message would be nice.

## Steps to reproduce (for bugs)
1. Create a new command with the name "test123"
2. Rename that command to "http" (or another external command you have)

## Your Environment
- Director version: master (last update: 19.03.2018)
- Icinga Web 2 version and modules: 2.5.1-1.stretch
- Icinga 2 version: 2.8.2-1.stretch
- Operating System and version: Debian 9 (stretch)
- Webserver, DB, PHP versions: Apache 2.4.25-3+deb9u3, mariadb-10.1.26-0+deb9u1, PHP-7.0.27-0+deb9u1

**Comment by Thomas-Gelf** [comment]
I can confirm this

**Comment by Thomas-Gelf** [comment]
We'll fix this with #1496
