### ISSUE TITLE
Is it possible to enable/disable hosts using the API?

### ISSUE THREAD

**Issue by terra-nova** [Icinga/icingaweb2-module-director#1461]
## Expected Behavior

I am trying to figure out how to disable hosts based on host group membership using the Icinga Director API. By disabling I mean the same action that is triggered by selecting the "Disabled: yes" property in the host properties view.

## Current Behavior

I am not able to disable a host using the API. I cannot find documentation for doing so.

## Possible Solution

?

## Steps to Reproduce (for bugs)

?

## Your Environment

* Director version (System - About): Git master from 2018-03-28
* Icinga Web 2 version and modules (System - About): 2.5.1
* Icinga 2 version (`icinga2 --version`): 2.8.1
* Operating System and version: CentOS 7.4 x64
* Webserver, PHP versions: Apache 2.4, PHP 7.1

**Comment by cptnkoiz** [comment]
same here.

**Comment by lstyles** [comment]
I too would like to know if it's possible to do via the API.

**Comment by BastiBr** [comment]
Same here. Is there any news?

**Comment by hardoverflow** [comment]
Hi guys,

i solved it like this command.
```
for i in $(curl -sku USER:PASS 'https://icinga2.host.tld:5665/v1/objects/hosts?filter=match(%22THIS-IS-MY-HOSTGROUP%22,host.groups)' | jq -r '.results[].name'); do curl -sku USER:PASS -H "Accept: application/json" -X POST "https://icinga2.host.tld/icingaweb2/director/host?name=$i" -d '{"disabled": true}'; done
```
