### ISSUE TITLE
cannot delete multiple objects

### ISSUE THREAD

**Issue by lager1** [Icinga/icingaweb2-module-director#1462]
## Expected Behavior

I would like to be able to delete multiple objects at once by a button, form or just by selecting specific objects. Selecting with holding shift key (or using ctrl) is possible in hosts page. It would be great to be able to use this feature in other director parts too. 

## Current Behavior

If i want to delete some objects, I have to manually select all of the objects and delete them by one. 

It may seem that this this use case is not appropriate for many people, but i found out, that if i change some of my sync rules which previously synchronized some objects, the old objects (which after modification seem not to be related to sync rule) do not get deleted.

## Possible Solution

Implement selecting all/multiple objects same as with hosts.

## Your Environment

* Director version (System - About):
```
master @ 1e7f0f962bf83be4590a211e96ab146ba3d0a65a
```

* Icinga Web 2 version and modules (System - About):
```
2.4.1
```

* Icinga 2 version (`icinga2 --version`):
```
icinga2 - The Icinga 2 network monitoring daemon (version: r2.6.0-1)

Copyright (c) 2012-2016 Icinga Development Team (https://www.icinga.org/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Application information:
  Installation root: /usr
  Sysconf directory: /etc
  Run directory: /run
  Local state directory: /var
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

System information:
  Platform: Debian GNU/Linux
  Platform version: 9 (stretch)
  Kernel: Linux
  Kernel version: 4.9.0-5-amd64
  Architecture: x86_64

Build information:
  Compiler: GNU 6.2.1
  Build host: amalia
```

* Operating System and version:
```
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.4 (stretch)
Release:	9.4
Codename:	stretch
```

* Webserver, PHP versions:
```
Server version: Apache/2.4.25 (Debian)
Server built:   2017-09-19T18:58:57
```

```
PHP 7.0.27-0+deb9u1 (cli) (built: Jan  5 2018 13:51:52) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.27-0+deb9u1, Copyright (c) 1999-2017, by Zend Technologies
```

**Comment by Thomas-Gelf** [comment]
For Hosts it works since v1.2, if I recall it correctly the Delete button has been added shortly after that release. Since v1.4 it is also available for single services:

![Multi-Select Services](https://www.icinga.com/wp-content/uploads/2017/10/director_choose-multiple-services.png)

More and more features have been added, like adding Services/Sets to multiple hosts at once. Do you have a concrete example where you want to also see it applied? And for what operations?

**Comment by lager1** [comment]
Currently I am not able to delete (not even select) multiple service groups and host groups. 

I do not need to do this any more (switched to production environment, so not deleting objects), so this could could be considered a feature (at leats for mentioned types of objects).
