### ISSUE TITLE
Windows absolute Path %SystemRoot% not detected

### ISSUE THREAD

**Issue by flohoff** [Icinga/icingaweb2-module-director#1469]
The function for detecting absolute in Paths in library/Director/Objects/IcingaCommand.php does not detect Windows Path aliases like %SystemRoot% %ProgramData% %ProgramFiles%

This is with director 1.4.2

Flo

**Comment by Thomas-Gelf** [comment]
This depends on [Icinga 2 issue #6259](https://github.com/Icinga/icinga2/issues/6259), but I'll fix it right now in the Director. So once the other issue is fixed, we're ready to go.
