### ISSUE TITLE
Purge feature does not seem to be deleting objects

### ISSUE THREAD

**Issue by yoshi314** [Icinga/icingaweb2-module-director#1471]
I have an import defined for classic http checks from sql

The sync role matched to the sql query has Update Policy: replace and Purge: yes

Unfortunately the subsequent syncs do not remove old services and merely add new ones. Given that this table defines 200+ services, it's a real chore to clean this up.

I am using director 1.4.3 at the moment.

Quickest way to check it is to add record to sql database, refresh the import source and the sync rule to generate new object, delete the record from database and while import source detects changes in source database, the sync rule does nothing, unless existing object was altered or new one was added.

**Comment by yoshi314** [comment]
I seem to be doing something very wrong here still: 

```
critical/config: Error: Name for object 'a4b-pl-host!PL - Front - LUCENE - demo.abstore.pl - n2' of type 'Service' is invalid: Object names may not contain '!'
Location: in [stage]/zones.d/ABS/services.conf: 218:1-218:71
[stage]/zones.d/ABS/services.conf(216): }
[stage]/zones.d/ABS/services.conf(217): 
[stage]/zones.d/ABS/services.conf(218): object Service "a4b-pl-host!PL - Front - LUCENE - demo.abstore.pl - n2" {
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[stage]/zones.d/ABS/services.conf(219):     host_name = "a4b-pl-host"
[stage]/zones.d/ABS/services.conf(220):     import "service-no-notifications"
```

**Comment by yoshi314** [comment]
I assume that i have to map actual object name to something else, then.

**Comment by Thomas-Gelf** [comment]
Mapping the object_name to the service name should do the job, yes. And of course the 'host' property also needs to be set at sync time. Purge is pretty conservative, it removes only objects that vanished between the Import Run related to the latest successful Sync and "now". So, in case you fiddled with your keys, it might have missed some "delete" operations.

That requires you to manually clean up your services. When going to your Single Services list, you can select multiple lines via SHIFT/CRTL-Click, this should help to speed things up.
