### ISSUE TITLE
Author is not filled in director_activity_log.author (when adding host)

### ISSUE THREAD

**Issue by InkUisitor** [Icinga/icingaweb2-module-director#1472]
## Expected Behavior
Ability to add Hosts

## Current Behavior
When I use Director to Clone a host (or add), an error telling me that director_activity_log.author is not filled appears.

## Possible Solution
For the moment, I made an alter column on the database to made author column nullable

## Your Environment
* Director version (System - About): 1.4.0
* Icinga Web 2 version and modules (System - About): 2.5.1
* Icinga 2 version (`icinga2 --version`): 2.8.2-1
* Operating System and version: Ubuntu 17.10
* Webserver, PHP versions: 7.1.15-0ubuntu0.17.10.1 / Zend engine 3.1.0

**Comment by InkUisitor** [comment]
OK... It's not a problem with Director but with IcingaWeb. I still was logged but my user was NULL...
I logged out and logged in again and the problem disapear...

**Comment by Thomas-Gelf** [comment]
I have been able to reproduce this by accident. It happens if you switch from Icinga Web 2.5.x to 2.4.x (or the other way round) while being logged in. There is nothing Director can do about this, logging out and in again fixes the problem.
