### ISSUE TITLE
Apply Rule changes Macros 

### ISSUE THREAD

**Issue by Wintermute2k6** [Icinga/icingaweb2-module-director#1482]
## Expected Behavior
Director should leave the Macro intact without changing the 'string' or field 'value'

## Current Behavior
Icinga2 Runtime Macro won't resolve / Director Parser changes entry in Field

## Possible Solution
Currently no Idea how to solve this

## Steps to Reproduce (for bugs)
1) Clean Base Setup Icinga 2 & Icinga Web 2  + Director v1.4.3
2) Create Service & Host Template + Host and Service
3) Create Apply Rule for Service
4) Enter Macro in Field & click store ( See Screenshots Service Apply_Rule_Macro1-4.png) Screenshots at the bottom
5) Preview rendered Config .. Macro wont work anymore ( See Screenshots Service Apply_Rule_Macro1-4.png) Screenshots at the bottom

## Your Environment

* Director version (System - About): See Screenshot Director_Version.png
![director_version](https://user-images.githubusercontent.com/7203835/39744973-3470ad98-52a6-11e8-8f37-8d7c6d0d627d.png)

* Icinga Web 2 version and modules (System - About): See Screenshot Modules_Version.png
![modules_version](https://user-images.githubusercontent.com/7203835/39744963-2dd4062e-52a6-11e8-9b47-ad3c0d3b6338.png)

* Icinga 2 version (`icinga2 --version`):
icinga2 - The Icinga 2 network monitoring daemon (version: r2.8.4-1)

Copyright (c) 2012-2017 Icinga Development Team (https://www.icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Application information:
  Installation root: /usr
  Sysconf directory: /etc
  Run directory: /run
  Local state directory: /var
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

System information:
  Platform: CentOS Linux
  Platform version: 7 (Core)
  Kernel: Linux
  Kernel version: 3.10.0-693.21.1.el7.x86_64
  Architecture: x86_64

Build information:
  Compiler: GNU 4.8.5
  Build host: unknown

* Operating System and version:
cat /etc/os-release 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

* Webserver, PHP versions:
[root@test modules]# yum list installed | grep httpd
httpd.x86_64                     2.4.6-67.el7.centos.6    @updates              
httpd-tools.x86_64               2.4.6-67.el7.centos.6    @updates              
[root@test modules]# yum list installed | grep scl
centos-release-scl.noarch        2-2.el7.centos           @extras               
centos-release-scl-rh.noarch     2-2.el7.centos           @extras               
rh-php71-php-cli.x86_64          7.1.8-1.el7              @centos-sclo-rh       
rh-php71-php-common.x86_64       7.1.8-1.el7              @centos-sclo-rh       
rh-php71-php-fpm.x86_64          7.1.8-1.el7              @centos-sclo-rh       
rh-php71-php-gd.x86_64           7.1.8-1.el7              @centos-sclo-rh       
rh-php71-php-intl.x86_64         7.1.8-1.el7              @centos-sclo-rh       
rh-php71-php-json.x86_64         7.1.8-1.el7              @centos-sclo-rh       
rh-php71-php-ldap.x86_64         7.1.8-1.el7              @centos-sclo-rh       
rh-php71-php-mbstring.x86_64     7.1.8-1.el7              @centos-sclo-rh       
rh-php71-php-mysqlnd.x86_64      7.1.8-1.el7              @centos-sclo-rh       
rh-php71-php-pdo.x86_64          7.1.8-1.el7              @centos-sclo-rh       
rh-php71-php-pgsql.x86_64        7.1.8-1.el7              @centos-sclo-rh       
rh-php71-php-xml.x86_64          7.1.8-1.el7              @centos-sclo-rh       
rh-php71-php-zip.x86_64          7.1.8-1.el7              @centos-sclo-rh       
rh-php71-runtime.x86_64          1-1.el7                  @centos-sclo-rh       
scl-utils.x86_64                 20130529-18.el7_4        @updates              
sclo-php71-php-pecl-imagick.x86_64 3.4.3-2.el7              @centos-sclo-sclo 

![apply_service_rule_macro1](https://user-images.githubusercontent.com/7203835/39746917-1b9df3f6-52ac-11e8-9b14-3bdb6dc4a5c7.png)
![apply_service_rule_macro2](https://user-images.githubusercontent.com/7203835/39746923-1fd6c420-52ac-11e8-877a-072e49ad7116.png)
![apply_service_rule_macro3](https://user-images.githubusercontent.com/7203835/39746934-236ce31c-52ac-11e8-9957-982e56b30a83.png)
![apply_service_rule_macro4](https://user-images.githubusercontent.com/7203835/39746937-284f1fb2-52ac-11e8-9c3f-6e46f31a701d.png)

**Comment by Thomas-Gelf** [comment]
Thanks for reporting this, should be fixed with v1.5.0!
