### ISSUE TITLE
Can't access to CustomVar Overview through Icinga Director

### ISSUE THREAD

**Issue by BlackDrag0n** [Icinga/icingaweb2-module-director#1485]
Can't access to CustomVar Overview through Icinga Director.
Give me this error:

`Fatal error: Uncaught ErrorException: Creating default object from empty value in /usr/share/php/Icinga/Web/Controller/ActionController.php:127 Stack trace: #0 /usr/share/php/Icinga/Web/Controller/ActionController.php(127): Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(2, 'Creating defaul...', '/usr/share/php/...', 127, Array) #1 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(59): Icinga\Web\Controller\ActionController->__construct(Object(Icinga\Web\Request), Object(Icinga\Web\Response), Array) #2 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response)) #3 /usr/share/php/Icinga/Application/Web.php(576): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response)) #4 [internal function]: Icinga\Application\Web->Icinga\Application\{closure}() #5 {main} Next Zend_Controller_Exception: Creating default object from empty value#0 /usr/share/php/Icinga/Web/Contr in /usr/share/icingaweb2/library/vendor/Zend/Controller/Plugin/Broker.php on line 332`

**Comment by Thomas-Gelf** [comment]
This should have been fixed with 05bc9e5 this morning, could you please try again?
