### ISSUE TITLE
Vars override not possible if service template name different than service when inherited from host template

### ISSUE THREAD

**Issue by tlo8640** [Icinga/icingaweb2-module-director#1489]
## Expected Behavior
When creating host template adding some services to this host template you can create host objects inheriting from this host template with all the service checks from this template. Great!

Sometimes you have to change (override) some values in the inherited Services for the created host individually

## Current Behavior

This works fine unless you change the name of the service checks when you attach it to the host template. Then you can't override anything anymore.

## Possible Solution
Currently (as an workaround), when we need other names for the services than the template name we create additional services  templates from the (generic) services templates and add the created templates (with the wished name) to the host template.

## Steps to Reproduce (for bugs)
What is working:
- create a host template
- create a service template with custom variables
- add a service to the host template using the create service template (keep the name!)
- create a host from the host template
- override some curom variables in the service of the create host
- works fine!

What doesn't work:
- create a host template
- create a service template with custom variables
- add a service to the host template using the create service template and change the name of the service!
- create a host from the host template
- (try) to override some curom variables in the service of the create host
- you fail!

Perhaps this Problem is related to 
https://github.com/Icinga/icingaweb2-module-director/issues/1368

## Your Environment

* Director version (System - About): 1.4.1
* Icinga Web 2 version and modules (System - About): 2.4.1
* Icinga 2 version (`icinga2 --version`): 2.8.2
* Operating System and version: RHEL 7
* Webserver, PHP versions:...

**Comment by Thomas-Gelf** [comment]
You're correct, this duplicates #1368 which has been fixed yesterday.
