### ISSUE TITLE
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 262144 bytes) in /usr/share/icingaweb2/modules/director/library/Director/Resolver/TemplateTree.php on line 181

### ISSUE THREAD

**Issue by mit99** [Icinga/icingaweb2-module-director#1494]
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 262144 bytes) in /usr/share/icingaweb2/modules/director/library/Director/Resolver/TemplateTree.php on line 181

Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 262144 bytes) in Unknown on line 0

![image](https://user-images.githubusercontent.com/39548109/40407776-d26eaec6-5e65-11e8-8627-33598cee8deb.png)

## Your Environment

* Director version (System - About):  0f4fd471e28a4f18560eceeb318475f20fe766f1
* Icinga Web 2 version and modules (System - About): 2.5.3
* Icinga 2 version (`icinga2 --version`):  r2.8.4-1
* Operating System and version: 16.04.4 LTS (Xenial Xerus)
* Webserver, PHP versions: Apache 2.4.18, PHP 7.0.30

**Comment by lx183** [comment]
I' m facing the same issue.

**Comment by lx183** [comment]
It seems like the "fetchall" function leads to a memory overflow. However, increasing the memory (memory_limit = 4000M) in the **/etc/opt/rh/rh-php71/php.ini** file to 4GB does not help.

![image](https://user-images.githubusercontent.com/35256191/44459109-aac84180-a608-11e8-948f-bc55456d4c96.png)

https://github.com/Icinga/icingaweb2-module-director/blob/d7c92a29bd53e5f4d224877b1efdde3b9a5a889e/library/Director/Resolver/TemplateTree.php

**Comment by lx183** [comment]
The issue occured after multiple imports from the vSphere module, so maybe that could cause the issue.

**Comment by Thomas-Gelf** [comment]
You somehow created a loop. Please see #1631 and the issues linked there for suggestions on how to fix your setup.
