### ISSUE TITLE
Allow to configure Director package name

### ISSUE THREAD

**Issue by Thomas-Gelf** [Icinga/icingaweb2-module-director#1497]
## Expected Behavior

I want to be able to choose a custom name for the configuration package deployed to Icinga.

## Current Behavior

The package name is hard-coded to `<module name>`, being `director`.

**Comment by friesoft** [comment]
Looks good to me. Thanks! :smile: 
Works nicely in my vagrant testbox :+1:
 
I guess it is works as (currently) designed that object names (hostnames, template names, ...) have to differ between packages, as you mentioned. Are there any plans to automatically add some sort of internal prefix, as discussed? Not mandatory for us but would be the icing(a) on the cake :)
