### ISSUE TITLE
Hostgroup creation with sync rule fails

### ISSUE THREAD

**Issue by Holundermann** [Icinga/icingaweb2-module-director#1500]
## Expected Behavior

Sync Rule for Hostgroup should create a hostgroup for objects matching the filter expression

## Current Behavior

An error occurs when the director applies the sync rule:
![image](https://user-images.githubusercontent.com/6639547/40469722-c17301a4-5f31-11e8-9c1e-34f254469d7a.png)

## Possible Solution

Bugfix

## Steps to Reproduce (for bugs)

- add Puppet DB as Data Source
- create a Sync Rule for Hostgroups matching at least one Host
- set the following options in the Modify tab:
![image](https://user-images.githubusercontent.com/6639547/40469881-2c5b2bea-5f32-11e8-95c2-978419e6a90c.png)
- set the following parameters in the properties tab
![image](https://user-images.githubusercontent.com/6639547/40469910-45acf876-5f32-11e8-8fa7-1e9ec2e7ba31.png)
- try to execute the sync rule

## Your Environment

* Director version (System - About):
1.4.3
* Icinga Web 2 version and modules (System - About):
2.5.1
* Icinga 2 version (`icinga2 --version`):
icinga2 - The Icinga 2 network monitoring daemon (version: r2.8.2-1)

Copyright (c) 2012-2017 Icinga Development Team (https://www.icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Application information:
  Installation root: /usr
  Sysconf directory: /etc
  Run directory: /run
  Local state directory: /var
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

System information:
  Platform: Debian GNU/Linux
  Platform version: 9 (stretch)
  Kernel: Linux
  Kernel version: 4.9.0-6-amd64
  Architecture: x86_64

Build information:
  Compiler: GNU 6.3.0
  Build host: 022328c363ac

* Operating System and version:
Debian 9
* Webserver, PHP versions:
PHP 7.0
Apache 2.4.25
* Database version:
Postgres Database 9.6

**Comment by Holundermann** [comment]
Same behavior with no filter expression:
![image](https://user-images.githubusercontent.com/6639547/40473610-f57e694c-5f3c-11e8-8bd0-a44a5587ef92.png)
Result:
![image](https://user-images.githubusercontent.com/6639547/40473648-12945870-5f3d-11e8-84c1-585f825c45dd.png)

![image](https://user-images.githubusercontent.com/6639547/40473671-22971c08-5f3d-11e8-9849-53542e7946c5.png)

**Comment by Thomas-Gelf** [comment]
Oh, I see - thank you!

**Comment by Thomas-Gelf** [comment]
I'm now able to reproduce this, affects PostgreSQL only. I pushed new Sync-related [tests](https://travis-ci.org/Icinga/icingaweb2-module-director/builds/383633954) to a separate branch, will dig deeper.
