### ISSUE TITLE
Duplicate deployments. One is done. The second is always in the execution state.

### ISSUE THREAD

**Issue by Aleksey-Maksimov** [Icinga/icingaweb2-module-director#1503]
Hello!

## Expected Behavior

I assume that the Deployment tab should not have duplicate entries.

## Current Behavior

Duplicate deployments. 
One is done. The second is always in the execution state.

![director-duplicate-deployment](https://user-images.githubusercontent.com/17614847/40624096-0a3534c8-629a-11e8-9ec7-f850d4420110.png)

I completely rebooted the Icinga server, but the situation does not change.
All new deployments are successful, but this old deployment is always in progress status. 
This is very embarrassing.

## Steps to Reproduce (for bugs)

I don't know how to reproduce the problem. The first time faced with such a problem.

## Environment

* Director version (System - About): 1.4.3 
* Icinga Web 2 version and modules (System - About): 2.5.3
* Icinga 2 version (`icinga2 --version`): r2.8.4-1
* Operating System and version: Debian GNU/Linux 8 (jessie) (kernel 3.16.0-4-amd64)
* Webserver, PHP versions: Apache/2.4.10 , PHP 5.6.33-0+deb8u1

**Comment by Thomas-Gelf** [comment]
Hi @Aleksey-Maksimov,

this is nothing to worry about, I'll show you how to make this "look normal". But first I'd like to figure out how this happened. Deploying the same configuration is perfectly legal, but then they should get different stage names. So, first of all to get a better idea of what happened please show me the output of:

```sql
SELECT
    id,
    start_time,
    LOWER(SUBSTR(HEX(config_checksum), 1, 7)) AS config,
    stage_name,
    duration_dump
  FROM director_deployment_log
  WHERE SUBSTR(config_checksum, 1, 3) = UNHEX('8ff25d');
```

**Comment by Aleksey-Maksimov** [comment]
Hello, Thomas.

+------+---------------------+---------+-----------------------------+---------------+
| id   | start_time          | config  | stage_name                  | duration_dump |
```
+------+---------------------+---------+-----------------------------+---------------+
| 1498 | 2018-05-28 16:12:53 | 8ff25d1 | KOM-AD01-MON20-1527513173-0 |           100 |
| 1499 | 2018-05-28 16:12:53 | 8ff25d1 | KOM-AD01-MON20-1527513173-1 |            99 |
+------+---------------------+---------+-----------------------------+---------------+
2 rows in set (0.00 sec)
```

**Comment by Aleksey-Maksimov** [comment]
Hello, Thomas.

Can you help me?

**Comment by Thomas-Gelf** [comment]
Duplicates #1488, will be fixed immediately. Sorry for the delay, I now finally found someone who helped me to reproduce this.
