### ISSUE TITLE
vars override funktioniert nicht

### ISSUE THREAD

**Issue by Diego-Holzer** [Icinga/icingaweb2-module-director#1514]
Vor 2 Tagen den Director updated.
Nach abschicken einer geänderten Konfiguration werden alle vars overrides ignoriert unter Services.

Nach einem Redeploy auf eine Konfig vor dem Update sind die vars overrrides korrekt. Ein aktuelles Deploy ignoriert die overrides.

**Comment by Thomas-Gelf** [comment]
@Diego-Holzer: kann ich grad nicht nachvollziehen... "&copy; bei mir läufts". Wäre aber natürlich ziemlich doof, weshalb ich für weitere Details dankbar wäre. Was zeigt der Config-Preview? Gerne auch per Mail...

**Comment by Diego-Holzer** [comment]
wo finde ich den deine E-Mail? Dann kann ich ein paar Screenshots machen.
Der Director zeigt mir die Korrekten Variablen an, Aber unter dem Dashboard sind andere Parameter hinterlegt.

**Comment by Thomas-Gelf** [comment]
Die ist Teil eines jeden [Commits](https://github.com/Icinga/icingaweb2-module-director/commit/85ea19d12e5826d198ca041a38f0d95424c378de.patch) ;-)

**Comment by Diego-Holzer** [comment]
hier mal den Auszug aus dem Host Inspection:
vars | {   _override_servicevars: {     nrpe-Check_DRIVESIZE: {       nrpe_arguments: [         "Drive=C:",         "Drive=D:",         "MaxWarn=75%",         "MaxCrit=90%"       ]     }   },   geolocation: "46.91394, 7.35893" }
-- | --

Hier der Auszug aus dem Service Inspection:
vars | {   nrpe_arguments: [     "Drive=C:",     "Drive=E:",     "MaxWarn=90%",     "MaxCrit=95%"   ],   nrpe_command: "CheckDRIVESIZE" }
-- | --

Habe ein Hosttemplate, mit dem Service und den Grundparameter. Bei einigen Hosts muss ich mit dem Override die Parameter überschreiben, weil Laufwerk D statt E abgefragt werden darf.
Im Director ist alles konfiguriert wie immer, aber unten kommt was anderes an.

**Comment by Thomas-Gelf** [comment]
Vielleicht auch hilfreich -> Deployments -> Render Config -> Diff with other config -> die letzte funktionierende wählen -> Links/Rechts vertauschen (Pfeile in der Mitte) -> Unterschiedliche Files untersuchen

**Comment by vita2** [comment]
Hallo Tom,

ich kann das o. g. Verhalten bestätigen. Aktuell bin ich im Master-Branch auf Commit 85ea19d12e5826d198ca041a38f0d95424c378de.

Hier zwei Screenshots betreffend des gewünschten Diffs. Links (8cfc243) ist die zuletzt funktionierende Config zu sehen, rechts (2c51068) ist die aktuelle Config bei der die Overrides nicht mehr funktionieren:

![1](https://user-images.githubusercontent.com/25298055/41097868-c49376d8-6a59-11e8-9ee5-b43b61881ab9.png)

![2](https://user-images.githubusercontent.com/25298055/41097869-c4b01c70-6a59-11e8-8621-98fb89a12fbb.png)

In `zones.d/director-global/service_apply.conf` gab es auch Änderungen. Hier wurden die Host-Variablen in Anführungs- und Dollar-Zeichen gesetzt aber ich vermute das das nicht die Ursache ist:

![3](https://user-images.githubusercontent.com/25298055/41097870-c4cba436-6a59-11e8-8610-1bc1ededf8c0.png)

Auszug der Config für einen Load Service-Check:

**zones.d/site-a/hosts.conf**
```
object Host "host-a" {
    ...
    vars["_override_servicevars"] = {
        ...
        load = {
            load_cload1 = 15
            load_cload15 = 10
            load_cload5 = 15
            load_wload1 = 12
            load_wload15 = 8
            load_wload5 = 12
        }
    }
    ...
}
```

**zones.d/director-global/service_apply.conf**
```
apply Service "load" {
    check_command = "load"
    max_check_attempts = "3"
    check_period = "24x7"
    check_interval = 1m
    retry_interval = 30s
    enable_notifications = false
    enable_active_checks = true
    enable_passive_checks = false
    enable_event_handler = false
    enable_perfdata = true
    volatile = false
    icon_image = "services"
    template_choice = "Check Execution Speed"

    assign where "server-linux" in host.templates
    command_endpoint = host_name
    vars.tags = [ "operatingsystem" ]

    import DirectorOverrideTemplate
}
```

**zones.d/director-global/service_templates.conf**
```
template Service "load" {
    check_command = "load"
    max_check_attempts = "3"
    check_period = "24x7"
    check_interval = 1m
    retry_interval = 30s
    enable_notifications = false
    enable_active_checks = true
    enable_passive_checks = false
    enable_event_handler = false
    enable_perfdata = true
    volatile = false
    icon_image = "services"
    template_choice = "Check Execution Speed"
    command_endpoint = host_name
    vars.tags = [ "operatingsystem" ]
}
```

**zones.d/director-global/001-director-basics.conf**
```
const DirectorStageDir = dirname(dirname(current_filename))

globals.directorWarnedOnceForThresholds = false;
globals.directorWarnOnceForThresholds = function() {
    if (globals.directorWarnedOnceForThresholds == false) {
        globals.directorWarnedOnceForThresholds = true
        log(LogWarning, "config", "Director: flapping_threshold_high/low is not supported in this Icinga 2 version!")
    }
}

if (! globals["DirectorOverrideTemplate"]) {
  const DirectorOverrideVars = "host var overrides (Director)"
  const DirectorOverrideTemplate = "_override_servicevars"

  template Service DirectorOverrideTemplate ignore_on_error {
    /**
     * Seems that host is missing when used in a service object, works fine for
     * apply rules
     */
    if (! host) {
      var host = get_host(host_name)
    }

    if (vars) {
      vars += host.vars[DirectorOverrideVars][name]
    } else {
      vars = host.vars[DirectorOverrideVars][name]
    }
  }
}
```

Bei der aktuellen Config kommen die Schwellwerte nicht von den Override-Servicevars sondern es werden die Default-Werte aus dem Check-Command genutzt.

Lass mich wissen wenn Du weitere Infos benötigst. Dann lasse ich Dir das baldmöglichst zukommen.

Gruß,
David

**Comment by Diego-Holzer** [comment]
Hast du auch zufällig von ICINGA Version r2.8.2-1 nach r2.8.4-1 gewechselt?

**Comment by Thomas-Gelf** [comment]
Servus David,

hatte gerade Gelegenheit mir das auf Diegos System anzuschauen... ziemlich schräg, die Config sieht für mich korrekt aus. Könntest du mir mal versuchen, in der `IcingaConfig.php` in `renderHostOverridableVars` folgende Zeilen zu entfernen...

```patch

          return sprintf(
              '
- if (! globals["DirectorOverrideTemplate"]) {
    const DirectorOverrideVars = "%s"
    [..]
    }
- }
',
            $settings->override_services_templatename,
```
...und neu zu deployen?

**Comment by Thomas-Gelf** [comment]
Ich hab's

**Comment by Thomas-Gelf** [comment]
Bitte nochmal testen

**Comment by vita2** [comment]
@Diego-Holzer 
Ich meine das auf dem System schon seit der Freigabe die Version 2.8.4-1 läuft, aber genau kann ich es nicht mehr nachvollziehen.

@Thomas-Gelf 
`git pull` gemacht und läuft wieder :) Ich danke Dir!

**Comment by Thomas-Gelf** [comment]
Danke für's schnelle testen, sorry für den Bug!
