### ISSUE TITLE
External check display same result as main server

### ISSUE THREAD

**Issue by bdevroey** [Icinga/icingaweb2-module-director#1515]
## Expected Behavior
Check disk space on each server

## Current Behavior
Local host/master: 127.0.0.1
DISK OK - free space: / 41043 MB (92% inode=97%): (this is the correct result)

Remote Server1:
Plugin Output
DISK OK - free space: / 41043 MB (92% inode=97%): /boot/efi 98 MB (99% inode=-):

Remote Server2:
Plugin Output
DISK OK - free space: / 41043 MB (92% inode=97%): /boot/efi 98 MB (99% inode=-):

De remote servers outputs the same results as the local server.
I also had the same issue with apt update check when receiving an alarm on for the apts for the master and al other servers: I did an upgrade only the master (apts) and the other suddenly the alarms for the other remote host also despaired .

Other checks as Pop, imap, smtp gives there unique results but the above problem tells me that it outputs the results only from the master/local even that the check is asked on each seperate host.

## Setup
Zone name: server1.com /  Global zone: No /Parent Zone: (default: -please choose-
object Zone "server1.com" {
    endpoints = [ "server1.com" ]
})

Cluster Zone: server1.com
object Endpoint "server1.com" {
    host = "xx.xx.xx.x1"
    port = "5665"
    log_duration = 1d
}

template Host "server1.com" {
    check_command = "ping4"
    check_interval = 2m
}
Icigna Agent and zone settings:
Cluster zone: default none
Agent: Yes
Establ. con.: yes
Accept conf: yes

(LOCALSERVERDOMAINASMASTER is the server where main icigna is installed)
added Hosts:$zones.d/LOCALSERVERDOMAINASMASTER/hosts.conf
object Host "server1.com." {
    import "server1.com"

    display_name = "server1.com."
    address = "xx.xx.xx.x1"
}

zones.d/LOCALSERVERDOMAINASMASTER/agent_endpoints.conf
object Endpoint "server1.com." {
    host = "xx.xx.xx.x1"
    log_duration = 0s
}

zones.d/LOCALSERVERDOMAINASMASTER/agent_zones.conf
object Zone "server1.com." {
    parent = "LOCALSERVERDOMAINASMASTER"
    endpoints = [ "server1.com." ]

## Environment

* Director version (System - About): master
* Icinga Web 2 version and modules (System - About): 2.5.3
* Icinga 2 version (`icinga2 --version`): version: r2.8.4-1
Application information:
  Installation root: /usr
  Sysconf directory: /etc
  Run directory: /run
  Local state directory: /var
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

System information:
  Platform: Ubuntu
  Platform version: 16.04.4 LTS (Xenial Xerus)
  Kernel: Linux
  Kernel version: 4.4.0-127-generic
  Architecture: x86_64

Build information:
  Compiler: GNU 5.3.1
  Build host: 9c880c2f42f5

PHP 7.0.30-0ubuntu0.16.04.1 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.30-0ubuntu0.16.04.1

**Comment by Thomas-Gelf** [comment]
I'm missing the **disk** Service definition in above details, guess that's the most interesting part. Did you enable "Run on Agent" in the related Service Template?

**Comment by bdevroey** [comment]
I had indeed forgot to enable the check on agend!

After i dit this one server returned dat it had no access to docker container, but thats normal.

And now i'm recieving Remote Icinga instance 'michaelpilarczyk.com.' is not connected to 'hostname'

I first going to check this when i'm home, thanks in advance, i'll update this post later !

object CheckCommand "disk" {
    import "plugin-check-command"
    command = [ PluginDir + "/check_disk" ]
    timeout = 1m
    arguments += {
        "-A" = {
            description = "Explicitly select all paths. This is equivalent to -R .*"
            set_if = "$disk_all$"
        }
        "-C" = {
            description = "Clear thresholds"
            set_if = "$disk_clear$"
        }
        "-E" = {
            description = "For paths or partitions specified with -p, only check for exact paths"
            set_if = "$disk_exact_match$"
        }
        "-I" = {
            description = "Regular expression to ignore selected path/partition (case insensitive) (may be repeated)"
            order = 2
            repeat_key = true
            value = "$disk_ignore_eregi_path$"
        }
        "-K" = {
            description = "Exit with CRITICAL status if less than PERCENT of inode space is free"
            value = "$disk_inode_cfree$"
        }
        "-L" = {
            description = "Only check local filesystems against thresholds. Yet call stat on remote filesystems to test if they are accessible (e.g. to detect Stale NFS Handles)"
            set_if = "$disk_stat_remote_fs$"
        }
        "-M" = {
            description = "Display the mountpoint instead of the partition"
            set_if = "$disk_mountpoint$"
        }
        "-R" = {
            description = "Case insensitive regular expression for path/partition (may be repeated)"
            repeat_key = true
            value = "$disk_eregi_path$"
        }
        "-W" = {
            description = "Exit with WARNING status if less than PERCENT of inode space is free"
            value = "$disk_inode_wfree$"
        }
        "-X" = {
            description = "Ignore all filesystems of indicated type (may be repeated)"
            repeat_key = true
            value = "$disk_exclude_type$"
        }
        "-c" = {
            description = "Exit with CRITICAL status if less than INTEGER units of disk are free or Exit with CRITCAL status if less than PERCENT of disk space is free"
            order = -3
            required = true
            value = "$disk_cfree$"
        }
        "-e" = {
            description = "Display only devices/mountpoints with errors"
            set_if = "$disk_errors_only$"
        }
        "-f" = {
            description = "Don't account root-reserved blocks into freespace in perfdata"
            set_if = "$disk_ignore_reserved$"
        }
        "-g" = {
            description = "Group paths. Thresholds apply to (free-)space of all partitions together"
            value = "$disk_group$"
        }
        "-i" = {
            description = "Regular expression to ignore selected path or partition (may be repeated)"
            order = 2
            repeat_key = true
            value = "$disk_ignore_ereg_path$"
        }
        "-k" = {
            description = "Same as --units kB"
            set_if = "$disk_kilobytes$"
        }
        "-l" = {
            description = " Only check local filesystems"
            set_if = "$disk_local$"
        }
        "-m" = {
            description = "Same as --units MB"
            set_if = "$disk_megabytes$"
        }
        "-p" = {
            description = "Path or partition (may be repeated)"
            order = 1
            repeat_key = true
            value = "$disk_partitions$"
        }
        "-p_old" = {
            order = 1
            value = "$disk_partition$"
        }
        "-r" = {
            description = "Regular expression for path or partition (may be repeated)"
            repeat_key = true
            value = "$disk_ereg_path$"
        }
        "-t" = {
            description = "Seconds before connection times out (default: 10)"
            value = "$disk_timeout$"
        }
        "-u" = {
            description = "Choose bytes, kB, MB, GB, TB (default: MB)"
            value = "$disk_units$"
        }
        "-w" = {
            description = "Exit with WARNING status if less than INTEGER units of disk are free or Exit with WARNING status if less than PERCENT of disk space is free"
            order = -3
            required = true
            value = "$disk_wfree$"
        }
        "-x" = {
            description = "Ignore device (only works if -p unspecified)"
            value = "$disk_partitions_excluded$"
        }
        "-x_old" = "$disk_partition_excluded$"
    }
    vars.disk_cfree = "10%"
    vars.disk_exclude_type = [
        "none",
        "tmpfs",
        "sysfs",
        "proc",
        "configfs",
        "devtmpfs",
        "devfs",
        "mtmfs",
        "tracefs",
        "cgroup",
        "fuse.gvfsd-fuse",
        "fuse.gvfs-fuse-daemon",
        "fdescfs"
    ]
    vars.disk_megabytes = true
    vars.disk_wfree = "20%"
}

**Comment by Thomas-Gelf** [comment]
This is the Command and not the Service ;-) Anyways, glad to hear that Director seems to deploy the configuration as instructed. I'll close this issue so far.
