### ISSUE TITLE
Apply Rules' overridable fields show wrong inherited value

### ISSUE THREAD

**Issue by matthenning** [Icinga/icingaweb2-module-director#1516]
## Expected Behavior
When overriding a service variable in an apply rule it's current value inherited from the service template is displayed.

## Current Behavior
The value inherited from the service template is skipped. Instead the value set in the command definition is displayed.

## Steps to Reproduce (for bugs)
- Create a command an define a value for one of it's fields
- Create a service template using this command and override the value of the field
- Create an apply rule applying the template and try to override the field again.
Expected text in the input would be: `"xyz" (inherited from template-name)`
But it's actually: `"abc" (inherited from command-name)`

## Your Environment
* Director version (System - About): 1.4.3
* Icinga Web 2 version and modules (System - About): 2.5.3
* Icinga 2 version (`icinga2 --version`): 2.8.4
* Operating System and version: Debian 9.4
* Webserver, PHP versions: NGINX, PHP 7.0

**Comment by Thomas-Gelf** [comment]
@matthenning: in my believes this should be fixed in v1.5.0, can you confirm this?

Thanks,
Thomas

**Comment by matthenning** [comment]
I'm out of office so I'll have to get back to you on monday for this one.
