### ISSUE TITLE
Self-referencing of templates not permitted causing object to be broken

### ISSUE THREAD

**Issue by chas0rde** [Icinga/icingaweb2-module-director#1520]
## Expected Behavior

It should not be possible to self-reference an object as import

## Current Behavior

If e.g. self-referencing a servicetemplate A as an import to itself, the director allows the storage of this configuration. If this is done by accident the object cannot be edited afterwards due to the recursion

```
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /usr/share/icingaweb2/modules/director/library/Director/Objects/IcingaObjectImports.php on line 222

Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /usr/share/php/Icinga/Application/Web.php on line 560

```

## Possible Solution

Do not list object itself in import list

## Steps to Reproduce (for bugs)

Create service template
Edit it and add itself as import
Store it
Try to open/edit it

## Your Environment

* Director version (System - About): 1.4.3
* Icinga Web 2 version and modules (System - About): 2.5.3
* Icinga 2 version (`icinga2 --version`):  r2.8.4-1
* Operating System and version:
 Platform: Ubuntu
  Platform version: 16.04.4 LTS (Xenial Xerus)
  Kernel: Linux
  Kernel version: 4.4.0-127-generic
  Architecture: x86_64
* Webserver, PHP versions: apache2 + PHP 7.0.30-0ubuntu0.16.04.1 (cli) ( NTS )

**Comment by Thomas-Gelf** [comment]
We'll fix this in #1631
