### ISSUE TITLE
Self-Service API: Service User is not pushed to PS Module

### ISSUE THREAD

**Issue by LordHepipud** [Icinga/icingaweb2-module-director#1525]
## Expected Behavior

Over the Self-Service API from the Icinga Director you are able to configure a service user for the Icinga 2 Agent. This user should be pushed to the Module with the variable

```
icinga_service_user
```

## Current Behavior

The service user is not added to the API output

## Possible Solution

Add the variable

```
icinga_service_user
```

to the output of the Self-Service API call at

```
/self-service/powershell-parameters?key=<your_key>
```

## Steps to Reproduce (for bugs)

1. Configure the Self-Service API with a different user
2. Run the PowerShell Module of Icinga 2 to use the Self-Service API
3. Check the Output from the Module and the Windows Services

The user has not been modified

## Your Environment

* Director version (System - About): latest master
* Icinga Web 2 version and modules (System - About): 2.5.3
* Icinga 2 version (`icinga2 --version`): 2.8.4
* Operating System and version: Debian Jessie
* Webserver, PHP versions: Apache, PHP5

**Comment by TobiasKneidl** [comment]
Same as #1405 and #1297. Could someone else check this behavior?

**Comment by LordHepipud** [comment]
Cool, I forgot I already opened an issue for this :D

**Comment by Thomas-Gelf** [comment]
We'll track this in #1297
