### ISSUE TITLE
[Feature] Modify: show file information for out-of-director config (like inspect)

### ISSUE THREAD

**Issue by friesoft** [Icinga/icingaweb2-module-director#1531]
## Expected Behavior
Like the inspect feature the modify action link on hosts/services which are not deployed by director should tell you the filename of the host/service.
Also described in the original implementation issue: https://github.com/Icinga/icingaweb2-module-director/issues/689#issuecomment-390982628  

## Current Behavior
Clicking on the modify action link shows e.g. "No such service: ping4" as the service is configured outside of director

## Steps to Reproduce (for bugs)
Use the standalone icinga2 vagrant box, create a new hosttemplate + host (check_command: ping4) in director, deploy. In the monitoring module choose the deployed host, open the ping4 service and click on the "Modify" action link. 
  
## Your Environment
* Director version (System - About): master (c2d54f9de92de8f066625a680c40537aa481e0e7)
* Icinga Web 2 version and modules (System - About): 2.5.3
* Icinga 2 version (`icinga2 --version`): v2.8.4-745-g4eb5b09
* Operating System and version: Cent OS 7.4 (Icinga2 standalone Vagrant Box)

**Comment by Thomas-Gelf** [comment]
![director_modify-external-service](https://user-images.githubusercontent.com/553008/97241625-f03cb680-17f1-11eb-86e6-798e82797ce8.png)
