### ISSUE TITLE
Director want to reencode DB to UTF8 but its already done

### ISSUE THREAD

**Issue by ep4sh** [Icinga/icingaweb2-module-director#1535]
## Expected Behavior
I see in Icinga Director -> Overview (near DB resourse):

> Please change the encoding for the director database to utf8

Also, when i try to add some template or othe item:

> Storing director_activity_log[] failed: SQLSTATE[22021]: Character not in repertoire: 7 ОШИБКА: неверная последовательность байт для кодировки "UTF8": 0xd0 0x32, query was: INSERT INTO director_activity_log (object_name, action_name, object_type, old_properties, new_properties, author, change_time, checksum, parent_checksum) VALUES (?, ?, ?, ?, ?, ?, ?, '\xd02c30f8d52aceb5bd6d622378855d4c2148cf04', '\x') {array ( 'id' => NULL, 'object_name' => '21', 'action_name' => 'create', 'object_type' => 'icinga_host', 'old_properties' => NULL, 'new_properties' => '{"object_name":"21","object_type":"template"}', 'author' => 'icinga2', 'change_time' => '2018-06-19 14:22:50', 'checksum' => '�,0��*ε�mb#x�]L!H�', 'parent_checksum' => NULL, )} (DbObject.php:824)

Also i created my db using doc pages:
`psql -q -c "CREATE DATABASE director WITH ENCODING 'UTF8';"`

## My env
```
* Director version (System - About):
director | master
```

Icinga Web 2 Version    2.5.3
* Icinga 2 version (`icinga2 --version`):

```
icinga2 - The Icinga 2 network monitoring daemon (version: r2.8.4-1)
Copyright (c) 2012-2017 Icinga Development Team (https://www.icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Application information:
  Installation root: /usr
  Sysconf directory: /etc
  Run directory: /run
  Local state directory: /var
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

```
> System information:
>   Platform: Debian GNU/Linux
>   Platform version: 9 (stretch)
>   Kernel: Linux
>   Kernel version: 4.9.0-6-amd64
>   Architecture: x86_64

> Build information:
>   Compiler: GNU 6.3.0
>   Build host: f7d481dc25b9

```
postgres=# \l
Список баз данных
-[ RECORD 1 ]-+----------------------
Имя           | director
Владелец      | postgres
Кодировка     | UTF8
LC_COLLATE    | ru_RU.UTF-8
LC_CTYPE      | ru_RU.UTF-8
Права доступа | =Tc/postgres         +
              | postgres=CTc/postgres+
              | director=CTc/postgres
```

`psql (PostgreSQL) 9.6.9`

Sorry i dont know how to make good report, but it seems like abnormal

**Comment by Thomas-Gelf** [comment]
At first sight it looks wrong that there is `'parent_checksum' => NULL`, and that it is translated to '\x' is also wrong. Probably occurs only on PostgreSQL and only on the very first activity. However it's still unclear to me how this can happen at all, as we're running quite some unit/integration tests on different PostgreSQL versions.

Do you already have activities in your activity log, or does this happen on the very first object creation? Did you kickstart run succeed?

**Comment by ep4sh** [comment]
Thanks for your reply - i thinks i`m master to get troubles :))
No, i havent any activity log. Please, if you could  - look these screenshots:
https://ibb.co/n3P9jd
https://ibb.co/kkH6VJ
Also i triend to remove database and recreate again - the same result.

**Comment by ep4sh** [comment]
Well done, thanks for your help!

**Comment by terra-nova** [comment]
Given that the official PostgreSQL documentation refer to the encoding as "UTF8" and not "utf8", maybe the expectation of lower case identifier in Director should be reconsidered ;-)

https://www.postgresql.org/docs/10/static/multibyte.html

Same for 9.6 and lower versions, too.

**Comment by Thomas-Gelf** [comment]
The linked pull-request has been merged.
