### ISSUE TITLE
Allow for deleting instances of custom variables.

### ISSUE THREAD

**Issue by rojobull** [Icinga/icingaweb2-module-director#1536]
## Expected Behavior
I think Director should allow for deleting of individual custom variables that are assigned to either commands, hosts, services, service sets, notifications or users. 

## Current Behavior
At the moment, the Custom Variables screen shows what variables exist. Clicking on a variable shows where/how many instances exists (commands, hosts, services, etc.). No action is allowed on that screen. The only way to do delete variables is by deleting the associated data filed and then choosing to delete ALL variable instances of that field which is not good if there is widespread use of that field. 

## Possible Solution
In the Custom Variables screen, it would be great to be able to manage each variable listed. After clicking on the variable the next screen should allow for deleting instances instead of just listing them. Ideally, we'd be able to delete single instances at a time, not just all host or services instances, for example.

## Your Environment

* Director version (System - About): master
* Icinga Web 2 version and modules (System - About): 2.5.3
* Icinga 2 version (`icinga2 --version`): 2.5.3
* Operating System and version: CentOS Linux release 7.4.1708
* Webserver, PHP versions: 5.4.16-43.el7_4

**Comment by Thomas-Gelf** [comment]
The part of the UI you're pointing to should allow mass-edit. In addition to this admins should also be allowed to remove (edit?) custom variables even when there is no related field. Should be an admin-only feature, as "normal" users are granted to modified only what your "fields" allow.

**Comment by rojobull** [comment]
That makes sense to me.

**Comment by blessendor** [comment]
Vote for it. I got this problem when cloned (too many hosts to start from scratch) from one client's monitored services, to the new client (they have separate logins/domains to controlling results). So I do not have a choice to remove foreign names from custom vars even I deleted cloned services - I still see custom vars on the host view page.

**Comment by Thomas-Gelf** [comment]
To delete all instances of a specific Custom Variable, please delete the related Data Field from the Data Fields overview - it will ask whether to delete related Custom Variables. In case you no longer have such field: create one, delete it.
