### ISSUE TITLE
[feature request] add data fields to hosts

### ISSUE THREAD

**Issue by R-Sommer** [Icinga/icingaweb2-module-director#1541]
I'd like have the possibility to add a data fields directly to a host object (without adding it to a host template first).

We have some hundreds of option variables for host objects and the are rarely used by default. Once one host need to have one of these variables set, I have to add it to a host template first. From this moment on it is presented in every host object (that is relying on the modified host template) and the list is becoming longer and longer. It would be easier and better arranged to just add this variable to the appropriate host object.

**Comment by Thomas-Gelf** [comment]
I do not consider this being a good idea. If you believe that you know about a real-world scenario that would convince me that it is, please do not hesitate to let me know. Closing this so far.

**Comment by R-Sommer** [comment]
In addition to what I've written: We (Lennart and Markus know us and our requirements best, if you would like to know some background information) develop a default monitoring solution that is deployed at many customer sites. Changes at the "develop-master" needs to be transferred to customer sites. The new basket feature shall do the job and I was successful the very first last week. 

But as far as I've seen during some short tests, it will "overwrite" data fields of a host template. That means if anybody did some "customizing" for any host, the snapshot import would destroy them. Having variables connected to the host object directly could provide a solution where host templates are identical for every customer site and customizing changes are only done with host variables.
