### ISSUE TITLE
No dropdown for "commands" linking

### ISSUE THREAD

**Issue by nessor** [Icinga/icingaweb2-module-director#1542]
## Expected Behavior
I knew from previous versions that when creating a service template you could select the required command from the external commands via a drop-down menu.

## Current Behavior
Currently, this no longer works. It is necessary to copy the name of the command (e.g. hostalive4) from the list and paste it manually into the corresponding field. However, the comparison as to whether the name or the command behind it exists still works reliably.

![img_001](https://user-images.githubusercontent.com/3463261/41740873-b4dd7a0e-7599-11e8-95fa-1339c44fc81a.jpg)

## Steps to Reproduce (for bugs)
Icinga - Director (menu) -> Services -> Service Template -> Add

## Your Environment
* Director version (System - About): master (?)
* Icinga Web 2 version and modules (System - About): 2.5.3
* Icinga 2 version (`icinga2 --version`): version: r2.8.4-1
* Operating System and version: Win10 Pro (client) / Ubuntu 16.04 (Server)
* Webserver, PHP versions: Apache2, PHP 7.0.30-0ubuntu0.16.04.1
* Browser: Chrome Version 67.0.3396.87 & Firefox v60.0.2

If I forgot something, just ask!

**Comment by lazyfrosch** [comment]
This field has been changed to autocompletion, so you can just type characters or `*` to see all.

Does that help?

**Comment by nessor** [comment]
Yeah, that helps. But why does the drop-down appear when I type *, but not when I start typing "http" for example?

**Comment by Thomas-Gelf** [comment]
It absolutely should, at least that's what it does for me

**Comment by nessor** [comment]
Sorry for my late response...
I have "found" my problem. Something went wrong during installation. Machine once completely reinstalled and it works wonderfully!
