### ISSUE TITLE
`director kickstart run` runs indefinitely

### ISSUE THREAD

**Issue by bastidest** [Icinga/icingaweb2-module-director#1543]
## Expected Behavior
Running 'icingacli director kickstart run' should kickstart the icinga configuration an exit successfully.

## Current Behavior
The command runs indefinitely and does not exit.

## Possible Solution
Uncomment this line to ensure that each curl request closes it's connection. Git blame shows this was commented out because of streams. A possible fix would be to close the connection only if the request is not a stream.

https://github.com/Icinga/icingaweb2-module-director/blob/3e466028022966f0cedc0a8e4a8f443e101f3e76/library/Director/Core/RestApiClient.php#L136

### Working docker image
1. Clone this git repo: `git clone https://github.com/bastidest/icinga2`
1. Checkout specific commit: `git checkout 14593e4e80531`
1. Create a file 'secrets_sql.env' with content `MYSQL_ROOT_PASSWORD=test`
1. run `docker-compose up --build`
1. Wait for output `==> Deploying new configuration, restarting Icinga2`

### Broken docker image (without closing http connection)
1. Open 'Dockerfile' and replace the url `https://github.com/bastidest/icingaweb2-module-director/archive/${GITREF_DIRECTOR}.tar.gz` with `https://github.com/Icinga/icingaweb2-module-director/archive/${GITREF_DIRECTOR}.tar.gz`
1. run `docker-compose up --build`
1. Output does not appear `==> Deploying new configuration, restarting Icinga2`

## Your Environment

* Director version (System - About): master
* Icinga Web 2 version and modules (System - About): 2.5.3
* Icinga 2 version (`icinga2 --version`): v2.8.4-791-gba680dc82
* Operating System and version: 4.9.0-6-amd64 #1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07)
* Webserver, PHP versions: PHP 7.0.27-0+deb9u1 on Apache2

**Comment by nilmerg** [comment]
Can confirm the issue and the proposed change solving it.

# My Environment
* Director version (System - About): master
* Icinga Web 2 version and modules (System - About): master
* Icinga 2 version (`icinga2 --version`): v2.8.4-809-gc89f92e
* Operating System and version: CentOS Linux release 7.4.1708 (Core)
* Webserver, PHP versions: Apache/2.4.6, PHP 7.1.8

**Comment by lazyfrosch** [comment]
This in an external issue in Icinga 2 with handling HTTP connections, only occuring in Icinga 2.9.0-pre

Please see:
https://github.com/Icinga/icinga2/issues/6428

**Comment by mcktr** [comment]
The issue in Icinga 2 with handling the connection is now solved.

IMHO I think the connection should be closed after the kickstart ran. Icinga 2 will log the following message when the kickstart runs, which might make someone think that a timeout is hit (which in fact happens) and something was not successfull.

```
[2018-07-09 21:30:47 +0200] information/HttpServerConnection: No messages for Http connection have been received in the last 10 seconds.
```

**Comment by dnsmichi** [comment]
Seems that icinga/icinga2#6635 is directly connected here, this all comes with corking the streams.
