### ISSUE TITLE
SSL error on import

### ISSUE THREAD

**Issue by kain64** [Icinga/icingaweb2-module-director#1551]
scenario:
vsphere with self signed certificate
click on import "Trigger Import Run" or "check for modifications"
error:
This Import Source failed when last checked at 2018-06-27 17:28:38: CURL ERROR: Peer's Certificate issuer is not recognized.

maybe I can temporary disable this check?

**Comment by Thomas-Gelf** [comment]
Well, it should look like this:

![config](https://raw.githubusercontent.com/Icinga/icingaweb2-module-vsphere/master/doc/screenshot/03_import-source/035_configure-connection.png)

I'd try to disable "verify peer" :)

**Comment by kain64** [comment]
thank you!!! :))
