### ISSUE TITLE
Migration php 7.2 for Ubuntu 18.04

### ISSUE THREAD

**Issue by InkUisitor** [Icinga/icingaweb2-module-director#1553]
## Expected Behavior
Everything works correctly ... :'(
When I updated my Ubuntu 17.10 to 18.04, php has moved from 7.1 to 7.2. I tried fixes for IcingaWeb (according to the commit that have been done on the icingaweb2 git) but Director has some problems too with the migration.

## Current Behavior
When you go to the page Activity log or Deployments, an error tells me that 
count(): Parameter must be an array or an object that implements Countable (QueryBasedTable.php:113)

## Possible Solution
I installed my Icinga on a machine and not a VM... You're my only solution now !!! :'(

## Your Environment
* Director version (System - About): 1.4.3
* Icinga Web 2 version and modules (System - About): Web 2.5.3 / Monitoring 2.5.3
* Icinga 2 version (`icinga2 --version`): 2.8.4-806-gc7e61748d
* Operating System and version: Ubuntu 18.04
* Webserver, PHP versions: php 7.2

**Comment by InkUisitor** [comment]
0 [internal function]: Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(2, 'count(): Parame...', '/usr/share/icin...', 113, Array)
1 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Web/Table/QueryBasedTable.php(113): count(NULL)
2 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Html/BaseElement.php(133): dipl\Web\Table\QueryBasedTable->renderContent()
3 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Html/Html.php(171): dipl\Html\BaseElement->render()
4 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Html/BaseElement.php(105): dipl\Html\Html->render()
5 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Html/BaseElement.php(133): dipl\Html\BaseElement->renderContent()
6 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Html/Html.php(259): dipl\Html\BaseElement->render()
7 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Zf1/SimpleViewRenderer.php(47): dipl\Html\Html->__toString()
8 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Zf1/SimpleViewRenderer.php(66): dipl\Zf1\SimpleViewRenderer->render()
9 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/HelperBroker.php(272): dipl\Zf1\SimpleViewRenderer->postDispatch()
10 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(518): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
11 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('deploymentsActi...')
12 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
13 /usr/share/php/Icinga/Application/Web.php(409): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
14 /usr/share/php/Icinga/Application/webrouter.php(104): Icinga\Application\Web->dispatch()
15 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...')
16 {main}

**Comment by Thomas-Gelf** [comment]
This has been fixed with #1458. You can either switch to the current master, pick just the fix from the linked pull request or wait for v1.5.0.

Cheers,
Thomas

**Comment by InkUisitor** [comment]
Thanks Thomas,
I fixed the file for the moment like your commit. I will switch on the master another time I think ! :)
