### ISSUE TITLE
Binary blobs are not properly transmitted to MySQL

### ISSUE THREAD

**Issue by nilmerg** [Icinga/icingaweb2-module-director#1556]
Given a `rowset_checksum` `�*���O��+d�C\"�I�` results in an invalid query string produced by Zend_Db_Statement:190 and ultimately in a segmentation fault caused by Zend_Db_Statement:196.

The invalid query is caused by the backslash in the checksum whereas the segmentation fault is a result of the invalid query. If the query is valid the segmentation fault does not occur.

So the actual issue is that the Director does not properly transmit binary blobs to MySQL.

## Expected Behavior
The director should properly escape binary blobs when querying the database.

## Current Behavior
In case of MySQL the director does not escape binary blobs at all.

## Possible Solution
Escape binary blobs or transmit them as part of prepared statements.

## Steps to Reproduce (for bugs)
Just have a row with the above `rowset_checksum` and run a syncrule check.

## Your Environment
* Director version (System - About): master@35815e0d
* Icinga Web 2 version and modules (System - About): 2.5.3 (ca7e886b820f0145999fdf7377f5c4132301eada)

---
ref/NC/565488

**Comment by lazyfrosch** [comment]
I had a look earlier on the issue, Zend really seems to struggle with handling escapes in non-prepared statements.

@Thomas-Gelf Do you think this explicit checksum handling can cause issues elsewhere?

**Comment by Thomas-Gelf** [comment]
@nilmerg: thanks a lot for tracking this down! Guess we all agree that this should never happen, and I'm strictly against "fixing" it this way. @lazyfrosch: we rely on binary data in multiple places, having problems there is absolutely unacceptable.

This is what ZF states on/before line 190:

```php
$escapeChar = preg_quote($escapeChar);
// this segfaults only after 65,000 characters instead of 9,000
$sql = preg_replace("/$q([^$q{$escapeChar}]*|($qe)*)*$q/s", '', $sql);
```

This makes a good candidate for the best code comment ever :laughing: The code sample internally shipped by @nilmerg works fine for me on my local system, is this a bug in the involved libprce? @nilmerg: I'll contact you directly in an instance...

**Comment by nilmerg** [comment]
@lazyfrosch The *prepared* solution:

ImportRun:88
```php
)->where('rsr.rowset_checksum = :checksum')->bind(['checksum' => $binchecksum])->order('r.object_name');
```

**Comment by lazyfrosch** [comment]
I'll review where we need to change checksums to use prepared statements.

This will avoid binary content inside the query text.

**Comment by Mikesch-mp** [comment]
I had a problem like this with director importing configuration files via fileshipper. One of the files had an umlaut in an comment, this lead to an sql error when trying to render or deploy configuration.

**Comment by Thomas-Gelf** [comment]
@lazyfrosch, @nilmerg: thanks! @Mikesch-mp: your problem should be completely unrelated, please open a dedicated issue. Files MUST be UTF8-encoded, fileshipper should refuse invalid files.

**Comment by Thomas-Gelf** [comment]
Unfortunately the _prepared_ solution broke PostgreSQL. I took the example provided by @nilmerg for MySQL and kept it as is for PostgreSQL - there is no binary data after quoteBinary for PG.
