### ISSUE TITLE
Error/bug importing

### ISSUE THREAD

**Issue by luisvegeta** [Icinga/icingaweb2-module-director#1558]
## Expected Behavior
Import from icinga2 text files

* Director version - latest master
* Icinga Web 2 version: 2.5.3
* Icinga 2 version - r2.8.4-1
* Operating System and version: Centos 7
* Webserver, PHP versions: NginX, php-fpm, php 7.1

## Current Behavior
When importing, only creates 001-director-basics.conf with error/code:

```
const DirectorStageDir = dirname(dirname(current_filename))

globals.directorWarnedOnceForThresholds = false;
globals.directorWarnOnceForThresholds = function() {
    if (globals.directorWarnedOnceForThresholds == false) {
        globals.directorWarnedOnceForThresholds = true
        log(LogWarning, "config", "Director: flapping_threshold_high/low is not supported in this Icinga 2 version!")
    }
}

if (! globals["DirectorOverrideTemplate"]) {
  const DirectorOverrideVars = "_override_servicevars"
  const DirectorOverrideTemplate = "host var overrides (Director)"

  template Service DirectorOverrideTemplate ignore_on_error {
    /**
     * Seems that host is missing when used in a service object, works fine for
     * apply rules
     */
    if (! host) {
      var host = get_host(host_name)
    }

    if (vars) {
      vars += host.vars[DirectorOverrideVars][name]
    } else {
      vars = host.vars[DirectorOverrideVars][name]
    }
  }
}

**Comment by lazyfrosch** [comment]
I suppose you installed Director and kickstarted the configuration with Icinga 2.

Now Director just imports very basic configuration, in terms of knowledge it needs for understanding and using them.

If you actually want to manage Host or Services you have to create them or import them explicitly into director.

Director does not manage your existing Icinga 2 configuration.

I agree documentation must be improved, but that's another topic.

Please also check your user forums: https://www.icinga.com/support/ (scroll down to community support)

**Comment by luisvegeta** [comment]
Hi, @lazyfrosch and thank you for the reply.

I don't want Director to manage my existing Icinga 2 configuration, I just want to import it. And at configuration kickstart, as far as i know, it should create  001-director-basics.conf with some configuration, not a piece of code in it.

And that's just it, even importing a very basic configuration it doesn't work.

Isn't this an error or bug worth looking in to it?

**Comment by lazyfrosch** [comment]
Unfortunatly kickstart can't do this.

You would have to create your own Import/Sync based on SQL or CoreApi.

But keep in mind that these imports are very basic and won't help you with any templates.

**Comment by luisvegeta** [comment]
Ok, thanks.

I'll just use icinga2 as I always did, and give up on director.
