### ISSUE TITLE
[dev.icinga.com #11426] choose external object to object

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#156]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11426

**Created by essener61 on 2016-03-21 12:17:30 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-03-21 12:36:38 +00:00 (in Redmine)_

---

an imported by cora - api command is to be changed . This is the icinga - director no longer possible , since it is an external object . As things stand, the command has to be completely redesigned . Is it not make more sense to allow users with appropriate warning to provide the external object to an object with corresponding deploy opportunities ?

**Comment by Thomas-Gelf** [comment]
While importing external objects works since quite some time, with v1.4.0 it is now also possible to clone them - so this feature request should be fulfilled.
