### ISSUE TITLE
Host -> Services -> Service Set -> click on title deletes set

### ISSUE THREAD

**Issue by lazyfrosch** [Icinga/icingaweb2-module-director#1560]
When clicking the group title of a Service Set it is immediate remove without prompt.

This should only happen when clicking on a remove link - with confirmation at best.

A click on the title should lead to the service set details.

**Comment by camskkz** [comment]
I will also add on this issue that if, after removing by mistake a service set this way, you try to restore former object in the activity log, the service set inheritence will call itself.
This is what #1465 describes.

**Comment by Thomas-Gelf** [comment]
Link will be transformed in a link-like form.
