### ISSUE TITLE
Adding more than one DbObject with priority fails

### ISSUE THREAD

**Issue by nbuchwitz** [Icinga/icingaweb2-module-director#1567]
## Expected Behavior
Adding more than one DbObject like an ImportPropertyModifier is possible.

## Current Behavior
It is not. It fails with the following error:
```
Storing import_row_modifier[] failed: SQLSTATE[23505]: Unique violation: 7 ERROR: duplicate key value violates unique constraint "import_row_modifier_prio" DETAIL: Key (source_id, priority)=(3, 1) already exists., query was: INSERT INTO import_row_modifier (source_id, property_name, provider_class, target_property, priority, description) VALUES (?, ?, ?, ?, ?, ?) {array ( 'id' => NULL, 'source_id' => '3', 'property_name' => 'hrs_geolocation', 'provider_class' => 'Icinga\\Module\\Director\\PropertyModifier\\PropertyModifierLowercase', 'target_property' => NULL, 'priority' => 1, 'description' => NULL, )} (DbObject.php:824)
```
After some debugging it turns out, that the default priority value for a freshly created PropertyModifier is 1, which prevends the ``setNextPriority`` method in ``PriorityColumn.php`` to update to the calculated value. 

## Possible Solution
Initialize the default value with ``null`` as expected by the ``setNextPriority`` method or change line 69 of ``ImportRowModifier.php`` to the following:

```
if (! $this->hasBeenLoadedFromDb() && $this->get('priority') === 1) { 
```

## Steps to Reproduce (for bugs)
Add more than one PropertyModifier to an importsource

## Your Environment

* Director version (System - About): GIT master
* Icinga Web 2 version and modules (System - About): 2.5.3
* Icinga 2 version (`icinga2 --version`): 2.8.4
* Operating System and version: CentOS 7.4
* Webserver, PHP versions: httpd, rh-php71

**Comment by Thomas-Gelf** [comment]
Thanks!
