### ISSUE TITLE
"doppelter Schlüsselwert verletzt Unique-Constraint"

### ISSUE THREAD

**Issue by viper539** [Icinga/icingaweb2-module-director#1568]
Hello,

i try to add a additional property modifier and get this error:
`Storing import_row_modifier[] failed: SQLSTATE[23505]: Unique violation: 7 FEHLER: doppelter Schlüsselwert verletzt Unique-Constraint »import_row_modifier_prio« DETAIL: Schlüssel »(source_id, priority)=(3, 1)« existiert bereits., query was: INSERT INTO import_row_modifier (source_id, property_name, provider_class, target_property, priority, description) VALUES (?, ?, ?, ?, ?, ?) {array ( 'id' => NULL, 'source_id' => '3', 'property_name' => 'name', 'provider_class' => 'Icinga\\Module\\Director\\PropertyModifier\\PropertyModifierLowercase', 'target_property' => 'object_name', 'priority' => 1, 'description' => NULL, )} (DbObject.php:824)`

I tried to remove the existing modifier and create the modifiers new, but it would't help.

Maybe it's still the issue with PostgreSQL in 
[https://github.com/Icinga/icingaweb2-module-director/issues/130](url)
which is also from me, but closed.

## Your Environment

* Director version (System - About): master from GitHub 25.06.2018
* Icinga Web 2 version and modules (System - About): 2.4.1
* Icinga 2 version (`icinga2 --version`): r2.6.0-1
* Operating System and version:
      Platform: Debian GNU/Linux
      Platform version: 9 (stretch)
      Kernel: Linux
      Kernel version: 4.9.0-6-amd64
      Architecture: x86_64
* Webserver: Apache2 2.4.25-3+deb9u4
* PHP: 7.0.30-0+deb9u1

**Comment by Thomas-Gelf** [comment]
duplicates  #1567

**Comment by Thomas-Gelf** [comment]
Thanks for reporting this!
