### ISSUE TITLE
How can I change a configuration file

### ISSUE THREAD

**Issue by userrst** [Icinga/icingaweb2-module-director#1569]
Good day

I have configured Icinga2 with "Icinga Director" and would like to modify a configuration file.

How can I change a configuration file like hosts.conf or timeperiods.conf without overwriting my changes by "Icinga Director"?

Thank you for your help

**Comment by Thomas-Gelf** [comment]
Director is unable to do so, you might want to check the [Getting started](https://github.com/Icinga/icingaweb2-module-director/blob/master/doc/04-Getting-started.md) part of our documentation.
