### ISSUE TITLE
[CLI] --json parameter can work with files

### ISSUE THREAD

**Issue by SimonHoenscheid** [Icinga/icingaweb2-module-director#1570]
## Expected Behavior
It would be nice if the --json parameter on the cli could write or read json files

## Current Behavior
files can be written by redirecting the output. reading is not possible.

## Possible Solution
implement feature

**Comment by Thomas-Gelf** [comment]
You mean something like `--json-from-file <filename>` or `cat <filename> | ... --json-from-file -` instead of `--json $(cat <filename>)`?

**Comment by SimonHoenscheid** [comment]
yes
