### ISSUE TITLE
Integrity constraint violation: icinga_hostgroup_host_resolved

### ISSUE THREAD

**Issue by sinky** [Icinga/icingaweb2-module-director#1574]
After update from r2.8.4-1 to 2.9, all previous defined assign filters on HostGroups are no longer visible (but active) and an error message appears on saving assign filters on new and existing HostGroups.

## Expected Behavior
No error message should appear and all previous defined assign filters should be there.

## Current Behavior
Error message appears on save:
`SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '15-3' for key 'PRIMARY', query was: INSERT INTO icinga_hostgroup_host_resolved (hostgroup_id, host_id) VALUES (?, ?) (Pdo.php:225)`

## Possible Solution
NA

## Steps to Reproduce (for bugs)
Create/edit a HostGroup and set/edit a assign filter

## Your Environment
* Director version (System - About): master
* Icinga Web 2 version and modules (System - About): 2.5.3
* Icinga 2 version (`icinga2 --version`): r2.9.0-1
* Operating System and version: Ubuntu 18.04 LTS
* Webserver, PHP versions: nginx/1.14.0, php7.2.7-1

**Comment by schumischumi** [comment]
same here. fresh install on raspian/debian, but older versions from debian repo:
- Director version (System - About): master
- Icinga Web 2 version and modules (System - About): **2.4.1**
- Icinga 2 version (icinga2 --version): **r2.6.0-1**
- Operating System and version:  Raspbian GNU/Linux 9 Kernel 4.14.52+ armv6l
- Webserver, PHP versions: apache/**2.4.25**, **php v7.0.30-0+deb9u1,**

**Comment by lazyfrosch** [comment]
This shouldn't be related to Icinga 2.9

Looks like something in the Hostgroup to Host resolver is broken:

```
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '2-2' for key 'PRIMARY', query was: INSERT INTO icinga_hostgroup_host_resolved (hostgroup_id, host_id) VALUES (?, ?) (Pdo.php:225)
```

**Comment by lazyfrosch** [comment]
It happens when resolving assign where from `Hostgroups`, e.g. when changing a hostgroup

**Comment by lazyfrosch** [comment]
This was introduced by c6de458235ccc902551ca7739ac6346919eeb4f2

We now add groups inherited from a parent template.

But this literally breaks when updating only for one hostgroup, the program does add assigned groups even when not updating that group.

**Comment by lazyfrosch** [comment]
@sinky @quentinsch @schumischumi Please test the patch in PR #1618

**Comment by schumischumi** [comment]
Hi,
the patch didnt work for me.
what i did:
edited the file /usr/share/icingaweb2/modules/director/library/Director/Objects/GroupMembershipResolver.php

```
foreach ($groupNames as $name) {
                $groupId = $this->getGroupId($name);
                //if (! array_key_exists($groupId, $mappings)) {

                //    $mappings[$groupId] = [];
                //}
                //$mappings[$groupId][$id] = $id;
                // only update when group is in groups to update
                if (array_key_exists($groupId, $groups)) {
                    if (! array_key_exists($groupId, $mappings)) {
                        $mappings[$groupId] = [];
                    }
                     $mappings[$groupId][$id] = $id;
                }
            }
```

rebooted the raspberry.
started kickstarter via cli

`pi@rpi1:/usr/share/icingaweb2/modules/director/library/Director/Objects $ sudo icingacli director kickstart run
ERROR: RuntimeException in /usr/share/icingaweb2/modules/director/library/Director/Data/Db/DbObject.php:824 with message: Storing icinga_command_argument[] failed: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '4--c' for key 'unique_idx', query was: INSERT INTO icinga_command_argument (command_id, argument_name, argument_value, argument_format, key_string, description, skip_key, set_if, sort_order, repeat_key, set_if_format, required) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) {array (
  'id' => NULL,
  'command_id' => '4',
  'argument_name' => '-c',
  'argument_value' => '$breeze_critical$',
  'argument_format' => 'string',
  'key_string' => NULL,
  'description' => 'Percentage strength below which a CRITICAL status will result',
  'skip_key' => NULL,
  'set_if' => NULL,
  'sort_order' => NULL,
  'repeat_key' => NULL,
  'set_if_format' => NULL,
  'required' => 'y',
)}
`

or gui

`Storing icinga_command_argument[] failed: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '4--c' for key 'unique_idx', query was: INSERT INTO icinga_command_argument (command_id, argument_name, argument_value, argument_format, key_string, description, skip_key, set_if, sort_order, repeat_key, set_if_format, required) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) {array ( 'id' => NULL, 'command_id' => '4', 'argument_name' => '-c', 'argument_value' => '$breeze_critical$', 'argument_format' => 'string', 'key_string' => NULL, 'description' => 'Percentage strength below which a CRITICAL status will result', 'skip_key' => NULL, 'set_if' => NULL, 'sort_order' => NULL, 'repeat_key' => NULL, 'set_if_format' => NULL, 'required' => 'y', )} (DbObject.php:824)`
