### ISSUE TITLE
Deployment failed with "Failed to load icinga_timeperiod "" (IcingaObject.php:329)"

### ISSUE THREAD

**Issue by TobiasKneidl** [Icinga/icingaweb2-module-director#1578]
## Current Behavior
I've deleted two old time zones and the deployment afterwards failed with:
Failed to load icinga_timeperiod "" (IcingaObject.php:329)

## Your Environment

* Director version (System - About): master
* Icinga Web 2 version and modules (System - About): 2.6
* Icinga 2 version (`icinga2 --version`): r2.9.0-1
* Operating System and version: Ubuntu 16.04
psql (PostgreSQL) 9.5.13

**Comment by TobiasKneidl** [comment]
This also happens with Director v1.5.1

**Comment by lazyfrosch** [comment]
This sounds like a broken relation in the database.

Although this should be prohibited, when you want to delete a timeperiod, SQL should block when it is used.

* Do you have any context? Stacktrace?
* An idea which object might be affected?

From a short look in the pgsql schema, it seems like icinga_user is missing a foreign key constraint for timeperiod.

Can you confirm this? Compare `icinga_user.period_id` to your current `icinga_timeperiod`

We need to confirm if MySQL is affected too.

**Comment by TobiasKneidl** [comment]
Thank You @lazyfrosch !

Yes in `icinga_user.period_id` was an timperiod referenced, which was deleted already in `icinga_timeperiod.`
After deleting the value, Deployment works!

**Comment by lazyfrosch** [comment]
Opened a PR to fix the schema and migrate properly see #1627

**Comment by Thomas-Gelf** [comment]
Had to revert the fix, sorry for that. Suggested a simpler query in the discussion to the initial pull request.
