### ISSUE TITLE
Overriding custom valriables does not work reliably

### ISSUE THREAD

**Issue by terra-nova** [Icinga/icingaweb2-module-director#1580]
## Expected Behavior

To add to the already open issues regarding overriding of custom variables, we have some issues with doing so on services associated with hosts via service sets. Merge and cross-reference as you see fit ;-)

In short, overriding of custom variables does not work reliably for us since we have upgraded our Icinga2 instances to 2.9.1.

Consider this:

We have a host with multiple service sets.

![ss0](https://user-images.githubusercontent.com/16338849/43311990-4997adf0-918c-11e8-8874-e1dd5063713a.PNG)

We set a custom variable `scheduled_downtimes` on one service each from two different service sets.

The configuration preview looks good, too:

```
object Host "xxx" {
    import "Host-IBM Power i"

    display_name = "xxx"
    address = "xxx"
    vars["_override_servicevars"] += {
        CPU = {
            scheduled_downtimes = [ "yyy" ]
        }
        "Job BUS400/CHKTGTP" = {
            scheduled_downtimes = [ "yyy ]
        }
    }
}
```

But the custom variable is only set for one service, and not the other.

`icinga2 object list` output for service 1:

```
  ...
  * vars
    % = modified in '/var/lib/icinga2/api/packages/director/3ddb79db-679f-4f8c-a1c4-7516825cb5a2/zones.d/director-global/001-director-basics.conf', lines 26:7-26:51
    ...
    * scheduled_downtimes = [ "yyy" ]
    * threshold_critical = "200%"
      % = modified in '/var/lib/icinga2/api/packages/director/3ddb79db-679f-4f8c-a1c4-7516825cb5a2/zones.d/director-global/service_templates.conf', lines 49:5-49:35
    * threshold_warning = "150%"
      % = modified in '/var/lib/icinga2/api/packages/director/3ddb79db-679f-4f8c-a1c4-7516825cb5a2/zo
```

service 2:

```
  * vars
    % = modified in '/var/lib/icinga2/api/packages/director/3ddb79db-679f-4f8c-a1c4-7516825cb5a2/zones.d/director-global/001-director-basics.conf', lines 26:7-26:51
```

Note the missing `scheduled_downtimes' var for service2.

I tried cloning the host object along with all services and service sets (as was suggested in issue #1579), but that did not help.

I created a new host object from scratch and assigned the same service sets to it... and lo and behold, the custom variables appeared on both services. However I now have close to zero confidence in the mechanism as a whole, since I have no clue why it works in one case and doesn't in another.

## Current Behavior

Overriding variables works sometimes, and other times, it doesn't.

## Your Environment

* Director version (System - About): 35815e0dad9bf7370a68f5128d17506b9a9530cb
* Icinga Web 2 version and modules (System - About): 2.6.0
* Icinga 2 version (`icinga2 --version`): 2.9.1
* Operating System and version: CentOS 7.5 x86_64
* Webserver, PHP versions: Apache 2.4, PHP 7.1 from SCL

**Comment by quentinsch** [comment]
Yeah, I have the same with. Reported it in issue: 1579

**Comment by lazyfrosch** [comment]
Thanks for your issue, for now let's move discussion to #1579
