### ISSUE TITLE
POST on existing service object creates duplicate

### ISSUE THREAD

**Issue by nbuchwitz** [Icinga/icingaweb2-module-director#1586]
I create some services via the API with something like the following:

```
% ./director-curl POST 'director/service' '{ "imports": [ "SPS Counter" ], "vars": { "somekey": "value" }, "object_name": "sps-sensor-123", "object_type": "object", "host": "hrs-0000" }'                                                        :) 10:42:04
HTTP/1.1 201 Created
Date: Fri, 03 Aug 2018 08:42:23 GMT
Server: Apache/2.4.6 (CentOS)
X-Powered-By: PHP/7.1.8
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Set-Cookie: Icingaweb2=g2aacvgg5dd9il18t1qgp4dr41; path=/icingaweb2/; HttpOnly
Transfer-Encoding: chunked
Content-Type: application/json

{
    "host": "hrs-0000",
    "imports": [
        "SPS Counter"
    ],
    "object_name": "sps-sensor-123",
    "object_type": "object",
    "vars": {
        "somekey": "value"
    }
}
```

When I rerun this command I would expect something like ``304 Not modified``, but get the same result as above (``201 Created``) and a second service object with the same name is created.

As it is also possible to create a identical service with the same host, I think it's not only an API specific issue. Shouldn't it be impossible to create identical services for a host or have I overseen something? In my opinion the combination of the host and service name is something like a primary key?

**Comment by Thomas-Gelf** [comment]
Thanks for reporting this, has been fixed with v1.5.0.
