### ISSUE TITLE
Change Cluster Zones In ServiceSet

### ISSUE THREAD

**Issue by stevie-sy** [Icinga/icingaweb2-module-director#1589]
We are using a Icinga HA Configuration with 2 Master-Nodes, 2 satellite in the network zone and 2 satellite in the server zone. 
We do our full configuration with the director. We also use service sets to configure services. We saw that every service set is saved in the file /var/lib/icinga2/api/zones/director-global/director/servicesets.conf. So that means that every node gets the apply rules from the service set. So when a set is for example only for servers also the network nodes gets this rules. And of course and vice versa. 

The result is that one node can't find the host which is in the other Zone. And if you make a icinga2 daemon -C then you will get a lot of warnings and of course you can find that also in the icinga2 log file after deployment. And the last point let the log file growing for nothing. 

A solution could be to set a zone at the service set like at other config sites like dependencys, templates, checks etc. Because if I changed the Zone in the templates (service or command) nothing changed in this case. 

## Your Environment

* Director version (System - About): Git Master 71ad855
* Icinga Web 2 version and modules (System - About): 2.6.1
* Icinga 2 version (`icinga2 --version`):  r2.9.1-1
* Operating System and version: CentOS 7
* Webserver, PHP versions:  Apache 2.4.6-80.el7, rh-php 7.1.8-1.el7

**Comment by phil-or** [comment]
+1

**Comment by dbu1986** [comment]
+1

**Comment by ohdearaugustin** [comment]
+1

**Comment by xam-stephan** [comment]
+1

**Comment by tbauriedel** [comment]
ref/NC/761567

**Comment by Wintermute2k6** [comment]
ref/NC/767217
