### ISSUE TITLE
Apply rules for host templates

### ISSUE THREAD

**Issue by sklaes** [Icinga/icingaweb2-module-director#1609]
I have several different import sources (Active Directories and vCenters). Using the sync rules I assign the host templates for environment specific properties, e.g. "command_endpoint".

In every environment there are Windows, Linux,... Systems that require appropriate checks (RDP, SSH,...), which can be combined in host templates.

## Current Behavior
So far it is only possible to create sync rules for every possible operating system, for every import source. This results in a number of "Operating System "x "Import Source" rules necessary to assign the necessary host templates.

## Expected Behavior

It would be very good if there were also apply rules for host templates:

```
template Host "generic-host-windows" {
    check_command ="hostalive
    [...]
    assign where match("Windows*", host.vars.os_type)
}
```
or alternatively the same possibilities as in the "Sync properties" to define independently of the import source - e.g. as a job

## Possible Solution
Implementation

## Steps to Reproduce (for bugs)
Its not a bug

## Your Environment

* Director version (System - About):  43a68c78ad81d28efecbdaa63af2d828712ba37f
* Icinga Web 2 version and modules (System - About): 2.5.3
* Icinga 2 version (`icinga2 --version`):  r2.8.4-1
* Operating System and version: CentOS 7
* Webserver, PHP versions: apache httpd 2.4.6, PHP 7

**Comment by lazyfrosch** [comment]
Icinga 2 does not allow a dynamic assignment of templates.

Templates are used to set explicit defaults of an object and are a fixed part of the config language syntax.

I see no way and no reason to implement this.

You can set import within the sync rule to assign hosts, even based on a filter that decides the property based on vars.
