### ISSUE TITLE
[dev.icinga.com #11451] Hosts and services not getting imported

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#161]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11451

**Created by pef on 2016-03-25 15:43:58 +00:00**

Assignee: _tgelf_
Status: _Resolved_  (closed on _2016-09-08 23:59:23 +00:00_)
Target Version: _1.2.0_
Last Update: _2016-10-31 19:52:58 +00:00 (in Redmine)_

---

With my configuration, Icinga Director doesn't import hosts, hostgroups, services, notification and users. Commands are getting imported.

I added an import rule for hosts with a source CoreAPI and index of object\_name looking for hosts. Once I have a look at the preview, I get the following expection:

    #0 /usr/share/icingaweb2/modules/director/library/Director/Objects/IcingaObjectGroups.php(154): Icinga\Module\Director\Objects\IcingaObjectGroups->add('sslvpn', 'fail')
    #1 /usr/share/icingaweb2/modules/director/library/Director/Objects/IcingaObjectGroups.php(120): Icinga\Module\Director\Objects\IcingaObjectGroups->add(Array)
    #2 /usr/share/icingaweb2/modules/director/library/Director/Objects/IcingaObject.php(674): Icinga\Module\Director\Objects\IcingaObjectGroups->set(Array)
    #3 /usr/share/icingaweb2/modules/director/library/Director/Data/Db/DbObject.php(301): Icinga\Module\Director\Objects\IcingaObject->setGroups(Array)
    #4 /usr/share/icingaweb2/modules/director/library/Director/Objects/IcingaObject.php(414): Icinga\Module\Director\Data\Db\DbObject->set('groups', Array)
    #5 /usr/share/icingaweb2/modules/director/library/Director/Data/Db/DbObject.php(389): Icinga\Module\Director\Objects\IcingaObject->set('groups', Array)
    #6 /usr/share/icingaweb2/modules/director/library/Director/Data/Db/DbObject.php(926): Icinga\Module\Director\Data\Db\DbObject->setProperties(Array)
    #7 /usr/share/icingaweb2/modules/director/library/Director/Objects/IcingaObject.php(1396): Icinga\Module\Director\Data\Db\DbObject::create(Array, Object(Icinga\Module\Director\Db))
    #8 /usr/share/icingaweb2/modules/director/library/Director/Core/CoreApi.php(303): Icinga\Module\Director\Objects\IcingaObject::createByType('Host', Array, Object(Icinga\Module\Director\Db))
    #9 /usr/share/icingaweb2/modules/director/library/Director/Core/CoreApi.php(393): Icinga\Module\Director\Core\CoreApi->getDirectorObjects('Host', 'Host', 'hosts', Array)
    #10 /usr/share/icingaweb2/modules/director/library/Director/Import/ImportSourceCoreApi.php(24): Icinga\Module\Director\Core\CoreApi->getHostObjects()
    #11 /usr/share/icingaweb2/modules/director/application/tables/ImportsourceHookTable.php(115): Icinga\Module\Director\Import\ImportSourceCoreApi->fetchData()
    #12 /usr/share/icingaweb2/modules/director/application/tables/ImportsourceHookTable.php(64): Icinga\Module\Director\Tables\ImportsourceHookTable->getBaseQuery()
    #13 /usr/share/icingaweb2/modules/director/library/Director/Web/Table/QuickTable.php(253): Icinga\Module\Director\Tables\ImportsourceHookTable->fetchData()
    #14 zend.view:///usr/share/icingaweb2/modules/director/application/views/scripts/list/table.phtml(13): Icinga\Module\Director\Web\Table\QuickTable->render()
    #15 /usr/share/php/Icinga/Web/View.php(204): include('zend.view:///us...')
    #16 /usr/share/php/Zend/View/Abstract.php(888): Icinga\Web\View->_run('/usr/share/icin...')
    #17 /usr/share/php/Zend/Controller/Action/Helper/ViewRenderer.php(912): Zend_View_Abstract->render('list/table.phtm...')
    #18 /usr/share/php/Zend/Controller/Action/Helper/ViewRenderer.php(933): Zend_Controller_Action_Helper_ViewRenderer->renderScript('list/table.phtm...', NULL)
    #19 /usr/share/php/Zend/Controller/Action.php(212): Zend_Controller_Action_Helper_ViewRenderer->render('list/table', NULL, true)
    #20 /usr/share/icingaweb2/modules/director/application/controllers/ImportsourceController.php(60): Zend_Controller_Action->render('list/table', NULL, true)
    #21 /usr/share/php/Zend/Controller/Action.php(516): Icinga\Module\Director\Controllers\ImportsourceController->previewAction()
    #22 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('previewAction')
    #23 /usr/share/php/Zend/Controller/Front.php(954): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
    #24 /usr/share/php/Icinga/Application/Web.php(383): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
    #25 /usr/share/php/Icinga/Application/webrouter.php(109): Icinga\Application\Web->dispatch()
    #26 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...')
    #27 {main} 

</pre>
The hostgroup "sslvpn" exists and is configured within /etc/icinga2/conf.d/juniper/ive.conf (see attachment):

    # common hostgroup for all SSLVPN appliances
    object HostGroup "sslvpn" {
            display_name =          "Juniper IVE SSL-VPN Appliances"
    }

This installation runs on CentOS 7 with SElinux enabled (if that matters).

Any ideas what might be wrong?

Best regards,
Stephan

**Attachments**

* [icinga-director-hostgroups_not_found.tar.gz](https://dev.icinga.com/attachments/download/3247/icinga-director-hostgroups_not_found.tar.gz) pef - _2016-03-25 15:40:46 +00:00_ - _Tarball of the /etc/icinga2/ config dir WITHOUT pki subdir_

**Changesets**

_2016-03-27 14:58:04 +00:00_ by _tgelf_ bc6bac9a62baa2f5c4f144f705df6f646a8ed50a

    ImportSourceCoreApi: add hostgroup support
    
    refs #11451

**Comment by SMUsamaShah** [comment]
We added hosts using conf.d and zones.d in Icinga2 and then installed Icinga Director but it is not importing any services or hosts. Kickstart completes without giving any exception or error.
Do I have to add all services manually? Adding new hosts using Director works but do we need to create all services, service templates manually?

**Comment by furier** [comment]
@SMUsamaShah same question for me...

**Comment by TheBags** [comment]
Hi,
I've the same problem.
My icinga2 is working well.
I've installed director module following the installation instructions.
But the wizard doesn't import anything :(


icinga2 version: r2.10.2-1

System information:
  Platform: Ubuntu
  Platform version: 18.04.1 LTS (Bionic Beaver)
  Kernel: Linux
  Kernel version: 4.15.0-38-generic
  Architecture: x86_64

Build information:
  Compiler: GNU 7.3.0
  Build host: 8baa592f9b22

Application information:

General paths:
  Config directory: /etc/icinga2
  Data directory: /var/lib/icinga2
  Log directory: /var/log/icinga2
  Cache directory: /var/cache/icinga2
  Spool directory: /var/spool/icinga2
  Run directory: /run/icinga2

Old paths (deprecated):
  Installation root: /usr
  Sysconf directory: /etc
  Run directory (base): /run
  Local state directory: /var

Internal paths:
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

![screenshot from 2018-11-15 14-40-37](https://user-images.githubusercontent.com/2011000/48556889-7bfaf800-e8e5-11e8-9ec2-9b7d18a56569.png)
![screenshot from 2018-11-15 14-40-15](https://user-images.githubusercontent.com/2011000/48556890-7c938e80-e8e5-11e8-81cc-a3f2ccba48a8.png)
![screenshot from 2018-11-15 14-40-05](https://user-images.githubusercontent.com/2011000/48556891-7c938e80-e8e5-11e8-9002-82847f4da9a6.png)

**Comment by Thomas-Gelf** [comment]
@TheBags & others: please do not comment on issues that have been closed more than two years ago. The very first paragraph in the [Getting Started](https://github.com/Icinga/icingaweb2-module-director/blob/master/doc/04-Getting-started.md#getting-started) documentation reads:

> Director is not allowed to modify existing configuration in /etc/icinga2 [..] And while importing existing config is possible [..], it is a pretty advanced task you should not tackle at the early beginning.

Kickstart imports just some very basic objects, like Zones, Endpoints and especially commands - as it wants to play nice with configuration shipped with the `itl`. And before opening other issues please eventually try to our community channels first and try to gain some basic understanding on how the Director works.
