### ISSUE TITLE
History / Activity Log: Filter on host is ignored

### ISSUE THREAD

**Issue by dbu1986** [Icinga/icingaweb2-module-director#1613]
## Expected Behavior

Viewing the "History" tab of a host-assigned service shows only activities regarding the given unique service.

## Current Behavior

If you have services having the same service name, but assigned to different hosts, and inspect each service's "History" tab, every list includes all activities of all services. The tab's URL GET parameter "host" seems not to be included in the filter expression.

## Possible Solution

Debugging the filter expression of the "History" tab URL: 
``` 
icingaweb2/director/service/history?host=[HOSTNAME]&name=[SERVICENAME]
```

## Steps to Reproduce (for bugs)

1. Create service HostA!testservice via Director
2. Create service HostB!testservice via Director
3. Make changes on each services (e.g. of their custom variables)
3. Open the "History" tab of HostA!testservice
4. The activity log will include changes of both services HostA!testservice & HostB!testservice

## Your Environment

* Director version (System - About): 1.5.1
* Icinga Web 2 version and modules (System - About): 2.6.3
* Icinga 2 version (`icinga2 --version`): 2.9.1
* Operating System and version: RHEL 7.5

**Comment by Thomas-Gelf** [comment]
Thanks for reporting this, I'll push a fix.
