### ISSUE TITLE
"Remove" button removes wrong serviceset in Host / Services view

### ISSUE THREAD

**Issue by terra-nova** [Icinga/icingaweb2-module-director#1619]
## Expected Behavior

We have hosts with multiple servicesets manually assigned to them. When clicking the "Remove" button in the Services tab on a Host object, the wrong serviceset is removed.

## Current Behavior

![snap0](https://user-images.githubusercontent.com/16338849/44908668-9973e900-ad1c-11e8-87f4-731d7c4857d3.PNG)

But another serviceset is removed instead:

![snap1](https://user-images.githubusercontent.com/16338849/44908678-a98bc880-ad1c-11e8-96c9-fb7f2321f256.PNG)

## Your Environment

* Director version (System - About): Git `2075f2e54a38a05888a0dcc75fd69f3812b30c4e`
* Icinga Web 2 version and modules (System - About): 2.6.1
* Icinga 2 version (`icinga2 --version`): 2.8.4
* Operating System and version: CentOS 7.5 x86_64
* Webserver, PHP versions: Apache 2.4, PHP 7.2 from CentOS SCLO

**Comment by Thomas-Gelf** [comment]
Thanks for reporting this!
