### ISSUE TITLE
boolean custom field and assign rules does not work for negate

### ISSUE THREAD

**Issue by gody01** [Icinga/icingaweb2-module-director#1625]
There is still issue as described in:

[dev.icinga.com #12095] boolean custom field and assign rules does not work #339

for negate condition director writes:

assign where host.vars.test_boolean != "true"

**Comment by gody01** [comment]
Director version: 1.4.3

**Comment by Thomas-Gelf** [comment]
Director writes `"true"` as you filled the string "true" into that field I guess. Having some magic in place would be dangerous, as someone else might want to match the String "true". In v1.5.x now provices `is false (not set)`, in v1.4.x please use `NOT` and then `is true (or set)`
