### ISSUE TITLE
Synced custom variables not shown when modifying a host

### ISSUE THREAD

**Issue by widhalmt** [Icinga/icingaweb2-module-director#1638]
## Expected Behavior

When syncing a property from an external source into an previously nonexistent custom variable I want to see this custom variable when viewing the host in Director for modification.

Current example: I put the type of EC2 instances into the custom variabel `host.vars.ec2machinetype` by using the Icinga Web 2 Module for AWS:

## Current Behavior

* I can see the custom variable in Icinga Web 2 outside of Director
* I can see the custom variable in the `Preview` tab of Director
* I *can't* see the custom variabel in the `Modify` view of this host in Director

## Possible solution

It seems like it works like expected when you create the custom variable as data field in Director and add this (empty) data field to a template for the host.

## Steps to Reproduce (for bugs)

1. Add a sync property from and external source and use a (previously non-existent) custom variable as destination
2. view one of the synced hosts in the `modify` mode of Director

## Your Environment

* Director version (System - About): 1.5.1
* Icinga Web 2 version and modules (System - About): 2.6.1
* Icinga 2 version (`icinga2 --version`): 2.9.1
* Operating System and version: RHEL 7 (on AWS)
* Webserver, PHP versions: httpd 2.4.6, php 7.1 (FPM)

**Comment by Thomas-Gelf** [comment]
Well... "works as designed" :laughing:

Vars are not presented in the UI unless related fields are provided. Reasons: control, security, usability. I do not think it would be wise to change this, you could however try to push issues like #508.

**Comment by widhalmt** [comment]
:laughing: I'm ok with that. Thanks for explaining.
