### ISSUE TITLE
Cannot change existing command argument value type

### ISSUE THREAD

**Issue by mdetrano** [Icinga/icingaweb2-module-director#1640]
## Expected Behavior

When changing the "value type" of an **existing** command argument, from "String" to "Icinga DSL" or vice versa, the value type should change after clicking "store".

## Current Behavior

The value type resets to whatever it was after clicking "store".

## Possible Solution

This seems to be intentionally implemented in IcingaCommandArgument.php, around line 150.
[github](https://github.com/Icinga/icingaweb2-module-director/blob/master/library/Director/Objects/IcingaCommandArgument.php#L150)

`unset($plain->argument_format); `

If I comment that line out, the value type can be changed and I can't see any problem with doing that..export works fine, API works fine.  Not sure why this was designed this way or if it needs to stay this way for some reason.

## Steps to Reproduce (for bugs)

Create a command in Director, create an argument.  Go back to that argument after creation, try to change the "value type" field, and click sore.

## Your Environment

* Director version (System - About): current master branch
* Icinga Web 2 version and modules (System - About):
* Icinga 2 version (`icinga2 --version`):
* Operating System and version:
* Webserver, PHP versions:

**Comment by Thomas-Gelf** [comment]
@mdetrano: I'll push it to master and we'll see what happens ;-)
