### ISSUE TITLE
Wrong Autocomplete in Service-Apply when using Datalist/Array in host.vars

### ISSUE THREAD

**Issue by joni1993** [Icinga/icingaweb2-module-director#1646]
## Expected Behavior
1. Create a list (e.g. "roles")
![2](https://user-images.githubusercontent.com/29347/45682517-bdb72e80-bb40-11e8-8e5e-7cebecc6b117.png)
2. Create field of type "Datalist" with datatype "Datalist" and  targettype Array
![3](https://user-images.githubusercontent.com/29347/45682531-cad41d80-bb40-11e8-96db-3ad118695ff8.png)
3. Add field to Host template & set field in host
![4](https://user-images.githubusercontent.com/29347/45682574-f0f9bd80-bb40-11e8-9e25-2de641103191.png)
4. Create Service-Apply rule with host.vars.roles
Autocomplete fills in the correct element from host.vars.roles

## Current Behavior
In step 4 the director inserts "Arrayelement-name [arrayelement-key]" instead of just the key
![5](https://user-images.githubusercontent.com/29347/45682729-7aa98b00-bb41-11e8-8800-6f7da6de372e.png)
This results in the service never beeing applied because it renders like this:
![6](https://user-images.githubusercontent.com/29347/45682754-901eb500-bb41-11e8-9b4f-4db4b1972534.png)

## Your Environment
* Director version (System - About): master (e895978ff243c007a2a50a1c34ea54bd5ef59411)
* Icinga Web 2 version and modules (System - About): 2.6.1
* Icinga 2 version (`icinga2 --version`): r2.9.1-1
* Operating System and version: Ubuntu 16.04
* Webserver, PHP versions: Apache2, 7.2 behind Nginx Reverse proxy

**Comment by Thomas-Gelf** [comment]
This should have been fixed with #1918 and released with v1.8.0.
