### ISSUE TITLE
Selection multiple hosts returns SQL error : 'table icinga_group__resolved' doesn't exist

### ISSUE THREAD

**Issue by camskkz** [Icinga/icingaweb2-module-director#1647]
## Expected Behavior
Selecting multiple hosts in the director view should allow us to change hostgroup and host templates for these hosts. 
This was working a few commits ago (less than 2 months ago) but I am not sure at which point it stopped working.

## Current Behavior
When selecting multiple hosts we get the following message : 

> SQLSTATE[42S02]: Base table or view not found: 1146 Table 'icinga2_director.icinga_group__resolved' doesn't exist, query was: SELECT g.object_name FROM icinga_group__resolved AS gr
INNER JOIN icinga_group AS g ON g.id = gr.group_id
LEFT JOIN icinga_group_ AS go ON go.group_id = gr.group_id AND go._id = 4222 WHERE (gr._id = '4222') AND (go._id IS NULL) ORDER BY g.object_name ASC

![capture d ecran 2018-09-19 a 14 56 22](https://user-images.githubusercontent.com/22221036/45754566-435bdc80-bc1c-11e8-8274-adb4c99bf27e.png)

## Steps to Reproduce (for bugs)
Go into Icinga Director > Host Objects > Hosts > Select multiple hosts with shift clic or ctrl clic

## Your Environment
* Director version (System - About): master Git commit e2bd821d26afb9e79b646a7932c4675c4f3b2c5f 
* Icinga Web 2 version and modules (System - About):
Icinga Web 2 Version 2.6.1 Git commit b3e0b5d587c3587a09d82b3634dbe3a5dd315353 
cube 1.0.1
doc 2.6.1
monitoring 2.6.1
puppetdb 1.0.0
theme-vpgrp 1.0.0
theme-vptech 2.0.0
vsphere 1.1.0

* Icinga 2 version (`icinga2 --version`): r2.8.2-1
* Operating System and version: Debian 8.11
* Webserver, PHP versions: nginx1.14, php5.6

**Comment by GalipoliX** [comment]
Same problem here.
Icinga Web 2 Version 2.6.1

Director Version master 
Git Commit 926bc2b0c6fb4ff416f79bc18ee7f6275fde3823


SQLSTATE[42S02]: Base table or view not found: 1146 Table 'director.icinga_group__resolved' doesn't exist, query was: SELECT g.object_name FROM icinga_group__resolved AS gr
INNER JOIN icinga_group AS g ON g.id = gr.group_id
LEFT JOIN icinga_group_ AS go ON go.group_id = gr.group_id AND go._id = 285 WHERE (gr._id = '285') AND (go._id IS NULL) ORDER BY g.object_name ASC

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'director.icinga_group__resolved' doesn't exist

**Comment by Thomas-Gelf** [comment]
Thanks for reporting and fixing this, good job!
