### ISSUE TITLE
Git Hub link is not available in Installation Page

### ISSUE THREAD

**Issue by gado4b2** [Icinga/icingaweb2-module-director#1648]
## Expected Behavior

Please include GitHub link for this module in installation page 
https://www.icinga.com/docs/director/latest/doc/02-Installation/

## Current Behavior

No Information related to GitHub link is available in installation page

## Your Environment

* Director version (System - About):
* Icinga Web 2 version and modules (System - About):
* Icinga 2 version (`icinga2 --version`):
* Operating System and version:
* Webserver, PHP versions:

**Comment by Thomas-Gelf** [comment]
Thanks for reporting this. This is for historical reasons, documentation has always been shipped with this software, so usually who was reading it already knew where to find it. The linked pull request will fix this once merged, so please follow that one for updates on this issue.
