### ISSUE TITLE
"Dry run" without deploy

### ISSUE THREAD

**Issue by widhalmt** [Icinga/icingaweb2-module-director#1661]
Hi,

I was asked if Director could have a "dry run" feature. In short it's just about having a way to check the created configuration with `icinga2 daemon -C` without triggering a deploy right afterwards.

This might help with writing configuration step-by-step without risking to  deploy valid yet inconsistent configuration. And it would keep Icinga 2 from syncing and reloading for small steps.

Cheers,
Thomas

/ref/NC/567668

**Comment by Thomas-Gelf** [comment]
Invalid configuration will never run, so there is nothing to fear here. In case you want to have such feature anyways it needs to be made available through the Icinga 2 API.

**Comment by widhalmt** [comment]
I might need more coffeine... seems like I mixed up the deployment methods of LConf and Director. 
X-) 

Now I see why there's no possibility for a "dry run". I'll talk to the people who asked me about this feature - maybe there'll be a follow-up issue for Icinga 2.

**Comment by Thomas-Gelf** [comment]
@widhalmt: can this be closed so far?

**Comment by lazyfrosch** [comment]
I think we can close this.

Btw. the actual deploy and config check is handed over to Icinga 2, we only parse the result after we uploaded the config.
