### ISSUE TITLE
Documentation Should include the location of the application

### ISSUE THREAD

**Issue by mwd5650** [Icinga/icingaweb2-module-director#1671]
It looks like the documentation section at https://www.icinga.com/docs/director/latest/doc/02-Installation/ points to  icingaweb2-module-director/doc/02-Installation.md. But when on the icinga website there is no mention in the introduction or the installation procedure where to get the module software from.

It's cost me more time that I'd like to admit, needlessly, because there is an assumption that the person reading this document got it from github, which is not always the case. So can someone please add the location of the director module to the actual installation documentation so that people can find the software that they'd like to install.

**Comment by gphargreaves** [comment]
I would be happy to update the docs and submit a pull request to try and clarify the installation procedure, however please can you let me know where you installed the director module / icingaweb2 from?

I have always installed from source, however appreciate this is not the same for everyone. Did you add the repo for your OS and install icingaweb2 using a package manager? If so can you provide some details?

**Comment by mwd5650** [comment]
It looks like this is fixed in pull request [#1656](https://github.com/Icinga/icingaweb2-module-director/pull/1656).

I ended up installing it from source once I found this gihub repository. However the documentation on the "official" Icinga2 website did not give a location for installation of the software. I guess it assumed that you would only be reading these instructions from the github repository, however the icinga website mirrors the installation document from this repository without indicating it is doing so, and since there is no location for the software in the instructions then if you go to the Incinga website and follow the instructions for installing director you'll find that it dumps you to essentially "Copy the source code to the director directory" without giving you a location in which to get the source code.

I've looked that the above pull request, it will fix this documentation issue and leave people to this repository. We just need to have the pull request merged in.

**Comment by Thomas-Gelf** [comment]
Thanks for reporting this. This is for historical reasons, documentation has always been shipped with this software, so usually who was reading it already knew where to find it. The linked pull request will fix this once merged, so please follow that one for updates on this issue.
