### ISSUE TITLE
Icingacli -> director can't import jobs

### ISSUE THREAD

**Issue by trondk** [Icinga/icingaweb2-module-director#1673]
Its possible to export jobs, but not to import them . using icingacli.
im running version 1.5.1, it this a Bug ?

/Tom

**Comment by Strijd** [comment]
@trondk 
Workaround 
Add all your jobs  to a basket and then  dump it with:
`icingacli director basket dump --<name of your basket >>  > jobs.json `

Then restore from STDIN 
`icingacli director basket restore < jobs.json `
