### ISSUE TITLE
Self-Service Registration throws an exception if client is already registered

### ISSUE THREAD

**Issue by zmaupin-do** [Icinga/icingaweb2-module-director#1675]
## Expected Behavior
If a client is already registered, don't fail out, return a 204 or 304 HTTP response. This is different than errors such as having an invalid key or an incorrectly configured host template. A client already being registered shouldn't cause a failure.

## Current Behavior
If a client is already registered, the software throws a SecurityException.

## Possible Solution
When sending POST for client self-service registration, if the client already exists - we shouldn't receive an error. The job is complete, and there were no faults. Instead can you return a 204?
https://github.com/Icinga/icingaweb2-module-director/blob/master/application/forms/IcingaHostSelfServiceForm.php#L103-L106

## Steps to Reproduce (for bugs)
1. Register a client with the Director self-service API.
2. Register the client again. Instead of receiving a response like 'nothing changed', the software throws an exception. 

## Your Environment

* We use chef. Each chef-client run our clients will attempt to register themselves unless they have a file created like /tmp/icinga2_registration (after successful registration). The problem is, if the file does not exist yet and the client is already registered - chef-client runs will fail instead of completing successfully because the registration action was completed previously.

**Comment by Thomas-Gelf** [comment]
Each client gets an API key on registration. This one is for your host only and should be persisted. `/tmp/icinga2_registration` is a bad idea, as `/tmp` is probably wiped on reboot. If you come with no or a wrong key and want to claim a host that has already been registered, this is going to be refused. You might be an attacker, so I'm not even telling you whether the host exists - or you have just the wrong key.

The key you generated on your template allows to register new hosts that haven't been claimed yet. Once registered, no one can steel your host - unless you free it in the Director.

Hope this helps.

Cheers,
Thomas

**Comment by zmaupin-do** [comment]
This makes sense. `If you come with no or a wrong key and want to claim a host that has already been registered, this is going to be refused.` However my case is stating why is there an error if I have the **correct** key and the host is already registered?

What about when we have the **correct** host template key? Why return an error here instead of a response like 'nothing changed'. How do we access the host key that's returned after registration?

How should we stop a client from attempting to register after their first registration? chef-client will call the POST function each time it converges unless we have some guard against this. So each time chef converges a client will attempt to register itself which is why we put the file in /tmp. Chef won't run the POST function if the file exists. The file is placed there upon successful registration. We want a client to attempt again after reboot so we chose /tmp purposely.

**Comment by Thomas-Gelf** [comment]
Ruby dummy code:

```ruby
def run
  if has_host_key?
    refresh_with_my_host_key
  else if has_template_key?
    register_with_template_key
  else
    # nothing to do, no auto-registration
  end
end
```

The two key types serve different purposes:
* **template key**: register new hosts using a specific template. Works only unless someone claimed this host. The response to the registration contains your personal host key
* **host key**: allows a host to fetch it's configuration, like the members of it's parent zone or the ticket required allowing you to ask your parent node to sign your certificate

The template key is not so critical. Sure, you can add new hosts - but you cannot steal another hosts identity. The host key is critical. It belongs to one host only and needs to be persisted in a safe place. When you drop and re-create the very same host you either need it's former key - or you need to free that host in the Director by "forgetting" it's key. With the host key you can run the same request as often as you want. This way a host could for example change it's IP address or learn about new parent nodes.

**Comment by zmaupin-do** [comment]
That makes more sense. Thanks!

**Comment by Thomas-Gelf** [comment]
You're welcome!

**Comment by zmaupin-do** [comment]
```bash
$ curl -X POST -H 'Content-Type: application/json' \ 
  -H 'Accept: application/json' \
  -u 'icingaadmin' \
  -d '{
    "object_name": "sfo2node.$fqdn",
    "address": "$ip",
    "key": "$host_template_key"
    }' 
  http://preprod-icinga2-master01.../icingaweb2/director/self-service/register-host
{
    "error": "The host \"sfo2node.$fqdn\" has already been registered (IcingaHostSelfServiceForm.php:103)"
}
```
This was expected ^. However, I thought the next command would allow me to update the `address` field.

```bash
$ curl -X POST -H 'Content-Type: application/json' \
  -H 'Accept: application/json' -u 'icingaadmin' \
  -d '{
    "object_name": "sfo2node.$fqdn",
    "address": "$ip",
    "key": "$host_key_returned_from_original_registration"
  }'
  http://preprod-icinga2-master01,,,/icingaweb2/director/self-service/register-host
Enter host password for user 'icingaadmin':
{
    "error": "Got invalid API key \"$host_key_returned_from_original_registration\" (IcingaHostSelfServiceForm.php:71)"
}
```

The host key used here is the one that was returned when the node was originally registered.

(I have replaced fqdn, address, and the keys with placeholders.)

**Comment by zmaupin-do** [comment]
I tried POST to `director/host?name=sfo2node.$fqdn. This overwrote the object_name with the host key.
```bash
$ curl -X POST -H 'Content-Type: application/json' \
  -H 'Accept: application/json' -u 'icingaadmin' \
  -d '{"object_name": "sfo2node.$fqdn",
  "address": "$ip", 
  "key": "$host_key_returned_from_original_registration"}'
  http://preprod-icinga2-master01.../icingaweb2/director/host?name=sfo2node.$fqdn
Enter host password for user 'icingaadmin':
{
    "address": "$ip",
    "api_key": "$host_key_returned_from_original_registration",
    "imports": [
        "hypervisors"
    ],
    "object_name": "$host_key_returned_from_original_registration",
    "object_type": "object"
}
```

**Comment by Thomas-Gelf** [comment]
@zmaupin-do:
* your requests show that you're authenticating yourself with admin credentials, this conflicts with the main idea behind the Self-Service part of the API: providing a key to a bunch of hosts, allowing them for self-registration without causing any harm to other systems
* as soon as you give them admin credentials you're in trouble. You could use your `icingaadmin` user for scripts running on your Chef Server but not on single nodes, as those credentials are way too powerful
* anyone with full write access to the Director can deploy code that will run (with Icinga privileges) on every node
* in case you want to run these operations from a Chef Server, Puppet Master or whatever that would be fine - and you wouldn't be restricted to the Self-Service-API at all
* the Self-Service-API is for self-registration only

In case the Self-Service API is what you want to use, let me try to provide more detailed example:

```ruby
def run
  director_registration
  icinga_certificate
  icinga_config
end

def director_registration
  return if host_key?
  return unless template_key?
  register_host(host_params) || fail
end

def icinga_certificate
  return unless host_key?
  return if certificate?
  request_certificate(ticket)
end

# This creates a new Host object or claims/updates an existing one. Once
# a host has been claimed, it is locked and cannot be modified unless someone
# drops it's host key ("Agent" tab in the UI or via REST API)
def register_host(params)
  post("#{@director_url}/self-service/register-host", params.merge({ key => @template_key }))
end

def ticket
  @ticket ||= get("#{@director_url}/self-service/ticket?key=#{@host_key}")
end

def request_certificate
  # Call icinga2 [..]
  # Check host_details() for your ca_server or to figure out who your parents are
end

def icinga_config
  info = host_details
  # Build your config file based on this information:
  # {
  #   "fetch_agent_name": false,
  #   "fetch_agent_fqdn": true,
  #   "transform_hostname": "0",
  #   "flush_api_directory": false,
  #   "director_host_object": "{\"address\":\"&ipaddress&\",\"display_name\":\"&hostname&\"}",
  #   "agent_add_firewall_rule": true,
  #   "global_zones": [ "director-global" ],
  #   "parent_zone": "master",
  #   "ca_server": "icinga-master1.example.com",
  #   "parent_endpoints": [ "icinga-master1.example.com" ],
  #   "accept_config": true
  # }

  # Write your configuration, restart Icinga in case it has been changed.
end

def host_details
  @host_details ||= get("#{@director_url}/self-service/powershell-parameters?key=#{@host_key}")
end

def host_params
  {
    "object_name" => @host.name,
    "address" => @ip_address
  }
end

def host_key?
  !!@host_key
end

def template_key?
  !!@template_key
end
```

There is an error in my above comment, there is no way of changing host properties after a host has been registered. All a host key allows you to do is to fetch a Ticket (for an automated CSR) and some config details (Icinga peers, Zones...) required to write your Agent's Icinga Config.

The Self-Service API has no other REST API endpoints apart from the ones shown in above example. Hope this helps, otherwise please let me know.

Cheers,
Thomas

**Comment by zmaupin-do** [comment]
That helps a ton. Thank you.

**Comment by Thomas-Gelf** [comment]
You're welcome!
