### ISSUE TITLE
director jobs are not running after icinga and director update

### ISSUE THREAD

**Issue by Tuxdiver** [Icinga/icingaweb2-module-director#1677]
## Expected Behavior
`icingacli director jobs run` should run all jobs. 

## Current Behavior
Jobs don't run, director shows 'This job runs every 900s and is currently pending'
icingacli command with `--verbose` shows all jobs, but they are not executed
'strace' of icingacli shows:
`[pid 19403] write(1, "ERROR: Icinga\\Exception\\NotFoundError in /usr/share/icingaweb2/modules/director/library/Director/Data/Db/DbObject.php:626 with message: Failed to load director_job \"4\"\n", 168) = 168`

Giving a job name on the command line starts the job and its state becomes green.

## Possible Solution
Fix it :-)

## Steps to Reproduce (for bugs)
Upgraded Icinga from 2.9.2 to 2.10.0 and "git pulled" director. After DB-Upgrade, Health startet to show the problem of pending jobs.

## Your Environment
* Director version (System - About): git master from today (cb9366c5f53de1fa86f5729357a55bcee5c0f874)
* Icinga Web 2 version and modules (System - About): 2.6.1
* Icinga 2 version (`icinga2 --version`): r2.10.0-1
* Operating System and version: Ubuntu 16.04
* Webserver, PHP versions: apache2=2.4.18-2ubuntu3.9, php7=1:7.0+35ubuntu6.1

**Comment by Tuxdiver** [comment]
Hint: the exception is thrown because of this wrong select:
`SELECT director_job.* FROM director_job WHERE (job_name = '10')`
which makes no sense - 10 is the job id, not the job name...

**Comment by Thomas-Gelf** [comment]
@Tuxdiver: thanks, this hint helped a lot! I'll immediately push a fix.

**Comment by Thomas-Gelf** [comment]
Should be fixed, you need to restart your Job Daemon after pulling the latest master.

**Comment by Tuxdiver** [comment]
Works! Thanks for fixing it!
