### ISSUE TITLE
Problem with Icinga director

### ISSUE THREAD

**Issue by adis3421** [Icinga/icingaweb2-module-director#1679]
Hi,
I have problem with Icinga director. I install new icinga2 version 2.10.0-1 and add module director and I have problem:
The use statement with non-compound name 'Exception' has no effect

#0 /usr/share/php/Icinga/Application/Modules/Module.php(1227): Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(Integer, String, String, Integer, Array)
#1 /usr/share/php/Icinga/Application/Modules/Module.php(1227): include()
#2 /usr/share/php/Icinga/Application/Modules/Module.php(1245): Icinga\Application\Modules\Module->includeScript(String)
#3 /usr/share/php/Icinga/Application/Modules/Module.php(871): Icinga\Application\Modules\Module->launchConfigScript()
#4 /usr/share/icingaweb2/application/controllers/ConfigController.php(126): Icinga\Application\Modules\Module->getConfigTabs()
#5 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Controllers\ConfigController->moduleAction()
#6 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch(String)
#7 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#8 /usr/share/php/Icinga/Application/Web.php(300): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#9 /usr/share/php/Icinga/Application/webrouter.php(104): Icinga\Application\Web->dispatch()
#10 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#11 {main}
In previous versions it worked correctly

**Comment by Thomas-Gelf** [comment]
Thanks for reporting this!
