### ISSUE TITLE
What about future plans regarding CLI and import/export feature?

### ISSUE THREAD

**Issue by R-Sommer** [Icinga/icingaweb2-module-director#1683]
I’ve several installations of director and the need to synchronize changes. The best solution for me would be one installation acting as master and export/import function to distribute all changes.

On the other hand it would be helpful to extend the CLI i.e. to manage data fields.

Therefore, I’d like to know about future plans regarding this topics.

Many thanks!

**Comment by eifelmicha** [comment]
I'm also interested in this question. Right now i have written some sql statements and icingacli director scripts but it's a pita. It works fine for kickstarting environments but i would also like to see an feature like that.

If you need 1:1 you can do sql dump and replace the hostname inside the dump and reimport on the other client....

**Comment by Thomas-Gelf** [comment]
@R-Sommer, @eifelmicha: the future is now :rocket: 

The feature you're looking is already in the current master and called "Configuration Basket". You'll find related documentation directly in the GUI:

> A Configuration Basket references a specific Configuration Objects or all objects of a specific type. It has been designed to share Templates, Import/Sync strategies and other base Configuration Objects. It is not a tool to operate with single Hosts or Services.
>
> You can create Basket snapshots at any time, this will persist a serialized representation of all involved objects at that moment in time. Snapshots can be exported, imported, shared and restored - to the very same or another Director instance.

## Configuration Baskets on the Dashboard
![01-basket_dashboard](https://user-images.githubusercontent.com/553008/47614002-f0860800-da98-11e8-87ba-5b37c8d38a9a.png)

## Introduction / Overview

![01_basket-introduction](https://user-images.githubusercontent.com/553008/47614084-2972ac80-da9a-11e8-853a-685e99ad77e5.png)

## Configure your Baskets
![02-basket_config](https://user-images.githubusercontent.com/553008/47614010-fed42400-da98-11e8-80ab-e8d005ec5723.png)

## Create as many Snapshots as you want
![03-basket_snapshot](https://user-images.githubusercontent.com/553008/47614012-0267ab00-da99-11e8-8398-8effe2e8bf1d.png)

## Diff existing snapshots against current configuration
![04-basket_snapshot_diff](https://user-images.githubusercontent.com/553008/47614013-04ca0500-da99-11e8-95ba-c473cd487f50.png)

## Show raw object diff
![05-basket_snapshot_object_diff](https://user-images.githubusercontent.com/553008/47614014-098eb900-da99-11e8-9e33-9c5a925967e5.png)

## Restore a Basket, eventually to another Director DB
![06-basket_restore_to_other_db](https://user-images.githubusercontent.com/553008/47614016-0bf11300-da99-11e8-9652-10f3778159e2.png)

## CLI

[CLI Documentation](https://github.com/Icinga/icingaweb2-module-director/blob/master/doc/60-CLI.md#director-configuration-basket) exists.

**Comment by Thomas-Gelf** [comment]
I hope this answered your questions, otherwise please let me know. Closing this issue for now.

**Comment by R-Sommer** [comment]
At a first glance, it looks promising. However, I can't see whether Data Fields and Data Lists are covered. Do they (maybe as part of host templates?)?

I'm experiencing some errors. Do you want me to open separate issues?

**Comment by Thomas-Gelf** [comment]
Data Fields are covered. Just add Templates, Commands or Sets, all related fields will be part of the basket. Unused fields aren't tracked, but this could easily be added if you need it. Data Lists already worked, as they where among the first objects I tested. Seems they got lost, they are not in the Basket Settings form. Known errors so far:

* Adding single Commands has been missing, fixed yesterday together with a little bug related to Host Templates
* Summary field is too short in the database, adding all object types leads to an Exception
* Data Lists cannot be chosen in the GUI
* It currently fails on PostgreSQL
* There is an issue with notifications, adding them fails

All of the above will be fixed for v1.6.0, if you have more please let me know in dedicated issues.

Thanks,
Thomas
