### ISSUE TITLE
using alternative pnp4nagios template for checks

### ISSUE THREAD

**Issue by swizzly** [Icinga/icingaweb2-module-director#1686]
Hi

It is rather a Feature request.
We use the command check_by_ssh in many service templates to execute many different checks on remote hosts. The problem is, that pnp4nagios uses the same check_by_ssh template for all of these different checks. We would like to be able to define which pnp4nagios template should be used for a given service template. [Here](http://docs.pnp4nagios.org/de/pnp-0.6/advanced) it is mentioned, that pnp4nagios understands, if the template is defined in braces at end of the perfdata. E.g.: to force the use of check_icmp template: `OK - 127.0.0.1: rta 2.687ms, lost 0% | rta=2.687ms;3000.000;5000.000;0; pl=0%;80;100;; [check_icmp]`
Would it be possible to implement it in Director?

Cheers

**Comment by Thomas-Gelf** [comment]
This cannot be implemented in the Director. You could however deal with custom variables and tweak your [perfdata writer](https://icinga.com/docs/icinga2/latest/doc/09-object-types/#perfdatawriter) accordingly or create dedicated commands inheriting  from `by_ssh`.
