### ISSUE TITLE
Create a view for non privileged users: assignes for a Host Object.

### ISSUE THREAD

**Issue by lokidaibel** [Icinga/icingaweb2-module-director#1687]
## Expected Behavior

The view already exist it just Need more rights to be viewed. To many in my case.
It would be nice to have the possibility to enable a "view only" mode so that users that are not allowed to 
Login into the Icinga director would be able to check which apply rules assigned which checks.

It looks like this in Director and it would be cool if my users would see that as well;
https://gyazo.com/9123b3b7f0c7c1b2b8b9dd90f2cfd1d2

## Current Behavior

While using the Director as configuration tool I am not able to provide this information on demand to my users.
This improvement would automate this issue. So far I need to create screenshots for the users *ugly*

## Possible Solution

Create a “Director Viewer” module where they can watch all informations I provided in the screenshot so I can enable the access for it for a specific Icinga role with the permission management within icingaweb2.

## Steps to Reproduce (for bugs)

Just try to figure out how you service are being applied without Director Access rights ;-)

## Your Environment 

* Director version (System - About): 1.5.1
* Icinga Web 2 version and modules (System - About):2.6.1
* Icinga 2 version (`icinga2 --version`): r2.9.1-1
* Operating System and version: Red Hat Enterprise Linux Server release 7.5 (Maipo)
* Webserver, PHP versions:
* HTTPD: 2.4.6-80.el7_5.1
* PHP:
rh-php71.x86_64                  1-1.el7              
rh-php71-php.x86_64              7.1.8-1.el7          
rh-php71-php-cli.x86_64          7.1.8-1.el7          
rh-php71-php-common.x86_64       7.1.8-1.el7          
rh-php71-php-fpm.x86_64          7.1.8-1.el7          
rh-php71-php-gd.x86_64           7.1.8-1.el7          
rh-php71-php-intl.x86_64         7.1.8-1.el7          
rh-php71-php-json.x86_64         7.1.8-1.el7          
rh-php71-php-ldap.x86_64         7.1.8-1.el7          
rh-php71-php-mbstring.x86_64     7.1.8-1.el7          
rh-php71-php-mysqlnd.x86_64      7.1.8-1.el7          
rh-php71-php-pdo.x86_64          7.1.8-1.el7          
rh-php71-php-pear.noarch         1:1.10.4-1.el7       
rh-php71-php-pgsql.x86_64        7.1.8-1.el7          
rh-php71-php-process.x86_64      7.1.8-1.el7          
rh-php71-php-xml.x86_64          7.1.8-1.el7          
rh-php71-php-zip.x86_64          7.1.8-1.el7          
rh-php71-runtime.x86_64          1-1.el7

**Comment by Thomas-Gelf** [comment]
This has been implemented with #1785, I didn't realize that there was an existing issue for this.
