### ISSUE TITLE
Email notification not sending on director module 

### ISSUE THREAD

**Issue by prabhakaran2304** [Icinga/icingaweb2-module-director#1689]
### i configured notification using director module but i am getting warning like 

Config file "zones.d/icingaweb2/notification_apply.conf"

 **warning in director Rendered file** --> apply notification "host_notify_mail_new" to Host 

> [2018-10-26 12:14:10 +0530] warning/ApplyRule: Apply rule 'host_notify_mail_new' 
  (in [stage]/zones.d/icingaweb2/notification_apply.conf: 1:0-1:48) for type 'Notification' does not match anywhere!

> apply Notification "host_notify_mail_new" to Host {
    import "host_mail"
    interval = 0s
    assign where HostGroup == "INFRA"
    states = [ Critical, Down, OK, Unknown, Up, Warning ]
    types = [
        Acknowledgement,
        Custom,
        DowntimeEnd,
        DowntimeRemoved,
        DowntimeStart,
        Problem,
        Recovery
    ]
    user_groups = [ "dc_team_all" ]
    users = [ "vprabhakaran" ]
}

## Steps to Reproduce (for bugs)

/var/log/icinga2/icinga2.log 

> [2018-10-26 11:00:15 +0530] information/ExternalCommandListener: Executing external command: [1540531815] SEND_CUSTOM_HOST_NOTIFICATION;INFRA_PRD_srv-2;0;vprabhakaran@xxxxx;chk
[2018-10-26 11:00:15 +0530] information/Checkable: Checking for configured notifications for object 'INFRA_PRD_srv-2'
[2018-10-26 11:00:15 +0530] information/Checkable: Checkable 'INFRA_PRD_srv-2' does not have any notifications.

## Your Environment

* Director version (System - About):master
* Icinga Web 2 version and modules (System - About):2.6.0
* Icinga 2 version (`icinga2 --version`):r2.9.0-1
* Operating System and version: centos-7.5
* Webserver, PHP versions: Apache/2.4.6 , rh-php71

**please help out , i was stuck since long only on my notification part .**

**Comment by Thomas-Gelf** [comment]
```
 assign where HostGroup == "INFRA"
```

This should read `host.groups`, and that's what the filter form field should suggest.
