### ISSUE TITLE
API Requests Slow/Timeout

### ISSUE THREAD

**Issue by SimonHoenscheid** [Icinga/icingaweb2-module-director#1692]
## Expected Behavior
Requests are smooth

## Current Behavior
setting the header to application/json results in extremly slow requests and timeouts. No longer possible to perform 10 or GET requests on a host object in a row.

Note: The User is a user available in the Userdatabase, no AD/LDAP involved

Trying the same Request as a loggedin User in the Webinterface results in very smooth response, so maybe Login involved?

## Steps to Reproduce (for bugs)
Perform curl Request on a host object in a loop and set the header to application/json.

## Your Environment

* Director version (System - About):
fc2e972bcdd4e55154936e446bf0173ed701371e
* Icinga Web 2 version and modules (System - About):
businessprocess | 2.1.0
director | master
doc | 2.6.1
grafana | master
monitoring | 2.6.1
reactbundle | v0.3.1
setup | 2.6.1
translation | 2.6.1
unicorn | master
vspheredb | 1.9.99alpha
* Icinga 2 version (`icinga2 --version`):
version: r2.10.1-1
* Operating System and version:
Platform: CentOS Linux
Platform version: 7 (Core)
Kernel: Linux
Kernel version: 3.10.0-862.14.4.el7.x86_64
Architecture: x86_64
* Webserver, PHP versions:
Apache/2.4.6 (CentOS)
 PHP 7.1.8-1.el7

**Comment by Thomas-Gelf** [comment]
If there is a problem we'll track it down. Please provide more details, I'm unable to reproduce this. How slow is slow, how long does a single request take? What parameters are you using, please show your full request. Do you have the chance to provide a packet capture? You can also send it via mail or let me know if you need a secure upload channel. Login will of course be involved, but shouldn't be very slow.

Thanks,
Thomas

**Comment by Thomas-Gelf** [comment]
Thanks! I guess `GET director/hosts` is pretty fast? Some of your requests are unbelievably slow. Could you please have a look at the involved systems during such a hanging request? `SHOW FULL PROCESSLIST` in MySQL, Apache Status -> are there free slots - and which process burns CPU, if any.

Thanks,
Thomas

**Comment by SimonHoenscheid** [comment]
The GET director/hosts shows the same behavior. Mysql is clean. The Host has a constant load of 8-12, but lots of spare CPU power, also memory and IO is available. Interesting thing is:

Icingaweb2 2.6.2 introduced "LDAP connections now have a timeout configuration which defaults to 5 seconds" feature, which leads to a maximum timeout of 5 secs, but the involved user is a user inside the web database, which has first priority in authentication backends. 

Thanks 
Simon

**Comment by Thomas-Gelf** [comment]
We tracked this down to an issue with LDAP/AD-Auth being slow and Icinga Web 2 issueing useless queries for unrelated Group membership. A related [Pull-request](https://github.com/Icinga/icingaweb2/pull/3652) has been created.

Thanks @SimonHoenscheid!
