### ISSUE TITLE
Trying to set invalid icinga_timeperiod key "prefer_includes". DB schema change? 

### ISSUE THREAD

**Issue by dfrise** [Icinga/icingaweb2-module-director#1694]
Hi,

Issue after upgrading from 1.5.1 to 1.5.2 (module replaced by the new one).

## Expected Behavior
Activity Log/Deploy 1 pending change without error

## Current Behavior
Activity Log/Deploy 1 pending change throws this error:
**Trying to set invalid icinga_timeperiod key "prefer_includes". DB schema change? (DbObject.php:651)**

## Steps to Reproduce (for bugs)
Upgrade from 1.5.1 to 1.5.2
Activity Log/Deploy 1 pending change

## My Environment
* Director version (System - About): 1.5.2
* Icinga Web 2 version and modules (System - About):  2.6.1
* Icinga 2 version (`icinga2 --version`): 2.10.1-1
* Operating System and version: RHEL 7.6
* Webserver, PHP versions: 7.1

Thanks
Dominique

**Comment by geotekberlin** [comment]
same issue here too

**Comment by dfrise** [comment]
Thanks Thomas for the reply and good catch!
Yes, I did use a master and thought it was at 1.5.1 level.

> director=# SELECT * FROM director_schema_migration;
>  schema_version |        migration_time        
> ----------------+------------------------------
>             151 | 2018-10-26 19:18:32.12351+02
> (1 row)

Thanks,
Dominique

**Comment by Thomas-Gelf** [comment]
@dfrise: then you need to go back to the master, schema downgrade is (intentionally) not supported. v1.6.0 will be there very soon.

**Comment by dfrise** [comment]
Got it, thanks
Dominique

**Comment by Thomas-Gelf** [comment]
You're welcome!
