### ISSUE TITLE
Health check inconsistency between GUI and CLI

### ISSUE THREAD

**Issue by swizzly** [Icinga/icingaweb2-module-director#1700]
## Expected Behavior
Healt check results in the Web GUI and the CLI should be identical.

## Current Behavior
In the Web GUI healt check page I see Problems that are "OK" in the CLI command results.
E.g. I have overdue problems with all four "Director Jobs", but in the results of the CLI command "icingacli director health check" all four are shown as "OK".
Under Director/Automation/Jobs all jobs are shown as pending, although they seem to be running: I tested it, as I changed the "Run interval" to 30 seconds and the "last attempt succeeded" data updates regularly, however with a timeoffset of -1h to the current local time.

## Your Environment

* Director version (System - About): gfc2e972
* Icinga Web 2 version and modules (System - About): 2.6.1-1
* Icinga 2 version (`icinga2 --version`): r2.9.1-1
* Operating System and version: RHEL 7.6
* Webserver, PHP versions: httpd-2.4.6-88.el7, rh-php71-php-7.1.8-1.el7

**Comment by Thomas-Gelf** [comment]
@swizzly: could this be related to #1332 or are other (non-Job) components affected too?

**Comment by swizzly** [comment]
I guess these are two separate problems. My system is indeed affected by the issue #1332 , but the problem here is that the CLI and the Web GUI show two different states, one (CLI) is OK while the Web GUI shows red overdue states.

**Comment by Thomas-Gelf** [comment]
If your web and your server are in different timezones this would explain this.

**Comment by swizzly** [comment]
The host where Icinga2 and also the httpd run and the client PC with the web browser are in the same timezone, at least the date command on the icinga2 host shows the same time as on the client pc.

**Comment by Thomas-Gelf** [comment]
@swizzly: we are investigating a strange issue with Icinga Web 2 itself. When going to your user down left in the menu, 'My Accout' -> what's your "Current Timezone"?

**Comment by dgoetz** [comment]
@Thomas-Gelf: Seeing here the same problem, GUI prints OK for those current and Pending for those uverdue, CLI prints everything OK. Timezones seem fine. Director version is slightly older than the one of the initial poster.
If you get in touch with me tomorrow, I can do some live debugging.

**Comment by Thomas-Gelf** [comment]
@dgoetz -> "seems fine" -> what timezone does Icinga Web 2 show? Is it Europe/London?

**Comment by dgoetz** [comment]
Systems timezone: Europe/Berlin (CET)
PHP (/etc/opt/rh/rh-php71/php.ini) timezone: Europe/Berlin
Icinga Web 2 timezone: Europe/Berlin

**Comment by swizzly** [comment]
Timezone in the WebGUI is "Browser (Europe/Paris)"

**Comment by XnS** [comment]
> @swizzly: could this be related to #1332 or are other (non-Job) components affected too?

In my case its related to the mentioned issue. Server uses UTC, clients CET which results in a critical for the health check and GUI.

Probably the same thing as in #1332: time() uses the local time instead of the server time.
https://github.com/Icinga/icingaweb2-module-director/blob/5404e32f6dbd7dbab373a321d09d69cae6072891/library/Director/Objects/DirectorJob.php#L114

**Comment by mwaldmueller** [comment]
Same here with v.1.6.2 with "Housekeeping" job

**Comment by mwaldmueller** [comment]
ref/NC/626303

**Comment by carraroj** [comment]
ref/NC/636733

**Comment by Thomas-Gelf** [comment]
@carraroj: this should have been fixed with the current master and will be released with v1.7.0. In case you tested this with a recent master and it does still NOT work please let me know, as we're about to tag the next release.

**Comment by Thomas-Gelf** [comment]
Has been tested by @carraroj, thanks you!
