### ISSUE TITLE
Deleting director objects does not delete their icinga object

### ISSUE THREAD

**Issue by julenl** [Icinga/icingaweb2-module-director#1709]
## Expected Behavior
Deleting director objects should delete them completely from icinga2.

## Current Behavior
The objects disappear from director, but they stay in icinga2.

## Possible Solution
Flush somehow the deleted objects from icinga2.
As a dirty workaround, re-creating the objects on director seems to overwrite the icinga2 config, but I am still unable to completely delete them.

## Steps to Reproduce (for bugs)
Create an object, for example a host, deploy config, delete it, deploy, and confirm that it still exists in the icinga environment. For example:

    icingacli director host create myhost --imports basic_host --address 1.2.3.4 --vars...
    icingacli director config deploy
    icingacli director host delete myhost
    icingacli director config deploy

The following command confirms that the host is still there:

    icingacli monitoring list hosts | grep myhost

## Environment
* Director version (System - About): "master" 
* Icinga Web 2 version and modules (System - About): icingaweb2-2.6.1-1.el7.icinga.noarch, graphite 0.0.0.5, monitoring 2.6.1
* Icinga 2 version icinga2-bin-2.10.1-1.el7.icinga.x86_64
* Operating System and version: CentOS 7
* Webserver, PHP versions: httpd-2.4.6-80.el7.centos.1.x86_64, php71

**Comment by Thomas-Gelf** [comment]
@julenl: if the director successfully deployed the configuration (please check in the Web UI), then there is not much it can do about this. If `icinga2 object list` does not show your host, but `icingacli monitoring list` does, then this is a bug in Icinga 2. Can you please test this?

**Comment by julenl** [comment]
@Thomas-Gelf: The output of `icinga2 object list -t host | grep myhost` also shows "myhost", after deleting the host with director.
I do think that the problem is at director's side, while communicating to icinga2 the deletion of the object...

**Comment by Thomas-Gelf** [comment]
@julenl: what does the UI tell you about this deployment?

**Comment by julenl** [comment]
@Thomas-Gelf: Good point, I didn't check in there.

Thanks! that solved the problem.

Apparently I had an "assign_where" rule on a host group which was causing the error.

    [2018-11-21 17:38:43 +0100] critical/config: Error: Invalid right side argument for 'in' operator: "['icinga_agent', 'ntp_client']"
    Location: in [stage]/zones.d/director-global/hostgroups.conf: 3:18-3:50
    [stage]/zones.d/director-global/hostgroups.conf(1): object HostGroup "agent_hosts" {
    [stage]/zones.d/director-global/hostgroups.conf(2):     display_name = "Hosts with the icinga2 agent installed"
    [stage]/zones.d/director-global/hostgroups.conf(3):     assign where "icinga_agent" in host.vars.roles
                                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    [stage]/zones.d/director-global/hostgroups.conf(4): }
    [stage]/zones.d/director-global/hostgroups.conf(5): 

	(0) Evaluating rule for group 'agent_hosts'
	(1) Evaluating group memberships for host 'myhost'

    [2018-11-21 17:38:43 +0100] critical/config: 1 error

**Comment by Thomas-Gelf** [comment]
You're welcome!
