### ISSUE TITLE
Error (DbObject.php:651)

### ISSUE THREAD

**Issue by jkvint** [Icinga/icingaweb2-module-director#1713]
## Expected Behavior
Hi,

Issue after upgrading from 1.5.1 to 1.5.2 (git update).

Activity Log/Deploy 1 pending change without error

Trying to set invalid icinga_timeperiod key "prefer_includes". DB schema change? (DbObject.php:651)

SELECT  *  FROM  director_schema_migration ;
+----------------+---------------------+
| schema_version | migration_time      |
+----------------+---------------------+
|            145 | 2017-12-27 18:32:41 |
|            146 | 2018-10-04 11:59:33 |
|            147 | 2018-10-04 11:59:33 |
|            148 | 2018-10-04 11:59:33 |
|            149 | 2018-10-04 11:59:33 |
|            150 | 2018-10-04 11:59:34 |
|            151 | 2018-10-04 11:59:34 |
|            157 | 2018-11-22 11:09:11 |
+----------------+---------------------+
8 rows in set

## Your Environment

* Director version (System - About): 1.5.2
* Icinga Web 2 version and modules (System - About):2.6.1
* Icinga 2 version (`icinga2 --version`): r2.10.2-1
* Operating System and version: Debian 9
* Webserver, PHP versions: Apache/2.4.25 PHP 7.0.30-0+deb9u1

**Comment by Thomas-Gelf** [comment]
Please see #1694. However, in your case there is something special - you're missing migrations in the middle. Did you manually mess with the migration files?

**Comment by jkvint** [comment]
I come in /usr/share/icingaweb2/modules/director and git checkout v1.5.2. Its all

**Comment by Thomas-Gelf** [comment]
v1.5.2 contains migrations up to `150`, so you have been running a GIT master version with a higher schema version. We do no schema downgrades, as this usually means loosing data. So you have to stay at the current master and might opt to then stay on a stable version once v1.6.0 has been released.

Your `schema_migrations` table however shows that you not only have been using a newer version, but it also shows that you somehow manually applied a schema migration file. Jumping from 151 to 157 is hardly possible otherwise.

**Comment by jkvint** [comment]
But I did not do anything with my hands, only updated icinga2, icingaweb2 and icinga2 director. Its all. Now I can not apply anything

**Comment by jkvint** [comment]
Tell me exactly what you want to hear. I didn’t do anything complicated, just updated all the packages icinga that's it.

**Comment by Thomas-Gelf** [comment]
Please double-check your `schema_migration`  table, it is in no way possible to reach this state:
```
| schema_version | migration_time |
+----------------+---------------------+
...
| 151 | 2018-10-04 11:59:34 |
| 157 | 2018-11-22 11:09:11 |
```

**Comment by jkvint** [comment]
Command correct? 
mysql> SELECT  *  FROM  director_schema_migration ;
+----------------+---------------------+
| schema_version | migration_time      |
+----------------+---------------------+
|            145 | 2017-12-27 18:32:41 |
|            146 | 2018-10-04 11:59:33 |
|            147 | 2018-10-04 11:59:33 |
|            148 | 2018-10-04 11:59:33 |
|            149 | 2018-10-04 11:59:33 |
|            150 | 2018-10-04 11:59:34 |
|            151 | 2018-10-04 11:59:34 |
|            157 | 2018-11-22 11:09:11 |
+----------------+---------------------+
8 rows in set

mysql>

**Comment by Thomas-Gelf** [comment]
Yes. And that output shows that something strange took place on November 22th. This was definitively NOT just a transition from 1.5.1 to 1.5.2.

**Comment by jkvint** [comment]
How can I solve my problem?

**Comment by Thomas-Gelf** [comment]
First you need to switch to the current master branch, downgrading to v1.5.2 will not work for you. You definitively have NOT been only on v1.5.1 before switching to v1.5.2. And then we'll see. It would really help if you could tell me the full story of this installation.

**Comment by jkvint** [comment]
Please tell me how can I lower the version?

**Comment by Thomas-Gelf** [comment]
You should **never** lower the version. `git checkout master` and `git pull` will bring you to the current master. This will fix your initial error message, and then we'll see.

**Comment by jkvint** [comment]
its work's, Thx
