### ISSUE TITLE
director doesn't show all group members

### ISSUE THREAD

**Issue by fireba11** [Icinga/icingaweb2-module-director#1714]
## Expected Behavior
HostGroups  > Group Membership
lists all group members

## Current Behavior
It lists about half of the members for me.
However if i look at the individual hosts in director the Group os shown just fine.

## Steps to Reproduce (for bugs)
Not quite sure, half my shows show up, the other half doesn't, all using the same template. Only one group membership each, no dynamically assigned groups either. Can't tell what causes either behaviour.

## Your Environment
* Director version (System - About): 1.5.1
* Icinga Web 2 version and modules (System - About): 2.6.2
* Icinga 2 version (`icinga2 --version`): r2.10.2-1)
* Operating System and version: debian 9.6

**Comment by Thomas-Gelf** [comment]
This should have been fixed, otherwise please let me know
