### ISSUE TITLE
imported_* tables are not cleaned up

### ISSUE THREAD

**Issue by ruleant** [Icinga/icingaweb2-module-director#1715]
## Context
Director import source functionality allows to import data from external resources. During an import job, the imported data is stored in several tables : 
 - imported_rowset
 - imported_row
 - imported_rowset_row
 - imported_row_property
 - imported_property
 - import_run

## Expected Behavior
The imported data is added to the imported_* tables on every new import.
To avoid the database to keep growing over time :
- older data should be removed (keep a data from a few import runs and remove data from older import timestamps, fe. after a week)
- on a succesfull new import, current data is replaced by the new data.

## Current Behavior
The imported data is added to the imported_* tables on every new import, but is never removed. This causes the database to keep growing indefinitely. If the size of the imported properties is large, or if the frequency of the job is high, the increase in database size is higher.

## Possible Solution
A few possible solutions : 
- regularly remove properties/rows/rowsets that are associated with an older timestamp of a successful import_run record
- lookup the latest rowset_checksum when running an import run, and replace it (and all associated properties and rows) after a succesfull import
- brute force approach : regularly truncate all imported_* (and import_run) tables, but this has undesired side effects (possible foreign key inconsistency between tables, possible failed sync job or removal of some/all hosts in icinga2, because the imported* tables are empty)

## Steps to Reproduce (for bugs)
Monitor the size of the monitored_* tables to see that they only grow over time.

## Your Environment
* Director version (System - About): 1.5.2 
* Icinga Web 2 version and modules (System - About): 2.6.1
* Icinga 2 version (`icinga2 --version`): r2.10.0-1
* Operating System and version:
 -  Platform: Debian GNU/Linux
 -  Platform version: 9 (stretch)
 -  Kernel: Linux
 -  Kernel version: 4.9.0-8-amd64
 -  Architecture: x86_64
* Webserver, PHP versions:
 - apache: 2.4.25-3+deb9u
 - php 7.0.30-0+deb9u

**Comment by Thomas-Gelf** [comment]
@ruleant: thanks for reporting this, and sorry for the late reply. I created #1920 with more related details

**Comment by Thomas-Gelf** [comment]
Closing this one, please follow #1920.
