### ISSUE TITLE
Deploy crashes Icinga after upgrade

### ISSUE THREAD

**Issue by Stefar77** [Icinga/icingaweb2-module-director#1723]
## Expected Behavior
Icinga service not crashing.

## Current Behavior
When we deploy from director we need to ssh to the Icinga host to start the service because it dies.

syslog messages after crash;
`Nov 28 15:30:44 Nagios02 icinga2: accept() failed with error code 9, "Bad file descriptor"
Nov 28 15:30:44 Nagios02 icinga2: Cannot accept new connection.
Nov 28 15:30:45 Nagios02 icinga2: Invalid socket: Address already in use Context:       (0) Activating object 'api' of type 'ApiListener'
Nov 28 15:30:45 Nagios02 icinga2: Cannot bind TCP socket for host '' on port '5665'. Context:   (0) Activating object 'api' of type 'ApiListener'
Nov 28 15:30:45 Nagios02 icinga2: Cannot add listener on host '' for port '5665'. Context:      (0) Activating object 'api' of type 'ApiListener'
`
Other logfiles don't contain any relevant messages. 

By the way: icingacli director config deploy --debug doesn't crash/do anything without a change?!
`Config matches active stage, nothing to do`
If there are changes this also crashes Icinga. It starts loading the new instance and then crashes when it wants to switch to the new process I think.
https://pastebin.com/j5nLnB9E

## Possible Solution
Downgrade?!

## Steps to Reproduce (for bugs)
Update Icinga2 to 2.10.2-1, web 2.6.2 and director 1.5.2 and try a deploy.

## Your Environment

* Director version (System - About): 1.5.2
* Icinga Web 2 version and modules (System - About): 2.6.2
* Icinga 2 version (`icinga2 --version`): 2.10.2-1
* Operating System and version: FreeBSD 11.2
* Webserver, PHP versions: Apache24, PHP 5.6.38

**Comment by Stefar77** [comment]
Sorry, I think this is not director specific but more a FreeBSD/Icinga issue with opening the socket in the new process.

**Comment by bsdlme** [comment]
This was fixed in some recent Icinga version.

**Comment by Thomas-Gelf** [comment]
Thanks @bsdlme, @Stefar77 - I'm closing this issue
