### ISSUE TITLE
property modifier not visible

### ISSUE THREAD

**Issue by swizzly** [Icinga/icingaweb2-module-director#1727]
## Current Behavior
I have a custom made Icingaweb2 module where I have some special property modifiers. It used to work with some earlier versions of Director, but recently I discovered, that some of the property modifiers are not listed in the dropdown list, while some others are still visible in the list.
In import rules that were made earlier the involved modifiers are not visible, only "- please choose -" is shown instead of the name of the modifier, but the import rules work as they should. I cannot create new modifiers for properties, as I cannot select these property modifiers from the list.

## Your Environment

* Director version (System - About): some version from 26.11.2018, I think: 7926d55
* Icinga Web 2 version and modules (System - About): 2.6.1-1
* Icinga 2 version (`icinga2 --version`): r2.9.1-1
* Operating System and version: RHEL7.6
* Webserver, PHP versions: PHP 7.1.8-1, httpd 2.4.6-88

**Comment by Thomas-Gelf** [comment]
@swizzly: is this still an issue for you?
