### ISSUE TITLE
Invalid JSON in response when registering host through self-service API with empty key

### ISSUE THREAD

**Issue by hrak** [Icinga/icingaweb2-module-director#1728]
This is a bit of an edge case, but during automating our host registration with Icinga using Chef i found that trying to register a host through the self-service api with an empty key results in a response that cannot be parsed as JSON, complicating error handling.

## Expected Behavior
A response like 
```
{
    "error": "key is required"
}
```

## Current Behavior
```
{
    "error": "An unknown error ocurred"
}
{
    "error": "An unknown error ocurred"
}
{
    "error": "An unknown error ocurred"
}
{
    "error": "An unknown error ocurred"
}
{
    "error": "An unknown error ocurred"
}
{
    "error": "key is required"
}
```

## Steps to Reproduce (for bugs)

```
./director-curl POST "director/self-service/register-host?name=fake.example.com&key=" '{"address": "192.168.1.1", "display_name": "fake.example.com"}'
HTTP/1.1 400 Bad Request
Server: nginx/1.14.2
Date: Thu, 06 Dec 2018 09:19:47 GMT
Content-Type: application/json
Transfer-Encoding: chunked
Connection: keep-alive
Set-Cookie: Icingaweb2=9dg882a2vrd813g72pt7sjr9ju43b1f5; path=/; secure; HttpOnly
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache

{
    "error": "An unknown error ocurred"
}
{
    "error": "An unknown error ocurred"
}
{
    "error": "An unknown error ocurred"
}
{
    "error": "An unknown error ocurred"
}
{
    "error": "An unknown error ocurred"
}
{
    "error": "key is required"
}
```

## Your Environment
* Director version (System - About): 1.5.1
* Icinga Web 2 version and modules (System - About): 2.6.2
* Icinga 2 version (`icinga2 --version`): r2.10.2-1
* Operating System and version: Ubuntu 16.04
* Webserver, PHP versions: nginx 1.14.2 php 7.2.10

**Comment by Thomas-Gelf** [comment]
This should have been fixed recently. We re-scheduled v1.6.0 for next Monday, it would be great if you could test whether the current master still shows this behavior.

**Comment by hrak** [comment]
@Thomas-Gelf Just tested master branch, it looks like the amount of errors returned is now just reduced to one, but I'm not getting the relevant error msg 'key is required':

also its returning a 200 OK now for an error.

```
./director-curl POST "director/self-service/register-host?name=fake.example.com&key=" '{"address": "192.168.1.1", "display_name": "fake.example.com"}'
HTTP/1.1 200 OK
Server: nginx/1.14.2
Date: Thu, 06 Dec 2018 11:04:29 GMT
Content-Type: text/html; charset=UTF-8
Transfer-Encoding: chunked
Connection: keep-alive

{
    "error": "An unknown error ocurred"
}

```

**Comment by Thomas-Gelf** [comment]
Thanks for testing this, I'll try to fix it for the next release.

**Comment by Thomas-Gelf** [comment]
Sorry, I forgot about this one. Have to move it to 1.7.0. Should be less urgent anyways,now that the answer is technically valid. Will be fixed, but not today.

**Comment by Thomas-Gelf** [comment]
This should now finally have been fixed. Error message gives more details, and it is once again 400 and not 200.
