### ISSUE TITLE
Creating objects with some auto increment id = object_name still has issues

### ISSUE THREAD

**Issue by rattacresh** [Icinga/icingaweb2-module-director#1729]
Basic info see issue #992, issues are basically the same, though with different causes. In effect, we still had a patch lying around that fixed further issues with auto increment id = object_name.

This issue is for opening the respective pull request only.

**Comment by ix-dev** [comment]
We are currently testing director version 1.6.0 with the patch from pull request #1730 applied, though it seems that there are still more issues with the ids.
Several of our sync rules fail with an exception "Trying to recreate ..".

**Comment by Thomas-Gelf** [comment]
@ix-dev: are you still facing related issues with the current master?
