### ISSUE TITLE
Shema-Migration 156 failed

### ISSUE THREAD

**Issue by TobiasKneidl** [Icinga/icingaweb2-module-director#1736]
After Checkout Version 1.6.0 two pending shema migrations failed with the following error:
"Migration 156 failed (SQLSTATE[42704]: Undefined object: 7 ERROR: index "command_object_name" does not exist) while running DROP INDEX command_object_name"

## Your Environment
* Director version (System - About):1.6.0
* Icinga Web 2 version and modules (System - About): 2.6.2
* Icinga 2 version (`icinga2 --version`): r2.10.2-1
* psql (PostgreSQL) 9.5.14

**Comment by Thomas-Gelf** [comment]
Not sure how you managed it to get there, I tried to start with a fresh v1.5.0 on PostgreSQL (9.6) and applied all migrations, didn't face this issue. Nonetheless, I'll throw in an `IF EXISTS` clause to let this succeed in any case.
