### ISSUE TITLE
Basket Feature - hostgroup custom selection not working

### ISSUE THREAD

**Issue by Gammenon** [Icinga/icingaweb2-module-director#1737]
## Expected Behavior
select "custom selection" -> "submit" should work with "Host Group"

## Current Behavior
select "custom selection" -> "submit" with "Host Group" leads to an error message and to that the change to this selection isn't saved.
![image](https://user-images.githubusercontent.com/34088644/49931062-50f4cb80-fec6-11e8-83d1-8d8a6193a62c.png)

## Steps to Reproduce (for bugs)
create a new basket, select "custom selection" on "Host Group"

## Your Environment

* Director version (System - About): 1.60
* Icinga Web 2 version and modules (System - About): 2.6.1
* Icinga 2 version (`icinga2 --version`): 2.9.1
* Operating System and version: CentOS 7.6.1810
* Webserver, PHP versions: Apache/2.4.6, PHP/7.1.8

**Comment by matthenning** [comment]
Looks like it'll be fixed in 1.6.1 and is already fixed in the `support/1.6` branch: #1733
