### ISSUE TITLE
Basket: Undefined index: IcingaTemplateChoiceHost (Basket.php:148)

### ISSUE THREAD

**Issue by wutzkachel** [Icinga/icingaweb2-module-director#1738]
When I try to upload basket configuration, I get the following message:
Undefined index: IcingaTemplateChoiceHost (Basket.php:148)

## Your Environment

* Director version (System - About): 1.6.0
* Icinga Web 2 version and modules (System - About):
Icinga Web 2 Version 2.6.2
* Icinga 2 version (`icinga2 --version`): 
Icinga2 - The Icinga 2 network monitoring daemon (version: r2.10.2-1)

Copyright (c) 2012-2018 Icinga Development Team (https://icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

System information:
  Platform: CentOS Linux
  Platform version: 7 (Core)
  Kernel: Linux
  Kernel version: 3.10.0-862.14.4.el7.x86_64
  Architecture: x86_64

Build information:
  Compiler: GNU 4.8.5
  Build host: unknown

Application information:

General paths:
  Config directory: /etc/icinga2
  Data directory: /var/lib/icinga2
  Log directory: /var/log/icinga2
  Cache directory: /var/cache/icinga2
  Spool directory: /var/spool/icinga2
  Run directory: /run/icinga2

Old paths (deprecated):
  Installation root: /usr
  Sysconf directory: /etc
  Run directory (base): /run
  Local state directory: /var

Internal paths:
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

* Operating System and version:
CentOS Linux release 7.6.1810 (Core)
* Webserver, PHP versions:
nginx-1.14.2-1.el7_4.ngx.x86_64
rh-php71-php-fpm-7.1.8-1.el7.x86_64
PHP 7.1.8 (cli) (built: Aug  9 2017 13:20:06) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies

**Comment by carraroj** [comment]
Issue is reproducible on Host-Templates or Commands, the other objects i haven't tested. 
ref/NC/597455

**Comment by winter1967** [comment]
i can reproduce the issue on Templates, Commands, all objects.
Whatever basket i try to upload (commands, commands and templates, all objects) i still get the message.
Undefined index: Command (Basket.php:148)

What have i done:
- create a basket in our prod  icinga2 system
- setting some objects to "all of them"
- submit
- Message: Basket have been successfully stored
- going to snapshots
- create a snapshot of the basket
- 22x HostGroup (for example) has been created
- click on the Snapshot
- Download the Snapshot
-  go to the director of our test icinga2 system
- upload (configuration basket upload)
- give a name to this basket (for example hostgroups)
- choose the file i've downloaded (Director-Basket_HostGroups_dd7e6cf.json)
- Button upload
- Getting in this try the message: "Undefined index: HostGroup (Basket.php:148)"



- PHP Version:
5.4.16
- Zend-Engine
2.4.0
- Director-Version
1.6.0 (upgraded from previous version)
- RHEL-Version
Red Hat Enterprise Linux Server release 7.5 (Maipo)

**Comment by NetworkNub** [comment]
Using _Custom Selection_ during basket creation also causes this message to displayed.

**Comment by lazyfrosch** [comment]
This should be fixed with:

master 35318396
support/1.6 60018f47
