### ISSUE TITLE
Basket: Failed to load director_datalist

### ISSUE THREAD

**Issue by killepitisch** [Icinga/icingaweb2-module-director#1748]
## Expected Behavior

Successfully creating a snapshot for a basket.

## Current Behavior

Regardless of which Items to be taken into consideration in the basket configuration, a snapshot fails with the error message 'Failed to load director_datalist "" (DbObject.php:628)'.

![basket1](https://user-images.githubusercontent.com/30339380/50513194-7ffa6800-0a96-11e9-80db-f7063d10fb4c.png)
![basket2](https://user-images.githubusercontent.com/30339380/50513199-8688df80-0a96-11e9-9692-868fa94ef5c2.png)

## Your Environment

* Director version (System - About): 1.6.0
* Icinga Web 2 version and modules (System - About): 2.6.2
* Icinga 2 version (`icinga2 --version`): 2.9.2
* Operating System and version: SLES 12 SP3
* Webserver, PHP versions: Apache 2.4.23, PHP 7.0.7

**Comment by Thomas-Gelf** [comment]
Please upgrade to v1.6.2 and let me know whether your problem persists, some basket-related issues have been fixed.

**Comment by killepitisch** [comment]
Hi Thomas, just upgraded and tested the new release. Unfortunately still the exact same issue... Is there any log file where I can look up a more detailed output?

**Comment by dbu1986** [comment]
I've had similar issues performing an basket import in a staging environment , dumped from production environment. My guess is that the term "director_datalist" refers to "Data Lists" as the Director-managed objects, but the mentioned Data List does not exist in your Director. For example I'm getting this message:

```
"Failed to load icinga_zone "[MYZONENAME]"
```
... when I try to import a "Service Template" basket in the staging environment where Director doesn't know anything about this Zone yet. So I had to import the Zones first.

Well, the difference between our observations is that creating the basket is working on my side, but not on your's. As your error message refers to Data List with an empty string, maybe one of your Service Templates refers to a Data List with an empty string or something. Could you please try to create a basket with different objects, like even Data Lists or Hostgroups?

**Comment by killepitisch** [comment]
@dbu1986 To my own surprise it is working with all objects other than Service or Host Templates. This wasn't the case when opening this issue for Director 1.6.0. So the release change to 1.6.2 must indeed have fixed something in this regard.
But still Templates cannot be exported with the same error message as mentioned above. I only have one Data List defined within Director for different operating systems. However it does not contain any empty fields.

**Comment by Thomas-Gelf** [comment]
There used to be related errors, but the should have been fixed. Please try again and do not hesitate to open a dedicated issue if the problem persists. The error message above looks weird, eventually please drop that basket and create a new one. In case your template uses a data field referencing a list there are two options: either provide a list with the very same name on target system, in case you want to provide different list values on different systems. Alternatively, add your list to the basket - it should work as expected.
