### ISSUE TITLE
[dev.icinga.com #11510] Impossible to provide empty parameter values to check command

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#175]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11510

**Created by geotek on 2016-04-02 21:37:48 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-04-02 21:37:48 +00:00 (in Redmine)_

---

In the predefined snmp-interface command it is impossible to enter an empty value for the -n check parameter. An empty parameter is necessary to get data from all interfaces independent of their names. If we create a name field "snmp\_interface" and enter no value, the interface name defaults to eth0, which is wrong. If we patch the database and replace the "eth0" with "false" we can see that now "false" is inherited, but the host check inspection still shows "eth0" even this is not shown as inherited value at the device level. Entering "" makes things even worse, because this causes the apostrophes to be escaped. This is really bad because as it is now, we have to manually assign specific interface names to each and every device and checking routers with different interface types is completely impossible.

**Comment by Thomas-Gelf** [comment]
This should be possible with boolean Custom Fields since quite some time. In case it isn't, please let me know
