### ISSUE TITLE
Deploy-button on host-object empties the deployment

### ISSUE THREAD

**Issue by avik78** [Icinga/icingaweb2-module-director#1750]
## Expected Behavior
When editing a host - clicking "Deploy" on top of the Host window should trigger a normal deploy

## Current Behavior
When editing a host - clicking "Deploy" on top of the Host window should trigger a normal deploy.
All objects are still in the director, but the running config is emtpy

If I edit a host - click Store and go to Activity log - and deploy from there, deployment goes fine.

## Possible Solution
To get all back, I need to trigger a new deploy

## Your Environment

* Director version (System - About): Master (2019-01-02)
* Icinga Web 2 version and modules (System - About): 

Icinga Web 2 Version | 2.6.2
director | master
doc | 2.6.2
graphite | 1.0.1
map | 1.0.4

* Icinga 2 version (`icinga2 --version`): r2.10.2-1
* Operating System and version: Ubuntu 16.04.01
* Webserver, PHP versions: apache-2-2.4.18-2ubuntu3.9,  php-7.0.32-0ubuntu0.16.04.1

**Comment by avik78** [comment]
I've investigated this further - and it looks like it might be related to the timezone setting of the browser. For some reason the user who added this, happened to use "Europe/London" as timezone (is that default?) - and the changes got a time stamp in the Activity log 2 hours earlier. 
After we changed it to our local time zone (CET), everything looks like it works as expected

**Comment by Thomas-Gelf** [comment]
Guess this duplicates #1332
