### ISSUE TITLE
Clone Service from Service Set to another Service Set

### ISSUE THREAD

**Issue by cstegm** [Icinga/icingaweb2-module-director#1758]
## Expected Behavior
service is cloned

## Current Behavior
Error Message:
```
Trying to recreate icinga_service ("{"service_set_id":"5","object_name":"ping"}") (DbObject.php:809)
```

## Steps to Reproduce (for bugs)
1. create two service sets A and B
2. create a service in service set A
3. try to clone a service from A to B

## Your Environment

* Director version (System - About): 1.6.0
* Icinga Web 2 version and modules (System - About): 2.6.1

**Comment by Thomas-Gelf** [comment]
Can be reproduced, thanks for reporting this!
