### ISSUE TITLE
[Feature-Request] Customize the order of fields

### ISSUE THREAD

**Issue by rafiwui** [Icinga/icingaweb2-module-director#1761]
## Expected Behavior
Typically I would expect e.g. critical and warning fields to be next to each other, especially when having a lot of fields to fill.
So I want to change the order custom fields are rendered.

## Current Behavior
Fields are ordered alphabetically.
E.g. the check_load command has the arguments `load_wload1`, `load_wload5` und `load_wload15`. Due to the alphabetic ordering is is listet `load_wload1`, `load_wload15`, `load_wload5`. The result is that sometimes the values for `load_wload15` and `load_wload5` are in the wrong order.

## Possible Solution
Have an attribute, like the position for arguments, that will affect the order fields are rendered.

## Environment
* Director version (System - About): master-branch (sometimes a few commits back)
* Icinga Web 2 version and modules (System - About): 2.6.2
* Icinga 2 version (`icinga2 --version`): r2.10.2-1

**Comment by Thomas-Gelf** [comment]
I like this feature request. It would be nice to also be able to group custom fields into different sections. The tricky part: fields can be inherited from multiple templates. So, just allowing one to move fields up or down is not enough, as other fields might be mixed in. We could add a "priorty" field allowing for an arbitrary number. This would require some discipline, but solve this issue - while being less user-friendly.

**Comment by Thomas-Gelf** [comment]
This has been implemented with #1969, is in the current master and will be part of v1.8.0
