### ISSUE TITLE
Can't use custom var in more than one notification configuration (pgsql)

### ISSUE THREAD

**Issue by d3vsl4sh** [Icinga/icingaweb2-module-director#1762]
## Expected Behavior
When a notification template with a custom field is imported by multiple notification configurations it should be possible to set a value for the custom field in each of these.

## Current Behavior
`Storing icinga_notification[vace-sec-8x5-service-notification] failed: SQLSTATE[23505]: Unique violation: 7 ERROR: duplicate key value violates unique constraint "notification_var_search_idx" DETAIL: Key (varname)=(thehive_apikey) already exists., query was: INSERT INTO icinga_notification_var (notification_id, varname, varvalue, format) VALUES (?, ?, ?, ?) {array ( 'id' => '4', 'object_name' => 'vace-sec-8x5-service-notification', 'object_type' => 'apply', 'disabled' => 'n', 'apply_to' => 'service', 'host_id' => NULL, 'service_id' => NULL, 'times_begin' => NULL, 'times_end' => NULL, 'command_id' => NULL, 'notification_interval' => NULL, 'period_id' => NULL, 'zone_id' => NULL, 'assign_filter' => 'service.enable_notifications=true&(host.vars.soc_customer=true|host.vars.soc_realm=true)', )} (DbObject.php:832)`

This behaviour seems to be related to the PostgreSQL database only.

## Possible Solution
In the db schema for pgsql in line [1751](https://github.com/Icinga/icingaweb2-module-director/blob/master/schema/pgsql.sql#L1751) a UNIQUE INDEX for the field varname is created. This unique constraint does not exist in mysql schema.

The unique constraint should either be removed or the index replaced with: `CREATE UNIQUE INDEX notification_var_search_idx ON icinga_notification_var (notification_id, varname);`

## Steps to Reproduce (for bugs)
* Create a notification template with a mandatory custom field
* Use the template in two or more notification apply rules
* Try to set the custom field value in both notifications

## Your Environment
* Director version (System - About): master
* Icinga Web 2 version and modules (System - About): 2.6.2
* Icinga 2 version (`icinga2 --version`): r2.10.2-1
* Operating System and version: Ubuntu 18.04.1 LTS
* Webserver, PHP versions: Apache, PHP 7.2
* DB:  postgresql 10.6-1.pgdg18.04+1

**Comment by Thomas-Gelf** [comment]
Thanks for reporting this, will be fixed!
