### ISSUE TITLE
[dev.icinga.com #11512] Debugging-Function 

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#177]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11512

**Created by essener61 on 2016-04-04 08:40:01 +00:00**

Assignee: _essener61_
Status: _Feedback_ 
Target Version: _(none)_
Last Update: _2016-04-06 06:56:45 +00:00 (in Redmine)_

---

it would be fine to have debbuging-function to find errors like

"SQLSTATE\[HY000\]: General error: 1366 Incorrect string value: '\\xDFen' for column 'property\_value' at row 1, query was: INSERT INTO imported\_property (checksum, property\_name, property\_value, format) VALUES (?, ?, ?, ?)"

Which file is corrupt ?

**Comment by Thomas-Gelf** [comment]
Found no real solution here. Please feel free to re-open this issue or a new one in case you have more concrete ideas on how this could look like.
