### ISSUE TITLE
using icinga director, removed host still exists in hostgroup

### ISSUE THREAD

**Issue by u10t010** [Icinga/icingaweb2-module-director#1771]
## Expected Behavior
After deleting host object in director, it should be deleted also in hostgroup

## Current Behavior
After deleting host object in director, it still remain in hostgroup

## Steps to Reproduce (for bugs)
- icingacli director host create myhost2 --imports generic_host_linux --address x.x.x.x --display_name 'myhost2'
- icingacli director config deploy
- added myhost2 via director gui to an already existing hostgroup with "host.display_name = myhost2"
-  icingacli director config deploy
- icingacli director host delete myhost2
- icingacli director config deploy
- but myhost2 still exists in the hostgroup

## Your Environment
* Director version (System - About): 1.6.0
* Icinga Web 2 version and modules (System - About): 2.6.2
* Icinga 2 version (`icinga2 --version`): r2.10.2-1
* Operating System and version: debian 9
* Webserver, PHP versions: apache2/stable,now 2.4.25-3+deb9u6 amd64, php/stable,now 1:7.0+49 all

**Comment by Thomas-Gelf** [comment]
What do you mean by "still exists in the hostgroup"?

**Comment by u10t010** [comment]
Thank you for your reply.
When reproducing the steps above (e.g. adding myhost2, deploying config, adding myhost2 into hostgroup, deploying config, delete myhost2, deploying config) and at last executing the following command. After all the deleted host "myhost2" still appears  in the remaing host group:
icingacli director hostgroup show hg_test
object HostGroup "hg_test" {
    assign where ........ || host.display_name == "myhost2"

**Comment by Thomas-Gelf** [comment]
If I correctly understood the issue, this is not considered a bug. And honestly, I do now know how we should address this. An apply rule not matching any host is perfectly valid, as fitting hosts might be imported at a later time. Please let me know if you have a different opinion on this.
