### ISSUE TITLE
Extensible sets buttons block access to input below

### ISSUE THREAD

**Issue by lazyfrosch** [Icinga/icingaweb2-module-director#1774]
## Expected Behavior

You should be able to see the full text field when editing a part.

## Current Behavior

The input box is blocked slightly by the buttons in the end.

![bildschirmfoto von 2019-02-06 14-52-15](https://user-images.githubusercontent.com/121874/52345986-d1dfc780-2a1e-11e9-984e-e5e3e7a723ac.png)

## Possible Solution

Move the buttons outside of the input area - to the right.

**Comment by Thomas-Gelf** [comment]
There are no plans to address this right now. Could probably be fixed with some CSS (for the first line only). Pull requests are of course welcome ;-)
