### ISSUE TITLE
zone_id not available in api

### ISSUE THREAD

**Issue by lewtoka** [Icinga/icingaweb2-module-director#1775]
## Expected Behavior
The API should return a zone_id when querying a zone via "/icingaweb2/director/zone?name=Test".

## Current Behavior
At the moments the endpoint only returns:
`{   
    "object_name": "Test",
    "object_type": "external_object"
}`

When creating or updating a host using the API a zone can only be set when specifying a zone_id attribute.

## Possible Solution
Either allow creating/updating a host with a zone(object_name) or return the id when querying zones. 

## Your Environment
Icinga Web 2 Version 2.6.2

**Comment by Thomas-Gelf** [comment]
Please set just `zone` and not `zone_id`, the API wants you to deal with object names - fiddling with IDs makes no fun.

**Comment by lewtoka** [comment]
Alright, thank you, it did work with the zone after all.

**Comment by Thomas-Gelf** [comment]
Glad to hear that!
