### ISSUE TITLE
[dev.icinga.com #11513] Confirmation on delete

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#178]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11513

**Created by mfrosch on 2016-04-04 09:04:17 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-12-19 16:09:09 +00:00 (in Redmine)_

---

Currently all objects I checked just get deleted by clicking the delete button.

Common behavior should be to confirm a deletion :)

---

**Relations**:

* duplicates [#11513](https://dev.icinga.com/issues/11513)

**Comment by Thomas-Gelf** [comment]
I'm rejecting this for now. Doesn't seem to be a big issue - and it might annoy those people who think before they click. Once we have cool new forms in our ipl I could imagine a nice button transforming in some kind of an "Are you sure?"-button after the first click - requiring an immediate second click. (no, no double-click :p).
