### ISSUE TITLE
Importing monitoring service templates??

### ISSUE THREAD

**Issue by bagintz** [Icinga/icingaweb2-module-director#1780]
I am new to icinga2 and it seems great.  One thing I can't figure out is how to get all the nice services that come standard with the monitoring plugin in the director section.  I want to add hosts via director but it seems I have to remake, by hand, all the service templates that come "out of the box" with the monitoring plugin.  Am I doing something wrong or thinking about it in the wrong way?

Thanks!
Bryan

**Comment by Thomas-Gelf** [comment]
All the Check Commands should be imported and provided by the Icinga Director. The only Service Template shipped with Icinga 2 is the `generic-service` Template in `conf.d`.

**Comment by bagintz** [comment]
@Thomas-Gelf the monitoring plugin has a service template right?  But that isn't available in the director, it seems I have to recreate them all, but that doesn't make sense so I figure I am doing something wrong??

**Comment by bagintz** [comment]
Is there a way to add service templates to director via files, so I could copy the templates from the default install or the monitoring plugin?  Again, I'm new so these might be silly questions, I am just trying to understand the ecosystem.

Thanks!

**Comment by B4DschK4Pp** [comment]
Same goes for me. I'm new to Icinga and now came across the check_netscaler command. The project (https://github.com/slauger/check_netscaler) has some examples for Icinga and already a lot of service templates. Now i want to know (and i guess this was the question of @bagintz,too) how to import these templates in director so you don't have to recreate them all manually in director itself.
I already tried to create a templates.conf in /etc/icinga2/conf.d and performed a kickstart with no luck.

Cheers

**Comment by tekgeist-inc** [comment]
Is there _any_ way at all to add service- or host-templates to the director at all?

I actually only want just the generic-host and generic-service templates from the conf.d directory and i'm biting my keyboard out of frustration over not getting it to work properly.

I always end up having to manually create these two basic templates via mouse pushing on the website, as otherwise i literally cannot add any hosts or services at all.
So much for having an unattended setup script..
We need a way of creating templates from the command line.
How about `icingacli director host_template` and `icingacli director service_template` commands with a `create` action, at the very least?

**Comment by steadfasterX** [comment]
I would opt-in here as well. there are many templates and such out there in standard nagios/icinga syntax which I want to import to the director.. but thats not all, when you migrate from a nagios/icinga to icinga2web + director the main goal here is to do the config in the GUI from now on - even for the migrated or to be migrated configs.. which is impossible as the conf files can not be imported to the director.

that one might go in the direction: https://github.com/Icinga/icingaweb2-module-fileshipper/blob/master/doc/04-FileShipping.md while it does not allow to just to copy over standard configs and I haven't had the time to look deeper here.

that one is doing almost the thing: https://github.com/Icinga/icingaweb2-module-director/issues/1683 but still the input files must be manually converted in non-standard conf format - before they can be imported (baskets look like a nice feature btw). I guess the basket one has the most potential here as it might be possible to re-use/copy that code - "just" adapting that to import standard confs...

**Comment by Thomas-Gelf** [comment]
Baskets have been implemented with v1.6.0.

A default import for legacy Templates (Icinga 1.x, Nagios) will probably not happen. We did so in a very few projects for customers who explicitly wanted us to do so, but this results in setups carrying on the old ugly (and insecure) world with $ARG1$:$ARG2$ and similar. This is not something we would like to officially support at all.
