### ISSUE TITLE
Service-Set variables are not being overwritten

### ISSUE THREAD

**Issue by rafiwui** [Icinga/icingaweb2-module-director#1789]
Hi,
since I updated the director from dc48a7e6a03cda495843a0d419143a11525443b6 to 89d4af564e98fa04600a4d9c6d565e903350435b custom variables from service-sets are not being overwritten when edited on hosts. Only the service-set standard variables are called on the check:

1. Overwritten vars:
![overwritevars](https://user-images.githubusercontent.com/9059431/52957088-33922100-3391-11e9-9ae9-0746796d4825.png)

2. Executed check
![image](https://user-images.githubusercontent.com/9059431/52956877-aea70780-3390-11e9-9cbf-7db3501db181.png)

Possibly this happened when #1616 was fixed through commit 85ed54f9329defa5e70fa72e0bb5b5cc45ca0738 because I can see a line being deleted that is about overwritten variables:
![image](https://user-images.githubusercontent.com/9059431/52957336-badf9480-3391-11e9-9613-3e594a0577d8.png)

**EDIT:** It is to mention that this happened only after I rolled out the configuration the first time after pulling the commit. That's why I am pretty sure that some commit must have broken this logic.

**Comment by gasmick** [comment]
same here

**Comment by Thomas-Gelf** [comment]
Sorry for the delay, been busy elsewhere. @rafiwui: thanks a lot for the detailed analysis, you nailed it. Will be fixed immediately.

**Comment by Thomas-Gelf** [comment]
Please give the `support/1.6` branch a try, a related fix has been pushed. Let me know whether it works for you - I'll then schedule v1.6.2.

**Comment by rafiwui** [comment]
Seems to work perfectly fine. Thx for the fix!
But we work with the master branch so I can't tell anything about `support/1.6`. Sorry.

**Comment by Thomas-Gelf** [comment]
Glad to hear that, the fix is now in both branches. Thanks again for your help!
