### ISSUE TITLE
Cannot insert quoted Argument to Command

### ISSUE THREAD

**Issue by redbob365** [Icinga/icingaweb2-module-director#1791]
## Expected Behavior
I wanna create a Command based on a nagios plugin. This command is 
`check_mysql_query -H $address$ -P 3306 -d fog -u fog -p fog -q "select * from images"`
## Current Behavior
I'm not lucky to create a parameter enclosed in quotes. I tried everything, even created a Data Field type string `$fog_query$, so I attached this field to host template, and type there this value "select * from images"

it always gives me this error:
`QUERY CRITICAL: Error with query - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '"select * from images"' at line 1`

## Your Environment
* Director version 1.4.3
* Icinga Web 2 version and modules: 2.6.1
* Icinga 2 version (`icinga2 --version`): r2.10.1-1
* Operating System and version: Ubuntu 16.04.5 LTS
* Webserver, PHP versions:  Apache2 / PHP 7.0.33

**Comment by tdschmidl** [comment]
Hi,
just for clarification - the query "select * from images" is running in mysql-cli and via cli using check_mysql_query fine, right?

I can only reproduce this issue when using quotes two-times like:

```icinga2 ~ # /usr/lib/nagios/plugins/check_mysql_query -c 5 -H localhost -d mysql -q "select User from mysql.user"
QUERY CRITICAL: Is not a numeric - 'icinga2'
icinga2 ~ # /usr/lib/nagios/plugins/check_mysql_query -c 5 -H localhost -d mysql -q "\"select User from mysql.user\""
QUERY CRITICAL: Error with query - You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '"select User from mysql.user"' at line 1```


For data fields you should be able to use $fieldname$ (associate it to the command).

However I was not always successful when using the parameter/datafield in the commands' arugments tab, using them directly in the  "Command" field on first tab was successful then.
Maybe spaces or the * char used in the datafield value breaks some functionality there.

You could also try upgrading Director to a more recent version "v1.6.1" is current release - but please mind that the necessary database migrations are one-way (no downgrade is supported as far as I know)

**Comment by terra-nova** [comment]
Hi,

first of all, check_mysql_query wants a query that returns a numeric scalar value, so a better fit would be something like "select count(*) from images" (returns the number of rows in the images table/view).

Second, in my experience you don't neet to add quoting characters at all, as Icinga will pass the variable content to the check plugin as a single argument, no matter whether or not the value contains whitespace or not. 

Regards

**Comment by redbob365** [comment]
Look, @tdschmidl, I upgraded Director to Master (how to upgrade to v.1.6.1?), so I did this:

1. Created a Data Field with these properties:
`Field Name: fog_query |
Caption: fog_query |
Data type: String`

2. Created a command template;
`Command type: Plugin Check Command | Command name: check_mysqlquery | Command: check_mysql_query | Timeout: 60 | Current zone: master` I assigned `fog_query` on it. 

Preview is here:
```
object CheckCommand "check_mysqlquery" {
    import "plugin-check-command"
    command = [ PluginDir + "/check_mysql_query" ]
    timeout = 1m
    arguments += {
        "-H" = "$address$"
        "-P" = "3306"
        "-d" = "fog"
        "-p" = "fog"
        "-q" = "$fog_query$"
        "-u" = "fog"
    }
}
```

3. Created a service `fog_query` with these preview:
```
template Service "fog_query" {
    check_command = "check_mysqlquery"
    max_check_attempts = "5"
    check_interval = 1m
    retry_interval = 1m
    check_timeout = 10s
    enable_notifications = true
    enable_active_checks = true
    enable_passive_checks = true
    enable_event_handler = true
    enable_flapping = false
    enable_perfdata = true
    command_endpoint = 
}
```

4. Added to Host Template `FOG server` a `fog_query` field with this value:  `select * from images` (without quotes) and set check command as `check_mysqlquery` to it. Look at the preview:
```
template Host "FOG Servers" {
    check_command = "check_mysqlquery"
    max_check_attempts = "10"
    check_interval = 30s
    retry_interval = 10s
    check_timeout = 5s
    enable_notifications = true
    enable_active_checks = true
    enable_passive_checks = true
    enable_event_handler = true
    enable_perfdata = true
    volatile = false
    zone = "master"
    command_endpoint = "srvici-mt.mt.trf1.gov.br"
    vars.fog_query = "select * from images"
    vars.os = "fog"
}
```
but, the plugin output gives me this message:
`QUERY CRITICAL: Error with query - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '"\"select * from images\""' at line 1`

Result: after every tries possible, (no quotes, "...", "\"...\"", "\\\"...\\\"\"") the result is always the same.

**Comment by redbob365** [comment]
@terra-nova, I finally got successful with your hint. Look:
`QUERY OK: 'select count(*) from images' returned 4.000000`

Solved Problem, thanks!
