### ISSUE TITLE
What to do to stop these "Pending Deployment" items?

### ISSUE THREAD

**Issue by redbob365** [Icinga/icingaweb2-module-director#1792]
## Expected Behavior
My Director-module is running properly. 

## Current Behavior
But when I open Deployments tab, I see these "pending tasks" at the image:
[Deployment Tab](https://imgur.com/a/jVbD1C7)
I restarted the server, but no lucky. Is there something I must do to stop them?

## Your Environment
* Director version 1.4.3
* Icinga Web 2 version and modules: 2.6.1
* Icinga 2 version (`icinga2 --version`): r2.10.1-1
* Operating System and version: Ubuntu 16.04.5 LTS
* Webserver, PHP versions:  Apache2 / PHP 7.0.33

**Comment by redbob365** [comment]
I changed Director version, now is `Master` (I couldn't `git checkout v.1.6.1`, so I `git clone https://github.com/Icinga/icingaweb2-module-director.git`.

Now the signal is not rounding anymore, but a `?`

**Comment by Thomas-Gelf** [comment]
Is this still an issue for you? The `?` is telling you that this specific deployment has been shipped to your Icinga node, but for whatever reason Icinga never started with that configuration. In case the next deployment went fine (and this isn't happening all the times), this is nothing you should worry about.

**Comment by redbob365** [comment]
Ok, I understood. So, I can say Director deployments are running fine. Thanks! At least, that rounding icon is gone. Thanks!
