### ISSUE TITLE
Cannot deploy anything after change Director release to Master

### ISSUE THREAD

**Issue by redbob365** [Icinga/icingaweb2-module-director#1793]
I figured out my Director version was 1.4.3, while there is 1.6.1 already. But, I didn't get to upgrade to 1.6.1, I don't know how to `git checkout v1.6.1`.

So I did this:

1. `rm /usr/share/icingaweb2/modules/director -rf`
2. `ICINGAWEB_MODULES=/usr/share/icingaweb2/modules`
3. `DIRECTOR_GIT=https://github.com/Icinga/icingaweb2-module-director.git`
4. `git clone $DIRECTOR_GIT $ICINGAWEB_MODULES/director`

So my Director release now is `Master`. After that, I cannot deploy anything. Instead of it, I see this message:
`Trying to set invalid icinga_host key "flapping_threshold". DB schema change? (DbObject.php:655)`
 

## Your Environment

* Director version Master
* Icinga Web 2 version and modules: 2.6.1
* Icinga 2 version (`icinga2 --version`): r2.10.1-1
* Operating System and version: Ubuntu 16.04.5 LTS
* Webserver, PHP versions:  Apache2 / PHP 7.0.33

**Comment by tdschmidl** [comment]
Just guessing: have you applied the DB schema changes/migrations already (done via kickstart-assistant)
<icinga2 url>/director/dashboard?name=infrastructure#!/director/kickstart
Cave: the DB migrations are one-way, so if you want to go back to an older release, further deployments will/might fail

**Comment by redbob365** [comment]
No, I haven't applied yet... So I searched for instructions, I found [these](https://github.com/Icinga/icingaweb2-module-director/blob/master/doc/03-Automation.md). So I run these commands:
````
icingacli director migration pending --verbose
There are 12 pending migrations
root@srvici-mt:~# icingacli director migration run --verbose
root@srvici-mt:~# icingacli director migration pending --verbose
There are no pending migrations
````
After that, director deployments are all ok!
Thanks!

**Comment by Thomas-Gelf** [comment]
Thanks @tdschmidl!
