### ISSUE TITLE
QueryBasedTable.php(113) error in Activity Log and Depolyments

### ISSUE THREAD

**Issue by mmkiel** [Icinga/icingaweb2-module-director#1798]
## Expected Behavior
Director should display information instead of Oops error in "Activity Log" and "Deployments".

## Current Behavior
Oops, an error occurred!

count(): Parameter must be an array or an object that implements Countable (QueryBasedTable.php:113)

#0 [internal function]: Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(2, 'count(): Parame...', '/usr/share/icin...', 113, Array)
#1 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Web/Table/QueryBasedTable.php(113): count(NULL)
#2 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Html/BaseElement.php(133): dipl\Web\Table\QueryBasedTable->renderContent()
#3 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Html/Html.php(171): dipl\Html\BaseElement->render()
#4 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Html/BaseElement.php(105): dipl\Html\Html->render()
#5 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Html/BaseElement.php(133): dipl\Html\BaseElement->renderContent()
#6 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Html/Html.php(259): dipl\Html\BaseElement->render()
#7 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Zf1/SimpleViewRenderer.php(47): dipl\Html\Html->__toString()
#8 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Zf1/SimpleViewRenderer.php(66): dipl\Zf1\SimpleViewRenderer->render()
#9 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/HelperBroker.php(272): dipl\Zf1\SimpleViewRenderer->postDispatch()
#10 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(518): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
#11 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('deploymentsActi...')
#12 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#13 /usr/share/php/Icinga/Application/Web.php(300): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#14 /usr/share/php/Icinga/Application/webrouter.php(104): Icinga\Application\Web->dispatch()
#15 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...')
#16 {main}

## Steps to Reproduce (for bugs)
New installation of icinga2, icingaweb2 and director module on openSuse Leap 15.

## Your Environment
* Director version (System - About): 1.4.3
* Icinga Web 2 version and modules (System - About): 2.6.2
* Icinga 2 version (`icinga2 --version`):  r2.10.3-1
* Operating System and version: openSUSE Leap 15.0, Kernel 4.12.14-lp150.12.48-default
* Webserver, PHP versions: apache2-2.4.33-lp150.2.6.1.x86_64, php7-7.2.5-lp150.2.15.1.x86_64

**Comment by R-Sommer** [comment]
Your director is pretty old. Would you mind to update to [V1.6.2](https://github.com/Icinga/icingaweb2-module-director/releases/tag/v1.6.2) and retry again?

**Comment by mmkiel** [comment]
Thanks for pointing this out; indeed, you are right. 
I just noticed, among all the icinga2 and icingaweb2 rpm packages, only(!) the director module was installed from the opensuse repository instead of the icinga2 repository and the openSUSE Leap 15.0 repository currently contains only older versions of icinga2 and icingaweb2. 
Since there seems no (current) rpm package for the director, the preferred solution would be to uninstall the old rpm and get a fresh Install from Github?

**Comment by R-Sommer** [comment]
Yeah, getting a fresh install from Github is fine. Please keep in mind to use a released version for production use only.
