### ISSUE TITLE
Import source DB query not saved properly

### ISSUE THREAD

**Issue by ix-dev** [Icinga/icingaweb2-module-director#1803]
## Expected Behavior
When we modify the DB Query of an existing Import source, store the changes and get a message that the ImportSource has been sucessfully updated then we expect that the changes are saved permanently.

## Current Behavior
We obeserved two different behaviors now, both result if the old query being displayed in the DB query field:
* When we switch to another page and switch back again, the old query shows up immediately
* The new DB query is actually executed and we can see the changes as expected after the import has run. Then the DB query is reset to the previously stored DB query, both in the DB query dialog and in the actual query results fetched from DB.

## Steps to Reproduce (for bugs)
* Add an Import source on the Automation configuration page (our SQL query yields 34 columns and has a "Decode as JSON" modifier on the vars field)
* Create a Sync rule with Update Policy "replace" and purge "yes"; no filter set
* Our Import and Sync rules are rather complex and need several seconds to complete
* Create Import and Sync Job with Run interval "60", Import source "Run all imports at once" and Run import set to "yes"
* Change the DB query of the Import source and store it
* Now we frequently see the behavior described above, i.e., the DB query is replaced by the previous version
* We could not verify if the behavior only occurs when a certain job is running while changing the configuration.

## Your Environment
* Director version (System - About): 1.6.2 (master f56634d6030894d553d4a645354b6571023ad426)
* Icinga Web 2 version and modules (System - About): 2.6.2
* Icinga 2 version (`icinga2 --version`): v2.10.3-294-g36fe6be
* Operating System and version: Debian GNU/Linux 8 x86_64
* Webserver, PHP versions: Apache/2.4.10, PHP 5.6.33-0+deb8u1

**Comment by Thomas-Gelf** [comment]
Are you sure that the "query is replace"? In case your sync is being executed with a former set of imported data, this might be a timezone issue with your Web UI being in another timezone than your web or db server. This should have been fixed with #1840, could you please give the current master a try?

Thanks,
Thomas
