### ISSUE TITLE
Apply For and Inherited From are not rendered in Host Services View

### ISSUE THREAD

**Issue by friesoft** [Icinga/icingaweb2-module-director#1804]
## Expected Behavior
"Inherited from " and "Generated from host vars" should be shown in director in the services view of a host.

## Current Behavior
Currently those two sections aren't shown.
magic_apply_for is set to its default: _director_apply_for
Therefore the query for host vars returns empty (/usr/share/icingaweb2/modules/director/application/controllers/HostController.php:146): 
`        if ($applied = $host->vars()->get($db->settings()->magic_apply_for)) {`
=> $host->vars()->get($db->settings()->magic_apply_for)) is empty

If I understood correctly the icinga_host_var table should contain "_director_apply_for" entries. Well it doesn't..
```
MySQL [icingadirector]> select * from icinga_host_var where varname = '_director_apply_for';
Empty set (0.00 sec)
```

## Possible Solution
I guess the _director_apply_for should be rendered into the host?

## Steps to Reproduce (for bugs)
Create a service template with an apply for rule based on a custom variable and restrict it using an apply where rule. The services view of the host doesn't display the applied service.

Sample config:
```
object Host "MeinHost" {
    import "LinuxHost"

    address = "192.168.10.1"
    vars.ssh_user = "icinga"
    vars.components = [ "/usr/bin/httpd" ]
}

apply Service "Component " for (config in host.vars.components) {
    import "Component"

    assign where host.vars.components
    vars.by_ssh_command = "~/libexec/check_procs --ereg-argument-array='" + config + "' --ppid=1"

    import DirectorOverrideTemplate
}

template Service "[Template] ssh-service (active)" {
    max_check_attempts = "3"
    check_interval = 1m
    retry_interval = 1m
    enable_notifications = true
    enable_active_checks = true
    enable_passive_checks = true
    enable_event_handler = true
    enable_perfdata = true
    check_command = "by_ssh"
    command_endpoint = null
    vars.by_ssh_command = "/bin/false"
    vars.by_ssh_logname = "$host.vars.ssh_user$"
    vars.by_ssh_quiet = true
    vars.by_ssh_timeout = 60
}

template Service "Component" {
    import "[Template] ssh-service (active)"
}

template Host "MyHost" {
    check_command = "hostalive"
    max_check_attempts = "3"
    check_interval = 15s
    retry_interval = 10s
    enable_notifications = true
    enable_active_checks = true
    enable_passive_checks = true
    enable_event_handler = true
    enable_perfdata = true
    volatile = false
}

template Host "LinuxHost" {
    import "MyHost"
    groups = [ "linux" ]
    vars.os = "linux"
}
```

## Your Environment
* Director version (System - About): master (b3bd671d90bacd7073f6af9733047ec4053e29f0)
* Icinga Web 2 version and modules (System - About): 2.6.2 (63cb9d728338225833884fda2c312a5a9f431fd6)
* Icinga 2 version (`icinga2 --version`): r2.10.2-1
* Operating System and version: Red Hat 7
* Webserver, PHP versions: Apache 2.4, PHP 7.1

**Comment by widhalmt** [comment]
ref/NC/606431

**Comment by lazyfrosch** [comment]
Part of this is due to #1483 - simple `true` or `is set` is not recognized by the apply resolver.

**Comment by lazyfrosch** [comment]
`magic_apply_for` is a very different feature... It is still experimental and causes me nightmares :laughing:

**Comment by lazyfrosch** [comment]
Quick example where it shows up right now, but still beares no information on `apply For`

```
apply Service "randomness" for (config in host.vars.randomness) {
    import "random"

    assign where "*random*" in host.vars.randomness

    import DirectorOverrideTemplate
}
```

![Bildschirmfoto von 2019-04-30 11-36-26](https://user-images.githubusercontent.com/121874/56953181-38ffaa80-6b3c-11e9-9575-6aaaec0e8b06.png)

**Comment by lazyfrosch** [comment]
What I did not understand: How is this related to inherited from? - This section should only list services that are added to templates of that host.

**Comment by friesoft** [comment]
Inherited from works correctly, I just didn't see it until now that I've tested it :) so The problem are only the apply for rules.

**Comment by lazyfrosch** [comment]
Closing this in favor of #1483 (and others)
