### ISSUE TITLE
Uncaught Error: Wrong parameters for InvalidArgumentException([string $message [, long $code [, Throwable $previous = NULL]]])

### ISSUE THREAD

**Issue by scoggins** [Icinga/icingaweb2-module-director#1810]
I'm getting an error Uncaught Error: Wrong parameters for InvalidArgumentException([string $message [, long $code [, Throwable $previous = NULL]]]) in /usr/share/icingaweb2/modules/director/library/Director/Objects/ImportSource.php:327

When trying to modify an target (guest.hostName) from the VMware import source. 

I believe there should be an sprintf() around the string at this position

https://github.com/Icinga/icingaweb2-module-director/blob/70dfc9dae98c6638259810156dd40ad3814a5882/library/Director/Objects/ImportSource.php#L325-L328

**Comment by Thomas-Gelf** [comment]
You're right, thanks for reporting this!
