### ISSUE TITLE
Schema-Migration failed after upgrade to v.1.6.2

### ISSUE THREAD

**Issue by markus-radtke** [Icinga/icingaweb2-module-director#1826]
Hey, after upgrading to v1.6.2 two of the schema-migrationscipts failed with following error:

`Migration 156 failed (SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'ido' for key 'object_name') while running ALTER TABLE icinga_command DROP INDEX object_name, ADD UNIQUE INDEX object_name (object_name)`

## Your Environment
* Director version (System - About): 1.6.2
* Icinga Web 2 version and modules (System - About): 2.6.2
* Icinga 2 version (`icinga2 --version`):  r2.10.4-1
* Operating System and version: Debian 9 fully patched
* Webserver, PHP versions: Apache2

**Comment by Thomas-Gelf** [comment]
Please show the output of:

```sql
SELECT * FROM icinga_command WHERE object_name = 'ido'\G
```

**Comment by markus-radtke** [comment]
Hey Thomas, you are quite fast, awesome!

Here is the needed output:

`MariaDB [director]> SELECT * FROM icinga_command WHERE object_name = 'ido'\G
*************************** 1. row ***************************
             id: 1
    object_name: ido
    object_type: external_object
       disabled: n
methods_execute: PluginCheck
        command: NULL
        timeout: 60
        zone_id: NULL
*************************** 2. row ***************************
             id: 215
    object_name: ido
    object_type: external_object
       disabled: n
methods_execute: PluginCheck
        command: NULL
        timeout: 60
        zone_id: NULL
2 rows in set (0.00 sec)
`

**Comment by Thomas-Gelf** [comment]
Interesting. The upgrade will make sure that this doesn't happen again. To fix this please try:

```sql
DELETE FROM icinga_command WHERE id = 1;
```

If this gives an error this would mean that id=1 is still in use. Don't worry, try the other ID (215). If one of them succeeds please try to apply the migration again. In case both fail let me know, we'll find a solution.

**Comment by markus-radtke** [comment]
Hi, it seems that there are lots of duplicate command entries... I will clean up and come back to you. I don't know why there are so much duplicate commands...

**Comment by Thomas-Gelf** [comment]
@markus-radtke: don't worry about deleting too many of them. Create an SQL-dump first if you want to be on the safe side. Delete only those with `object_type = 'external_object'`, as all missing ones will be re-created when you re-trigger the Kickstart Wizard from the Director Infrastructure Dashboard afterwards. When affected commands are in use, your query will be rejected.

**Comment by markus-radtke** [comment]
@Thomas-Gelf 
first of all thanks for your fast help! I've deleted all related entries by using 
`DELETE ignore FROM icinga_command WHERE object_type = 'external_object';`

After that I was able to run the migration scripts. Then I've started the Kickstart Wizard and now everything is fine.

Hope to see you again at the next OSMC!
