### ISSUE TITLE
CheckCommands `dummy` and `passive` will be reimported in every kickstart run

### ISSUE THREAD

**Issue by widhalmt** [Icinga/icingaweb2-module-director#1829]
Hi,

On older installations of Director with Icinga 2 where an older version of the ITL was imported, the CheckCommands `dummy` and `passive` should be changed during kickstart but they aren't.

This leads to a situation where every kickstart run logs that the commands were changed in the activity log.

It seems there is a problem with removing the `arguments` part from the database.

I had this with an older but updated setup at a customers, @lazyfrosch reported it too. It sill occurs with the ITL from Icinga 2 2.10.4 and Director 1.6.2.

Cheers,
Thomas

ref/NC/610247

**Comment by lazyfrosch** [comment]
The setting part of `IcingaArguments` is not implemented correctly, it just forgets all arguments when set to "empty" instead of marking them for removal.

Fix will be included in 1.7.
