### ISSUE TITLE
[dev.icinga.com #11525] Cannot remove service from host, service became service template

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#183]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11525

**Created by las68 on 2016-04-05 09:43:32 +00:00**

Assignee: _(none)_
Status: _Resolved_  (closed on _2016-04-07 23:14:56 +00:00_)
Target Version: _(none)_
Last Update: _2016-04-07 23:14:56 +00:00 (in Redmine)_

---

I created service 'Check HP Proliant health' based on check\_hpasm command and assigned it to host.

I cannot deploy this config successfully and I decide to delete service.
But button 'Delete'is not active for service.

1. service for some unknown reason became service template (Services / Preview / Config preview: ... )

template Service "Check HP Proliant health" {
check\_command = "check\_hpasm"
enable\_notifications = true
enable\_active\_checks = true
enable\_passive\_checks = true
enable\_event\_handler = true
enable\_perfdata = false
zone = "icinga2.sibmg.local"
}

2. and I got an error when deploying, probably for some misconfiguration:

information/ConfigItem: Committing config items
information/ApiListener: My API identity: icinga2.sibmg.local
critical/config: Error: Validation failed for object 'check\_hpasm' of type 'CheckCommand'; Attribute 'zone': Object 'director-global' of type 'Zone' does not exist.
Location: in /var/lib/icinga2/api/packages/director/icinga2.sibmg.local-1459849226-17/zones.d/director-global/commands.conf: 3:1-3:33
/var/lib/icinga2/api/packages/director/icinga2.sibmg.local-1459849226-17/zones.d/director-global/commands.conf(1): library "methods"
/var/lib/icinga2/api/packages/director/icinga2.sibmg.local-1459849226-17/zones.d/director-global/commands.conf(2):
/var/lib/icinga2/api/packages/director/icinga2.sibmg.local-1459849226-17/zones.d/director-global/commands.conf(3): object CheckCommand "check\_hpasm" {
<sup></sup>^
/var/lib/icinga2/api/packages/director/icinga2.sibmg.local-1459849226-17/zones.d/director-global/commands.conf(4): execute = PluginCheck
/var/lib/icinga2/api/packages/director/icinga2.sibmg.local-1459849226-17/zones.d/director-global/commands.conf(5): command = \[ PluginDir + "/check\_hpasm" \]

critical/config: 1 error

check\_hpasm exist in PluginDir

---

**Relations**:

* relates [#11547](https://dev.icinga.com/issues/11547)

**Comment by Fiiti** [comment]
Till Today nothing happens about this. Neither any hint in the Documentation (imho) nor the director itself adding them.
Would it not make sense to add these cofig generally and automatically?

So long,
Fiiti

**Comment by Thomas-Gelf** [comment]
> Neither any hint in the Documentation (imho) [..]

@Fiiti: this is the very first step in the [Getting Started](https://github.com/Icinga/icingaweb2-module-director/blob/master/doc/04-Getting-started.md) section of our documentation

> [..] nor the director itself adding them.

Zones are a security feature in Icinga 2. Therefore adding them for a single Icinga node through the API would work, but in a distributed environment it doesn't behave like you might expect. Manually adding that zone is usually only required for your core (master/satellite) nodes. For your Agents you should try to use the sample config/scripts provided by the Director - you'll find that zone in all of them.

Cheers,
Thomas
