### ISSUE TITLE
MySQL 8.0 compatibility for sql_mode

### ISSUE THREAD

**Issue by lazyfrosch** [Icinga/icingaweb2-module-director#1842]
It seems like MySQL 8.0 changed some requirements for `sql_mode`, which we set for migrations:

```
# icingacli director migration run
ERROR: RuntimeException in /usr/share/icingaweb2/modules/director/library/Director/Db/Migration.php:60 with message:
Migration 0 failed (SQLSTATE[42000]: Syntax error or access violation: 1231 Variable 'sql_mode' can't be set to the value of 'NO_AUTO_CREATE_USER') while running --
```

**Comment by lazyfrosch** [comment]
I guess we should just drop it.

It was deprecated in 5.7 and apparently removed now:

https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sqlmode_no_auto_create_user

> It is preferable to create MySQL accounts with CREATE USER rather than GRANT. NO_AUTO_CREATE_USER is deprecated and the default SQL mode includes NO_AUTO_CREATE_USER. Assignments to sql_mode that change the NO_AUTO_CREATE_USER mode state produce a warning, except assignments that set sql_mode to DEFAULT. NO_AUTO_CREATE_USER will be removed in a future MySQL release, at which point its effect will be enabled at all times (GRANT will not create accounts).

**Comment by Thomas-Gelf** [comment]
@lazyfrosch: dropping this is fine, we did so in other modules too. However, this has been removed from Director in 764f6cc - eventually you're using an Icinga Web 2 module where this is still a thing?

**Comment by lazyfrosch** [comment]
Oh you are right, my bad. I was testing migrations and began with the 1.5.0 schema...
