### ISSUE TITLE
Allow to add association of fields with external command to basket

### ISSUE THREAD

**Issue by widhalmt** [Icinga/icingaweb2-module-director#1854]
Hi,

It would be good to have the option to add the association of fields with external commands to a basket.

This seems not to be part of "command definitions" right now.

Cheers,
Thomas

**Comment by widhalmt** [comment]
ref/NC/613501

**Comment by Thomas-Gelf** [comment]
Has been implemented with cc15cae, and finally works now after fixing a related filtering issue.
