### ISSUE TITLE
Error while creating snapshot in the Baskets

### ISSUE THREAD

**Issue by afeefghannam89** [Icinga/icingaweb2-module-director#1856]
## Expected Behavior

I want to create a snapshot from the basket in Director including my local template. Unfortunately i receive the following error : 

Uncaught Error: Call to a member function export() on null in /usr/share/icingaweb2/modules/director/library/Director/DirectorObject/Automation/BasketSnapshot.php:449
Stack trace:
#0 /usr/share/icingaweb2/modules/director/library/Director/DirectorObject/Automation/BasketSnapshot.php(407): Icinga\Module\Director\DirectorObject\Automation\BasketSnapshot->addByIdentifier('HostTemplate', 'Generic Host')
#1 /usr/share/icingaweb2/modules/director/library/Director/DirectorObject/Automation/BasketSnapshot.php(139): Icinga\Module\Director\DirectorObject\Automation\BasketSnapshot->addByIdentifiers('HostTemplate', Array)
#2 /usr/share/icingaweb2/modules/director/library/Director/DirectorObject/Automation/BasketSnapshot.php(108): Icinga\Module\Director\DirectorObject\Automation\BasketSnapshot->addObjectsChosenByBasket(Object(Icinga\Module\Director\DirectorObject\Automation\Basket))
#3 /usr/share/icingaweb2/modules/director/application/forms/BasketCreateSnapshotForm.php(33): Icinga\Module\Director\DirectorObject\Automatio
     

MariaDB [director]> SELECT * FROM director_basket \G
*************************** 1. row ***************************
       uuid: ��Ó�h�$VX2��]"
basket_name: test123
 owner_type: user
owner_value: icingaadmin
    objects: {"HostTemplate":["Generic Host","Linux Icinga Agent","foreman_host"],"ServiceTemplate":["Generic Service","Agent-based Service","Agent RAM Service","Agent Disk Service","Agent SSH Service","Agent NTP Service","Agent Icinga Service","Agent CPU Service","linux_disk","generic-service"],"ServiceSet":["Icinga Agent Linux Basic Services"],"DataList":["Operation Systems","Check Execute"]}
1 row in set (0.00 sec)

* Director version (System - About): 1.6.2
* Icinga Web 2 version and modules (System - About): 
icinga web 2 : 2.6.3
monitoring : 2.6.3
* Icinga 2 version (`icinga2 --version`):
icinga2 - The Icinga 2 network monitoring daemon (version: v2.10.4-610-g37de1a9)
* Operating System and version:
CentOS 7
* Webserver, PHP versions:

**Comment by Thomas-Gelf** [comment]
Thanks for reporting this, #1940 helped me to better understand the problem. Will close this as a duplicate
