### ISSUE TITLE
Notification Interval ist set to 0s but should be 0

### ISSUE THREAD

**Issue by emtie** [Icinga/icingaweb2-module-director#1857]
## Expected Behavior
I have created a notification template in icingaweb2-module-director. Within this template I have definied a notification intervall of "0" (without ""). In my understandig that should generate only a single notification Mail. But icinga keeps on sending mails every minute. I think this is because the template file generated from icinga director has interval = 0s in it. "s" is too much. 

So the suggestion would be that the director does not translate the 0 in the webfrontend (Field notification interval) to 0s in the configuration file

## Current Behavior

![notification1](https://user-images.githubusercontent.com/11004719/57103798-0665d580-6d27-11e9-94da-cc6bda517ae8.JPG)
this notification generates this:
![notification2](https://user-images.githubusercontent.com/11004719/57103824-141b5b00-6d27-11e9-8e73-c5c8dd934bdd.JPG)
but instead it should look like this:
![notification3](https://user-images.githubusercontent.com/11004719/57103899-44fb9000-6d27-11e9-8971-681726150c15.JPG)

## Your Environment

* Director version (System - About): 1.6.2
* Icinga Web 2 version and modules (System - About): 2.6.3
* Icinga 2 version (`icinga2 --version`): (version: r2.10.4-1)
* Operating System and version:
System information:
  Platform: Ubuntu
  Platform version: 18.04.2 LTS (Bionic Beaver)
  Kernel: Linux
  Kernel version: 4.15.0-48-generic
  Architecture: x86_64
* Webserver, PHP versions:
Server version: Apache/2.4.29 (Ubuntu)
PHP 7.2.17-0ubuntu0.18.04.1

**Comment by dnsmichi** [comment]
Hi,

the Icinga config compiler will convert duration literals such as 1m, 30s and even 0s to numbers. You can test that by running the config validation (or deploy the configuration from the Director), and run `icinga2 object list --type Notification --name ...`.

Internally, the `interval` attribute is a floating point number (double) and just taken into account as expected. There's no difference with `0s` or `0` in this regard.

On a more technical level, our lexer already interpretes this into numbers. That is why `object list` doesn't know about the duration literal anymore and just prints the raw number.

https://github.com/Icinga/icinga2/blob/master/lib/config/config_lexer.ll#L206

Cheers,
Michael

**Comment by emtie** [comment]
Hi dnsmichi,

thank you for the quick reply. But then I don't understand why I keep getting notifications over and over again instead of once. I somewhere read that it might have todo with 0s interpreted in a wrong way?

Are there other ways to get only notified once when a new status occurs?

cu emtie

**Comment by dnsmichi** [comment]
Verify that `volatile` is set to false.
