### ISSUE TITLE
Exception on clicking a Host in Hosts based on template

### ISSUE THREAD

**Issue by friesoft** [Icinga/icingaweb2-module-director#1864]
## Expected Behavior
Clicking a host in the list of "Hosts based on template xyz" should link to the host.

## Current Behavior
Currently the link to a host (in this example replaced by the string "HOSTNAME") from the list (/icingaweb2/director/hosttemplate/objects?name=template-linux&inheritance=direct) leads to an uncaught exception:
> Uncaught Error: Class 'Icinga\Module\Director\Dashboard\HOSTNAMEDashboard' not found in /usr/share/icingaweb2/modules/director/library/Director/Dashboard/Dashboard.php:46
> Stack trace:
> #0 /usr/share/icingaweb2/modules/director/application/controllers/DashboardController.php(42): Icinga\Module\Director\Dashboard\Dashboard::loadByName('HOSTNAME', Object(Icinga\Module\Director\Db))
> #1 /usr/share/icingaweb2/modules/director/application/controllers/IndexController.php(33): Icinga\Module\Director\Controllers\DashboardController->indexAction()
> #2 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Director\Controllers\IndexController->indexAction()
> #3 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('indexAction')
> #4 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
> #5 /usr/share/php/Icinga/Application/Web.php(300): Zend_Control
> 
> #0 [internal function]: Icinga\Application\Web->Icinga\Application\{closure}()
> #1 {main}

A link like this is generated:
`href="/icingaweb2/director/?name=HOSTNAME"`

## Possible Solution
Link needs to be fixed, linking to `href="/icingaweb2/director/host?name=HOSTNAME"`

## Steps to Reproduce (for bugs)
Host => Host Templates => Click on a host template with direct objects => Click on a host from the list => Exception

## Your Environment
* Director version (System - About): 644853f7a0838d13d361e5c35829762fe9f87763
* Icinga Web 2 version and modules (System - About): 2.6.2
* Icinga 2 version (`icinga2 --version`): r2.10.4-1
* Operating System and version: RHEL7
* Webserver, PHP versions: Apache 2.4, PHP 7.1

**Comment by friesoft** [comment]
Similar thing happens when clicking on an apply rule in the Service Templates -> Apply Rules list - it leads to the director startpage because the generated url is wrong:
`/icingaweb2/director/servicetemplate/applyrules?name=MYTEMPLATE&inheritance=direct`

Wrong link:
`href="/icingaweb2/director//edit?id=1092"`

**Comment by Thomas-Gelf** [comment]
Can be reproduced thanks for reporting this!

**Comment by friesoft** [comment]
I'm already preparing a pullrequest - but I guess you are faster :laughing:

**Comment by Thomas-Gelf** [comment]
Cool, then I'll do nothing :beers:

**Comment by friesoft** [comment]
I hope this is correct :) It's working for me at least :laughing:

**Comment by Thomas-Gelf** [comment]
Looks good to me. Wanted to test it with a special table and stumbled over another (new) bug. Give me some minute to clean that one up, I'll merge your's afterwards. Thanks a lot!
