### ISSUE TITLE
Exception in Notification Template Usage of Apply Rules

### ISSUE THREAD

**Issue by friesoft** [Icinga/icingaweb2-module-director#1867]
## Expected Behavior
Clicking on the usage of notification apply rules should show the list of apply rules

## Current Behavior
Using this url: `/icingaweb2/director/notificationtemplate/usage?name=TEMPLATENAME`
The templates needs to have apply rules (in my case direct) => Clicking on the usage of the apply rules leads to an exception on this url: `/icingaweb2/director/notificationtemplate/applyrules?name=TEMPLATENAME&inheritance=direct`

> Oops, an error occurred!
> SQLSTATE[42S22]: Column not found: 1054 Unknown column 'o.apply_for' in 'field list', query was: SELECT o.id, o.object_name, o.disabled, o.assign_filter, o.apply_for FROM icinga_notification AS o WHERE (object_type = 'apply') AND (EXISTS (SELECT (1) AS e FROM icinga_notification_inheritance AS oi WHERE (oi.notification_id = o.id) AND (oi.parent_notification_id = 1))) ORDER BY o.object_name ASC LIMIT 25 (Pdo.php:225)
> #0 /usr/share/icingaweb2/library/vendor/Zend/Db/Statement.php(297): Zend_Db_Statement_Pdo->_execute(Array)
> #1 /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Abstract.php(470): Zend_Db_Statement->execute(Array)
> #2 /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT o.id, o....', Array)
> #3 /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Abstract.php(725): Zend_Db_Adapter_Pdo_Abstract->query(Object(Zend_Db_Select), Array)
> #4 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Web/Table/ZfQueryBasedTable.php(121): Zend_Db_Adapter_Abstract->fetchAll(Object(Zend_Db_Select))
> #5 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Web/Table/QueryBasedTable.php(209): dipl\Web\Table\ZfQueryBasedTable->fetchQueryRows()
> #6 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Web/Table/QueryBasedTable.php(148): dipl\Web\Table\QueryBasedTable->fetch()
> #7 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Web/Table/QueryBasedTable.php(112): dipl\Web\Table\QueryBasedTable->fetchRows()
> #8 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Html/BaseHtmlElement.php(198): dipl\Web\Table\QueryBasedTable->renderContent()
> #9 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Html/HtmlDocument.php(193): dipl\Html\BaseHtmlElement->renderUnwrapped()
> #10 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Html/HtmlDocument.php(250): dipl\Html\HtmlDocument->render()
> #11 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Html/BaseHtmlElement.php(175): dipl\Html\HtmlDocument->renderUnwrapped()
> #12 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Html/BaseHtmlElement.php(198): dipl\Html\BaseHtmlElement->renderContent()
> #13 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Html/HtmlDocument.php(193): dipl\Html\BaseHtmlElement->renderUnwrapped()
> #14 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Html/HtmlDocument.php(262): dipl\Html\HtmlDocument->render()
> #15 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Zf1/SimpleViewRenderer.php(65): dipl\Html\HtmlDocument->__toString()
> #16 /usr/share/icingaweb2/modules/director/library/vendor/ipl/Zf1/SimpleViewRenderer.php(104): dipl\Zf1\SimpleViewRenderer->render()
> #17 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/HelperBroker.php(272): dipl\Zf1\SimpleViewRenderer->postDispatch()
> #18 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(518): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
> #19 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('applyrulesActio...')
> #20 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
> #21 /usr/share/php/Icinga/Application/Web.php(300): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
> #22 /usr/share/php/Icinga/Application/webrouter.php(104): Icinga\Application\Web->dispatch()
> #23 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...')
> #24 {main}

## Possible Solution
library/Director/Web/Table/ApplyRulesTable.php
=> looks like apply_for doesn't exist anymore in the table icinga_notification

## Steps to Reproduce (for bugs)
Open a notification template, click on the usage number of direct apply rules => Exception 

## Your Environment
* Director version (System - About): master (06.05.2019)
* Icinga Web 2 version and modules (System - About): 2.6.2
* Icinga 2 version (`icinga2 --version`): r2.10.4-1
* Operating System and version: RHEL7
* Webserver, PHP versions: Apache 2.4, PHP 7.1

**Comment by friesoft** [comment]
@Thomas-Gelf Guess you were faster in #1866 :laughing:

**Comment by Thomas-Gelf** [comment]
Thank you anyways!
