### ISSUE TITLE
Allow custom Host Attributes in Dependency Apply rules

### ISSUE THREAD

**Issue by ix-dev** [Icinga/icingaweb2-module-director#1870]
## Expected Behavior

We want to configure a custom host attribute as the "Parent Host" in a Dependency Apply rule using the Icinga Director.

This feature is described in the [Icinga2 Documentation](https://icinga.com/docs/icinga2/latest/doc/03-monitoring-basics/#apply-dependencies-based-on-custom-attributes).

The rendered configuration should look like this:
```
apply Dependency "vm-host-to-parent-master" to Host {
  parent_host_name = host.vars.vm_parent
  assign where "generic-vm" in host.templates
}
```

## Current Behavior

The Director only supports host names in the Parent Host field. When we try to configure a variable in the Parent Host field we get the following error:
```
Failed to load icinga_host "host.vars.vm_parent" (DbObject.php:628)
```
Of course a host object with this name does not exist. The Director expects that the configured value is the `object_name` of a host object, not a host attribute.

## Possible Solution

The Director should accept custom attributes for the `parent_host_name` configuration option.

## Your Environment

* Director version (System - About): 1.6.2
* Icinga Web 2 version and modules (System - About): 2.6.2
* Icinga 2 version (`icinga2 --version`): v2.10.3-294-g36fe6be
* Operating System and version: Debian GNU/Linux 9
* Webserver, PHP versions: Apache/2.4.25 (Debian)

**Comment by widhalmt** [comment]
ref/NC/614707

**Comment by Thomas-Gelf** [comment]
This is what the form looks like:

![dependency_based_on_var_form](https://user-images.githubusercontent.com/553008/60808148-df44dd80-a187-11e9-8332-7eb455fda9d4.png)

Rendering example:

![dependency_based_on_var_rendered](https://user-images.githubusercontent.com/553008/60808186-f1268080-a187-11e9-8fef-1e2c0a14f5dc.png)
