### ISSUE TITLE
[Feature-Request] new datafield type with hidden entries (e.g. passwords)

### ISSUE THREAD

**Issue by n0braist** [Icinga/icingaweb2-module-director#1872]
A nice feature would be a datafield with the possibility to hide the added data (in director not webui itself) like for passwords or usernames .

The would be a huge improvement for security reasons, because of using icinga director with multiple users which shouldn't see all information from other users which added such sensitive data

**Comment by carraroj** [comment]
ref/NC/617905

**Comment by Thomas-Gelf** [comment]
I tried to tackle this in various ways. It might sound easy - but is quite complex. After different attempts I settled with the following:

* the `String` data type gets a new setting, `visibility` can now be either `visible` or `hidden`
* we introduce a new dedicated form element type...
* ...and a dedicated view renderer

Requirements that should be fulfilled:

 * the current password should not be rendered to the HTML page (unless the user decides to change it)
 * it must be possible to visually distinct whether a password has been set
 * it should be impossible to "see" the length of the stored password
 * a changed password must be persisted
 * forms might be subject to multiple submissions in case other fields fail. If the user changed the password during the first submission attempt, the new string should not be lost.
 * all this must happen within the bounds of ZF1 form elements and related view helpers. This means that there is no related context available - and we do not know whether the form has been submitted and whether the current values have been populated from DB

In addition to this, a user with `director/inspect` or `director/showconfig` permissions is obviously still able to see those passwords. You have to revoke them in case you want to hide all your sensitive data.

**Comment by Thomas-Gelf** [comment]
A field configured this way:

![director_hidden_string_settings](https://user-images.githubusercontent.com/553008/60965403-092c0a80-a316-11e9-9b58-bdce668debdb.png)

...now looks like this:

![director_hidden_string](https://user-images.githubusercontent.com/553008/60965440-252fac00-a316-11e9-820f-a3732c2cde7c.png)

...and fulfills all requirements listed above.
