### ISSUE TITLE
[Feature-Request] Forced sync

### ISSUE THREAD

**Issue by manfredw** [Icinga/icingaweb2-module-director#1877]
## Expected Behavior
Possibility to force a sync after changing sync properties even when source data unchanged.

## Current Behavior
Sync rule will be only executed after changes on source data, but ignores changes in sync properties.

**Comment by lazyfrosch** [comment]
As discussed on the forum, this is neither a bug nor a feature request:
https://community.icinga.com/t/resync-after-changing-sync-properties/1274/10
