### ISSUE TITLE
How to impliment by_ssh commands in Director

### ISSUE THREAD

**Issue by sol1-matt** [Icinga/icingaweb2-module-director#1884]
## Expected Behavior
I'm struggling to implement checks by_ssh through director, imparticular the by_ssh_arguments. Issue [1356](https://github.com/Icinga/icingaweb2-module-director/issues/1356) seems to suggest it is possible to implement.

As in 1356 the by_ssh command is imported. But I can't see how to create the expected structure of by_ssh_arguments, to create a by_ssh command outside director I'd have arguments configured like this
```
        vars.by_ssh_arguments = {
                "-w" = {
                        value = "$disk_wfree$"
                        description = "Exit with WARNING status if less than INTEGER units of disk are free or Exit with WARNING status if less than PERCENT of disk space is free"
                        required = true
                        order = -3
                }

                "-c" = {
                        value = "$disk_cfree$"
                        description = "Exit with CRITICAL status if less than INTEGER units of disk are free or Exit with CRITCAL status if less than PERCENT of disk space is free"
                        required = true
                        order = -3
                }

     }
```
with the end result of the command being run is (from the icinga icinga2.log)
`arguments: '/usr/lib/nagios/plugins/check_by_ssh' '-C' ''/usr/bin/sudo' '/usr/lib/nagios/plugins/check_disk' '-c' '10000' '-w' '20000'  '/'' '-H' '192.168.0.123' '-i' '/var/lib/nagios/.ssh/id_rsa' '-l' 'checker' '-o' 'StrictHostKeyChecking=no' '-t' '60'
`

The closest I could come to the above structure in director is a Data field of type Datalist with a target data type of Array.

A preview of the command using this variable produces this which isn't what is I'm after.

```
template CheckCommand "disk-by-ssh" {
    import "plugin-check-command"
    import "by_ssh"

    vars.by_ssh_arguments = [ "-c", "-w" ]
    vars.by_ssh_command = [ "/usr/bin/sudo", "/var/lib/nagios/plugins/check_disk" ]
}
```
I could do a normal array but that would mean building the key value pairs into a single key in director including the command part, by_ssh_command above.

And if I could create the above structure in director would it work with the limitation director has with by_ssh where it is Unable to fetch function body through API.

## Current Behavior
Is it possible to create a by_ssh command in director that has multiple key/value pairs being passed as a value of a parent key?

## Your Environment

* Director version (System - About): 1.6.2
* Icinga Web 2 version and modules (System - About): 2.6.2
* Icinga 2 version (`icinga2 --version`): r2.10.3-1
* Operating System and version: Ubuntu 18.04.2
* Webserver, PHP versions: Apache/2.4.29 PHP/7.2.17

**Comment by sol1-matt** [comment]
I tried to implement the check command in director like this

Add a template with a variable for -C

    template CheckCommand "by-ssh" {
        import "plugin-check-command"
        import "by_ssh"
    
        arguments += {
            "-C" = "$by_ssh_command$"
        }
    }

Add a template to check disks with the parameters 

    template CheckCommand "disk-by-ssh" {
        import "plugin-check-command"
        import "by-ssh"
    
        vars.by_ssh_command = [
            "/usr/bin/sudo",
            "/var/lib/nagios/plugins/check_disk",
            "-c",
            "$disk-cfree$",
            "-w",
            "$disk-wfree$",
            "-p",
            "$disk_partitions$"
        ]
        vars.disk_cfree = "10%"
        vars.disk_wfree = "20%"
    }

This didn't help, I get a error from the Plugin Output

    check_by_ssh: No remotecmd

**Comment by XnS** [comment]
There's already an external command called `by_ssh` which you can use. You just need some kind of basic ssh checks which configures your ssh options (username, port, actual command and so on) and a check for each service you want to check over ssh. This service checks inherits the basic ssh check.

For example:

#### Generic check which is inherited by all checks run over ssh.

Field configuration:
- by_ssh_command
- by_ssh_logname
- by_ssh_options

Check definition:
```
template Service "Basic Check by SSH" {
    check_command = "by_ssh"
    max_check_attempts = "3"
    check_interval = 5m
    retry_interval = 1m
    check_timeout = 15s
    vars.by_ssh_logname = "nagios"
    vars.by_ssh_options = "StrictHostKeyChecking=no"
}
```

#### And the actual check like this:
Field configuration:
- value_critical
- value_warning

Check definition:
```
template Service "Disk Check by SSH" {
    import "Basic Check by SSH"

    vars.by_ssh_command = "/usr/lib/nagios/plugins/check_disk -L -e -X nsfs -w $value_warning$ -c $value_critical$"
    vars.disk_errors_only = true
    vars.disk_stat_remote_fs = true
    vars.grafana_graph_config = "disk"
    vars.value_critical = "7%"
    vars.value_warning = "13%"
}
```

**Comment by sol1-matt** [comment]
Thanks XnS, this helped.

For the benefit of others like me who had trouble implementing the by_ssh external command the steps I used to get this working are 

- On the external command `by_ssh` add the fields you will need for the ssh parameters
- Add a new **string** field in define data fields called `by_ssh_command` _(the array I had above doesn't work)_
- Add a command template `by-ssh-director`, the preview will look like this. _Note adding `$by_ssh_command$` argument here won't work_ 
```
template CheckCommand "by-ssh-director" {
    import "plugin-check-command"
    import "by_ssh"

    vars.by_ssh_identity = "/var/lib/nagios/.ssh/id_rsa"
    vars.by_ssh_logname = "nagioschecker"
    vars.by_ssh_options = "StrictHostKeyChecking=no"
    vars.by_ssh_timeout = "60"
}
```
- add a command that includes 
-- a argument `-C` with a value `$by_ssh_command$`
-- a field `$by_ssh_command$`
-- set the `$by_ssh_command$` value to the command with switches that will be run on the remote host as XnS has done
-- any other values you need for the switches which will mean another trip to define data fields
you should end up with something like this
```
object CheckCommand "disk-ssh" {
    import "icinga-check-command"
    import "by-ssh-director"

    arguments += {
        "-C" = "$by_ssh_command$"
    }
    vars.by_ssh_command = "/usr/bin/sudo /var/lib/nagios/plugins/check_disk -w $disk_wfree$ -c $disk_cfree$  -p $disk_partitions$ "
    vars.disk_cfree = "10%"
    vars.disk_wfree = "20%"
}
```
This command can now be used as you would normally in a director service with seperate fields for each switch value.


Note: I can't see any way of dynamically adding switches depending on the value being set or not, so you could end up with multiple commands for the same thing with different switches in the `$by_ssh_command$` value.
