### ISSUE TITLE
Datalist permissions doesn't show entry 

### ISSUE THREAD

**Issue by mkayontour** [Icinga/icingaweb2-module-director#1885]
Hi, 

Entries in datalists can be assigned to a specific role in the director. 

## Expected Behavior
Expected that if a user is part of a role which is allowed to see a specific entry in an datalist to see the entry.

## Current Behavior
The entry is not shown to the user.

## Steps to Reproduce (for bugs)
1. Create a role and assign it to a user. (permissions are (* allow everything ))
2. Create a datalist with two values, one value is assigned to the role previously created. 
![image](https://user-images.githubusercontent.com/7584938/58566388-ded43100-8230-11e9-9e20-28aea16e5bc8.png)

3. Logout and Login again as the user with the role and try to select the value in the datalist. 
![image](https://user-images.githubusercontent.com/7584938/58566459-ff03f000-8230-11e9-9435-38324c166ca5.png)

## Your Environment

* Director version (System - About): 1.6.2
* Icinga Web 2 version and modules (System - About): 2.6.3
* Icinga 2 version (`icinga2 --version`): 2.10.5
* Operating System and version: Centos 7
* Webserver, PHP versions: 2.4.6 / Php 7.1.8

**Comment by widhalmt** [comment]
ref/NC/617339
