### ISSUE TITLE
hostadress max 64 digits possible

### ISSUE THREAD

**Issue by tomabg** [Icinga/icingaweb2-module-director#1890]
## Expected Behavior
when working with amazon aws some hostadresses are generated and exceeds the 64 digit limit
e.g.: dilab-app-prod-na-apps-alb-vd1-1467527011.us-east-1.elb.amazonaws.com

## Current Behavior
its not possible to create a new host with the above hostadress due to limit to 64 chars

## Possible Solution
increase limit for hostadress

## Steps to Reproduce (for bugs)
try to create a host with more than 64 chars

## Your Environment
not relevant

**Comment by tomabg** [comment]
tried with latest master.
limit to 64 bytes still exist for hostadress
hostadress is automatically used when using http checks
especially for cloud services resp automatically generated DNS names long names are very usual

**Comment by Thomas-Gelf** [comment]
Will be fixed, thanks for reporting this!
