### ISSUE TITLE
Feature request: Make API created config GUI editable

### ISSUE THREAD

**Issue by Wintermute2k6** [Icinga/icingaweb2-module-director#1899]
## Expected Behavior
After creation of an 'Service' Apply Rule via API the user should be able to edit the CheckCommand via the WebGUI.
Same restrictions apply for other DirectorAPI created services.

## Current Behavior
User can't manually edit an Service Apply Rule which was created  via the DirectorAPI.

## Possible Solution
Make the API created config editable.

## Steps to Reproduce (for bugs)
create service apply rule via DirectorAPI

```
apply Service "bonded-interfaces-rm" {
    import "template-standard-service-rm"

    check_command = "check_bonded_interfaces-rm"
    assign where "test1" in host.groups || "test-nas" in host.groups || "test-hypervisor-node" in host.groups
    groups = [ "bonded-interfaces-rm" ]

    import DirectorOverrideTemplate
}
```
try to change the check_command afterwards via Director Module GUI.

## Your Environment

* Director version (System - About): Director Version 1.62
* Icinga Web 2 version and modules (System - About): Icinga Web 2 2.6.3
* Icinga 2 version (`icinga2 --version`): 2.10.2
* Operating System and version: 
* Webserver, PHP versions:

**Comment by Wintermute2k6** [comment]
ref/NC/15511

**Comment by Thomas-Gelf** [comment]
We'll allow access to the `check_command` property for Service Apply Rules (for admins only), not for single services.
