### ISSUE TITLE
Basket for command related stuff does not work

### ISSUE THREAD

**Issue by swizzly** [Icinga/icingaweb2-module-director#1903]
## Expected Behavior
Creating a basket and storing all command related stuff in it should result an unempty file.

## Current Behavior
In a new basket all the command related categories i.e. "Command definitions", "External Command Definitions" and "Command Templates" are set to "All of them". Creating a new Snapshot results in an empty dataset. Director shows "-" and the Time Stamp as info, the file itself contains only "[]".

## Steps to Reproduce (for bugs)
- Create a new basket
- set all command related categories to "All of them".
- create a new snapshot
- check the results

## Your Environment
* Director version (System - About): Director-master version from 2019.06.11
* Icinga Web 2 version and modules (System - About): icingaweb2-2.6.1-1.el7
* Icinga 2 version (icinga2 --version): icinga2-2.9.1-1.el7
* Operating System and version: Red Hat 7.6
* Webserver, PHP versions: httpd-2.4.6-89.el7_6, rh-php71-1-1.el7

**Comment by Thomas-Gelf** [comment]
Has been fixed with 75b78c5.
