### ISSUE TITLE
icingacli renders special characters double quotes, braces in a strange way, sometimes

### ISSUE THREAD

**Issue by tlo8640** [Icinga/icingaweb2-module-director#1913]
## Expected Behavior
when querying director objects with icingacli assign_filter should be always "human readable", Escaping "double quotes" is allowed :-)
Example:

    icingacli director notification show work-test-notify --json
    {
       "apply_to": "service",
        "assign_filter": "!\"new_staged\"=host.groups",
    ...

## Current Behavior
on some notification objects it look like this:

    icingacli director notification show netcool_cleanpipe_service_notify_24x7_new  --json
    {
        "apply_to": "service",
        "assign_filter": "!%22new_staged%22=host.groups
    ...

At least rendering in director UI and when config is deployed to icinga2, it is working

## Possible Solution
rewrite assign_filter with icingacli or remove assign rules in icinga director and recreate (not tested)

## Steps to Reproduce (for bugs)
new created object will get "human readable" assign_filters. cannot reproduce at the moment.

## Question:
Could this lead into Problems in the future?
Should I recreate the assign_filters for preventing problems?
What could be the reason for this strange formatting?

## Your Environment
* Director version (System - About): 1.6.2
* Icinga Web 2 version and modules (System - About): 2.6.3
* Icinga 2 version (`icinga2 --version`): 
* Operating System and version: RHEL 7, 64 Bit
* Webserver, PHP versions: Php 7.1

**Comment by Thomas-Gelf** [comment]
Closing this, filters are shown in their internal storage format. This has technical reasons. We might introduce a new filter serialization format in the future, but there are no immediate plans to do so
