### ISSUE TITLE
there is no real solution/work-around for this, it should be avoided to use the restore functionality for Service-Sets.

### ISSUE THREAD

**Issue by ant0nwax** [Icinga/icingaweb2-module-director#1914]
there is no real solution/work-around for this, it should be avoided to use the restore functionality for Service-Sets.

_Originally posted by @darmagan in https://github.com/Icinga/icingaweb2-module-director/issues/1115#issuecomment-337883149_

Please remove the button or write this IMPORTANT INFORMATION TO THE BUTTON

**Comment by Thomas-Gelf** [comment]
@ant0nwax: are you facing related problems? The comment you're referring is two years old, and the related issue should have been fixed at least one year ago. If you are, please open a new dedicated issue explaining how to reproduce your problem.

Thanks,
Thomas
