### ISSUE TITLE
Basket import failed

### ISSUE THREAD

**Issue by R-Sommer** [Icinga/icingaweb2-module-director#1917]
## Expected Behavior
Create a new basket and snapshot (including Host Template and Data Lists, Option All of them ->17x HostTemplate, 8x DataList, 32x Datafield), download and upload it to a fresh installation.

## Current Behavior
Hitting **Upload** runs into this error message:

count(): Parameter must be an array or an object that implements Countable

#0 /usr/share/icingaweb2/library/vendor/Zend/Validate/File/Upload.php(224): Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(Integer, String, String, Integer, Array)
#1 /usr/share/icingaweb2/library/vendor/Zend/File/Transfer/Adapter/Abstract.php(665): Zend_Validate_File_Upload->isValid(String, String)
#2 /usr/share/icingaweb2/library/vendor/Zend/File/Transfer/Adapter/Http.php(145): Zend_File_Transfer_Adapter_Abstract->isValid(String)
#3 /usr/share/icingaweb2/library/vendor/Zend/Form/Element/File.php(441): Zend_File_Transfer_Adapter_Http->isValid(String)
#4 /usr/share/icingaweb2/library/vendor/Zend/Form.php(2278): Zend_Form_Element_File->isValid(NULL, Array)
#5 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/QuickForm.php(379): Zend_Form->isValid(Array)
#6 /usr/share/icingaweb2/modules/director/application/controllers/BasketController.php(124): Icinga\Module\Director\Web\Form\QuickForm->handleRequest()
#7 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Director\Controllers\BasketController->uploadAction()
#8 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch(String)
#9 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#10 /usr/share/php/Icinga/Application/Web.php(300): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#11 /usr/share/php/Icinga/Application/webrouter.php(104): Icinga\Application\Web->dispatch()
#12 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#13 {main}

## Steps to Reproduce (for bugs)
Several tries ended with identical stack trace

## Your Environment
Two identical machines, single instances with director:
* Director version (System - About): 1.6.2
* Icinga Web 2 version and modules (System - About): 2.6.3
* Icinga 2 version (`icinga2 --version`): r2.10.5-1
* Operating System and version: Ubuntu 18.04
* Webserver, PHP versions: Apache 2.4.29-1ubuntu4.8, 7.2.19-0ubuntu0.18.04

**Comment by R-Sommer** [comment]
I just did another very simple test. Starting with icinga and director being empty, creating just one simple host template, creating a basket and snapshot [Director-Basket_test1_ba94d73.zip](https://github.com/Icinga/icingaweb2-module-director/files/3434481/Director-Basket_test1_ba94d73.zip), restarting with empty databases and trying to upload the previously created snapshot result in exact the same error.

**Comment by R-Sommer** [comment]
BTW: Import via cli (icingacli director basket restore) works like a charm.

**Comment by Thomas-Gelf** [comment]
You're running into the Icinga Web [issue #3689](https://github.com/Icinga/icingaweb2/issues/3689), the bug is in a vendor library. This has been fixed quite some time ago and released today with Icinga Web 2.7.0. You can either upgrade or manually apply [this patch](https://github.com/Icinga/icingaweb2/commit/bd84ccf6042c397d42007127fef11b5f7e68b0e1)

**Comment by R-Sommer** [comment]
Yeah, now it's working. Thank you so much.

**Comment by Thomas-Gelf** [comment]
You're welcome!
