### ISSUE TITLE
- in datalist key causes the director to render apply rules wrong

### ISSUE THREAD

**Issue by winem** [Icinga/icingaweb2-module-director#1918]
This might also be an issue that I use `-` as key which is not recommended at all and I just missed hints or the related section in the documentation on this topic. If that's the case this ticket might not require a actual fix but a hint in the UI when creating datalists for example. 

## Expected Behavior
The rendered apply rule should look like this: 
```
assign where "clickhouse-server" in host.vars.hosted_services
```

## Current Behavior
The apply rule actually looks like this: 
```
assign where "Clickhouse-Server [clickhouse-server]" in host.vars.hosted_services
```

## Possible Solution
Find out why keys containing a `-` are rendered different.

## Steps to Reproduce (for bugs)
1. Create a datalist with `Key: clickhouse-server`, `Label: Clickhouse-Server`
2. Create a datafield `hosted_services` (or use any other name, this is just to reflect my actual env)
3. Add that field to a host or host template and choose the value `clickhouse-server`
4. Create a service apply rule or a service set and use `Assign where host.vars.hosted_services contains redis-server`
5. Switch to the `Preview` of that rule or set and check the `assign where` line:
```
[...]
assign where "Clickhouse-Server [clickhouse-server]" in host.vars.hosted_services && host.enable_active_checks
[...]
``` 

I also verified this via the icinga2 cli commands and by checking the actually applied configuration in the files of the director zone. 

Removing the `-` from the key or replacing it by an underscore works as expected and solves the issue.

## Your Environment

* Director version (System - About): 1.6.2
* Icinga Web 2 version and modules (System - About): 2.6.3
* Icinga 2 version (`icinga2 --version`): r2.10.5-1
* Operating System and version: Ubuntu 18.04
* Webserver, PHP versions: Apache 2.4.29, PHP 2.7.3

**Comment by zampat** [comment]
My vote for this issue, I note each time i use field values containing "space" characters. +1

**Comment by Wintermute2k6** [comment]
Ref/NC/693346

**Comment by lazyfrosch** [comment]
An attendee in the Director workshop found this, it should be an issue in the JS script code used with auto completion. The field can be manually set correctly at any time.
