### ISSUE TITLE
restoring a basket snapshot fails after deleting a data list 

### ISSUE THREAD

**Issue by R-Sommer** [Icinga/icingaweb2-module-director#1919]
## Expected Behavior
Creating a basket snapshot, deleting a data list and restoring that snapshot shall recreate the deleted data list.

## Current Behavior
Trying to restore the snapshot fails with this error:
Failed to load director_datalist "" (DbObject.php:628)

## Steps to Reproduce (for bugs)
This error is reproducible, no matter which data list is deleted

## Your Environment
* Director version (System - About): 1.6.2
* Icinga Web 2 version and modules (System - About): 2.7.0
* Icinga 2 version (`icinga2 --version`): r2.10.5-1
* Operating System and version: Ubuntu 18.04
* Webserver, PHP versions: apache 2.4.29-1ubuntu4.8, php 7.2.19-0ubuntu0.18.04

**Comment by Thomas-Gelf** [comment]
I didn't try with 1.6.2 right now, but for me it works flawlessly with the current master. Quite some basket-related issues have been tackled, so I consider this as being fixed. Please let me know if you're still facing related problems.
