### ISSUE TITLE
`Deploy anyways` overlapped by the page selector - Actitivity Log 

### ISSUE THREAD

**Issue by winem** [Icinga/icingaweb2-module-director#1928]
I am not sure if it's really a director issue. I think I did not notice this with Icingaweb 2.6.x. Not sure about 2.7.0 but I think it was introduced with the update to 2.7.0 or 2.7.1. I do not have a test environment available which is still on 2.7.0 to verify it.

## Expected Behavior
The whole text `There are no pending changes. Deploy anyways.` should be visible.

## Current Behavior
Only the text up to `Depl` is visible.
![Selection_409](https://user-images.githubusercontent.com/1457899/63337459-4b972d00-c341-11e9-89e9-d0426f85b35a.png)

## Steps to Reproduce (for bugs)
Go to Icinga Director -> Activity Log without any pending changes. 

## Your Environment

* Director version (System - About): 1.6.2
* Icinga Web 2 version and modules (System - About): 2.7.1
* Icinga 2 version (`icinga2 --version`): r2.10.5-1
* Operating System and version: Ubuntu 18.04
* Webserver, PHP versions: Apache2 & PHP 7.4

**Comment by log1-c** [comment]
Same goes for the german translation in v2.7.1 of Icinga Web 2:
![image](https://user-images.githubusercontent.com/24474580/63761534-9e349400-c8c1-11e9-9839-77f6b35bcecf.png)

Icinga Web 2 Version
    2.7.1
Git Commit
    b0bf9c4b0637f6113adb788e78c2bcf619225dd8
PHP Version
    7.2.19-0ubuntu0.18.04.2

With Icinga Web 2.6.3 this looks normal:
![image](https://user-images.githubusercontent.com/24474580/63761602-bc9a8f80-c8c1-11e9-8463-52ea47e1d9a3.png)

**Comment by Thomas-Gelf** [comment]
Thanks for reporting this, has been fixed
