### ISSUE TITLE
Director Icinga2 Linux Kickstart scrip't dont enable IPv6

### ISSUE THREAD

**Issue by RogerSik** [Icinga/icingaweb2-module-director#1932]
## Expected Behavior
The Linux kickstart script active icinga2 api but it doen'st add ```bind_host = "::"``` so it doen'st listen on IPv6. Can be easily tested with ```telnet localhost 5665``` and ```telnet -6 localhost 5665```

IPv6 should be as default enabled or at least when there is a IPv6 address specified in Director.

## Current Behavior
No IP6. Need to be enabled manually with editing ```/etc/icinga2/features-enabled/api.conf``` and adding to ```  bind_host = "::"``` and restart icinga2 service. 

## Your Environment

* Director version (master pulled on 27.08.2019):
* Icinga Web 2 version and modules (System - About):

- graphite 1.1.0
- monitoring 2.7.1
- Icinga Web2 Version 2.7.1

* Icinga 2 version (`icinga2 --version`):

version: r2.10.5-1

* Operating System and version:

Ubuntu 18.04
* Webserver, PHP versions:

Apache2 + PHP 7.3.8

**Comment by dnsmichi** [comment]
That will be fixed with 2.11 making this the default.

**Comment by RogerSik** [comment]
Cool! Great work are you all doing on Icinga2! :)
