### ISSUE TITLE
Postgresql error Migration 166 failed

### ISSUE THREAD

**Issue by undertaket** [Icinga/icingaweb2-module-director#1937]
Good day.
I had a problem installing director
Installed software:
Director version master
icinga web 2 version 2.6.3
icinga 2 version r2.10.5-1
Operating System FreeBSD 12.0
PHP 7.2.21
Webserver nginx 1.16.1
Database PostgreSQL 11 

After adding the schema to the database, migration was required, an error occurred during the migration:
`Migration 166 failed (SQLSTATE [42704]: Undefined object: 7 ERROR: type "enum_sync_rule_object_type" does not exist) while running ALTER TYPE enum_sync_rule_object_type ADD VALUE 'scheduledDowntime' (Migration.php: 60)`

Please help with solving the problem.

**Comment by Thomas-Gelf** [comment]
That's strange. I re-tried right now, works in here. Please show me the output of...

```sql
SELECT * FROM director_schema_migration;
```

...and:

```
\d sync_rule
```

Thanks,
Thomas

**Comment by Thomas-Gelf** [comment]
ping @undertaket
