### ISSUE TITLE
Trait 'gipfl\IcingaWeb2\Controller\Extension\ControlsAndContentHelper' not found

### ISSUE THREAD

**Issue by tdschmidl** [Icinga/icingaweb2-module-director#1943]
## Expected Behavior
Director loads as expected

## Current Behavior
Icinga Web 2 Director Module stopped working with:
Trait 'gipfl\IcingaWeb2\Controller\Extension\ControlsAndContentHelper' not found
#0 [internal function]: Icinga\Application\Web->Icinga\Application\{closure}()
#1 {main}
Note: Using branch "master"

## Steps to Reproduce (for bugs)
Commit 606d71501ef1486a4aac847ccd2a52f8a380736e introduced this bug

## Workaround
Use previos commit 9c62ea24b316dd9865386ab69dff0811220667a6

## Your Environment

* Director version (System - About): recent (09/17/19)
* Icinga Web 2 version and modules (System - About): 2.7.1
* Icinga 2 version (`icinga2 --version`): 2.10.5-1.buster
* Operating System and version: Debian Buster (10)
* Webserver, PHP versions: nginx, PHP 7.2.22-1+0\~20190902.26+debian10\~1.gbpd64eb7

**Comment by Thomas-Gelf** [comment]
Thanks for reporting this! #1938 has been implemented to make upgrades smooth, but the related redirecting code should be moved one line below. Currently it only works if you satisfy at least one of our new dependencies. Will be fixed immediately.
