### ISSUE TITLE
Revise kickstart script for Linux Agents

### ISSUE THREAD

**Issue by mwaldmueller** [Icinga/icingaweb2-module-director#1944]
## Expected Behavior
The current kickstart script for the deyploment of Linux Agents should be revised.

## Current Behavior/Possible Solution
Conspicuousnesses:

1. Parent node

In a distributed setup `ICINGA2_CA_NODE` should be set to the parent satellite node(s) of the Agent.

2. Version compare

Does the opposite:

```
version_compare() {
  # args: v1 op v2
  return "$(awk "BEGIN {!print ($1 $2 $3)}")"
}
```

From my point of view it should be:

```
version_compare() {
  # args: v1 op v2
  return "$(awk "BEGIN {print ($1 $2 $3)}")"
}
```

3. Restart command

Instead of:
```
  echo "Please restart icinga2:"
  echo "  service icinga2 restart"
else
```

Could be changed to:

```
  echo "Please restart icinga2:"
  echo "  systemctl restart icinga2"
else
```

## Your Environment

* Director version (System - About): v1.6.2
* Icinga Web 2 version and modules (System - About): not relevant
* Icinga 2 version (`icinga2 --version`): not relevant
* Operating System and version: not relevant
* Webserver, PHP versions: not relevant

**Comment by syrof** [comment]
There is a problem in kickstart with icinga2 version detection with new 2.11.0-1.

Previous version:
```
# icinga2 --version
icinga2 - The Icinga 2 network monitoring daemon (version: r2.10.5-1)
```
Current version:
```
# icinga2 --version
 icinga2 - The Icinga 2 network monitoring daemon (version: 2.11.0-1)
```
kickstart script expecting "r" or "v" just before version like in "r2.10.5-1"
```
icinga_version() {
  "$ICINGA2_BIN" --version 2>/dev/null | grep -oP 'version: [rv]\K\d+\.\d+\.\d+[^\)]*'
}
```
which generates an error while runnig kickstart
```
INFO: This should be a RedHat system
check: icinga2 installed - ERROR: You need to install icinga2!
```
In my case I just removed [rv] but this part of regex needs update.

My environment:
- Director version (System - About): v1.6.2
- Icinga Web 2 version and modules (System - About): 2.7.1
- Icinga 2 version (icinga2 --version): 2.11.0-1
- Operating System and version: Centos 7.7.1908
- Webserver, PHP versions: PHP 7.1.32

**Comment by dnsmichi** [comment]
Similar thing as with https://github.com/Icinga/icingaweb2/pull/3881

**Comment by Thomas-Gelf** [comment]
@mwaldmueller: thanks for testing the proposed fix. Regarding the CA-Proxy part: @mwaldmueller will create a dedicated issue
