### ISSUE TITLE
Class 'ipl\Html\HtmlDocument' not found

### ISSUE THREAD

**Issue by linuxmail** [Icinga/icingaweb2-module-director#1953]
Hi,

## Expected Behavior
Upgrading master branch from director and install the required modules to get the latest Director version working.

## Current Behavior
The module module in Icingaweb2 just brings:

```
Class 'ipl\Html\HtmlDocument' not found

#0 [internal function]: Icinga\Application\Web->Icinga\Application\{closure}()
#1 {main} 
```
The Apache2 logfile says:

```
[Sun Sep PHP Fatal error:  Class 'ipl\\Html\\HtmlDocument' not found in /usr/share/icingaweb2/modules/director/library/Director/Dashboard/Dashboard.php on line 20, referer: https://mon/icingaweb2/director/dashboard?name=hosts
[Sun Sep PHP Fatal error:  Class 'ipl\\Html\\HtmlDocument' not found in /usr/share/icingaweb2/modules/director/library/Director/Dashboard/Dashboard.php on line 20, referer: https://mon/icingaweb2/director/dashboard?name=hosts

[Sun Sep PHP Fatal error:  Interface 'ipl\\Html\\ValidHtml' not found in /usr/share/icingaweb2/modules/incubator/vendor/gipfl/icingaweb2/src/Widget/Tabs.php on line 11, referer: https://mon/icingaweb2/director/dashboard?name=hosts

[Sun Sep PHP Fatal error:  Class 'ipl\\Html\\HtmlDocument' not found in /usr/share/icingaweb2/modules/director/library/Director/Dashboard/Dashboard.php on line 20, referer: https://mon/icingaweb2/director/dashboard?name=hosts
```

## Your Environment
```
for module in incubator reactbundle ipl director; do echo $module ; cd $module ; git branch ; cd ..; done
incubator
* (HEAD detached at origin/stable/0.3.0)
  master
reactbundle
* (HEAD detached at origin/stable/0.7.0)
  master
ipl
* (HEAD detached at origin/stable/0.3.0)
  master
director
* master
```

```
Icinga Web 2 Version
    2.7.1
Git Commit
    b0bf9c4b0637f6113adb788e78c2bcf619225dd8
PHP Version
    5.6.40-0+deb8u1
Git Commit Datum
    2019-08-14
```

Name | Version
-- | --
cube | 1.0.0
director | master
doc | 2.7.1
fileshipper | 0.9.3
incubator | v0.3.0
ipl | v0.3.0
monitoring | 2.7.1
reactbundle | 0.7.0

**Comment by Thomas-Gelf** [comment]
Please attach the output of:

    find /etc/icingaweb2/enabledModules/{ipl,incubator,reactbundle}/ -type f | grep -v '.git'

**Comment by linuxmail** [comment]
Attached.
[debug.txt](https://github.com/Icinga/icingaweb2-module-director/files/3639580/debug.txt)

**Comment by Thomas-Gelf** [comment]
Looks good to me. That's the 'missing' file:

    /etc/icingaweb2/enabledModules/ipl/vendor/ipl/html/src/HtmlDocument.php

Are the file permissions ok, is our web (system) user able to read those files?

**Comment by linuxmail** [comment]
ls -l /etc/icingaweb2/enabledModules/ipl/vendor/ipl/html/src/HtmlDocument.php
-rw-r--r-- 1 www-data www-data 7194 Sep 22 10:57 /etc/icingaweb2/enabledModules/ipl/vendor/ipl/html/src/HtmlDocument.php
root@mon:/etc/icingaweb2/enabledModules/ipl# su - www-data -s /bin/bash
www-data@mon:~$ cd  /etc/icingaweb2/enabledModules/ipl/vendor/ipl/html/src/
www-data@mon:/etc/icingaweb2/enabledModules/ipl/vendor/ipl/html/src$ less HtmlDocument.php
...
```

looks fine. I would also expecting some "denied" messages, but nothing.

**Comment by Thomas-Gelf** [comment]
Strange. Please mail me a `.tar.gz` file containing these three directories plus `director`. Or better contact me first, I'll send you an upload link.

**Comment by linuxmail** [comment]
Mail sent.

**Comment by Thomas-Gelf** [comment]
This was a tricky one. Just for the records: not an issue, there where leftovers from an installation error  [reactbundle/#7](https://github.com/Icinga/icingaweb2-module-reactbundle/issues/7)) in the opcache.
