### ISSUE TITLE
When is director v1.7.0 getting tagged?

### ISSUE THREAD

**Issue by Ademi1** [Icinga/icingaweb2-module-director#1963]
## Expected Behavior

I have an automated setup of Icinga2, and I am pulling code from the icingaweb2-module-director repo master branch which sometimes leaves me having to upgrade dependencies. I would like to stay on a stable version of director, and upgrade when I see fit. Since downgrading the director is not an option, is there an ETA on when the latest version of icinga is getting tagged so I can include it in my code, and stopping pulling code from the master branch

## Your Environment

* Director version (System - About):
* Icinga Web 2 version and modules (System - About):
* Icinga 2 version (`icinga2 --version`):
* Operating System and version:
* Webserver, PHP versions:

**Comment by Thomas-Gelf** [comment]
[Here](https://github.com/Icinga/icingaweb2-module-director/releases/tag/v1.7.0) you go, sorry for the delay.
