### ISSUE TITLE
Raise incubator requirement in upgrade docs

### ISSUE THREAD

**Issue by nbuchwitz** [Icinga/icingaweb2-module-director#1967]
The minimal incubator version which is mentioned in the upgrade docs for director 1.7.0 and module info seems to be too low. The module fails with a dependency error when version v0.3.0 is installed. Updating incubator to version v0.5.0 resolves the error. 

Possible solution: Increase dependency to v0.5.0 (or v0.4.0?)

**Comment by Thomas-Gelf** [comment]
@nbuchwitz: please give me one more hint, where did I forget to raise that version?

**Comment by nbuchwitz** [comment]
Looks like I am seeing ghosts - everything looks fine. Maybe some caching issues with my browser.

**Comment by Thomas-Gelf** [comment]
Thank you :laughing:. I double-checked this, just to be sure:

* [module.info](https://github.com/Icinga/icingaweb2-module-director/blob/v1.7.0/module.info)
* [Installation / Requirements](https://github.com/Icinga/icingaweb2-module-director/blob/v1.7.0/doc/02-Installation.md#requirements)
* [Upgrading to 1.7.x](https://github.com/Icinga/icingaweb2-module-director/blob/v1.7.0/doc/05-Upgrading.md#upgrading-to-17x)

Cheers,
Thomas
