### ISSUE TITLE
Director 1.7.0 - If Background Daemon not running: Link to documentation is invalid

### ISSUE THREAD

**Issue by NeverUsedID** [Icinga/icingaweb2-module-director#1972]
"The Icinga Director Background Daemon is not running. Please check our documentation in case you need step by step instructions showing you how to fix this."

The link is pointing to : https://icinga.com/docs/director/latest/doc/75-Background-Daemon/

I have no idea where it should be going, but you will find the document under: 

/usr/share/icingaweb2/modules/director/doc/75-Background-Daemon.md (defaultpath)

or 

https://github.com/Icinga/icingaweb2-module-director/blob/master/doc/75-Background-Daemon.md

**Comment by Thomas-Gelf** [comment]
Thanks for the hint, we'll upgrade the documentation. If you enable the documentation module, you'll be shown the documentation that is available right there, locally on your system.

ping @bobapple :-)

**Comment by bobapple** [comment]
Sorry for the delay, documentation is updated now.
