### ISSUE TITLE
system reboot after deploying changes

### ISSUE THREAD

**Issue by habanero79** [Icinga/icingaweb2-module-director#1975]
## Expected Behavior
The deployment should be successful and the changes has to go online

## Current Behavior
After i click on "deploy" the System completely reboots. this happens not every time but in 8 of 10 cases.

## Possible Solution
None

## Steps to Reproduce (for bugs)
- i make some changes (hosts, Service e.g.)
- i click on deploy to make the changes happen
- in web frontend i see the spinning circle while the icinga Server shuts down and reboots
- after the System is up again i have to try this once more until a deployment succeed

## Your Environment
* Director version (System - About): 1.7.0
* Icinga Web 2 version and modules (System - About): 2.6.2
* Icinga 2 version (`icinga2 --version`): 
* Operating System and version: openhabian (Raspbian buster)
* Webserver, PHP versions: Apache2, PHP7.3

**Comment by Thomas-Gelf** [comment]
Please debug this on the Icinga system and report your findings in the [Icinga2 Issue tracker](https://github.com/Icinga/icinga2/issues). When your remote Icinga system crashes, there is not much the Web frontend can do about this.
