### ISSUE TITLE
Apply rule fails for hosts with an Icinga agent active

### ISSUE THREAD

**Issue by mtdeguzis** [Icinga/icingaweb2-module-director#1980]
## Expected Behavior
I should be able to write an apply rule that applies "host.name = somehost.domain.com". somehost.domain.com is running an Icinga agent. This may be similar to https://github.com/Icinga/icinga2/issues/7514.

## Current Behavior
When I apply a service using a the multiple host apply rule, I received an error in the hosts icinga log `/var/lib/icinga2/api/zones-stage//startup.log`:

![image](https://user-images.githubusercontent.com/27829577/66491512-d2829f00-ea80-11e9-88e8-f2ded2840783.png)
```
[2019-10-01 18:02:03 -0400] critical/config: Error: Validation failed for object 'somehost.domain.com!check-ping4' of type 'Service'; Attribute 'command_endpoint': Command endpoint must not be set.
Location: in /var/lib/icinga2/api/zones-stage//director-global/director/service_apply.conf: 120:1-120:35
/var/lib/icinga2/api/zones-stage//director-global/director/service_apply.conf(118): }
/var/lib/icinga2/api/zones-stage//director-global/director/service_apply.conf(119): 
/var/lib/icinga2/api/zones-stage//director-global/director/service_apply.conf(120): apply Service "check-ping4" {
                                                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/var/lib/icinga2/api/zones-stage//director-global/director/service_apply.conf(121):     import "check_ping4"
```

Log: 

## Possible Solution
? Use a host group instead ?

## Steps to Reproduce (for bugs)

1.  Create a command
2. Add a host and install an Icing agent:
```
$ sudo icinga2 node wizard
Welcome to the Icinga 2 Setup Wizard!

We will guide you through all required configuration details.

Please specify if this is an agent/satellite setup ('n' installs a master setup) [Y/n]: y

Starting the Agent/Satellite setup routine...

Please specify the common name (CN) [somehost.domain.com]: somehost.domain.com

Please specify the parent endpoint(s) (master or satellite) where this node should connect to:
Master/Satellite Common Name (CN from your master/satellite node): icingamaster.domain.com

Do you want to establish a connection to the parent node from this node? [Y/n]: y
Please specify the master/satellite connection information:
Master/Satellite endpoint host (IP address or FQDN): <IP>
Master/Satellite endpoint port [5665]: 5665

Add more master/satellite endpoints? [y/N]: n
Parent certificate information:

 Subject:     CN = icingamaster.domain.com
 Issuer:      CN = Icinga CA
 Valid From:  Nov 15 03:53:27 2018 GMT
 Valid Until: Nov 11 03:53:27 2033 GMT
 Fingerprint: <ID>
Is this information correct? [y/N]: y

Please specify the request ticket generated on your Icinga 2 master (optional).
 (Hint: # icinga2 pki ticket --cn 'somehost.domain.com'): 

# Accepted request manually on master...

No ticket was specified. Please approve the certificate signing request manually
on the master (see 'icinga2 ca list' and 'icinga2 ca sign --help' for details).
Please specify the API bind host/port (optional):
Bind Host []: 
Bind Port []: 

Accept config from parent node? [y/N]: y
Accept commands from parent node? [y/N]: y

Reconfiguring Icinga...
Disabling feature notification. Make sure to restart Icinga 2 for these changes to take effect.
Enabling feature api. Make sure to restart Icinga 2 for these changes to take effect.

Local zone name [somehost.domain.com]:  
Parent zone name [master]: 

Default global zones: global-templates director-global
Do you want to specify additional global zones? [y/N]: n

Do you want to disable the inclusion of the conf.d directory [Y/n]: n

Done.
```
3. Create a service template
4. Create an apply rule with "host.name = somehost.domain.com"
5. Check local logs

## Your Environment
* Icinga Web 2 version and modules (System - About): 
  * Icinga Web 2 Version 2.7.1
  * Git commit b0bf9c4b0637f6113adb788e78c2bcf619225dd8
  * PHP Version 7.1.30
* Web browser used: Chrome v75
* Icinga 2 version used (`icinga2 --version`): 2.11.0-1
* PHP version used (`php --version`):
```
[root@udaicinga icingaweb2]# /opt/rh/rh-php71/root/usr/sbin/php-fpm -v
PHP 7.1.30 (fpm-fcgi) (built: Jul 10 2019 09:46:42)
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
```

* Server operating system and version:
```
# cat /etc/os-release 
NAME="Red Hat Enterprise Linux Server"
VERSION="7.7 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.7"
PRETTY_

**Comment by mtdeguzis** [comment]
Hmm... can't reproduce the error or find the prior log. Strange. Well it seems* to be working with a 'check-systemd-httpd-new' I made and applied to 2 hosts.

However, when I deleted the check-systemd-httpd and check-systemd-httpd2 that I added to 2 hosts separately, then adding a single apply rule with the name "check-systemd-httpd", it failed:

```
/var/lib/icinga2/api/zones-stage//director-global/director/service_apply.conf(91): }
/var/lib/icinga2/api/zones-stage//director-global/director/service_apply.conf(92): 
/var/lib/icinga2/api/zones-stage//director-global/director/service_apply.conf(93): apply Service "check-systemd-httpd" {
                                                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/var/lib/icinga2/api/zones-stage//director-global/director/service_apply.conf(94):     import "check_systemd_httpd"
/var/lib/icinga2/api/zones-stage//director-global/director/service_apply.conf(95): 

[2019-10-09 11:20:07 -0400] critical/config: 1 error
[2019-10-09 11:20:07 -0400] critical/cli: Config validation failed. Re-run with 'icinga2 daemon -C' after fixing the config.
```
^ This is the entirety of the log.

Using the check function as suggested in the log:
```
$ sudo -u icinga icinga2 daemon -C
[2019-10-09 11:21:41 -0400] information/cli: Icinga application loader (version: 2.11.0-1)
[2019-10-09 11:21:41 -0400] information/cli: Loading configuration file(s).
[2019-10-09 11:21:42 -0400] information/ConfigItem: Committing config item(s).
[2019-10-09 11:21:42 -0400] information/ApiListener: My API identity: somehost.domain.com
[2019-10-09 11:21:42 -0400] information/ConfigItem: Instantiated 1 ScheduledDowntime.
[2019-10-09 11:21:42 -0400] information/ConfigItem: Instantiated 1 FileLogger.
[2019-10-09 11:21:42 -0400] information/ConfigItem: Instantiated 15 NotificationCommands.
[2019-10-09 11:21:42 -0400] information/ConfigItem: Instantiated 14 Notifications.
[2019-10-09 11:21:42 -0400] information/ConfigItem: Instantiated 1 IcingaApplication.
[2019-10-09 11:21:42 -0400] information/ConfigItem: Instantiated 25 HostGroups.
[2019-10-09 11:21:42 -0400] information/ConfigItem: Instantiated 1 Host.
[2019-10-09 11:21:42 -0400] information/ConfigItem: Instantiated 1 Downtime.
[2019-10-09 11:21:42 -0400] information/ConfigItem: Instantiated 1 CheckerComponent.
[2019-10-09 11:21:42 -0400] information/ConfigItem: Instantiated 4 Zones.
[2019-10-09 11:21:42 -0400] information/ConfigItem: Instantiated 2 Endpoints.
[2019-10-09 11:21:42 -0400] information/ConfigItem: Instantiated 1 UserGroup.
[2019-10-09 11:21:42 -0400] information/ConfigItem: Instantiated 1 ApiListener.
[2019-10-09 11:21:42 -0400] information/ConfigItem: Instantiated 321 CheckCommands.
[2019-10-09 11:21:42 -0400] information/ConfigItem: Instantiated 9 TimePeriods.
[2019-10-09 11:21:42 -0400] information/ConfigItem: Instantiated 1 User.
[2019-10-09 11:21:42 -0400] information/ConfigItem: Instantiated 13 Services.
[2019-10-09 11:21:42 -0400] information/ConfigItem: Instantiated 23 ServiceGroups.
[2019-10-09 11:21:42 -0400] information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
[2019-10-09 11:21:42 -0400] information/cli: Finished validating the configuration file(s).
```

**Comment by mtdeguzis** [comment]
Tried to workaround this by using `host.groups = newgroup` instead of the hostname. That did not work.

**Comment by mtdeguzis** [comment]
Update, I was able to fix this by ensuring the zone was set to master for the "icinga-agent" host template, as well as the multi-host apply rule for these hosts that have a live agent running.

I'm really thinking this is related to https://github.com/Icinga/icinga2/issues/7514.

**Comment by Thomas-Gelf** [comment]
Please show me the preview of your apply rule, once "normal" and once fully "resolved". Also, in the shown error log please click one the filename/line-number link and show the full apply rule as rendered in that file.

**Comment by mtdeguzis** [comment]
Here are the steps I took to avoid causing issue on production (using our dev instance with the same version and all).

1. Added agent to host
```
[mtdeguzis@host.domain.com ~]$ sudo icinga2 node wizard
Welcome to the Icinga 2 Setup Wizard!

We will guide you through all required configuration details.

Please specify if this is an agent/satellite setup ('n' installs a master setup) [Y/n]: y

Starting the Agent/Satellite setup routine...

Please specify the common name (CN) [host.domain.com]: 

Please specify the parent endpoint(s) (master or satellite) where this node should connect to:
Master/Satellite Common Name (CN from your master/satellite node): icinga.domain.com

Do you want to establish a connection to the parent node from this node? [Y/n]: y
Please specify the master/satellite connection information:
Master/Satellite endpoint host (IP address or FQDN): <IP>
Master/Satellite endpoint port [5665]: 

Add more master/satellite endpoints? [y/N]: n
Parent certificate information:

 Subject:     CN = icinga.domain.com
 Issuer:      CN = Icinga CA
 Valid From:  Nov 15 03:53:27 2018 GMT
 Valid Until: Nov 11 03:53:27 2033 GMT
 Fingerprint: <ID>

Is this information correct? [y/N]: y

Please specify the request ticket generated on your Icinga 2 master (optional).
 (Hint: # icinga2 pki ticket --cn 'host.domain.com'): 

No ticket was specified. Please approve the certificate signing request manually
on the master (see 'icinga2 ca list' and 'icinga2 ca sign --help' for details).
Please specify the API bind host/port (optional):
Bind Host []: 
Bind Port []: 

Accept config from parent node? [y/N]: y
Accept commands from parent node? [y/N]: y

Reconfiguring Icinga...
Disabling feature notification. Make sure to restart Icinga 2 for these changes to take effect.
Enabling feature api. Make sure to restart Icinga 2 for these changes to take effect.

Local zone name [host.domain.com]: 
Parent zone name [master]: 

Default global zones: global-templates director-global
Do you want to specify additional global zones? [y/N]: n

Do you want to disable the inclusion of the conf.d directory [Y/n]: n

Done.

Now restart your Icinga 2 daemon to finish the installation!

### accepted cert on Icinga master with 'icinga2 ca sign ID' ####

[mtdeguzis@host.domain.com ~]$ sudo systemctl restart icinga2
```
2. Create simple hostname check
![image](https://user-images.githubusercontent.com/27829577/66677432-9d6c7d00-ec37-11e9-910b-c634e1ed1abd.png)
3. Create template
![image](https://user-images.githubusercontent.com/27829577/66677716-44e9af80-ec38-11e9-91c1-77e05c25759b.png)
4. Create apply rule
![image](https://user-images.githubusercontent.com/27829577/66677943-bd507080-ec38-11e9-9e24-7a7f17444404.png)
5. Deploy changes

Notice the log dir for the target host is now present for startup
{code}
$ sudo ls /var/lib/icinga2/api/zones-stage
director-global  startup.log  status

$ sudo cat /var/lib/icinga2/api/zones-stage/startup.log                                                                                     
[2019-10-11 15:16:35 -0400] information/cli: Icinga application loader (version: 2.11.0-1)
[2019-10-11 15:16:35 -0400] information/cli: Loading configuration file(s).
[2019-10-11 15:16:35 -0400] information/ConfigItem: Committing config item(s).
[2019-10-11 15:16:35 -0400] information/ApiListener: My API identity: hostname.domain.com
[2019-10-11 15:16:35 -0400] critical/config: Error: Validation failed for object 'hostname.dom.com!check-hostname' of type 'Service'; Attribute 'command_endpoint': Command endpoint must not be set.
Location: in /var/lib/icinga2/api/zones-stage//director-global/director/service_apply.conf: 11:1-11:30
/var/lib/icinga2/api/zones-stage//director-global/director/service_apply.conf(9): }
/var/lib/icinga2/api/zones-stage//director-global/director/service_apply.conf(10): 
/var/lib/icinga2/api/zones-stage//director-global/director/service_apply.conf(11): apply Service "check-hostname" {
                                                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/var/lib/icinga2/api/zones-stage//director-global/director/service_apply.conf(12):     import "check_hostname"
/var/lib/icinga2/api/zones-stage//director-global/director/service_apply.conf(13): 

[2019-10-11 15:16:35 -0400] critical/config: 1 error
[2019-10-11 15:16:35 -0400] critical/cli: Config validation failed. Re-run with 'icinga2 daemon -C' after fixing the config.
{code}

## Preview as shown in Icingaweb2
zones.d/director-global/service_apply.conf
{code}
apply Service "check-hostname" {
    import "check_hostname"

    assign where host.name == "hostname.domain.com"

    import DirectorOverrideTemplate
}
{code}

##Local host file 
/var/lib/icinga2/api/zones-stage//director-global/director/service_apply.conf
{code}
apply Service "check-hostname" {
    import "check_hostname"

    assign where host.name == "hostname.domain.com"

    import DirectorOverrideTemplate
}

## Icinga master
/var/lib/icinga2/api/zones/director-global/director/service_apply.conf
{code}
apply Service "check-hostname" {
    import "check_hostname"

    assign where host.name == "hostname.domain.com"

    import DirectorOverrideTemplate
}
{code}

/var/lib/icinga2/api/zones/director-global/director/service_templates.conf
{code}
template Service "check_hostname" {
    check_command = "check_hostname"
    enable_notifications = false
    enable_active_checks = true
    enable_perfdata = false
    command_endpoint = host_name
}
{code}

**Comment by Thomas-Gelf** [comment]
Hi @mtdeguzis,

here you didn't accept the default setting:

> `Do you want to disable the inclusion of the conf.d directory [Y/n]: n`

And this is where your problem originates. Please do not include `conf.d` in your `icinga2.conf` on any node, eventually read [this](https://github.com/Icinga/icinga2/issues/7572#issuecomment-541305425) for related details. Then your problem should go away. When using the Director I'd suggest to use the Agent setup mechanisms proposed by the Director instead of manually trying to get things done with `icinga2 node setup`.

**Comment by mtdeguzis** [comment]
> use the Agent setup mechanisms proposed by the Director instead of manually trying to get things done with icinga2 node setup

This is spattered across the distributed monitoring docs, eventually hitting this section: https://icinga.com/docs/icinga2/latest/doc/06-distributed-monitoring/#distributed-monitoring-setup-master. Wonder if it should have an earmark/note about those using Director.

I assume it is this doc: https://github.com/Icinga/icingaweb2-module-director/blob/master/doc/24-Working-with-agents.md

The only thing I am not sure of, is what is the bare-minimum requirement to try the Director approach? Do I merely need the icinga2 package (plus deps it pulls in automatically)?

Let me give that a shot soon here with my test data node I chose in my last comment.

**Comment by Thomas-Gelf** [comment]
You found the right documentation links. Eventually ask in our [community forum](https://community.icinga.com/) for assistance.

> So now that I know the conf.d inclusion is the issue, i'll test that.

Perfect. In case you're still facing issues and thing this might be a bug please let me know.

**Comment by mtdeguzis** [comment]
This did indeed solve the issue after I reran the node setup (which will permanently move to Puppet soon) with the default option to disable inclusion of conf.d
```
$ sudo systemctl restart icinga2

# Good no errors for startup log.
$ sudo cat /var/lib/icinga2/api/zones-stage/startup.log
cat: /var/lib/icinga2/api/zones-stage/startup.log: No such file or directory
```

I made sure our puppet module had confd set to false, which it already did. Thanks for the help! I'll be sure to track https://github.com/Icinga/icingaweb2-module-director/issues/1980.
