### ISSUE TITLE
Updating director from pre-1.7 master to 1.7 fails

### ISSUE THREAD

**Issue by nitramabuar** [Icinga/icingaweb2-module-director#1981]
## Expected Behavior
1. click on "Apply a pending schema migration"
2. schema migration is executed

## Current Behavior
1. click on "Apply a pending schema migration"
following error is thrown:
```
Migration 167 failed (SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'director_daemon_info' already exists) while running CREATE TABLE director_daemon_info (
  instance_uuid_hex VARCHAR(32) NOT NULL, -- random by daemon
  schema_version SMALLINT UNSIGNED NOT NULL,
  fqdn VARCHAR(255) NOT NULL,
  username VARCHAR(64) NOT NULL,
  pid INT UNSIGNED NOT NULL,
  binary_path VARCHAR(128) NOT NULL,
  binary_realpath VARCHAR(128) NOT NULL,
  php_binary_path VARCHAR(128) NOT NULL,
  php_binary_realpath VARCHAR(128) NOT NULL,
  php_version VARCHAR(64) NOT NULL,
  php_integer_size SMALLINT NOT NULL,
  running_with_systemd ENUM('y', 'n') NOT NULL,
  ts_started BIGINT(20) NOT NULL,
  ts_stopped BIGINT(20) DEFAULT NULL,
  ts_last_modification BIGINT(20) DEFAULT NULL,
  ts_last_update BIGINT(20) DEFAULT NULL,
  process_info MEDIUMTEXT NOT NULL,
  PRIMARY KEY (instance_uuid_hex)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_bin
```

## Your Environment
* Director version (System - About): 1.7
* Icinga Web 2 version and modules (System - About): 2.7.1
* Icinga 2 version (`icinga2 --version`): r2.11.0-1
* Operating System and version: Debian 10
* Webserver, PHP versions:
Apache: 2.4.38, PHP: 7.3.9-1

**Comment by nitramabuar** [comment]
Checking the documentation now - I seem to have overlooked something and I need to remove the old daemon.
closing

**Comment by Thomas-Gelf** [comment]
Did you somehow manually apply changes to that schema? To fix your error please run...

```sql
DROP TABLE director_daemon_info;
```

...and then run the schema migration once again.

**Comment by nitramabuar** [comment]
This fixed the issue - migration worked perfectly. Thank you very much.

I only applied changes through the button in director in the past - but updated regularly from master.
