### ISSUE TITLE
Cloning a sync rule: Uncaught Error: Class name must be a valid object or a string in ...

### ISSUE THREAD

**Issue by NeverUsedID** [Icinga/icingaweb2-module-director#1982]
If I want to clone any sync rule i get the following Error Message in Webinterface:

```
 PHP Fatal error:  Uncaught Error: Class name must be a valid object or a string in /usr/share/icingaweb2/modules/ipl/vendor/ipl/html/src/FormElement/FormElementContainer.php:244
Stack trace:
#0 /usr/share/icingaweb2/modules/ipl/vendor/ipl/html/src/FormElement/FormElementContainer.php(200): ipl\\Html\\Form->createElement('rule_name', 'text', Array)
#1 /usr/share/icingaweb2/modules/ipl/vendor/ipl/html/src/FormElement/FormElementContainer.php(156): ipl\\Html\\Form->registerElement('rule_name', 'text', Array)
#2 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/CloneSyncRuleForm.php(31): ipl\\Html\\Form->addElement('rule_name', 'text', Array)
#3 /usr/share/icingaweb2/modules/ipl/vendor/ipl/html/src/HtmlDocument.php(258): Icinga\\Module\\Director\\Web\\Form\\CloneSyncRuleForm->assemble()
#4 /usr/share/icingaweb2/modules/ipl/vendor/ipl/html/src/Form.php(61): ipl\\Html\\HtmlDocument->ensureAssembled()
#5 /usr/share/icingaweb2/modules/director/application/controllers/SyncruleController.php(512): ipl\\Html\\Form->handleRequest(Object(G in /usr/share/icingaweb2/modules/ipl/vendor/ipl/html/src/FormElement/FormElementContainer.php on line 244, referer: https://xxxx/icingaweb2/director/syncrules$
```
It worked some time ago, but i can't find out whats the problem. Only changes I can remember was to install the nagvis module incl. php requiremends and enabled livestatus tcp. 

If Iam tring to clone a Import source im getting:

`SQLSTATE[HY093]: Invalid parameter number: no parameters were bound, query was: SELECT import_row_modifier.* FROM import_row_modifier WHERE (source_id = ?) ORDER BY priority ASC`

## Your Environment

* Director version (System - About): 1.7.0
* IPL version: v0.3.0
* Icinga Web 2 version and modules (System - About): 2.7.1
* Icinga 2 version (`icinga2 --version`):
System information:
  Platform: Ubuntu
  Platform version: 16.04.6 LTS (Xenial Xerus)
  Kernel: Linux
  Kernel version: 4.4.0-161-generic
  Architecture: x86_64

Build information:
  Compiler: GNU 5.4.0
  Build host: runner-LTrJQZ9N-project-298-concurrent-0

Application information:

General paths:
  Config directory: /etc/icinga2
  Data directory: /var/lib/icinga2
  Log directory: /var/log/icinga2
  Cache directory: /var/cache/icinga2
  Spool directory: /var/spool/icinga2
  Run directory: /run/icinga2

Old paths (deprecated):
  Installation root: /usr
  Sysconf directory: /etc
  Run directory (base): /run
  Local state directory: /var

Internal paths:
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

* Operating System and version:
* Webserver, PHP versions: Apache/2.4.41 (Ubuntu) / PHP 7.3

**Comment by Thomas-Gelf** [comment]
Thanks for reporting this, has been fixed.
