### ISSUE TITLE
Background daemon should collect deployment logs 

### ISSUE THREAD

**Issue by Thomas-Gelf** [Icinga/icingaweb2-module-director#1988]
This currently happens only while someone is looking at the deployments page or when automated deployment jobs have been configured.

**Comment by orangepeelbeef** [comment]
Any progress on this?  This issue comes up every day for us.  About half of the time we do any kind of deployment Director health check fails saying the config was not deployed even though it was.  It is fixed by doing a second deployment (no changes) and for some reason that clears it.
