### ISSUE TITLE
Unable to start the new Director daemon service

### ISSUE THREAD

**Issue by envycz** [Icinga/icingaweb2-module-director#1990]
## Expected Behavior

- Starting new Director deamon service without a problem after setting everything up acording to the instructions [here](https://github.com/Icinga/icingaweb2-module-director/blob/master/doc/75-Background-Daemon.md)
- Same problem is occuring on my two servers running different versions of Icinga
- Also I'm new to Github so sorry if I'm not submitting the issue 100% correctly :)

## Current Behavior
Starting Director Daemon service exits with error code 255.

**systemctl start icinga-director.service** output
> Job for icinga-director.service failed because the control process exited with error code. See "systemctl status icinga-director.service" and "journalctl -xe" for details

**systemctl status icinga-director.service** output
> icinga-director.service - Icinga Director - Monitoring Configuration
   Loaded: loaded (/etc/systemd/system/icinga-director.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Tue 2019-10-15 05:15:37 EDT; 1s ago
     Docs: https://icinga.com/docs/director/latest/
  Process: 21664 ExecStart=/usr/bin/icingacli director daemon run (code=exited, status=255)
 Main PID: 21664 (code=exited, status=255)
Oct 15 05:15:37 osboxes systemd[1]: icinga-director.service: main process exited, code=exited, status=255/n/a
Oct 15 05:15:37 osboxes systemd[1]: Failed to start Icinga Director - Monitoring Configuration.
Oct 15 05:15:37 osboxes systemd[1]: Unit icinga-director.service entered failed state.
Oct 15 05:15:37 osboxes systemd[1]: icinga-director.service failed.
Unit output.service could not be found.

**journalctl -xe** output
>Oct 15 05:14:06 osboxes systemd[1]: icinga-director.service: main process exited, code=exited, status=255/n/a
Oct 15 05:14:06 osboxes systemd[1]: Failed to start Icinga Director - Monitoring Configuration.
-- Subject: Unit icinga-director.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit icinga-director.service has failed.
--
-- The result is failed.
Oct 15 05:14:06 osboxes systemd[1]: Unit icinga-director.service entered failed state.
Oct 15 05:14:06 osboxes systemd[1]: icinga-director.service failed.

## Possible Solution
Unknown

## Steps to Reproduce (for bugs)
Steps from [here](https://github.com/Icinga/icingaweb2-module-director/blob/master/doc/75-Background-Daemon.md)

## Your Environment
* Director version (System - About):
v1.7.0
* Icinga Web 2 version and modules (System - About):
v2.7.1
* Icinga 2 version (`icinga2 --version`):
v2.11.0-1
* Operating System and version:
CentOS 7.7.1908
* Webserver, PHP versions:
Apache v2.4.6, PHP v7.1.32

**Comment by Thomas-Gelf** [comment]
Please show the output of:

```sh
which icingacli
icingacli module list
```

**Comment by envycz** [comment]
which icingacli
`/usr/bin/icingacli`

icingacli module list
```
MODULE         VERSION   STATE     DESCRIPTION
director       1.7.0     enabled   Director - Config tool for Icinga 2
incubator      0.5.0     enabled   Incubator provides bleeding-edge libraries
ipl            v0.3.0    enabled   The Icinga PHP library
monitoring     2.7.1     enabled   Icinga monitoring module
reactbundle    0.7.0     enabled   ReactPHP-based 3rd party libraries
```

**Comment by Thomas-Gelf** [comment]
Thanks! Now please:

```sh
grep director /etc/passwd
su - icingadirector -s /bin/bash
icingacli director daemon run --debug --trace
```

**Comment by Thomas-Gelf** [comment]
(and in case it keeps running: use `CTRL-C` to stop it)

**Comment by envycz** [comment]
ok thanks :), here -

grep director /etc/passwd
`icingadirector:x:984:978::/var/lib/icingadirector:/bin/false`

icingacli director daemon run --debug --trace
```
Running without systemd
PHP Fatal error:  Uncaught Error: Call to undefined function posix_getpid() in /usr/share/icingaweb2/modules/director/library/Director/Daemon/DaemonProcessDetails.php:97
Stack trace:
#0 /usr/share/icingaweb2/modules/director/library/Director/Daemon/DaemonProcessDetails.php(28): Icinga\Module\Director\Daemon\DaemonProcessDetails->initialize()
#1 /usr/share/icingaweb2/modules/director/library/Director/Daemon/BackgroundDaemon.php(115): Icinga\Module\Director\Daemon\DaemonProcessDetails->__construct('f626d51929864fd...')
#2 /usr/share/icingaweb2/modules/director/library/Director/Daemon/BackgroundDaemon.php(84): Icinga\Module\Director\Daemon\BackgroundDaemon->initializeProcessDetails(false)
#3 /usr/share/icingaweb2/modules/director/library/Director/Daemon/BackgroundDaemon.php(58): Icinga\Module\Director\Daemon\BackgroundDaemon->initialize()
#4 /usr/share/icingaweb2/modules/reactbundle/vendor/react/event-loop/src/Tick/FutureTickQueue.php(46): Icinga\Module\Director\Daemon\BackgroundDaemon->Icinga\Module\Director\Daemon\{closure}()
# in /usr/share/icingaweb2/modules/director/library/Director/Daemon/DaemonProcessDetails.php on line 97

Fatal error: Uncaught Error: Call to undefined function posix_getpid() in /usr/share/icingaweb2/modules/director/library/Director/Daemon/DaemonProcessDetails.php:97
Stack trace:
#0 /usr/share/icingaweb2/modules/director/library/Director/Daemon/DaemonProcessDetails.php(28): Icinga\Module\Director\Daemon\DaemonProcessDetails->initialize()
#1 /usr/share/icingaweb2/modules/director/library/Director/Daemon/BackgroundDaemon.php(115): Icinga\Module\Director\Daemon\DaemonProcessDetails->__construct('f626d51929864fd...')
#2 /usr/share/icingaweb2/modules/director/library/Director/Daemon/BackgroundDaemon.php(84): Icinga\Module\Director\Daemon\BackgroundDaemon->initializeProcessDetails(false)
#3 /usr/share/icingaweb2/modules/director/library/Director/Daemon/BackgroundDaemon.php(58): Icinga\Module\Director\Daemon\BackgroundDaemon->initialize()
#4 /usr/share/icingaweb2/modules/reactbundle/vendor/react/event-loop/src/Tick/FutureTickQueue.php(46): Icinga\Module\Director\Daemon\BackgroundDaemon->Icinga\Module\Director\Daemon\{closure}()
# in /usr/share/icingaweb2/modules/director/library/Director/Daemon/DaemonProcessDetails.php on line 97
```

**Comment by Thomas-Gelf** [comment]
This helped! The `php-posix` extension is missing, please re-check our [Installation requirements](https://github.com/Icinga/icingaweb2-module-director/blob/master/doc/02-Installation.md#requirements)

Cheers,
Thomas
