### ISSUE TITLE
Cant start new director daemon

### ISSUE THREAD

**Issue by ultralongnamewithoutanymeaning** [Icinga/icingaweb2-module-director#1996]
## Expected Behavior
Starting new Director deamon service without a error after setting everything up acording to the instructions

## Current Behavior
Error while trying to start the daemon with "systemctl start icinga-director.service"

Job for icinga-director.service failed because the control process exited with error code. See "systemctl status icinga-director.service" and "journalctl -xe" for details.

## journalctl -xe
-- Unit icinga-director.service has begun starting up.
Oct 17 15:10:42 TCDCI0000174 icingadirector[6260]: ERROR: ErrorException in /usr/share/icingaweb2/modules/director/library/Director/Daemon/BackgroundDaemon.php:146 with message: Use of undefined constant SIGHUP - assumed 'SIGHUP'

Oct 17 15:10:42 TCDCI0000174 systemd[1]: icinga-director.service: Main process exited, code=exited, status=1/FAILURE
Oct 17 15:10:42 TCDCI0000174 systemd[1]: Failed to start Icinga Director - Monitoring Configuration.
-- Subject: Unit icinga-director.service has fail

## Steps to Reproduce (for bugs)
systemctl start icinga-director.service

## Your Environment
* Icinga Web 2 version and modules (System - About):
director	1.7.0
doc	2.7.1
incubator	0.5.0
ipl	v0.3.0
monitoring	2.7.1
reactbundle	0.7.0
setup	2.7.1
translation	2.7.1

* Icinga 2 version (`icinga2 --version`): 2.11.0-1
* Operating System and version: SLES 12 SP3
* Webserver, PHP versions: 
Name             | Version     
-----------------+-------------
apache2-mod_php5 | 5.6.37-2.1  
php5             | 5.6.37-2.1  
php5-ctype       | 5.6.37-2.1  
php5-curl        | 5.6.37-2.1  
php5-dom         | 5.6.37-2.1  
php5-gd          | 5.6.37-2.1  
php5-gettext     | 5.6.37-2.1  
php5-iconv       | 5.6.37-2.1  
php5-intl        | 5.6.37-2.1  
php5-json        | 5.6.37-2.1  
php5-mbstring    | 5.6.37-2.1  
php5-openssl     | 5.6.37-2.1  
php5-pdo         | 5.6.37-2.1  
php5-pgsql       | 5.6.37-2.1  
php5-posix       | 5.6.37-2.1  
php5-sockets     | 5.6.40-lp151.11.14

**Comment by Thomas-Gelf** [comment]
You're missing php5-pcntl, please check our [installation requirements](https://github.com/Icinga/icingaweb2-module-director/blob/master/doc/02-Installation.md#requirements).

Cheers,
Thomas
