### ISSUE TITLE
SQL error when trying to clone Import Source

### ISSUE THREAD

**Issue by shiz0** [Icinga/icingaweb2-module-director#1997]
## Expected Behavior
Import Source can be cloned under new name and then edited

## Current Behavior
Import Source cannot be cloned, the following SQL error is shown:
`SQLSTATE[HY093]: Invalid parameter number: no parameters were bound, query was: SELECT import_row_modifier.* FROM import_row_modifier WHERE (source_id = ?) ORDER BY priority ASC`

## Steps to Reproduce (for bugs)
Not exactly sure here, I have an import source (from MS AD) with modifiers etc. and I'm trying to clone that to use on our next domain.
If more Info is needed, I'll be happy to provide.

## Your Environment
* Director version (System - About): 1.7.1 
* Icinga Web 2 version and modules (System - About): 2.7.3
Git commit 06cabfe8ba28cf545a42c92f25484383191a4e51
PHP Version 7.1.30
Git commit date 2019-10-18

Loaded modules
Name 			Version
director 		1.7.1
doc 			2.7.3
incubator 		0.5.0
ipl 			v0.4.0
monitoring 		2.7.3
reactbundle 	0.7.0
vsphere 		1.1.0 

* Icinga 2 version (`icinga2 --version`):
icinga2 - The Icinga 2 network monitoring daemon (version: 2.11.1-1)

Copyright (c) 2012-2019 Icinga GmbH (https://icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

System information:
  Platform: CentOS Linux
  Platform version: 7 (Core)
  Kernel: Linux
  Kernel version: 3.10.0-1062.4.1.el7.x86_64
  Architecture: x86_64

Build information:
  Compiler: GNU 4.8.5
  Build host: runner-LTrJQZ9N-project-322-concurrent-0

Application information:

General paths:
  Config directory: /etc/icinga2
  Data directory: /var/lib/icinga2
  Log directory: /var/log/icinga2
  Cache directory: /var/cache/icinga2
  Spool directory: /var/spool/icinga2
  Run directory: /run/icinga2

Old paths (deprecated):
  Installation root: /usr
  Sysconf directory: /etc
  Run directory (base): /run
  Local state directory: /var

Internal paths:
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

* Operating System and version:
Centos 7
* Webserver, PHP versions:
Apache/2.4.6 (CentOS)
PHP 7.1.30 with FPM from SCL (rh-php71)

Unsure if related to https://github.com/Icinga/icingaweb2-module-director/issues/1982
But since I assumed that should be fixed in 1.7.1 an also I'm not getting any errors in the WebInterface (apart from the SQL one), I'm opening another here. Hope that's ok.

**Comment by mickael-ange** [comment]
I have similar SQL error if I try to clone an "Import AWS EC2 instances" using AWS module.
![image](https://user-images.githubusercontent.com/5266874/67367296-c7169400-f5a7-11e9-8d43-3f972e95233e.png)

Same with restoring a basket snapshot.
![image](https://user-images.githubusercontent.com/5266874/67367420-0644e500-f5a8-11e9-92b2-5cb5e979025c.png)


```
icinga2 --version
icinga2 - The Icinga 2 network monitoring daemon (version: 2.11.0-1)

Copyright (c) 2012-2019 Icinga GmbH (https://icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

System information:
  Platform: CentOS Linux
  Platform version: 7 (Core)
  Kernel: Linux
  Kernel version: 3.10.0-1062.1.2.el7.x86_64
  Architecture: x86_64

Build information:
  Compiler: GNU 4.8.5
  Build host: runner-LTrJQZ9N-project-322-concurrent-0

Application information:

General paths:
  Config directory: /etc/icinga2
  Data directory: /var/lib/icinga2
  Log directory: /var/log/icinga2
  Cache directory: /var/cache/icinga2
  Spool directory: /var/spool/icinga2
  Run directory: /run/icinga2

Old paths (deprecated):
  Installation root: /usr
  Sysconf directory: /etc
  Run directory (base): /run
  Local state directory: /var

Internal paths:
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid
```
- PHP Binary: /opt/rh/rh-php71/root/usr/bin/php
- PHP Version: 7.1.30
- PHP Integer: 64bit
- Icinga Web 2 Version: 2.6.3
- Git commit: 0d119242ba1728f4b617000a1bd14a230f96f2ee

Modules:
![image](https://user-images.githubusercontent.com/5266874/67367094-5e2f1c00-f5a7-11e9-8919-bcaf880ad8aa.png)

Regards

**Comment by mickael-ange** [comment]
Same result with the CLI:
```
cat Director-Basket_AWS-53fb850.json | icingacli director basket restore 
ERROR: Zend_Db_Statement_Exception in /usr/share/icingaweb2/library/vendor/Zend/Db/Statement/Pdo.php:225 with message: SQLSTATE[08P01]: <<Unknown error>>: 7 ERROR:  bind message supplies 0 parameters, but prepared statement "pdo_stmt_00000005" requires 1, query was: SELECT import_row_modifier.* FROM import_row_modifier WHERE (source_id = ?) ORDER BY priority ASC
````

Tracing back the code for this `source_id`. I've figured out that the import source expected `source_id` from `id`.
```
# grep -RF source_id /usr/share/icingaweb2
/usr/share/icingaweb2/modules/director/application/controllers/ImportsourceController.php:        $id = $this->params->get('source_id', $this->params->get('id'));
/usr/share/icingaweb2/modules/director/application/controllers/ImportsourceController.php:            ['source_id' => $source->get('id')],
/usr/share/icingaweb2/modules/director/application/controllers/ImportsourceController.php:                    ['source_id' => $source->get('id')]
/usr/share/icingaweb2/modules/director/application/controllers/ImportsourceController.php:        $listUrl = 'director/importsource/modifier?source_id='
/usr/share/icingaweb2/modules/director/application/controllers/ImportsourceController.php:                ['source_id' => $source->get('id')],
[..]
```
So I tried to add an `id` in the basket JSON for the ImportSource object:
```
{
    "ImportSource": {
        "Import AWS EC2 Instances": {
            "id": 1,
            "description": "Import AWS EC2 Instances in Tokyo",
            "key_column": "name",
            "modifiers": [
                

```
et voila!
```
cat Director-Basket_AWS_53fb850.json | icingacli director basket restore 
Objects from Basket Snapshot have been restored
```

```
sudo su - postgres
postgres=# \c icingadirector
icingadirector=# SELECT import_row_modifier.* FROM import_row_modifier  ORDER BY priority ASC;
 id | source_id |  property_name   | target_property |                             provider_class                             | priority | description 
----+-----------+------------------+-----------------+------------------------------------------------------------------------+----------+-------------
  1 |         1 | status           |                 | Icinga\Module\Director\PropertyModifier\PropertyModifierRejectOrSelect |        1 | 
  2 |         1 | tags.Environment | environment     | Icinga\Module\Director\PropertyModifier\PropertyModifierRejectOrSelect |        2 | 
(2 rows)
```

I will try to see if I can find where to add the `id` in the basket download function.
I have not searched for the clone function yet but I bet it is related.

**Comment by NeverUsedID** [comment]
Take a look here [](https://github.com/Icinga/icingaweb2-module-director/issues/1982)

Maybe test the git version as this bug should be fixed

**Comment by Thomas-Gelf** [comment]
Thanks for reporting this. Can be reproduced, will be fixed.
