### ISSUE TITLE
Sync Rule failed: Trying to recreate icinga_host while it should merge/replace it.

### ISSUE THREAD

**Issue by NeverUsedID** [Icinga/icingaweb2-module-director#2004]
## Expected Behavior
Host that are already existing should be merged or replaced, not recreated

## Current Behavior

Iam trying to add Hosts from vspheredb and the sync rule wants to create a new host, even its already existing.

`This Sync Rule failed when last checked at 2019-10-31 10:46:49: Exception while syncing Icinga\Module\Director\Objects\IcingaHost some_host_name: Trying to recreate icinga_host ("some_host_name")`

The host exists in the director and is not coming from some local configfiles. If i click preview, i can clearly see that he want to create the host instead of ignoring/modifying it. Only one host is merged/replaced in my example, all others are created instead of modified.

## Import  Basket

[Director-Basket_sync-rule-creates-host-instead-of-modify.json.txt](https://github.com/Icinga/icingaweb2-module-director/files/3793396/Director-Basket_sync-rule-creates-host-instead-of-modify.json.txt)

## Your Environment

Director version (System - About): 1.7.0
Icinga Web 2 version and modules (System - About): 2.7.2
Icinga 2 version (icinga2 --version): r2.11.0-1
Operating System and version: Ubuntu 16.04.6 LTS
Webserver, PHP versions: Apache/2.4.41 (Ubuntu), PHP 7.3.10-1+ubuntu16.04.1+deb.sury.org+1

**Comment by Thomas-Gelf** [comment]
@NeverUsedID: seems that your problem derives from tweaking your object_name in the Sync Property, this takes place "after" we check whether an object exists. This behaviour might be improved, but as of this writing it works this way for performance reasons.

You have to make sure that your key column equals the object name, then it should work as expected. This is possible via Property Modifiers at import time or in this special case also via SQL.

**Comment by NeverUsedID** [comment]
Thanks for your fast support. I changed the name of my "fqdn" column to "object_name" and now its working.

**Comment by Thomas-Gelf** [comment]
You're welcome, glad to hear that it works!
