### ISSUE TITLE
Paged LDAP Requests Import Source

### ISSUE THREAD

**Issue by schneif2** [Icinga/icingaweb2-module-director#2019]
## Expected Behavior
List all entries from LDAP request (with more than 1000 entries)

## Current Behavior
Stops after 1000 entries

## Possible Solution
Change line 17: library/Director/Import/ImportSourceLdap.php:
from
`$query = $this->connection()->select()->from($this->settings['objectclass'], $columns);`
to
`$query = $this->connection()->select()->setUsePagedResults(true)->from($this->settings['objectclass'], $columns);`

## Steps to Reproduce (for bugs)
Try to import more than 1000 LDAP entries with automatisation -> import source
Limit is 40 Pages with 25 entries in preview
After change all entries will be listed

## Your Environment
Director version (System - About): 1.7.2

**Comment by OliB11** [comment]
:+1: +1

Same for me. After I changed the above file manually, it will work.

**Comment by Thomas-Gelf** [comment]
Thanks for reporting this - and for the reminder!

**Comment by Wintermute2k6** [comment]
Sorry for re-opening this Issue but as an actual change in the actual php version:
