### ISSUE TITLE
Host Templates are not usable by user having a role with director/filter/hostgroups assigned

### ISSUE THREAD

**Issue by MolbioUnige** [Icinga/icingaweb2-module-director#2020]
## Expected Behavior
I'd like to have different admin users having each a set of servers. They should be able to create new hosts themselves based on templates created by an admin user. I, as admin, have created a host template for each the groups, every host templates having a different HostGroup, i.e:

```
template Host "MOLBIO -Standard Linux Server" {
    import "Standard Linux Server"

    groups = [ "molbio" ]
    vars.department = "molbio"
}
```
I have then created a restricted admin role which has everything enabled but with a restriction on director/filter/hostgroups, i.e. `hostgroup_name=molbio`

## Current Behavior
A user with that restricted role sees host templates but cannot use them, nor create a new template based on them. Moreover, the user cannot create a HostTemplate for himself, but that's better like this.

Whatever the user does with host templates the following message is displayed:

> Unable to store a host with the given properties because of insufficient permissions (IcingaHostForm.php:363)

If the user selects a template and click on the "Host" tab, the following is displayed

> No such object available
> 
> 0 /usr/share/icingaweb2/modules/director/library/Director/Web/Controller/ObjectController.php(441): Icinga\Module\Director\Web\Controller\ObjectController->loadObject()
> 1 /usr/share/icingaweb2/modules/director/library/Director/Web/Controller/ObjectController.php(75): Icinga\Module\Director\Web\Controller\ObjectController->eventuallyLoadObject()
> 2 /usr/share/php/Icinga/Web/Controller/ActionController.php(152): Icinga\Module\Director\Web\Controller\ObjectController->init()
> 3 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(59): Icinga\Web\Controller\ActionController->__construct(Object(Icinga\Web\Request), Object(Icinga\Web\Response), Array)
> 4 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
> 5 /usr/share/php/Icinga/Application/Web.php(300): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
> 6 /usr/share/php/Icinga/Application/webrouter.php(99): Icinga\Application\Web->dispatch()
> 7 /usr/share/icingaweb2/public/index.php(4): require_once(String)
> 8 {main}

## Steps to Reproduce (for bugs)

1. Create non-admin role
2. Grant permission everywhere
2. Add a filter to director/filter/hostgroups

## Your Environment

* Director version (System - About): 1.7.2
* Icinga Web 2 version and modules (System - About): 2.7.3
* Icinga 2 version (`icinga2 --version`): r2.11.2-1
* Operating System and version: Ubuntu  18.04.3 LTS (Bionic Beaver)
* Webserver, PHP versions: Apache/2.4.29 (Ubuntu), PHP 7.2.24-0ubuntu0.18.04.1

**Comment by lippserd** [comment]
Hi @MolbioUnige,

Could you please test related PR? Further, please don't grant the director admin (`director/*`) permission to restricted users. The code just does not expect restrictions with this permission which is why you get the **No such object available** errors.

With the PR, a restricted non-admin director user is allowed to create hosts from the templates that match his host group restriction.

Feedback is welcome.

All the best,
Eric

**Comment by lippserd** [comment]
ref/IP/22355
