### ISSUE TITLE
Host object displays older custom vars values from previous  inheritated template

### ISSUE THREAD

**Issue by carraroj** [Icinga/icingaweb2-module-director#2029]
## Current Behavior
Previous changes in imported templates doesn't displayed in Host-object when modify the Host-object. In previous Director version it worked before.

## Your Environment

* Director version (System - About): 1.7.2
* Icinga Web 2 version and modules (System - About): 2.7.3
* Icinga 2 version (`icinga2 --version`): 2.11.2
* Operating System and version:
* Webserver, PHP versions:

**Comment by carraroj** [comment]
ref/NC/649525

**Comment by Thomas-Gelf** [comment]
Description makes no sense to me, sorry
