### ISSUE TITLE
Director tries to put objects into global zone if no zone set

### ISSUE THREAD

**Issue by mzhaase** [Icinga/icingaweb2-module-director#2035]
## Expected Behavior
Deployment should work

## Current Behavior
Upon deployment, I get errors like these:

    [2019-11-25 18:10:34 +0100] critical/config: Error: Service 'xxxx!Kamailio Log' cannot be put into global zone 'global'.

However, these objects do not have a cluster zone set in director. This happened after upgrading icinga2 2.7 -> 2.11 and director 1.6 -> 1.7

## Your Environment
* Director version (System - About): 1.7
* Icinga Web 2 version and modules (System - About): 2.7.3
* Icinga 2 version (`icinga2 --version`): 2.11
* Operating System and version: debian 8
* Webserver, PHP versions: apache, 5.6.40

```
mysql> select * from icinga_service where object_name='Kamailio Log' \G
*************************** 1. row ***************************
                     id: 89
            object_name: Kamailio Log
            object_type: apply
               disabled: n
           display_name: NULL
                host_id: NULL
         service_set_id: 12
       check_command_id: NULL
     max_check_attempts: NULL
        check_period_id: NULL
         check_interval: NULL
         retry_interval: NULL
          check_timeout: NULL
   enable_notifications: NULL
   enable_active_checks: NULL
  enable_passive_checks: NULL
   enable_event_handler: NULL
        enable_flapping: NULL
        enable_perfdata: NULL
       event_command_id: NULL
               volatile: NULL
                zone_id: NULL
    command_endpoint_id: NULL
                  notes: NULL
              notes_url: NULL
             action_url: NULL
             icon_image: NULL
         icon_image_alt: NULL
              use_agent: NULL
              apply_for: NULL
      use_var_overrides: NULL
          assign_filter: NULL
     template_choice_id: NULL
flapping_threshold_high: NULL
 flapping_threshold_low: NULL
```

```
mysql> select * from icinga_host where object_name='xxxx' \G
*************************** 1. row ***************************
                     id: 16
            object_name: xxxx
            object_type: object
               disabled: n
           display_name: xxx
                address: xxx.xxx.xxx.xxx
               address6: NULL
       check_command_id: NULL
     max_check_attempts: NULL
        check_period_id: NULL
         check_interval: NULL
         retry_interval: NULL
          check_timeout: NULL
   enable_notifications: NULL
   enable_active_checks: NULL
  enable_passive_checks: NULL
   enable_event_handler: NULL
        enable_flapping: NULL
        enable_perfdata: NULL
       event_command_id: NULL
               volatile: NULL
                zone_id: NULL
    command_endpoint_id: NULL
                  notes: NULL
              notes_url: NULL
             action_url: NULL
             icon_image: NULL
         icon_image_alt: NULL
              has_agent: NULL
  master_should_connect: NULL
          accept_config: NULL
                api_key: NULL
     template_choice_id: NULL
flapping_threshold_high: NULL
 flapping_threshold_low: NULL
1 row in set (0.01 sec)
```

**Comment by Thomas-Gelf** [comment]
Please share the output of:

```sql
SELECT * FROM director_setting;
SELECT * FROM icinga_zone;
```

**Comment by mzhaase** [comment]
```
mysql> SELECT * FROM director_setting;
+---------------------+-----------------+
| setting_name        | setting_value   |
+---------------------+-----------------+
| default_global_zone | global          |
| enable_audit_log    | y               |
| master_zone         | director-global |
+---------------------+-----------------+
3 rows in set (0.00 sec)

mysql> SELECT * FROM icinga_zone;                                                                                                                                                                                    +----+-----------+----------------------------+-----------------+----------+-----------+
| id | parent_id | object_name                | object_type     | disabled | is_global |
+----+-----------+----------------------------+-----------------+----------+-----------+
|  1 |      NULL | director-global            | external_object | n        | n         |
|  2 |         1 | satellite_xxx             | external_object | n        | n         |
|  4 |         1 | satellite_yyy        | external_object | n        | n         |
|  5 |         1 | satellite_zzz       | external_object | n        | n         |
|  7 |         1 | satellite_aaa | external_object | n        | n         |
+----+-----------+----------------------------+-----------------+----------+-----------+
5 rows in set (0.00 sec)
```

**Comment by mzhaase** [comment]
```
cat /etc/icinga2/zones.conf
object Zone "director-global"  {
  endpoints = [ "my-master", ]
}

object Zone "global"  {
  global = true
}

object Zone "satellite_aaa"  {
  endpoints = [ "xxx", ]
  parent = "director-global"
}

object Zone "satellite_bbb"  {
  endpoints = [ "xxx", ]
  parent = "director-global"
}

object Zone "satellite_ccc"  {
  endpoints = [ "xxx", ]
  parent = "director-global"
}

object Zone "satellite_ddd"  {
  endpoints = [ "xxx", ]
  parent = "director-global"
}
```

**Comment by Thomas-Gelf** [comment]
Great, this helps. You configured your Zones differently from the proposed default configuration. You have a custom default global zone named `global`, and somehow the `director-global` Zone is still there, NOT global and being used as your master Zone.

While doing so is perfectly legal, I'd strongly advise against it. You'll confuse everyone in every issue/discussion, as no one expects your master zone being called `director-global`. In addition to this you have to be very careful, as every Agent will be shipped with `director-global`.

Said all this, it looks like you changed your Zones in your file-based configuration AFTER the Director learned about it. Please trigger the Kickstart again (Infrastructure -> Kickstart -> Fire) to teach the Director about your new reality.

If this doesn't help, please share the preview of the Service Set containing your Kamailio Log Service, and also all related Service Templates. Please include the rendered Config AND the target file name.

And even if this works, please strongly consider naming your Zones differently. Eventually use our [Community Forum](https://community.icinga.com/) to ask for help.

Cheers,
Thomas

**Comment by mzhaase** [comment]
Well after upgrading to 2.11 I followed the steps outlined here:

https://github.com/Icinga/icinga2/issues/7530

Which basically says to change all zones to external via mysql in director DB and add them to zones.conf afterwards. If this does not work, what exactly are the steps to resolve 7530?

**Comment by mzhaase** [comment]
Trying to re-run kickstart:

`SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails ("director"."icinga_host", CONSTRAINT "icinga_host_command_endpoint" FOREIGN KEY ("command_endpoint_id") REFERENCES "icinga_endpoint" ("id") ON UPDATE CASCADE), query was: DELETE FROM icinga_endpoint WHERE (id = '2') (Pdo.php:225)`

```
mysql> select * from icinga_endpoint where id=2 \G                                                                                                                                                                   *************************** 1. row ***************************
          id: 2
     zone_id: 2
 object_name: xxx
 object_type: external_object
    disabled: n
        host: xxxx
        port: NULL
log_duration: NULL
  apiuser_id: 2
1 row in set (0.00 sec)
```

I guess that means I should undo the steps in 7530 and turn them back to type 'object'?

**Comment by Thomas-Gelf** [comment]
> Well after upgrading to 2.11 I followed the steps outlined here:
> 
> [Icinga/icinga2#7530](https://github.com/Icinga/icinga2/issues/7530)
> 
> Which basically says to change all zones to external via mysql in director DB and add them to zones.conf afterwards. If this does not work, what exactly are the steps to resolve 7530?

This comment quotes [this](https://github.com/Icinga/icinga2/issues/7542#issuecomment-535976245) without referencing the original comment and leaves out this part:

> Alternatively you could stick with the latest 2.10.x and wait with 2.11.x unless this issue has been fixed. That's what I would do. Your configuration isn't wrong, it just fails on 2.11.0. Sure, Director always advised against creating Zones and Endpoints, unless "you know what you're doing". Those who knew have been bitten, we're sorry for that. But still, it should work, this is a bug. We're already working on it, it will be fixed.

But this does not explain how `director-global` became our master(!!) zone?!

The error triggered by Kickstart shows that you have Host object(s) using a command endpoint that used to be defined in your Director setup, has been transformed into being "external" by you with the linked queries while not being defined in your text-based Icinga configuration.

In case this is a satellite, your config should be fixed. In case it is just an Agent with special settings in your Director DB, it shouldn't be "external". You can find related hosts with:

```sql
SELECT  * FROM icinga_host WHERE command_endpoint_id = 2;
```

Cheers,
Thomas

**Comment by mzhaase** [comment]
There where a couple unused templates referencing these endpoints, which I deleted. I ran kickstart again and now it works fine. Deploy also works. I don't know why director tried to put things into global and whether that is a bug, so in case it is a bug, I leave this open. If it isn't, you can close it.

The reason director-global became the master zone was mostly because the documentation was pretty unclear back in early 2017. Now it's technical debt.

**Comment by lazyfrosch** [comment]
This also seem to happen when the Kickstart is run initially without any global Zone, did this by mistake.

I had to re-run Kickstart to import the new Zone, then it would be rendered without the `zone = ` attribute.

Maybe we should fail on Kickstart, when no global zone was detected? Or at least during rendering, when the global zone is not present.

**Comment by Thomas-Gelf** [comment]
After looking into the problem @lazyfrosch encountered, we settled on providing some guidance / early warnings to detect these and similar configuration errors. While in the example shown by @mzhaase the director-global Zone was defined as a non-global zone, @lazyfrosch didn't have a global Zone at all.

While technically speaking, this might not be considered being a bug, in my believes we should at least try to point out such configuration errors, so that our users can adjust their Icinga configuration. Created #2374 and  #2375, closing this issue.
