### ISSUE TITLE
Director REST API: table director_deployment_log not updated after deployment

### ISSUE THREAD

**Issue by a2yp** [Icinga/icingaweb2-module-director#2039]
## Expected Behavior
When deploying config changes via Director REST API `POST director/config/deploy` the director_deployment_log table should be updated properly.

## Current Behavior
After deployments via Director REST API `POST director/config/deploy` the director_deployment_log table is not updated properly althoug the rollout was successfull:

<img width="2255" alt="Bildschirmfoto 2019-11-29 um 11 54 27" src="https://user-images.githubusercontent.com/58001001/69865797-84c92c80-12a2-11ea-8017-5f9e74aa36bb.png">

<details><summary>In this status warnings for pending deployments are send.</summary>
<p>

```
Info:    Icinga Director: there are problems

Director configuration: 3 tests OK
[OK] Database resource 'director' has been specified
[OK] Make sure the DB schema exists
[OK] There are no pending schema migrations

Director Deployments: 2 tests OK, 1x WARNING
[OK] Deployment endpoint is '*********'
[OK] There are 0 un-deployed changes
[WARNING] The last Deployment started 9m 2s ago and is still pending

Import Sources: 1 tests OK
[OK] No Import Sources have been defined

Sync Rules: 1 tests OK
[OK] No Sync Rules have been defined

Director Jobs: 1 tests OK
[OK] No Jobs have been defined
```

</p>
</details>

After a redeploy of the same config via GUI:
<img width="2255" alt="Bildschirmfoto 2019-11-29 um 11 55 20" src="https://user-images.githubusercontent.com/58001001/69865901-da9dd480-12a2-11ea-8aa1-913a3ab7b467.png">

 
## Steps to Reproduce (for bugs)
Trigger config rollout via Director REST API.

## Your Environment
* Director version: 1.7.2 (9c95fb8680f6f389ca24ff6e41d9002185596cb3)
* Icinga Web 2 version: 2.7.3
* Icinga 2 version: r2.11.2-1
* Operating System and version: Debian GNU/Linux 9 (stretch)
* Webserver, PHP versions: apache2, 7.0.33-0+deb9u6

**Comment by ziirish** [comment]
Same issue.

This problem also triggers the *deployment* health check as the deployment is considered as pending.

**Comment by ziirish** [comment]
The problem also occurs when launching a deployment from the CLI with `icingacli director config deploy`

**Comment by Thomas-Gelf** [comment]
Please follow the related/duplicate issue #2045 for updates on this, it also shows a related workaround.
