### ISSUE TITLE
[FEATURE REQUEST] Import Source - REST API - Token based authentication

### ISSUE THREAD

**Issue by dakide** [Icinga/icingaweb2-module-director#2044]
The REST API Import Source doesn't allow for token based authentication.

The only fields are for username and password, but no token based auth.
Is there a way to authenticate via a user/app token?

The source I'm using is PHPIpam - https://github.com/phpipam/phpipam
Their API authentication works like this:
POST to /api/your_app_name/user with basic auth and get a token
GET to any other endpoint along with the token in the header.

Trying to authenticate of course doesn't work since I assume the Director is sending a GET request with basic auth. 
This is the message I get when I set the REST API URL to the token generation endpoint of PHPIpam:
![image](https://user-images.githubusercontent.com/53129107/70343910-558d5f00-1850-11ea-8e10-cde1f21a87e5.png)

**Comment by nordeep** [comment]
I'm using https://github.com/home-assistant/home-assistant as the source. And it would be great to be able to add/change Headers in requests!

**Comment by Thomas-Gelf** [comment]
It's now possible to define custom headers: #2132
