### ISSUE TITLE
Incongruities of deployment health check

### ISSUE THREAD

**Issue by mwaldmueller** [Icinga/icingaweb2-module-director#2045]
The health tab (and the icingacli check) reports a pending deployment (triggered automatically via config job):

![Bildschirmfoto 2019-12-09 um 07 30 58](https://user-images.githubusercontent.com/3973350/70412943-660f2680-1a56-11ea-84c4-2bbbc3bf11b0.png)

But the deployment is already finished:

![Bildschirmfoto 2019-12-09 um 07 31 25](https://user-images.githubusercontent.com/3973350/70412948-6b6c7100-1a56-11ea-9e93-a9208d0f0ac7.png)

The curious thing: After opening the deployment history once in the Director webinterface the status of the check switches to OK.

`
[OK] The last Deployment was successful at 05:30
`

## Your Environment

* Director version (System - About): v1.7.2
* Icinga Web 2 version and modules (System - About): v2.7.3
* Icinga 2 version (`icinga2 --version`): v2.11.2
* Operating System and version: CentOS 7.7
* Webserver, PHP versions: Apache, PHP 7.1.30

**Comment by afeefghannam89** [comment]
ref/NC/682419

**Comment by Thomas-Gelf** [comment]
While v1.8 will fix this, you can use the new Deployment-Status CLI- or REST-API-functionality to trigger a refresh of eventually uncollected stages from Icinga in the meantime:

* [REST API - Deployment Status](https://github.com/Icinga/icingaweb2-module-director/blob/master/doc/70-REST-API.md#deployment-status)
* [Director CLI - Deployment Status](https://github.com/Icinga/icingaweb2-module-director/blob/master/doc/60-CLI.md#deployments-status)

Every time you trigger one of the above, in case there are Deployments with uncollected Startup Logs, Director will connect to Icinga and eventually collect related files.

Cheers,
Thomas
