### ISSUE TITLE
Show indicator for external object 

### ISSUE THREAD

**Issue by Baboon92** [Icinga/icingaweb2-module-director#2050]
## Expected Behavior
Show the indicator for external endpoints. At the moment, it is only available for the master endpoint. Would be an enhancement for a better, detailed overview.

## Your Environment
* Director version (System - About): 1.7.0
* Icinga Web 2 version and modules (System - About): 2.7.3
* Icinga 2 version (`icinga2 --version`): 2.10.5
* Operating System and version: CentOS 7
* Webserver, PHP versions: Apache + PHP-FPM 7.1

**Comment by Thomas-Gelf** [comment]
@Baboon92: sure, could you please elaborate this? What would you expect to see?

**Comment by Baboon92** [comment]
The master is marked with an Icon at the end. We updated Icinga to 2.11.x and had some problems figuring out which endpoint-object is external or not (they are listed together without any mark on them.

In this example, the master is marked **as master** and we need to mark **external**, too
![endpoint_master_icon](https://user-images.githubusercontent.com/44637656/71077642-16340c00-2188-11ea-9748-ed84e23f9c7d.png)

**Comment by Thomas-Gelf** [comment]
Got it, you want to have a visual distinction between external Endpoints and those that have been created in the Director, correct? Should we add an "Object Type" column? A dedicated Icon? If so, how does "external" look like? Different colors? Italic text? So many options :D

**Comment by Thomas-Gelf** [comment]
I opted for the table column.
