### ISSUE TITLE
Searching Director activity log renders "Oops, an error occurred!" Postgres db

### ISSUE THREAD

**Issue by toerkl** [Icinga/icingaweb2-module-director#2057]
## Expected Behavior
Searching activity log should return the results based on my search.

## Current Behavior
Throws the following error when searching for "Load":
SQLSTATE[42883]: Undefined function: 7 ERROR:  operator does not exist: enum_activity_action ~~ unknown
LINE 1: ...."object_type" LIKE '%Load%' OR "l"."action_name" LIKE '%Loa...
                                                             ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts., query was: SELECT COUNT(*) AS cnt FROM director_activity_log AS l WHERE ("l"."author" LIKE '%Load%' OR "l"."object_name" LIKE '%Load%' OR "l"."object_type" LIKE '%Load%' OR "l"."action_name" LIKE '%Load%') (Pdo.php:225)

## Possible Solution/Workaround

Remove "OR "|"."action_name" from query as per below:

**Original (not working):**
SELECT COUNT(*) AS cnt FROM director_activity_log AS l WHERE ("l"."author" LIKE '%postgres%' OR "l"."object_name" LIKE '%postgres%' OR "l"."object_type" LIKE '%postgres%' OR "l"."action_name" LIKE '%postgres%')
**Fixed (working):**
SELECT COUNT(*) AS cnt FROM director_activity_log AS l WHERE ("l"."author" LIKE '%postgres%' OR "l"."object_name" LIKE '%postgres%' OR "l"."object_type" LIKE '%postgres%');
**Original (not working):**
SELECT l.author, l.action_name AS action, l.object_name, l.object_type, l.id, l.change_time, UNIX_TIMESTAMP(l.change_time) AS ts_change_time FROM director_activity_log AS l WHERE ("l"."author" LIKE '%postgres%' OR "l"."object_name" LIKE '%postgres%' OR "l"."object_type" LIKE '%postgres%' OR "l"."action_name" LIKE '%postgres%') ORDER BY change_time DESC, id DESC LIMIT 100
**Fixed (working):**
SELECT l.author, l.action_name AS action, l.object_name, l.object_type, l.id, l.change_time, UNIX_TIMESTAMP(l.change_time) AS ts_change_time FROM director_activity_log AS l WHERE ("l"."author" LIKE '%postgres%' OR "l"."object_name" LIKE '%postgres%' OR "l"."object_type" LIKE '%postgres%') ORDER BY change_time DESC, id DESC LIMIT 100

## Steps to Reproduce (for bugs)

https://<our domain>/icingaweb2/director/config/activities?q=Load
1. Go to Icinga Director, activity log
2. Click the "Search field"
3. Type in for example "Load"

## Your Environment

* Director version (System - About): 
1.7.2
reactbundle: >=0.7.0
ipl: >=0.3.0
incubator: >=0.5.0

* Icinga Web 2 version and modules (System - About):
2.7.3

* Icinga 2 version (`icinga2 --version`):
2.11.2-1

* Operating System and version: 
CentOS Linux release 7.7.1908 (Core)

* Webserver, PHP versions:  
apache httpd-2.4.6-90.el7.centos.x86_64
PHP 7.2.24
PHP 7.1.30

Database:
Postgres version 10.7

**Comment by mdkamijo** [comment]
I have the same problem. Guess everyone has...
Have not this been fixed before, like in this one:
https://github.com/Icinga/icingaweb2-module-director/issues/1408

**Comment by Tenrin1993** [comment]
Same Problem here

**Comment by mdkamijo** [comment]
It’s still the same I guess even if you upgrade to the latest version of Director.

**Comment by Tenrin1993** [comment]
> It’s still the same I guess even if you upgrade to the latest version of Director.

Can confirm since we have the latest version of the director and web

**Comment by Thomas-Gelf** [comment]
Thank you for all the details, I can confirm the issue. Problem here is type safety for enumerated data types in PostgreSQL. While MySQL allows you to query for `enum_column LIKE 'something`, this fails in PostgreSQL. As a workaround, please try to comment/remove `action` from the `ActivityLogTable`'s `$searchColumns` on [this line](https://github.com/Icinga/icingaweb2-module-director/blob/606d715/library/Director/Web/Table/ActivityLogTable.php#L32).

I'd love to find a generic solution for this, preferably without hard-wiring `return $otherSearchColumns if $this->isPostgreSql()`. We'll see.
