### ISSUE TITLE
Cloning an Import Source gives an SQL error

### ISSUE THREAD

**Issue by luciov66** [Icinga/icingaweb2-module-director#2082]
## Expected Behavior
when I select an import source and I click on clone, I expect the inport source to be cloned.

## Current Behavior
when I select an import source and I click on clone, an SQL error is displayed: SQLSTATE[HY093]: Invalid parameter number, no. parameters were bound, query was: SELECT import_row_modifier.* FROM import_row_modifier WHERE (source_id=?) ORDER BY priority ASC

## Possible Solution
the SQL query should be revised.

## Steps to Reproduce (for bugs)
open Director, select Import Data Sources; select an item from the list, for instance "nedi";
then click on Clone; give the clone a new name, then confirm by clicking on Clone.

## Your Environment
* Director version : 1.7.1
* Icinga Web 2 version and modules (System - About):
* Icinga 2 version (`icinga2 --version`):
icinga2 - The Icinga 2 network monitoring daemon (version: r2.10.5-1)

Copyright (c) 2012-2020 Icinga GmbH (https://icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

System information:
  Platform: CentOS Linux
  Platform version: 7 (Core)
  Kernel: Linux
  Kernel version: 3.10.0-957.12.1.el7.x86_64
  Architecture: x86_64

Build information:
  Compiler: GNU 4.8.5
  Build host: 0b9a90f31f19

Application information:

General paths:
  Config directory: /neteye/local/icinga2/conf/icinga2
  Data directory: /neteye/local/icinga2/data/lib/icinga2
  Log directory: /neteye/local/icinga2/data/log/icinga2
  Cache directory: /neteye/local/icinga2/data/cache/icinga2
  Spool directory: /neteye/local/icinga2/data/spool/icinga2
  Run directory: /run/icinga2

Old paths (deprecated):
  Installation root: /usr
  Sysconf directory: /neteye/local/icinga2/conf
  Run directory (base): /run
  Local state directory: /neteye/local/icinga2/data

Internal paths:
  Package data directory: /usr/share/icinga2
  State path: /neteye/local/icinga2/data/lib/icinga2/icinga2.state
  Modified attributes path: /neteye/local/icinga2/data/lib/icinga2/modified-attributes.conf
  Objects path: /neteye/local/icinga2/data/cache/icinga2/icinga2.debug
  Vars path: /neteye/local/icinga2/data/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

* Operating System and version: CentOS Linux release 7.7.1908 (Core)
* Webserver, PHP versions: rh-php71
![importsource-clone-error](https://user-images.githubusercontent.com/40464048/74354487-b8a0f200-4dbb-11ea-8f83-9627df68f2b0.JPG)

**Comment by Thomas-Gelf** [comment]
This should have been fixed with #1997 and released with (v1.7.2](https://github.com/Icinga/icingaweb2-module-director/releases/tag/v1.7.2)
