### ISSUE TITLE
Feature-Request: Add Permission for schedule downtimes

### ISSUE THREAD

**Issue by mkayontour** [Icinga/icingaweb2-module-director#2086]
I try to give certain users the ability to create downtimes for their hosts, with the permissions right now there's no way to give them access only to the downtimes section. 

On the other hand, they could still interfere with hosts which aren't owned by the team. If there was maybe a way to limit them on certain hostgroups, so every filter they write will be something like this:
`where hostgroup.name == team1 and (their custom filter) `

Would this be a permission which could be integrated somehow?

**Comment by Thomas-Gelf** [comment]
Will be implemented, but at a global level only. The proposed filter logic WOULD work (we already tested this with notifications long time ago) but becomes incredibly complicated once you have teams with overlapping permissions.

So this will be an all-or-nothing permission. In addition, we add the possibility to restrict access to Scheduled Downtime rules by name. This makes it easier to track down issues (and figure out who caused them) in case of a misconfigured downtime.
