### ISSUE TITLE
Dependencies in Director not correctly rendered

### ISSUE THREAD

**Issue by Gianlu** [Icinga/icingaweb2-module-director#2088]
## Expected Behavior
Service dependencies with custom vars are correctly created,

## Current Behavior
Configuration file for service dependency is wrong. Some sections are switched.

When trying to configure a service dependency, the preview and the rendered file is:
```
apply Dependency "My children sites" to Service {
    import "base-dependency"

    parent_host_name = host.vars.parent_site
    disable_checks = true
    assign where host.vars.parent_site == "my-parent-site.mydomain.lcl" && service.name == "http-endpoint" && typeof(host.vars.parent_site) == String && typeof(host.vars.parent_site) == String    parent_service_name = "http-endpoint"
}

apply Dependency "My children sites" for (host_parent_name in host.vars.parent_site) to Service {
    import "base-dependency"

    parent_host_name = host_parent_name
    disable_checks = true
    assign where host.vars.parent_site == "my-parent-site.mydomain.lcl" && service.name == "http-endpoint" && typeof(host.vars.parent_site) == Array && typeof(host.vars.parent_site) == Array    parent_service_name = "http-endpoint"
```
The *parent_service_name* keyword is after the *assign* keyword and validation fails.

## Steps to Reproduce (for bugs)
Create a service dependency with a variable as parent.

## Your Environment

* Director version (System - About): 1.7.2
* Icinga Web 2 version and modules (System - About): Icinga Web 2 2.7.3. Modules: doc (2.7.3), fileshipper 1.1.0, grafana 1.3.6, idoreports 0.9.1, icubator 0.5.0, ipl 0.3.0, map 1.1.0, monitoring 2.7.3, pdfexport 0.9.1, react bundle 0.7.0, reporting 0.9.2
* Icinga 2 version (`icinga2 --version`): 2.11.2-1
* Operating System and version: Debian Stretch 9.11
* Webserver, PHP versions: Apache 2.4.25, php 7.0.33-0+deb9u6

**Comment by dgoetz** [comment]
I am still having the same problem with the current master and Apache 7.3.

**Comment by Thomas-Gelf** [comment]
Thanks @dgoetz for your help with reproducing this
