### ISSUE TITLE
Autofill in dependency form fills key and value

### ISSUE THREAD

**Issue by m4k5ym** [Icinga/icingaweb2-module-director#2094]
## Expected Behavior

key

## Current Behavior

key [value]

## Possible Solution

Fill only the key.

## Steps to Reproduce (for bugs)

Create a dependency and try to autofill an assign where clause.

## Your Environment

* Director version (System - About): 1.7.2
* Icinga Web 2 version and modules (System - About): 2.7.3
* Icinga 2 version (`icinga2 --version`): 2.11.2-1
* Operating System and version: SLES 12 SP4
* Webserver, PHP versions: Apache 2.4.23 / PHP 7.2.20

**Comment by m4k5ym** [comment]
#1646

**Comment by m4k5ym** [comment]
References to #1646

**Comment by m4k5ym** [comment]
Nope.

**Comment by Thomas-Gelf** [comment]
Yope ;-) Should have been fixed with #1918 and released with v1.8.0.
