### ISSUE TITLE
custom vars Users notification assignment

### ISSUE THREAD

**Issue by powelleb** [Icinga/icingaweb2-module-director#2100]
## Expected Behavior
script level:
apply Notification "host-alert" to Host {
    import "host-alert-template"
    users = [ host.vars.contact ]
    assign where host.name && ! (host.vars.contact == "")
}

One should be able to reproduce this apply Notification via director.

## Current Behavior
when trying to create the Notification via director, 
"Users" when $host.vars.contact$ is entered returns
The related icinga_user "$host.vars.contact$" doesn't exists: Failed to load icinga_user "$host.vars.contact$" (IcingaObjectMultiRelations.php:222)

Suggestion:   
In drop down for Users: add Custom Expression
and allow Custom Expression to skip the lookup icinga_user and just be a reference variable.

## Your Environment

* Director version (System - About): master (bf0653d238...)
* Icinga Web 2 version and modules (System - About): 2.7.3
* Icinga 2 version (`icinga2 --version`): 2.11.3-1
* Operating System and version: 1804 LTS
* Webserver, PHP versions:

**Comment by Thomas-Gelf** [comment]
Please follow #462
