### ISSUE TITLE
Displaying of groups

### ISSUE THREAD

**Issue by mwaldmueller** [Icinga/icingaweb2-module-director#2113]
Applied (host)groups have a comma prepended:

![hostgroups](https://user-images.githubusercontent.com/3973350/79542119-5bf7d700-808b-11ea-83fa-922c6c01dda8.png)

## Your Environment

* Director version (System - About): v1.7.2
* Icinga Web 2 version and modules (System - About): v2.7.3
* Icinga 2 version (`icinga2 --version`): v.2.11.3
* Operating System and version: CentOS 7
* Webserver, PHP versions: Apache, PHP 7.1

**Comment by Thomas-Gelf** [comment]
This SHOULD have been fixed, was related to an assumption broken by the underlying Html elements

**Comment by Thomas-Gelf** [comment]
Verified, works
