### ISSUE TITLE
Unable to detect your Icinga 2 Core version with Icinga v2.12.0-rc1

### ISSUE THREAD

**Issue by mwaldmueller** [Icinga/icingaweb2-module-director#2114]
It worked a while, but suddenly I'm not able to deploy any more:

![coreversion](https://user-images.githubusercontent.com/3973350/79572422-35529400-80bd-11ea-93c9-98e761bba58b.png)

## Your Environment

* Director version (System - About): v1.7.2
* Icinga Web 2 version and modules (System - About): v2.8.0-rc1
* Icinga 2 version (`icinga2 --version`): v2.12.0-rc1
* Operating System and version: Debian 10
* Webserver, PHP versions: Apache, PHP 7.1

**Comment by mwaldmueller** [comment]
Was a problem on network side, works!

**Comment by gaius1234** [comment]
was the issue resolved?

**Comment by gaius1234** [comment]
Am having the same issue and can't resolve. need help

**Comment by skalec** [comment]
Same Problem.
Core r2.12.0-1
Web: 2.8.2
