### ISSUE TITLE
Background Daemon fails to start

### ISSUE THREAD

**Issue by niemalsnever** [Icinga/icingaweb2-module-director#2120]
## Expected Behavior
Background Daemon should start

## Current Behavior
Background Daemon fails to start with a permissions error
```
icingadirector@icingahost:~$ icingacli director daemon run
Icinga\Exception\IcingaException in /usr/share/php/Icinga/Application/ApplicationBootstrap.php:524 with message: Cannot load application configuration. An exception was thrown: <- Icinga\Exception\NotReadableError in /usr/share/php/Icinga/Application/Config.php:328 with message: Cannot read config file "/etc/icingaweb2/config.ini". Permission denied
Icinga\Exception\IcingaException in /usr/share/php/Icinga/Application/ApplicationBootstrap.php:595 with message: Cannot load user backend configuration. An exception was thrown: <- Icinga\Exception\NotReadableError in /usr/share/php/Icinga/Application/Config.php:328 with message: Cannot read config file "/etc/icingaweb2/authentication.ini". Permission denied
ERROR: Icinga\Exception\NotReadableError in /usr/share/php/Icinga/Application/Config.php:328 with message: Cannot read config file "/etc/icingaweb2/resources.ini". Permission denied
```
Permissions-Listing of /etc/icingaweb2
```
root@icingahost:/etc/icingaweb2# ll
total 48
drwxrws---   5 www-data icingaweb2  4096 Apr 29 01:23 ./
drwxr-xr-x 122 root     root       12288 Apr 29 01:37 ../
-rw-------   1 www-data www-data      54 Apr 29 01:23 authentication.ini
-rw-------   1 www-data www-data     212 Apr 29 01:23 config.ini
drwxr-xr-x   3 www-data www-data    4096 Apr 28 23:29 dashboards/
drwxr-xr-x   2 www-data www-data    4096 Apr 29 01:31 enabledModules/
-rw-------   1 www-data www-data      54 Apr 29 01:23 groups.ini
drwxr-xr-x   6 www-data www-data    4096 Apr 29 01:31 modules/
-rw-------   1 www-data www-data     514 Apr 29 01:24 resources.ini
-rw-------   1 www-data www-data      77 Apr 29 01:23 roles.ini
```

## Your Environment

* Director version (System - About): master
* Icinga Web 2 version and modules (System - About): 2.6.2
* Icinga 2 version (`icinga2 --version`): r2.11.2-1
* Operating System and version: Raspbian buster  
* Webserver, PHP versions: nginx 1.14.2, PHP-FPM 7.3

**Comment by Thomas-Gelf** [comment]
Hi @niemalsnever,

somehow your file permissions have been messed up. Those INI files should be `0660 (-rw-rw----)` and belong to the `icingaweb2` group. This is what the `s`-Flag on the `/etc/icingaweb2` folder should take care of (it's mode `2770`). Seems that someone (or some tool) intervened here.

As a quick fix, please run:

```sh
chgrp -R icingaweb2 /etc/icingaweb2
find /etc/icingaweb2 -type f -name "*.ini" -exec chmod 660 {} \;
find /etc/icingaweb2 -mindepth 1 -type d -exec chmod 2775 {} \;
```

If unsure please take a backup first. In case a configuration management tool has been used to tweak those permissions, please fix this there.

Cheers,
Thomas

**Comment by niemalsnever** [comment]
Hi @Thomas-Gelf,

that worked like a charm, thanks a lot! I managed to accidentially delete my icinga(web) configuration directory, and must've messed up those permissions, trying to get everything back to a working state.
Thanks again for your quick help!

**Comment by Thomas-Gelf** [comment]
You're welcome!
