### ISSUE TITLE
SQLSTATE[42000]: Syntax error or access violation: 1064 when opening a service in Service Set

### ISSUE THREAD

**Issue by roadieman** [Icinga/icingaweb2-module-director#2121]
## Expected Behavior
When opening a service in a service set, I can see and edit the content.

## Current Behavior
An error occurs when opening a service in a service set (service set is attached to a host template).
Klicks: 
"Hosts" > "Host Templates" > "Template Name" > "Services" >" "<Service Name in service set>"

***Output:
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '))' at line 2, query was: SELECT h.object_name AS host_name, hv.varvalue FROM icinga_host_var AS hv
INNER JOIN icinga_host AS h ON h.id = hv.host_id WHERE (hv.varname = '_override_servicevars') AND (h.object_name IN ())

There are no problems with:
Klicks: 
"Services" > "Service Sets" > "Service Set Name" > "Services" > "Servicename"

## Possible Solution

??? 

## Steps to Reproduce (for bugs)
- Add Hosttemplate
- Add Serviceset to the new Hosttemplate
- Open a Service from Serviceset in the new Hosttemplate

## Your Environment

* Director version (System - About): master / 46013a8938e2ff22e2590241713fa60993587129 
* Icinga Web 2 version and modules (System - About): 2.7.3 / 06cabfe8ba28cf545a42c92f25484383191a4e51
* Icinga 2 version (`icinga2 --version`): 2.11.3-1
* Operating System and version: RHEL 7.8
* Webserver, PHP versions: httpd24-httpd-2.4.34-15.el7.x86_64 / php7.2.24
* MariaDB Server: 10.3.22

**Comment by roadieman** [comment]
![image](https://user-images.githubusercontent.com/44840278/81261599-a510ca80-903c-11ea-8711-c241385c8a4f.png)

![image](https://user-images.githubusercontent.com/44840278/81261640-b78b0400-903c-11ea-9424-25589fc75f65.png)

**Comment by wrkhunte** [comment]
How did you fix this @roadieman ?

**Comment by roadieman** [comment]
Never fixed that... Gave up. I removed the service set from the host template and added it to each host individually.
