### ISSUE TITLE
Infrastructure configuration not adding zone to endpoint.

### ISSUE THREAD

**Issue by dbiers** [Icinga/icingaweb2-module-director#2129]
## Expected Behavior
Creating a new endpoint (`salt.biers.int`) and setting to cluster zone "`icinga.biers.int`" should add this endpoint to the "`icinga.biers.int`" cluster/zone.

## Current Behavior
Output suggests that it is not adding the endpoint to the zone.  Configuration deployment fails as this endpoint has not been assigned a zone.

## Possible Solution
Unknown

## Steps to Reproduce (for bugs)
Using Icinga2 director > Infrastructure > Endpoints to add a zone.  Modifying or creating a new endpoint and assigning it to zone "icinga.biers.int" but the configuration does not reflect that it has been added to a zone.

## Your Environment
* Director version (System - About):  
  * `master`
* Icinga Web 2 version and modules (System - About):
  * Icinga Web 2 Version 2.7.3
  * Modules:
    * director (`master`)
    * incubator (`0.5.0`)
    * ipl (`v0.5.0`)
    * monitoring (`2.7.3`)
    * reactbundle (`0.7.0`)
* Icinga 2 version (`icinga2 --version`):
  * Icinga 2 `version: 2.11.3-1`
* Operating System and version:
  * CentOS 8 (Core) x64
* Webserver, PHP versions:
  * Webserver:  `httpd.x86_64  -  2.4.37-16.module_el8.1.0+256+ae790463    @AppStream`
  * PHP:  `PHP 7.2.11 (cli)`

**Comment by dbiers** [comment]
Error from configuration deployment:

```
[2020-05-26 10:31:06 -0500] critical/config: Error: Endpoint 'salt.biers.int' does not belong to a zone.
Location: in [stage]/zones.d/icinga.biers.int/endpoints.conf: 1:0-1:31
[stage]/zones.d/icinga.biers.int/endpoints.conf(1): object Endpoint "salt.biers.int" {
                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[stage]/zones.d/icinga.biers.int/endpoints.conf(2):     host = "salt.biers.int"
[stage]/zones.d/icinga.biers.int/endpoints.conf(3): }

[2020-05-26 10:31:06 -0500] critical/config: 1 error
[2020-05-26 10:31:06 -0500] critical/cli: Config validation failed. Re-run with 'icinga2 daemon -C' after fixing the config.
```

From what I can tell, it is assigned properly within the database:

```
MariaDB [biers_icingadir]> select * from icinga_endpoint;
+----+---------+------------------+-----------------+----------+----------------+------+--------------+------------+
| id | zone_id | object_name      | object_type     | disabled | host           | port | log_duration | apiuser_id |
+----+---------+------------------+-----------------+----------+----------------+------+--------------+------------+
|  1 |       1 | icinga.biers.int | external_object | n        | NULL           | 5665 | 86400        |          1 |
|  3 |       1 | VMs              | template        | n        | NULL           | 5665 | NULL         |          1 |
|  5 |       1 | salt.biers.int   | object          | n        | salt.biers.int | NULL | NULL         |       NULL |
+----+---------+------------------+-----------------+----------+----------------+------+--------------+------------+
3 rows in set (0.000 sec)

MariaDB [biers_icingadir]> select * from icinga_zone;
+----+-----------+------------------+-----------------+----------+-----------+
| id | parent_id | object_name      | object_type     | disabled | is_global |
+----+-----------+------------------+-----------------+----------+-----------+
|  1 |      NULL | icinga.biers.int | external_object | n        | n         |
|  2 |      NULL | global-templates | external_object | n        | y         |
|  3 |      NULL | director-global  | external_object | n        | y         |
+----+-----------+------------------+-----------------+----------+-----------+
3 rows in set (0.000 sec)
```

For editing the endpoint and launching "Preview" button, I see the following:

```
object Endpoint "salt.biers.int" {
    host = "salt.biers.int"
}
```

..which doesn't make sense, as I've assigned the zone to this endpoint.

**Comment by Thomas-Gelf** [comment]
Hi @dbiers,

is `salt` a monitored node (read: Icinga Agent) or an Icinga infrastructure node (read: Satellite)?

Cheers,
Thomas

**Comment by dbiers** [comment]
@Thomas-Gelf `salt.biers.int` is a monitored node.  This is a home lab.

In the past (previous lab), I've had to create separate zones and endpoints for each node I wanted to be monitored, each with their own checks.  This was done without Director, though.

To give an idea of where this is coming from is I have a `disk` check that is running but all monitored nodes are giving the exact same details, which tells me that the `check_disk` is running on the local `icinga.biers.int` master and not the nodes.

I've switched the disk check to include "Run on Agent:  Yes" and this inevitably caused this issue currently.

**Comment by Thomas-Gelf** [comment]
Remove the Zone, no need to care about that complexity when it comes to Icinga Agents with the Director. Just switch **Icinga Agent** to **yes** for this host or in a fitting template. Have a look at the Host's config preview to see it's effect.

Thomas

NB: The Infrastructure tab shows:

> When you feel the desire to manually create Zone or Endpoint objects please rethink this twice. Doing so is mostly the wrong way, might lead to a dead end, requiring quite some effort to clean up the whole mess afterwards.

**Comment by dbiers** [comment]
Hey @Thomas-Gelf -- thanks for the help.  I believe I am on the right track, now.

As a precaution, I've removed all hosts and basically starting from scratch so the configuration deployment worked fine.

I'm now having an issue with self-signed certificates, but I do not believe this has anything to do with the director.

```
[2020-05-26 16:24:35 -0500] information/ApiListener: Reconnecting to endpoint 'icinga.biers.int' via host 'icinga.biers.int' and port '5665'
[2020-05-26 16:24:35 -0500] warning/ApiListener: Certificate validation failed for endpoint 'icinga.biers.int': code 18: self signed certificate
[2020-05-26 16:24:35 -0500] information/ApiListener: New client connection for identity 'icinga.biers.int' to [10.10.11.9]:5665 (certificate validation failed: code 18: self signed certificate)
[2020-05-26 16:24:35 -0500] information/ApiListener: Finished reconnecting to endpoint 'icinga.biers.int' via host 'icinga.biers.int' and port '5665'
```

Thanks again!

**Comment by Thomas-Gelf** [comment]
Glad to hear that it works!
