### ISSUE TITLE
Notifications Sync Rule not working with assign_filter

### ISSUE THREAD

**Issue by EmmaTinten** [Icinga/icingaweb2-module-director#2142]
## Expected Behavior
I want to create a sync rule to import notifications using an assign_filter rule for host and servicegroups.
The sync rule should create the corresponding notifications.

## Current Behavior
Configuring the sync rule property for "assign_filter" results in the following message in the preview: "I can only assign for applied objects or objects with native support for assigments, got object".

## Steps to Reproduce (for bugs)
1. Create a import source to import groups (groupnames, mailadress).
2. Create a sync rule using destinations for object_name, import and apply_to (service).
3. Add the missing property "assign_filter" for the sync rule. Use any expression you wish.

## Your Environment
* Director version (System - About): 1.7.2
* Icinga Web 2 version and modules (System - About): 2.7.3
* Icinga 2 version (`icinga2 --version`):  r2.11.3-1
* Operating System and version: Debian GNU/Linux 10 (buster)
* Webserver, PHP versions: 
  - apache2        2.4.38-3+deb10u3
  - php                2:7.3+69

**Comment by cmusinsky** [comment]
Hi @EmmaTinten,

I ran into a couple similar issues when trying to import Notifications via sync. I outlined what I did to get them working here: https://github.com/Icinga/icingaweb2-module-director/issues/2128#issuecomment-673537723

Hope it helps!

**Comment by Thomas-Gelf** [comment]
The error message is misleading, 63d76ab addresses this
