### ISSUE TITLE
Add support for new Icinga for Windows solution

### ISSUE THREAD

**Issue by LordHepipud** [Icinga/icingaweb2-module-director#2147]
The Icinga Director is right now only shipping with native support of the old PowerShell Module which has been deprecated with version 1.3.0, as we are going to move forward with [Icinga for Windows](https://icinga.com/docs/windows/latest/) instead.

For this reason we should add support for the new installer handling and propably add support for additional Self-Service API configurations, like the IP-Address conversion feature.

For support reasons we should keep the old module shipped and useable with the Director. Maybe it might be possible to split the section for the content a little to have `Old Widows`, `Icinga for Windows` and `Linux` solution on different tabs to keep the site content more clean.

As of integration we have two options in my oppinion:

1. Ship the Kickstart-Script code with configurable source for the code being executed
2. Ship only the install wizard command

## Kickstart Script

```powershell
[Net.ServicePointManager]::SecurityProtocol = "tls12, tls11";
$ProgressPreference = "SilentlyContinue";

$global:IcingaFrameworkKickstartSource = 'https://raw.githubusercontent.com/Icinga/icinga-powershell-kickstart/master/script/icinga-powershell-kickstart.ps1';

$Script = (Invoke-WebRequest -UseBasicParsing -Uri $global:IcingaFrameworkKickstartSource).Content;
$Script += "`r`n`r`n Start-IcingaFrameworkWizard;";

Invoke-Command -ScriptBlock ([Scriptblock]::Create($Script));
```

The location of `https://raw.githubusercontent.com/Icinga/icinga-powershell-kickstart/master/script/icinga-powershell-kickstart.ps1` which is the URL pointing to the actual script for being executed to get everything started and running should in my oppinion be configurable to allow the user easier customization.

## Wizard Command

```powershell
Use-Icinga;
Start-IcingaAgentInstallWizard -DirectorUrl 'url_pointing_to_director' -SelfServiceAPIKey 'your_template_key' -UseDirectorSelfService 1 -OverrideDirectorVars 0 -Reconfigure -RunInstaller;
```

As of now the following content is missing from the Self-Service API which is being asked during installation:

### Question
```
Do you want to convert parent node(s) connection data to IP adresses? (Y/n):
```

### Description
This will convert all hostnames and FQDN's (if possible) to an IP address.

### Example

```
example.com => 93.184.216.34
```

### Argument

```
-ConvertEndpointIPConfig
```

### Values

0: Disabled
1: Enabled

### Question
```
Do you want to install the Icinga PowerShell Plugins? (Y/n):
```

### Description
Will determine if the Icinga for Windows plugins should be installed or not, followed by the question of the download source

### Arguments

```
-InstallFrameworkPlugins
-PluginsUrl
```

### Valuess

**InstallFrameworkPlugins**:
0: No
1: Yes

**PluginsUrl**:
Full path to the Icinga for Windows plugins ZIP file

### Question
```
Do you want to install the Icinga PowerShell Framework as a service? (Y/n):
```

### Description
Will determine if the Icinga for Windows solution should be installed and running as service. This will require to download the service binary for the solution and decide where the binary should be installed to

### Arguments

```
-InstallFrameworkService
-FrameworkServiceUrl
-ServiceDirectory
```

### Valuess

**InstallFrameworkService**:
0: No
1: Yes

**FrameworkServiceUrl**:
Full path to the Icinga for Windows service binary ZIP file

**ServiceDirectory**:
The target directory the service binary will be installed into

Once these three questions are handled  properly and the new solution is implemented, we could move forward with possible additional features and configurations.

What do you think about this?

**Comment by Thomas-Gelf** [comment]
@LordHepipud: work on v1.8 starts next week, in case you have some time let's talk about this!

**Comment by LordHepipud** [comment]
Sounds fine to me. Lets discuss when you are available :)

**Comment by Thomas-Gelf** [comment]
As the API seems to play nice, the UI part was still missing. Now it looks like this:

![director_self-service_icinga4win](https://user-images.githubusercontent.com/553008/100658200-f7099c80-334e-11eb-9fe4-b5a4553303ae.png)
