### ISSUE TITLE
I can't start the icinga director service.

### ISSUE THREAD

**Issue by sergiu-simi** [Icinga/icingaweb2-module-director#2162]
## Current Behavior

When i run this: systemctl start icinga-director.service
I found same issue and i followed from there but still icinga-director won't run.

## Your Environment

* Director version (System - About): 1.7.2
* Icinga Web 2 version and modules (System - About): 2.8.1
* Icinga 2 version (`icinga2 --version`): 2.11.4-1
* Operating System and version: CentOS 8
* Webserver, PHP versions: 7.1.30

-- Unit icinga-director.service has begun starting up.
Jul 22 14:19:26 localhost.localdomain icingadirector[4455]: Started by systemd, notifying watchdog every 5s via /run/systemd/notify
Jul 22 14:19:26 localhost.localdomain icingadirector[4455]: PHP Fatal error:  Uncaught Error: Call to undefined function posix_getpid() in /usr/share/icingaweb2/modules/incubator/vendor/gipfl/systemd/src/NotifySystemD.php:193
Jul 22 14:19:26 localhost.localdomain icingadirector[4455]: Stack trace:
Jul 22 14:19:26 localhost.localdomain icingadirector[4455]: #0 /usr/share/icingaweb2/modules/director/library/Director/Daemon/BackgroundDaemon.php(74): gipfl\SystemD\NotifySystemD->setReady()
Jul 22 14:19:26 localhost.localdomain icingadirector[4455]: #1 /usr/share/icingaweb2/modules/director/library/Director/Daemon/BackgroundDaemon.php(52): Icinga\Module\Director\Daemon\BackgroundDaemon->initialize()
Jul 22 14:19:26 localhost.localdomain icingadirector[4455]: #2 /usr/share/icingaweb2/modules/reactbundle/vendor/react/event-loop/src/Tick/FutureTickQueue.php(46): Icinga\Module\Director\Daemon\BackgroundDaemon->Icinga\Module\Director\Dae
Jul 22 14:19:26 localhost.localdomain icingadirector[4455]: #3 /usr/share/icingaweb2/modules/reactbundle/vendor/react/event-loop/src/StreamSelectLoop.php(181): React\EventLoop\Tick\FutureTickQueue->tick()
Jul 22 14:19:26 localhost.localdomain icingadirector[4455]: #4 /usr/share/icingaweb2/modules/director/library/Director/Daemon/BackgroundDaemon.php(55): React\EventLoop\StreamSelectLoop->run()
Jul 22 14:19:26 localhost.localdomain icingadirector[4455]: #5 /usr/share/icingaweb2/modules/director/application/clicommands/DaemonCommand.php(24): Icinga\Module\Direc in /usr/share/icingaweb2/modules/incubator/vendor/gipfl/systemd/src/
Jul 22 14:19:26 localhost.localdomain icingadirector[4455]: Fatal error: Uncaught Error: Call to undefined function posix_getpid() in /usr/share/icingaweb2/modules/incubator/vendor/gipfl/systemd/src/NotifySystemD.php:193
Jul 22 14:19:26 localhost.localdomain icingadirector[4455]: Stack trace:
Jul 22 14:19:26 localhost.localdomain icingadirector[4455]: #0 /usr/share/icingaweb2/modules/director/library/Director/Daemon/BackgroundDaemon.php(74): gipfl\SystemD\NotifySystemD->setReady()
Jul 22 14:19:26 localhost.localdomain icingadirector[4455]: #1 /usr/share/icingaweb2/modules/director/library/Director/Daemon/BackgroundDaemon.php(52): Icinga\Module\Director\Daemon\BackgroundDaemon->initialize()
Jul 22 14:19:26 localhost.localdomain icingadirector[4455]: #2 /usr/share/icingaweb2/modules/reactbundle/vendor/react/event-loop/src/Tick/FutureTickQueue.php(46): Icinga\Module\Director\Daemon\BackgroundDaemon->Icinga\Module\Director\Dae
Jul 22 14:19:26 localhost.localdomain icingadirector[4455]: #3 /usr/share/icingaweb2/modules/reactbundle/vendor/react/event-loop/src/StreamSelectLoop.php(181): React\EventLoop\Tick\FutureTickQueue->tick()
Jul 22 14:19:26 localhost.localdomain icingadirector[4455]: #4 /usr/share/icingaweb2/modules/director/library/Director/Daemon/BackgroundDaemon.php(55): React\EventLoop\StreamSelectLoop->run()
Jul 22 14:19:26 localhost.localdomain icingadirector[4455]: #5 /usr/share/icingaweb2/modules/director/application/clicommands/DaemonCommand.php(24): Icinga\Module\Direc in /usr/share/icingaweb2/modules/incubator/vendor/gipfl/systemd/src/
Jul 22 14:19:26 localhost.localdomain systemd[1]: icinga-director.service: main process exited, code=exited, status=255/n/a
Jul 22 14:19:26 localhost.localdomain systemd[1]: Failed to start Icinga Director - Monitoring Configuration.
-- Subject: Unit icinga-director.service has failed

**Comment by jwilliams-shadowsoft** [comment]
@sergiu-simi I've had that problem before where it cannot find `posix_getpid()`. There's a prerequisite that you're missing. What OS are you running on?

**Comment by jwilliams-shadowsoft** [comment]
@sergiu-simi If it's RHEL 7 or CentOS 7 you need to have these PHP 7.1 prereq RPMs:
- `rh-php71-php-cli`
- `rh-php71-php-process` (this is the one that has `posix_getpid()` I think)
- `rh-php71-php-common`

Hope that helps!

**Comment by sergiu-simi** [comment]
@jwilliams-shadowsoft Thanks for your reply. I have that packages and don t run.

**Comment by jwilliams-shadowsoft** [comment]
@sergiu-simi The Dec 4, 2018 solution to this completely different module may contain the answer: https://github.com/Icinga/icingaweb2-module-vspheredb/issues/54

**Comment by Thomas-Gelf** [comment]
@jwilliams-shadowsoft: thank you, that's definitively the right answer - `posix_getpid()` requires `php-process`
@sergiu-simi: in case you upgraded to Icinga Web 2.8 you probably got `rh-php73-*` installed, and now your daemon might be using that version. In that case, please also install the corresponding `rh-php73-php-process` package and other [dependencies](https://github.com/Icinga/icingaweb2-module-director/blob/master/doc/02-Installation.md#requirements)

**Comment by sergiu-simi** [comment]
Thank you @jwilliams-shadowsoft ! I saw that post and it doesn’t help me.
@Thomas-Gelf i will see tomorrow if that helps me. Thank you

**Comment by Moxie505** [comment]
@Thomas-Gelf FYI, I also had this issue when getting the icinga2 vagrant boxes (https://github.com/Icinga/icinga-vagrant) started up. Installing rh-php73-php-process fixed it and allowed the director service to start without error. Thanks.

**Comment by sergiu-simi** [comment]
Thank you @Thomas-Gelf and @Moxie505 . I installed rh-php71-php-process and daemon started.
