### ISSUE TITLE
HostGroup edit fails when director/filter/hostgroups is active

### ISSUE THREAD

**Issue by okrouhly** [Icinga/icingaweb2-module-director#2164]
## Expected Behavior
Work as normal editation (at least allow Assign where changes) of given Group to users that has allowed that group by director/filter/hostgroup setting.
Solving that issue may be a partial workarround to issue #2163 

## Current Behavior
An error occures when trying to edit given Host Group:
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'o.object_name' in 'where clause', query was: SELECT h.id FROM icinga_hostgroup AS h WHERE (id = '4') AND (o.object_name IN ('Linux'))

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'o.object_name' in 'where clause'

## Possible Solution
Change function filterHostGroupsQuery default argument to $tableAlias = 'h' instead of current value 'o' at file library/Director/Restriction/HostgroupRestriction.php

## Steps to Reproduce (for bugs)
- Limit user role to access only some Host Groups in Icinga Director by setting director/filter/hostgroups to correct value/name(s) of existing Host Group(s).
- Logout/Login with that role.
- Try to edit given Host Group with that user, an error above will be displayed.

## Your Environment
* Director version (System - About): 1.7.2 or older (tested also on 1.6.2)
* Icinga Web 2 version and modules (System - About): N/A
* Icinga 2 version (`icinga2 --version`): N/A
* Operating System and version: N/A
* Webserver, PHP versions: N/A

**Comment by formorer** [comment]
I am also facing that Problem with a recent Director and the simple fix also fixes it here.
