### ISSUE TITLE
[dev.icinga.com #11685] Permit templates to define "cumulative" properties instead of overwriting them 

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#217]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11685

**Created by greatexpectations on 2016-04-27 08:36:44 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-04-27 08:36:44 +00:00 (in Redmine)_

---

Hello,

basically I am looking for a way to to something like this

    template Host "template-A" {
        groups += [ "Hostgroup-A" ]
    }

    template Host "template-B" {
        groups += [ "Hostgroup-B" ]
    }

    object Host "MyHost" {
        import "template-A"
        import "template-B"
    }

with the expected result of MyHost being assigned to both hostgroups. Right now this does not work in Director; the last imported template will simply overwrite the values defined in previously imported templates.

It would be nice to be able to specify whether a given property should be "cumulative" (e.g. use operator += for lists or dictionaries) or "explicit" (overwriting any previously assigned values).

Kind regards

**Comment by Thomas-Gelf** [comment]
This duplicates #344
