### ISSUE TITLE
[dev.icinga.com #11687] preview result of apply rules in director

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#218]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11687

**Created by ashira07 on 2016-04-27 09:44:26 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-04-27 09:44:26 +00:00 (in Redmine)_

---

It would be nice to have a preview/forcast of defined apply rules within director.
So you can easily see in director which hosts/services are affected by a director apply-rule.

Currently it is difficult to determine, if a director-defined apply-rule really does what it should.

---

**Relations**:

* blocks [#11687](https://dev.icinga.com/issues/11687)

**Comment by Thomas-Gelf** [comment]
Please follow #1986
