### ISSUE TITLE
Blacklisting should be highlighted

### ISSUE THREAD

**Issue by mwaldmueller** [Icinga/icingaweb2-module-director#2183]
Blacklisting of Services needs a deployment and should be highlighted in the activity log.

## Your Environment

* Director version (System - About): 1.7.2
* Icinga Web 2 version and modules (System - About): 2.8.2
* Icinga 2 version (`icinga2 --version`): 2.12.0
* Operating System and version: CentOS 7
* Webserver, PHP versions: Apache, PHP 7.3

**Comment by Thomas-Gelf** [comment]
You're absolutely right. There already is a related issue, closing this in favour of  #1794
