### ISSUE TITLE
Kickstart after removing Zone from zones.conf gives foreign constraint error if child object exists

### ISSUE THREAD

**Issue by jwilliams-shadowsoft** [Icinga/icingaweb2-module-director#2206]
## Expected Behavior
Director should give an error message stating that the Zone to be deleted by Kickstart has existing child objects.

## Current Behavior
SQLSTATE message displayed in red when Kickstarting:

```
SQLSTATE[23000]: Integrity constraint violation: 
1451 Cannot delete or update a parent row: 
a foreign key constraint fails 
("director"."icinga_host", CONSTRAINT "icinga_host_zone" 
FOREIGN KEY ("zone_id") REFERENCES "icinga_zone" ("id") ON UPDATE CASCADE), 
query was: DELETE FROM icinga_zone WHERE (id = '8') (Pdo.php:225)
```

## Possible Solution
An administrator-friendly error should be produced, something like:
```
Kickstart attempted to delete a Zone because it no longer exists in zones.conf.
Child objects exist that prevent deletion:
* Host Template "hosttemplatename"
```

Most monitoring administrators will not understand the meaning of the foreign key constraint error and will not want to dig through the database to find the issue.

## Steps to Reproduce
1. Create a test zone in zones.conf
1. Kickstart
1. Add Host Template into Zone
1. Deploy
1. Remove Zone from zones.conf
1. Reload
1. Kickstart

### Observations:
- From the SQL error message, we know that the `icinga_zone.id` is 9 (`DELETE FROM icinga_zone WHERE (id = '9')`)
- The child objects of Zones are Hosts (either Hosts themselves or Host Templates).
- It does not seem possible to induce a state where you can orphan Endpoints, the other possible child of a Zone.

### Detection:
- Run the following SQL query against the database (substituting the correct `icinga_zone.id` from the error message in for the comparison to `z.id` in the WHERE clause):

    ```
    SELECT 
      z.id, 
      z.object_name, 
      h.id, 
      'Host' child_type,
      h.object_name, 
      h.object_type 
    FROM 
      icinga_zone z,
      icinga_host h
    WHERE 
      z.id = h.zone_id
      AND z.id = 9
    ```

- Test case result:

    ```
    id | object_name | id | child_type | object_name        | object_type
    ---|-------------|----|------------|--------------------|------------
     9 | fake        | 26 | Host       | fake-host-template | template
    ```

### Correction
1. Delete the Host Template shown by the query
1. If deletion is not possible, move the Host Template to different "Cluster Zone".
1. Kickstart should now work. 

**Note:** It may be possible to have other types of orphaned objects that refer to the "Cluster Zone", those are not addresed in this issue.

## Your Environment
* Director version (System - About): 1.7.2
* Database: MySQL / MariaDB
* Icinga Web 2 version and modules (System - About): 2.8.2, ipl 0.7.0, incubator 0.7.0, reactbundle 0.7.0
* Icinga 2 version (`icinga2 --version`): 2.11.5

**Comment by bobapple** [comment]
ref/IC/28725

**Comment by Thomas-Gelf** [comment]
Note for myself: the same should be applied to Commands and Endpoints.

**Comment by Thomas-Gelf** [comment]
Friendlier error message makes it into v1.8, showing dependencies needs more love - #2234 has been created for this

**Comment by TheInfectedFetus** [comment]
Like holy shit how long does it take to fix something as simple as this ?
