### ISSUE TITLE
Import source modifier: DNS PTR lookup crashes

### ISSUE THREAD

**Issue by idandr** [Icinga/icingaweb2-module-director#2207]
## Expected Behavior
When using the import source modifier "Get DNS records of a specific type" for a PTR lookup and using "Set no value (null)" on failure, I want to get the DNS name(s) or a null value.

Just for the record, if someone wants to use this modifier for PTR records: You can not use the format `1.2.3.4` as input. You have to use another modifier before to convert this to `4.3.2.1.in-addr.arpa`. I used regex pattern `/^([0-9]+)\.([0-9]+)\.([0-9]+)\.([0-9]+)$/` and replacement `$4.$3.$2.$1.in-addr.arpa.` (rightmost dot to suppress subdomain searches).

## Current Behavior
Preview fails if a DNS record is missing. Output:
```
dns_get_record(): A temporary server error occurred.

#0 [internal function]: Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(Integer, String, String, Integer, Array)
#1 /usr/share/icingaweb2/modules/director/library/Director/PropertyModifier/PropertyModifierDnsRecords.php(56): dns_get_record(String, Integer)
#2 /usr/share/icingaweb2/modules/director/library/Director/Objects/ImportSource.php(373): Icinga\Module\Director\PropertyModifier\PropertyModifierDnsRecords->transform(String)
#3 /usr/share/icingaweb2/modules/director/library/Director/Objects/ImportSource.php(316): Icinga\Module\Director\Objects\ImportSource->applyPropertyModifierToRow(Object(Icinga\Module\Director\PropertyModifier\PropertyModifierDnsRecords), String, Object(stdClass))
#4 /usr/share/icingaweb2/modules/director/library/Director/Web/Table/ImportsourceHookTable.php(101): Icinga\Module\Director\Objects\ImportSource->applyModifiers(Array)
#5 /usr/share/icingaweb2/modules/incubator/vendor/gipfl/icingaweb2/src/Table/SimpleQueryBasedTable.php(29): Icinga\Module\Director\Web\Table\ImportsourceHookTable->prepareQuery()
#6 /usr/share/icingaweb2/modules/incubator/vendor/gipfl/icingaweb2/src/Table/SimpleQueryBasedTable.php(15): gipfl\IcingaWeb2\Table\SimpleQueryBasedTable->getQuery()
#7 /usr/share/icingaweb2/modules/incubator/vendor/gipfl/icingaweb2/src/Table/QueryBasedTable.php(56): gipfl\IcingaWeb2\Table\SimpleQueryBasedTable->getPaginationAdapter()
#8 /usr/share/icingaweb2/modules/incubator/vendor/gipfl/icingaweb2/src/Table/QueryBasedTable.php(255): gipfl\IcingaWeb2\Table\QueryBasedTable->getPaginator(Object(gipfl\IcingaWeb2\Url))
#9 /usr/share/icingaweb2/modules/director/application/controllers/ImportsourceController.php(149): gipfl\IcingaWeb2\Table\QueryBasedTable->renderTo(Object(Icinga\Module\Director\Controllers\ImportsourceController))
#10 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Director\Controllers\ImportsourceController->previewAction()
#11 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch(String)
#12 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#13 /usr/share/php/Icinga/Application/Web.php(300): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#14 /usr/share/php/Icinga/Application/webrouter.php(99): Icinga\Application\Web->dispatch()
#15 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#16 {main}
```

## Possible Solution
I tried the suggestion on https://stackoverflow.com/a/44395269 for a quick fix, prefixing dns_get_record() with an @-sign in line 56 of PropertyModifierDnsRecords.php. I have to wait for some DNS timeouts (be patient or lower the limits on your local resolver), but it works.

## Steps to Reproduce (for bugs)
Define an import source, that gives you an IP address which is not resolvable by your local resolver. Use the modifier for this field and try to view the preview.

## Your Environment
* Director version (System - About): 1.7.2

**Comment by Thomas-Gelf** [comment]
May I ask why you're not using the "Get host by name" property modifier?

**Comment by Thomas-Gelf** [comment]
Regarding error handling:

* DNS server timeouts should not be the norm. Letting the whole import run fail in such case doesn't feel wrong to me
* `dns_get_record()` is not the best method when it goes to error handling, as it doesn't allow to distinct between different error conditions. But it usually shouldn't show warnings (and therefore trigger Exceptions, as we're strict about warnings). Could you please let me know a query/type/resolver combination that leads to such behaviour? Eventually combined with the PHP version being in use
* preview shouldn't completely fail, the tabs should still be shown. This has already been addressed with 7f1018a

I'm absolutely not a fan of error suppression via `@`, but of course sometimes we're forced to do so.

**Comment by idandr** [comment]
> May I ask why you're not using the "Get host by name" property modifier?

It uses gethostbyname(), which makes a hostname to IP address lookup (A record). I would like to do the reverse, IP address to hostname lookup (PTR record), which needs gethostbyaddr().

Adding a modifier "Get host by address" for reverse lookups could be a comfortable solution. One could even skip the additional modifier which transforms "1.2.3.4" to "4.3.2.1.in-addr.arpa". This might be a feature request which qualifies for its own ticket.

> Regarding error handling:

* You are right, our DNS timeout is caused by a missing reverse lookup zone in our internal DNS server. Not, as I thought, by a missing DNS PTR record in an existing reverse lookup zone. We will fix this in the DNS server.
* I can reproduce the behaviour with a PTR query for an internal IP address and the setting given in the last point. The system is Debian 10, local resolver queries going to our internal Microsoft DNS servers (plural for redundancy only) which should be authoritative. PHP version is 7.3.
* Looks much better now with the cited commit. Tabs are shown and, very helpful, the offending IP address is shown as argument to dns_get_record(). Great!

Given the already implemented new error output and your valid remark in the first point, I'm happy with the status now. If you want to find out more about the second point, I'll try to help. Otherwise feel free to close this ticket.

**Comment by Thomas-Gelf** [comment]
> > May I ask why you're not using the "Get host by name" property modifier?
> 
> It uses gethostbyname(), which makes a hostname to IP address lookup (A record). I would like to do the reverse, IP address to hostname lookup (PTR record), which needs gethostbyaddr().

Sorry, my fault - I always confuse them :laughing:

> Adding a modifier "Get host by address" for reverse lookups could be a comfortable solution. One could even skip the additional modifier which transforms "1.2.3.4" to "4.3.2.1.in-addr.arpa". This might be a feature request which qualifies for its own ticket.

Done: #2210

> Given the already implemented new error output and your valid remark in the first point, I'm happy with the status now. If you want to find out more about the second point, I'll try to help. Otherwise feel free to close this ticket.

Deal. As we plan to ship some more advanced fancy DNS features sooner or later, I'll close this for now.
