### ISSUE TITLE
Improve error message when import is missing

### ISSUE THREAD

**Issue by rndmh3ro** [Icinga/icingaweb2-module-director#2224]
## Expected Behavior

When creating a host via the API, the error message when an import is missing could be more helpful.
Maybe something like this:
```
    "error": "Failed to load the import icinga_command \"footlemp\""
```

## Current Behavior
I want to create a Command with an import. When this import does not exist, a 404 error message is thrown:
```
> curl  'http://127.0.0.1/icingaweb2/director/command?name=foo' -H 'Accept: application/json' -H 'Authorization: Basic aWNpbmdhYWRtaW46aWNpbmdh' -d '{
>     "command": "foo",
>     "imports": [
>         "footlemp"
>     ],
>     "methods_execute": "PluginCheck",
>     "object_name": "foo",
>     "object_type": "object"
> }'
{
    "error": "Failed to load icinga_command \"footlemp\""
}
```

## Possible Solution

Improve the error message.

## Steps to Reproduce (for bugs)
Run this command against you icinga instance:

```
curl  'http://127.0.0.1/icingaweb2/director/command?name=foo' -H 'Accept: application/json' -d '{
    "command": "foo",
    "imports": [
        "footemp"
    ],
    "methods_execute": "PluginCheck",
    "object_name": "foo",
    "object_type": "object"
}'
```

## Your Environment

* Director version (System - About): 1.7.2
* Icinga Web 2 version and modules (System - About): 2.8.1

**Comment by Thomas-Gelf** [comment]
Hi @rndmh3ro,

any suggestions? Currently the error message is:

>  **Failed to load icinga_command "footlemp"**

404 (object not found) also doesn't seem wrong to me. What would you expect to read in such case?

Regards,
Thomas

**Comment by rndmh3ro** [comment]
Thanks @Thomas-Gelf for your answer.

> 404 (object not found) also doesn't seem wrong to me

Definetly! They're not wrong, but for me (and some of my colleagues) hard to grasp.

> What would you expect to read in such case?

Like I said in the initial issue, maybe it would be helpful to include in the message, that it is an import that fails:

```
"error": "Failed to load the import icinga_command \"footlemp\""
                         ~~~~~~~~~~
```

**Comment by Thomas-Gelf** [comment]
Ok, thanks for clarification! What do you think about this variant:

    Unable to load parent referenced from command "foo", failed to load icinga_command "footlemp"

**Comment by rndmh3ro** [comment]
Sounds good to me! This definetly makes it clearer what is missing.

**Comment by Thomas-Gelf** [comment]
Fixed. I declared this being a "bugfix", so it will be part of the upcoming 1.8.1 patch release ;-)

**Comment by Thomas-Gelf** [comment]
Just for the records, the following two scenarios are being dealt with:

### Referencing a missing parent

    Unable to load parent referenced from command "check_something", failed to load icinga_command "Default Command"

### Referencing a missing related object

    Unable to load object referenced from service "CPU Load", failed to load icinga_host "www.example.com"
