### ISSUE TITLE
Call to undefined method ipl\Html\Text::addAttributes() when host overrides groups

### ISSUE THREAD

**Issue by mdetrano** [Icinga/icingaweb2-module-director#2253]
## Expected Behavior

Host page should display host form.

## Current Behavior

Error is shown:

Uncaught Error: Call to undefined method ipl\Html\Text::addAttributes() in /usr/share/icingaweb2/modules/director/application/forms/IcingaHostForm.php:233
Stack trace:
#0 /usr/share/icingaweb2/modules/director/application/forms/IcingaHostForm.php(60): Icinga\Module\Director\Forms\IcingaHostForm->addGroupsElement()
...

## Steps to Reproduce (for bugs)

Create a host template with more than one hostgroup.  Add a host that uses that template.  Set host groups locally for the host itself.  Reload Host form page.

Note: if only one hostgroup is configured in the host template, everything seems to work fine.

## Your Environment

* Director version (System - About): 1.8.0 (master branch)
* Icinga Web 2 version and modules (System - About): 2.8.2
* Icinga 2 version (`icinga2 --version`): 2.12.2
* Operating System and version: Centos 7,8
* Webserver, PHP versions: 7.x

**Comment by mdetrano** [comment]
Ok, looks like this is work in progress (with a strikeGroupLinks function taking shape).  
Problem seems to come down to createHostgroupLinks() returning not just Link objects but plain text commas if the list has more than one group.
Quick fix is to add in application/forms/IcingaHostForm.php,  around line 233:

```
foreach ($links->getContent() as $link) {
                    if (get_class($link) != 'ipl\Html\Link') continue;  // <--- skip addAttributes on ipl\Html\Text objects
                    $link->addAttributes([

```

**Comment by Thomas-Gelf** [comment]
Thanks @mdetrano for reporting this and for tracking it down!
