### ISSUE TITLE
DeploymentStatus: invalid byte sequence for encoding "UTF8"

### ISSUE THREAD

**Issue by ziirish** [Icinga/icingaweb2-module-director#2260]
## Expected Behavior

When calling `DeploymentStatus` either through the API or through the CLI with provided config checksums, I expect the result to be as documented in #2187 

## Current Behavior

Instead, I'm getting the following error:

```
$ icingacli director config deploymentstatus --configs a289a1212e7929f0d75de272570b20ef2ecdba8e
ERROR: Zend_Db_Statement_Exception in /usr/share/icingaweb2/library/vendor/Zend/Db/Statement/Pdo.php:225 with message: SQLSTATE[22021]: Character not in repertoire: 7 ERROR:  invalid byte sequence for encoding "UTF8": 0xa2, query was: SELECT LOWER(ENCODE(l.config_checksum, 'hex')) AS checksum, l.startup_succeeded AS deployed FROM director_deployment_log AS l WHERE (l.config_checksum IN ('���!.y)��]�rW
                       �.ͺ�'))
```

## Possible Solution

Removing the use of the `hex2bin` function [here](https://github.com/Icinga/icingaweb2-module-director/blob/0544b57db4273976d938ee48b21a57d7caf8c483/library/Director/Deployment/DeploymentStatus.php#L83) solved the problem for me. Note that I'm using postgresql as the database engine.

## Steps to Reproduce (for bugs)

Check the status of a **given** deployment with a postgresql DB. (you must provide the `--configs` flag in order to trigger the bug)

## Your Environment

* Director version (System - About): 1.8.0
* Icinga Web 2 version and modules (System - About): 2.7.3
* Icinga 2 version (`icinga2 --version`): r2.12.3-1
* Operating System and version: Debian 10
* Webserver, PHP versions: 7.3.19-1~deb10u1
* Postgresql version: 11.7-0+deb10u1

**Comment by mdkamijo** [comment]
We are seeing the same thing but not with the same error. The error we get is:
```
icingacli director config deploymentstatus --configs 2cb3bf94-ed64-41fa-af1a-7455fd53d3e8
ERROR: ErrorException in /usr/share/icingaweb2/modules/director/library/Director/Deployment/DeploymentStatus.php:83 with message: hex2bin(): Input string must be hexadecimal string
```

In our case we just upgraded Director and incubator and then the issue started.

I changed line 83 in /usr/share/icingaweb2/modules/director/library/Director/Deployment/DeploymentStatus.php:
```
- $binaryConfigChecksums[$singleConfigChecksum] = hex2bin($singleConfigChecksum);
+ $binaryConfigChecksums[$singleConfigChecksum] = $singleConfigChecksum;
```

and then things started to work as normal. All pending deploys were ok.

**Comment by Thomas-Gelf** [comment]
@mdkamijo: config hashes are SHA1 checksums,  they're 20 bytes long, and you need 40 ascii/hex characters to represent such a checksum. Your parameter is formatted like a UUID and only 16 bytes (32 characters plus dashes) long. The error will vanish once you remove your dashes, but then the given checksum is still to short.
