### ISSUE TITLE
Modify action link not working for service apply rules

### ISSUE THREAD

**Issue by blindzero** [Icinga/icingaweb2-module-director#2261]
## Expected Behavior
The action link "Modify" should also work for services based on service apply rules.

## Current Behavior
The value $config$ of a service apply rule is used for the display name (which is very good thing).
As this service display name is then used to open the "modify" action link the service can not be found.
![image](https://user-images.githubusercontent.com/13959569/103483605-ae7b4e00-4de8-11eb-8514-7dbc34113608.png)

## Steps to Reproduce (for bugs)
* create service by service apply rule
* open service in overview
* click on "modify" action link

## Your Environment
* Director version (System - About): 1.7.2
* Icinga Web 2 version and modules (System - About): 2.8.2
* Icinga 2 version (`icinga2 --version`): r2.12.3-1
* Operating System and version: Ubuntu 20.04
* Webserver, PHP versions: Apache/2.4.41 + PHP 7.4.3

**Comment by log1-c** [comment]
Hi,
the problem is not the apply rule, but the apply _for_.
Here is a issue where this is already discussed and it is on the wishlist for the one of the next versions:
https://github.com/Icinga/icingaweb2-module-director/issues/831

**Comment by blindzero** [comment]
@log1-c 
thanks, closing as duplicate to #831
