### ISSUE TITLE
Director Automation with Authorization header

### ISSUE THREAD

**Issue by blindzero** [Icinga/icingaweb2-module-director#2262]
## Expected Behavior
Calling an REST API for automation import sources with an authorization header (key), not username / password.
Some background: I wanted to import objects from our Azure environment. As Azure's Graph API is only accepting header authentication I can not realize this with director's automation.

## Current Behavior
A username / password login must be supplied for REST API to work.

## Possible Solution
- select authorization mode when chosing REST API as automation import source
- login: brings username / password field (as-is)
- header: brings "header name" and "key" field

**Comment by Thomas-Gelf** [comment]
Are you running v1.8? Username and Password shouldn't be required, Custom Headers are now possible

**Comment by blindzero** [comment]
Great, thanks. Solved with 1.8
