### ISSUE TITLE
PHP-FPM Failure

### ISSUE THREAD

**Issue by mabfuss** [Icinga/icingaweb2-module-director#2278]
Hi,
i have get an error in the icinga2 director. Anybody know this problem?

This error comes if i select a host in icinga director. In the services tab i select not a single service, rather a service, which is part of a service-set and bound to a hostgroup.

In the director gui i get the following error messages:
```

Uncaught Error: Call to undefined method Icinga\Module\Director\Resolver\OverriddenVarsResolver::resolveFor() in /usr/share/icingaweb2/modules/director/library/Director/Objects/DirectorDatafield.php:260
Stack trace:
#0 /usr/share/icingaweb2/modules/director/library/Director/Objects/DirectorDatafield.php(240): Icinga\Module\Director\Objects\DirectorDatafield->applyObjectData(Object(Icinga\Module\Director\Web\Form\Element\Text), Object(Icinga\Module\Director\Forms\IcingaServiceForm))
#1 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/IcingaObjectFieldLoader.php(380): Icinga\Module\Director\Objects\DirectorDatafield->getFormElement(Object(Icinga\Module\Director\Forms\IcingaServiceForm))
#2 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/IcingaObjectFieldLoader.php(183): Icinga\Module\Director\Web\Form\IcingaObjectFieldLoader->createElements(Object(Icinga\Module\Director\Forms\IcingaServiceForm))
#3 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/IcingaObjectFiel

#0 [internal function]: Icinga\Application\Web->Icinga\Application\{closure}()
#1 {main}
```

It seems to be an error with php-fpm(systemctl status php-fpm).

journalctl -u php-fpm
`Jan 28 14:19:45 HOSTNAME icingaweb2[248257]: ErrorException in /usr/share/icingaweb2/modules/director/library/Director/Objects/DirectorDatafield.php:260 with message: Uncaught Error: Call to undefined method>`

-     Icinga Web 2 version 2.8.2
-     Business Process 2.3.0
-     FileShipper 1.2.0
-     Grafana 1.3.6
-     Incubator 0.6.0
-     IPL 0.5.0
-     Map 1.1.0
-     MapDataType 0.1.0
-     Nagvis 1.1.1
-     Reactbundle 0.8.0
-     Reporting 0.10.0
-     x509 1.0.0
-     Chrome 81.0.x
-     Icinga 2 2.12.3
-     PHP 7.2.24
-     CentOS 8.3.2011
-     php-7.2.24-1
-     Apache 2.4.37

**Comment by geotekberlin** [comment]
Same error here. with director-master dated 2021-02-28. Reverting back to release 1.8.0 resolved the issue for me

**Comment by Thomas-Gelf** [comment]
Thanks for reporting this! I initially haven't been able to reproduce it - but then finally understood that I forgot to push a modification related to a recent change.
