### ISSUE TITLE
Feature request: "Just disable" as third option to "Purge"

### ISSUE THREAD

**Issue by widhalmt** [Icinga/icingaweb2-module-director#2285]
## Expected Behavior

When a host is just temporarily removed from a sync source we want to keep it in Director but have it `disabled`.

## Current Behavior

When a host is removed from the data source we're syncing from, there's only the option to choose between `yes` and `no` for purging.

## Possible Solution

Add a third option to `purge`: Just disable

## Extra information

This is especially useful for environments where hosts can be temporarily deactivated in a CMDB and the CMDB always reacts with not showing the host anymore in the export. When you added some manual information to the host that's always lost when the host is "resynced". Given, most checks etc. should work via `apply` rule but when there are manual modifications like custom variables it would be nice to have an option to keep it.

ref/NC/702004

**Comment by Thomas-Gelf** [comment]
I like this idea!

**Comment by rbnick** [comment]
very good approach, i like it !

**Comment by Thomas-Gelf** [comment]
Has been implemented.

**Comment by khmuth** [comment]
@Thomas-Gelf 
Thank you very much for the quick implementation!

**Comment by Thomas-Gelf** [comment]
You're welcome!
