### ISSUE TITLE
[dev.icinga.com #11759] Allow to set command_endpoint in host and service templates

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#229]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11759

**Created by tgelf on 2016-05-10 13:59:18 +00:00**

Assignee: _tgelf_
Status: _Resolved_  (closed on _2016-06-28 01:25:04 +00:00_)
Target Version: _1.1.0_
Last Update: _2016-06-28 01:25:04 +00:00 (in Redmine)_

---

This happens implicitly for agents, however setting it manually should be possible in the Agent/Zone section of host and service templates. Use case: let master nodes ping each other from "the other node".

**Changesets**

_2016-06-28 01:21:39 +00:00_ by _tgelf_ 79600c26266c38375d8584198896f2606fa1ff3f

    IcingaHostForm: allow to set command_endpoint
    
    fixes #11759

**Comment by cbnorman** [comment]
it looks like this was resolved with `command_endpoint = host_name`  can we make it a host vars. i need to specify endpoints for my network devices so they dont run on the master, but it cant be host_name as the host is a switch which cant have an agent installed. vars.client_endpoint is in the documentation so i can assign a endpoint for all services of a switch.

**Comment by amitkumar912** [comment]
It looks like if you try to Update a `command_endpoint` on a device via the Director API, it returns with a `304 NOT MODIFIED`, the only way I've gotten it to work was to also update the Display name. So it appears that its not passing the validation when trying to modify this field after its been created.
