### ISSUE TITLE
basket import of commands

### ISSUE THREAD

**Issue by koerb** [Icinga/icingaweb2-module-director#2307]
## Expected Behavior
importing basket with datafields assigned to commands

## Current Behavior
running into:

ERROR: RuntimeException in /usr/share/icingaweb2/modules/director/library/Director/Data/Db/DbObject.php:853 with message: Storing director_datafield[] failed: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails ("director"."director_datafield", CONSTRAINT "director_datafield_category" FOREIGN KEY ("category_id") REFERENCES "director_datafield_category" ("id") ON UPDATE CASCADE), query was: INSERT INTO director_datafield (category_id, varname, caption, description, datatype, format) VALUES (?, ?, ?, ?, ?, ?) {array (
  'id' => NULL,
  'category_id' => '5',
  'varname' => 'ps_command',
  'caption' => 'PS Checkcommand',
  'description' => NULL,
  'datatype' => 'Icinga\\Module\\Director\\DataType\\DataTypeArray',
  'format' => NULL,
)}

## Your Environment
* Director version (System - About): 1.8.0
* Icinga Web 2 version and modules (System - About): 2.8.2
* Icinga 2 version (`icinga2 --version`): 2.12.3
* Operating System and version: CentOS 8.3.2011
* Webserver, PHP versions:  Apache/2.4.37, 7.2.24

**Comment by cmusinsky** [comment]
I ran into this as well- it seems the new datafield category feature has an issue where a category is not added to a basket if a datafield is assigned to it. The 2 workarounds I have found are:
1. Manually create the datafield category in the Icinga Director instance you are importing to. The caveat here is that the ID of the datafield category seems to be automatically generated, so this has to line up with the basket export. You could probably manually insert the datafield category into the DB if you'd like.
2. Remove the datafield category from the datafield the command is using and re-snapshot the basket. This should import correctly without the datafield category.

**Comment by Thomas-Gelf** [comment]
Should have been fixed with v1.9. Please create new snapshots for your baskets, as Category IDs in your old baskets will be ignored.

**Comment by Thomas-Gelf** [comment]
Please see #2256 for related changes
