### ISSUE TITLE
SQL Error when displaying Data Fields

### ISSUE THREAD

**Issue by Tommi2Day** [Icinga/icingaweb2-module-director#2310]
## Expected Behavior

show list of Data Fields

## Current Behavior

> Oops, an error occurred!
> SQLSTATE[42803]: Grouping error: 7 ERROR:  column "dfc.category_name" must appear in the GROUP BY clause or be used in an aggregate function
> LINE 1: ...varname, df.caption, df.description, df.datatype, dfc.catego...
>                                                              ^, query was: SELECT COUNT(*) AS cnt FROM (SELECT df.id, df.varname, df.caption, df.description, df.datatype, dfc.category_name AS category, SUM(used_fields.cnt) AS assigned_fields, SUM(used_vars.cnt) AS assigned_vars FROM director_datafield AS df
>  LEFT JOIN director_datafield_category AS dfc ON df.category_id = dfc.id
>  LEFT JOIN (SELECT COUNT(*) AS cnt, icinga_command_field.datafield_id FROM icinga_command_field GROUP BY datafield_id UNION ALL SELECT COUNT(*) AS cnt, icinga_host_field.datafield_id FROM icinga_host_field GROUP BY datafield_id UNION ALL SELECT COUNT(*) AS cnt, icinga_notification_field.datafield_id FROM icinga_notification_field GROUP BY datafield_id UNION ALL SELECT COUNT(*) AS cnt, icinga_service_field.datafield_id FROM icinga_service_field GROUP BY datafield_id UNION ALL SELECT COUNT(*) AS cnt, icinga_user_field.datafield_id FROM icinga_user_field GROUP BY datafield_id) AS used_fields ON used_fields.datafield_id = df.id
>  LEFT JOIN (SELECT COUNT(*) AS cnt, icinga_command_var.varname FROM icinga_command_var GROUP BY varname UNION ALL SELECT COUNT(*) AS cnt, icinga_host_var.varname FROM icinga_host_var GROUP BY varname UNION ALL SELECT COUNT(*) AS cnt, icinga_notification_var.varname FROM icinga_notification_var GROUP BY varname UNION ALL SELECT COUNT(*) AS cnt, icinga_service_var.varname FROM icinga_service_var GROUP BY varname UNION ALL SELECT COUNT(*) AS cnt, icinga_service_set_var.varname FROM icinga_service_set_var GROUP BY varname UNION ALL SELECT COUNT(*) AS cnt, icinga_user_var.varname FROM icinga_user_var GROUP BY varname) AS used_vars ON used_vars.varname = df.varname GROUP BY df.id,	df.varname ORDER BY caption ASC) AS t (Pdo.php:225)

## Possible Solution

change line 88 in modules/director/library/Director/Web/Table/DatafieldTable.php from
`)->group('df.id')->group('df.varname')->order('caption ASC');`
to
 `)->group('df.id')->group('df.varname')->group('dfc.category_name')->order('caption ASC');`

## Steps to Reproduce (for bugs)

Click on "Define Data Fields", Error will come up 

## Your Environment

* Director version (System - About): 
 > master Git 302c9b645d901567df5433657487701627396d0d

* Icinga Web 2 version and modules (System - About):
 >setup : 2.6.2
 > director: master
 >incubator  0.6.0
 > ipl  v0.5.0
 >monitoring  2.6.2
 > reactbundle  0.9.0
* Icinga 2 version (`icinga2 --version`):
version: r2.12.3-1)
* Operating System and version:
 >Platform: Raspbian GNU/Linux
 >Platform version: 10 (buster)
 >Kernel: Linux
 >Kernel version: 5.10.17-v7l+
* Webserver, PHP versions:
 > Apache 2.4.38-3+deb10u4
 >PHP 7.3.27-1~deb10u1

**Comment by Guentha** [comment]
I had the same issue, solution solved it for me.

**Comment by Thomas-Gelf** [comment]
Thank you!
