### ISSUE TITLE
Director: Allow functions like .split on host fields custom vars

### ISSUE THREAD

**Issue by radioactive9** [Icinga/icingaweb2-module-director#2319]
Hello @Thomas-Gelf 

A very simple requirement is to cut the FQDN and put it in a host.vars.CustomField and display just the hostname.
This helps in lot of other places. 
Like for example if we have that in a CustomField with just hostname we can refer it to some log config files in some log monitoring service where the log config is {hostname}-{dbinstance}.cfg. Because FQDN is already being pushed while onboarding it makes perfect sense to be able to cut to hostname within Director. I dont know if this is already possible today - but based on community discussion it seems it is good to have
Ref:
https://community.icinga.com/t/director-splitting-hostname-from-fqdn/7198/9

**Comment by Thomas-Gelf** [comment]
Hi @radioactive9,

a DSL-based solution is possible only in Command Arguments, please see [this issue](https://github.com/Icinga/icingaweb2-module-director/issues/496) for a full example. For various reasons (security concerns, Apply Rules pre-calculation) there are no plans to allow DSL in custom vars. But this is should not be required for your use-case, just put the corresponding logic in your corresponding CheckCommand's argument. In case you do not need this for all checks involving that command: either clone it or create a new one inheriting from the existing one and override just the required argument.

In case you insist on having a Custom Variable with the short host name, the Director-way of doing so is via Property Modifiers at Import time. This has also been suggested in the linked discussion. As you're not using that way to onboard your hosts, this logic belongs to your very own onboarding process: just create the hosts with the required properties.

If this for whatever reason might not be possible, there is another option you might want to consider: create an Import Source importing Hosts from the Director and create an Update-Only Sync rule just setting this variable on existing Hosts.

Cheers,
Thomas
