### ISSUE TITLE
Problems with cloned service sets in the director (rf/NC/723918)

### ISSUE THREAD

**Issue by tbauriedel** [Icinga/icingaweb2-module-director#2323]
Hello,
there is a bug in the service sets.

- Create a service set
- Apply to a host
- Clone the created service set
- Deactivate the original service set on the host
- Assign the cloned service set to the same host

If you now go to the service outside the director and select "Modify", you will be sent to the original (disabled) service set instead of the clone (enabled).

To get rid of the error, the name of the services have to be changed. If the names are the same, it refers incorrectly.

Icinga Web 2 Version: 2.8.2
Icinga 2 Director Version: 1.8.0

Regards
Tobias Bauriedel

**Comment by bobapple** [comment]
ref/IP/33447

**Comment by Thomas-Gelf** [comment]
Have been able to reproduce this, @bobapple assisted me with doing so. Problem: the _director/host/findservice_ URL (as being used by the monitoring module Hook) points to the **first** of to services with the same name, belonging to different sets. The fact that one of them might have been disabled isn't respected.
