### ISSUE TITLE
[Feature-Request] Extending Source Expression with choice for custom string or dropdown menu for boolean values 

### ISSUE THREAD

**Issue by Wintermute2k6** [Icinga/icingaweb2-module-director#2325]
## Expected Behavior
In Sync, there is the custom expression field which allows for a custom string. It might be useful to have a choice here beside custom strings with some pre-defined options via dropdown like, boolean values or the choice to link to a pre-defined datalist.

## Current Behavior
There is the only choice of a custom string.

## Possible Solution
Maybe implement the additional option for a dropdown choice between custom string and other pre-defined options.

## Steps to Reproduce (for bugs)
None, the custom string option is a default at the moment in the Sync in the source expression field.
 

![image001](https://user-images.githubusercontent.com/7203835/118772768-64b96e80-b884-11eb-97c9-fc339966fc10.png)

ref/NC/724322

**Comment by bobapple** [comment]
ref/NC/724322

ref/IP/33669

**Comment by Thomas-Gelf** [comment]
Generating values in Sync which do not exist at Import time feels wrong to me. You can address this with the "Make Boolean" (Convert to a boolean value) property modifier as follows:

* pick an arbitrary column for a new Property Modifier, **Convert to a boolean value**
* key column is perfect, as this should neither provide NULL values nor any of the following strings: 0, false, n, no, 1, true, y or yes
* choose a meaningful Target Property name, like **false**
* pick one of the options "Set false", "Set true" or "Set null" for **Invalid Properties**

![director_import-provide-boolean-column](https://user-images.githubusercontent.com/553008/199661566-d708ea2e-3081-4361-8aaf-f75a4e4aee9e.png)

Now this new column can be used in your Sync Rules. Hope this helps!

Cheers,
Thomas
