### ISSUE TITLE
adding hostgroup to host causes exception

### ISSUE THREAD

**Issue by wrkhunte** [Icinga/icingaweb2-module-director#2326]
## Expected Behavior
I add an existing or a new host group to a host.

## Current Behavior
As soon as I have added a group to the host, an error message appears and the host can no longer be configured.

## Possible Solution
Just a workaround: the only solution so far is to delete the entire host group. then the host can be edited again

## Steps to Reproduce (for bugs)
create a new host group (e.g. named grp_test). edit a host object and add the new created group. The following message appears immediately after the setting has been saved:

> Uncaught Error: Call to undefined method ipl\Html\Text::addAttributes() in /usr/share/icingaweb2/modules/director/application/forms/IcingaHostForm.php:233
Stack trace:
#0 /usr/share/icingaweb2/modules/director/application/forms/IcingaHostForm.php(60): Icinga\Module\Director\Forms\IcingaHostForm->addGroupsElement()
#1 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/QuickForm.php(370): Icinga\Module\Director\Forms\IcingaHostForm->setup()
#2 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/QuickForm.php(587): Icinga\Module\Director\Web\Form\QuickForm->prepareElements()
#3 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/QuickForm.php(602): Icinga\Module\Director\Web\Form\QuickForm->setRequest(Object(Icinga\Web\Request))
#4 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/QuickForm.php(381): Icinga\Module\Director\Web\Form\QuickForm->getRequest()
#5 /usr/share/icingaweb2/modules/director/library/Director/Web/Controller/ObjectController.php(536): Ici

> #0 [internal function]: Icinga\Application\Web->Icinga\Application\{closure}()
#1 {main}

## Your Environment

* Director version (System - About): 1.8.0
* Icinga Web 2 version and modules (System - About): 2.8.2
* Icinga 2 version (`icinga2 --version`): 2.12.3
* Operating System and version: CentOS 7
* Webserver, PHP versions: PHP 7.3.20, httpd 2.4.6-97

**Comment by Thomas-Gelf** [comment]
Duplicates #2253, fix has been released
