### ISSUE TITLE
Missing "override vars" button in context with data field categories and service sets

### ISSUE THREAD

**Issue by pdorschner** [Icinga/icingaweb2-module-director#2327]
## Expected Behavior

If one or more data fields of a service are assigned to a data field category, the "override vars" button should be displayed in the service tab.
<img width="625" alt="override" src="https://user-images.githubusercontent.com/37802318/118947605-cac2f600-b957-11eb-9e58-d0841eaa9593.png">

## Current Behavior

If one or more data fields of a service are assigned to a data field category, the "override vars" button is missing in the service tab.

<img width="1248" alt="Datafield_with_category" src="https://user-images.githubusercontent.com/37802318/118945528-d2819b00-b955-11eb-909d-50f961122bc2.png">
<img width="1236" alt="missing_override" src="https://user-images.githubusercontent.com/37802318/118946678-ec6fad80-b956-11eb-8e35-cf0d5ae92f48.png">

## Steps to Reproduce (for bugs)

1. Create a data field category (e.g. Processes)
2. Create a new data field (e.g. procs_critical)
3. Select the previous created data field category (e.g. Processes) 
4. Apply the service set and display the service (procs)

## Your Environment

* Director version (System - About): 1.8.0
* Icinga Web 2 version and modules (System - About): 2.8.2
* Icinga 2 version (`icinga2 --version`): 2.12.3
* Operating System and version: CentOS 7
* Webserver, PHP versions: Apache/2.4.6, PHP 7.3.20

**Comment by Thomas-Gelf** [comment]
Should have been fixed with #2303
