### ISSUE TITLE
Add Support for User templates in baskets

### ISSUE THREAD

**Issue by Nathaniel-Donahue** [Icinga/icingaweb2-module-director#2328]
## Expected Behavior
It should be possible to add User templates and User into baskets

## Current Behavior
It is not possible to add User templates and User into baskets

## Your Environment
Icinga Web 2 : Icinga Web 2 v2.8.2
Director : Icinga Director v1.8.0 (current master)

**Comment by dgoetz** [comment]
Also add User groups, so all User related things I guess.
