### ISSUE TITLE
Director Daemon status: db no running config after x509 module installation

### ISSUE THREAD

**Issue by Thomastouma** [Icinga/icingaweb2-module-director#2329]
## Expected Behavior
Daemon should continue running with backend configuration 
``
● icinga-director.service - Icinga Director - Monitoring Configuration                               
   Loaded: loaded (/etc/systemd/system/icinga-director.service; enabled; vendor preset: enabled)     
   Active: active (running) since Thu 2021-05-20 14:41:47 CEST; 1s ago                               
     Docs: https://icinga.com/docs/director/latest/                                                  
 Main PID: 122861 (icingacli)                                                                        
   Status: "running, db: connected"                                                                  
    Tasks: 1 (limit: 9509)                                                                           
   Memory: 11.5M                                                                                     
   CGroup: /system.slice/icinga-director.service                                                     
           └─122861 icinga::director: running, db: connected                                         
                                                                                                     
May 20 14:41:47 ic2-web1-dev.qbs.se systemd[1]: Starting Icinga Director - Monitoring Configuration..
May 20 14:41:47 ic2-web1-dev.qbs.se systemd[1]: Started Icinga Director - Monitoring Configuration.  
``

## Current Behavior
1. Install and configure icingacli and the x509 module on another server than the one hosting the systemd icinga-director daemon
2. Collect certificate data and send to database backend for x509 module
3. On the icingaweb2 install and configure the x509 module to use the same x509 database backend as to where the machine responsible for monitoring x509 sends the data.
4. Icinga-director daemon stops and crashes because of above steps

``
● icinga-director.service - Icinga Director - Monitoring Configuration                      
   Loaded: loaded (/etc/systemd/system/icinga-director.service; enabled; vendor preset: enabled
   Active: active (running) since Wed 2021-05-19 13:26:09 CEST; 1 day 1h ago                
     Docs: https://icinga.com/docs/director/latest/                                         
 Main PID: 119381 (icingacli)                                                               
   Status: "running, db: connected"                                                         
    Tasks: 1 (limit: 9509)                                                                  
   Memory: 16.2M                                                                            
   CGroup: /system.slice/icinga-director.service                                            
           └─119381 icinga::director: running, db: no configuration                           
                                                                                            
May 19 13:26:08 ic2-web1-dev.qbs.se systemd[1]: Starting Icinga Director - Monitoring Config 
May 19 13:26:09 ic2-web1-dev.qbs.se systemd[1]: Started Icinga Director - Monitoring Configu
May 19 13:26:09 ic2-web1-dev.qbs.se icingadirector[119381]: DB configuration is not valid   
``

## Possible Solution
1. Remove the x509 backend from /etc/icingaweb2/resources.ini on the icingaweb2 server.
2.  icinga-director daemon restarts itself like normal again and enters a valid configuration state

## Steps to Reproduce (for bugs)
1. Install and configure icingacli and the x509 module on another server than the one hosting the systemd icinga-director daemon
2. Collect certificate data through that server and send to database backend for x509 module
3. On the icingaweb2 configure the x509 module to use the same x509 database backend as to where the server responsible for monitoring x509 sends the data.
4. Icinga-director daemon stops and crashes because of above steps

## Your Environment

* Director version (System - About):   1.8.0
* Icinga Web 2 version and modules (System - About):     2.8.2
* Icinga 2 version (`icinga2 --version`): r2.12.3-1
* Operating System and version: debian 10
* Webserver, PHP versions: apache2, php 7.3

**Comment by Thomastouma** [comment]
Just did.
Apparently a password in the resources.ini is not allowed to contain the character "
If so it breaks the string leading from the first opening " to the one " thats part of the password and rest of the config breaks as a result.
``
password = "randompassword^ll"asd323"
``

**Comment by Thomas-Gelf** [comment]
This kind of messes up all following strings. Special characters need to be escaped in INI files, as shown [here](https://en.wikipedia.org/wiki/INI_file#Escape_characters). Did you configure this resource through Icinga Web? Because then you should be covered. In case you're using some automation tool make sure to use libraries able to write valid INI files.

Hope this helps!
