### ISSUE TITLE
Possibility to set "MatchAny" on assign rules

### ISSUE THREAD

**Issue by Foxeronie** [Icinga/icingaweb2-module-director#2336]
Hey! :)

We tried to use service apply rules with a wildcard on hostgroups, but this works only if the host is not in multiple hostgroups.
You can find more details here: https://github.com/Icinga/icinga2/issues/8654

By setting the "MatchAny" parameter the assign rule works when the host is in multiple hostgroups.
Is there a possibility to add an option in Director to set this parameter?

Best regards,
Patrick

**Comment by khmuth** [comment]
+1

**Comment by Foxeronie** [comment]
> see [#2095](https://github.com/Icinga/icingaweb2-module-director/pull/2095)

Thank you, didn't check first! Closing this issue again.
