### ISSUE TITLE
[dev.icinga.com #11777] Show objects using specific templates

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#234]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11777

**Created by tgelf on 2016-05-12 08:19:39 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-05-12 08:19:39 +00:00 (in Redmine)_

---

This would probably be a good fit for the template tree. We could also eventually add a new related tab to the template detail view.

**Comment by Thomas-Gelf** [comment]
This has been fully implemented for v1.4.0
