### ISSUE TITLE
typo in ObjectsTableService.php

### ISSUE THREAD

**Issue by moreamazingnick** [Icinga/icingaweb2-module-director#2357]
https://github.com/Icinga/icingaweb2-module-director/blob/e72da4cac4191a4e76ab7f02e2b70447b9b11bc9/library/Director/Web/Table/ObjectsTableService.php#L27

looks like a typo.
'hots_object_type' => 'h.object_type',
vs
'host_object_type' => 'h.object_type',

**Comment by Thomas-Gelf** [comment]
Thank you!
