### ISSUE TITLE
Custom fields in check command should be sorted regardless of upper and lower case

### ISSUE THREAD

**Issue by phil-or** [Icinga/icingaweb2-module-director#2358]
## Current Behavior
We have a lot of custom vars in our Director config - especially since using the icinga powershell framework. 
If you add a field to a check command, the fields in the dropdown menu are sorted alphabetically and at the beggining there are fields with uppercase letters and in the end lowercase letters. 
![grafik](https://user-images.githubusercontent.com/36534023/125798478-707ac03d-a4fe-4c21-b94e-2d344ffaeaae.png)

## Expected Behavior
Fields in Dropdown menu should be sorted alphabetically, regardless of upper and lower case.
The list at "Define Data Fields" is sorted correct.

**Comment by tbauriedel** [comment]
ref/NC/761567
