### ISSUE TITLE
Data Fields - search results different  

### ISSUE THREAD

**Issue by phil-or** [Icinga/icingaweb2-module-director#2359]
## Current Behavior
In the Director menu "Define Data Fields" you can search for defined Data Fields. Unfortunately you get different results with the following search queries:
![grafik](https://user-images.githubusercontent.com/36534023/125923416-7427e32d-c2de-4601-9d98-ac8559ce7029.png)
![grafik](https://user-images.githubusercontent.com/36534023/125923480-f30f392c-3b02-4195-9a07-c92953d4bdb1.png)

First I thought it's a problem with case in/-sensitive, but as you can see in the first screenshot, you get results for "icinga" and "Icinga", but only a few of them. 

## Expected Behavior
Search results should be case insensitive and containing all Data Fields with "icinga" and "Icinga".

**Comment by tbauriedel** [comment]
ref/NC/761567

**Comment by Thomas-Gelf** [comment]
Note for myself: branch is ready, but depends on a new incubator release
