### ISSUE TITLE
Clone an import source fails with Fatal error - Allowed memory size of .. exhausted in various php files

### ISSUE THREAD

**Issue by vpdose** [Icinga/icingaweb2-module-director#2362]
## Expected Behavior
Before my update to icinga/icingaweb2/director  this morning I was able to clone import sources in the director

## Current Behavior
When I try this now, a fatal error is thrown:

Fatal error
: Allowed memory size of 2147483648 bytes exhausted (tried to allocate 20480 bytes) in
/usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php
on line
339

Fatal error
: Allowed memory size of 2147483648 bytes exhausted (tried to allocate 20480 bytes) in
/usr/share/php/Icinga/Application/Web.php
on line
455

## Possible Solution
I already expanded the memory_limit in /etc/php.ini from 128M to 2048M - then the time until the error occures just is longer, but that's it.

I also checked this on another server, where I also updated this morning

## Steps to Reproduce (for bugs)
Icinga Director -> Automation -> Import Source

- choose any import source (host, services, data list)
- clone

wait a few seconds until fatal error occurs.
## Your Environment

* Director version (System - About): 1.8.1
* Icinga Web 2 version and modules (System - About):  2.9.0
* Icinga 2 version (`icinga2 --version`):  2.12.5-1
* Operating System and version: CentOS Stream release 8
* Webserver, PHP versions: PHP 7.4.21

**Comment by Thomas-Gelf** [comment]
Thanks for reporting this, can be reproduced. Works fine with Icinga Web 2.8.3, fails in an endless loop with v2.9.0. Seems that there went something wrong in [ipl\Html](https://github.com/Icinga/ipl-html), some essential interfaces have been changed in v0.4.0.

**Comment by lippserd** [comment]
I’ll have a look!

**Comment by Thomas-Gelf** [comment]
This was fast, thanks @lippserd :+1: You've got a mail with some additional notes two minutes ago

**Comment by vpdose** [comment]
Hey lippserd,

I was a bit impatient and took the liberty to update ipl to 0.6.1 - you did some changes there.

After a "git clone"  I was able to clone my import jobs - looks very much as if you did it - thanks !!

Best regards
Volker

**Comment by Thomas-Gelf** [comment]
Fixed with ipl 0.6.1
