### ISSUE TITLE
Search in DataFieldCategory not working

### ISSUE THREAD

**Issue by moreamazingnick** [Icinga/icingaweb2-module-director#2367]
## Expected Behavior
Search in DataFieldCategory should return filtered entries

## Current Behavior
![Screenshot 2021-07-30 at 06 18 13](https://user-images.githubusercontent.com/29682206/127599703-dc1a1860-a1a7-4ea6-a1f7-d2ad4b4eab5e.png)

## Possible Solution
Change from:
class DatafieldCategoryTable extends ZfQueryBasedTable
{
    protected $searchColumns = array(
        'dfc.varname',
        'dfc.caption',
    );
to:
class DatafieldCategoryTable extends ZfQueryBasedTable
{
    protected $searchColumns = array(

       'dfc.category_name',
       'dfc.description',
    );

## Steps to Reproduce (for bugs)
https://yourdomain.at/icingaweb2/director/data/fieldcategories?q=test

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'dfc.varname' in 'where clause', query was: SELECT COUNT(*) AS cnt FROM (SELECT dfc.id, dfc.category_name, dfc.description, COUNT(df.id) AS assigned_fields FROM director_datafield_category AS dfc
 LEFT JOIN director_datafield AS df ON df.category_id = dfc.id WHERE (`dfc`.`varname` LIKE '%test%' OR `dfc`.`caption` LIKE '%test%') GROUP BY dfc.id,
	dfc.category_name ORDER BY category_name ASC) AS t (Pdo.php:225)
#0 /usr/share/icingaweb2/library/vendor/Zend/Db/Statement.php(297): Zend_Db_Statement_Pdo->_execute()
#1 /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Abstract.php(470): Zend_Db_Statement->execute()
#2 /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query()
#3 /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Abstract.php(816): Zend_Db_Adapter_Pdo_Abstract->query()
#4 /usr/share/icingaweb2/modules/incubator/vendor/gipfl/icingaweb2/src/Zf1/Db/SelectPaginationAdapter.php(42): Zend_Db_Adapter_Abstract->fetchOne()
#5 [internal function]: gipfl\IcingaWeb2\Zf1\Db\SelectPaginationAdapter->count()
#6 /usr/share/icingaweb2/modules/incubator/vendor/gipfl/icingaweb2/src/Widget/Paginator.php(134): count()
#7 /usr/share/icingaweb2/modules/incubator/vendor/gipfl/icingaweb2/src/Widget/Paginator.php(115): gipfl\IcingaWeb2\Widget\Paginator->getTotalItemCount()
#8 /usr/share/icingaweb2/modules/incubator/vendor/gipfl/icingaweb2/src/Widget/Paginator.php(457): gipfl\IcingaWeb2\Widget\Paginator->getPageCount()
#9 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(339): gipfl\IcingaWeb2\Widget\Paginator->render()
#10 /usr/share/icinga-php/ipl/vendor/ipl/html/src/BaseHtmlElement.php(255): ipl\Html\HtmlDocument->renderUnwrapped()
#11 /usr/share/icinga-php/ipl/vendor/ipl/html/src/BaseHtmlElement.php(324): ipl\Html\BaseHtmlElement->renderContent()
#12 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(498): ipl\Html\BaseHtmlElement->renderUnwrapped()
#13 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(339): ipl\Html\HtmlDocument->render()
#14 /usr/share/icinga-php/ipl/vendor/ipl/html/src/BaseHtmlElement.php(255): ipl\Html\HtmlDocument->renderUnwrapped()
#15 /usr/share/icingaweb2/modules/incubator/vendor/gipfl/icingaweb2/src/Widget/Controls.php(161): ipl\Html\BaseHtmlElement->renderContent()
#16 /usr/share/icinga-php/ipl/vendor/ipl/html/src/BaseHtmlElement.php(324): gipfl\IcingaWeb2\Widget\Controls->renderContent()
#17 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(498): ipl\Html\BaseHtmlElement->renderUnwrapped()
#18 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(369): ipl\Html\HtmlDocument->render()
#19 /usr/share/icingaweb2/modules/incubator/vendor/gipfl/icingaweb2/src/Zf1/SimpleViewRenderer.php(61): ipl\Html\HtmlDocument->__toString()
#20 /usr/share/icingaweb2/modules/incubator/vendor/gipfl/icingaweb2/src/Zf1/SimpleViewRenderer.php(104): gipfl\IcingaWeb2\Zf1\SimpleViewRenderer->render()
#21 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/HelperBroker.php(272): gipfl\IcingaWeb2\Zf1\SimpleViewRenderer->postDispatch()
#22 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(518): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
#23 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch()
#24 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch()
#25 /usr/share/php/Icinga/Application/Web.php(304): Zend_Controller_Front->dispatch()
#26 /usr/share/php/Icinga/Application/webrouter.php(107): Icinga\Application\Web->dispatch()
#27 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...')
#28 {main}

## Your Environment
* Director version (System - About): 1.8.1
* Icinga Web 2 version and modules (System - About): 2.9.2
* Icinga 2 version (`icinga2 --version`): 2.12.5
* Operating System and version: Ubuntu 20.04
* Webserver, PHP versions: 7.4.x

**Comment by Thomas-Gelf** [comment]
Thank you!
