### ISSUE TITLE
Error: Invalid argument supplied for foreach() - While accessing  "/icingaweb2/director"

### ISSUE THREAD

**Issue by Prathameshhankare** [Icinga/icingaweb2-module-director#2384]
## Current Behavior
Unable to access Director dashboard and gets an error as " Invalid argument supplied for foreach()"

It was working fine till yesterday and suddenly started to give the error.

Note: I am using the master version for the director module.

## My Environment

* Director version (System - About): Master version(updated last on 24th Aug 2021)
* Icinga Web 2 version and modules (System - About): v2.9.3
* Icinga 2 version (`icinga2 --version`): v2.13.1
* Operating System and version: Centos 7
* Webserver, PHP versions: v7.3.29

![image](https://user-images.githubusercontent.com/52577680/131305464-e7b1c08c-aeed-4513-a32c-03bc37bc076d.png)

**Comment by Thomas-Gelf** [comment]
Please `git pull` once again, this broke on Tuesday with b321327 and has been fixed on Wednesday with 6cc902f. Sorry for the inconvenience, and thanks for reporting this!

**Comment by Prathameshhankare** [comment]
Thanks, @Thomas-Gelf. Do I have an option to get rid of the master branch and be on the stable release? for example v1.8.1.

**Comment by Thomas-Gelf** [comment]
@Prathameshhankare: this is not possible with point/patch-releases, as they are usually technically much older than the current master branch. This means chances are high, that running the GIT master you already applied DB migrations, that are more recent than the last release. So if you `git checkout v1.8.1`, the Director Dashboard will probably tell you:

> Your DB schema (migration #173) is newer than your code base. Downgrading Icinga Director is not supported and might lead to unexpected problems.

But as soon as the next "major" release (1.9.0, as of this writing) arrives, this is perfectly possible. We always provide a straight upgrade path from any GIT master in time to the next `.0`-release.

**Comment by Prathameshhankare** [comment]
@Thomas-Gelf, thanks again for the information. The issue is resolved now, we are good to close this thread.
