### ISSUE TITLE
Satellite based Service

### ISSUE THREAD

**Issue by jensrudolf** [Icinga/icingaweb2-module-director#2394]
## Expected Behavior
In addition to Agent-based service it would be very usefull to have an Satellite-based service where one could set the command endpoint of the service to a custom value or macro (e.g. host.vars.satellite / host.vars.parent)

## Current Behavior
Currently, the command_endpoint can only be set to "none" or "host.name" for Agent-based services. I can see no way to specify that a Service / Service Template should run on a Icinga2 Satellite node.

## Possible Solution
Add "command_endpoint" field to Service / Service Template or provide "Run on Satellite" choice with ability to specify Satellite endpoint.

## Your Environment
* Director version (System - About):  1.8.1
* Icinga Web 2 version and modules (System - About): 2.9.3
* Icinga 2 version (`icinga2 --version`): 2.12.3
* Operating System and version: Debian Bullseye
* Webserver, PHP versions: NGINX, PHP 7.4

**Comment by idandr** [comment]
For your host, set the zone of the host to one of your satellite zones and "Icinga2 Agent" to Yes (this host has an agent installed).
For your service set "Run on agent" to "No" (rendering to "command_endpoint = none").
This should result in the requested behaviour - the check is run on one of the satellites in the given satellite zone (check from satellite).

If you set "Run on agent" to "Yes" for another service, this check is run by the agent (on the host, not on the satellite).

**Comment by jensrudolf** [comment]
@idandr Thank you very much. Works as expected. Closing this ticket.
