### ISSUE TITLE
Api users, Endpoints, and Zones error on Zend_Db_Select 

### ISSUE THREAD

**Issue by mxroo** [Icinga/icingaweb2-module-director#2395]
## Expected Behavior
Infrastructure pieces Api users, Endpoints, and Zones should be accessible through Director web UI

## Current Behavior

When going to icingaweb2/director/apiusers, icingaweb2/director/endpoints, or icingaweb2/director/zones, errors of this form appear instead of a usable interface.

```
Error
 
Declaration of Icinga\Module\Director\Web\Table\ObjectsTableApiUser::applyObjectTypeFilter(Zend_Db_Select $query) should be compatible with Icinga\Module\Director\Web\Table\ObjectsTable::applyObjectTypeFilter(Zend_Db_Select $query, ?Zend_Db_Select $right = NULL)

#0 /usr/share/php/Icinga/Application/ClassLoader.php(303): Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(Integer, String, String, Integer, Array)
#1 /usr/share/php/Icinga/Application/ClassLoader.php(303): require()
#2 [internal function]: Icinga\Application\ClassLoader->loadClass(String)
#3 [internal function]: spl_autoload_call(String)
#4 /usr/share/icingaweb2/modules/director/library/Director/Web/Table/ObjectsTable.php(58): class_exists(String)
#5 /usr/share/icingaweb2/modules/director/library/Director/Web/Controller/ObjectsController.php(142): Icinga\Module\Director\Web\Table\ObjectsTable::create(String, Object(Icinga\Module\Director\Db))
#6 /usr/share/icingaweb2/modules/director/library/Director/Web/Controller/ObjectsController.php(130): Icinga\Module\Director\Web\Controller\ObjectsController->getTable()
#7 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Director\Web\Controller\ObjectsController->indexAction()
#8 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch(String)
#9 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#10 /usr/share/php/Icinga/Application/Web.php(304): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#11 /usr/share/php/Icinga/Application/webrouter.php(107): Icinga\Application\Web->dispatch()
#12 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#13 {main}
```

## Possible Solution
Possible Zend version incompatibility between Ubuntu packages and Director

## Steps to Reproduce (for bugs)
Appears on every load of those pages on my setup.

## Your Environment
* Director version (System - About): master
* Icinga Web 2 version and modules (System - About): 2.9.3
** Loaded Libraries
*** icinga/icinga-php-thirdparty | 0.10.0
*** icinga/icinga-php-library | 0.6.1
** Loaded Modules
*** director | master
*** doc | 2.9.3
*** incubator | 0.6.0
*** ipl | v0.3.0
*** migrate | 2.9.3
*** monitoring | 2.9.3
*** reactbundle | 0.7.0
*** setup | 2.9.3
* Icinga 2 version (`icinga2 --version`): r2.13.1-1
* Operating System and version: Ubuntu 18.04.6 LTS 
* Webserver, PHP versions: Apache/2.4.29 (Ubuntu), PHP 8.0.10

**Comment by Thomas-Gelf** [comment]
Thanks for reporting this, has been fixed.

**Comment by mxroo** [comment]
Amazing, thank you!
