### ISSUE TITLE
Cannot login to vsphere 7

### ISSUE THREAD

**Issue by roadieman** [Icinga/icingaweb2-module-director#2398]
After Upgrading our VCenter to VSphere 7 it's not possible to login with Director Module.
We have the same effect like https://github.com/Icinga/icingaweb2-module-vsphere/issues/33

**Messages on Import Preview**

Oops, an error occurred!

Got 500: '<?xml version="1.0" encoding="UTF-8"?>
<soapenv:Envelope xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
 xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"
 xmlns:xsd="http://www.w3.org/2001/XMLSchema"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<soapenv:Body>
<soapenv:Fault><faultcode>ServerFaultCode</faultcode><faultstring>The session is not authenticated.</faultstring><detail><NotAuthenticatedFault xmlns="urn:vim25" xsi:type="NotAuthenticated"><object type="Folder">group-d1</object><privilegeId>System.View</privilegeId></NotAuthenticatedFault></detail></soapenv:Fault>
</soapenv:Body>
</soapenv:Envelope>' (CurlLoader.php:255)

#0 /usr/share/icingaweb2/modules/vsphere/library/Vsphere/CurlLoader.php(184): Icinga\Module\Vsphere\CurlLoader->request('post', 'https://192.168...', '<?xml version="...', Array)
#1 /usr/share/icingaweb2/modules/vsphere/library/Vsphere/SoapClient.php(56): Icinga\Module\Vsphere\CurlLoader->post('https://192.168...', '<?xml version="...', Array)
#2 /usr/share/icingaweb2/modules/vsphere/library/Vsphere/SoapClient.php(37): Icinga\Module\Vsphere\SoapClient->doCurlRequest('<?xml version="...', 'https://192.168...', 'urn:vim25/6.7.3', 1, 0)
#3 [internal function]: Icinga\Module\Vsphere\SoapClient->__doRequest('<?xml version="...', 'https://192.168...', 'urn:vim25/6.7.3', 1, 0)
#4 /usr/share/icingaweb2/modules/vsphere/library/Vsphere/Api.php(110): SoapClient->__soapCall('Logout', Array)
#5 /usr/share/icingaweb2/modules/vsphere/library/Vsphere/Api.php(267): Icinga\Module\Vsphere\Api->soapCall('Logout', Array)
#6 /usr/share/icingaweb2/modules/vsphere/library/Vsphere/ProvidedHook/Director/ImportSource.php(31): Icinga\Module\Vsphere\Api->logout()
#7 /usr/share/icingaweb2/modules/director/library/Director/Web/Table/ImportsourceHookTable.php(101): Icinga\Module\Vsphere\ProvidedHook\Director\ImportSource->fetchData()
#8 /usr/share/icingaweb2/modules/incubator/vendor/gipfl/icingaweb2/src/Table/SimpleQueryBasedTable.php(29): Icinga\Module\Director\Web\Table\ImportsourceHookTable->prepareQuery()
#9 /usr/share/icingaweb2/modules/incubator/vendor/gipfl/icingaweb2/src/Table/SimpleQueryBasedTable.php(15): gipfl\IcingaWeb2\Table\SimpleQueryBasedTable->getQuery()
#10 /usr/share/icingaweb2/modules/incubator/vendor/gipfl/icingaweb2/src/Table/QueryBasedTable.php(56): gipfl\IcingaWeb2\Table\SimpleQueryBasedTable->getPaginationAdapter()
#11 /usr/share/icingaweb2/modules/incubator/vendor/gipfl/icingaweb2/src/Table/QueryBasedTable.php(255): gipfl\IcingaWeb2\Table\QueryBasedTable->getPaginator(Object(gipfl\IcingaWeb2\Url))
#12 /usr/share/icingaweb2/modules/director/application/controllers/ImportsourceController.php(162): gipfl\IcingaWeb2\Table\QueryBasedTable->renderTo(Object(Icinga\Module\Director\Controllers\ImportsourceController))
#13 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Director\Controllers\ImportsourceController->previewAction()
#14 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('previewAction')
#15 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#16 /usr/share/php/Icinga/Application/Web.php(304): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#17 /usr/share/php/Icinga/Application/webrouter.php(107): Icinga\Application\Web->dispatch()
#18 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...')
#19 {main}

## Your Environment

* Director version: 1.8.1 
* Icinga Web 2 version and modules: 2.9.2
* Icinga 2 version (`icinga2 --version`): 2.13.01
* Operating System and version: rhel 7.9
* Webserver, PHP versions:  7.3.20

**Comment by Thomas-Gelf** [comment]
Please pull the current master branch or manually apply this [little fix](https://github.com/Icinga/icingaweb2-module-vspheredb/commit/e27d81086e5a0ef972fe77848035b7745c89e999]

**Comment by roadieman** [comment]
That's fast :-)

But this fix is only for the vsphere module!? We habe this issue on director module.

Thank you
Patrick

**Comment by Thomas-Gelf** [comment]
[vSphere-Module v1.1.1](https://github.com/Icinga/icingaweb2-module-vsphere/releases/tag/v1.1.1) should fix this

**Comment by roadieman** [comment]
It does! I was searching in the wrong section.

Many thanks and greetings from another Keyboard Man
Patrick
