### ISSUE TITLE
ranges in time periods are not written so all checks in icinga are on status "delayed"

### ISSUE THREAD

**Issue by thrashiii** [Icinga/icingaweb2-module-director#2408]
## Expected Behavior
when I define ranges within a time period these should written as ranges.

## Current Behavior
since last update when I write configs via director the whole icinga2 monitoring system is going wrong. In all host and service checks the last check status is "delayed".

In icinga2 debug log all checks report "not in check period". Also in director time period config preview the defined ranges are empty.

## Your Environment

* Director version (System - About): master
* Icinga Web 2 version and modules (System - About): 2.9.3
* Icinga 2 version (`icinga2 --version`): r2.13.1-1
* Operating System and version: debian 9.13
* Webserver, PHP versions: apache 2.4.25-3+deb9u11, php 7.4

**Comment by Thomas-Gelf** [comment]
Can be reproduced, thanks for reporting this!

**Comment by thrashiii** [comment]
thank you for fast fixing. Problem ist solved...
