### ISSUE TITLE
unable to edit time period ranges

### ISSUE THREAD

**Issue by thrashiii** [Icinga/icingaweb2-module-director#2415]
## Current Behavior
when I want to edit an existing time period range the following error appears:

Trying to recreate icinga_timeperiod_range ("{"timeperiod_id":"3","range_key":"friday","range_type":"include"}") (DbObject.php:896)

The error also appears when I create a new time period and want to add more ranges. The first range, e.g. monday 00:00-23:00 will be created. When I want to add the second range, eg. tuesday 00:00-23:00 the error also appears.

## Your Environment

* Director version (System - About): master
* Icinga Web 2 version and modules (System - About): 2.9.3
* Icinga 2 version (`icinga2 --version`): r2.13.1-1
* Operating System and version: debian 9
* Webserver, PHP versions: apache 2.4.25-3+deb9u11, php 7.4

**Comment by afeefghannam89** [comment]
I confirm this problem in the actual master 

ref/NC/737205

**Comment by lippserd** [comment]
@Thomas-Gelf Just wanted to let you know that this is a regression and it doesn't exist in the latest version. Do you have a special label for that?

**Comment by Thomas-Gelf** [comment]
Can be reproduced, thanks for reporting this

**Comment by thrashiii** [comment]
Are there any news when the bug will be fixed?

**Comment by thrashiii** [comment]
thank you for fixing this...
