### ISSUE TITLE
Set command argument based on host variable value

### ISSUE THREAD

**Issue by wrkhunte** [Icinga/icingaweb2-module-director#2425]
## Expected Behavior
I am trying to set the arguments of a command using a host variable. The host variable is an int value (snmp_version) from a data list (snmp_versions).
The command should set the following:
If the value of the host variable is 1, the argument -C should be set with a community string.
If the value of the host variable is 3, several other arguments (snmp_priv, snmp_auth, snmp_user, ...) should be set.

## Current Behavior
If I set "$snmp_version$" for "Condition (set_if)", then the argument is set regardless of the value entered.

Is it possible to use a macro here, such as "match (" 1 ", $snmp_version$)" (doesn't work for me) or to check the value in another way?

## Steps to Reproduce (for bugs)
Create a host with a "snmp_version" field. Create a command with an argument which is set or omitted based on the value in the host variable "snmp_version".

## Your Environment

* Director version (System - About): 1.8.0
* Icinga Web 2 version and modules (System - About): 2.8.2
* Icinga 2 version (`icinga2 --version`): 2.12.3
* Operating System and version: CentOS 7
* Webserver, PHP versions: httpd, 7.3.20

**Comment by Thomas-Gelf** [comment]
This is more an Icinga config question than Director-related. When setting the condition format to "Icinga DSL", you need to specify an Icinga DSL expression that returns a boolean value. Depending on the rendered data type, one of the following should do the Job:

String:

    return macro("$snmp_version$") == "1";

Integer:

    return macro("$snmp_version$") == 1;

**Comment by wrkhunte** [comment]
ok, I understand that, but what do I have to set for "Condition (set_if)" to get the return value (boolean) from the macro?

Please excuse if I may not know a basic here, but I've been working on this for a long time before I posted it here and would be very happy if I find a solution.
