### ISSUE TITLE
Config deployment job fails with "SQLSTATE[42000]: Syntax error..."

### ISSUE THREAD

**Issue by atj** [Icinga/icingaweb2-module-director#2426]
## Expected Behavior
Config job should complete successfully.

## Current Behavior
The job intermittently fails, with the following error logged by the Icinga Director service:

```
icingadirector[3614699]: Job (Icinga Deploy Config): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '?)' at line 1, query was: SELECT LOWER(HEX(l.config_checksum)) AS c FROM director_deployment_log AS l WHERE (l.stage_name = ?)
icingadirector[3614699]: Job (Icinga Deploy Config) failed: Process exited with exit code 1
```

## Possible Solution

The `getActiveChecksum()` function appears to be triggering this issue:

https://github.com/Icinga/icingaweb2-module-director/blob/4f959572f2ad210493602552fce961a8db806be3/library/Director/Job/ConfigJob.php#L155-L161

This function calls `DirectorDeploymentLog::getConfigChecksumForStageName()` which executes the SQL statement that appears in the error message:

https://github.com/Icinga/icingaweb2-module-director/blob/4f959572f2ad210493602552fce961a8db806be3/library/Director/Objects/DirectorDeploymentLog.php#L92-L102

It's clear from the error message that the bound parameter in the prepared statement is not being interpolated, which I assume is due to the call to `$this->api()->getActiveStageName()` is returning NULL?

I've checked the Icinga 2 logs at the times the issue occurs and the API requests are logged with status "OK", e.g.:

```
[2021-11-10 07:32:16 +0000] information/ApiListener: New client connection from [::ffff:10.0.1.xxx]:42764 (no client certificate)
[2021-11-10 07:32:16 +0000] information/HttpServerConnection: Request: GET /v1/ (from [::ffff:10.0.1.xxx]:42764), user: icingadirector, agent: , status: OK).
[2021-11-10 07:32:16 +0000] information/HttpServerConnection: Request: GET /v1/config/packages (from [::ffff:10.0.1.xxx]:42764), user: icingadirector, agent: , status: OK).
[2021-11-10 07:32:16 +0000] information/HttpServerConnection: Request: GET /v1/config/packages (from [::ffff:10.0.1.xxx]:42764), user: icingadirector, agent: , status: OK).
[2021-11-10 07:32:16 +0000] information/HttpServerConnection: Request: GET /v1/config/packages (from [::ffff:10.0.1.xxx]:42764), user: icingadirector, agent: , status: OK).
[2021-11-10 07:32:16 +0000] information/HttpServerConnection: HTTP client disconnected (from [::ffff:10.0.1.xxx]:42764)
```

Should there be some logic added to confirm that `$this->api()->getActiveStageName()` or the `$stage` parameter is a valid value?

## Steps to Reproduce (for bugs)

Configure a config deployment job and wait.

## Your Environment

* Director version (System - About):

Version: 1.8.1
Git commit: 087ce05ebe9ec935d14ceb73293a2ce25b8088b5

* Icinga Web 2 version and modules (System - About):

Icinga Web 2 Version: 2.9.3
Git commit: c757a17530c326c7d6daebd6171486cb8167a8a1
PHP Version: 7.4.3

* Icinga 2 version (`icinga2 --version`):

```
icinga2 - The Icinga 2 network monitoring daemon (version: r2.13.1-1)

Copyright (c) 2012-2021 Icinga GmbH (https://icinga.com/)
License GPLv2+: GNU GPL version 2 or later <https://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

System information:
  Platform: Ubuntu
  Platform version: 20.04.2 LTS (Focal Fossa)
  Kernel: Linux
  Kernel version: 5.8.0-1038-aws
  Architecture: x86_64

Build information:
  Compiler: GNU 9.3.0
  Build host: runner-hh8q3bz2-project-508-concurrent-0
  OpenSSL version: OpenSSL 1.1.1f  31 Mar 2020
```
* Operating System and version:

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal
```

* Webserver, PHP versions:

Apache v2.4.41-4ubuntu3.4
PHP v7.4.3-4ubuntu2.5
Database: AWS RDS MySQL

**Comment by carraroj** [comment]
ref/NC/740931

**Comment by Thomas-Gelf** [comment]
Thanks for reporting this, should have happened only when the very first Deployment took place via Job and/or whenever Icinga wasn't reachable (happens when Icinga is restarting)
