### ISSUE TITLE
Click on link on external command doesn't work anymore

### ISSUE THREAD

**Issue by blindzero** [Icinga/icingaweb2-module-director#2427]
## Expected Behavior
Clicking on the name of an external command in director opens the external command's detail page.
(maybe relating to #2422 ?)

## Current Behavior
Empty page on the right side shown.
JS errors:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'split')
    at Icinga.Loader.redirectToUrl (icinga.min.js:588)
    at Icinga.Loader.processRedirectHeader (icinga.min.js:586)
    at Icinga.Loader.onComplete (icinga.min.js:624)
    at u (icinga.min.js:14)
    at Object.fireWith [as resolveWith] (icinga.min.js:14)
    at k (icinga.min.js:16)
    at XMLHttpRequest.<anonymous> (icinga.min.js:16)
```

## Possible Solution
no idea.
Maybe relating to #2422 or to [icingaweb2 issue #4598](https://github.com/Icinga/icingaweb2/issues/4598)? But I just could see this so far in director.

## Steps to Reproduce (for bugs)
* have environment as given
* open director > commands
* select "external"
* click on command's name

## Your Environment
* Director version (System - About): 1.8.1 Git commit 087ce05ebe9ec935d14ceb73293a2ce25b8088b5
* Icinga Web 2 version and modules (System - About): 2.9.4 Git commit d208d1ccfef86606984739e6357138c459146134
* Icinga 2 version (`icinga2 --version`): 
```
icinga2 - The Icinga 2 network monitoring daemon (version: r2.13.1-1)

Copyright (c) 2012-2021 Icinga GmbH (https://icinga.com/)
License GPLv2+: GNU GPL version 2 or later <https://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

System information:
  Platform: Ubuntu
  Platform version: 20.04.3 LTS (Focal Fossa)
  Kernel: Linux
  Kernel version: 5.11.0-1021-azure
  Architecture: x86_64

Build information:
  Compiler: GNU 9.3.0
  Build host: runner-hh8q3bz2-project-508-concurrent-0
  OpenSSL version: OpenSSL 1.1.1f  31 Mar 2020

Application information:

General paths:
  Config directory: /etc/icinga2
  Data directory: /var/lib/icinga2
  Log directory: /var/log/icinga2
  Cache directory: /var/cache/icinga2
  Spool directory: /var/spool/icinga2
  Run directory: /run/icinga2

Old paths (deprecated):
  Installation root: /usr
  Sysconf directory: /etc
  Run directory (base): /run
  Local state directory: /var

Internal paths:
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

```
* Operating System and version: see above
* Webserver, PHP versions:  2.4.41-4ubuntu3.8, php 7.4.3

**Comment by bewue** [comment]
I have basically the same versions installed and the same problem.
The same problem exists when I click on "modify service".

![grafik](https://user-images.githubusercontent.com/38508611/141754311-8c9e33a5-0f27-4e92-98e6-58d6aa490b19.png)

I think he problem exists since the last update i have installed on 2021-11-10:

php-icinga:amd64 (2.9.3-1.bionic, 2.9.4-1.bionic)
icingaweb2-module-monitoring:amd64 (2.9.3-1.bionic, 2.9.4-1.bionic)
icingacli:amd64 (2.9.3-1.bionic, 2.9.4-1.bionic)
icingaweb2-common:amd64 (2.9.3-1.bionic, 2.9.4-1.bionic)
icingaweb2-module-doc:amd64 (2.9.3-1.bionic, 2.9.4-1.bionic)
icinga-php-library:amd64 (0.6.1-1.bionic, 0.7.0-1.bionic)
icingaweb2:amd64 (2.9.3-1.bionic, 2.9.4-1.bionic)

**Comment by lippserd** [comment]
We'll have a look!

**Comment by lippserd** [comment]
@sukhwinder33445 Please also check Icinga/icingaweb2#4598. That one might be related.

**Comment by sukhwinder33445** [comment]
Yes, that is related and the same [PR](https://github.com/Icinga/icingaweb2/pull/4600) also fixes this issue.
