### ISSUE TITLE
Error "Unknown column icinga_service_set.uuid" at service in a service set

### ISSUE THREAD

**Issue by Gninieb** [Icinga/icingaweb2-module-director#2430]
## Expected Behavior
You can edit services in a service set.

## Current Behavior
If i klick on a service in a service set:

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'icinga_service_set.uuid' in 'field list', query was: SELECT icinga_service_set.uuid FROM icinga_service_set WHERE (object_name = 'Server Name')

#0 /usr/share/icingaweb2/library/vendor/Zend/Db/Statement.php(297): Zend_Db_Statement_Pdo->_execute()
#1 /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Abstract.php(470): Zend_Db_Statement->execute()
#2 /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query()
#3 /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Abstract.php(816): Zend_Db_Adapter_Pdo_Abstract->query()
#4 /usr/share/icingaweb2/modules/director/library/Director/Db/Branch/UuidLookup.php(88): Zend_Db_Adapter_Abstract->fetchOne()
#5 /usr/share/icingaweb2/modules/director/library/Director/Db/Branch/UuidLookup.php(64): Icinga\Module\Director\Db\Branch\UuidLookup::fetchOptionalUuid()
#6 /usr/share/icingaweb2/modules/director/application/controllers/ServiceController.php(74): Icinga\Module\Director\Db\Branch\UuidLookup::findUuidForKey()
#7 /usr/share/icingaweb2/modules/director/application/controllers/ServiceController.php(43): Icinga\Module\Director\Controllers\ServiceController->loadOptionalSet()
#8 /usr/share/php/Icinga/Web/Controller/ActionController.php(165): Icinga\Module\Director\Controllers\ServiceController->init()
#9 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(59): Icinga\Web\Controller\ActionController->__construct()
#10 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch()
#11 /usr/share/php/Icinga/Application/Web.php(304): Zend_Controller_Front->dispatch()
#12 /usr/share/php/Icinga/Application/webrouter.php(107): Icinga\Application\Web->dispatch()
#13 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#14 {main}

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'icinga_service_set.uuid' in 'field list'

#0 /usr/share/icingaweb2/library/vendor/Zend/Db/Statement/Pdo.php(219): PDOStatement->execute()
#1 /usr/share/icingaweb2/library/vendor/Zend/Db/Statement.php(297): Zend_Db_Statement_Pdo->_execute()
#2 /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Abstract.php(470): Zend_Db_Statement->execute()
#3 /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query()
#4 /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Abstract.php(816): Zend_Db_Adapter_Pdo_Abstract->query()
#5 /usr/share/icingaweb2/modules/director/library/Director/Db/Branch/UuidLookup.php(88): Zend_Db_Adapter_Abstract->fetchOne()
#6 /usr/share/icingaweb2/modules/director/library/Director/Db/Branch/UuidLookup.php(64): Icinga\Module\Director\Db\Branch\UuidLookup::fetchOptionalUuid()
#7 /usr/share/icingaweb2/modules/director/application/controllers/ServiceController.php(74): Icinga\Module\Director\Db\Branch\UuidLookup::findUuidForKey()
#8 /usr/share/icingaweb2/modules/director/application/controllers/ServiceController.php(43): Icinga\Module\Director\Controllers\ServiceController->loadOptionalSet()
#9 /usr/share/php/Icinga/Web/Controller/ActionController.php(165): Icinga\Module\Director\Controllers\ServiceController->init()
#10 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(59): Icinga\Web\Controller\ActionController->__construct()
#11 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch()
#12 /usr/share/php/Icinga/Application/Web.php(304): Zend_Controller_Front->dispatch()
#13 /usr/share/php/Icinga/Application/webrouter.php(107): Icinga\Application\Web->dispatch()
#14 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#15 {main}

## Possible Solution
?

## Steps to Reproduce (for bugs)
Klick on a service in a serviceset to edit it.

## Your Environment

* Director version (System - About): master
* Icinga Web 2 version and modules (System - About): 2.9.4 **and also 2.9.5**
* Icinga 2 version (`icinga2 --version`):
icinga2 - The Icinga 2 network monitoring daemon (version: r2.13.1-1)

Copyright (c) 2012-2021 Icinga GmbH (https://icinga.com/)
License GPLv2+: GNU GPL version 2 or later <https://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

System information:
  Platform: Ubuntu
  Platform version: 20.04.3 LTS (Focal Fossa)
  Kernel: Linux
  Kernel version: 5.4.0-90-generic
  Architecture: x86_64

Build information:
  Compiler: GNU 9.3.0
  Build host: runner-hh8q3bz2-project-508-concurrent-0
  OpenSSL version: OpenSSL 1.1.1f  31 Mar 2020

Application information:

General paths:
  Config directory: /etc/icinga2
  Data directory: /var/lib/icinga2
  Log directory: /var/log/icinga2
  Cache directory: /var/cache/icinga2
  Spool directory: /var/spool/icinga2
  Run directory: /run/icinga2

Old paths (deprecated):
  Installation root: /usr
  Sysconf directory: /etc
  Run directory (base): /run
  Local state directory: /var

Internal paths:
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

* Operating System and version: Ubuntu 20.04
* Webserver, PHP versions:  apache  2.4.41-4ubuntu3.8 ,PHP 7.4.3

**Comment by amyers1616** [comment]
I too am having the same issue. 

Icinga Web 2 Version: 2.9.4
Director version: master
Icinga2 Version: 2.13.2-1
Platform: CentOS 7

I tried downgrading from master to v1.8.1 which cleared the error, but then introduced others. Moving back to master and retesting resulted in the same error as @OP.

**Comment by dbecker1234** [comment]
+1

Icinga Web 2 Version: 2.9.4
Director version: master
Icinga2 Version: 2.13.2-1
Platform: Debian 11

Tried to add the missing field without success. Downgrading to last release also not possible, but I remember reading somewhere that downgrading of the db scheme is not supported anyway.  But there seems to be already a pull request #2418 with additional changes.
Guess that's the downside of using master branch. ;-)

**Comment by Basti1978** [comment]
same issue here

Icinga Web 2 Version: 2.9.4
Director version: master
Icinga2 Version: 2.13.2-1
Platform: CentOS 7

**Comment by Thomas-Gelf** [comment]
Pull request has been completed and merged, sorry for the delay
