### ISSUE TITLE
User gets wrongfully the service-ro view via the "Configuration" link in the monitoring module

### ISSUE THREAD

**Issue by slalomsk8er** [Icinga/icingaweb2-module-director#2434]
## Expected Behavior
User can click on the "Configuration" link in the monitoring module and overwrite thresholds of service directly.

## Current Behavior
If a user clicks on the "Configuration" link in the monitoring module, he gets the services-ro view and can't change the thresholds of a service.
If he then tries via director -> host -> services and clicks on the service he wants to change he gets the service-rw view and can accomplish the task.

## Steps to Reproduce (for bugs)

1. create restricted user with director/​filter/​hostgroups.
2. user gets error message on click of "Configuration" link in the monitoring module 
3. give user director/​monitoring/​services-ro
4. error message is gone but still no edit possible
5. give user director/​services
6. still no direct edit possible

## Your Environment

Icinga Web 2 Version
2.9.5
Git Commit
053971c99dc1a4510beb64a888ea695cc14032dc
PHP-Version
7.3.29

<html>
<body>
<h2 style="box-sizing: inherit; font-weight: 600; margin: 2.5em 0px 0.333em; font-size: 1.333em; color: rgb(83, 83, 83); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: center; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Geladene Bibliotheken</h2>

Name | Version
-- | --
icinga/icinga-php-library | 0.7.0
icinga/icinga-php-thirdparty | 0.10.0

</body>
</html>

<html>
<body>
<h2 style="box-sizing: inherit; font-weight: 600; margin: 2.5em 0px 0.333em; font-size: 1.333em; color: rgb(83, 83, 83); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: center; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Geladene Module</h2>

Name | Version
-- | --
businessprocess | 2.3.0
company | 1.0.0
cube | 1.1.0
director | 1.8.1.2021090901
doc | 2.9.5
fileshipper | 1.2.0
grafana | 1.4.2
incubator | 0.10.0
ipl | v0.5.0
monitoring | 2.9.5
reactbundle | 0.9.0
vspheredb | 1.2.1
x509 | 1.0.0

</body>
</html>

**Comment by Thomas-Gelf** [comment]
@slalomsk8er: thanks for reporting this! I've been able to reproduce the problem in:

> 2. user gets error message on click of "Configuration" link in the monitoring module

Should have been fixed, this affected the **Modify**-Link for all Services which where not "real" single Service objects on a Host.

Regarding the other steps: IMHO this works as expected, when you grant **services-ro**, you'll see where those services come from - but you're not allowed to modify them. RO == ReadOnly. If in doubt or in case I overlooked something: please let me know!

Closing this issue for now, as the original problem (the unnamed "error message") has been fixed.
