### ISSUE TITLE
Unknown column 'icinga_service_set.uuid' in 'field list'

### ISSUE THREAD

**Issue by bobapple** [Icinga/icingaweb2-module-director#2441]
## Expected Behavior
I am able to update a service within a Service Set.

## Current Behavior
I get the following error when trying to update a service of a service set:

```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'icinga_service_set.uuid' in 'field list', query was: SELECT icinga_service_set.uuid FROM icinga_service_set WHERE (object_name = 'linux-checks')

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'icinga_service_set.uuid' in 'field list'
```

## Steps to Reproduce (for bugs)
I migrated an existing v1.8.1 Director to the current master. The service set was created prior to the migration.

## Your Environment
* Director version (System - About): master (`5fe0a8812cf6a35a91e4becede6b7b652902f164`)
* Icinga Web 2 version and modules (System - About): 2.9.5
* Icinga 2 version (`icinga2 --version`): r2.13.1-1
* Operating System and version: Ubuntu 20.04
* Webserver, PHP versions: PHP 7.4.3

**Comment by bobapple** [comment]
Edit: MySQL schema update were executed successfully during the update from v1.8.1 to master

**Comment by Thomas-Gelf** [comment]
Thanks for reporting this. Duplicates  #2430, will be fixed today with the (incomplete) pull request in #2418.
