### ISSUE TITLE
Adding a TimeRange to a ScheduledDowntime fails

### ISSUE THREAD

**Issue by niemalsnever** [Icinga/icingaweb2-module-director#2442]
## Expected Behavior
The TimeRange should be added

## Current Behavior
Following Error message shows:
```
Trying to recreate icinga_scheduled_downtime_range ("{"scheduled_downtime_id":"1","range_key":"friday","range_type":"include"}") (DbObject.php:896)
```
![image](https://user-images.githubusercontent.com/6272364/143959902-318b3796-8518-4676-b4bc-2696e8965d35.png)
All ranges shown in the above image were added running version 1.8.1 of the Director. When switching to the `master` branch and trying to add a new time range, the above message is shown.

A config change still seems to be created and deployable, but the new range never shows up in the director GUI.

## Steps to Reproduce (for bugs)
- Use `master` branch of the Director
- Add a new ScheduledDowntime through the WebGUI
- Add a Time Range to that ScheduledDowntime -> Works
- Try to add a second Time Range -> Fails
  - But a new "change set" in the Activities-Pane will be created.

## Your Environment

* Director version (System - About): `master`
* Icinga Web 2 version and modules (System - About): `2.8.2`
* Icinga 2 version (`icinga2 --version`): `r2.13.1-1`
* Operating System and version: Raspbian Buster
* Webserver, PHP versions: nginx 1.14.2, PHP 7.3 (and also tested with 8.0)

**Comment by Gninieb** [comment]
Same problem here! Trying to change timerange for existing downtime and getting following error:

`Trying to recreate icinga_scheduled_downtime_range ("{"scheduled_downtime_id":"1","range_key":"friday","range_type":"include"}") (DbObject.php:896)`

Icinga Web 2 Version 2.9.5
Icinga Director Master Branch

After getting the error the change is in the downtime config history visible but after a deployment the change is gone.
