### ISSUE TITLE
open any external command details(preview etc.) results in blank splitscreen

### ISSUE THREAD

**Issue by Pio84** [Icinga/icingaweb2-module-director#2447]
## Expected Behavior
it should open submenu from the command.

## Current Behavior
like said, it splits the screen but the right side is blank. 
Browser Debugger shows:
`Uncaught TypeError: $target.data(...) is undefined`
`icinga.min.js:588:310`
This is the line:
`icinga.logger.debug('Discarding detail url '+url+' as it\'s the origin of the redirect');return false;});}}}else{if(url.match(/#!/)){var parts=url.split(/#!/);icinga.ui.layout2col();this.loadUrl(parts.shift(),$('#col1'));this.loadUrl(parts.shift(),$('#col2'));}else{if($target.attr('id')==='col2'){if($target.data('icingaUrl').split('?')[0]===url.split('?')[0]){}else if($('#col1').data('icingaUrl').split('?')[0]===url.split('?')[0]){icinga.ui.layout1col();$target=$('#col1');delete(this.requests['col2']);}}`

## Possible Solution
The reason iam here

## Steps to Reproduce (for bugs)
I think I screwed up manually adding mail host notification. And then overwrite it with an import using the infrastructure wizard.

## Your Environment

* Director version (System - About): **1.8.1**
* Icinga Web 2 version and modules (System - About): 
* Icingaweb2: 2.9.4
* incubator 0.6.0
* monitoring 2.9.4
* icinga/icinga-php-library 0.7.0
* inga/icinga-php-thirdparty 0.10.0

* Icinga 2 version (`icinga2 --version`): r2.13.1-1
* System information:
  Platform: Ubuntu
  Platform version: 20.04.3 LTS (Focal Fossa)
  Kernel: Linux
  Kernel version: 5.4.0-91-generic
  Architecture: x86_64

Build information:
  Compiler: GNU 9.3.0
  Build host: runner-hh8q3bz2-project-508-concurrent-0
  OpenSSL version: OpenSSL 1.1.1f  31 Mar 2020

Application information:

General paths:
  Config directory: /etc/icinga2
  Data directory: /var/lib/icinga2
  Log directory: /var/log/icinga2
  Cache directory: /var/cache/icinga2
  Spool directory: /var/spool/icinga2
  Run directory: /run/icinga2

Old paths (deprecated):
  Installation root: /usr
  Sysconf directory: /etc
  Run directory (base): /run
  Local state directory: /var

Internal paths:
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

* Webserver, PHP versions:
* Server version: Apache/2.4.41 (Ubuntu)
* PHP 8.0.13

what is the best way to flush the commands an make a new import, without any loss of other data like datafields, datacategorys, user, timeperiods etc.
Or should I export everything I need in baskets and go back to the backup after the initial installation.

thanks pio

**Comment by Thomas-Gelf** [comment]
Please upgrade to Icinga Web 2.9.5, see [#4598](https://github.com/Icinga/icingaweb2/issues/4598) for details
