### ISSUE TITLE
Service set members get mixed up when editing

### ISSUE THREAD

**Issue by dbecker1234** [Icinga/icingaweb2-module-director#2449]
## Expected Behavior
Create two service sets, assign each a service which inherit of the same template.
Overwrite some variables, but with different values.
Till this point everything is working fine, you see the different values in the preview:

```
apply Service "USV Battery Health" {
    import "USV Battery Health"

    assign where "USV" in host.groups && host.vars.vendor != "APC"
    vars.ups_criticalx = "remaining_time=:15"
    vars.ups_warningx = "remaining_time=:30"

    import DirectorOverrideTemplate
}
```
vs.

```
apply Service "USV Battery Health" {
    import "USV Battery Health"

    assign where "USV" in host.groups && host.vars.vendor == "APC"
    vars.ups_criticalx = "remaining_time=:2"
    vars.ups_warningx = "remaining_time=:5"

    import DirectorOverrideTemplate
}
```
Try to edit those services again.

## Current Behavior
With both service sets you can only edit the first member service.
Meaning both URLs 
```
/icingaweb2/director/service?name=USV Battery Health&set=USV-Small
/icingaweb2/director/service?name=USV Battery Health&set=USV-Big
```
targets the same service and you cannot edit the other one.
Also when clicking on the service tab of services sets using the same inherited templates the focus in the service set window change to one of the other sets (but not every time).

## Possible Solution
You should be able to edit the services separately and the focus should not jump. 

## Steps to Reproduce (for bugs)
see above

## Your Environment

* Director version (System - About): master (100bc4b7775155139ae6fdaf9be0986aac0f15c6)
* Icinga Web 2 version and modules (System - About): 2.9.5
* Icinga 2 version (`icinga2 --version`): 2.13.2
* Operating System and version: Debian 11
* Webserver, PHP versions: Apache 2.4.51, PHP 7.4.25

**Comment by Thomas-Gelf** [comment]
Thanks for reporting this, should now work as expected
