### ISSUE TITLE
Unable to rollout a variable with $ in it

### ISSUE THREAD

**Issue by CHOOH1992** [Icinga/icingaweb2-module-director#2450]
Hi,
i assume this is just an error by not knowing how to correctly add the variable..

We tried to add the name of a hidden share to the disk_smb check ( https://icinga.com/docs/icinga-2/latest/doc/10-icinga-template-library/#disk_smb ) in Icingaweb2 Director.

Name of the share: data$

Added this to vars (disk_smb_share) on rollout the director stucks. (Stops the rollout)

## Current Behavior
[2021-12-09 14:55:50 +0000] critical/config: Error: Validation failed for object 'XXXXX!Check Data Share' of type 'Service'; Attribute 'vars' -> 'disk_smb_share': Closing $ not found in macro format string ''data$''.

## Your Environment

* Director version (System - About): 1.8.1
* Icinga Web 2 version and modules (System - About): 2.9.5
* Icinga 2 version (`icinga2 --version`): 2.13.2
* Webserver, PHP versions: Apache, php7.4.3

**Comment by mocdaniel** [comment]
Hi,

in Icinga's DSL, `$` needs to be escaped by another `$` since Icinga will try to resolve a macro following `$` otherwise.

So just enter `data$$` as the name of your share and you should be fine.

Best,
Daniel

**Comment by CHOOH1992** [comment]
Hi,
thanks for the fast reply! Working well now, have a nice day.
Best regards
