### ISSUE TITLE
Modification stored for wrong Service

### ISSUE THREAD

**Issue by bobapple** [Icinga/icingaweb2-module-director#2452]
## Expected Behavior
Modifying a Service updates the Service of the correct Host.

## Current Behavior
I habe a service template called "HTTP" which I use on multiple hosts. I recently discovered that in some cases the wrong service gets updated.

Eg.: I modify the Service "host1!HTTP" and change the vhost, insted the vhost of "host2!HTTP" is changed.

The URL points to the correct host!service, however after storing the changes I can see in the activity log that the wrong service was updated.

I thought that this behaviour appeared after having some difficulties with a certain host. I was able to resolv it by deleting the host and re-creating it. Unfortunately, I can now see the same misbehaviour on completely now host!service.

## Steps to Reproduce (for bugs)
Not sure about this, since I was only able to reproduce it in my production environment. I updated the environment from 1.8.1 to master a couple of weeks ago. I pulled the master branch every now and than, most recently today.

I could provide access to the environment for debugging if that helps.

## Your Environment
* Director version (System - About): master (`27e5e72f410c11a6c207f5411747176e6b8a8587`)
* Icinga Web 2 version and modules (System - About): 2.9.5
* Icinga 2 version (`icinga2 --version`): r2.13.2-1
* Operating System and version: Ubuntu 20.04
* Webserver, PHP versions: PHP 7.4.3

**Comment by Thomas-Gelf** [comment]
To reproduce this: go to your service using the link provided by the activity log. That link still uses the service name, and not it's UUID. However, this is perfectly legal and must be supported for quite some time. Took me some time to understand how to reproduce this and to track down the real bug. Thanks a lot for finding and reporting this!

**Comment by bobapple** [comment]
Can confirm it's fixed, thank you!
