### ISSUE TITLE
Cant Upload Director Basket

### ISSUE THREAD

**Issue by fesch89** [Icinga/icingaweb2-module-director#2458]
## Expected Behavior
The Director Basket JSON File shoud be uploaded and Basket should be created

## Current Behavior
Upload Fails with Error "File 'director.json' exceeds the defined ini size"

## Your Environment
* Director version (System - About): 1.8.1
* Icinga Web 2 version and modules (System - About): 2.9.5
* Icinga 2 version (`icinga2 --version`): 2.13.2-1
* Operating System and version: CentOS7
* Webserver, PHP versions: Apache2, PHP7.3

**Comment by Thomas-Gelf** [comment]
Please check your server's `upload_max_filesize` and `post_max_size` settings (`php.ini`)

**Comment by fesch89** [comment]
Hi Thomas,
thank you very much for your advice. That worked. I had to adjust the "max_allowed_packet" in the MySQL server.cnf afterwards, in case someone should have the problem again.
