### ISSUE TITLE
multiselect for hosts and services broken in current master build

### ISSUE THREAD

**Issue by moreamazingnick** [Icinga/icingaweb2-module-director#2466]
## Expected Behavior
multiselect should work 

## Current Behavior
On a mac: select one host press "cmd" and select another host produces an error 
if you exchange the uuid in the url with the corresponding id's it works as expected

![Screenshot 2022-01-25 at 00 39 19](https://user-images.githubusercontent.com/29682206/150883624-e419e436-e1ba-49b1-a27e-cce56bb748b7.png)

## Your Environment

* Director version (System - About): master -25.01.2022
* Icinga Web 2 version and modules (System - About):2.9.5
* Icinga 2 version (`icinga2 --version`): 2.13.2
* Operating System and version: Ubuntu 20.04
* Webserver, PHP versions: 7.4

**Comment by Thomas-Gelf** [comment]
Thanks for reporting this!

**Comment by moreamazingnick** [comment]
This is not fixed
