### ISSUE TITLE
[Feature Request] Time details in director jobs

### ISSUE THREAD

**Issue by tbauriedel** [Icinga/icingaweb2-module-director#2470]
Currently in Director Jobs it is only possible to select an run interval for the execution of the jobs.

For more accurate and better scheduling of jobs, it would be good to have a way to specify exact times for execution.

For example:
Mondays, 18:31, daily 02:00, weekday 06:00 & 12:00 etc.

In "Scheduled Downtimes" there is already a similar function to set the ranges. Such a function for jobs would be extremely helpful.

![Bildschirmfoto 2022-02-07 um 08 41 12](https://user-images.githubusercontent.com/44896393/152745451-3fb73bf0-88bf-4747-ad84-2e09d593d7df.png)

**Comment by Thomas-Gelf** [comment]
> In "Scheduled Downtimes" there is already a similar function to set the ranges

The same is true for Jobs. Define a Time Period - and the Job will allow you to pick one.

As discussed:

* time slot can be influenced by defining Time periods
* a short run interval and a longer grace period are the way to go, when automating deployments. The settings on the Screenshot are doing the complete opposite
* a Job will NEVER force the deployment of a configuration, when the very same configuration is already running
* the "Force Rendering" will only force to re-render it's very own configuration (as field description states), and not force a deployment. This is only useful when an external static source ships configuration through the Director, like the "Configuration File Shipping" feature of the fileshipper module does. Normally, when there is nothing in the Activity Log, Director doesn't even bother to render a new configuration. Which means, that changes in an external Directory would get unnoticed.

Closing this issue, works as expected. Running at "just one specific moment in time" is not what Jobs have been defined for. The combination of Import, Sync and Deployment allows for consistent Deployments according specific rules. There will never be half-finished Imports or Sync operations, and no needless Deployments are being forced.

Cheers,
Thomas
