### ISSUE TITLE
Activity Log: allow remarks

### ISSUE THREAD

**Issue by Thomas-Gelf** [Icinga/icingaweb2-module-director#2471]
Used by an add-on module for now, Director just provides the base infrastructure. Implementation is there since quite a while, UI components where missing:

![activity_with_merge-remark](https://user-images.githubusercontent.com/553008/152939853-d33cf7f4-34ac-4251-9400-43bdc1addca4.png)

An older screenshot shows some trickier remarks. different colors have been removed:

![director_activitylog_remarks](https://user-images.githubusercontent.com/553008/152939547-a0356bcb-45b2-4875-a707-f8fe0c1d92e9.png)

**Comment by Tqnsls** [comment]
@Thomas-Gelf Hi Thomas, 
Thank you very much for releasing a new version! 
Could it be that you forgot to add a new column "uuid" to "director_datalist_entry"?

![image](https://user-images.githubusercontent.com/67681686/154525457-65a36326-f90c-4cbe-a369-0374d6371b31.png)

Kind regards

**Comment by Tqnsls** [comment]
Could you give more information which module adds the notes / remarks to the activity log pls?
