### ISSUE TITLE
Drop hook `IcingaDbCubeLinks`

### ISSUE THREAD

**Issue by nilmerg** [Icinga/icingaweb2-module-director#2480]
Drop the hook `IcingaDbCubeLinks` and provide a new one implementing the new interface. Make sure it uses a different name, to not run into problems with Director v1.9.0 and Cube 1.2.0.

I like the idea with `getHostNames()` though. Please add a similar method (`getObjectNames()`) to the abstract class `IcingaDbCube` and implement it in it's implementations.

**Comment by Thomas-Gelf** [comment]
@raviks789 provided a new/fixed implementation of this Hook, so I guess it's no longer required to drop it
