### ISSUE TITLE
upgrading and installation links in Release INFO dead

### ISSUE THREAD

**Issue by tomabg** [Icinga/icingaweb2-module-director#2483]
for example https://github.com/Icinga/icingaweb2-module-director/blob/v1.9.0/05-Upgrading.md

**Comment by tomabg** [comment]
issue still exists for release 1.9.0 but release 1.9.1 is already there so imho correction no more needed

**Comment by Thomas-Gelf** [comment]
It IS relevant, thanks for reporting it - links for v1.9 should now be fine
