### ISSUE TITLE
V1.9.0 save host failed

### ISSUE THREAD

**Issue by tomabg** [Icinga/icingaweb2-module-director#2485]
After update to director v1.9.0 save host fails with:

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'director_datalist_entry.uuid' in 'field list', query was: SELECT director_datalist_entry.uuid FROM director_datalist_entry WHERE (`list_id` = 2) AND (`entry_name` = 'DX')

#0 /usr/share/icingaweb2/library/vendor/Zend/Db/Statement.php(297): Zend_Db_Statement_Pdo->_execute(Array)
#1 /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Abstract.php(470): Zend_Db_Statement->execute(Array)
#2 /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query(String, Array)
#3 /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Abstract.php(816): Zend_Db_Adapter_Pdo_Abstract->query(Object(Zend_Db_Select), Array)
#4 /usr/share/icingaweb2/modules/director/library/Director/Db/Branch/UuidLookup.php(117): Zend_Db_Adapter_Abstract->fetchOne(Object(Zend_Db_Select))
#5 /usr/share/icingaweb2/modules/director/library/Director/Db/Branch/UuidLookup.php(91): Icinga\Module\Director\Db\Branch\UuidLookup::fetchOptionalUuid(Object(Icinga\Module\Director\Db), Object(Zend_Db_Select))
#6 /usr/share/icingaweb2/modules/director/library/Director/Data/Db/DbObject.php(1377): Icinga\Module\Director\Db\Branch\UuidLookup::findUuidForKey(Array, String, Object(Icinga\Module\Director\Db), Object(Icinga\Module\Director\Db\Branch\Branch))
#7 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/Validate/IsDataListEntry.php(53): Icinga\Module\Director\Data\Db\DbObject::exists(Array, Object(Icinga\Module\Director\Db))
#8 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/Validate/IsDataListEntry.php(39): Icinga\Module\Director\Web\Form\Validate\IsDataListEntry->isListEntry(String)
#9 /usr/share/icingaweb2/library/vendor/Zend/Form/Element.php(1428): Icinga\Module\Director\Web\Form\Validate\IsDataListEntry->isValid(String, Array)
#10 /usr/share/icingaweb2/library/vendor/Zend/Form.php(2280): Zend_Form_Element->isValid(String, Array)
#11 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/QuickForm.php(393): Zend_Form->isValid(Array)
#12 /usr/share/icingaweb2/modules/director/library/Director/Web/Controller/ObjectController.php(638): Icinga\Module\Director\Web\Form\QuickForm->handleRequest()
#13 /usr/share/icingaweb2/modules/director/library/Director/Web/Controller/ObjectController.php(171): Icinga\Module\Director\Web\Controller\ObjectController->addObjectForm(Object(Icinga\Module\Director\Objects\IcingaHost))
#14 /usr/share/icingaweb2/modules/director/application/controllers/HostController.php(99): Icinga\Module\Director\Web\Controller\ObjectController->editAction()
#15 /usr/share/icingaweb2/modules/director/library/Director/Web/Controller/ObjectController.php(117): Icinga\Module\Director\Controllers\HostController->editAction()
#16 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Director\Web\Controller\ObjectController->indexAction()
#17 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch(String)
#18 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#19 /usr/share/php/Icinga/Application/Web.php(304): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#20 /usr/share/php/Icinga/Application/webrouter.php(107): Icinga\Application\Web->dispatch()
#21 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#22 {main}
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'director_datalist_entry.uuid' in 'field list'

#0 /usr/share/icingaweb2/library/vendor/Zend/Db/Statement/Pdo.php(219): PDOStatement->execute(Array)
#1 /usr/share/icingaweb2/library/vendor/Zend/Db/Statement.php(297): Zend_Db_Statement_Pdo->_execute(Array)
#2 /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Abstract.php(470): Zend_Db_Statement->execute(Array)
#3 /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query(String, Array)
#4 /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Abstract.php(816): Zend_Db_Adapter_Pdo_Abstract->query(Object(Zend_Db_Select), Array)
#5 /usr/share/icingaweb2/modules/director/library/Director/Db/Branch/UuidLookup.php(117): Zend_Db_Adapter_Abstract->fetchOne(Object(Zend_Db_Select))
#6 /usr/share/icingaweb2/modules/director/library/Director/Db/Branch/UuidLookup.php(91): Icinga\Module\Director\Db\Branch\UuidLookup::fetchOptionalUuid(Object(Icinga\Module\Director\Db), Object(Zend_Db_Select))
#7 /usr/share/icingaweb2/modules/director/library/Director/Data/Db/DbObject.php(1377): Icinga\Module\Director\Db\Branch\UuidLookup::findUuidForKey(Array, String, Object(Icinga\Module\Director\Db), Object(Icinga\Module\Director\Db\Branch\Branch))
#8 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/Validate/IsDataListEntry.php(53): Icinga\Module\Director\Data\Db\DbObject::exists(Array, Object(Icinga\Module\Director\Db))
#9 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/Validate/IsDataListEntry.php(39): Icinga\Module\Director\Web\Form\Validate\IsDataListEntry->isListEntry(String)
#10 /usr/share/icingaweb2/library/vendor/Zend/Form/Element.php(1428): Icinga\Module\Director\Web\Form\Validate\IsDataListEntry->isValid(String, Array)
#11 /usr/share/icingaweb2/library/vendor/Zend/Form.php(2280): Zend_Form_Element->isValid(String, Array)
#12 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/QuickForm.php(393): Zend_Form->isValid(Array)
#13 /usr/share/icingaweb2/modules/director/library/Director/Web/Controller/ObjectController.php(638): Icinga\Module\Director\Web\Form\QuickForm->handleRequest()
#14 /usr/share/icingaweb2/modules/director/library/Director/Web/Controller/ObjectController.php(171): Icinga\Module\Director\Web\Controller\ObjectController->addObjectForm(Object(Icinga\Module\Director\Objects\IcingaHost))
#15 /usr/share/icingaweb2/modules/director/application/controllers/HostController.php(99): Icinga\Module\Director\Web\Controller\ObjectController->editAction()
#16 /usr/share/icingaweb2/modules/director/library/Director/Web/Controller/ObjectController.php(117): Icinga\Module\Director\Controllers\HostController->editAction()
#17 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Director\Web\Controller\ObjectController->indexAction()
#18 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch(String)
#19 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#20 /usr/share/php/Icinga/Application/Web.php(304): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#21 /usr/share/php/Icinga/Application/webrouter.php(107): Icinga\Application\Web->dispatch()
#22 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#23 {main}

**Comment by gianmarco-mameli** [comment]
Hi, same problem for me, cannot save host with changed datalist field

**Comment by tomabg** [comment]
retest in 1.9.1 was passed..seems fixed with datalist fix
