### ISSUE TITLE
Basket with simple Service set contains Malformed UTF-8 characters

### ISSUE THREAD

**Issue by mwaldmueller** [Icinga/icingaweb2-module-director#2488]
## Current Behavior
Creation of basket snapshot fails if Service set is included:
<img width="621" alt="basket1" src="https://user-images.githubusercontent.com/3973350/157237184-0ed6f47f-6fff-41af-9f32-57969c362baf.png">

Example Service set:
<img width="619" alt="serviceset1" src="https://user-images.githubusercontent.com/3973350/157237484-d6eb1253-f0c6-4296-b2e1-943196df925a.png">

## Your Environment

* Director version (System - About): 1.9.0
* Icinga Web 2 version and modules (System - About): 2.9.5
* Icinga 2 version (`icinga2 --version`): 2.13.2
* Operating System and version: EL8
* Webserver, PHP versions: Apache, PHP 7.2.24

**Comment by akqopensystems** [comment]
+1 - We have the same behavior
