### ISSUE TITLE
Failed to start Icinga Director

### ISSUE THREAD

**Issue by allanlouie-entel** [Icinga/icingaweb2-module-director#2493]
Director version 1.9.0
Icinga Web 2 version 2.9.5
CentOS Linux release 7.9.2009 (Core)
PHP versions 7.3.29

Hi Guys,

I have encounter this error and i hope somebody can help me as i'm new to this linux/centos/icinga
i manage this far and cant wait to pull thru to monitor our servers.

this is the error i get

[root@entelphmon admin]# systemctl status icinga-director.service -l
● icinga-director.service - Icinga Director - Monitoring Configuration
Loaded: loaded (/etc/systemd/system/icinga-director.service; enabled; vendor preset: disabled)
Active: activating (auto-restart) (Result: exit-code) since Mon 2022-03-14 17:53:37 PST; 2s ago
Docs: [Introduction - Icinga Director](https://icinga.com/docs/director/latest/)
Process: 9646 ExecStart=/usr/bin/icingacli director daemon run (code=exited, status=255)
Main PID: 9646 (code=exited, status=255)

Mar 14 17:53:37 entelphmon systemd[1]: Unit icinga-director.service entered failed state.
Mar 14 17:53:37 entelphmon systemd[1]: icinga-director.service failed.

I'm hoping for favorable response.

**Comment by erik911** [comment]
Hi,
check requirements and your php extensions. Probably php-pcntl ( Process Control ) is missing.

**Comment by allanlouie-entel** [comment]
thank @erik911 for the reply, i have installed the php-pcntl but i still get an error when im starting the service.

![image](https://user-images.githubusercontent.com/101700168/158718072-43f4c9f4-34f7-4405-b259-840904dd3356.png)

**Comment by allanlouie-entel** [comment]
what other things i needed to check on this? i appreciate the help.

**Comment by allanlouie-entel** [comment]
![image](https://user-images.githubusercontent.com/101700168/158723143-cbf0d9bd-42d2-4111-8528-5cde5b33ae48.png)
here are the list of the php installed on my system, do you think i miss out something?

**Comment by allanlouie-entel** [comment]
this is now resolved i manage to find what is missing, thanks for your help
