### ISSUE TITLE
Theme Modus: dark

### ISSUE THREAD

**Issue by hashfunktion** [Icinga/icingaweb2-module-director#2521]
Hello together,

since the new IcingaWeb2 Version have the option of Color Mode of the Theme (Dark/Light/System) the director Module is not really god in the Dark Mode - see Expected Behavior.
Is this a general bug in the director module or it is a client problem? 

## Expected Behavior
When I´m using the dark theme mod with the default Theme in the Director Module the text in input fields should be visible.

## Current Behavior
When I´m using the dark theme mod with the default Theme in the Director Module the text in input fields is not visible because it´s written in white color.
![image](https://user-images.githubusercontent.com/5895349/162738595-62037ede-2b7d-41ef-af2d-a6994a691934.png)

## Your Environment

The Icinga 2 network monitoring daemon **_(version: r2.13.2-1)_**

System information:
  Platform: Ubuntu
  Platform version: 20.04.4 LTS (Focal Fossa)
  Kernel: Linux
  Kernel version: 5.4.0-107-generic
  Architecture: x86_64

Build information:
  Compiler: GNU 9.3.0
  Build host: runner-hh8q3bz2-project-298-concurrent-0
  OpenSSL version: OpenSSL 1.1.1f  31 Mar 2020

Icinga Web 2 Version 2.10.0
PHP 7.4.28

businessprocess		2.4.0
company		0.0.0
director		1.9.0
fileshipper		1.0.1
grafana		Master
idoreports		0.9.1
incubator		0.14.0
ipl		v0.5.0
map		1.1.0
monitoring		2.10.0
pdfexport		0.9.1
reactbundle		0.9.0
reporting		0.9.1
x509		1.1.0	

Client:
MacOS 12.3.1
Safari / MS Edge / Google Chrome (actual Versions)

**Comment by nilmerg** [comment]
Hi,

you didn't notice that there is a v1.9.1 available with support for the dark mode, I guess. :wink:

**Comment by hashfunktion** [comment]
Hi,
oh, actually I meant to write the issue last week and only just got around to it. There was no new release yet, the last days I had not looked for a new release 

Thanks and sorry!

BR
