### ISSUE TITLE
Director doesn't save changes to timeperiods (when using browser)

### ISSUE THREAD

**Issue by Stefomat** [Icinga/icingaweb2-module-director#2525]
## Expected Behavior

When going to Director > Timeperiods > Timeperiods to adjust a time period, i press save, roll out the new configuration an it gets activated.

## Current Behavior

When I go to Director > Timeperiods > Timeperiods to adjust a time period, the Director shows me a change in the activity log, but after rolling out the configuration, it is not active. Immediately after pressing "Save" of the changed period, the old period is displayed again.

## Possible Solution

You can use the cli version of the director, e.g.
`icingacli director timeperiod set arbeitszeit --json '{"ranges": { "friday": "08:00-13:00", "monday": "08:00-16:00", "thursday": "08:00-16:00", "tuesday": "08:00-16:00", "wednesday": "08:00-16:00" }}'`

## Steps to Reproduce (for bugs)

Have a timeperiod configured or create a new one, e.g.
```
object TimePeriod "arbeitszeit" {
    import "legacy-timeperiod"
    display_name = "Normale Arbeitszeit"
    ranges = {
        "friday"	= "08:00-13:00"
        "monday"	= "08:00-16:00"
        "thursday"	= "08:00-16:00"
        "tuesday"	= "08:00-16:00"
        "wednesday"	= "08:00-16:00"
    }
}
```
Now go back to Director > Timeperiods > Timeperiods and try to modify one of the periods, e.g. tuesday from 16:00 to 17:00
Click save, view the activity log and try to activate the new configuration.

## Your Environment

* Director version (System - About): 1.9.0
* Icinga Web 2 version and modules (System - About): 2.9.6
* Icinga 2 version (`icinga2 --version`): r2.13.2-1
* Operating System and version: Debian GNU/Linux 10
* Webserver, PHP versions: Apache2 2.4.38 | PHP 7.3

**Comment by Yoda-BZH** [comment]
I also have this behaviour when editing Scheduled downtimes. I suppose it's since v1.9.0 .

When editing a scheduled downtime, I have an entry in the activity log showing the change. However, each previously edited line has it's value reset.

Exemple: 
step 1: edit friday
![image](https://user-images.githubusercontent.com/751889/164384006-72542824-abe0-4050-9572-a2c853d46363.png)


step 2: edit monday
![image](https://user-images.githubusercontent.com/751889/164384157-f32c54ad-748e-4f0d-b1ab-55b387966f21.png)

note that friday is back to it's previous value.

**Comment by lucafwp** [comment]
Hi @Thomas-Gelf, since this has been removed from 1.10.0 milestone, will it be added to next version?
Is there a way to fix this?

**Comment by Thomas-Gelf** [comment]
Hi @lucafwp,

guess this was just a matter of running out of time for the release. I'm working on v1.10.2 today and tomorrow, I'll try to fix this too.

Cheers,
Thomas

**Comment by Thomas-Gelf** [comment]
Took me some time to track this time. Fixing it was easy - once I understood the problem :sweat_smile:
