### ISSUE TITLE
Can't viably import External Command Definitions from Basket

### ISSUE THREAD

**Issue by Nayakum** [Icinga/icingaweb2-module-director#2527]
## Expected Behavior
When importing a Basket containing an External Command Definitions, I'd expect to be able to use said Definitions.

## Current Behavior
In my case, I create a Definition in /etc/icinga2/zones.d/global-templates in my test environment, and then ex- and import it to production via Basket through Icingaweb.

![grafik](https://user-images.githubusercontent.com/84782250/165031752-3bb2a14c-3b7e-4001-9179-610d827e2711.png)

The ex- and import themselves work and I can create Service Templates and Services with the Definition, but Deployment fails because the CheckCommand doesn't exist.
Kickstarting after the import deletes the Definition, as long as it isn't used already in a Service Template. In this case, I first have to delete the Template.
I didn't test whether it's possible to create the Definition in the Icingaweb Director and then correctly ex- and import it via Basket.

## Possible Solution
The ability to create an External Command Definition in /etc/icinga2/zones.d/global-templates and being able to ex- and import it via Director Basket.

## Steps to Reproduce (for bugs)
1. Go to /etc/icinga2/zones.d/global-templates and create a new Command Definition, e.g. by adding it to an existing file.
2. Export said Definition via Basket in Icingaweb.
3. Import this into another environment.
4. Build a Service Template upon this new Definition and deploy.

[2022-04-22 08:46:36 +0200] information/cli: Loading configuration file(s).
[2022-04-22 08:46:37 +0200] information/ConfigItem: Committing config item(s).
[2022-04-22 08:46:37 +0200] information/ApiListener: My API identity: prod_server
[2022-04-22 08:46:38 +0200] critical/config: Error: Validation failed for object 'prod_server!Test Export' of type 'Service'; Attribute 'check_command': Object 'test_basket_export' of type 'CheckCommand' does not exist.

5. Additionally, use the kickstart in Icingaweb.

## Your Environment

* Director version (System - About): 1.9.1
* Icinga Web 2 version and modules (System - About): 2.8.2

![grafik](https://user-images.githubusercontent.com/84782250/165031220-c55c9810-f00d-4f96-9d53-3e9a9bce2a9c.png)

* Icinga 2 version (`icinga2 --version`): r2.13.1-1
* Operating System and version: SLES 15
* Webserver, PHP versions: 7.2.5

**Comment by Thomas-Gelf** [comment]
External Commands assume, that your Icinga 2 Core knows about those commands via other means (usually text-based configuration). They'll not be deployed by the Director, their solely purpose is to make them accessible and usable in your Director UI via Service Templates. So according to your description, everything seems to work as expected.
