### ISSUE TITLE
Alerts are not cleaned up when removing last remain hosts from a zone

### ISSUE THREAD

**Issue by stupiddr** [Icinga/icingaweb2-module-director#2535]
## Expected Behavior
When all hosts are removed from a zone a blank hosts.conf file for that zone is written so that the hosts are no longer monitored

## Current Behavior
When all hosts are removed from a Zone the file /var/lib/icinga2/api/zones/ZONE/director/hosts.conf is no longer written
and the host continues to be monitored

## Possible Solution
If a Zone is defined and no hosts exist in the Zone write a blank hosts.conf for that zone

## Steps to Reproduce (for bugs)
Add a single host to a Zone and deploy changes so the Host is monitored.
Remove the host from the Zone and deploy changes.
You'll then see the host continues to be monitored.

## Your Environment

* Director version (System - About):
* Icinga Web 2 version and modules (System - About): 2.9.6
* Icinga 2 version (`icinga2 --version`): 1.9.0
```
icinga2 - The Icinga 2 network monitoring daemon (version: 2.13.2-1)

Copyright (c) 2012-2022 Icinga GmbH (https://icinga.com/)
License GPLv2+: GNU GPL version 2 or later <https://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

System information:
  Platform: CentOS Linux
  Platform version: 7 (Core)
  Kernel: Linux
  Kernel version: 3.10.0-1160.62.1.el7.x86_64
  Architecture: x86_64

Build information:
  Compiler: GNU 4.8.5
  Build host: runner-hh8q3bz2-project-322-concurrent-0
  OpenSSL version: OpenSSL 1.0.2k-fips  26 Jan 2017

Application information:

General paths:
  Config directory: /etc/icinga2
  Data directory: /var/lib/icinga2
  Log directory: /var/log/icinga2
  Cache directory: /var/cache/icinga2
  Spool directory: /var/spool/icinga2
  Run directory: /run/icinga2

Old paths (deprecated):
  Installation root: /usr
  Sysconf directory: /etc
  Run directory (base): /run
  Local state directory: /var

Internal paths:
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid
  ```
* Operating System and version:
CentOS 7
* Webserver, PHP versions:
nginx/1.20.1
php/8.0.18

**Comment by Thomas-Gelf** [comment]
This sounds like an [issue](https://github.com/Icinga/icinga2/issues/3323) that should have been solved long time ago. Honestly, I lost track about it's state as the issue has been "rebranded" and shifted around multiple times. In case it still persists, please create a dedicated [Icinga 2 issue](https://github.com/Icinga/icinga2/issues).
