### ISSUE TITLE
API request failed: Invalid stage name 'monitor1.example.com-1640382790-113'. (RestApiResponse.php:92)

### ISSUE THREAD

**Issue by BigAndini** [Icinga/icingaweb2-module-director#2540]
## Expected Behavior

Hey, I'm not able to take over the changes from the director module into my icinga instance with the error of the title. Googling around a bit brought me to permissions are not set correctly, However when I check the permissions of the director api user there is only a single asterisk, so it should have all permissions. I would expect to be able to deploy configuration with click on "Deploy x pending changes" again.

## Current Behavior

Right now I click on the link to deploy the changes and only get the above error message.

## Steps to Reproduce (for bugs)

As of now I cannot tell, yet how to setup icinga director to break the system like this.

## Your Environment

* Director version (System - About): 1.3.1
* Icinga Web 2 version and modules (System - About): 2.10.1
* Icinga 2 version (`icinga2 --version`): icinga2 - The Icinga 2 network monitoring daemon (version: r2.13.3-1)
* Operating System and version: CentOS 7
* Webserver, PHP versions: Apache, PHP 7.4

**Comment by Thomas-Gelf** [comment]
Stage names are chosen by Icinga itself, Director has no control over this. Not sure what went wrong, but I'm glad to hear that it then worked fine for you ;-)
