### ISSUE TITLE
Uncaught Error: Call to a member function toString()  when navigating to service templates from rendered previews

### ISSUE THREAD

**Issue by mocdaniel** [Icinga/icingaweb2-module-director#2554]
## Expected Behavior

When navigating to a service template from a rendered preview (e.g. of a service set or apply rule), the `Modify` tab of said service template should open.

## Current Behavior

When navigating to a service template from a rendered preview (e.g. of a service set or apply rule) by clicking the linked 

`import "this-template-crashes"`

the following stack trace is displayed:

```
Uncaught Error: Call to a member function toString() on null in /usr/share/icingaweb2/modules/director/application/controllers/ServiceController.php:254
Stack trace:
#0 /usr/share/icingaweb2/modules/director/library/Director/Web/Controller/ObjectController.php(497): Icinga\Module\Director\Controllers\ServiceController->loadObject()
#1 /usr/share/icingaweb2/modules/director/library/Director/Web/Controller/ObjectController.php(90): Icinga\Module\Director\Web\Controller\ObjectController->loadOptionalObject()
#2 /usr/share/icingaweb2/modules/director/application/controllers/ServiceController.php(46): Icinga\Module\Director\Web\Controller\ObjectController->init()
#3 /usr/share/php/Icinga/Web/Controller/ActionController.php(170): Icinga\Module\Director\Controllers\ServiceController->init()
#4 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(59): Icinga\Web\Controller\ActionController->__construct()
#5 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch()
#6 /usr/share/php/Icinga/Application/Web.php(304): Zend_Controller_Front->dispatch()
#7 /usr/share/php/Icinga/Application/webrouter.php(109): Icinga\Application\Web->dispatch()
#8 /usr/share/icingaweb2/public/index.php(4): require_once('...')
#9 {main}
thrown

#0 [internal function]: Icinga\Application\Web->Icinga\Application\{closure}()
#1 {main}
```

## Possible Solution

From my observations, it's probably some bug connected to the recently introduced `UUIDs` - when editing a service template 'the normal way', the URL looks like this:

http://10.77.14.179/icingaweb2/director/services/templates#!/icingaweb2/director/service/edit?uuid=fc11b6b9-5e88-4fed-b9f0-a7320f00bdce

While the navigation process described above leads to a URL like this:

http://10.77.14.179/icingaweb2/director/services/applyrules#!/icingaweb2/director/service?name=generic-service

## Steps to Reproduce (for bugs)

1. Create a generic service template with arbitrary configuration
2. Create a new apply rule or service (within a service set or standalone)
3. Open the 'preview' tab of this service
4. Click the linked template

## Your Environment

* Director version (System - About): v1.9.1
* Icinga Web 2 version and modules (System - About): v2.9.6 / v2.10.1
* Icinga 2 version (`icinga2 --version`): v2.13.3
* Operating System and version: RHEL8.5
* Webserver, PHP versions: httpd, PHP v7.4.19 / v8.0.13

**Comment by Thomas-Gelf** [comment]
Thanks for reporting this, it is related to #2487. As a workaround please use the following patch:

```patch
diff --git a/application/controllers/ServiceController.php b/application/controllers/ServiceController.php
index ec9545ef..34d698a6 100644
--- a/application/controllers/ServiceController.php
+++ b/application/controllers/ServiceController.php
@@ -251,6 +251,11 @@ class ServiceController extends ObjectController
 
         $key = $this->getLegacyKey();
         $uuid = UuidLookup::findServiceUuid($this->db(), $this->getBranch(), 'object', $key, $this->host, $this->set);
+        foreach (['apply', 'template'] as $type) {
+            if ($uuid === null) {
+                $uuid = UuidLookup::findServiceUuid($this->db(), $this->getBranch(), $type, $key, $this->host, $this->set);
+            }
+        }
         $this->params->set('uuid', $uuid->toString());
         parent::loadObject();
     }
```

The final fix might differ.
