### ISSUE TITLE
Debian bullseye error since icingaweb2 2.11.0 - Uncaught Error: Class 'Icinga\Util\Translator' not found in /usr/share/icingaweb2/modules/director/library/vendor/ipl/Compat/Translator.php:20

### ISSUE THREAD

**Issue by rseffner** [Icinga/icingaweb2-module-director#2556]
## Expected Behavior
Working links insider Director part of web UI

## Current Behavior
error as in subject

## Possible Solution
I reinstalled 2.10.1 debian packages from packages.icinga.org/debian

## Your Environment
debian bullseye with apache2 from debian.org, icinga2 and icingaweb2 from icinga.org, php7.4 from sury.org - php via fcgi

**Comment by rseffner** [comment]
If I remember right - it's over a year ago - by using apt-get intstall icinga2 icingaweb2

**Comment by rseffner** [comment]
I've seen today, there is also an package icingaweb2-module-director but If I Install this, it breaks something more. So I restored to the backup fromm before.

**Comment by lippserd** [comment]
I would recommend removing the director directory completely and (re)installing the [incubator](https://github.com/Icinga/icingaweb2-module-incubator/) and Director module from scratch via Git. We don't have packages for modules yet, but I would definitely not recommend installing them from Debian.

**Comment by rseffner** [comment]
Because I installed from pagackes.icinga.org (and not Debian) your hint will break package managemet with apt.

If I Install 2.10.1 Versions of icingaweb2* and php-icinga packages from mentioned repository everything works as expected. With updated versions 2.11.0 from same repo it does not.
Maybe I can fix ist using git versions but the reason for errors  will then still exist in repo.
I've no incubator in /ist/Share/icingaweb2/modules - why I should Update/Install it?

**Comment by lippserd** [comment]
> Because I installed from pagackes.icinga.org (and not Debian) your hint will break package managemet with apt.
 
Only if you have installed Director via packages which I doubt.

> I've no incubator in /ist/Share/icingaweb2/modules - why I should Update/Install it?

The Director has the incubator dependency since ages.

Your installation looks completely odd. So please remove Director and install incubator and Director via Git. Nothing more and nothing else.
