### ISSUE TITLE
Uncaught Error: Class 'Icinga\Util\Translator' not found in /usr/share/icingaweb2/modules/incubator/vendor/gipfl/icingaweb2/src/Translator.php:20

### ISSUE THREAD

**Issue by demel42** [Icinga/icingaweb2-module-director#2566]
## Expected Behavior
Opening the director link should display the director main screen

## Current Behavior
Uncaught Error: Class 'Icinga\Util\Translator' not found in /usr/share/icingaweb2/modules/incubator/vendor/gipfl/icingaweb2/src/Translator.php:20
Stack trace:
#0 /usr/share/icingaweb2/modules/incubator/vendor/gipfl/translation/src/TranslationHelper.php(17): gipfl\IcingaWeb2\Translator->translate()
#1 /usr/share/icingaweb2/modules/director/library/Director/Dashboard/Dashboard.php(146): Icinga\Module\Director\Dashboard\Dashboard->translate()
#2 /usr/share/icingaweb2/modules/director/library/Director/Dashboard/Dashboard.php(135): Icinga\Module\Director\Dashboard\Dashboard->createTabForDashboard()
#3 /usr/share/icingaweb2/modules/director/library/Director/Dashboard/HostsDashboard.php(32): Icinga\Module\Director\Dashboard\Dashboard->createTabsForDashboards()
#4 /usr/share/icingaweb2/modules/director/application/controllers/DashboardController.php(54): Icinga\Module\Director\Dashboard\HostsDashboard->getTabs()
#5 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Director\Controller

#0 [internal function]: Icinga\Application\Web->Icinga\Application\{closure}()
#1 {main}

## Steps to Reproduce (for bugs)
click on the link "Icinga-Director" in the main-menu oder an subpage of the director

## Your Environment

* Director version (System - About):
* Icinga Web 2 version and modules (System - About):

<img width="618" alt="Bildschirmfoto 2022-07-19 um 16 51 29" src="https://user-images.githubusercontent.com/24937941/179780848-1c6e1f2c-d9b3-4dfa-95cd-cf8d4d9dcb60.png">

* Icinga 2 version (`icinga2 --version`):
icinga2 - The Icinga 2 network monitoring daemon (version: r2.13.4-1)

Copyright (c) 2012-2022 Icinga GmbH (https://icinga.com/)
License GPLv2+: GNU GPL version 2 or later <https://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

System information:
  Platform: Ubuntu
  Platform version: 20.04.4 LTS (Focal Fossa)
  Kernel: Linux
  Kernel version: 5.15.35-1-pve
  Architecture: x86_64

Build information:
  Compiler: GNU 9.4.0
  Build host: runner-hh8q3bz2-project-298-concurrent-0
  OpenSSL version: OpenSSL 1.1.1f  31 Mar 2020

Application information:

General paths:
  Config directory: /etc/icinga2
  Data directory: /var/lib/icinga2
  Log directory: /var/log/icinga2
  Cache directory: /var/cache/icinga2
  Spool directory: /var/spool/icinga2
  Run directory: /run/icinga2

Old paths (deprecated):
  Installation root: /usr
  Sysconf directory: /etc
  Run directory (base): /run
  Local state directory: /var

Internal paths:
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid
  
* Operating System and version:
root@Icinga2:~# cat /etc/*release*
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"

seems to be like https://github.com/Icinga/icingaweb2-module-director/issues/2548?
i have made a apt update/upgrade before

**Comment by demel42** [comment]
perhaps, i have a problem of understanding.
i have done a fresh `apt update/upgrade`, but nothing changed.
in the linked issue, i see, that the *incubator* ist on version *master*, not on *0.11.0* like me. but i didn't updated single modules yet.
i have found the dir */etc/icingaweb2/enabledModules/incubator*, seems to be the content of the git repository.
should is get https://github.com/Icinga/icingaweb2-module-incubator/archive/refs/tags/v0.17.0.tar.gz an untarnished ist at this place?

thx

**Comment by Thomas-Gelf** [comment]
As the README states, make-release is for developers, and the master itself intentionally does not run. So installing the latest version as you did was the right move!
