### ISSUE TITLE
[dev.icinga.com #11853] Allow to delete deployments

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#258]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11853

**Created by sru on 2016-05-28 18:28:22 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-06-17 22:52:08 +00:00 (in Redmine)_

---

... at least failed ones.

I understand that you try to follow git style commits here.
But with times, lots of disfunctional configs might clutter up the list.

It is ok if only special permission roles are allowed to delete items from the list.

**Comment by Thomas-Gelf** [comment]
Please follow #1920
