### ISSUE TITLE
Creating new database schema failes due to duplicate line in SQL statement

### ISSUE THREAD

**Issue by 4L60** [Icinga/icingaweb2-module-director#2609]
Creating new database schema failes. Problem is a duplicate line in mysql.sql. That's line 2325 and 2326 (imports TEXT DEFAULT NULL,) in the "CREATE TABLE branched_icinga_service_set" statement.

**Comment by Thomas-Gelf** [comment]
Thank you for reporting this, @4L60. The issue been fixed, pushed to the main branch and cherry-picked to support/1.10 - it will be part of v1.10.1. As a workaround, please remove this line on new setups.

**Comment by 4L60** [comment]
Thank you for your quick reply and bugfixing! Removing the duplicate line did the job for me.
