### ISSUE TITLE
Import Job sets all names to lowercase

### ISSUE THREAD

**Issue by brusilva84** [Icinga/icingaweb2-module-director#2617]
## Expected Behavior
Host.name should be imported with the correct case from the datasource

## Current Behavior
I've upgraded to 1.10 and all my jobs of importing hosts are setting host.name to lowercase

## Steps to Reproduce (for bugs)
Create a Mysql query to import hosts. even if the hostname field is in upper it transforms to lower

## Your Environment

* Director version (System - About): 1.10
* Icinga Web 2 version and modules (System - About): Icinga DB Web1.0.1
* Icinga 2 version (`icinga2 --version`): version: r2.13.5-1)
* Operating System and version: debian buster
* Webserver, PHP versions: php 8.1

**Comment by Thomas-Gelf** [comment]
Please see #2608
