### ISSUE TITLE
Fix #2609 not in Debian package on packages.icinga.com/debian

### ISSUE THREAD

**Issue by anmith** [Icinga/icingaweb2-module-director#2628]
Hi,

I don't know if this is the right place for the issue:

As packages.icinga.com/debian (which was used for the Icinga installation according to the official instructions) claims to have director 1.10.0 available, I installed the module from the repository instead of downloading the tarball.

When trying to create the database scheme, I ran into the error fixed in

https://github.com/Icinga/icingaweb2-module-director/issues/2609

The latest release on GitHub is marked as "14 days ago", the fix was made 12 days ago, so the tar might also be broken for new installs.

**Comment by Thomas-Gelf** [comment]
If an issue is linked to a milestone, you can see which release to expect that fix - in this case v1.10.1. Seems that package builds have not been triggered yet, at least I cannot find a v1.10.1 package. IMHO a tag should trigger such builds - seems that it doesn't.

Regardless of this, the workaround in the original issue also helps with v1.10.0.

**Comment by Thomas-Gelf** [comment]
Update: packages for v1.10.1 are already there
