### ISSUE TITLE
[dev.icinga.com #11886] Implement changing the order of modifiers

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#263]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11886

**Created by tobiasvdk on 2016-06-02 17:22:07 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-10-11 20:01:26 +00:00 (in Redmine)_

---

If you need to apply multiple modifiers on one attribute and the order in which they get applied is important you need change the order of the modifiers. Please implement some kind of buttons to change the order, e.g. as it is for sorting templates. [Draft]()
![sort_modifier_list.png](https://dev.icinga.com/attachments/download/3410/sort_modifier_list.png)

**Attachments**

* [sort_modifier_list.png](https://dev.icinga.com/attachments/download/3410/sort_modifier_list.png) tobiasvdk - _2016-06-02 17:21:27 +00:00_
* [0001-Sort-sync-properties-in-ascending-order.patch](https://dev.icinga.com/attachments/download/3680/0001-Sort-sync-properties-in-ascending-order.patch) tobiasvdk - _2016-10-11 20:01:23 +00:00_

**Comment by Thomas-Gelf** [comment]
Hey, one more related issue :laughing: - has been implemented
