### ISSUE TITLE
Include contrib folder in Icinga2 deb Packages

### ISSUE THREAD

**Issue by johannesst** [Icinga/icingaweb2-module-director#2639]
## Expected Behavior
The contrib folder is included thus agent tab inside director works.

## Current Behavior
 I updated Icinga2, icingaweb2 and it's modules to the latest version.  I used the new director packages for the first time.
Alas afterwards I got following error in director:
![image](https://user-images.githubusercontent.com/965038/196928451-9898266f-80f6-4169-b2d7-321ff7de10bd.png)

## Possible Solution
I downloaded the release file from github and extracted the contrib folder from it. After putting it in my director install path the agent tab is working again:
![image](https://user-images.githubusercontent.com/965038/196929747-c83397ea-34a7-4f45-bdfb-d2f7353491b0.png)

Thus I propose to add an extra debian package icinga-director-contrib with the contrib folder and add it to the "recommended packages" in the debian control file.

## Steps to Reproduce (for bugs)
Install the debian packages in Ubuntu 

## Your Environment

* Director version (System - About): 1.10.1
* Icinga Web 2 version and modules (System - About):  Icinga Web 2 Version | 2.11.1
* Icinga 2 version (`icinga2 --version`): r2.13.5-1
* Operating System and version: "Ubuntu 22.04.1 LTS"
* Webserver, PHP versions: apache2 2.4.52-1ubuntu4.1 PHP 8.1.2

**Comment by lippserd** [comment]
Hi,

Thanks for the report. We'll just add the `contrib` folder to the deb packages. RPMs already have it.

All the best,
Eric

**Comment by lippserd** [comment]
Fixed with packages for version 1.10.2.
