### ISSUE TITLE
[dev.icinga.com #11888] Improve "Inspect" functionality

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#264]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11888

**Created by geotek on 2016-06-03 07:05:46 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-06-03 08:32:43 +00:00 (in Redmine)_

---

In the first line of the "inspect" window I would like to **see the complete parsed check command with all it's parameters** so that it can be cut and pasted into a linux command line session. This would not only help debugging check commands and trying out parameter modifications, it would also allow for a quick check which parameters are actually passed to the check command without the need to scroll down.

One might even get a step further and add a html link to the check line that opens a popup window that allows to interactively modify the check command and execute it. Of course this would cause security issues because it is not desirable to allow execution of arbitratry linux commands in the GUI without proper authentification.

**Comment by Meinen** [comment]
+1

**Comment by friesoft** [comment]
Having the full command with all arguments just for copy and pasting would be amazing! Atm we use the inspect feature every time we need the exact command and then reconstruct the command from the provided array. This would be a huge timesaver and probably shouldn't be hidden behind an inspect button.

**Comment by Meinen** [comment]
Currently we are migrating to Icinga2. So every time there is a check running into an unknown error we have to reconstruct what Icinga2 is doing. But hiding it behind an inspect button, only accessible by permited users, the way it is handled now, is very much preferable since a lot of checks use secrets or passwords which not every DAU needs to know and if replaced by * showing the command is pretty pointless :P.

**Comment by Thomas-Gelf** [comment]
First draft:

![director-inspect_preview](https://user-images.githubusercontent.com/553008/35269452-55a1a73c-002c-11e8-9b0a-f887a5acc250.png)

* **Source Location** either names your local Icinga configuration file and the line where the given object begins - or directly links you to the configuration rendered by the Director at the time being, even if other deployment attempts occurred in the meantime
* **Last Check Result** can be used to copy and paste the command
* A hint explaining to switch to the Icinga user first should be added
* Related objects like Commands, Groups and similar should link to the related object inspection
* The Endpoint used for inspection (and it's url) are shown, you can jump there

I hope for now this should suffice, or does anyone have more related suggestions? State-related information could also be presented in a nice way, but I'd prefer to handle that in a separate feature request, as this could easily become pretty complex.

Cheers,
Thomas

**Comment by friesoft** [comment]
That looks really nice! :) 👍Perfectly useable for us.
