### ISSUE TITLE
Basket snapshots doesn't work after upgrade to 1.10.x

### ISSUE THREAD

**Issue by stevie-sy** [Icinga/icingaweb2-module-director#2644]
Since upgrading to 1.10.x creating snapshots with the basket doesn't work anymore. It doesn't matter in the UI or with the CLI. 

Error in the UI:
![image](https://user-images.githubusercontent.com/38723488/197534421-02aa477f-ff1c-40a0-9b57-bbbe3ae2fb5f.png)

error running the CLI:
ERROR: Icinga\Module\Director\Exception\JsonEncodeException in /usr/share/icingaweb2/modules/director/library/Director/Exception/JsonException.php:12 with message: Malformed UTF-8 characters, possibly incorrectly encoded

## Your Environment
* Director version (System - About):
* Icinga Web 2 version and modules (System - About): 2.11.1
* Icinga 2 version (`icinga2 --version`): 2.13.5
* Operating System and version: CentOS 7
* Webserver, PHP versions: Apache, rh-php 7.3

**Comment by Thomas-Gelf** [comment]
I'm unable to reproduce this, tried to snapshot a couple of baskets, works fine over here. Could you please create your snapshot on CLI with `--trace`? Blind guess: some object type manages it to ship a binary UUID where it shouldn't

**Comment by Thomas-Gelf** [comment]
What kind of objects do you have in your basket? I'm able to reproduce this, when I add "Basket Definitions" to my basket. Is this the case for your setup? And if so, could you please test whether the error disappears, when you remove them from the basket?

**Comment by Thomas-Gelf** [comment]
NB: as the error message is not very helpful, when tracking down such errors, I pushed a related improvement with #2646. The error would now look as follows:

![image](https://user-images.githubusercontent.com/553008/197728820-dd20f1af-9023-4423-bc5f-a275688dd55a.png)

**Comment by Thomas-Gelf** [comment]
Issue has been fixed and cherry-picked to support/1.10, will be released with v1.10.2. This should have affected only Baskets containing Baskets. As a workaround, remove Baskets from your Basket. As a quick-fix, please apply this little [patch](470137b).

Thanks for reporting this!

**Comment by stevie-sy** [comment]
Hi Tom, 

do you need any further information or can I see this as fixed. You wrote in short time so many comments. :-)

**Comment by Thomas-Gelf** [comment]
Hi @stevie-sy,

I'm pretty confident to have caught the root cause of this issue. Did your basket contain Basket definitions? You could apply the patch if you want, and let me know, whether it helped to fix your problem - it's just a single line.

In case similar problems occurs again, v1.10.2 will provide better error handling, being able to show more related details.

Cheers,
Thomas

**Comment by stevie-sy** [comment]
Here are are some screenshots of the basket defination to backup the director config as json beside a db-backup:
![image](https://user-images.githubusercontent.com/38723488/197737271-c6f6cb21-bb27-468f-a1a7-d720f51d83e5.png)
![image](https://user-images.githubusercontent.com/38723488/197737357-ff68d72d-2f4e-46f9-a430-706a437e0528.png)
![image](https://user-images.githubusercontent.com/38723488/197737356-2a81d24d-faca-41e7-bc9c-8a4c0c58526f.png)

and the line from our backup script:
```
/usr/bin/icingacli director basket snapshot --name "$basket" > /dev/null
/usr/bin/icingacli director basket dump --name "$basket" >  $TARGETDIR/$NOW\-director.json
```



With the one liner patch it work like before and expected. Thank you

**Comment by Thomas-Gelf** [comment]
Thanks for testing and letting me know!
