### ISSUE TITLE
Changeing "Cluster Zone" on host template is not reflected correctly in History/Activity log

### ISSUE THREAD

**Issue by log1-c** [Icinga/icingaweb2-module-director#2651]
## Expected Behavior

All changes to host templates are reflected in the history correctly

## Current Behavior

Currently removing the "Cluster Zone" config option in the host template (setting it to "nothing") isn't shown in the history.
![image](https://user-images.githubusercontent.com/24474580/199947169-a139d3b4-573f-4c89-8331-4a314a3826bf.png)

adding the Zone attribute again is shown though:
![image](https://user-images.githubusercontent.com/24474580/199947552-e827e6c9-54ee-4c96-acfd-4ecee2f5a7e3.png)

and removing it once more shows nothing again:
![image](https://user-images.githubusercontent.com/24474580/199947994-da6ac8b3-e9bd-45df-8ac6-d20bc48d9918.png)

I haven't done any other changes to the template except the zone option.
## Your Environment

* Director version (System - About): 1.9.1
* Icinga Web 2 version and modules (System - About): 2.9.5
* Icinga 2 version (`icinga2 --version`): 2.13.2
* Operating System and version: rhel8
* Webserver, PHP versions: php 7.2.24

**Comment by log1-c** [comment]
Another problem this creates:
When deleting a template that has the Zone attribute configured the restore function of the Director also does not set this attribute, thus you have to set it manually yourself.

setting the zone:
![image](https://user-images.githubusercontent.com/24474580/200339440-36d3d919-7b5b-41d1-b9b2-d22cdcb3d8ec.png)

deleting the template:
![image](https://user-images.githubusercontent.com/24474580/200339515-9f83872c-6b17-4189-98c7-406cff14f51a.png)

restoring the template
![image](https://user-images.githubusercontent.com/24474580/200339556-e6da5a5a-c0be-4b62-abc0-25cb3bc0c451.png)

**Comment by Thomas-Gelf** [comment]
Hi @log1-c,

what version are you running?

**Comment by log1-c** [comment]
Hi @Thomas-Gelf 
Director v1.9.1 (873022caa17bca0e613db460e62f488899084728) on Icinga Web 2 Version 2.9.5 with PHP Version 7.2.24

**Comment by Thomas-Gelf** [comment]
This sounds like the issue in #2559, which has been introduced with v1.9 and fixed with v1.10. Could you please test whether 1.10.2 fixes your issue?

**Comment by log1-c** [comment]
Yes, v1.10.2 fixes this.
Thanks!
