### ISSUE TITLE
Sync rule: update policy "ignore" removes undefined properties

### ISSUE THREAD

**Issue by idandr** [Icinga/icingaweb2-module-director#2657]
## Expected Behavior
With update policy "ignore", updates for the same host should be ignored.

## Current Behavior
After an update from director 1.9.1 to 1.10.2 updates of host values (here: "address" not defined) are not ignored with update policy "ignore".

## Possible Solution
May be a side effect of #2623, that fixes "merge" but effects "ignore"?

## Steps to Reproduce (for bugs)
Have some newly undefined values in an existing hosts import. Set sync update policy to "ignore". Have a look at the sync preview - variables with undefined values would be removed.
![image](https://user-images.githubusercontent.com/38357406/201349906-44c11ca1-18cc-42e6-86e7-863510b08e7f.png)

## Your Environment
* Director version (System - About): 1.10.2
* Icinga Web 2 version (System - About): 2.11.2

**Comment by Thomas-Gelf** [comment]
Note for myself -> branch fix/setting-null-with-merge
