### ISSUE TITLE
assign where with operator contains and a "&" in value fails

### ISSUE THREAD

**Issue by tbauriedel** [Icinga/icingaweb2-module-director#2667]
When using the operator "contains" of an assign where statement, the use of the "&" character within the value is not possible.

Following error occurs:
```
array_key_exists(): The first argument should be either a string or an integer (IcingaObject.php:184)
```

## Your Environment
* Director version (System - About): 1.10.2
* Icinga Web 2 version and modules (System - About): 2.11.2

**Comment by tbauriedel** [comment]
ref/NC/761642

**Comment by mrc-rpprcht** [comment]
ref/NC/770144

**Comment by Thomas-Gelf** [comment]
Hint: same goes true for `|`
