### ISSUE TITLE
Parent Service in new dependency apply rule leads to error message

### ISSUE THREAD

**Issue by mwaldmueller** [Icinga/icingaweb2-module-director#2669]
## Current Behavior
When adding new dependencies any entry in "Parent Service" leads to error message: **Unable to resolve related property: "parent_service_id" (IcingaDependency.php:592)**

![depdendency](https://user-images.githubusercontent.com/3973350/204231869-d528cfdd-c90f-46ab-85e5-3a7f52fa2f08.png)

## Your Environment

* Director version (System - About): 1.10.2
* Icinga Web 2 version and modules (System - About): 2.11.2
* Icinga 2 version (`icinga2 --version`): 2.13.6
* Operating System and version: CentOS 7
* Webserver, PHP versions: Apache, PHP 7.3.33

**Comment by Thomas-Gelf** [comment]
Can be reproduced. This occurs only for a rare case: depending on a single service on a single host. Applied Service dependencies usually leave the "Host" field unfilled, that way they always match the very same Host. That's why this didn't happen in other setups.

**Comment by Thomas-Gelf** [comment]
@mwaldmueller: should now have been fixes. It would be great if you could give the fix a try in your environment, as this was tricky to reproduce - it happens only if some rare conditions match.

**Comment by mwaldmueller** [comment]
It works reliable for new dependencies. But I have troubles with existing dependencies:
* Set new Parent Service: 2x clicks on "Store" needed to save
* Change existing Parent Service: 2x clicks on "Store" needed to save
* Delete existing Parent Service: 2x clicks on "Store" needed to save, but last entry remains (e.g. in the Preview)
