### ISSUE TITLE
Duplicate Service Set on Clone Service

### ISSUE THREAD

**Issue by lucafwp** [Icinga/icingaweb2-module-director#2671]
## Expected Behavior
When cloning a Service from a Service Set I would like to choose the target Service Set from a clean list of unique names.

## Current Behavior
The proposed target Service Sets list contains duplicated names. This is happens if a Service Set is already attached to one or more hosts. You will therefore see one Service Set name for each host where it is applied plus the Service Set template.

## Steps to Reproduce (for bugs)
- Create host "HostTest1"
- Create host "HostTest2"
- Create Service Set "SStest1" 
- Create Service Set "SStest2" 
- Create Service "Service1"
- Create Service "Service2"
- Add "Service1" and "Service2" to Service Set "SStest1" 
- Add Service Set "SStest1" to host "HostTest1" and host "HostTest2"
- Clone "Service1" from Service Set "SStest1" 
- You will see a list of target service sets with "SStest1" repeated 3 times

## Your Environment

* Director version (System - About): 1.10.1
* Icinga Web 2 version and modules (System - About): 2.11.1
* Icinga 2 version (`icinga2 --version`): 2.12.3
* Operating System and version: CentOS 7
* Webserver, PHP versions: 7.3.33

**Comment by Thomas-Gelf** [comment]
@moreamazingnick: merged, thank you!
