### ISSUE TITLE
Sort Host and Service templates in tree view alphabetical

### ISSUE THREAD

**Issue by mwaldmueller** [Icinga/icingaweb2-module-director#2691]
## Expected Behavior
Host and Services templates in tree view should be sorted alphabetical

## Current Behavior
Host and Services templates in tree view are sorted randomly (by ID?)

## Your Environment

* Director version (System - About): v1.10.2
* Icinga Web 2 version and modules (System - About): 2.11.3
* Icinga 2 version (`icinga2 --version`): 2.13.6
* Operating System and version: RHEL 8
* Webserver, PHP versions: Apache

**Comment by Thomas-Gelf** [comment]
Thanks for reporting this, has been implemented. SHOULD have no side-effects ;-)
