### ISSUE TITLE
Get PHP error all the time in Icinga Director Deplyments

### ISSUE THREAD

**Issue by github6043** [Icinga/icingaweb2-module-director#2694]
Hi all, after deploying changes in Director, I get the following error all the time (since around 2 Months)

Jan 04 11:17:22 advsrmon122 icingadirector[888]: PHP Deprecated:  Using ${var} in strings is deprecated, use {$var} instead in /usr/share/icingaweb2/modules/director/library/Director>
Jan 04 11:17:22 advsrmon122 icingadirector[888]: Deprecated: Using ${var} in strings is deprecated, use {$var} instead in /usr/share/icingaweb2/modules/director/library/Director/Reso>
Jan 04 11:17:22 advsrmon122 icingadirector[888]: PHP Deprecated:  Using ${var} in strings is deprecated, use {$var} instead in /usr/share/icingaweb2/modules/director/library/Director>
Jan 04 11:17:22 advsrmon122 icingadirector[888]: Deprecated: Using ${var} in strings is deprecated, use {$var} instead in /usr/share/icingaweb2/modules/director/library/Director/Reso>
Jan 04 11:17:22 advsrmon122 icingadirector[888]: PHP Deprecated:  Using ${var} in strings is deprecated, use {$var} instead in /usr/share/icingaweb2/modules/director/library/Director>
Jan 04 11:17:22 advsrmon122 icingadirector[888]: Deprecated: Using ${var} in strings is deprecated, use {$var} instead in /usr/share/icingaweb2/modules/director/library/Director/Reso>
Jan 04 11:17:22 advsrmon122 icingadirector[888]: PHP Deprecated:  Using ${var} in strings is deprecated, use {$var} instead in /usr/share/icingaweb2/modules/director/library/Director>
Jan 04 11:17:22 advsrmon122 icingadirector[888]: Deprecated: Using ${var} in strings is deprecated, use {$var} instead in /usr/share/icingaweb2/modules/director/library/Director/Reso>

I use 

![image](https://user-images.githubusercontent.com/40850921/210559496-84c99f9e-498e-4de8-9f73-f621b4fdf62c.png)

**Comment by jwilliams-shadowsoft** [comment]
Although the message is annoying, and the string interpolation should be fixed in the Director code, that form of string interpolation is still supported through PHP 8. It will become an exception in PHP 9, so the code has to be fixed before then.

The message is a warning and the code is still working correctly. It's not immediately clear to me how many times this construct is used in the existing PHP code, but the maintainers need to have a plan to update these references before they support PHP 9.

Here's the article that I found that explains the situation: [PHP.Watch: ${var} string interpolation deprecated](https://php.watch/versions/8.2/$%7Bvar%7D-string-interpolation-deprecated)

Hope that helps!

**Comment by github6043** [comment]
Ok, but when I switch to PHP 8.2 Icinga stops running
Deprecated: Creation of dynamic property Icinga\Application\Modules\Module::$configdir is deprecated in /usr/share/php/Icinga/Application/Modules/Module.php on line 264

Deprecated: Creation of dynamic property Icinga\Application\Modules\Module::$configdir is deprecated in /usr/share/php/Icinga/Application/Modules/Module.php on line 264

Deprecated: Creation of dynamic property Icinga\Application\Modules\Module::$configdir is deprecated in /usr/share/php/Icinga/Application/Modules/Module.php on line 264

Deprecated: Creation of dynamic property Icinga\Application\Modules\Module::$configdir is deprecated in /usr/share/php/Icinga/Application/Modules/Module.php on line 264

Deprecated: Creation of dynamic property Icinga\Application\Modules\Module::$configdir is deprecated in /usr/share/php/Icinga/Application/Modules/Module.php on line 264

Deprecated: Creation of dynamic property Icinga\Application\Modules\Module::$configdir is deprecated in /usr/share/php/Icinga/Application/Modules/Module.php on line 264

Deprecated: Creation of dynamic property Icinga\Application\Modules\Module::$configdir is deprecated in /usr/share/php/Icinga/Application/Modules/Module.php on line 264

Deprecated: Creation of dynamic property Icinga\Application\Modules\Module::$configdir is deprecated in /usr/share/php/Icinga/Application/Modules/Module.php on line 264

Deprecated: Creation of dynamic property Icinga\Application\Modules\Module::$configdir is deprecated in /usr/share/php/Icinga/Application/Modules/Module.php on line 264

Fatal error: Uncaught Error: Class "Locale" not found in /usr/share/icinga-php/ipl/vendor/ipl/i18n/src/Locale.php:122 Stack trace: #0 /usr/share/icinga-php/ipl/vendor/ipl/i18n/src/Locale.php(87): ipl\I18n\Locale->parseLocale() #1 /usr/share/php/Icinga/Application/Web.php(500): ipl\I18n\Locale->getPreferred() #2 /usr/share/php/Icinga/Application/ApplicationBootstrap.php(719): Icinga\Application\Web->detectLocale() #3 /usr/share/php/Icinga/Application/Web.php(103): Icinga\Application\ApplicationBootstrap->setupInternationalization() #4 /usr/share/php/Icinga/Application/ApplicationBootstrap.php(416): Icinga\Application\Web->bootstrap() #5 /usr/share/php/Icinga/Application/webrouter.php(105): Icinga\Application\ApplicationBootstrap::start() #6 /usr/share/icingaweb2/public/index.php(4): require_once('...') #7 {main} thrown in /usr/share/icinga-php/ipl/vendor/ipl/i18n/src/Locale.php on line 122

**Comment by github6043** [comment]
And now, "synchronisation" Director and Icinga stopped  working. Deleting a Service or Host and deploy results in Service / Host not visible in Director but remains in Icinga as Host / Service

**Comment by github6043** [comment]
![image](https://user-images.githubusercontent.com/40850921/211566961-5ec1c92c-84b9-4525-8fe1-904dca3cc963.png)

**Comment by jwilliams-shadowsoft** [comment]
@github6043 I kind of doubt that the "locale" processing code that you got the stacktrace from has anything to do with the deprecation. 

@Thomas-Gelf This may be one for you.

Also, @github6043 -- what locale are you using? The stacktrace shows that it was unable to parse something having to do with that.

**Comment by Thomas-Gelf** [comment]
@jwilliams-shadowsoft: there will be support for PHP 8.2 in Director v1.11.0

@github6043: as @jwilliams-shadowsoft pointed out, your errors are not related to the Icinga Director. The warnings appear, because also Icinga Web itself does not (yet) support PHP v8.2. AFAIK, this is already being worked on. Your fatal error happens because you probably didn't install the required dependency `php-intl`.

**Comment by github6043** [comment]
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
