### ISSUE TITLE
Configuration Branch: Error when checking for changes after an Import

### ISSUE THREAD

**Issue by bobapple** [Icinga/icingaweb2-module-director#2711]
## Initial Situation
User is within an active configuration branch and runs an Import and Sync. After clicking "Check for Changes" 

## Error
Hitting "Check for Changes" leads to an SQL Exception. I attached a screenshot.

## Screenshot
![image001](https://user-images.githubusercontent.com/1497070/220869813-45f5eff2-a463-4931-8546-9f8c764b103d.png)

## References
ref/NC/743288

**Comment by Thomas-Gelf** [comment]
I haven't been able to reproduce this on a test system. That binary property might look weird, but should be safe. I slightly modified the code to enforce a hex-based replacement before passing our data to the DB abstraction layer. Could you please give this patch a try:

```patch
--- a/library/Director/Db/Branch/BranchStore.php
+++ b/library/Director/Db/Branch/BranchStore.php
@@ -56,6 +56,7 @@ class BranchStore
                 $rows = $db->fetchAll($db->select()->from($table)->where('branch_uuid = ?', $oldQuotedUuid));
                 foreach ($rows as $row) {
                     $modified = (array)$row;
+                    $this->quoteBinaryProperties($modified);
                     $modified['branch_uuid'] = $quotedUuid;
                     if ($table === self::TABLE_ACTIVITY) {
                         $modified['timestamp_ns'] = round($modified['timestamp_ns'] / 1000000);
@@ -68,6 +69,21 @@ class BranchStore
         return $this->fetchBranchByName($newName);
     }
 
+    protected function quoteBinaryProperties(&$properties)
+    {
+        foreach ($properties as $key => $value) {
+            if ($this->isBinaryColumn($key)) {
+                $properties[$key] = $this->connection->quoteBinary($value);
+            }
+        }
+    }
+
+    protected function isBinaryColumn($key)
+    {
+        return (strpos($key, 'uuid') !== false || strpos($key, 'checksum') !== false)
+            && strpos($key, 'hex') === false;
+    }
+
     protected function runTransaction($callback)
     {
         $db = $this->db;
```

**Comment by Thomas-Gelf** [comment]
Hint: the patch is now to be found in the master branch. Please let me know, whether it resolves your issue. In case it doesn't, please provide some more steps allowing me to reproduce this.

**Comment by bobapple** [comment]
Thanks Tom, will give it a try and get back once I have feedback.

**Comment by bobapple** [comment]
There's another SQL-Exception when clicking "Sync to Branch: XYZ". This could be related to this one:

<img width="85" alt="image001 (1)" src="https://user-images.githubusercontent.com/1497070/221122764-a5cb66d5-6924-4550-97c1-c7d7c5bc6704.png">

<img width="428" alt="image002 (1)" src="https://user-images.githubusercontent.com/1497070/221122704-361c3c97-5c41-430e-9c5a-38dedd846b77.png">

**Comment by Thomas-Gelf** [comment]
> There's another SQL-Exception when clicking "Sync to Branch: XYZ". This could be related to this one:

Does this occur with or without this patch?

**Comment by bobapple** [comment]
Yes, without the patch. We still have to try the patch, you can leave this open until I have further feedback. I just thought I'd forward the additional info just in case.

**Comment by bobapple** [comment]
Same behaviour when testing with the patch. But we have new insights: The problem seems to be related to creating new users. There's a SQL Exception when manually creating a new user within a configuration branch. The affected sync rules also create new users, so it may be the same issue.

This is the exception when creating a new user (within a config branch):
```
QLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '?)' at line 1, query was: SELECT icinga_user_states_set.property, icinga_user_states_set.merge_behaviour FROM icinga_user_states_set WHERE (user_id = ?)

SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '?)' at line 1
```

**Comment by Thomas-Gelf** [comment]
Thanks for testing! Can be reproduced, will be fixed.

**Comment by Thomas-Gelf** [comment]
I pushed an an additional fix, it would be great if you could give it a try

**Comment by bobapple** [comment]
Thanks Tom! I'll give you feedback once I have it.

**Comment by bobapple** [comment]
Works 👍
