### ISSUE TITLE
UI allows data fields to be added and break uniqueness

### ISSUE THREAD

**Issue by R-Sommer** [Icinga/icingaweb2-module-director#2723]
## Expected Behavior
A user shall not be allowed to enter unique field name more than one time.

## Current Behavior
A user can add multiple data fields with the same field name.

## Possible Solution
Add unique key to schema.

## Steps to Reproduce (for bugs)
1. Add new data field with any field name
2. Add new data field with the same field name as in step 1

## Your Environment
* Director version (System - About): 1.10.2
* Icinga Web 2 version and modules (System - About): 2.11.4
* Icinga 2 version (`icinga2 --version`): r2.13.7-1
* Operating System and version: Debian 11
* Webserver, PHP versions: Apache 2.4.54-1~deb11u1, PHP 2:7.4+76

## Additional information
Sometimes new data fields do not appear in the full list. They can be made visible using the search box.

**Comment by Thomas-Gelf** [comment]
Hi @R-Sommer,

it's not a but, it's a feature ;-) Please read [this comment](https://github.com/Icinga/icingaweb2-module-director/issues/2284#issuecomment-797007659) for related details. There are use cases for this, that's why field names are not unique. 

Best,
Thomas

**Comment by R-Sommer** [comment]
Ok, then I was wrong in interpreting the description:
![image](https://user-images.githubusercontent.com/10089355/225242231-c8df17be-fb80-4248-8cd6-163cfc922301.png)

And it looks like there is an other bug since not all entries appear in the full list e.g.:
![image](https://user-images.githubusercontent.com/10089355/225242925-e68fc66f-1e75-4e78-9329-14c3fb46f3a2.png)

But only if I use the search box:
![image](https://user-images.githubusercontent.com/10089355/225243087-a661bc40-14f9-4a6a-b987-b80899979aeb.png)

**Comment by Thomas-Gelf** [comment]
You're not wrong, the description is :-) The list is ordered by field Label, your `x` could to be found on the next page

**Comment by R-Sommer** [comment]
There is no next page:
![image](https://user-images.githubusercontent.com/10089355/225248361-707304f8-b7aa-48b3-9e9d-b5f5c80533b6.png)

**Comment by R-Sommer** [comment]
Hmm, but when I add another one it appears in the full list:
![image](https://user-images.githubusercontent.com/10089355/225249460-0829e4e2-0524-4986-8051-6a85a47f921a.png)

**Comment by Thomas-Gelf** [comment]
> There is no next page: ![image](https://user-images.githubusercontent.com/10089355/225248361-707304f8-b7aa-48b3-9e9d-b5f5c80533b6.png)

Aren't you allowed to click the double-arrow right to the current page number?

**Comment by R-Sommer** [comment]
Ok, I was totally wrong.

**Comment by Thomas-Gelf** [comment]
You weren't, at least you pointed me to that misleading field description. Has been fixed, now it looks as follows:

![grafik](https://user-images.githubusercontent.com/553008/225259041-47949c48-ad0e-4125-ac06-de4bcade1255.png)
