### ISSUE TITLE
Error creating specific service to service dependency via Director

### ISSUE THREAD

**Issue by RafaelSche** [Icinga/icingaweb2-module-director#2731]
## Expected Behavior
I'm trying to create a dependency in the Director . Its equivalent in Icinga Language is:  
```
template Dependency "vault-seal-deb-template" {
    disable_checks = true
    disable_notifications = true
    ignore_soft_states = true
    period = "24x7"
    states = [ OK, Warning ]
}

apply Dependency "vault-seal-dependency" to Service {
    import "vault-seal-deb-template"

    parent_host_name = "vault-bullseye.cs.uni-paderborn.de"
    parent_service_name = "vault-seal"

    assign where service.name == "configs-deployed"
}
```
This works.  
  
## Current Behavior
![Screenshot_2023-04-13_15-57-04](https://user-images.githubusercontent.com/47508551/231782118-4599cb90-bdd7-4ce1-ab17-2a1609b0760c.png)

Error Message in the Screenshot above: "preg_match(): Unknown modifier 'v' (AssignFilterHelper.php:145)"

## Steps to Reproduce (for bugs)

Try to create a Service-to-Service dependency (depend on one specific service on one specific host). See below for System Specification.

## Your Environment

Icinga Web 2 version and modules (System - About):
```$ icingacli --version
Icinga Web 2  2.11.4    
Git Commit    11453bfa92a70a44efbf7f966f5e7f27e9300a28 
PHP Version   7.4.33    
MODULE             VERSION   
[...]
director           1.10.2 
[...]     
icingadb           1.0.2    
[...]
Icinga 2 version (`icinga2 --version`):
```
```
$ icinga2 --version
icinga2 - The Icinga 2 network monitoring daemon (version: r2.13.7-1)
[...]
System information:
  Platform: Debian GNU/Linux
  Platform version: 11 (bullseye)
  Kernel: Linux
  Kernel version: 5.10.0-21-amd64
  Architecture: x86_64

Build information:
  Compiler: GNU 10.2.1
  Build host: runner-hh8q3bz2-project-575-concurrent-0
  OpenSSL version: OpenSSL 1.1.1n  15 Mar 2022
```
Operating System and version:
```  
$ hostnamectl 
[...]
    Virtualization: vmware
    Operating System: Debian GNU/Linux 11 (bullseye)
    Kernel: Linux 5.10.0-21-amd64
    Architecture: x86-64
```
Webserver: apache2; Version: 2.4.56-1~deb11u1
PHP versions: see above
Director version: see above

**Comment by RafaelSche** [comment]
> Please try to replace line 138 in `AssignFilterHelper.php` as follows, and let me know, whether this fixes your issue:
> 
> ```diff
> -                    $parts[] = preg_quote($part, '/');
> +                    $parts[] = preg_quote($part, '/');
> ```

Those lines are identical. But in my version the line was `$parts[] = preg_quote($part);`, so I guess you meant that. I changed it to `$parts[] = preg_quote($part, '/');`. Thanks for that.

You could not reproduce that? So it is a version issue?

**Comment by Thomas-Gelf** [comment]
Thanks for testing and letting me know. It's a bug in all versions, affects only those who have slashes in their Service names. Has now been fixed
