### ISSUE TITLE
Deactivated Service from a Service Set Applied to a Host don't marked as Deactivated

### ISSUE THREAD

**Issue by andickts** [Icinga/icingaweb2-module-director#2746]
## Expected Behavior
Apply a service set to a host through a rule or a host template
Deactivate a service in the service set for a specific host
The service in the services list of the host appears strikethrough

## Current Behavior
The deactivated service in the services list of the host is not strikethrough

## Possible Solution
None

## Steps to Reproduce (for bugs)
As described in the expected behavior
In the earlier director version the behavior was as expected

## Your Environment

* Director version (System - About): 1.10.2
* Icinga Web 2 version and modules (System - About): 2.10.5
* Icinga 2 version (`icinga2 --version`): 2.11.9
* Operating System and version: RedHat 8.7
* Webserver, PHP versions: 7.3.11

**Comment by petulko8080** [comment]
confirm, same [problem (I was about to wrote same bug when found that is already reported)
