### ISSUE TITLE
[dev.icinga.com #11928] Add property modifier for getting the hostname (gethostbyaddr)

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#275]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11928

**Created by tobiasvdk on 2016-06-10 15:01:04 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-10-11 20:02:08 +00:00 (in Redmine)_

---

Add property modifier for getting the hostname from an ip address (gethostbyaddr).

**Attachments**

* [0001-Add-property-modifier-to-get-host-s-FQDN.patch](https://dev.icinga.com/attachments/download/3424/0001-Add-property-modifier-to-get-host-s-FQDN.patch) tobiasvdk - _2016-06-10 15:01:44 +00:00_
* [0001-Add-property-modifier-to-get-host-s-FQDN.patch](https://dev.icinga.com/attachments/download/3520/0001-Add-property-modifier-to-get-host-s-FQDN.patch) tobiasvdk - _2016-07-28 19:19:22 +00:00_
* [0001-Add-property-modifier-to-get-host-s-FQDN.patch](https://dev.icinga.com/attachments/download/3681/0001-Add-property-modifier-to-get-host-s-FQDN.patch) tobiasvdk - _2016-10-11 20:01:58 +00:00_

**Comment by RincewindsHat** [comment]
Looks like this functionality was implemented at some point. @Thomas-Gelf close?

**Comment by Thomas-Gelf** [comment]
The proposed patch does a little bit more than just gethostbyaddr, the topic is tricky. However, a simple GetHostByAddr (#2210) has since been implemented, and there is also **Get DNS records of a specific type** - so this should be covered. Closing the issue. In case anything is missing, please let me know
