### ISSUE TITLE
Styling broken when cloning an Import Source

### ISSUE THREAD

**Issue by bobapple** [Icinga/icingaweb2-module-director#2760]
## Expected Behavior
Default dark theme should work with all forms of Icinga Director.

## Current Behavior
When cloning an Import Source the input field is white with a white font.

![Screenshot 2023-06-01 at 10 06 04](https://github.com/Icinga/icingaweb2-module-director/assets/1497070/7cb56367-a88d-4dd5-aa45-25e0dbc992f0)

## Steps to Reproduce (for bugs)
Clone an existing Import Soruce

## Your Environment

* Director version (System - About): v1.10.2
* Icinga Web 2 version and modules (System - About): v2.11.4

**Comment by Thomas-Gelf** [comment]
Hi @bobapple,

thanks for reporting this! I'll close it for being a duplicate, this has been fixed with 7d5d5b3 for #2670.

Cheers,
Thomas
