### ISSUE TITLE
Timeperiods use wrong time for jobs

### ISSUE THREAD

**Issue by Nayakum** [Icinga/icingaweb2-module-director#2762]
## Expected Behavior
If I add a job in Automation --> Jobs and tell it to run during a predefined timeperiod, I expect the job to run during the given period (and conforming to its run interval).

## Current Behavior
The job recognises the timeperiod, but applies a delay to it. In our case, it applies the timeperiod two hours later than what is defined in the timeperiod. This affects both the starting point as well as the ending point, so a timeperiod defined as 05:00 - 06:00 actually works between 07:00 - 08:00.
First, I suspected a timezone setting, but the time settings are correct for the server the director is running on. Also, time frames configured in other places seem to be working as intended. For example, we have scheduled downtimes which only activate at specific times in the week, and they are applied as expected.

## Possible Solution
No idea, sadly. A workaround is to move the timeperiod around, but that doesn't solve the issue. And since I don't know what the cause is, I don't know when that might change so I need to reconfigure the timeperiod.

## Steps to Reproduce (for bugs)
1. Create a timeperiod in Director --> Timeperiods
2. Go to Automation --> Jobs & create a new job. applying the newly created timeperiod to it
3. Check wether the job is actually running during the timeperiod.

At the time of creating these screenshots, it was 11:38 - 11:40 AM on Tuesday.

![grafik](https://github.com/Icinga/icingaweb2-module-director/assets/84782250/722329b0-26c6-490e-8ec6-3814c7c6fdc9)

![grafik](https://github.com/Icinga/icingaweb2-module-director/assets/84782250/ff2ec986-1f4b-4e87-92ed-41b2ac9b6c29)

![grafik](https://github.com/Icinga/icingaweb2-module-director/assets/84782250/ae734c2b-875e-479b-bc48-778cd596d4a4)

## Your Environment
![grafik](https://github.com/Icinga/icingaweb2-module-director/assets/84782250/98d3df5f-731c-4026-b601-534e54d8a211)

Director is running on SLES 15 SP4

## Additional information
I also already raised an issue via email at Netways.

**Comment by Wintermute2k6** [comment]
ref/NC/785659
