### ISSUE TITLE
Can't edit multiple services with same name

### ISSUE THREAD

**Issue by lucafwp** [Icinga/icingaweb2-module-director#2798]
## Expected Behavior

As a user I would like to change some custom properties on a service on multiple hosts.

## Current Behavior

At the moment, if you go to "Icinga Director >> Services >> Single Services" and select multiple services with the same name, only one service is actually selected:
![image](https://github.com/Icinga/icingaweb2-module-director/assets/36190810/62a385dc-3962-48c2-a83c-e16577dd8b77)

## Steps to Reproduce (for bugs)

- Create 2 hosts: host1, host2
- Create a service: service_test
- Add service_test on both hosts
- Go to "Icinga Director >> Services >> Single Services"
- Select service_test from the two hosts
- Edit some custom properties

## Your Environment

The issue has been reproduces on icingaweb2 demo: https://icinga.com/demo
* Director version (System - About): 1.9.1
* Icinga Web 2 version and modules (System - About): 2.11.1
* Icinga 2 version (`icinga2 --version`): XX
* Operating System and version: XXX
* Webserver, PHP versions: XXX

**Comment by moreamazingnick** [comment]
#2497 #2599
