### ISSUE TITLE
[dev.icinga.com #11964] Notifications: "interval" ignored

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#281]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11964

**Created by spillerm on 2016-06-17 08:57:09 +00:00**

Assignee: _(none)_
Status: _Closed_  (closed on _2016-06-18 11:14:35 +00:00_)
Target Version: _(none)_
Last Update: _2016-06-18 11:14:35 +00:00 (in Redmine)_

---

Hi,

for notifications, director (yesterday's git clone) says for interval:
"The notification interval (in seconds). This interval is used for active notifications. Defaults to 30 minutes. If set to 0, re-notifications are disabled."

That seems not to be correct; I get notified exactly every 5 minutes and independently of what I put in the "interval" field :)

I defined "check\_interval = 5m" and "retry\_interval = 5m" for my service - these are the only "300s" settings I can find.

Regards,
Marianne

**Comment by odrino14** [comment]
i have a same issue with the interval = 0s
i have a renotification where i shouldn't

**Comment by Thomas-Gelf** [comment]
@odrino14: such a comment (just "me too") with no related details attached to an issue closed a year ago isn't very helpful. Please have a look at the generated config. If that looks wrong to you, please open a dedicated issue explaining what went wrong and how.

In case the config looks correct there is nothing Director could do about this. In that case please try to reproduce this issue with a minimal (eventually hand-written) config and open a related Icinga 2 issue.
