### ISSUE TITLE
Commands with Icinga DSL do not preview, clone or REST GET correctly

### ISSUE THREAD

**Issue by lazyfrosch** [Icinga/icingaweb2-module-director#2814]
## Expected Behavior

I should be able to see the content of a `value`/`set_if`, if it contains Icinga DSL.

This should work for preview, clone, REST GET. I have not tried PUT/POST in API.

## Current Behavior

When an object is cloned, it just contains `/* Icinga 2 does not export DSL function bodies via API */` instead of the DSL.

Currently the preview just prints out the following.

```
object NotificationCommand "something" {
    import "plugin-notification-command"
    command = [ "something" ]
    arguments += {
        "--message" = {{
            /* Icinga 2 does not export DSL function bodies via API */
        }}
    }
}
```

And the API:

```json
{
  "arguments": {
    "--message": {
      "type": "Function",
      "body": "/* Icinga 2 does not export DSL function bodies via API */"
    }
  },
  "command": "/usr/bin/aws sns publish",
  // ...
}
```

Config rendering seems to work fine, so some behavior difference to preview:

```
object NotificationCommand "something" {
    import "plugin-notification-command"
    command = [ "something" ]
    arguments += {
        "--message" = {{
            var host = get_host(notification.host_name)
        var message = {
// ...
```

## Steps to Reproduce (for bugs)

Create a command using Icinga DSL as value in an argument and hit preview.

## Your Environment
* Director version (System - About): 1.10.2
* Icinga Web 2 version and modules (System - About): 2.12.0
* Icinga 2 version (`icinga2 --version`): 2.14.0
* Operating System and version: CentOS 7 (yeah I know)
* Webserver, PHP versions: Apache+fpm PHP 7.3.33

**Comment by Thomas-Gelf** [comment]
Hi @lazyfrosch,

could you please give v1.11 a try? There has been a related fix. It addressed such an issue with baskets, but this could have solved your issue too: #2811

Cheers,
Thomas

**Comment by lazyfrosch** [comment]
Updating to master? Tom Tom Tom... 😆 

9a9799e4914bd01bfc2012ef362d39578b4e85de works for me on my test system: clone, preview, REST GET

fixed in #2811
milestone: v1.12.0

**Comment by Thomas-Gelf** [comment]
@lazyfrosch: master? No, it's in the v1.11 release

**Comment by lazyfrosch** [comment]
My bad... 4 hours ago 🤣
