### ISSUE TITLE
[dev.icinga.com #11971] Postgresql: icingacli housekeeping

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#282]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11971

**Created by Tuxdiver on 2016-06-17 12:16:44 +00:00**

Assignee: _Tuxdiver_
Status: _Feedback_ 
Target Version: _(none)_
Last Update: _2016-12-12 12:39:05 +00:00 (in Redmine)_

---

Git Master 2016-060-17

There is a PostgreSQL bug running icingacli director housekeeing <ANY TASK>:

    # icingacli director  housekeeping  run oldUndeployedConfigs
    ERROR: Zend_Db_Statement_Exception in /usr/share/icingaweb2/library/vendor/Zend/Db/Statement/Pdo.php:225 with message: SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near "c"
    LINE 1: DELETE c.* FROM director_generated_config c LEFT JOIN direct...
                   ^, query was: DELETE c.* FROM director_generated_config c LEFT JOIN director_deployment_log d ON c.checksum = d.config_checksum WHERE d.config_checksum IS NULL   AND ? != LOWER(ENCODE(c.last_activity_checksum, 'hex'))

**Comment by cbnorman** [comment]
im also getting this problem, any updates? not sure if its related but i cant delete input sources, and one of my sync rule cant update hosts it created, so on the next run i have to manually delete all hosts before it allow for the hosts to be recreated

**Comment by kajla** [comment]
Hi,

Same problem here.

Director version: 1.3.1
![kep](https://cloud.githubusercontent.com/assets/5457824/24192502/7c9e0152-0eef-11e7-9f90-d6acc2d23c25.png)
![kep](https://cloud.githubusercontent.com/assets/5457824/24192690/19720172-0ef0-11e7-8804-5b1bcbff136d.png)

Thanks,
Adam

**Comment by takeda** [comment]
This issue is still in the latest version of director and is easily reproducible. I get it every single time I issue `icingacli director housekeeping run ALL` even on freshly installed icinga.

**Comment by takeda** [comment]
I know there is a proposed patch that still haven't been merged, but this is my solution (I can create a patch if needed).

```
    public function wipeOldUndeployedConfigs()
    {
        $conn = $this->connection;
        $lastActivity = $conn->getLastActivityChecksum();

        if ($this->connection->getDbType() === 'pgsql') {
        $sql = 'DELETE FROM director_generated_config WHERE checksum IN ('
             . '  SELECT checksum FROM director_generated_config c'
             . '   LEFT JOIN director_deployment_log d ON c.checksum = d.config_checksum'
             . '   WHERE d.config_checksum IS NULL'
             . '   AND ? != ' . $conn->dbHexFunc('c.last_activity_checksum') . ')';
        } else {
        $sql = 'DELETE c.* FROM director_generated_config c'
             . ' LEFT JOIN director_deployment_log d ON c.checksum = d.config_checksum'
             . ' WHERE d.config_checksum IS NULL'
             . '   AND ? != ' . $conn->dbHexFunc('c.last_activity_checksum');
        }

        return $this->db->query($sql, $lastActivity);
    }

```
PostgreSQL does not have the same subquery limitation as MySQL it can reference the same table that is about to delete data from. So I essentially used subquery that is very similar to the count query. This is easier to understand and less prone to mistakes. I'm only giving one example but each task can be easily converted this way.

Should I create a PR with this change?

**Comment by bhozar** [comment]
Any update on this? There has recently been a new Director release (v1.5.1) but the housekeeping for PGSQL is still throwing the error:

Housekeeping (SQLSTATE[42601]: Syntax error: 7 ERROR: syntax error at or near "c" LINE 1: DELETE c.* FROM director_generated_config c LEFT JOIN direct... ^, query was: DELETE c.* FROM director_generated_config c LEFT JOIN director_deployment_log d ON c.checksum = d.config_checksum WHERE d.config_checksum IS NULL AND ? != LOWER(ENCODE(c.last_activity_checksum, 'hex')))

**Comment by TobiasKneidl** [comment]
Same here on Director 1.5.1 and PSQL.

**Comment by Thomas-Gelf** [comment]
Sorry for leaving this orphaned for such a long time, will schedule it for v1.6.0

**Comment by Thomas-Gelf** [comment]
See #12
