### ISSUE TITLE
Problem New custom field in Notification Templates

### ISSUE THREAD

**Issue by lamaratonaug** [Icinga/icingaweb2-module-director#2826]
I have a problem when I try to add a new "custom field" inside a notification templates"

I correctly created a data field categories and added 2 data fields, but when I go to add it to the template notification it gives me an error which I report in the attachment

## Your Environment

* Director version (1.11.0):
* Icinga Web 2 version and modules (2.12.0):
* Icinga 2 version (r2.14.0-1):
* Operating System and version:
* Debian 11.8

![Image 003](https://github.com/Icinga/icingaweb2-module-director/assets/5113761/5ecaffe7-dcdb-4537-b099-21b2d2dbd0fa)

**Comment by timblankman** [comment]
We have also this problem.

**Comment by obivatelj-afk** [comment]
Same Problem here.

Your Environment
Director version 1.11.0
Icinga Web 2 version and modules 2.12.0
Icinga 2 version (r2.14.0-1):
With PHP 8.0.30 and 8.2.12 tested
Operating System and version:
Debian 12.2

**Comment by sol1-matt** [comment]
I upgraded an existing installation to Director v1.11.0 recently and found the same problem with new host, service and notification templates, no data fields are selectable at all. 
On some existing templates I am able to select new data fields for hosts and services. None of the existing notification templates the data fields can select new data fields. 
This installation has 100's of existing datafields and templates that select them. 

On a different installation which was a clean install we found the same problem, no data fields are selectable at all on host, service or notification templates.

Both installations were
Director: 1.11.0
incubator: 0.20.0
icinga-php-thirdparty: 0.12.0
icinga-php-library: 0.13.0

The upgraded installation was PHP 8.2.7
The clean installation was PHP 8.1.x

The exact error message is `There are no data fields available. Please ask an administrator to create such`

The error seems to be coming from [IcingaObjectFieldForm.php](https://github.com/Icinga/icingaweb2-module-director/blob/aa31b37fd184228d3397c512ae8fc175f2d82d39/application/forms/IcingaObjectFieldForm.php#L75).

**Comment by sol1-matt** [comment]
One workaround to this problem is to create a director basket which creates the fields for you. 
I've tested this and it works, it is not a trivial thing to create a basket by hand though.

**Comment by willfurnell** [comment]
@sol1-matt Do you have an example of that please? Unfortunately I am in the same situation here trying to add a custom field to a notification template
![mail-template-host-director-custom-fields](https://github.com/Icinga/icingaweb2-module-director/assets/3112077/61f17305-f8fd-42c8-acc9-b479755ae361)

**Comment by sol1-matt** [comment]
@willfurnell 
You can find some examples of baskets that I've created here (https://gitlab.sol1.net/IC/Icinga-Notifications/-/tree/main/director_baskets).

I'd suggest exporting out an existing template and if the Datafield's are missing add them in. 
Export can have UUID's, I typically remove those and use random id's but that might not be the best approach. 

The above repo also had a generator branch which is still experimental and focused on Notification Templates only so far. 

The [LinuxFab Plugin's](https://github.com/Linuxfabrik/monitoring-plugins) also have baskets and a generator if you need another reference.

**Comment by bobapple** [comment]
ref/IP/48629
