### ISSUE TITLE
[enhancement request] - to be able to comment the changes

### ISSUE THREAD

**Issue by BorisTrnka** [Icinga/icingaweb2-module-director#2833]
Hello, I'd like to suggest/request to add new field "Comment" into each modification form to be able to enter a comment/reason why performing the change. This information should not be stored (optionally it could be) as part of the edited icinga object (host, service, ...), but stored only as part of the "Activity log" entry. 

The intention is to be able to comment the activity to document the reason of change (e.g., to enter request ticket number, etc.) - it could help to remember why it was done latter when reviewing the history. 

Thanks.

**Comment by BorisTrnka** [comment]
Something like:

![image](https://github.com/Icinga/icingaweb2-module-director/assets/80466164/5ae71ffd-badb-4929-8956-d798ef879d84)

![image](https://github.com/Icinga/icingaweb2-module-director/assets/80466164/e6a142f5-2786-4246-b4ae-9c301eb37a13)

**Comment by nilmerg** [comment]
Hi Boris,

this is already possible by using [Icinga Director Branches](https://icinga.com/docs/icinga-director-branches/latest/doc/03-Configuration-Branches/).

There are no plans to add this to Icinga Director.

Best,
Johannes

**Comment by BorisTrnka** [comment]
Hi, thanks for your comment. I will review the functionality of branches module, but let me ask: does it mean each time user changes single threshold (e.g., for CPU check from 90 to 95%) there will be / has to be a new branch?

**Comment by BorisTrnka** [comment]
will do, thanks
