### ISSUE TITLE
Import source: "Set based on filter" cannot be revoked

### ISSUE THREAD

**Issue by tectumopticum** [Icinga/icingaweb2-module-director#2864]
## Expected Behavior
In a Property Modifier of an Import rule a "Set based on filter*"-flag should be stored with its value when set from "Yes" to "No".

## Current Behavior
If you change the flag from "Yes" to "No" and press the save-button, the flag changes back to "Yes".

## Possible Solution
unknown

## Steps to Reproduce (for bugs)
1. select an existing Property Modifier or add a new one (the kind of modifier is not important)
2. make sure that "Set based on filter*" is set to "No"
3. change "Set based on filter*" to "Yes"
4. enter something in the "Filter Expression*"-field (e.g. a=a)
5. klick on the "Store"-button
6. change "Set based on filter*" back to "No"
7. klick on the "Store"-button

The flag changes back to "Yes", the "Filter Expression"-fiel reappears.

## Your Environment
* Director version (System - About): 1.11.0
* Icinga Web 2 version and modules (System - About): 2.12.1
businessprocess 2.4.1
clustergraph   1.0.5
company        1.0.0
cube           1.3.2    
director       1.11.0 
doc            2.12.1  
eventtracker   0.9.0
fileshipper    1.2.0  
grafana        2.0.3  
icingadb       1.1.1  
idoreports     0.10.0
incubator      0.20.0
map            2.0.0    
migrate        2.12.1 
pdfexport      0.10.1
reporting      1.0.1  
vspheredb      1.7.1
x509           1.3.2   
* Icinga 2 version (`icinga2 --version`): 2.14.2
* Operating System and version: SLES 15 SP5
* Webserver, PHP versions: Apache/2.4.51, PHP 8.0.30 (cli) (built: Aug 23 2023 12:00:00) ( NTS )

**Comment by lippserd** [comment]
Fixed by #2939
