### ISSUE TITLE
Couldn't find the files of director after installing it in /etc/icingaweb2/modules, i tried using some resources to create config.ini  kickstart.ini myself, but i think there are some other packages not available.

### ISSUE THREAD

**Issue by Alabs12** [Icinga/icingaweb2-module-director#2865]
## Expected Behavior
when i open the front end of icingaweb, i can see the director, but i couldn't deploy the hosts (stay loading). and that's maybe i created the config myself. 
-cat config.ini
[db]
resource = "Director DB"
cat kickstart.ini
[config]
endpoint = icinga-master
username = director
password = "*********"

## Current Behavior
"icingacli module list"
MODULE         VERSION   STATE     DESCRIPTION
director       1.11.0    enabled   Director - Config tool for Icinga 2
doc            2.12.1    enabled   Documentation module
incubator      0.20.0    enabled   Incubator provides bleeding-edge libraries
monitoring     2.12.1    enabled   Icinga monitoring module

"systemctl start icinga-director.service"
Job for icinga-director.service failed because the control process exited with error code.
See "systemctl status icinga-director.service" and "journalctl -xeu icinga-director.service" for details.

"systemctl status icinga-director.service"
● icinga-director.service - Icinga Director - Monitoring Configuration
     Loaded: loaded (/etc/systemd/system/icinga-director.service; enabled; preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Mon 2024-02-05 14:14:00 CET; 22s ago
       Docs: https://icinga.com/docs/director/latest/
    Process: 14685 ExecStart=/usr/bin/icingacli director daemon run (code=exited, status=3)
   Main PID: 14685 (code=exited, status=3)
        CPU: 46ms

"journalctl -xeu icinga-director.service"
░░ Subject: Unit process exited
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░
░░ An ExecStart= process belonging to unit icinga-director.service has exited.
░░
░░ The process' exit code is 'exited' and its exit status is 3.
Feb 05 14:14:30 icinga-VMware-Virtual-Platform systemd[1]: icinga-director.service: Failed with result 'exit-code'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░
░░ The unit icinga-director.service has entered the 'failed' state with result 'exit-code'.
Feb 05 14:14:30 icinga-VMware-Virtual-Platform systemd[1]: Failed to start icinga-director.service - Icinga Director - Monitoring Configuration.

## Possible Solution
the possible solution is to delete what i did myself and find the solution to install the directory directly. and find the packages in modules

## Your Environment
*icinga2 - The Icinga 2 network monitoring daemon (version: r2.14.2-1)

Copyright (c) 2012-2024 Icinga GmbH (https://icinga.com/)
License GPLv2+: GNU GPL version 2 or later <https://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

System information:
  Platform: Ubuntu
  Platform version: 23.04 (Lunar Lobster)
  Kernel: Linux
  Kernel version: 6.2.0-39-generic
  Architecture: x86_64

Build information:
  Compiler: GNU 12.3.0
  Build host: runner-hh8q3bz2-project-575-concurrent-0
  OpenSSL version: OpenSSL 3.0.8 7 Feb 2023

Application information:

General paths:
  Config directory: /etc/icinga2
  Data directory: /var/lib/icinga2
  Log directory: /var/log/icinga2
  Cache directory: /var/cache/icinga2
  Spool directory: /var/spool/icinga2
  Run directory: /run/icinga2

Old paths (deprecated):
  Installation root: /usr
  Sysconf directory: /etc
  Run directory (base): /run
  Local state directory: /var

Internal paths:
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid
* Apache2, PHP 8.1.12 :

**Comment by nilmerg** [comment]
Hi,

please ask such a question in the [community forum](https://community.icinga.com/).

Thank you
