### ISSUE TITLE
Deleting data list cause error when using PostgreSQL as backend

### ISSUE THREAD

**Issue by afeefghannam89** [Icinga/icingaweb2-module-director#2913]
## Current Behavior
![image](https://github.com/user-attachments/assets/40922fe8-92f4-4bc0-a999-dfa0105c88ca)

PostgreSQL is strict and does not do any magic typecasting. SQLServer does typecasting automagically. https://dev.mysql.com/doc/refman/8.4/en/type-conversion.html#:~:text=For%20example%2C%20MySQL%20automatically%20converts,as%20necessary%2C%20and%20vice%20versa.&text=It%20is%20also%20possible%20to,using%20the%20CAST()%20function. 

That is why the Problem does not appear by MySQL users.
## Possible Solution

change this

'l.id = dfs.setting_value',

to this

'CAST(l.id AS text) = dfs.setting_value',

in this file /usr/share/icingaweb2/modules/director/library/Director/Objects/DirectorDatalist.php (line 106):

## Steps to Reproduce (for bugs)
create data list and use it. You should use PostgreSQL as backend. Try to delete the data list, you will get the same error above in the screenshot. 

## Your Environment

* Director version: 1.11.

**Comment by raviks789** [comment]
ref/IP/55374
