### ISSUE TITLE
cant delete filter on import source modifier

### ISSUE THREAD

**Issue by MisterMountain** [Icinga/icingaweb2-module-director#2922]
## Expected Behavior
When clicking "delete" it should actually delete the filter

## Current Behavior
When clicking "delete" the filter does not get deleted

## Steps to Reproduce (for bugs)
Create an filter for a modifier that gets a property from another import source

## Your Environment
* Director version (System - About): 1.11.1
* Icinga Web 2 version and modules (System - About): 2.12.1 (with Netbox Module 3.6.2
* Icinga 2 version (`icinga2 --version`): 2.14.2
* Operating System and version: Debian Linux 12 bookworm
* Webserver, PHP versions: 8.2.20
* 

https://github.com/user-attachments/assets/33016d3e-c49d-43a2-bb00-a1712dc971cf

**Comment by tectumopticum** [comment]
#2864
