### ISSUE TITLE
[dev.icinga.com #11985] Improve Host and Service filters

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#294]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11985

**Created by geotek on 2016-06-18 11:07:00 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-06-18 11:20:49 +00:00 (in Redmine)_

---

Some of the most asked questions when managing objects with Director in production use are:

-   Which hosts have template xxx applied?
-   Which hosts have service yyy applied?
-   What are the hosts that use the shown service?
-   Where is my variable yyy used?

As far as I can see this is not yet possible with the current filter logic.

This is not only a convenience feature, it becomes essential if you can\`t delete an obsolete object because Director tells you it is still being used somewhere but you have no easy way to find out where it is used unless looking into the MySQL database or use CLI commands,

**Comment by Thomas-Gelf** [comment]
v1.4.0 should be able to answer above questions.
