### ISSUE TITLE
[dev.icinga.com #11987] Custom variable assignment in host template is inherited but cannot be overridden by assignment in host

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#296]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11987

**Created by geotek on 2016-06-18 16:12:24 +00:00**

Assignee: _geotek_
Status: _Feedback_ 
Target Version: _(none)_
Last Update: _2016-08-26 14:24:31 +00:00 (in Redmine)_

---

Assume you have numerous host objects that all import one common host template. Assign a variable field to the host object and give it a default value to be used at some check services. If you open the host object you will correctly see the assigned variable field including the inherited value from the template. This works well as it allows to pass certain default values to some underlying service checks without the need to fill in the value field in each and every host.

Now if you want to override the inherited value for a specific host you may enter some other variable value and this will be correctly stored but it will be ignored. The custom variable field section in dashboard still shows the variable value defined at the template level and not the overriding value at the host level. Also, the underlying service check ignores the new host value. With "Inspect" I can see, however, that the host variable is correctly interpreted, but it seems to get lost somewhere on it's way to Icinga.

Tested with newest Director rev. 1cfc5520 and Icinga2 V.2.4.10

I would very much appreciate if this could be solved.

**Comment by Thomas-Gelf** [comment]
Custom Variable Overrides introduced with 1.3.0 should fix this, otherwise please let me know.

**Comment by bargru** [comment]
I'm sorry, but i need to reopen the bug report.

I'm checking multiple servers with Icinga 2 configured as agent. The checks come from the monitoring plugins. I overwrite some of the thresholds values with custom variables. These variables are ignored during the automatic check execution.
![error_icinga](https://user-images.githubusercontent.com/13362393/36151152-83861a20-10c6-11e8-9cfa-b13b06a6c33b.png)

If I execute the check manually (with the button "Check now"), the custom variables are correctly considered.
![no_error_icinga](https://user-images.githubusercontent.com/13362393/36151154-83bdd0aa-10c6-11e8-98cf-aead7a6074f2.png)

The custom variables are displayed correctly in the host view. 
![host_view](https://user-images.githubusercontent.com/13362393/36151153-83a0f566-10c6-11e8-9270-2ec51f7021d5.png)

**Setup:**
Icinga 2 on master: 2.8.1
Icinga 2 on client: 2.8.0
Icinga Web 2: 2.5.1
Director: 1.4.3

The error also occurs under Director 1.3.2 an Icinga 2.7.2
