### ISSUE TITLE
[dev.icinga.com #11997] Generated URLs get cut off after 254 bytes

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#301]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11997

**Created by vavi on 2016-06-21 07:57:05 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-10-04 09:25:17 +00:00 (in Redmine)_

---

I noticed, that URLs, that get generated for links like "Inspect" (select a service on a host &gt; Problem handling &gt; Actions &gt; Inspect) get cut off after 254 bytes URL length. This leads to the following error:

    #0 /usr/share/icingaweb2/modules/director/library/Director/Core/RestApiResponse.php(20): Icinga\Module\Director\Core\RestApiResponse->parseJsonResult('{"error":404.0,...')
    #1 /usr/share/icingaweb2/modules/director/library/Director/Core/RestApiClient.php(193): Icinga\Module\Director\Core\RestApiResponse::fromJsonResult('{"error":404.0,...')
    #2 /usr/share/icingaweb2/modules/director/library/Director/Core/RestApiClient.php(63): Icinga\Module\Director\Core\RestApiClient->curlRequest('get', 'objects/service...', Object(stdClass), false, false)
    #3 /usr/share/icingaweb2/modules/director/library/Director/Core/RestApiClient.php(199): Icinga\Module\Director\Core\RestApiClient->request('get', 'objects/service...', Object(stdClass))
    #4 /usr/share/icingaweb2/modules/director/library/Director/Core/CoreApi.php(65): Icinga\Module\Director\Core\RestApiClient->get('objects/service...', Object(stdClass))
    #5 /usr/share/icingaweb2/modules/director/application/controllers/InspectController.php(76): Icinga\Module\Director\Core\CoreApi->getObject('pc63052!VHost h...', 'services')
    #6 /usr/share/php/Zend/Controller/Action.php(516): Icinga\Module\Director\Controllers\InspectController->objectAction()
    #7 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('objectAction')
    #8 /usr/share/php/Zend/Controller/Front.php(954): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
    #9 /usr/share/php/Icinga/Application/Web.php(384): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
    #10 /usr/share/php/Icinga/Application/webrouter.php(109): Icinga\Application\Web->dispatch()
    #11 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...')
    #12 {main}

</pre>
If I complete the URL manualy in the browsers location bar, the request works out fine.

This happend to me as my service names got longer and longer to be unique :-)

**Comment by lazyfrosch** [comment]
@friesoft said we can close this as they never saw it again.

Most likely an issue with some special char in that long service name. The error is a 404 from Icinga 2's API.
