### ISSUE TITLE
[dev.icinga.com #12009] Group Membership destination field

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#305]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12009

**Created by chrkli193 on 2016-06-22 08:21:28 +00:00**

Assignee: _chrkli193_
Status: _Feedback_ 
Target Version: _(none)_
Last Update: _2016-10-13 14:14:52 +00:00 (in Redmine)_

---

Is it possible to use a source expression instead of a source coloum in the group sync rule or have this as additional field so that I do not have to create seperate group coloum in my import source?

**Comment by Thomas-Gelf** [comment]
Got no feedback, should work fine
