### ISSUE TITLE
[dev.icinga.com #12015] Deleted a custom variable in template but its still there

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#309]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12015

**Created by chrkli193 on 2016-06-22 10:00:13 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-06-22 10:00:13 +00:00 (in Redmine)_

---

I've created a custom variable in director and put this field to a host template. Now I've deleted this variable but I can see it in the preview of director in all hosts and templates which are below this template (tree) also it's deployed to icinga2.
I'm not able to configure this variable

**Comment by Thomas-Gelf** [comment]
When deleting a field you're right now going to be asked whether you want to remove all related variables.
