### ISSUE TITLE
[dev.icinga.com #12055] Custom variables vanish on service apply once not beeing used

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#323]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12055

**Created by cstein on 2016-06-27 21:08:55 +00:00**

Assignee: _(none)_
Status: _Assigned_ 
Target Version: _(none)_
Last Update: _2016-12-06 08:51:19 +00:00 (in Redmine)_

---

Currenty custom variables are removed from service apply rules for example in case they are not assigned on a host.

Example: Import data over sync rules and set custom variables for host objects.

Now generate apply rules for these custom variables after an import.

Now purge the import data and ensure they are gone. Once removed, re-check your service apply rules.

Instead of the custom variable, there will be 'Please choose' instead. Once saving the apply rule, they will be removed from the rule.

---

**Relations**:

* relates [#13227](https://dev.icinga.com/issues/13227)

**Comment by Thomas-Gelf** [comment]
This is no longer an issue with v1.4.0
