### ISSUE TITLE
[dev.icinga.com #12066] Icinga 2 Deployment errors assistant - what needs to be done in Director forms?

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#327]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12066

**Created by mfriedrich on 2016-06-28 14:51:08 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-06-28 15:05:39 +00:00 (in Redmine)_

---

One thing which came to my mind during the talk at Icinga Camp Amsterdam - there was a deployment which contained errors.

Obviously we are much into that stuff that we can read a log and extract the Icinga 2 errors our own. Though it'll be hard for the users to identify a problem - e.g. when a check\_command is missing.

I could imagine that building the bridge from generated configuration with errors to actual Director "knobs" and forms could be tricky sometimes.

I'm not sure if that's possible but maybe the Director could parse the Icinga 2 error, locate the config file and "reverse engineer" which change or form is necessary being changed in order to correct the error. Some sort of "assistant" for deployment errors :-)

In case of questions, poke me ;)

**Comment by Thomas-Gelf** [comment]
What has been implemented so far:

* log will be shortened where too large
* startup log tries to link directly to the related config where possible
* rendered config links back to config forms for simple objects like hosts

The rest of the details (like "check_command missing" should already be shown in the provided log.
