### ISSUE TITLE
[dev.icinga.com #12087] Show usage of Commands over templates and objects

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#335]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12087

**Created by friesoft on 2016-07-03 17:44:02 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-07-03 17:44:02 +00:00 (in Redmine)_

---

It would be nice being able to select a Command or Service/Apply Rule and show
1.) Which services are using the command
2.) To which Hosts the service was added
3.) To which Hosts the Apply Rule of a service applies

Using this information and multiselect like everywhere else in icingaweb2 (missing atm) it would be possible to easily check if a service has been added everywhere needed, can be deleted all at one click (especially important atm as purging Services isn't working).

Would be really nice to see this added :)

---

**Relations**:

* blocks [#12087](https://dev.icinga.com/issues/12087)

**Comment by Thomas-Gelf** [comment]
> purging Services isn't working

This part should have been solved quite some time ago. Code showing template usage, directly and indirectly and more has been pushed to `next`, still needs to be provided for hosts and commands. Currently it's services-only: #895

**Comment by Thomas-Gelf** [comment]
This should look like template usage overviews, and in addition to this I'd love to see #1480 implemented.

**Comment by Thomas-Gelf** [comment]
Here a few screen-shots, showing that this works fine with all kind of Commands (Notification, Event, Check) and even with external commands:

![director_command_unused](https://user-images.githubusercontent.com/553008/39651053-c53bf710-4fea-11e8-89c8-a8b604e298e7.png)

![director_command_used_external](https://user-images.githubusercontent.com/553008/39651061-ca98f276-4fea-11e8-93d0-766015669188.png)

![director_command_used_notification](https://user-images.githubusercontent.com/553008/39651069-ce8e7d42-4fea-11e8-80b8-cec7ceeb0c73.png)
