### ISSUE TITLE
[dev.icinga.com #12095] boolean custom field and assign rules does not work

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#339]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12095

**Created by Tuxdiver on 2016-07-05 09:25:49 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _1.3.1_
Last Update: _2016-11-30 08:37:27 +00:00 (in Redmine)_

---

Using a custom field of type boolean and trying to use this in an apply rule does not work, because director always adds quotes around the value part:

        assign where host.vars.test_boolean == "true"

I think, this should be:

        assign where host.vars.test_boolean == true

Solution: remember the field type while generating the code for the apply rule

**Comment by friesoft** [comment]
Any news? :) Seems to apply everywhere where apply rules are used (notifications, service groups, ...)

**Comment by rajo** [comment]
+1 this would really be helpful if this would work soon

**Comment by widhalmt** [comment]
+1 from I just hit that as well.

**Comment by SimonHoenscheid** [comment]
+1

**Comment by jcromero** [comment]
+1

**Comment by Meinen** [comment]
+1

**Comment by amreuland** [comment]
Any news on this yet?

**Comment by xtruthx** [comment]
+1

**Comment by MaartenUreel** [comment]
+1
still a big issue

**Comment by vita2** [comment]
+1
i need this for assignment rules to check if host notifications are enabled

```
apply Notification "host-mail" to Host {
    import "notification-mail"

    assign where host.enable_notifications == "true"
    user_groups = [ "netadmins" ]
}
```

**Comment by papst01** [comment]
+1

**Comment by kjde** [comment]
+1

**Comment by Foxeronie** [comment]
+1

**Comment by kajla** [comment]
+1

**Comment by wlma** [comment]
+1

**Comment by Hrocc** [comment]
+1

**Comment by itsopensource** [comment]
+1

**Comment by chas0rde** [comment]
+1

**Comment by fireheadman** [comment]
+1

**Comment by fireheadman** [comment]
+1

**Comment by cyberkov** [comment]
+1

**Comment by wols** [comment]
+1

**Comment by vita2** [comment]
hello @Thomas-Gelf,

it would be nice if you could consider a fix for this issue in the upcoming 1.4 release :relaxed:

**Comment by Thomas-Gelf** [comment]
No more likes? I should wait for more of them...




...just kidding :laughing: I hear you!

**Comment by Thomas-Gelf** [comment]
Anyone involved here: could you please let me know whether the implementation for the linked feature request solves your problem? It does not try to "understand" the strings "true" or "false" and it does not do anything for false (you can use a negation for this). But it provides `is true (or set)` as a new virtual operator type, and renders to `where <chosen.property>`. So you can use it for boolean true or also to say `assign where host.address6` (or similar).

Cheers,
Thomas

**Comment by vita2** [comment]
now it is possible to build a assignment rule for notifications which only matches if "enable_notifications" was set. example:
```
zones.d/master/notification_apply.conf

apply Notification "host-1st-pushover" to Host {
    import "template-pushover-host"
    import "template-host-1st"

    assign where host.address && host.enable_notifications
    user_groups = [ "netadmins" ]
}
```

it is also possible to create a service-apply-rule which only hits if a certain custom host variable was set to true. example:
```
zones.d/director-global/service_apply.conf

apply Service "booleantest" {
    import "dummy"

    assign where host.vars.booleantest

    import DirectorOverrideTemplate
}
```

for me, it works as expected now. thank you!

have a nice weekend  :beers::smile:

**Comment by Thomas-Gelf** [comment]
@vita2: who needs a weekend - didn't you notice that I'm on vacation since two weeks? Glad to hear that it works for you!

**Comment by menewol** [comment]
does this only wirk if writing the `service_apply.conf` manually? im trying to match wether a host has an odd ip address with the regex function in the icinga director. my regex "[13579]$" matches for the very last digit in the ipaddress, so if a host has an odd address this should match to true. 

i've attached 2 screenshots...this is either still a problem for the director or i'm doing something terribly wrong. if second please just point it out to me so i'll go on finding the right solution! 
![service_apply](https://user-images.githubusercontent.com/5627394/30161520-32522bd4-93d1-11e7-86ea-b8f5c05441cf.png)
![render_failure](https://user-images.githubusercontent.com/5627394/30161521-3256bd02-93d1-11e7-9527-8440e2d9ffad.PNG)
best regards, wolfgang

**Comment by Foxeronie** [comment]
@menewol You can set the "=" to "is true (or set)" to use this on vars, addresses, etc.
But I dont think you can insert a regex rule in the first field.
I opened a regex feature request already. #435

**Comment by menewol** [comment]
@Foxeronie which version is it you are using? we're running 2.4.1 and theres no "is true (or set)" option. should this assign where rule work if it is set up manually?
