### ISSUE TITLE
[dev.icinga.com #12138] create and modify scheduled downtimes with director

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#347]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12138

**Created by mknodel on 2016-07-12 07:45:59 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _1.3.1_
Last Update: _2016-11-30 09:01:26 +00:00 (in Redmine)_

---

Hi guys,

is it possible to create and modify scheduled downtimes with director?
If not, when this feature will be available?

kind regards,
M. Knodel

**Changesets**

_2016-10-13 08:33:10 +00:00_ by _tgelf_ 3dace133dfce58692f4a0b3324258b5628be791f

    ScheduledDowntime: initial implementation
    
    refs #12138

_2016-10-13 11:48:43 +00:00_ by _tgelf_ e391cf61c294ef74fd60806ea473588bbede71f9

    ScheduledDowntime: initial implementation
    
    refs #12138

_2016-10-13 12:01:49 +00:00_ by _tgelf_ d141e545b160d384941a1502ee83439d7aaafe04

    ScheduledDowntime: initial implementation
    
    refs #12138

_2016-12-30 09:09:07 +00:00_ by _tgelf_ b5bd4e115994404f71a1836885600df31e26b1f7

    ScheduledDowntime: initial implementation
    
    refs #12138

**Comment by Thomas-Gelf** [comment]
Sorry, too late for 1.4.0. Should be easy to implement afterwards.

**Comment by mengine23** [comment]
Would be great to get this in the near future.

**Comment by fireba11** [comment]
Would appreciate that too.

**Comment by swizzly** [comment]
me too

**Comment by bl4kd3th** [comment]
This is a good Icinga2 feature that needs to be implemented in director as well. +1

**Comment by Simkimdm** [comment]
Is it planned for 1.5.0?

**Comment by fireba11** [comment]
I actually managed to use that already, though it's non obvious and will probably not work for all szenarios.
* create a timetable that excludes your scheduled downtime
* make a copy if the host tamplates you use and set your timetable as "check period"

that simply stops checks for the host and all services for your scheduled downtime.
Pro-tip: leave a few minutes wiggle room, checks are not instant and clocks might be slightly off ...

**Comment by mdeguzis** [comment]
Any update on a target release on the roadmap?

**Comment by phil-or** [comment]
Would be great to get this in the next version.

**Comment by d3vsl4sh** [comment]
Any update on this? Seems like it was removed from milestone 1.4.0 but not added to any upcoming. So, this one is untracked and might not get implemented any time soon...

**Comment by TobiasKneidl** [comment]
Any update if we get this in the next version?

**Comment by rangoy** [comment]
I see that there is some work in progress on the branch scheduled-downtimes-12138 [ ref b5bd4e1 ].

Can someone comment on what's blocking this from beeing merged into the master branch? Does @Thomas-Gelf have any comment on the status?

**Comment by Thomas-Gelf** [comment]
I rebased and pushed [feature/scheduled-downtimes-347](https://github.com/Icinga/icingaweb2-module-director/tree/feature/scheduled-downtimes-347) and dropped the other branch, that's the current state of this feature. It's still unfinished and just a matter of time and priorities.

**Comment by Thomas-Gelf** [comment]
v1.5.0 is a little bit late - so why not add more features ;-)

**Comment by Thomas-Gelf** [comment]
Well... nope. Have to postpone this one - sorry.

Reason: it's mostly done, but I didn't want to clone the periods-handling as it exists for the TimePeriod object one more time. It's ugly, I hate it. Soon after v1.5.0 Director will depend on our new `ipl`, the new 'Icinga PHP Library`. It got a lot of code from the Director and will provide a modern web form framework for Icinga Web 2 and all of it's modules. We'll then be able to easily create much more flexible forms.

**Comment by widhalmt** [comment]
From my last meeting, there's a `+1` for this feature.

/ref/NC/567668

**Comment by achmet9948** [comment]
Is the Scheduled Downtime function already active? Or is there already an appointment?
