### ISSUE TITLE
[dev.icinga.com #12145] Value type "constants" in command arguments

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#348]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12145

**Created by ryanrudak on 2016-07-13 08:07:23 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-07-15 16:27:18 +00:00 (in Redmine)_

---

At the momente are available "String" and "Icinga DSL" as value types in the "Arguments" section of a command.
Is it possible to add an other value type? Like global constants (NodeName, PlatformName, PlatformVersion).

Background:
I have a notification command and I would like to use the constant "NodeName" in one of my arguments,
so that I can see which custer endpoint has send that notification.

Now are every value of an argument are inside of quotes, like:
(related argument "-n" = "NodeName" )

        arguments = {
            "-a" = "$address$"
            "-b" = "$notification.author$"
            "-c" = "$notification.comment$"
            "-d" = "$icinga.long_date_time$"
            "-e" = "$service.name$"
            "-l" = "$host.display_name$"
            "-n" = "NodeName"
            "-o" = "$service.output$"
            "-r" = "$user.email$"
            "-s" = "$service.state$"
            "-t" = "$notification.type$"
        }

In that case the constant NodeName is handled as a string, but

        arguments = {
            "-a" = "$address$"
            "-b" = "$notification.author$"
            "-c" = "$notification.comment$"
            "-d" = "$icinga.long_date_time$"
            "-e" = "$service.name$"
            "-l" = "$host.display_name$"
            "-n" = NodeName
            "-o" = "$service.output$"
            "-r" = "$user.email$"
            "-s" = "$service.state$"
            "-t" = "$notification.type$"
        }

if the quotes for the related constant are gone the constant is handled in the right way and I see the cluster endpoint (NodeName) in the notification.

Like:

    ***** Icinga2 Service Monitoring  *****

    Notification Type: PROBLEM

    Service:    Physical Memory Usage - Windows
    Host:       fileserver.prod.local
    Address:    fileserver.prod.local
    State:      WARNING

    Date/Time:  2016-07-12 18:00:04 +0200

    NodeName:   icingacluster_a.prod.local

    Additional Info: Physical Memory: 95%used(3906MB/4096MB) (>95%) : WARNING 

    Comment: [] 

---

**Relations**:

* relates [#12145](https://dev.icinga.com/issues/12145)
* relates [#12145](https://dev.icinga.com/issues/12145)

**Comment by Thomas-Gelf** [comment]
The solution proposed by @mdetrano is the way to go, globals shouldn't even be required for constants:

`return NodeName;`

I'll close this issue, please do not hesitate to re-open it or a new one in case you're still facing related problems.
