### ISSUE TITLE
[dev.icinga.com #12183] Provide sync for existing commands/zones/endpoints out of the box

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#352]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12183

**Created by tgelf on 2016-07-20 09:53:12 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-07-20 09:53:12 +00:00 (in Redmine)_

---

With import/sync definitions one is able to use objects created "manually" in the Icinga 2 configuration. This basically means re-implementing what is already there at kickstart time in a point and click way. As this is somewhat tricky and people often need this for one or the other reason it would be nice to have such rules there out of the box with the following features:

-   it should notify in case there have been local changes, at least before deploying
-   you should be able to run it as a background job
-   it should provide an easy "internalize/externalize this object" mechanism

The last one is for getting rid of manual config, it would of course conflict with a background job re-syncing the existing manual config. This feature should also allow you to survive changes where master or satellite zones and/or endpoints are renamed on your deployment endpoint.

---

**Relations**:

* relates [#12183](https://dev.icinga.com/issues/12183)
* duplicates [#12183](https://dev.icinga.com/issues/12183)

**Comment by Thomas-Gelf** [comment]
Kickstart is now linked from the new Infrastructure Dashboard, there is also some text with related hints. Should suffice for now, more to come.
