### ISSUE TITLE
[dev.icinga.com #12185] Assing multiple hostgroups with a sync rule

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#354]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12185

**Created by psi on 2016-07-20 12:46:40 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-07-20 13:17:40 +00:00 (in Redmine)_

---

I've multiple sync attrs for Hostgroup-Membership but only the first one gets respected.
I would assume all hostgroups gets merged.

**Comment by Thomas-Gelf** [comment]
Syncing multiple hostgroup memberships should work fine, in case it doesn't please re-open this or a new issue with more details explaining how to reproduce this.

Thanks,
Thomas
