### ISSUE TITLE
[dev.icinga.com #12187] Job runner does *nothing*

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#356]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12187

**Created by psi on 2016-07-20 13:16:51 +00:00**

Assignee: _(none)_
Status: _Closed_  (closed on _2016-07-25 09:44:21 +00:00_)
Target Version: _(none)_
Last Update: _2017-01-07 09:57:13 +00:00 (in Redmine)_

---

I've defined some Jobs but if run:

    # icingacli director jobs run --debug                                                                                      
    Director JobRunner is starting "Trigger Sync"
    Director JobRunner is starting "Deploy Config"
    Director JobRunner is starting "Trigger Import"
    # echo $?
    0

The director UI tells me that the job was never executed.

**Comment by mbassett** [comment]
Using a MySQL Aurora DB  Aurora 5.6.10a 

# id, job_name, job_class, disabled, run_interval, timeperiod_id, last_attempt_succeeded, ts_last_attempt, ts_last_error, last_error_message
1, Import EC2 Hosts, Icinga\Module\Director\Job\ImportJob, n, 900, , y, 2017-01-19 01:11:40, 2017-01-06 23:36:45, Failed to load import_source ""
2, Sync DEV, Icinga\Module\Director\Job\SyncJob, n, 900, , y, 2017-01-19 01:17:40, 2017-01-06 23:36:45, Failed to load sync_rule ""
3, Sync QA, Icinga\Module\Director\Job\SyncJob, n, 900, , y, 2017-01-19 01:17:40, 2017-01-06 23:36:45, Failed to load sync_rule ""
4, Sync LT, Icinga\Module\Director\Job\SyncJob, n, 900, , y, 2017-01-19 01:17:44, 2017-01-06 23:36:45, Failed to load sync_rule ""
5, Sync Tools, Icinga\Module\Director\Job\SyncJob, n, 900, , y, 2017-01-19 01:17:45, 2017-01-06 23:36:45, Failed to load sync_rule ""
6, Sync STG, Icinga\Module\Director\Job\SyncJob, n, 900, , y, 2017-01-19 01:17:49, , 
7, Sync Prod, Icinga\Module\Director\Job\SyncJob, n, 900, , y, 2017-01-19 01:17:55, , 



# job_id, setting_name, setting_value
1, run_import, y
1, source_id, 1
2, apply_changes, n
2, rule_id, 1
3, apply_changes, n
3, rule_id, 3
4, apply_changes, n
4, rule_id, 4
5, apply_changes, n
5, rule_id, 2
6, apply_changes, n
6, rule_id, 6
7, apply_changes, n
7, rule_id, 7


# NOW(), UTC_DATE()
'2017-01-19 01:16:02', '2017-01-19'
