### ISSUE TITLE
[dev.icinga.com #12192] Add modifier failure handler "ignore object" on import sources

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#357]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12192

**Created by tobiasvdk on 2016-07-21 06:02:47 +00:00**

Assignee: _tobiasvdk_
Status: _Assigned_ 
Target Version: _(none)_
Last Update: _2016-07-23 08:43:06 +00:00 (in Redmine)_

---

E.g. when using the property modifier "Get host by name" on an import source currently you only have the possibilty to

1.  set no value
2.  keep the property
3.  let the whole import fail

It would be nice to have the failure handler "ignore object" which only ignores this object (where the modifier fails) but goes on to the next in the import run. At the end of the import the list of ignored objects should be visible. The use case I have is that when the appropriate DNS record for one object is missing the whole import fails or I would have an ip address as display name.

**Comment by Thomas-Gelf** [comment]
It is now possible to implement this, modifiers have been allowed to skip rows
