### ISSUE TITLE
[dev.icinga.com #12212] Simpler import or example data

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#361]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12212

**Created by kbr on 2016-07-23 01:00:18 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-07-23 01:00:18 +00:00 (in Redmine)_

---

First of all: great work on the GUI, it is really easy to use and clean!

I'm having problems with getting started with director. I find it quite hard to create the automation rules to import all my already existing services, hosts and hostgroups. I've read through several other issues and the baseline was always: start from scratch. This makes it really hard for newcomers to start using director.

I would love to have the kickstart command include services and hosts. Using the wizard I've already configured several servers and it seems kind of complex to re implement this basic configuration using the Director GUI, for what time effort it was to create the configuration using the wizard.

I know, not all of the information from the configuration files is exposed through the API (like hierarchies) but it would to simply import the basics in order to have example to go by through the GUI.

**Comment by Thomas-Gelf** [comment]
Rejecting this, guess this won't happen anytime soon.
