### ISSUE TITLE
[dev.icinga.com #12230] Service templates names are not uniqe

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#364]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12230

**Created by aledermueller on 2016-07-26 09:56:31 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _1.3.1_
Last Update: _2016-11-30 08:38:06 +00:00 (in Redmine)_

---

The director allows to create service templates with identical names more than once.

Regards, Achim

---

**Relations**:

* relates [#12230](https://dev.icinga.com/issues/12230)
* duplicates [#12230](https://dev.icinga.com/issues/12230)
* duplicates [#12230](https://dev.icinga.com/issues/12230)
* blocks [#12893](https://dev.icinga.com/issues/12893)

**Comment by Thomas-Gelf** [comment]
I consider this being fixed, otherwise please let me know. We did our best to solve this in various places in "user space". In case we opt for dedicated template tables, we could finally introduce DB constraints.
