### ISSUE TITLE
[dev.icinga.com #12232] Template-Tree(s) should be initialized with root templates

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#366]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12232

**Created by jprusch on 2016-07-26 11:46:59 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-07-26 11:46:59 +00:00 (in Redmine)_

---

By now the template tree does not display any entries apart from "Templates" if existing root templates are not inherited by other templates. It would be nice to display these root templates initially below "Templates".

**Comment by Thomas-Gelf** [comment]
Fixed in `next`
