### ISSUE TITLE
[dev.icinga.com #12520] Implement API-version-based behaviour

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#369]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12520

**Created by tgelf on 2016-08-23 16:01:44 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-08-23 16:01:44 +00:00 (in Redmine)_

---

Icinga 2.5 allows to ask for the Icinga 2 version. This should be respected and provided internally in an easy-to-use way. Icinga should not be hammered with requests when this information is requested in a loop or so. Things to consider:

-   we always need to access /v1 first, there is the Core version to be found in v2.5.x, there is no such on 2.4
-   we currently do not care about the core version when rendering the configuration, this might change in the future
-   consider storing the target Core version with the generated config (might make sense anyways as we are also able to render 1.x config)
-   version information should somehow be cached for a short time to avoid useless requests
-   cache should involve the endpoint name as we might talk to different nodes, and it should last for a very short period of time
-   while for the web frontend this information might resist in a session and eventually be dropped after a while, we also have to think of long-running jobs. One might have a running Icinga 2.4.x, upgrade to 2.5.x or later and not restart director-jobs.service as there is no need for doing so

---

**Relations**:

* blocks [#12440](https://dev.icinga.com/issues/12440)
* blocks [#12441](https://dev.icinga.com/issues/12441)

**Comment by Thomas-Gelf** [comment]
Has been implemented and is now possible.
