### ISSUE TITLE
[dev.icinga.com #12238] clone functionality for sync-rules

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#370]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12238

**Created by swizzly on 2016-07-27 06:11:52 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-07-27 06:11:52 +00:00 (in Redmine)_

---

Hi,

It would be nice to have a function to clone sync-rules.

Cheers

**Comment by nbuchwitz** [comment]
Please also provide something for the import sources. Maybe I could help with a PR.

**Comment by Thomas-Gelf** [comment]
@nbuchwitz: sure! I created #1409 which mentions Import, Sync and Jobs. Will close this as being a duplicate, since now a more generic feature request exists.
