### ISSUE TITLE
[dev.icinga.com #12264] Allow to render legacy config

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#378]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12264

**Created by tgelf on 2016-08-01 06:58:15 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-08-01 06:58:15 +00:00 (in Redmine)_

---

Legacy means 1.x in this context. Director should and will not be a config tool for Icinga 1.x. This is a sponsored feature for specific migration needs. It should be publicly available, but it should not be immediately obvious that it is there.

**Changesets**

_2016-08-01 06:59:31 +00:00_ by _tgelf_ 4c978db3d00048fbd0a45e074f205a66a36de6d4

    IcingaConfig: allow to toggle legacy renderer
    
    refs #12264

---

**Relations**:

* relates [#12264](https://dev.icinga.com/issues/12264)

**Comment by Thomas-Gelf** [comment]
Closing this for now, works so far.
