### ISSUE TITLE
[dev.icinga.com #12270] Sync Rules should complain when no Sync Properties have been defined

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#383]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12270

**Created by tgelf on 2016-08-01 09:25:21 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-08-01 09:44:27 +00:00 (in Redmine)_

---

**Comment by Thomas-Gelf** [comment]
Looks like this:

![director_no-sync-without-properties](https://cloud.githubusercontent.com/assets/553008/25654918/46135bc6-2ff3-11e7-9d68-9c5914115a2a.png)

**Comment by Thomas-Gelf** [comment]
Oooops, there is a typo :laughing:

**Comment by Thomas-Gelf** [comment]
Should read like this:

![director_no-sync-without-properties](https://cloud.githubusercontent.com/assets/553008/25654996/9a518bea-2ff3-11e7-80c8-e0f766d060ce.png)
