### ISSUE TITLE
[dev.icinga.com #12291] Unable to filter on attribute that is a variable or use one without setting it

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#386]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12291

**Created by TheFlyingCorpse on 2016-08-02 18:16:18 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-09-02 07:44:20 +00:00 (in Redmine)_

---

    Source A: 
    - objectname = hostname
    - vars.osfamily = ${parameters.vars.osfamily} (based on puppetdb resource)
    - imports PuppetDB-Icinga2Master IF certname=host1|host2
    - imports PuppetDB-Icinga2NodeLinux IF osfamily=a|b
    - imports PuppetDB-Icinga2NodeWindows IF osfamily=c

    Source B:
    - objectname = hostname
    - vars.description = description (ldap attribute)

    Source C:
    - objectname = hostname
    - imports PuppetDB-Icinga2NodeLinux IF osfamily=Linux

Issues:
1) I am not able to use **${parameters.vars.osfamily}=Debian** in the filter
2), I discovered I was unable to not use osfamily from other sources, fair enough.
3) I could not use the existing attribute already synced in, fair enough. Maybe that should be a feature request ;-)
4) When I tried to use the osfamily from Source C, that was now added as a filter, it didn't work until it was also a synced attribute to an attribute, like vars.osfamilyy = Debian as an extra (redundant) rule to make the filter take effect. Is this intended?

**Comment by Thomas-Gelf** [comment]
@TheFlyingCorpse: this is an old one and I'm not sure whether I completely understood the problem. Any idea whether this is still an issue?

**Comment by TheFlyingCorpse** [comment]
I worked around it long ago, not sure if it is still an issue, so close it!
