### ISSUE TITLE
[dev.icinga.com #12292] Do not allow service imports without host names 

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#387]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12292

**Created by TheFlyingCorpse on 2016-08-02 18:19:05 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-08-02 18:19:05 +00:00 (in Redmine)_

---

Do not allow service importing without it either being either a template or external object, or have the host\_name set. It is not possible to rediscover these services without entering the database for removal :)

---

**Relations**:

* relates [#12230](https://dev.icinga.com/issues/12230)

**Comment by Thomas-Gelf** [comment]
@TheFlyingCorpse: it's not yet forbidden, and that would be hard to accomplish. I added some more hints and a new related property modifier with #922. Requiring a host isn't possible as one might also want to synchronize service templates or service set members.
