### ISSUE TITLE
[dev.icinga.com #12308] Do not allow to add a service to a host...

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#390]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12308

**Created by tgelf on 2016-08-03 23:30:37 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-08-03 23:30:37 +00:00 (in Redmine)_

---

...as long as there is not service template available. This currently shows a form with no imports field and results in an exception when storing it.

**Comment by Thomas-Gelf** [comment]
Fixed, a related warning is now shown - and an error in case the user insists and tries to go on anyways
