### ISSUE TITLE
[dev.icinga.com #12315] Changing the name of a timeperiod-range results in adding a new range

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#391]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12315

**Created by InTheWild on 2016-08-04 16:01:24 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-08-04 16:01:24 +00:00 (in Redmine)_

---

Can be reproduced like that:

-   Select a timeperiod
-   Go to the ranges-tab and click on an existing range
-   Change the value of the "Day(s)"-field and hit "Store"
    Now there exists both ranges. The new range also appears in the "Preview"-tab and is also depoyed.

Tested with the official 1.1.0-director.

**Comment by Thomas-Gelf** [comment]
Has been fixed, as renaming ranges is no longer allowed :p
