### ISSUE TITLE
[dev.icinga.com #12440] Fetch the client ticket number from the REST API action

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#401]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12440

**Created by mfriedrich on 2016-08-15 13:31:39 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-08-15 13:31:39 +00:00 (in Redmine)_

---

The current way of calculating the ticket number based on the fetched ticket salt might change. Furthermore it sounds reasonable to not expose the ticket salt to any application.

There is a API action implemented with [\#12433](https://dev.icinga.com/issues/12433) which leaves the ticket number calculation inside the core and just presents the ticket string to the caller.

Please kindly consider that for the next release.

---

**Relations**:

* relates [#12433](https://dev.icinga.com/issues/12433)
* blocks [#12440](https://dev.icinga.com/issues/12440)

**Comment by dnsmichi** [comment]
Any progress here? The code still generates its own hash instead of querying the Icinga 2 API.

https://github.com/Icinga/icingaweb2-module-director/blob/da2968a6d3657e20a5695823a80f9f29e6c13e56/library/Director/Util.php#L89

**Comment by julianbrost** [comment]
This was done in 1a61cfc5c7bbe78689ed5a3ebcd5648a72e03c1f, so this issue can be closed.

**Comment by Thomas-Gelf** [comment]
Thanks!
