### ISSUE TITLE
[dev.icinga.com #12524] Import of Hosts and properties.. - Custom Variables (Fields) - But not editable later?

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#418]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12524

**Created by klockk on 2016-08-23 18:16:09 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-08-23 18:16:09 +00:00 (in Redmine)_

---

I setup a Host import, then sync rule to import the custom variables.....
They show up in the imported hosts preview, but I see no method of editing them, as the FIELDS TAB isn't available...
if I create a host MANUALLY in Director, after creation, the Fields tab appears and I can assign values to the Fields/Custom Variables...

Am I missing something here?

**Comment by Thomas-Gelf** [comment]
You need to add related fields to some template used by those imported hosts.
