### ISSUE TITLE
[dev.icinga.com #12547] Consider "disabling Director" with pending schema changes

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#422]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12547

**Created by tgelf on 2016-08-25 11:32:14 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-08-25 11:32:14 +00:00 (in Redmine)_

---

This should not be checked with every single action. However, web sessions check this anyways when refreshing the menu - we could persist (and later clean up) this information in the session. Jobs should eventually refuse to run with an outdated schema.

---

**Relations**:

* relates [#12260](https://dev.icinga.com/issues/12260)

**Comment by Thomas-Gelf** [comment]
Will not be implemented, but might be a side-effect of the upcoming dedicated background daemon.
