### ISSUE TITLE
[dev.icinga.com #12589] Custom boolean variable not matching on boolean field

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#423]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12589

**Created by jlam on 2016-08-29 22:31:08 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-08-29 22:31:08 +00:00 (in Redmine)_

---

Created a custom Boolean variable for a host. Create an apply rule for a service to match that variable. However, the apply rule is not matching at all. I have isolated the issue to the quotes of the Boolean value in the service\_apply.conf file. If I remove the quotes, it apply rule matches.

For example:

1.  NOTE: Doesn't work
    apply Service "Disk" {
    import "Disk"

assign where host.vars.legacy == "false"
}

\#NOTE: Works
apply Service "Disk" {
import "Disk"

assign where host.vars.legacy == false
}

**Comment by nE0sIghT** [comment]
Still issue

**Comment by Thomas-Gelf** [comment]
This duplicates #339 I guess, will be implemented.
