### ISSUE TITLE
[dev.icinga.com #12616] Add modifier capitalize to import

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#427]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12616

**Created by dgoetz on 2016-09-01 11:41:26 +00:00**

Assignee: _dgoetz_
Status: _Feedback_ 
Target Version: _(none)_
Last Update: _2016-12-13 11:31:50 +00:00 (in Redmine)_

---

Find a git patch attached which adds modifier capitalize which can simply capitalize a field during import.

**Attachments**

* [0001-adds-modifier-capitalize.patch](https://dev.icinga.com/attachments/download/3615/0001-adds-modifier-capitalize.patch) dgoetz - _2016-09-01 11:39:27 +00:00_

**Comment by dgoetz** [comment]
I created a pull request for this, it uses a selectbox for decision if lowercase should be used with default true as I found no example for a checkbox.
