### ISSUE TITLE
[dev.icinga.com #12645] Inherited groups not shown

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#433]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12645

**Created by dgoetz on 2016-09-05 09:44:32 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-11-04 08:00:03 +00:00 (in Redmine)_

---

Inherited groups are not shown. This could cause confusion and also if set on the host it overrides instead of adding, which would also be nice if configureable.

**Comment by Thomas-Gelf** [comment]
This has been implemented.
