### ISSUE TITLE
[dev.icinga.com #12646] Sync rule for imports with filter only the last is used

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#434]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12646

**Created by dgoetz on 2016-09-05 11:02:10 +00:00**

Assignee: _tgelf_
Status: _Feedback_ 
Target Version: _(none)_
Last Update: _2016-10-14 06:54:56 +00:00 (in Redmine)_

---

When i create a syncr rule to add imports based on a filter only the last one is evaluted (at least with 1.1 release).

An example: I have three templates "Linux", "Linux with Icinga 2 agent" and "Windows" which should be applied when the imported host has the matching filter "os=linux", "os=linux&agent=Icinga 2" and os="Windows". But it seems only the last is used as it was working fine with only linux hosts with agent and it broke when I added a windows host.

**Comment by Thomas-Gelf** [comment]
Talked to @dgoetz, problem should no longer exist.
