### ISSUE TITLE
[dev.icinga.com #12695] Cannot select commands created with Director when editing services

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#440]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12695

**Created by greatexpectations on 2016-09-12 08:22:29 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-09-29 08:11:32 +00:00 (in Redmine)_

---

Hi,

I have defined a check command using the Icinga Director UI, and successfully deployed the configuration. I can even see the checkcommand with icinga2 object list -t checkcommand, however I cannot select the newly defined checkcommand in the Director service properties view. It only allows me to pick from those commands that are defined as external objects.

Director version: Git commit 04cae6f8f89aafe19de452a2529124539ebcea99 (pull from 2016-09-12)
Icinga2 version: 2.5.4
Db backend: PostgreSQL 9.2

Kind Regards

**Comment by Thomas-Gelf** [comment]
This should have been fixed quite some time ago.
