### ISSUE TITLE
[dev.icinga.com #12778] Advice against creating zones/endpoints

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#463]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12778

**Created by tgelf on 2016-09-23 15:28:20 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-11-30 08:06:09 +00:00 (in Redmine)_

---

It rarely makes any sense to manually create zones/endpoints. Beginners coming from plain Icinga 2 config often want to start to build their infrastructure with Director exactly like they did before. That way they likely manage it to shoot themselves in the foot while doing completely needless work.

The related forms (Zones, endpoints) should eventually show a big note suggesting to re-read the docs to be absolutely sure that this is really what they need and want.

**Changesets**

_2016-09-29 19:46:21 +00:00_ by _(unknown)_ 2a83225b523ea52c9d45d570de534b7ba0a30579

    Render the Endpoint to it's Zone parent zone
    
    So you are actually able to define a satellite zone/endpoint from inside the director.
    
    Lower-Knowledge will be deployed via director, higher (or same level) zones and endpoints have to be configured in static local config.
    
    refs #12778

---

**Relations**:

* relates [#12778](https://dev.icinga.com/issues/12778)

**Comment by Thomas-Gelf** [comment]
Advice has been added long time ago, rendering has been fixed, slightly different than proposed.
