### ISSUE TITLE
[dev.icinga.com #12896] New propertymodifier to select a given array element

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#473]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12896

**Created by swizzly on 2016-10-12 12:16:18 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-10-12 12:16:18 +00:00 (in Redmine)_

---

Hi,

It would be nice to have a new propertymodifier that would return a given element of an array, e.g. select the first or last or nth element of an array.

Thank, cheers

---

**Relations**:

* relates [#12896](https://dev.icinga.com/issues/12896)

**Comment by Thomas-Gelf** [comment]
Ping @swizzly - we have been talking about this one
