### ISSUE TITLE
[dev.icinga.com #12900] Allow download of host-specific Powershell / Bash Script from remote host

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#475]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12900

**Created by twidhalm on 2016-10-12 13:57:40 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-10-12 14:04:52 +00:00 (in Redmine)_

---

Hi,

The scripts for agent installation and configuration on the `Agent` tab of the host view in Director are great. If one could download them via API it would make automatic deployment of Icinga 2 agents a lot easier.

The main benefit of this specific download is the integrated setup ticket. All other parts of the script could be replicated with most config management tools but it's a no-go to use the ticket salt on other hosts than the Icinga 2 config master.

Cheers,
Thomas

---

**Relations**:

* relates [#12915](https://dev.icinga.com/issues/12915)

**Comment by Thomas-Gelf** [comment]
A solution for this has been implemented with the Self-Service-API in v1.4.0
