### ISSUE TITLE
[dev.icinga.com #12911] Services can not be restored in history

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#483]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12911

**Created by mfrosch on 2016-10-13 09:23:11 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _1.3.1_
Last Update: _2016-11-30 08:38:19 +00:00 (in Redmine)_

---

When I try to restore a service to its previous state via the history, I get the following error:

    icinga_service has a multicolumn key, array required

This seems due to the service's object key consisting of host\_id and name.

Here is a screenshot from the debugger:

![multicolumn.png](https://dev.icinga.com/attachments/download/3690/multicolumn.png)

![multicolumn-gui.png](https://dev.icinga.com/attachments/download/3691/multicolumn-gui.png)

**Attachments**

* [multicolumn.png](https://dev.icinga.com/attachments/download/3690/multicolumn.png) mfrosch - _2016-10-13 09:22:37 +00:00_
* [multicolumn-gui.png](https://dev.icinga.com/attachments/download/3691/multicolumn-gui.png) mfrosch - _2016-10-13 09:22:39 +00:00_

---

**Relations**:

* relates [#12911](https://dev.icinga.com/issues/12911)

**Comment by aflatto** [comment]
I just encountered the same issue in the  master from Jan 19 
![screenshot at 2018-03-20 12-22-43](https://user-images.githubusercontent.com/15072071/37649344-227093ca-2c3a-11e8-8d2e-c4b338e58cf6.png)

**Comment by NeverUsedID** [comment]
Same here with an "Apply  Service For"-Rule

**Comment by Thomas-Gelf** [comment]
This should have been fixed with v1.5.0 - in case there are still related issues please let us know.
