### ISSUE TITLE
[dev.icinga.com #12915] Fully automated Agent rollout

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#486]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12915

**Created by tgelf on 2016-10-13 11:27:55 +00:00**

Assignee: _tgelf_
Status: _Assigned_ 
Target Version: _(none)_
Last Update: _2016-10-13 11:27:55 +00:00 (in Redmine)_

---

Given that the Agents can reach a) their CA master and b) the Director I could imagine the following workflow:

-   I assign an API key to a specific host template. This key allows you to create new agent hosts using exactly this single host template. Nothing more. No read access, not even for it's one object. Host template field restrictions should apply.
-   The CREATE request generates a dedicated API key for the new host and ships that key in it's response.
-   The Agent can now use that key to retrieve it's ticket for certificate signing, to fetch it's customized icinga2.conf or just the information required to create such: ca host, parent zone and node(s), their addresses in case the Agent should connect to it's parent(s)

This would for example allow to ship a single script to all your Windows servers without the need to customize the script on every agent.

---

**Relations**:

* relates [#12915](https://dev.icinga.com/issues/12915)

**Comment by freddy4711** [comment]
Hello,

I am very interested in this feature, as we are planning a new landscape with Windows and Linux agents. Is there any progress on that feature?

**Comment by LordHepipud** [comment]
Hello,

you can take a look on the Icinga 2 PowerShell Module on my GitHub Account: https://github.com/LordHepipud/icinga2-powershell-module

It's the same PowerShell Script / Module beeing used within the Director, but new developments are added there in first place. Right now you still have to configure all arguments for the script manually, but creating hosts, receiving the certificate and installing / configuring the Agent is possible right away.

What you can do for example is execute the Script with PowerShell remote execution or by Group Policies for identical hosts who should report to the same Icinga 2 instance. In that case you can still manage a large amount of Windows machines at the same time.

For Linux you could use tools like Puppet or Ansible for example, to do the job.

Best regards

**Comment by Thomas-Gelf** [comment]
Things are working forward. Depending on how much time I'll need to spend on other tasks there is a good chance that this could be implemented within this week - we'll see. @LordHepipud is working on the related PowerShell code in parallel.

![director_self-service](https://user-images.githubusercontent.com/553008/27871629-7dbf1896-61a6-11e7-8d97-d02e00bcc773.png)

**Comment by Thomas-Gelf** [comment]
@LordHepipud: could you please test the current implementation?
