### ISSUE TITLE
[dev.icinga.com #12924] Get rid of all those __toString methods...

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#493]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12924

**Created by tgelf on 2016-10-14 10:30:09 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-10-14 10:30:40 +00:00 (in Redmine)_

---

...with their weird error-handling

**Comment by Thomas-Gelf** [comment]
Such methods still exist, but they don't really hurt
