### ISSUE TITLE
[dev.icinga.com #12944] Command selection requires methods_execute

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#500]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12944

**Created by mfrosch on 2016-10-19 10:56:09 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _1.3.1_
Last Update: _2016-11-30 08:38:59 +00:00 (in Redmine)_

---

Usually you can set methods\_execute via a template, like the core does it.

But when you do that, the command will not be found by \\Icinga\\Module\\Director\\Db::enumCheckcommands

It needs to be specifically set on every command.

**Comment by Thomas-Gelf** [comment]
There is no way to configure such Command (without type) in the GUI any more. We might re-allow doing so when inheriting a type once we have  fully resolved property cache tables, but unless then it's not worth the effort.
