### ISSUE TITLE
[dev.icinga.com #12964] Beatify rendered assign rules

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#506]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12964

**Created by tgelf on 2016-10-24 17:24:09 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-10-24 17:24:09 +00:00 (in Redmine)_

---

I expect to read something like:

        assign where (
            host.name == "as"
            || host.name == "ba"
            || (
                host.vars.x == "y"
                && host.vars.a == "b"
            )
        )

Currently I get:

        assign where host.name == "as" || host.name == "ba" || (host.vars.x == "y" && host.vars.a == "b")

**Comment by Thomas-Gelf** [comment]
Not now.
