### ISSUE TITLE
[dev.icinga.com #12969] Fully resolve all templates to a flat structure

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#511]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12969

**Created by tgelf on 2016-10-24 20:04:28 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-10-24 20:04:28 +00:00 (in Redmine)_

---

Might happen at runtime and/or into a flat cache-like db structure. This is a base requirement for a couple of features, like apply-rule preview, showing all related/affected objects and more.

**Comment by Thomas-Gelf** [comment]
It's not persisted, but already exists in-memory in a pretty fast way. Having it DB-based might still be nice, but that's something we can tackle in a second moment.
