### ISSUE TITLE
[dev.icinga.com #12970] Change "experimental_features" to be a boolean value

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#512]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12970

**Created by tgelf on 2016-10-24 21:02:40 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-10-24 21:02:40 +00:00 (in Redmine)_

---

**Comment by Thomas-Gelf** [comment]
Not needed for now
