### ISSUE TITLE
[dev.icinga.com #12971] Make job form more comfortable

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#513]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12971

**Created by tgelf on 2016-10-24 21:21:21 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-10-24 21:21:21 +00:00 (in Redmine)_

---

Changing settings forth and back is sometimes weird, this needs more dedicated love

**Comment by Thomas-Gelf** [comment]
Weirdness only affects you when changing idea, should once be fixed with #81
