### ISSUE TITLE
[dev.icinga.com #12972] Propose existing command vars and macros from set_if...

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#514]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12972

**Created by tgelf on 2016-10-24 21:29:49 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-10-24 21:29:49 +00:00 (in Redmine)_

---

...when adding fields

---

**Relations**:

* relates [#11460](https://dev.icinga.com/issues/11460)

**Comment by sahnd** [comment]
Hi,

it would be very helpful to have this in place, because otherwise we need to define a lot of data fields by hand.
Is there a roadmap/timetable for this feature to be implemented?

Regards,
Sebastian

**Comment by widhalmt** [comment]
Yes. This would be very good to have it fixed. It makes using ITL commands rather cumbersome.

**Comment by mwaldmueller** [comment]
+1

**Comment by mwaldmueller** [comment]
ping

**Comment by offsides** [comment]
Any word on making this happen?  Having to define the boolean parameters totally separately from the arguments is both confusing and cumbersome.

**Comment by log1-c** [comment]
Might I ask for a current status for this feature?
