### ISSUE TITLE
[dev.icinga.com #12975] Ask whether applied objects should be copied, too

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#515]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12975

**Created by twidhalm on 2016-10-25 07:14:33 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-10-25 07:14:33 +00:00 (in Redmine)_

---

Hi,

When copying a template (e.g. host template) it would be a very nice feature if assigned services (and maybe other objects) could (optionally!) be copyied, too. Since assigned services use template specific apply rules this would have to be a clone of the apply rules. I don't think it would be a good idea to just add another assign to the apply rules.

Cheers,
Thomas

**Comment by Thomas-Gelf** [comment]
When cloning a Host Director now allows to also clone optionally clone assigned single services and sets. Defaults to YES.
