### ISSUE TITLE
[dev.icinga.com #12973] Simplify lists and link to object overview pages

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#516]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12973

**Created by tgelf on 2016-10-24 21:43:01 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-10-24 21:43:01 +00:00 (in Redmine)_

---

Our tables should become simpler and link to compact overview pages with all the details related to that specific object, and all the required links for any related action.

**Comment by Thomas-Gelf** [comment]
This is fine for now.
