### ISSUE TITLE
[dev.icinga.com #12999] setAssign_filter should bail when setting assign_filter and it's not supported

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#527]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12999

**Created by mfrosch on 2016-10-28 07:22:40 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-10-28 07:22:40 +00:00 (in Redmine)_

---

I added a workaround in f9f61be7aa454afda474bd61969b6bb20ca2b031 to avoid Sync / replace problems with Services.

This might cause issues because assign\_filter could possibly be set to NULL on every object, and then erroring on DB save.

**Comment by Thomas-Gelf** [comment]
This used to be an issue at the time being, when we changed how assign_filter's work. I vaguely remember to have introduced a new related exception in case someone still tries to fill the legacy property. Closing this for now, as it shouldn't affect any recent installation - in case I overlooked something please let me know by re-opening this with some related details.
