### ISSUE TITLE
[dev.icinga.com #13025] Assign service to host with Director API

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#540]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13025

**Created by kelemen on 2016-11-01 15:29:46 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-11-23 17:41:58 +00:00 (in Redmine)_

---

Hello,

I wonder what is a proper way to assign a service to a host with Director API.

I was unable to find an example in the docs. Is there such an option at all?

Thanks!

**Comment by Thomas-Gelf** [comment]
The given example should work fine. In case more details are required please post a more specific question.
