### ISSUE TITLE
[dev.icinga.com #13027] No dashboard available for users with limited permissions

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#542]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13027

**Created by mmabrouk on 2016-11-01 19:38:50 +00:00**

Assignee: _tgelf_
Status: _Resolved_  (closed on _2016-11-03 13:30:06 +00:00_)
Target Version: _1.2.0_
Last Update: _2016-11-03 15:07:58 +00:00 (in Redmine)_

---

I am trying to add a user that can only create/modify users and notifications using Icinga Director, so I added the following permissions to my roles.ini:

"module/director, director/api, director/users/read, director/users/write, director/userGroups/read, director/userGroups/write, director/notifications/read, director/notifications/write".

However every time I navigate to Icinga Director it gives an error "Got no "Data" dashboard for you".

This error doesn't appear when I'm using a user with unrestricted permissions "\*".

**Attachments**

* [error.PNG](https://dev.icinga.com/attachments/download/3761/error.PNG) mmabrouk - _2016-11-01 16:51:57 +00:00_

**Changesets**

_2016-11-03 13:27:15 +00:00_ by _tgelf_ 58245108c44ae55a3c49d0220084724ab4800324

    Dashboard: show a nice message if no dashboard...
    
    ...is available
    
    fixes #13027

---

**Relations**:

* copied_to [#13027](https://dev.icinga.com/issues/13027)

**Comment by aflatto** [comment]
The same issue is happening to me now : 
Director:Version  master
Git commit : 6c80a20cf8b947d5cc283a343900fb75108fb7af
icinga 2.4.1 
Web2 2.6.1

**Comment by Thomas-Gelf** [comment]
@aflatto: please specify what "same issue" means. What permissions did you assign?

**Comment by aflatto** [comment]
At some stage I defined them as full admin and they still did see any dashboard.

On 27 November 2017 11:52:17 GMT+02:00, Thomas Gelf <notifications@github.com> wrote:
>@aflatto: please specify what "same issue" means. What permissions did
>you assign?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/Icinga/icingaweb2-module-director/issues/542#issuecomment-347131236

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Thomas-Gelf** [comment]
This doesn't really help, no way one would see nothing with a global "*" permission. Did you log them out and in again after changing permissions? Your permissions in Icinga Web 2 are evaluated at login time and they stay valid throughout your session.

**Comment by aflatto** [comment]
Yes. After every change I asked the user to logout and login again.
We tried several combinations of permissions and none show the dashboard.  I even compared to the old install we have, and in that one they only had access to the monitoring module and could see the dashboard. 
As soon as I am back I will attempt to upload screen captures.

On 27 November 2017 12:40:42 GMT+02:00, Thomas Gelf <notifications@github.com> wrote:
>This doesn't really help, no way one would see nothing with a global
>"*" permission. Did you log them out and in again after changing
>permissions? Your permissions in Icinga Web 2 are evaluated at login
>time and they stay valid throughout your session.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/Icinga/icingaweb2-module-director/issues/542#issuecomment-347143682

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by aflatto** [comment]
These are screen captures of the issue : 

![user-permissions-1](https://user-images.githubusercontent.com/15072071/33263900-3ba938ca-d374-11e7-8b4c-d50595d9909e.PNG)
![snipimage](https://user-images.githubusercontent.com/15072071/33263953-617dee4c-d374-11e7-858a-582835138c30.JPG)

**Comment by Thomas-Gelf** [comment]
@aflatto: this user seems to have no permission at all. For example, you granted access to the Cube module and to the Director module, none of them is visible in the menu. The second screen-shot is showing the Icinga Web 2 dashboard and not the Director Dashboard. So, this should not be related in any way to either Director nor above issue, being closed since a long time ago.

At first sight this looks like a configuration error. Maybe somehow your role doesn't get assigned to your user. Your screen-shot doesn't show related details (users/groups matching rules), so I cannot help you with this. If you're unable to fix it please open a dedicated issue in the Icinga Web 2 issue tracker with all the details related to your role in question.

Cheers,
Thomas
