### ISSUE TITLE
[dev.icinga.com #13033] TemplateResolver needs to be updated properly on changed imports

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#545]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13033

**Created by mfrosch on 2016-11-03 08:00:26 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-11-03 08:00:26 +00:00 (in Redmine)_

---

We cannot just clear the cache every time. (For sync performance)

This has been tried to achieve with 86d2f317ee7ec44d8a924d8e51ace253f44feba7, but it is falsly implemented.

Also the test HostTests::testHandlesUnmodifiedProperties is affected by this. (has been disabled)

**Changesets**

_2016-11-03 08:01:56 +00:00_ by _mfrosch_ bfcb452595a1197808578b3e3bcc5f9947ac4abd

    WIP: TemplateResolver: Fix updating imports without clearing the cache
    
    Not yet working, IcingaObjectImports load stuff from TemplateResolver, which loops with this code.
    
    refs #13033

**Comment by Thomas-Gelf** [comment]
While parts of this might still apply, above code is no longer in use
