### ISSUE TITLE
[dev.icinga.com #13037] Add ability to increase check_timeout for Services

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#546]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13037

**Created by mwaldmueller on 2016-11-03 13:08:19 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _1.3.1_
Last Update: _2016-11-30 08:46:54 +00:00 (in Redmine)_

---

Add ability to increase check\_timeout for Services to overwrite the default CheckCommand timeout of 60 seconds.

**Comment by widhalmt** [comment]
+1 thanks for dealing with this. I hit this,too.
