### ISSUE TITLE
[dev.icinga.com #13048] Some tabs are missing parameters

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#556]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13048

**Created by tgelf on 2016-11-04 08:47:26 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-11-04 08:47:26 +00:00 (in Redmine)_

---

Example: "Add a service" and instead of compiling the form click it's tab.

**Comment by Thomas-Gelf** [comment]
All tabs have been re-implemented for v1.4.0 and special care has been taken to fix this.
