### ISSUE TITLE
[dev.icinga.com #13055] Data field as array provide data lists 

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#560]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13055

**Created by chrkli193 on 2016-11-07 06:44:11 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-12-13 12:07:05 +00:00 (in Redmine)_

---

I would be great if it is possible to assign a datalist to a datafield of type array.

Example:

I have a Windows host and want to check only a part of all available drives.
Then I can choose only those drives from a field of type array and create a apply rule like:

assign where "x:" in host.windows\_drives
assign where "d:" in host.windows\_drives

---

**Relations**:

* relates [#13543](https://dev.icinga.com/issues/13543)
* relates [#12701](https://dev.icinga.com/issues/12701)

**Comment by dgoetz** [comment]
:+1:

I would benefit from this in the following use case. Service/Serviceset assignment is done by a custom variable which is an array of installed applications, limiting this to a datalist would prevent typos and directly show which applications are already prepared.

**Comment by Thomas-Gelf** [comment]
After proof-reading this and talking to @dgoetz this should be a duplicate and has been implemented for v1.4.0.
