### ISSUE TITLE
[dev.icinga.com #13060] Wrong sort order of sync rule properties

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#565]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13060

**Created by tobiasvdk on 2016-11-07 17:21:58 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-11-07 17:22:47 +00:00 (in Redmine)_

---

Currently sync rule properties are sorted by priority in descending order but they need to be sorted in ascending order.

**Attachments**

* [0001-Correct-sort-order-of-sync-rule-properties.patch](https://dev.icinga.com/attachments/download/3781/0001-Correct-sort-order-of-sync-rule-properties.patch) tobiasvdk - _2016-11-07 17:22:44 +00:00_

---

**Relations**:

* copied_to [#13061](https://dev.icinga.com/issues/13061)

**Comment by Thomas-Gelf** [comment]
Déjà-vu?! Fixed.
