### ISSUE TITLE
[dev.icinga.com #13061] Wrong sort order of import source row modifiers

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#566]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13061

**Created by tobiasvdk on 2016-11-07 17:25:36 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-11-07 17:26:07 +00:00 (in Redmine)_

---

Currently import source row modifiers are sorted by priority in descending order but they need to be sorted in ascending order.

**Attachments**

* [0001-Correct-sort-order-of-import-source-row-modifiers.patch](https://dev.icinga.com/attachments/download/3782/0001-Correct-sort-order-of-import-source-row-modifiers.patch) tobiasvdk - _2016-11-07 17:26:05 +00:00_

---

**Relations**:

* copied_to [#13061](https://dev.icinga.com/issues/13061)

**Comment by Thomas-Gelf** [comment]
@tobiasvdk: this has been implemented together with the possibility to re-order modifiers and a schema upgrade fixing former priorities. They used to be stored with priority = 1 - all of them.
