### ISSUE TITLE
[dev.icinga.com #13062] Allow sorting of jobs

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#567]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13062

**Created by tobiasvdk on 2016-11-07 18:19:04 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-11-07 18:19:04 +00:00 (in Redmine)_

---

Normally you want to import all data first and afterwards trigger a sync. So I have two jobs, "Import All" and "Sync All" and both have the same "Run interval". To work correctly I must be able to set the job run order so that the import job runs before the sync job.

**Comment by Thomas-Gelf** [comment]
Might sound reasonable, at first sight - but it absolutely isn't. Different intervals for different sources, both needed in the same sync, Sync running at a much higher frequency as it is often ways faster than many sources and so on. Order doesn't matter and gives no guarantee, if it wasn't right in the current sync it will be in the next one.
