### ISSUE TITLE
[dev.icinga.com #13064] Replace TableLoader and FormLoader with a generic ClassLoader

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#570]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13064

**Created by mfrosch on 2016-11-08 07:47:28 +00:00**

Assignee: _mfrosch_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-11-08 09:56:07 +00:00 (in Redmine)_

---

Currently, Tables can not extend other tables, because of a non existing auto-loader.

Idea is to replace the existing FormLoader and TableLoader with an additional spl\_autoload ClassLoader.

The Form contexts gets auto-loaded by icingaweb2, Tables not yet.

**Changesets**

_2016-11-08 07:59:54 +00:00_ by _mfrosch_ 9169da0fa99f7884c8bc2febd3a2f731cd0550f3

    ClassLoader: Introduce additional ClassLoader
    
    The Loader replaces TableLoader in a generic manner. FormLoader is handled by Icinga\Application\ClassLoader for every module.
    
    refs #13064

_2016-11-28 17:12:49 +00:00_ by _mfrosch_ 038d77709f649f8817e7b460d919ee4ff7d33309

    ClassLoader: Introduce additional ClassLoader
    
    The Loader replaces TableLoader in a generic manner. FormLoader is handled by Icinga\Application\ClassLoader for every module.
    
    refs #13064

**Comment by Thomas-Gelf** [comment]
Thanks for the time spent on this, @lazyfrosch. I'll reject this, we'll not implement a custom loader in the Director module. Such a loader belongs to the base framework. For now, Director form and table loading works - even if it's not very "nice".

The `ipl` will help us to simplify some code an to get rid of most table/form aliens in the Director over time, beginning with v1.4.0. They will then make part of the library tree - and this will become a non-issue.
