### ISSUE TITLE
[dev.icinga.com #9462] Evaluate using bigint for timestamps with msec support

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#58]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/9462

**Created by tgelf on 2015-06-19 20:42:57 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2017-01-16 15:32:40 +00:00 (in Redmine)_

---

I'd like to have database-independent support for more granular timestamps. We should evaluate storing unix timestamps with m/usecs to 64bit bigint fields.

Cheers,
Thomas

**Comment by Thomas-Gelf** [comment]
Nothing to evaluate, bigint is now our default for timestamps in other modules too. No urgency right now, we fixed timezone issues differently right now.
