### ISSUE TITLE
[dev.icinga.com #13097] Template Tree

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#582]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13097

**Created by mmittel2 on 2016-11-09 09:47:58 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-11-09 09:47:58 +00:00 (in Redmine)_

---

For me the template tree is always fully opened. If I close a branch it opens with the next reload.
Cheers Merlin.

---

**Relations**:

* relates [#13101](https://dev.icinga.com/issues/13101)

**Comment by Thomas-Gelf** [comment]
We could steal some code from the `businessprocess` module to solve this, but this seems overkill to me right now. Once we unified some libs (looking at you, `ipl`), we could get this for free. In the meantime, not auto-refreshing the tree must suffice as a 'fix'.
