### ISSUE TITLE
[dev.icinga.com #13101] Rewrite the template tree

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#584]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13101

**Created by tgelf on 2016-11-09 10:22:53 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-11-09 10:22:53 +00:00 (in Redmine)_

---

It should:

-   fit the look and feel of the rest of the application
-   show all templates, not only used ones
-   allow to show related objects
-   remember which nodes where collapsed

---

**Relations**:

* relates [#13101](https://dev.icinga.com/issues/13101)

**Comment by Thomas-Gelf** [comment]
Implemented and pushed to `next`.

![director_new-templatetree](https://user-images.githubusercontent.com/553008/27457428-0482fc32-57a5-11e7-9595-caeca88c2e36.png)
