### ISSUE TITLE
[dev.icinga.com #13109] Cannot edit or delete timeperiods

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#586]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13109

**Created by dzalewski on 2016-11-09 14:30:27 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-11-09 15:32:24 +00:00 (in Redmine)_

---

Hi,

I've defined wrong time period range "00:00:-24:00" instead of "00:00-24:00" (notice extra full colon after 00). When I try to change it, nothing happens and I'm getting a yellow notification a the bottom saying that object has not been modified (see attached screenshot)

In addition to that when I try to delete this timeperiod , director doesn't allow me to that and comes back with an error:

    SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails ("director"."director_job", CONSTRAINT "director_job_period" FOREIGN KEY ("timeperiod_id") REFERENCES "icinga_timeperiod" ("id") ON UPDATE CASCADE), query was: DELETE FROM icinga_timeperiod WHERE (id = '1')

    #0 /usr/share/icingaweb2/library/vendor/Zend/Db/Statement.php(297): Zend_Db_Statement_Pdo->_execute(Array)
    #1 /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Abstract.php(470): Zend_Db_Statement->execute(Array)
    #2 /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Pdo/Abstract.php(232): Zend_Db_Adapter_Abstract->query('DELETE FROM ici...', Array)
    #3 /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Abstract.php(652): Zend_Db_Adapter_Pdo_Abstract->query('DELETE FROM ici...')
    #4 /usr/share/icingaweb2/modules/director/library/Director/Data/Db/DbObject.php(790): Zend_Db_Adapter_Abstract->delete('icinga_timeperi...', 'id = '1'')
    #5 /usr/share/icingaweb2/modules/director/library/Director/Data/Db/DbObject.php(912): Icinga\Module\Director\Data\Db\DbObject->deleteFromDb()
    #6 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/DirectorObjectForm.php(644): Icinga\Module\Director\Data\Db\DbObject->delete()
    #7 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/DirectorObjectForm.php(586): Icinga\Module\Director\Web\Form\DirectorObjectForm->deleteObject(Object(Icinga\Module\Director\Objects\IcingaTimePeriod))
    #8 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/QuickForm.php(450): Icinga\Module\Director\Web\Form\DirectorObjectForm->onRequest()
    #9 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/QuickForm.php(462): Icinga\Module\Director\Web\Form\QuickForm->setRequest(Object(Icinga\Web\Request))
    #10 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/QuickForm.php(322): Icinga\Module\Director\Web\Form\QuickForm->getRequest()
    #11 /usr/share/icingaweb2/modules/director/library/Director/Web/Controller/ObjectController.php(166): Icinga\Module\Director\Web\Form\QuickForm->handleRequest()
    #12 /usr/share/icingaweb2/modules/director/library/Director/Web/Controller/ObjectController.php(104): Icinga\Module\Director\Web\Controller\ObjectController->editAction()
    #13 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Director\Web\Controller\ObjectController->indexAction()
    #14 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('indexAction')
    #15 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
    #16 /usr/share/php/Icinga/Application/Web.php(384): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
    #17 /usr/share/php/Icinga/Application/webrouter.php(109): Icinga\Application\Web->dispatch()
    #18 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...')
    #19 {main}

</pre>
I'm using following versions:

Icinga2 2.5.4
Icingaweb2 2.5.4
Director (github checkout from Nov 4th)
MariaDB 5.5.50
RHEL 7.2

Thanks

Dominik

**Attachments**

* [director-timeperiods.PNG](https://dev.icinga.com/attachments/download/3795/director-timeperiods.PNG) dzalewski - _2016-11-09 14:29:28 +00:00_
* [director-delete-timeperiods.PNG](https://dev.icinga.com/attachments/download/3797/director-delete-timeperiods.PNG) dzalewski - _2016-11-09 14:29:28 +00:00_

**Comment by Thomas-Gelf** [comment]
There where still some related bugs that should have been fixed this (or last?) week.
