### ISSUE TITLE
[dev.icinga.com #13125] Import hosts with AWS modul

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#589]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13125

**Created by stay on 2016-11-10 10:19:05 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-12-02 19:59:55 +00:00 (in Redmine)_

---

Hi folks,
I´m currently trying to create a import based on the AWS module.
I´ve set up everything as described in the documentation, and after the first source import i can successfully see the EC2 Instances in the preview tab.
My issue is with the sync rule.
I don´t want to sync all instances, therefore I´ve modified the sync rule with a filter expression.
The filter expression is: tags.Application=IIS.
If I try to trigger the sync rule, i´m being told that nothing changed and no host are imported.
The import source does actually not hold the field "tags.Application", but the field "tags", does hold it. As this field is a JSON, I do think my expression in the sync rule should work.
Do I have to create dedicated modifier for the import source? If so what is the best way to do so?
Any help is appreciated.
Cheers!

**Comment by Thomas-Gelf** [comment]
Yep, wrong issue tracker - closing this one
