### ISSUE TITLE
[dev.icinga.com #13139] Allow to set Zone in Notification Templates

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#594]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13139

**Created by log1c on 2016-11-10 12:59:28 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-11-10 12:59:28 +00:00 (in Redmine)_

---

Allow to set Zone in Notification Templates, like we already are able to in user templates.

Best Regards,
Logic

**Comment by Thomas-Gelf** [comment]
This has been merged.
