### ISSUE TITLE
[dev.icinga.com #13143] Automation sync jobs order

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#595]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13143

**Created by dzalewski on 2016-11-10 14:37:35 +00:00**

Assignee: _dzalewski_
Status: _Feedback_ 
Target Version: _(none)_
Last Update: _2016-11-10 16:03:29 +00:00 (in Redmine)_

---

Hi,

I have 4 sync jobs in Director pulling hosts, host groups, user and user groups from CMDB (iTop) via SQL query.

Hosts sync job won't be able to assign a host to a host group if its not there already. I have to first run host group sync jobs and then hosts sync job.

It would be nice if we were able to set sync jobs order or perhaps dependencies on other sync jobs.

I'm not sure if this the most elegant solution. Is there is alreadya better way of solving this issue?

Thanks

Dominik

---

**Relations**:

* relates [#13145](https://dev.icinga.com/issues/13145)

**Comment by Thomas-Gelf** [comment]
There where some bugs related to persisting job errors, this should have been improved with v1.7.0. No plans for hard-coded "ordering" right now.
