### ISSUE TITLE
[dev.icinga.com #13211] REST API over HTTPs as data source

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#603]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13211

**Created by dzalewski on 2016-11-16 12:48:25 +00:00**

Assignee: _dzalewski_
Status: _Feedback_ 
Target Version: _(none)_
Last Update: _2016-12-06 12:38:07 +00:00 (in Redmine)_

---

It would be nice if data could be fetched from a source via REST API over HTTPS. Most REST APIs return back JSON so ability to parse it would be a useful.

**Comment by Thomas-Gelf** [comment]
No feedback, closing this for now.
