### ISSUE TITLE
[dev.icinga.com #13213] Configure commands for sudo in director

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#604]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13213

**Created by bcogel on 2016-11-16 13:11:42 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-11-17 10:25:11 +00:00 (in Redmine)_

---

I'm trying to set up a command to be used through sudo with director.

What does work:

- Define the check command "eDir Time" with command "/usr/bin/sudo /usr/lib/nagios/plugins/check\_edir\_time" (or "/usr/bin/sudo /usr/lib64/nagios/plugins/check\_edir\_time").
- Service is defined with name "eDir Time" and check command "eDir Time"
- Check command preview is now

object CheckCommand "eDIR Time" {
import "plugin-check-command"
command = \[ "/usr/bin/sudo", "/usr/lib/nagios/plugins/check\_edir\_time" \]
}

- Check result is now

OK: All reachable servers have time in sync. OK: All servers were contacted.

- system log for sudo shows

sudo: icinga : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/lib/nagios/plugins/check\_edir\_time

What doesn't work is to somehow replace "/usr/lib/nagios/plugins" with PluginDir. Depending on what I'm doing, I get the plugin result in Icinga:

sudo: Kein TTY vorhanden und kein Â»askpassÂ«-Programm angegeben

and in the system log things like

sudo: icinga : command not allowed ; TTY=unknown ; PWD=/ ; USER=root ; COMMAND=check\_edir\_time

or

sudo: icinga : command not allowed ; TTY=unknown ; PWD=/ ; USER=root ; COMMAND=PluginDir+"/check\_edir\_time"

So the problem is not to get sudo working as expected, but to get the director and/or icinga2 to setup the paths correct and to expand the defined constant. At the moment I'm getting code like

command = \[ PluginDir + "/sudo", "PluginDir+check\_edir\_time" \]

command = \[ PluginDir + "/sudo", "check\_edir\_time" \]

....

Things would be easier if I could simply select a commandtype ' sudo Plugin Check Command' or select a checkbox 'Run as (sudo)' with perhaps a field for a sudo username in the 'new command' dialog.

In both cases director could use PluginDir as constant in the commands without side effects to generate the expected code:

command = \[ "sudo", PluginDir + "/check\_edir\_time" \]

Regards
Berthold Cogel

**Comment by cflinspach** [comment]
In director it only adds "PluginDir" if you just use a relative path. If you use the full path it doesn't prefix it with PluginDir. An example is we have a plugin that uses icmp from Net::Ping which required root access. so for our "Command" we have `/usr/bin/sudo /usr/lib/nagios/plugins/check_ap_status.pl` and the "preview" tab shows 
```
object CheckCommand "ap_status" {
    import "plugin-check-command"
    command = [
        "/usr/bin/sudo",
        "/usr/lib/nagios/plugins/check_ap_status.pl"
    ]
```
And we used visudo and added:
# Nagios
nagios ALL=(root) NOPASSWD: /usr/lib/nagios/plugins/check_ap_status.pl


The command works fine and runs with sudo.

**Comment by Thomas-Gelf** [comment]
Thanks for the detailed explanation, @cflinspach - I'll close this issue.
