### ISSUE TITLE
[dev.icinga.com #13223] Cannot delete service from CLI

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#605]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13223

**Created by plarivee on 2016-11-17 13:17:29 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-11-17 13:17:29 +00:00 (in Redmine)_

---

director 1.1.0
icingacli 2.3.4+fix-1~ppa1404+1

After creating a service with the cli, I can show it, check if exists but cannot delete. Getting this error:

    root@web:~# icingacli director service delete snmp_check_test
    ERROR: Icinga\Exception\IcingaException in /usr/share/php/Icinga/Cli/Command.php:141 with message: Object name parameter is required

Using --verbose --debug doesn't give more info.

Deleting the service in the Director UI does work. Also getting same error with director 1.2.0

root@web:~\# icingacli director service set snmp\_check\_test --object\_type template --check\_command "snmp-storage" --auto-create
Service 'snmp\_check\_test' has been created
root@web:~\# icingacli director service exists snmp\_check\_test
Service 'snmp\_check\_test' exists
root@web:~\# icingacli director service show snmp\_check\_test
template Service "snmp\_check\_test" {
check\_command = "snmp-storage"
}

**Comment by shakalandy** [comment]
@Thomas-Gelf would some G+T help overhere? or a package of bordeaux wines? ;-)

**Comment by Thomas-Gelf** [comment]
user@web:~$ icingacli director service delete 'My Service' --host some.example.com
    Service 'My Service' has been deleted
