### ISSUE TITLE
[dev.icinga.com #13227] Provide an autocompletion feature

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#606]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13227

**Created by tgelf on 2016-11-17 14:13:17 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _1.4.0_
Last Update: _2016-11-28 14:51:38 +00:00 (in Redmine)_

---

There are various places where this can be helpful. Just to name a few:

-   import lists
-   all kind of "extensible sets" (allows faster loading)
-   filters (column dropdowns)

---

**Relations**:

* relates [#13227](https://dev.icinga.com/issues/13227)
* relates [#13227](https://dev.icinga.com/issues/13227)

**Comment by Thomas-Gelf** [comment]
Preview:

![director_autocomplete_command](https://cloud.githubusercontent.com/assets/553008/26626680/510216ce-45f8-11e7-834a-ba9758b76ef8.gif)

**Comment by Thomas-Gelf** [comment]
Has been re-enabled and pushed to `next`. Works so far, data providers will be re-factored. Also, suggestion context might ask for "more context"... we'll see. Works for now, might be shaped after playing with it for a little while.
