### ISSUE TITLE
[dev.icinga.com #13261] Deleting a host with manually set services or servicesets does not give it in history

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#615]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13261

**Created by TheFlyingCorpse on 2016-11-20 10:28:50 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-11-20 15:19:47 +00:00 (in Redmine)_

---

When deleting a host which has "directyl" assigned services, either by hand or through a sync rule it doesnt add these services as "cascade" deleted to the history.

Why is this a bug?
This is an issue when you want to restore said object to being functional again, you dont neccesarily know which service(set)s were added by hand.

---

**Relations**:

* duplicates [#13261](https://dev.icinga.com/issues/13261)

**Comment by Thomas-Gelf** [comment]
Duplicates #623
