### ISSUE TITLE
[dev.icinga.com #13283] Missing Groups fiel for services through template

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#619]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13283

**Created by birkir on 2016-11-23 01:54:03 +00:00**

Assignee: _(none)_
Status: _Assigned_ 
Target Version: _(none)_
Last Update: _2016-12-07 00:02:41 +00:00 (in Redmine)_

---

When creating a service for a host template, it is not possible to set a service-group for that service.

Create new host template -&gt; Add service -&gt; no Groups field.

**Comment by dgoetz** [comment]
I have the same problem with services applied as a service set. The use case is to have the same checks like basic http check (and very specific ones) used in different service sets for different application server. So in this case it makes no sense to define group membership on the service template and apply form already allows to set the groups, so it make sense to have this option also on service sets. If you agree it would be a one line change if I am correct (and a second similar one for the original request).

```
diff --git a/application/forms/IcingaServiceForm.php b/application/forms/IcingaServiceForm.php
index 6358345..dc06210 100644
--- a/application/forms/IcingaServiceForm.php
+++ b/application/forms/IcingaServiceForm.php
@@ -310,6 +310,7 @@ class IcingaServiceForm extends DirectorObjectForm
 
         $this->addNameElement()
              ->addDisabledElement()
+             ->addGroupsElement()
              ->groupMainProperties();
 
         if ($this->hasPermission('director/admin')) {
```

Another idea would be to have the groups element on the service set form and let services inherit from it but this would require more work including a new database table. Also it will make configuration easier for some but will perhaps not fit everyone's use case, so I would opt for the first one. 

If you agree I can create a pull request for this.

**Comment by dgoetz** [comment]
The pull request adds the element to add Servicegroups in Service sets and at Host templates.

The logic with inherited and applied groups like it is available for Hostgroups is still missing as it would require a similar resolver and instead of duplicating the code it could be perhaps moved to be more general. But this is to much for my coding skills. ;-)

**Comment by Thomas-Gelf** [comment]
Well... it's merged, so let's mention it.
