### ISSUE TITLE
[dev.icinga.com #13287] Error message doesn't show list (id) if a key is not found

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#621]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13287

**Created by tobiasvdk on 2016-11-23 09:54:45 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-12-08 20:17:47 +00:00 (in Redmine)_

---

I had the following error message because the key is missing in a list map:

    This Import Source failed when last checked at 2016-11-23 09:50:56: "this-is-my-key" cannot be found in the "List with id " data list

The data list id is missing. Furthermore as a user I don't want to know the list *id* but the list *name*.

**Attachments**

* [0001-Return-data-list-name.patch](https://dev.icinga.com/attachments/download/3895/0001-Return-data-list-name.patch) tobiasvdk - _2016-12-08 20:16:53 +00:00_

**Comment by tobiasvdk** [comment]
I think this can be closed @Thomas-Gelf

**Comment by Thomas-Gelf** [comment]
@tobiasvdk: yes, has been merged with fd53224. Thank you!
