### ISSUE TITLE
[dev.icinga.com #13307] Depending services should get deleted by director

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#623]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13307

**Created by mfrosch on 2016-11-24 10:12:05 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-11-24 10:24:01 +00:00 (in Redmine)_

---

Currently services that are directly added to a host will get deleted by the database, and not the director itself.

Therefor they are not shown in audit log.

We should properly delete the services, and log the event. Maybe find a general way for related objects that should be deleted without question. (Or ask a question?)

---

**Relations**:

* duplicates [#13261](https://dev.icinga.com/issues/13261)

**Comment by Thomas-Gelf** [comment]
Restore is now fine, we should address this.

**Comment by Thomas-Gelf** [comment]
NB: delete also takes place, what's missing is the restore button
