### ISSUE TITLE
[dev.icinga.com #13325] Make fields from service Object available at host where service is assigned without need to add the fields to host templates

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#626]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13325

**Created by shoenscheid on 2016-11-25 09:28:37 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-11-25 10:23:20 +00:00 (in Redmine)_

---

Currently a service check and the corresponding fields/vars for a check are assigned the following way:

command -&gt; service template -&gt; apply rule
host template -&gt; host object

if I want to assign a different value just for one host, I have currently 3 solutions:

1) write an apply rule, just matching the host (means the other applies do not match this one)
2) add the service directly to the host object
3) use a general apply, add the fields to the host template and set the different values to this host.

Lets have a look at case 3:

This is the solution, which is close to icinga2 best practice. But the problem is, the fields will be visible at every host, which has the corresponding template assigned. Alternatively I need to stack templates with different fields, which is complex.
I would really like to see the feature to assign fields/vars to specific hosts only. that would stop blowing up hosts with unnecessary fields and implement the best practice

---

**Relations**:

* duplicates [#13068](https://dev.icinga.com/issues/13068)

**Comment by Thomas-Gelf** [comment]
[Director v1.3.0](https://github.com/Icinga/icingaweb2-module-director/releases/tag/v1.3.0) has been tagged and should provide what you have been asking for. No more need for so many templates, you can override single service properties at a host level, even when that service derives from an apply rule.
