### ISSUE TITLE
[dev.icinga.com #13335] Modify Hosts using multiple Import sources/Sync rules

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#627]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13335

**Created by friesoft on 2016-11-27 23:15:01 +00:00**

Assignee: _friesoft_
Status: _Feedback_ 
Target Version: _(none)_
Last Update: _2016-11-27 23:32:31 +00:00 (in Redmine)_

---

We have one MySQL database containing all our hosts and services. We want to have all the information what to monitor in the Host configuration - this allows us to see everything in one place and apply services using "apply for" rules making the process of adding new services really clean (just a one liner in the custom var).

As it is currently not possible to have multiple Import sources modifying the same hosts we are facing the problem that the SQL statement for importing all hosts including services is already hundreds of lines long, using tons of subselects and therefore isn't really readable/maintainable anymore.

Our preferred way would be multiple import sources/sync rules:

-   Import Source 1: Import Hosts (just the host with address, description, groups, ...)
-   Import Source 2: Apache Instances (modifies the host by adding/modifying the custom var containing all apache instances)
-   Import Source 3: Tomcat Instances (modifies the host by adding/modifying the custom var containing all tomcat instances)

If this is already possible I must apologize but then it wasn't really obvious for me.
Last time I tried the second import source (+sync) removed either all the hosts imported using import source 1 or those manually created.

**Comment by friesoft** [comment]
Using multiple import sources with one sync rule works for me :) This can be closed.
