### ISSUE TITLE
[dev.icinga.com #13347] Invalid deployment log query

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#630]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13347

**Created by mfrosch on 2016-11-28 15:56:32 +00:00**

Assignee: _mfrosch_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-11-28 15:56:32 +00:00 (in Redmine)_

---

Seems to happen when nothing has been deployed yet.

Noticed on PostgreSQL...

    SELECT director_deployment_log.* FROM director_deployment_log WHERE (id = '')

**Comment by Thomas-Gelf** [comment]
I roughly remember this being fixed. In case you can reproduce this, please let me know.

**Comment by VerosK** [comment]
The issue is still present on clean Icinga Director installation ( Director 1.4.3, IcingaWeb2 2.5.1, Icinga 2.8.2-1, PostgreSQL 10). However it disappears after first deploy.

**Comment by entrop-tankos** [comment]
Still present
`root@icinga01 ~ # icingacli module list
MODULE         VERSION   STATE     DESCRIPTION
consul         1.0.0     enabled   Consul module for Icinga Web 2
director       1.11.6    enabled   Director - Config tool for Icinga 2
icingadb       1.1.4     enabled   Icinga DB Web
incubator      0.23.0    enabled   Incubator provides bleeding-edge libraries
`
