### ISSUE TITLE
[dev.icinga.com #13349] can't set custom properties on servicesets

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#631]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13349

**Created by crashbuggy on 2016-11-29 01:05:21 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-11-29 01:05:21 +00:00 (in Redmine)_

---

Hi,

I have a serviceset that contains a load service,
I've created datafeilds procs\_critical and procs\_warning

if I navigate to Icinga Director -&gt; Hosts -&gt; blah.com -&gt; Services -&gt; Centos (the name of the serviceset)
the url being director/hosts\#!/director/serviceset?name=Centos&host=blah.com

I see a form with procs\_critical and procs\_warning
if I fill in some values and hit store, I get a red box with

    Storing icinga_service_set[] failed: SQLSTATE[23000]: Integrity constraint violation: 
      1048 Column 'object_name' cannot be null, query was: 
      UPDATE icinga_service_set SET object_name = ? WHERE (id = '10') {array ( 'id' => '10', 'host_id' => '30', 'object_name' => NULL, 'object_type' => 'object', 'description' => NULL, 'assign_filter' => NULL, )} (DbObject.php:763)

**Comment by Thomas-Gelf** [comment]
I removed this feature for now. Service Sets changed over time, formerly you have been allowed to set common fields, now you're able to set all properties when adding services to the set - and there are overrides at a host level. As the mentioned feature (also set vars on a Set level) is no longer provided in the GUI, I'll close this issue.

Thanks,
Thomas
