### ISSUE TITLE
[dev.icinga.com #13391] How do I setup nrpe service templates?

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#638]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13391

**Created by mbassett on 2016-12-02 20:41:22 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-12-13 19:40:16 +00:00 (in Redmine)_

---

I attempted to build a check-via-nrpe service that i could use to run multiple kinds of nrpe checks. I built the fields and tried to replicate the nrpe imported service as closely as i could and applied this to nodes. I tried using the $HOSTADDRESS$ macro but when the check tried to execute it claimed there was no such macro even though icinga2 docs say that macro should be present everywhere. I tried several ways to get it to work and ended up deleting all my work. What is the correct way to do this?

director imported the existing nrpe service from icinga2 core api but i'm not sure really how to use this.

object CheckCommand "nrpe" {
import "plugin-check-command"
command = \[ PluginDir + "/check\_nrpe" \]
timeout = 5m
arguments += {
"-4" = {
description = "Use IPv4 connection"
set\_if = "$nrpe\_ipv4$"
}
"-6" = {
description = "Use IPv6 connection"
set\_if = "$nrpe\_ipv6$"
}
"-H" = "$nrpe\_address$"
"-a" = {
order = 1
repeat\_key = false
value = "$nrpe\_arguments$"
}
"-c" = "$nrpe\_command$"
"-n" = {
description = "Do not use SSL."
set\_if = "$nrpe\_no\_ssl$"
}
"-p" = "$nrpe\_port$"
"-t" = "$nrpe\_timeout$"
"-u" = {
description = "Make socket timeouts return an UNKNOWN state instead of CRITICAL"
set\_if = "$nrpe\_timeout\_unknown$"
}
}
vars.check\_address = {
type = "Function"
}
vars.check\_ipv4 = "$nrpe\_ipv4$"
vars.check\_ipv6 = "$nrpe\_ipv6$"
vars.nrpe\_address = "$check\_address$"
vars.nrpe\_no\_ssl = false
vars.nrpe\_timeout\_unknown = false
}

**Comment by mbassett** [comment]
This can be closed.

**Comment by Thomas-Gelf** [comment]
Thanks! Just curious, have you been able to figure out how it works - or did you opt for the Agent instead?

**Comment by mbassett** [comment]
I went with icinga agent instead.  My issue was with the NRPE version installed in centos

**Comment by ktella** [comment]
I had similiar issue with passing argument to nrpe. I workaround the issue.

More details here.
https://github.com/Icinga/icinga2/issues/4979

http://serverfault.com/questions/702586/error-with-using-nrpe-with-icinga2
