### ISSUE TITLE
[dev.icinga.com #13533] Cannot delete a command

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#646]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13533

**Created by dzalewski on 2016-12-12 14:40:06 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-12-12 14:40:06 +00:00 (in Redmine)_

---

I cannot delete a command if its being used by a service in a service set. That's fair enough but it would be nice if there was a more human friendly :) warning saying why I cannot delete it e.g. "Command X is being used in template/service set X."

    SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails ("director"."icinga_service", CONSTRAINT "icinga_service_check_command" FOREIGN KEY ("check_command_id") REFERENCES "icinga_command" ("id") ON UPDATE CASCADE), query was: DELETE FROM icinga_command WHERE (id = '197')

    #0 /usr/share/icingaweb2/library/vendor/Zend/Db/Statement.php(297): Zend_Db_Statement_Pdo->_execute(Array)
    #1 /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Abstract.php(470): Zend_Db_Statement->execute(Array)
    #2 /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Pdo/Abstract.php(232): Zend_Db_Adapter_Abstract->query('DELETE FROM ici...', Array)
    #3 /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Abstract.php(652): Zend_Db_Adapter_Pdo_Abstract->query('DELETE FROM ici...')
    #4 /usr/share/icingaweb2/modules/director/library/Director/Data/Db/DbObject.php(791): Zend_Db_Adapter_Abstract->delete('icinga_command', 'id = '197'')
    #5 /usr/share/icingaweb2/modules/director/library/Director/Data/Db/DbObject.php(913): Icinga\Module\Director\Data\Db\DbObject->deleteFromDb()
    #6 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/DirectorObjectForm.php(659): Icinga\Module\Director\Data\Db\DbObject->delete()
    #7 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/DirectorObjectForm.php(609): Icinga\Module\Director\Web\Form\DirectorObjectForm->deleteObject(Object(Icinga\Module\Director\Objects\IcingaCommand))
    #8 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/QuickForm.php(451): Icinga\Module\Director\Web\Form\DirectorObjectForm->onRequest()
    #9 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/QuickForm.php(463): Icinga\Module\Director\Web\Form\QuickForm->setRequest(Object(Icinga\Web\Request))
    #10 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/QuickForm.php(323): Icinga\Module\Director\Web\Form\QuickForm->getRequest()
    #11 /usr/share/icingaweb2/modules/director/library/Director/Web/Controller/ObjectController.php(167): Icinga\Module\Director\Web\Form\QuickForm->handleRequest()
    #12 /usr/share/icingaweb2/modules/director/library/Director/Web/Controller/ObjectController.php(105): Icinga\Module\Director\Web\Controller\ObjectController->editAction()
    #13 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Director\Web\Controller\ObjectController->indexAction()
    #14 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('indexAction')
    #15 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
    #16 /usr/share/php/Icinga/Application/Web.php(384): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
    #17 /usr/share/php/Icinga/Application/webrouter.php(109): Icinga\Application\Web->dispatch()
    #18 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...')
    #19 {main}

</pre>

**Comment by DisSsha** [comment]
Hi ,
I had the same problem when you name a command in the director with the same of an external command.
Director make a mapping between the external command and you can't remove it anymore + you can't deploy again due to duplicate command.

**Comment by Thomas-Gelf** [comment]
In case you manually removed manually created (or shipped) command definition in your plaintext Icinga 2 configuration (and restarted Icinga) just re-trigger **Kickstart** in your Director, like when adding additional master or satellite nodes. It will then re-sync objects and should delete obsolete ones.

**Comment by Thomas-Gelf** [comment]
(you can find the **Kickstart Wizard** when going to **Icinga Infrastructure** on your Director's main dashboard)

**Comment by DisSsha** [comment]
Yes I know, thanks for that tips.
I managed that issue with some delete commands directly on the icinga director DB. :)
I was on the Icinga Camp Berlin & I spoke with you after the Director speech. Now the test is nearly over and I will make a fresh install and I will remove all configuration shipped by icinga2 package to have everything managed by the director. That tool is super awesome :)

**Comment by Thomas-Gelf** [comment]
Glad to hear that :-) I'll leave this issue open, as it's main message is:

> [..] it would be nice if there was a **more human friendly** [..]

As a user you shouldn't be required to know what foreign key constraints are to decipher an error message.

**Comment by Thomas-Gelf** [comment]
Fixed with #1443, #335 and #1480
