### ISSUE TITLE
[dev.icinga.com #13559] Agend Configuration Script, make Variable ICINGA2_PARENT_ENDPOINTS an Array

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#651]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13559

**Created by shoenscheid on 2016-12-14 09:17:05 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-12-14 09:17:05 +00:00 (in Redmine)_

---

To allow the configuration of Agents with Multiple Master nodes, the Variable ICINGA2\_PARENT\_ENDPOINTS should be able to take multiple values, an array would be a good type here.

./confagent.sh: line 10: icinga02d100.dev.example.com: command not found

check: icinga2 installed - OK

1 \#!/bin/bash
2
3 \# This generates and signs your required certificates. Please do not
4 \# forget to install the Icinga 2 package and your desired monitoring
5 \# plugins first:
6
7 ICINGA2\_NODENAME='icinga-client03d100.dev.example.com'
8 ICINGA2\_CA\_TICKET='55e96ca2d40d9c9be3ef59c5fcaeea70df3a1e7c'
9 ICINGA2\_PARENT\_ZONE='master'
10 ICINGA2\_PARENT\_ENDPOINTS='icinga01d100.dev.example.com', 'icinga02d100.dev.example.com'
11 ICINGA2\_CA\_NODE='icinga01d100.dev.example.com'
12 \# Make sure icinga2 is installed and running

**Comment by mens** [comment]
I submitted a pull request #881 to fix this problem

**Comment by Thomas-Gelf** [comment]
This should have been fixed with v1.5.0
