### ISSUE TITLE
[dev.icinga.com #13595] Hosts with host group defined broken in webui.

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#659]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13595

**Created by aross on 2016-12-14 21:37:54 +00:00**

Assignee: _tgelf_
Status: _Resolved_  (closed on _2016-12-14 21:50:00 +00:00_)
Target Version: _1.3.0_
Last Update: _2016-12-14 21:50:00 +00:00 (in Redmine)_

---

After a recent update, hosts with a defined host group cannot be selected in the webui.

The following error is displayed.

    Argument 2 passed to Icinga\Module\Director\Data\Db\DbObject::load() must be an instance of Icinga\Module\Director\Data\Db\DbConnection, null given, called in /opt/data/www/icingaweb2/modules/director/library/Director/Objects/IcingaObjectGroups.php on line 182 and defined

    #0 /opt/data/www/icingaweb2/modules/director/library/Director/Data/Db/DbObject.php(1036): Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(4096, 'Argument 2 pass...', '/opt/data/www/i...', 1036, Array)
    #1 /opt/data/www/icingaweb2/modules/director/library/Director/Objects/IcingaObjectGroups.php(182): Icinga\Module\Director\Data\Db\DbObject::load('Database', NULL)
    #2 /opt/data/www/icingaweb2/modules/director/library/Director/Objects/IcingaObjectGroups.php(163): Icinga\Module\Director\Objects\IcingaObjectGroups->add('Database', 'fail')
    #3 /opt/data/www/icingaweb2/modules/director/library/Director/Objects/IcingaObjectGroups.php(129): Icinga\Module\Director\Objects\IcingaObjectGroups->add(Array)
    #4 /opt/data/www/icingaweb2/modules/director/library/Director/Objects/IcingaObject.php(997): Icinga\Module\Director\Objects\IcingaObjectGroups->set(Array)
    #5 /opt/data/www/icingaweb2/modules/director/library/Director/Data/Db/DbObject.php(305): Icinga\Module\Director\Objects\IcingaObject->setGroups(Array)
    #6 /opt/data/www/icingaweb2/modules/director/library/Director/Objects/IcingaObject.php(649): Icinga\Module\Director\Data\Db\DbObject->set('groups', Array)
    #7 /opt/data/www/icingaweb2/modules/director/library/Director/Data/Db/DbObject.php(401): Icinga\Module\Director\Objects\IcingaObject->set('groups', Array)
    #8 /opt/data/www/icingaweb2/modules/director/library/Director/Objects/IcingaObject.php(592): Icinga\Module\Director\Data\Db\DbObject->setProperties(Array)
    #9 /opt/data/www/icingaweb2/modules/director/library/Director/Data/Db/DbObject.php(950): Icinga\Module\Director\Objects\IcingaObject->setProperties(Array)
    #10 /opt/data/www/icingaweb2/modules/director/library/Director/Objects/IcingaObject.php(2363): Icinga\Module\Director\Data\Db\DbObject::create(Array, NULL)
    #11 /opt/data/www/icingaweb2/modules/director/library/Director/Web/Form/IcingaObjectFieldLoader.php(224): Icinga\Module\Director\Objects\IcingaObject::fromPlainObject(Object(stdClass))
    #12 /opt/data/www/icingaweb2/modules/director/library/Director/Web/Form/IcingaObjectFieldLoader.php(189): Icinga\Module\Director\Web\Form\IcingaObjectFieldLoader->removeFilteredFields(Array)
    #13 /opt/data/www/icingaweb2/modules/director/library/Director/Web/Form/IcingaObjectFieldLoader.php(37): Icinga\Module\Director\Web\Form\IcingaObjectFieldLoader->attachFieldsToForm(Object(Icinga\Module\Director\Forms\IcingaHostForm))
    #14 /opt/data/www/icingaweb2/modules/director/library/Director/Web/Form/DirectorObjectForm.php(340): Icinga\Module\Director\Web\Form\IcingaObjectFieldLoader->addFieldsToForm(Object(Icinga\Module\Director\Forms\IcingaHostForm))
    #15 /opt/data/www/icingaweb2/modules/director/library/Director/Web/Form/DirectorObjectForm.php(634): Icinga\Module\Director\Web\Form\DirectorObjectForm->addFields()
    #16 /opt/data/www/icingaweb2/modules/director/library/Director/Web/Form/QuickForm.php(451): Icinga\Module\Director\Web\Form\DirectorObjectForm->onRequest()
    #17 /opt/data/www/icingaweb2/modules/director/library/Director/Web/Form/QuickForm.php(463): Icinga\Module\Director\Web\Form\QuickForm->setRequest(Object(Icinga\Web\Request))
    #18 /opt/data/www/icingaweb2/modules/director/library/Director/Web/Form/QuickForm.php(323): Icinga\Module\Director\Web\Form\QuickForm->getRequest()
    #19 /opt/data/www/icingaweb2/modules/director/library/Director/Web/Controller/ObjectController.php(167): Icinga\Module\Director\Web\Form\QuickForm->handleRequest()
    #20 /opt/data/www/icingaweb2/modules/director/application/controllers/HostController.php(51): Icinga\Module\Director\Web\Controller\ObjectController->editAction()
    #21 /opt/data/www/icingaweb2/modules/director/library/Director/Web/Controller/ObjectController.php(105): Icinga\Module\Director\Controllers\HostController->editAction()
    #22 /opt/data/www/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Director\Web\Controller\ObjectController->indexAction()
    #23 /opt/data/www/icingaweb2/library/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('indexAction')
    #24 /opt/data/www/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
    #25 /opt/data/www/icingaweb2/library/Icinga/Application/Web.php(384): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
    #26 /opt/data/www/icingaweb2/library/Icinga/Application/webrouter.php(109): Icinga\Application\Web->dispatch()
    #27 /opt/data/www/icingaweb2/public/index.php(4): require_once('/opt/data/www/i...')
    #28 {main}

</pre>
Broken host

    {
        "address": "192.168.114.86",
        "display_name": "db03",
        "groups": [
            "Database"
        ],
        "imports": [
            "generic-linux-template"
        ],
        "object_name": "db03",
        "object_type": "object",
    }

Working host

    {
        "address": "192.168.114.186",
        "display_name": "db02",
        "imports": [
            "generic-linux-template"
        ],
        "object_name": "db02",
        "object_type": "object"
    }

**Comment by plattimer74** [comment]
Problem seems to still exist in 1.3.0
nformation/cli: Icinga application loader (version: v2.6.0)
information/cli: Loading configuration file(s).
information/ConfigItem: Committing config item(s).
information/ApiListener: My API identity: pu0991nicm0001.netmon.det.nsw.edu.au
critical/config: Error: Validation failed for object 'paul' of type 'HostGroup'; Attribute 'zone': Object 'director-global' of type 'Zone' does not exist.
Location: in [stage]/zones.d/director-global/hostgroups.conf: 1:0-1:22
[stage]/zones.d/director-global/hostgroups.conf(1): object HostGroup "paul" {
                                                    ^^^^^^^^^^^^^^^^^^^^^^^
[stage]/zones.d/director-global/hostgroups.conf(2):     assign where host.check_interval == "60"
[stage]/zones.d/director-global/hostgroups.conf(3): }

critical/config: 1 error

**Comment by Thomas-Gelf** [comment]
Hi @plattimer74,

as far as it goes to your last shown error, I bet you missed the first step in our [getting started](https://github.com/Icinga/icingaweb2-module-director/blob/master/doc/04-Getting-started.md#define-a-new-global-zone) documentation ;-)

Also, this seems in no way related to the original issue, which shows a completely different error message.

Cheers,
Thomas
