### ISSUE TITLE
[dev.icinga.com #13625] Sync: do not artificially limit available memory

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#665]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13625

**Created by tgelf on 2016-12-15 17:40:42 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-12-15 17:40:42 +00:00 (in Redmine)_

---

We currently limit ourselves, even with more memory assigned in the php.ini

**Comment by saikrishnagaddipati** [comment]
I am getting the below error when i do a puppetDB sync in Icinga director. Below is the error which is displayed in the IcingaWeb UI. 
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 32 bytes) in /usr/share/icingaweb2/modules/puppetdb/library/Puppetdb/PuppetDbApi.php on line 184


Is my error related to the above issue?

**Comment by Thomas-Gelf** [comment]
@saikrishnagaddipati: blind guess: no, your error happens at an earlier stage. Please try to raise the memory_limit in your php.ini and reload your web server.

**Comment by saikrishnagaddipati** [comment]
Hi Thomas, I am getting the below error even after increasing the memory_limit to 5G in php.ini.

Fatal error: Maximum execution time of 30 seconds exceeded in /usr/share/icingaweb2/modules/puppetdb/library/Puppetdb/PuppetDbApi.php on line 297

any suggestions?

**Comment by Thomas-Gelf** [comment]
This should have been fixed on day after v1.4.0, will be released with v1.5.0
