### ISSUE TITLE
[dev.icinga.com #13663] Adding a service after adding a service set

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#669]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13663

**Created by Finn on 2016-12-19 09:58:32 +00:00**

Assignee: _tgelf_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-12-19 13:25:16 +00:00 (in Redmine)_

---

Hello,

this is just a minor annoyence.
If you add a service set to a host, in the director, the panel goes to the service sets services instead of going to the hosts services.
This made me add the service to the service set a few times now.
It would be more Intuitive, in my opinion, if the panel switches back to the host so you can continue adding services.

Greetings,
Finn

**Comment by Thomas-Gelf** [comment]
This has been fixed.
