### ISSUE TITLE
[dev.icinga.com #13681] Can't apply Schema update 127

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#671]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13681

**Created by Zriel on 2016-12-19 15:16:47 +00:00**

Assignee: _Zriel_
Status: _Feedback_ 
Target Version: _(none)_
Last Update: _2017-01-10 17:01:02 +00:00 (in Redmine)_

---

I got this message with the latest update. I'm in the latest GIT version. Applied one of the updates of the latest "broken" gits with issues on the sql schemas.

"Migration 127 failed (SQLSTATE\[42S21\]: Column already exists: 1060 Duplicate column name 'checksum') while running ALTER TABLE icinga\_command\_var ADD COLUMN checksum VARBINARY (20) DEFAULT NULL AFTER command\_id, ADD INDEX search\_idx (varname), ADD INDEX checksum (checksum)"

Would show gratitude for a fix or how to solve this.

Thanks in advance

**Comment by Thomas-Gelf** [comment]
Glad that it worked. I'll come back to this in case anyone else comes up with this issue. Didn't have a similar report so far.

Thanks,
Thomas
