### ISSUE TITLE
[dev.icinga.com #13697] Make permission director/admin visible

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#676]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13697

**Created by bsheqa on 2016-12-20 10:33:42 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-12-20 10:33:42 +00:00 (in Redmine)_

---

This permission is not listed in Icinga Web 2 permission set but it exists and is important.
In my scenario I want to give access to a user to everything related to Director but not the API.

**Comment by Thomas-Gelf** [comment]
@bobapple, in case you're still interested in this feature: `director/*` is what you're looking for. `director/admin` is for internal purposes only and will not be exposed in the foreseeable future.

Cheers,
Thomas

**Comment by bobapple** [comment]
Wouldn't `director/*` also allow access to the Director API?

**Comment by Thomas-Gelf** [comment]
Sorry, I missed that point. Yes, it does. Still, `director/admin` would not help here, exposing it wouldn't work as expected. In Icinga Web 2 it is currently not possible to grant `module/*` but not `module/specialperm`. When creating a special admin role without one specific permission I fear the next one could ask for an admin with all permissions, but without `director/deployment` - and so on.

This could be tackled by splitting up `director/admin` into more and more smaller dedicated permissions, something that is going to happen anyways over time. `director/admin` can be seen as an internal placeholder for any permission that might be added in future but does not already exist. Out of curiosity, what's the use-case for your example? If I'm not allowed to use the REST API I can still write my dedicated crawler or so and achieve the same when being an admin. Help me understand your needs, eventually I can come up with another solution.

**Comment by bobapple** [comment]
I came up with this while building the [online demo](https://www.icinga.com/products/demo/). I wanted to allow the users to use everything except the API.
