### ISSUE TITLE
[dev.icinga.com #13705] mass deletion of hosts

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#677]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13705

**Created by tpiet on 2016-12-20 17:56:50 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-12-20 17:56:50 +00:00 (in Redmine)_

---

Hi,

would it be possible to add a feature to select multiple hosts and delete them in one step?
Currently with director v1.2.0. after selecting multiple hosts delete button is shown but pressing on delete does not delete the hosts.

BR
Thomas

**Comment by cbnorman** [comment]
this would be really helpful after screwing up an import rule

**Comment by leegarrett** [comment]
Not wanting to grave dig, but could this also be added for hostgroups, host templates and choices?
