### ISSUE TITLE
[dev.icinga.com #13711] Make Deployment Status available via API

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#679]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13711

**Created by shoenscheid on 2016-12-21 10:33:11 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-12-22 08:45:28 +00:00 (in Redmine)_

---

It would be great to have an API Call, which allows to monitor the current/latest deployment status. E.g. in Setups where multiple Admins and Users work together

**Comment by Thomas-Gelf** [comment]
Has been implemented with #2187
