### ISSUE TITLE
[dev.icinga.com #13719] Failed to create new user groups - Trying to set invalid key zone_id

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#680]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13719

**Created by MonitorJunkie on 2016-12-21 14:37:22 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2017-01-09 22:25:45 +00:00 (in Redmine)_

---

Hallo,

Existing user groups are OK.
I try to create a new user group, but it is not possible.

Error: Trying to set invalid key zone\_id

Trying to set invalid key zone\_id

    #0 /usr/share/icingaweb2/modules/director/library/Director/Objects/IcingaObject.php(649): Icinga\Module\Director\Data\Db\DbObject->set('zone_id', NULL)
    #1 /usr/share/icingaweb2/modules/director/library/Director/Data/Db/DbObject.php(359): Icinga\Module\Director\Objects\IcingaObject->set('zone_id', NULL)
    #2 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/DirectorObjectForm.php(99): Icinga\Module\Director\Data\Db\DbObject->__set('zone_id', NULL)
    #3 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/DirectorObjectForm.php(623): Icinga\Module\Director\Web\Form\DirectorObjectForm->object().

.

MonitorJunkie

**Attachments**

* [2016-12-21 12_15_22-Icinga Usergroups.jpg](https://dev.icinga.com/attachments/download/3963/2016-12-21%2012_15_22-Icinga%20Usergroups.jpg) MonitorJunkie - _2016-12-21 14:33:54 +00:00_
* [Bildschirmfoto 2016-12-22 um 17.04.04.png](https://dev.icinga.com/attachments/download/3973/Bildschirmfoto%202016-12-22%20um%2017.04.04.png) Markus - _2016-12-22 16:04:40 +00:00_

**Comment by SimonHoenscheid** [comment]
I was hit by this issue today

**Comment by Exkudor** [comment]
Seconded, also ran into this issue with my new Installation today.

Icinga2 v2.4.3
Icingaweb2 v2.4.0
Director v1.3.0

**Comment by nicolinux** [comment]
Hi, I am using this Icinga2 docker image:
https://hub.docker.com/r/jordan/icinga2/

Is there a way around this issue without updating to the latest version? Where is the difference between using the cli and editing /etc/icinga2/conf.d/users.conf?

The reason I am asking is because even though the Icinga Director is praised as the best solution to configure Icinga2, having to configure via the cli _and_ the director is super darn confusing and very user unfriendly :(
