### ISSUE TITLE
[dev.icinga.com #13731] Command Templates skip_key behavior of arguments

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#682]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13731

**Created by shoenscheid on 2016-12-22 11:14:03 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-12-22 11:14:03 +00:00 (in Redmine)_

---

if I define an argument and want the key to be skipped, I need to leave the argument name empty. That becomes a problem if you defined a name first, and want to remove it afterwards. Director will trow an error. the other problem is, if you have multiple args like these. you have multiple args without a name. I suggest to add a field to director where to choose skip key behavior like we did for repeat key.

**Comment by psi-4ward** [comment]
Same here:

```
Storing icinga_command_argument[668] failed: SQLSTATE[23000]: 
Integrity constraint violation: 1048 Column 'argument_name' cannot be null, query was: 

UPDATE icinga_command_argument 
SET argument_name = ? 
WHERE (id = '668') 

{array ( 'id' => '668', 'command_id' => '71', 'argument_name' => NULL, 'argument_value' => '$http_url$', 'argument_format' => 'string', 'key_string' => NULL, 'description' => NULL, 'skip_key' => NULL, 'set_if' => NULL, 'sort_order' => '1000', 'repeat_key' => NULL, 'set_if_format' => 'string', 'required' => 'y', )} 

(DbObject.php:755)
```

**Comment by Thomas-Gelf** [comment]
Workaround for now: delete the argument and add a new one. I'm sure that after three times you learn to think first and create the argument afterwards ;-) Just kidding, I know this is sometimes nasty - should be fixed.
