### ISSUE TITLE
[dev.icinga.com #13759] Custom Variables + Service Apply + Macro/Expression issue

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#685]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13759

**Created by mdetrano on 2016-12-23 22:13:10 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-12-23 22:13:10 +00:00 (in Redmine)_

---

I noticed that custom variables setup for Service Apply rules (and those created for Services on Host Templates), will have the expression rendered when rendering the object definition.

So a parameter like -- MYVAR : Foo $BAR$

is written out like:

vars.MYVAR = "Foo " + BAR

This only happens for service applies...it does not happen for services created directly on a host. (in that case, the variable is rendered like : MYVAR = "Foo $BAR$" , and the macro works as expected).

In the renderCustomVars function in IcingaObject, this seems to be the intended setup:

return $this~~<span style="text-align:right;">vars()</span>~~&gt;toConfigString($this~~<span style="text-align:right;">isApplyRule()); &lt;-</span>~~ when isApplyRule is true, toConfigString renders the expression.

but I am wondering if it is really supposed to be that way (and only for Apply rules).

For me, it is more useful to have the macro passed through so the command can evaluate it later.

Attaching "diff" which works around the problem.

**Attachments**

* [apply_custom_vars_issue.diff](https://dev.icinga.com/attachments/download/3979/apply_custom_vars_issue.diff) mdetrano - _2016-12-23 22:12:31 +00:00_

**Comment by mdetrano** [comment]
Note:  I suspect this IS needed when doing an Apply For and want to use "$config$" in a variable assignment.  Perhaps there is a way to not render the expression for other macros, but do extract expression for config and {object}.{var} variables.
