### ISSUE TITLE
[dev.icinga.com #13813] "Modify" action link for services

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#689]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13813

**Created by seferovic on 2016-12-28 15:07:16 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-12-28 15:07:16 +00:00 (in Redmine)_

---

Hi!

While presenting Icinga Director to my team (feedback was great btw ;-)) a colleague of mine suggested that it would be great if he could modify the threshold values directly in the Icinga Web 2 (instead of going back to Icinga Director and having to select host and service afterwards).

There is a "modify" action link for the host object:
https://www.icinga.com/demo/monitoring/host/show?host=localhost#!/demo/director/host/edit?name=localhost

Would it be possible to add a modify action link for the service as well?
https://www.icinga.com/demo/director/hosts#!/demo/director/service?name=Swap&host=localhost

**Comment by Thomas-Gelf** [comment]
This Link should be shown for every service and point to an intermediary page. That page should then figure out whether and how this Service has been created be the Director. Then it should either redirect to the right place or show a friendly message. Missing permissions should be handled gracefully.

**Comment by Thomas-Gelf** [comment]
Intermediary page works fine, this is how it looks like when a service cannot be found:

![director_service_modify_not_found](https://user-images.githubusercontent.com/553008/40364021-7c5640b0-5dd1-11e8-827f-eba5447ffe78.png)

In case the master is reachable this could also be improved by showing information regarding the related local configuration file for Object not deployed by the Director (like "Inspect" does).
