### ISSUE TITLE
[dev.icinga.com #13823] Mandatory fields now enforced, but "no" is no answer?

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#690]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13823

**Created by spillerm on 2016-12-29 08:38:07 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-12-29 09:17:30 +00:00 (in Redmine)_

---

Hi,

I created a data field, and its data type is "boolean". I'd like to apply by assign rule (... where host.vars.datafield == true), and my datafield is mandatory: I explicitly make a choice whether this data field is true or false.

But when I choose "No" AND the field is mandatory, it's not going to be accepted ("Value is required and can't be empty").

For me, this is a bug - false != empty :)

What do you think?

Cheers,
Marianne

**Comment by Thomas-Gelf** [comment]
Fixed in `next`.
