### ISSUE TITLE
[dev.icinga.com #13837] Does DirectorOverrideTemplate break my service?

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#691]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13837

**Created by spillerm on 2016-12-30 08:41:55 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-12-30 09:07:50 +00:00 (in Redmine)_

---

Hi,

I try to move a working service from config files to director. In config files, it looks like this:

    apply Service "nfs-server" {
      import "generic-nrpe"
      display_name = "NFSv4 Server Health"

      check_command = "nrpe"
      vars.nrpe_command = "check_nfs4"
      groups = [ "nfs" ]

      assign where host.vars.nfs_server == true
    }

So I click around in director, and "Preview" gives me a service like this (zones.d/director-global/service\_apply.conf):

    apply Service "nfs-server" {
        import "generic-nrpe"

        assign where host.vars.nfs_server == "true"
        groups = [ "nfs" ]
        vars.nrpe_command = "check_nfs4"

        import DirectorOverrideTemplate
    }

The only difference I see is "import DirectorOverrideTemplate" and these "" around true; but while my config file service matches several hosts, this director service matches nowhere (disabled config file and then deployed director service).

So what is DirectorOverrideTemplate, and can it cause this?

Cheers,
Marianne

**Comment by Thomas-Gelf** [comment]
I created #729 for the 'true / is set' operator and will close this issue. The rest should work fine as long as the data types match.

Cheers,
Thomas
