### ISSUE TITLE
[dev.icinga.com #13905] Float is not accepted as "Number" data type

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#697]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13905

**Created by tobiasvdk on 2017-01-07 21:03:41 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2017-01-07 21:03:41 +00:00 (in Redmine)_

---

Setting the data type "Number" only allows integers to be assigned but not float.

**Comment by tobiasvdk** [comment]
Duplicates #307.
