### ISSUE TITLE
[dev.icinga.com #13909] Allow to override non-variable parameters of templates in derived objects

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#698]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13909

**Created by greatexpectations on 2017-01-09 10:05:26 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2017-01-09 10:05:26 +00:00 (in Redmine)_

---

We often have to change individual "non-variable" parameters (e.g. not vars.xxx, but things like check\_interval, retry\_interval etc.) for individual host and service objects. Unfortunately it is not currently possible in Director to edit these fields directly; instead we have to create template objects for them. This leads to a unmanageable catalog of templates.

Would it be possible to overcome this by modifying the DirectorOverrideTemplate such that at least the most frequently needed "non-variable" properties could be made editable in Director?

Something along the line of...

if (vars) {
if(host.vars\[DirectorOverrideVars\]\["check\_interval"\]) {
check\_interval = host.vars\[DirectorOverrideVars\]\["check\_interval"\]
}
if(host.vars\[DirectorOverrideVars\]\["retry\_interval"\]) {
check\_interval = host.vars\[DirectorOverrideVars\]\["check\_interval"\]
}
...
vars += host.vars\[DirectorOverrideVars\]\[name\]
} else {
vars = host.vars\[DirectorOverrideVars\]\[name\]
}

Kind regards

**Comment by Thomas-Gelf** [comment]
Will be shipped with #899.
