### ISSUE TITLE
[dev.icinga.com #13915] 'in' operator wrongly been rendered as '=='

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#699]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13915

**Created by ventura10 on 2017-01-09 11:58:14 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2017-01-09 12:05:09 +00:00 (in Redmine)_

---

I have found this error when I tried to create a new hostgroup, but it may exists in other locations.

If you use the 'in' operator, you **expect** a rendered config like:

object HostGroup "VM" {
assign where host.name **in** \["server1","server2"\]
}

But actually you **wrongly** get:

object HostGroup "VM" {
assign where host.name **<span style="text-align:center;">=</span>** \["server1","server2"\]
}

**Attachments**

* [array-in-assignment-fix.patch](https://dev.icinga.com/attachments/download/4013/array-in-assignment-fix.patch) ventura10 - _2017-01-09 12:02:34 +00:00_

**Comment by Thomas-Gelf** [comment]
Should be fixed and tested in current master. In case it doesn't please let us know ;-)
