### ISSUE TITLE
[dev.icinga.com #13931] notification config sync zone choice?

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#700]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13931

**Created by CLXJZam on 2017-01-10 13:50:59 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2017-01-10 13:50:59 +00:00 (in Redmine)_

---

I have a multi-zone installation (icinga 2.6.0), using the native config sync methods [pre-director]()

config =&gt; checker =&gt; satellites

Where "config" is purely for managing the configuration, "checker" is an ha zone that performs the majority of my checks, writes to the IDO and deals with shipping performance stats to influxDB; the satellite zones are due to firewall / geographical / logical separation. Some of these satellite zones will need to be responsible for their own notifications, whereas others it would be preferable to leave to the "checker" zone to manage.

I can configure this all fine "pre-director" using manually maintained config files shipped from the "config" zone, however I would like to find a migration path, as ultimately I'd like to hand over the tweaking of configuration to others (who are happier with a web GUI than a terminal) and also to sync hosts from our CI database / users from our AD etc.

So, the issue is (using director 1.2.0 from git master) that notifications configured via the icingaweb2 director module (resulting in notification\_apply.conf and notification\_templates.conf) end up in /var/lib/icinga2/api/packages/director/fqdn-hash/zones.d/config and never get sync'd down to the "checker" zone (and therefore presumably not to the satellite zones either).

My question therefore is: is there some way of specifying to which zone the notification configuration will be deployed?

**Comment by mbassett** [comment]
You need a director-global zone for the global configuration deployment.

See  https://github.com/Icinga/icingaweb2-module-director/blob/v1.3.0/doc/10-How-it-works.md

**Comment by Thomas-Gelf** [comment]
Thanks @mbassett, that's correct. Allow me to add a small note, `director-global` isn't hardcoded - it can be changed through the form shown at `icingaweb2/director/config/settings`. However, when starting with Director I strongly suggest to stay with the defaults, this makes it easier for other people to help you.

**Comment by mbassett** [comment]
better update your doco then @Thomas-Gelf  =)

**Comment by dnsmichi** [comment]
@mbassett send a PR :-)

**Comment by Thomas-Gelf** [comment]
Well... @mbassett is right :laughing: Just - it wasn't an accident that this settings-page is hard to find. I want people to stick with the defaults unless they better understood how things work :wink:

I'll close this issue, guess @mbassett mentioned all it needs to get started. @CLXJZam: in case you're still facing problems please let us know.

Cheers,
Thomas
