### ISSUE TITLE
[dev.icinga.com #13937] Allow Director to create hostgroups based on how icinga2 does

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#701]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13937

**Created by fireheadman on 2017-01-10 20:14:32 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2017-01-10 20:15:42 +00:00 (in Redmine)_

---

On a fresh build, the icinga master will have definition in the groups.conf of
object HostGroup "linux-servers" {
display\_name = "Linux Servers"

-   assign where host.vars.os == "Linux"
    \*}

....In incinga director, I am unable to create a group and map it to\* host.vars.os\*, var.os is not even an option.
Would like to see director have more flexibility to expand the conditions in "Assign where" section.

Possibly even expand this functionality to other parts of director.

**Comment by Thomas-Gelf** [comment]
This should perfectly work since 1.2.0, but definitively with the latest version. In case it doesn't please let me know and provide some more details.

Thanks,
Thomas

NB: you need to have at least one host with `os` defined, otherwise the property wouldn't show up
