### ISSUE TITLE
[dev.icinga.com #13985] Command fields are not resolved in the service form

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#712]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13985

**Created by tobiasvdk on 2017-01-12 20:27:18 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2017-01-13 08:00:00 +00:00 (in Redmine)_

---

Fields of a command which already have a value assigned are not shows in the service form but not resolved.
Command:
![](director_command_fields_not_resolved_in_service_command)

Service:
![](director_command_fields_not_resolved_in_service)

**Attachments**

* [director_command_fields_not_resolved_in_service.png](https://dev.icinga.com/attachments/download/4043/director_command_fields_not_resolved_in_service.png) tobiasvdk - _2017-01-12 20:24:35 +00:00_
* [director_command_fields_not_resolved_in_service_command.png](https://dev.icinga.com/attachments/download/4045/director_command_fields_not_resolved_in_service_command.png) tobiasvdk - _2017-01-12 20:24:36 +00:00_

**Comment by Thomas-Gelf** [comment]
This should have been in 1.3.0 :disappointed:

**Comment by Thomas-Gelf** [comment]
Please try again
