### ISSUE TITLE
[dev.icinga.com #13989] Pagination: tell about limited page count

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#714]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13989

**Created by tgelf on 2017-01-13 08:43:53 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2017-01-13 08:43:53 +00:00 (in Redmine)_

---

COUNT (\*) on every click when navigating through a huge table is pointless, this is why we introduced "limited limits". Works fine, but the user might not understand what's going on. So the pagination component should somehow provide related hints.

---

**Relations**:

* relates [#13989](https://dev.icinga.com/issues/13989)

**Comment by Thomas-Gelf** [comment]
As far as I remember we lost our limited limits in outta space :p
