### ISSUE TITLE
[dev.icinga.com #13995] Add a field for ignore expression to apply rules

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#715]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13995

**Created by lbetz on 2017-01-13 10:32:01 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2017-01-13 10:32:01 +00:00 (in Redmine)_

---

If you use host templates and apply services to these templates, I'd like a ignore field to set an additional ignore expression for excluding some service.

apply Service .... {
import <service>

assign where <host-template> in host.templates
ignore where ....
}

I also like to use host.temlates into this ignore expression, like

ignore where <host-template> in host.templates

Because so I can use templates only to exclude something. I.e. I have a linux-host template for all linux based agents and I wanna exclude the cluster zone check from all masters are commbined in host template icinga-master.

**Comment by leo90skk** [comment]
I miss the `ignore` feature too. It should not be so difficult to implement. It is next to the same as `assign`, or?

**Comment by Thomas-Gelf** [comment]
@leo90skk: this feature request points to another direction. `ignore` is perfectly possible via `and not`, we just opted for providing just on filter element for the following reasons:
* ease of use. You might be used to `ignore` from your manual configuration, but the average user is mostly confused when provided the choice to assign where VS ignore with both of them allowing deeply nested combinations of and/or/not
* performance. Icinga is much faster to evalue a single deeply nested assign rule than multiple flat ones

The feature request opened by @lbetz targets a very special kind of apply rules, those being automagically rendered when adding a service to a host template. We'll provide a way to go to the single host inheriting that service, click "delete" - and show the service as being deleted (while still being there). Same thing could also be provided for "normal" apply rules. Go to a host, realize that it got applied a service, click "delete", there you go.

Both variants will store that host to kind of a "blacklist". Nothing complicated, but requires some steps. a) schema migration involving new tables, b) GUI changes (show inherited/applied but "deleted" services stroken with the possibility to undo that change and c) adding all blacklisted hosts to the related apply rule as `and not host.name in (...)`.

I'm pretty sure that users will misuse this feature, and someone will end up with a service being applied to 500 hosts with 450 of them blacklisting it, but hey - that's how things go :laughing:

Cheers,
Thomas

**Comment by sysadmama** [comment]
+1 Waiting for this.

**Comment by widhalmt** [comment]
+1 or maybe even +2 or +5 ;-)

**Comment by nunofernandes** [comment]
+1 ..

**Comment by mdeguzis** [comment]
Looking for a solution here as well to bucket odd hosts I have that don't fit in an existing host group.

**Comment by Thomas-Gelf** [comment]
With v1.5.0 this is available via the "blacklist" feature. And of course, extending your filter with AND NOT has always been possible.

**Comment by sinky** [comment]
> With v1.5.0 this is available via the "blacklist" feature. And of course, extending your filter with AND NOT has always been possible.

Does the "AND NOT... " work with the "contains" statement?
The resulting config on my director is this
```assign where "gh_windows and not host.vars.no_service_check" in host.groups```
