### ISSUE TITLE
[dev.icinga.com #14005] CLI Services

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#719]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/14005

**Created by mmittel2 on 2017-01-13 14:39:26 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2017-01-13 14:39:26 +00:00 (in Redmine)_

---

It seems to be impossible to delete Service Objects with the CLI which are created directly to a host.
Plus the creation of a service to a host is quite annoying since I need the host\_id attribute from the database.
For example:
icingacli director service create hi --host\_id 2 --imports web\_http

And last but not least I think a CLI command that returns all services applied to a host (even better if specified by e.g. import) would be quite handy.

Nevertheless thanks a lot for the work done.
Cheers Merlin

**Comment by Thomas-Gelf** [comment]
```
user@web:~$  icingacli director service create hi --host app1 --imports "Dummy Service"
Service 'hi' has been created
user@web:~$  icingacli director service delete hi --host app1
Service 'hi' has been deleted
user@web:~$  icingacli director service create hi --host app1 --imports "Dummy Service"
Service 'hi' has been created
user@web:~$  icingacli director service create hi2 --host app1 --imports "Dummy Service"
Service 'hi2' has been created
user@web:~$  icingacli director service create hi3 --host app1 --imports "Dummy Service"
Service 'hi3' has been created
user@web1:~$  icingacli director service delete hi2 hi3 hi --host app1
Service 'hi2' has been deleted
Service 'hi3' has been deleted
Service 'hi' has been deleted
```
