### ISSUE TITLE
Re-edit hostgroups/ servicegroups forces me to "assign where"

### ISSUE THREAD

**Issue by sysadmama** [Icinga/icingaweb2-module-director#725]
Hi,

my example: I create a service group "webservice" with display name "Websrevices" and store it; everything's fine, but there's a typo. I correct it, and then I can't save my group: "assign where" - "Value is required and can't be empty". But I don't want to assign here :) (Only workaround is completely delete this group and then re-add it. Mpf.) Bug or feature? For me it's a bug.

Cheers,
  Marianne

**Comment by Thomas-Gelf** [comment]
I see, it's a bug. I'll postpone this as there is a feature branch currently going on where those "hard-wired" dropdowns will be replaced with an auto-completion element. This problem will then be gone. It already works here, but is still to hot - so it will not make part of 1.3.0 (which should be tagged within an hour).

Thanks,
Thomas

**Comment by Thomas-Gelf** [comment]
Feature branch has been postponed, but this issue has been fixed.
