### ISSUE TITLE
Service Set matches host but does not appear on hosts services tab  

### ISSUE THREAD

**Issue by SimonHoenscheid** [Icinga/icingaweb2-module-director#727]
The counter on the service set does not count the hosts. See screenshots attached. The Services are Applied to the Hosts.

![bug_icinga_director_service_set_2](https://cloud.githubusercontent.com/assets/4162281/22069987/a579b2e6-dd9a-11e6-810d-584eb75d6097.PNG)
![bug_icinga_director_service_set_3](https://cloud.githubusercontent.com/assets/4162281/22069986/a577c79c-dd9a-11e6-9cfe-59b18dc8f659.PNG)

**Comment by SimonHoenscheid** [comment]
Tested on an other installation. Happens the same way

**Comment by Thomas-Gelf** [comment]
I never was very happy with those counters, as I expected such complaints when I merged that commit. This counts only hosts where this set has been directly assigned. No chance to evaluate apply rules for thousands of hosts every time one clicks that tab.

This depends on #573 and can easily be fixed once we have that feature.

**Comment by Thomas-Gelf** [comment]
Oh, now I see some more detail: in your first screenshot, the left part is what I've been talking about. I did oversee the second screenshot. You're right, currently you see only services from sets that have directly been added to the host (or have been inherited from one of it's templates) - but apply rules for service sets are not even evaluated.

**Comment by Thomas-Gelf** [comment]
The last part could be implemented, I would just have problems to fix the numbers in the left part of the first screenshot. Sadly it's too late for 1.3.0...

**Comment by Thomas-Gelf** [comment]
I'll close this in favor of #735, as that one has screenshots better highlighting the problem. That's the part that can be fixed quickly, the rest has will be solved with #573
