### ISSUE TITLE
Provide an "is set / is true" assignment operator

### ISSUE THREAD

**Issue by Thomas-Gelf** [Icinga/icingaweb2-module-director#729]

**Comment by erezzarum** [comment]
any chance to have it implemented soon :)?

**Comment by mbassett** [comment]
This one is a big issue for me as well.

**Comment by Thomas-Gelf** [comment]
Should fix #339 - instead of using suggested "magic" true/false string detection this should explicitly say "is true (or set)". So someone could also say "where host.address is true (or set)" - and it should be rendered to `where host.address`.
