### ISSUE TITLE
Schema apply error

### ISSUE THREAD

**Issue by MAngel666** [Icinga/icingaweb2-module-director#730]
with the last git version I get this error if I click on "apply schema migrations"

Migration 104 failed (SQLSTATE[23502]: Not null violation: 7 ERROR: column "range_key" contains null values) while running ALTER TABLE icinga_timeperiod_range ADD COLUMN range_key character varying(255) NOT NULL, ADD COLUMN range_value character varying(255) NOT NULL

**Comment by Thomas-Gelf** [comment]
Seems that you already managed it to insert invalid data (key or value being NULL). This migration from September wants to protect you from this - and now fails to apply the constraint as erroneous data is already there. I'll push a small change deleting those rows for you. Don't worry, they shouldn't be able to do anything useful right now anyways.

**Comment by Thomas-Gelf** [comment]
Please pull and apply the migration again, it should work fine afterwards. Eventually re-check your Timeperiods before deploying again, but I do not expect any issues.

**Comment by MAngel666** [comment]
oh you have done it for mysql... can you make it for postgres to?

**Comment by Thomas-Gelf** [comment]
Sure :dagger:

**Comment by Thomas-Gelf** [comment]
Let's bring the discussion back here. We are seeing two different issues here. I misunderstood the first one, the second one derives from the erroneous fix. Has been reverted, back to the original issue. Problem is that I'm adding a new column with NOT NULL constraint, filling that columns with data in the next query. Just, at the time when the column is added there is no value - and PostgreSQL correctly complains.

Give me a few more minutes...

**Comment by Thomas-Gelf** [comment]
Seems that there is no single-step way in PostgreSQL to get this accomplish, I guess I need to add the column allowing NULLs first, populate it's value, and then ALTER again to make it NOT NULL :scream:

**Comment by Thomas-Gelf** [comment]
Please try again

**Comment by MAngel666** [comment]
yep works! thx for the fast help!

**Comment by Thomas-Gelf** [comment]
You're welcome!
