### ISSUE TITLE
Custom fields are gone in Service Templates after upgrade to 1.3.0

### ISSUE THREAD

**Issue by crsprsp** [Icinga/icingaweb2-module-director#731]
Hello,

after i did the upgrade vom 1.2.0 this morning i found all Service Templates empty from all added data fields. 
How to handle that?

bye, Rico

**Comment by Thomas-Gelf** [comment]
Could you please show me some related screenshot to get a better understanding of what you mean with "empty"? Please show a service form and the related Fields tab.

**Comment by crsprsp** [comment]
Hi Tom, 

for example my check_NT Template looks like this now:

![image](https://cloud.githubusercontent.com/assets/16636402/22101845/63f84abc-de35-11e6-92b3-1372f20338e6.png)

But should look like this:

![image](https://cloud.githubusercontent.com/assets/16636402/22101934/c174de76-de35-11e6-8812-a7488807137a.png)

All the Custom properties i once added are gone. I can add them again without any error, but _ALL_ my Service Templates are affected. ALL. :(

bye, Rico

**Comment by Thomas-Gelf** [comment]
Don't worry, nothing has been lost so far. At least I hope so ;-) Did you eventually assign those fields to the check command, and not to the service template? So that they should be inherited?

**Comment by crsprsp** [comment]
Hm, nope. I added them to the Service Template. Like i've leaned it from this guys in Nuremberg ;)

![image](https://cloud.githubusercontent.com/assets/16636402/22102966/9f1105d6-de39-11e6-9bdb-a2a175a4b13a.png)

**Comment by Thomas-Gelf** [comment]
Strange... could you please also show me the related command? I'm trying to reproduce this

**Comment by crsprsp** [comment]
This one?

object CheckCommand "check_nt" {
    import "plugin-check-command"
    command = [ PluginDir + "/check_nt" ]
    timeout = 1m
    arguments += {
        "-H" = "$nt_address$"
        "-c" = "$nt_crit$"
        "-d" = "$nt_showall$"
        "-l" = "$nt_partition$"
        "-p" = "$nt_port$"
        "-s" = "$nt_pass$"
        "-v" = "$nt_check_variable$"
        "-w" = "$nt_warn$"
    }
    vars.nt_address = "$address$"
    vars.nt_pass = "mypass"
    vars.nt_port = "12489"
}

**Comment by Thomas-Gelf** [comment]
This one, a screenshot of the related Fields tab would be great

**Comment by crsprsp** [comment]
Ok, they're quite the same as in the Service Template:

![image](https://cloud.githubusercontent.com/assets/16636402/22103573/f691b6fa-de3b-11e6-8ee8-2842fc6a7563.png)

**Comment by Thomas-Gelf** [comment]
That's interesting... is this screenshot from 1.3.0?

**Comment by crsprsp** [comment]
Yes, freshly upgraded this morning:

like git fetch && git status and then a git pull. 
Afterwards there was one schema upgrade pending which i applied.

**Comment by Thomas-Gelf** [comment]
Ok, now I'm able to reproduce this - thank you! Your information that you defined those fields at the service template (and not on the command) somewhat confused me. So when you try to add the same fields to the service template they are back, is that correct? (no need to do this everywhere, I'll fix this)

And when previewing the generated Config for your services they still carry all their values I guess? At least that's the part I'm able to reproduce. What seems to be broken is that somehow the service no longer shows the fields it inherited from a command. Please correct me where my assumption is wrong.

**Comment by crsprsp** [comment]
Totally correct! When i add them again to the Service Template, they're back.

Everything i configured, is still there. I just found this because some guys pushed me ot add some services. :)

**Comment by Thomas-Gelf** [comment]
Just to give you some feedback in the meantime: I solved parts of this, didn't yet commit it. Was tricky to find, but easy to fix. Still, it currently doesn't show values inherited from the command in the GUI, I'll push my changes as soon as I fixed that part too.

**Comment by crsprsp** [comment]
Ok, sounds very good! Give me a hint as soon as you pushed it please.

**Comment by Thomas-Gelf** [comment]
Sure

**Comment by Thomas-Gelf** [comment]
This is also related to #712, slipped through

**Comment by Thomas-Gelf** [comment]
Please try again

**Comment by crsprsp** [comment]
Baem! this is it! working! Thank you!!!

**Comment by Thomas-Gelf** [comment]
You're welcome! Glad that it works, and thanks for reporting this. Build status currently shows failing, but that's just because of an unneeded empty line. Latest tests are running and will be green: [build 123](https://travis-ci.org/Icinga/icingaweb2-module-director/builds/193373456).

Please pull again, just to have the "green version" ;-)

**Comment by crsprsp** [comment]
so good! Thank you again Tom!
