### ISSUE TITLE
Refreshing left pane with services looses search

### ISSUE THREAD

**Issue by friesoft** [Icinga/icingaweb2-module-director#732]
If you search for service templates and click the refresh button the pane looses the search. If you've got many service templates and it is for example on page 3 you are navigated back to page 1.

/icingaweb2/director/services/templates?(service=*logfile*)
Click the button "Refresh the templates"
--> back to the whole search

This is especially annoying if you have the templates filtered, add an apply rule and want to see it in the left pane. As soon as you click refresh you are back to the start.

**Comment by Thomas-Gelf** [comment]
Thanks for pointing us to this, definitively needs improvement

**Comment by Thomas-Gelf** [comment]
Fixed with new table implementation in `next`
