### ISSUE TITLE
Cloning a service template looses field assignment

### ISSUE THREAD

**Issue by friesoft** [Icinga/icingaweb2-module-director#733]
If you click clone on a service template (preserving all imports) all assigned fields are lost. 

All values of the fields are copied because as soon as you manually add the field assignment back the values are still there.

**Comment by Thomas-Gelf** [comment]
Uhm... yeah... that's a feature :laughing:
Jokes apart, I guess we can fix this

**Comment by mbassett** [comment]
Not to hijack, but similarly when you clone a service set, you get no services.

**Comment by druchoo** [comment]
+1 for this feature
