### ISSUE TITLE
Service Template Search doesn't search in apply rule names

### ISSUE THREAD

**Issue by friesoft** [Icinga/icingaweb2-module-director#734]
Searching for the name of an apply rule doesn't find anything as the filter only searches in the names of the template.

/icingaweb2/director/services/templates?(service=%2Acatalina%2A)
This only returns matching templates but not matching apply rules.

**Comment by Thomas-Gelf** [comment]
Good catch, it would of course be useful to search apply rule names too!

**Comment by Thomas-Gelf** [comment]
I'll close this in favor of #895 - apply rules will get a dedicated table.
