### ISSUE TITLE
services assigned with servicesets are not shown at the  "hosts -> services" tab, custom properties can't be assigned

### ISSUE THREAD

**Issue by Hrocc** [Icinga/icingaweb2-module-director#735]
Version: 1.3.0 

Serviceset: 
![grafik](https://cloud.githubusercontent.com/assets/25223332/22106223/fefaa9ee-de47-11e6-87fc-e309af541ec2.png)
![grafik](https://cloud.githubusercontent.com/assets/25223332/22106277/419121b6-de48-11e6-8c6c-9fc086e9e148.png)

host where the apply rule matches:

![grafik](https://cloud.githubusercontent.com/assets/25223332/22106305/6dd4ea0a-de48-11e6-98a1-e8c9c8747a6b.png)

Custom properties to the services defined with servicesets can't be set

**Comment by mbassett** [comment]
related to this ( can open a separate ticket )

after upgrading to 1.3.0 from a git master snapshot of early jan
I noticed that after creating service set, and assigning custom properties when I added them to the service set, those custom properties do not show in the UI when going back to edit the service set.  Icinga is using the custom properties I set or the checks would be failing, but at this point I can't change the parameters without recreating the service set.

**Comment by rai-n-air** [comment]
definetly saved my day! THANK YOU!

**Comment by Thomas-Gelf** [comment]
Glad to hear that :-) You're welcome!
