### ISSUE TITLE
Sort order of service templates is wrong

### ISSUE THREAD

**Issue by friesoft** [Icinga/icingaweb2-module-director#736]
Our service templates have a funny sort order. It is sorted alphabetically from A to Z and then some imports for all services (e.g. "[Template] ssh-service (active)"). Then services are starting again from A to Z and then another time. So some services with A are in the first group, some in the second and some in the third..

**Comment by Thomas-Gelf** [comment]
Those should be services with and services without a CheckCommand, could that be the case? You can create apply rules for the first ones, and you can't for the latter. Just, I'm not sure whether this distinction is really useful - you're not the first one to be confused about this :laughing:

**Comment by friesoft** [comment]
Oh my dear :D I definitely didn't get this.. you are correct the first A-Z are those with CheckCommands set directly in the template, the second A-Z are those who inherit the CheckCommand from another template.

To be honest I don't think this makes sense from a user perspective :)

**Comment by Thomas-Gelf** [comment]
This got fixed with ongoing work in #895
