### ISSUE TITLE
Searching Director Hosts for display name does not return results

### ISSUE THREAD

**Issue by mbassett** [Icinga/icingaweb2-module-director#737]
When I search Director Hosts page for things it automatically sets the filter to use name and display_name.

However, when searching for things by display_name no matching results are ever set

![icingahosts](https://cloud.githubusercontent.com/assets/2250654/22126694/99ee160c-de4d-11e6-9097-68a0394e1270.png)

**Comment by mbassett** [comment]
(same search in icinga overview hosts returns values, this is just in director->hosts )

**Comment by Thomas-Gelf** [comment]
Search has been completely changed and simplified for v1.4.0 - default search includes display_name
