### ISSUE TITLE
Inheriting numbers from service template not working

### ISSUE THREAD

**Issue by friesoft** [Icinga/icingaweb2-module-director#738]
We have a service template called "template SSH service active" which has by_ssh as checkcommand and some fields for configuration (e.g. timeout). The timeout field is a number field.

If I now create a new service template which imports this template the timeout isn't displayed as inherited. Looks like inheriting number fields doesn't work. The other strings are correctly displayed as inherited.

**Comment by Thomas-Gelf** [comment]
There was a related issue in 1.3.0 that has been fixed in the meantime - but I'm not sure whether this is really what you describe. Could you please show me some related screen-shots? e.g. involved command, templates...

Thanks,
Thomas

**Comment by leeclemens** [comment]
I think I'm seeing the same as @friesoft is describing (hopefully).
I've seen this for a while, including v1.3.1 and 6234648a1ffe74a7239b2ab30a3bb3b7afafc6dc.

> tcp service

I'm not sure how it got `vars.tcp_refuse = "crit"`...I'm guessing from the command that was imported (hadn't noticed it do that previously). The `tcp` command object was imported and has no fields assigned to it via Director.
```
template Service "tcp" {
    import "Standard Active Service"

    check_command = "tcp"
}
```
![icinga2-director-738_tcp](https://cloud.githubusercontent.com/assets/1250267/24831483/2fede120-1c68-11e7-88cc-2577029b41da.png)

> tcp-http service
```
template Service "tcp-http" {
    import "tcp"

    vars.tcp_port = 80
    vars.tcp_refuse = "warn"
}
```
![icinga2-director-738_tcp-http](https://cloud.githubusercontent.com/assets/1250267/24831486/336eb946-1c68-11e7-9491-8be4c24ee282.png)

> tcp-mysite service

Expected `80 (inherited from "tcp-http")`
```
template Service "tcp-mysite" {
    import "tcp-http"

}
```
![icinga2-director-738_tcp-mysite](https://cloud.githubusercontent.com/assets/1250267/24831487/355ad9f6-1c68-11e7-8429-91952e57f79f.png)

**Comment by friesoft** [comment]
@leeclemens yes that is the same behaviour I'm also having.

**Comment by lazyfrosch** [comment]
Works as of now (confirmed by @friesoft) (ebe1917b152b786cc708abe5215fd0c4be7c4237)

![bildschirmfoto von 2017-12-06 09-31-38](https://user-images.githubusercontent.com/121874/33652066-51f652fc-da68-11e7-8c05-c25f2b0e019f.png)
