### ISSUE TITLE
Issue with Notification Apply Assign Bool Values

### ISSUE THREAD

**Issue by ctoepfl** [Icinga/icingaweb2-module-director#739]
icinga2:2.4.0
director:1.3.0

i configure in director a own notficiation and want assign all services or hosts where enable_notfications is true, but it is quoted - i thind bool values should not be quoted?

preview from director:
```
apply Notification "send-service-to-sysadmin" to Service {
    import "generic-service-notification"

    assign where host.enable_notifications == "true"
    user_groups = [ "sysadmin" ]
}
```

old: 
```
assign where host.enable_notifications == "true"
```
patched:
`assign where host.enable_notifications == true`

**Comment by mbassett** [comment]
#729

**Comment by Icinganator** [comment]
I ran into the same issue - it's impossible to assign notifications for services via a bool variable, because the values true/false are quoted. Therefore no notification will be sent.
Tested with director 1.3.1

**Comment by noudAndi** [comment]
There is a workaround, which is not nice, but working:

` assign where host.enable_notifications != "false"`

However, I also would love to have this fixed. :)
