### ISSUE TITLE
"Disable host" does not disable its endpoint

### ISSUE THREAD

**Issue by sysadmama** [Icinga/icingaweb2-module-director#741]
Hi,

I have several hosts, defined in Director and disabled there. But in icinga2.log, I get every minute for each of these hosts messages like

```
critical/ApiListener: Cannot connect to host 'a.b.c.d' on port '5665'
critical/TcpSocket: Invalid socket: Connection timed out
```

In fact, in /var/lib/icinga2/api/zones/lns-2007/director/hosts.conf my host is commented out with the hint "This object has been disabled", but the endpoint and zone is not disabled and my logs get flooded. I did not try to register a new host with same ip address, but I think it would be confusing.

But in my opinion, "disable" should disable all :) 

Cheers,
  Marianne

**Comment by Thomas-Gelf** [comment]
You're absolutely right, thanks for reporting this!
