### ISSUE TITLE
Possible issue with repeated Kickstart 

### ISSUE THREAD

**Issue by detto9** [Icinga/icingaweb2-module-director#743]
Hi,
I'm building a fresh Icinga system using Icinga 2.6.0 and Director 1.3.0 on Ubuntu compiling the sources from GitHub (no packages).
The initial kickstart was fine. 
Now I'd like to repeat the kickstart, because I would like to import new/updated command definitions from the Icinga Core. I made no other changes.
The result is:

`ubuntu@icinga:~$ sudo su - -c "PATH=$PATH:/share/icingaweb2/bin icingacli director kickstart run --verbose --debug"
ERROR: Icinga\Exception\IcingaException in /share/icingaweb2/modules/director/library/Director/Data/Db/DbObject.php:755 with message: Storing icinga_apiuser[] failed: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'object_name' cannot be null, query was: INSERT INTO icinga_apiuser (object_name, object_type, disabled, password, client_dn, permissions) VALUES (?, ?, ?, ?, ?, ?) {array (
  'id' => NULL,
  'object_name' => NULL,
  'object_type' => 'external_object',
  'disabled' => 'n',
  'password' => NULL,
  'client_dn' => NULL,
  'permissions' => NULL,
)}
ubuntu@icinga:~$
`

I only have the "minimum set" of API users: "root" by default and I added"director" as instructed by the docs.

Is this an issue ? Or am I doing anything wrong ?
Thanks,
          -detto9

**Comment by Thomas-Gelf** [comment]
When running on CLI you need a kickstart.ini? -> [docs/automation](https://github.com/Icinga/icingaweb2-module-director/blob/master/doc/03-Automation.md)

In case that file exists and you believe it to be correct please let me know.

**Comment by detto9** [comment]
Danke Thomas!
