### ISSUE TITLE
 'director-global' of type 'Zone' does not exist.

### ISSUE THREAD

**Issue by dgoeger** [Icinga/icingaweb2-module-director#749]
Hi,

every time, i will create a Hostgroup there is an error message on deploying:

Validation failed for object 'windows-servers' of type 'HostGroup'; Attribute 'zone': Object 'director-global' of type 'Zone' does not exist.

Do i need a Zone director-global? Or is there a Bug?

Thank You.

**Comment by Copis** [comment]
You need to add the following lines into /etc/icinga2/zones.conf

/****   Icinga 2 Global Zone   ****/
object Zone "director-global" {
        global = true
}

**Comment by dgoeger** [comment]
Thank You, but why do i need this Zone?
Isn't it possible to create another "default Zone"?

**Comment by Thomas-Gelf** [comment]
![director_global-zone_rtfm1](https://cloud.githubusercontent.com/assets/553008/22287118/e37eed48-e2f1-11e6-93ea-a6a54ff5df4f.png)

![director_global-zone_rtfm2](https://cloud.githubusercontent.com/assets/553008/22287128/edc6809a-e2f1-11e6-997a-e8e989280b38.png)

**Comment by dgoeger** [comment]
I should read the documentation better :)
Thank you Thomas
