### ISSUE TITLE
Service Assign-rule isset

### ISSUE THREAD

**Issue by dgoeger** [Icinga/icingaweb2-module-director#750]
Hello,

is it possible to set a service apply rule like this: "assign where host.address"?

I don't find a operator like "is set" or something else.

**Comment by dgoeger** [comment]
second assign Rule how to create: assign where (host.address || host.address6) && host.vars.os == "Linux"

**Comment by lazyfrosch** [comment]
Please use the search of GitHub, it's pretty good

See #729 and #739

**Comment by dgoeger** [comment]
Okay sorry i search for that Problem but don't find anything.
But the Second rule is another Problem ....
There is an and Operator combined with an or operator.
Should i Open a Second issu?
