### ISSUE TITLE
applied service sets are not shown in Director/Hosts/Services

### ISSUE THREAD

**Issue by rai-n-air** [Icinga/icingaweb2-module-director#753]
Director 1.3.0 (2017_01_26 Download)

Director/Hosts/Services shows only services attached directly to the host or services from attached templates or single services attached by apply rules but no service coming from service-sets which are attached by apply rule.
It´s not even showing the service set names.
The Rendering is ok. In Icinga the Services are all there but in director I can´t see them so I have no control...
Would be great to see this like it was great to see it for templates.

Thank you in advance!

**Comment by mwaldmueller** [comment]
+1

**Comment by rai-n-air** [comment]
can be closed: https://github.com/Icinga/icingaweb2-module-director/commit/4860082d4bb4b2631dab6927f4890ecd25327f65
