### ISSUE TITLE
Service templates do not recognize when command arguments (fields) are deleted 

### ISSUE THREAD

**Issue by SimonHoenscheid** [Icinga/icingaweb2-module-director#754]
When adding fields to commands and creating a service template with this command afterwards, everything works fine. But if you delete fields from the command, the service template does not recognize it. That currently forces the user to delete the template and the apply rules and create it again. It would be nice if there would be an update mechanism for this case.

**Comment by lazyfrosch** [comment]
Is there an error coming up? Or is your problem that you can't remove the set values?

**Comment by SimonHoenscheid** [comment]
The problem is that a change to command fields is not recognized by the template. Deleted field values from the command persist in the template

**Comment by lazyfrosch** [comment]
Sadly a known problem, since the API supports non-field values any time.

We would have to implement a cleanup, with confirmation when removing a field.

**Comment by SimonHoenscheid** [comment]
Hope this is fixed soon. Thanks

**Comment by Thomas-Gelf** [comment]
There is no easy way to solve this. Field removal is covered, at least when it goes to deleting a whole data field:

![director_remove_field](https://cloud.githubusercontent.com/assets/553008/22331453/d665ecd0-e3cb-11e6-82fd-1d215e08da64.png)

The form also tries to explain what's going on and why. Things get complicated when just removing a field from a template. What if the same field exists on an inheriting template or on the related command? What if you change the data type? What if you just want to temporarily remove the field from one template to re-add it to it's parent (or child) later on?

We could add more hints explaining what's going on, but there is no way to implement some "magic" that would make everybody happy. Right now, preserving data is the most conservative "solution". Far better than accidentally deleting values from a huge bunch of objects.

Related issues to improve the whole work-flow already exist. They target "renaming fields", "binding vars to fields" (lot of discussion, no solution) and more mass-edit functionality.

So far, this works "as it should". When removing a field from a template, please remove it's values first. Re-add the field in case you forgot doing so. Delete fields through the main Data Fields list to get this handled automagically, like shown on the above screen-shot. Usually this should suffice. Open more specific issues with suggestions of how this could be handled for special use-cases.

Said all this, I'll close this issue as won't-fix for now.
