### ISSUE TITLE
Service/Service template "Check execution" options disappears

### ISSUE THREAD

**Issue by erezzarum** [Icinga/icingaweb2-module-director#755]
I can't reproduce it, but i'm now starting a new deployment and it looks like everytime i create an "apply rule" on a service template, after navigating through the UI returning back to it, navigates me back to the "apply rule" service template and i can't access the "original" one.
It's not a browser caching issues as well.
The only way to edit it again is to delete the whole service and recreate it which is a not scalable workaround.

**Comment by erezzarum** [comment]
Managed to reproduce it!
When changing an execution options value (i.e check interval) on a service template that inherits from another service template, after reverting back to default (to inherit from the template, removing our value) the execution options disappear at all for the service template which requires to re-create again.

**Comment by mbassett** [comment]
are you running 1.3.0 or master branch?  All my missing custom properties have come back on the latest master branch.

**Comment by erezzarum** [comment]
I am using the latest commit from the master branch.
Do i need to have any database migration? because i didn't alert me on any of them (checked with the icingacli)

Thanks.

**Comment by erezzarum** [comment]
Trying to delete the service to clean some thing up, and this happens:
`SQLSTATE[23503]: Foreign key violation: 7 ERROR: update or delete on table "icinga_service" violates foreign key constraint "icinga_service_inheritance_parent_service" on table "icinga_service_inheritance"
DETAIL: Key (id)=(23) is still referenced from table "icinga_service_inheritance"., query was: DELETE FROM icinga_service WHERE (id = '23')

#0 /usr/share/icingaweb2/library/vendor/Zend/Db/Statement.php(297): Zend_Db_Statement_Pdo->_execute(Array)
#1 /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Abstract.php(470): Zend_Db_Statement->execute(Array)
#2 /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Pdo/Abstract.php(232): Zend_Db_Adapter_Abstract->query('DELETE FROM ici...', Array)
#3 /usr/share/icingaweb2/library/vendor/Zend/Db/Adapter/Abstract.php(652): Zend_Db_Adapter_Pdo_Abstract->query('DELETE FROM ici...')
#4 /usr/share/icingaweb2/modules/director/library/Director/Data/Db/DbObject.php(782): Zend_Db_Adapter_Abstract->delete('icinga_service', 'id = '23'')
#5 /usr/share/icingaweb2/modules/director/library/Director/Data/Db/DbObject.php(904): Icinga\Module\Director\Data\Db\DbObject->deleteFromDb()
#6 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/DirectorObjectForm.php(706): Icinga\Module\Director\Data\Db\DbObject->delete()
#7 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/DirectorObjectForm.php(640): Icinga\Module\Director\Web\Form\DirectorObjectForm->deleteObject(Object(Icinga\Module\Director\Objects\IcingaService))
#8 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/DirectorObjectForm.php(630): Icinga\Module\Director\Web\Form\DirectorObjectForm->handlePost()
#9 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/QuickForm.php(451): Icinga\Module\Director\Web\Form\DirectorObjectForm->onRequest()
#10 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/QuickForm.php(463): Icinga\Module\Director\Web\Form\QuickForm->setRequest(Object(Icinga\Web\Request))
#11 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/QuickForm.php(322): Icinga\Module\Director\Web\Form\QuickForm->getRequest()
#12 /usr/share/icingaweb2/modules/director/application/controllers/ServiceController.php(144): Icinga\Module\Director\Web\Form\QuickForm->handleRequest()
#13 /usr/share/icingaweb2/modules/director/library/Director/Web/Controller/ObjectController.php(111): Icinga\Module\Director\Controllers\ServiceController->editAction()
#14 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Director\Web\Controller\ObjectController->indexAction()
#15 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('indexAction')
#16 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#17 /usr/share/php/Icinga/Application/Web.php(389): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#18 /usr/share/php/Icinga/Application/webrouter.php(109): Icinga\Application\Web->dispatch()
#19 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...')
#20 {main}`

**Comment by Thomas-Gelf** [comment]
@erezzarum: I somehow missed this issue... a lot of things changed since the time being, does this problem still exist for you?
