### ISSUE TITLE
users --> groups --> add

### ISSUE THREAD

**Issue by ysijason** [Icinga/icingaweb2-module-director#756]
Trying to set invalid key zone_id

#0 /usr/share/icingaweb2/modules/director/library/Director/Objects/IcingaObject.php(649): Icinga\Module\Director\Data\Db\DbObject->set('zone_id', NULL)
#1 /usr/share/icingaweb2/modules/director/library/Director/Data/Db/DbObject.php(353): Icinga\Module\Director\Objects\IcingaObject->set('zone_id', NULL)
#2 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/DirectorObjectForm.php(99): Icinga\Module\Director\Data\Db\DbObject->__set('zone_id', NULL)
#3 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/DirectorObjectForm.php(626): Icinga\Module\Director\Web\Form\DirectorObjectForm->object()
#4 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/QuickForm.php(451): Icinga\Module\Director\Web\Form\DirectorObjectForm->onRequest()
#5 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/QuickForm.php(463): Icinga\Module\Director\Web\Form\QuickForm->setRequest(Object(Icinga\Web\Request))
#6 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/QuickForm.php(322): Icinga\Module\Director\Web\Form\QuickForm->getRequest()
#7 /usr/share/icingaweb2/modules/director/library/Director/Web/Controller/ObjectController.php(221): Icinga\Module\Director\Web\Form\QuickForm->handleRequest()
#8 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Director\Web\Controller\ObjectController->addAction()
#9 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('addAction')
#10 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#11 /usr/share/php/Icinga/Application/Web.php(389): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#12 /usr/share/php/Icinga/Application/webrouter.php(109): Icinga\Application\Web->dispatch()
#13 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...')
#14 {main}

**Comment by Thomas-Gelf** [comment]
Please pull, should be fixed in current master.

**Comment by ysijason** [comment]
@Thomas-Gelf 

yep fixed, amazing response time
