### ISSUE TITLE
Problem applying schema update when going from 123 to 128

### ISSUE THREAD

**Issue by KaneRason** [Icinga/icingaweb2-module-director#757]
The following error is reported in the web interface after attempting to apply the 5 required schema migrations to bring the level up to 128.  The new git repository was pulled on the 27/1/2017.

Migration 126 failed (SQLSTATE[HY000]: General error: 1553 Cannot drop index 'icinga_service_set_host': needed in a foreign key constraint, query was: EXECUTE stmt) while running EXECUTE stmt

The issue appears to be similar to the closed ticket #695 

Please let me know if you require any further information.

**Comment by Thomas-Gelf** [comment]
Please post the output of the following query:

```
SELECT * FROM information_schema.table_constraints
  WHERE table_schema = 'director' AND (
    table_name like '%host%' or table_name like '%service%'
)\G
```

Thanks,
Thomas

**Comment by KaneRason** [comment]
Hi Thomas
Output  attached as requested,
thanks Kane

[757_2017_01_30_1.txt](https://github.com/Icinga/icingaweb2-module-director/files/738601/757_2017_01_30_1.txt)

**Comment by schmm2** [comment]
I have the exactly the same issue here.
I'm currently on Schema 125. But i get the exact same error: 
Migration 126 failed (SQLSTATE[HY000]: General error: 1553...

What can we do?

**Comment by schmm2** [comment]
found a solution: SET GLOBAL FOREIGN_KEY_CHECKS=0;
Forced it to apply the update

**Comment by Thomas-Gelf** [comment]
Sorry, I didn't realize that this is still open. @KaneRason: your output shows A LOT of misnamed indexes, all of them named like `icinga_service_set_ibfk_*`. You need to delete them, manually, I'm not going to add something handling so many variants unless a bunch of people with the same issue is showing up.

@schmm2: nooooooooooo!!! Please never, never force schema upgrades. In case there have been other errors, it's very, very hard to detect them right now. I'd strongly suggest you to `mysqldump` with `--no-create-info`, drop the database, let Director re-create the DB with the same schema version, re-import your data. Backup the whole database (with schema) first to be on the safe side, or restore to a new DB in case you have never done a similar operation before.

@ anyone reading this: please NEVER FORCE DB MIGRATIONS. In case they fail, there is usually a reason that wants to be fixed. If you force schema upgrades you might hide errors that could pop up long time later, and it might be very, very hard to figure out what went wrong with your DB.

**Comment by KaneRason** [comment]
@Thomas-Gelf no problem, my fault as I accidentally closed and then reopened the ticket after attaching the requested info.  I'll give your suggestion a go and report back.

Thanks

Kane

**Comment by Thomas-Gelf** [comment]
@KaneRason: sample query to delete those indexes:

```sql
ALTER TABLE icinga_service_set DROP FOREIGN KEY icinga_service_set_ibfk_1;
```

**Comment by Thomas-Gelf** [comment]
(everything with *ibfk* is wrong)

**Comment by schmm2** [comment]
ok. thanks for the information. I will try to recreate the DB. thanks for the support :)

**Comment by KaneRason** [comment]
@Thomas-Gelf: that worked perfectly.  Many thanks for your help, Director is a great module.

**Comment by Thomas-Gelf** [comment]
You're welcome!
