### ISSUE TITLE
REST API Ticket issue

### ISSUE THREAD

**Issue by chrkli193** [Icinga/icingaweb2-module-director#759]
Was there a change during the last updates to the REST API?
A few weeks ago I could fetch the ticket as described in the doc files. And I only got the ticket nr. Now when I run the same command I get also all information about the host like this:

director/host/ticket?name=hostname
{
    "address": "10.10.10.10",
    "display_name": "hostname",
    "imports": [
        "generic-host-windows-director",
        "Icinga Agent"
    ],
    "object_name": "hostname",
    "object_type": "object",
    "vars": {
        "os": "windows"
    }
}
"12345678900kjk3jklj234jkl234"

**Comment by cptnkoiz** [comment]
Same here, broke our Agent deployment.

**Comment by Thomas-Gelf** [comment]
Thanks for reporting this, can be reproduced and will be fixed.
