### ISSUE TITLE
Sync Rule Properties, preselect field source name

### ISSUE THREAD

**Issue by SimonHoenscheid** [Icinga/icingaweb2-module-director#761]
Sync Rules are written for a specific source only, when creating one, the source is pre selected. So it makes sense to prefil the source name field with the source when creating a new property

**Comment by Thomas-Gelf** [comment]
> Sync Rules are written for a specific source only

This assumption is wrong, sync rules can perfectly combine multiple import sources. The current behavior tries to make this obvious. Pre-selecting one single source after a single field has been added would either make this feature useless or at least hide it. I'm not a big fan of both and will therefore reject this issue.
