### ISSUE TITLE
FreeBSD: icingaweb-director: Undefined offset: 0

### ISSUE THREAD

**Issue by SB211** [Icinga/icingaweb2-module-director#766]
Running ICINGA2 with ICINGAWEB2 on FreeBSD (11.0-R and 12-CURRENT), module "director" fails to show the graphical "kickstart" environment when klicking on the "Director" tag shown in the lefthand menu. It results in the backtrace shown below.

Obviously, director works from the console (using icingacli), I'm also able to crate objects/templates from the graphical frontend stored successfully in the PostGreSQL backend.

Since I'm not sure what this error does mean I do not know where to start looking.

I'm with subversion  revision 4024 of the director.

Background:

System is either 11.0-R or 12-CURRENT, all ports used are compiled and build from the most recent ports tree, PHP is PHP 5.6 as it is defined as the standard in FreeBSD's ports tree, backend DBs are either postgresql 9.6.X and postgresql 9.5.5.

[...]
```
#0 /usr/local/www/icingaweb2/modules/director/library/Director/Dashboard/Dashlet/Dashlet.php(233): Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(8, 'Undefined offse...', '/usr/local/www/...', 233, Array)
#1 /usr/local/www/icingaweb2/modules/director/library/Director/Dashboard/Dashlet/Dashlet.php(163): Icinga\Module\Director\Dashboard\Dashlet\Dashlet->statSummary(false)
#2 /usr/local/www/icingaweb2/modules/director/library/Director/Dashboard/Dashlet/Dashlet.php(172): Icinga\Module\Director\Dashboard\Dashlet\Dashlet->getSummary()
#3 zend.view:///usr/local/www/icingaweb2/modules/director/application/views/scripts/dashlets/default.phtml(4): Icinga\Module\Director\Dashboard\Dashlet\Dashlet->getEscapedSummary()
#4 /usr/local/www/icingaweb2/library/Icinga/Web/View.php(231): include('zend.view:///us...')
#5 /usr/local/www/icingaweb2/library/vendor/Zend/View/Abstract.php(877): Icinga\Web\View->_run('/usr/local/www/...')
#6 /usr/local/www/icingaweb2/library/vendor/Zend/View/Helper/Partial.php(106): Zend_View_Abstract->render('dashlets/defaul...')
#7 [internal function]: Zend_View_Helper_Partial->partial('dashlets/defaul...', Array)
#8 /usr/local/www/icingaweb2/library/vendor/Zend/View/Abstract.php(346): call_user_func_array(Array, Array)
#9 /usr/local/www/icingaweb2/library/Icinga/Web/View.php(250): Zend_View_Abstract->__call('partial', Array)
#10 /usr/local/www/icingaweb2/modules/director/library/Director/Dashboard/Dashlet/Dashlet.php(129): Icinga\Web\View->__call('partial', Array)
#11 /usr/local/www/icingaweb2/modules/director/library/Director/Dashboard/Dashlet/Dashlet.php(129): Icinga\Web\View->partial('dashlets/defaul...', Array)
#12 zend.view:///usr/local/www/icingaweb2/modules/director/application/views/scripts/dashboard/index.phtml(26): Icinga\Module\Director\Dashboard\Dashlet\Dashlet->render()
#13 /usr/local/www/icingaweb2/library/Icinga/Web/View.php(231): include('zend.view:///us...')
#14 /usr/local/www/icingaweb2/library/vendor/Zend/View/Abstract.php(877): Icinga\Web\View->_run('/usr/local/www/...')
#15 /usr/local/www/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(904): Zend_View_Abstract->render('dashboard/index...')
#16 /usr/local/www/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(925): Zend_Controller_Action_Helper_ViewRenderer->renderScript('dashboard/index...', NULL)
#17 /usr/local/www/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(964): Zend_Controller_Action_Helper_ViewRenderer->render()
#18 /usr/local/www/icingaweb2/library/vendor/Zend/Controller/Action/HelperBroker.php(272): Zend_Controller_Action_Helper_ViewRenderer->postDispatch()
#19 /usr/local/www/icingaweb2/library/vendor/Zend/Controller/Action.php(518): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
#20 /usr/local/www/icingaweb2/library/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('indexAction')
#21 /usr/local/www/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#22 /usr/local/www/icingaweb2/library/Icinga/Application/Web.php(389): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#23 /usr/local/www/icingaweb2/library/Icinga/Application/webrouter.php(109): Icinga\Application\Web->dispatch()
#24 /usr/local/www/icingaweb2/public/index.php(4): require_once('/usr/local/www/...')
#25 {main}
```

**Comment by Thomas-Gelf** [comment]
@SB211: does this still happen?

**Comment by SB211** [comment]
Yes, I regret to report that this error is still occuring although I've just checked out revision 4107 of icingaweb2-module-director.

FreeBSD does have a port now, located in the ports tree at net-mgmt/icingaweb2-module-director, but also with that port, the error persists.

I do not know where to start searching for a possible inconsistent or malformed configuration.

**Comment by bmccorkle** [comment]
Were you ever able to solve this?   I believe I am having the same issue possibly.

**Comment by Thomas-Gelf** [comment]
Could you guys please point me to the source where you got your Director from? We are not using Subversion, there is no revision 4107 and files/line numbers in the shown stack trace do not reflect any recent version.

**Comment by bmccorkle** [comment]
I built mine from the FreeBSD ports collection:

https://www.freebsd.org/cgi/ports.cgi?query=icingaweb2-module-director-1.4.3&stype=all&sektion=all

**Comment by Thomas-Gelf** [comment]
I have no experience with FreeBSD packaging, what looks suspicious is that while the Makefile has been upgraded to 1.4.3, pkg-list's last change refers to 1.4.1. However, no file has been added between those two releases, so this should be fine.

Still, neither the `pkg-list` nor Director v1.4.3 contains for example the file `application/views/scripts/dashboard/index.phtml` - so what you are running does not reflect Director v1.4.x. Could you please try to cleanly re-install this package? Seems that something got messed up badly.

**Comment by bmccorkle** [comment]
Okay, I'll give it a try and let you know.  Might be a day or two.

**Comment by bmccorkle** [comment]
Here you go.  I had some time today and took a snapshot of the virtual machine then uninstalled the module from the FreeBSD ports collection.  Then tried downloading it straight from github here and unzipping it to the IcingaWeb2 modules directory.   It seems to have registered okay but the error remained the same for me.  I even tried dropping the mysql database and recreating it.   I reverted the machine back to my snapshot.  Here's the trace...

Undefined offset: 0 (Dashlet.php:237)
#0 /usr/local/www/icingaweb2/modules/director/library/Director/Dashboard/Dashlet/Dashlet.php(237): Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(8, 'Undefined offse...', '/usr/local/www/...', 237, Array)
#1 /usr/local/www/icingaweb2/modules/director/library/Director/Dashboard/Dashlet/Dashlet.php(184): Icinga\Module\Director\Dashboard\Dashlet\Dashlet->statSummary(false)
#2 /usr/local/www/icingaweb2/modules/director/library/Director/Dashboard/Dashlet/Dashlet.php(147): Icinga\Module\Director\Dashboard\Dashlet\Dashlet->getSummary()
#3 /usr/local/www/icingaweb2/modules/director/library/vendor/ipl/Html/BaseElement.php(133): Icinga\Module\Director\Dashboard\Dashlet\Dashlet->renderContent()
#4 /usr/local/www/icingaweb2/modules/director/library/vendor/ipl/Html/Html.php(171): dipl\Html\BaseElement->render()
#5 /usr/local/www/icingaweb2/modules/director/library/vendor/ipl/Html/BaseElement.php(105): dipl\Html\Html->render()
#6 /usr/local/www/icingaweb2/modules/director/library/vendor/ipl/Html/BaseElement.php(133): dipl\Html\BaseElement->renderContent()
#7 /usr/local/www/icingaweb2/modules/director/library/vendor/ipl/Html/Html.php(171): dipl\Html\BaseElement->render()
#8 /usr/local/www/icingaweb2/modules/director/library/Director/Dashboard/Dashboard.php(82): dipl\Html\Html->render()
#9 /usr/local/www/icingaweb2/modules/director/library/vendor/ipl/Html/Html.php(171): Icinga\Module\Director\Dashboard\Dashboard->render()
#10 /usr/local/www/icingaweb2/modules/director/library/vendor/ipl/Html/BaseElement.php(105): dipl\Html\Html->render()
#11 /usr/local/www/icingaweb2/modules/director/library/vendor/ipl/Html/BaseElement.php(133): dipl\Html\BaseElement->renderContent()
#12 /usr/local/www/icingaweb2/modules/director/library/vendor/ipl/Html/Html.php(259): dipl\Html\BaseElement->render()
#13 /usr/local/www/icingaweb2/modules/director/library/vendor/ipl/Zf1/SimpleViewRenderer.php(47): dipl\Html\Html->__toString()
#14 /usr/local/www/icingaweb2/modules/director/library/vendor/ipl/Zf1/SimpleViewRenderer.php(66): dipl\Zf1\SimpleViewRenderer->render()
#15 /usr/local/www/icingaweb2/library/vendor/Zend/Controller/Action/HelperBroker.php(272): dipl\Zf1\SimpleViewRenderer->postDispatch()
#16 /usr/local/www/icingaweb2/library/vendor/Zend/Controller/Action.php(518): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
#17 /usr/local/www/icingaweb2/library/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('indexAction')
#18 /usr/local/www/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#19 /usr/local/www/icingaweb2/library/Icinga/Application/Web.php(407): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#20 /usr/local/www/icingaweb2/library/Icinga/Application/webrouter.php(104): Icinga\Application\Web->dispatch()
#21 /usr/local/www/icingaweb2/public/index.php(4): require_once('/usr/local/www/...')
#22 {main}

**Comment by bmccorkle** [comment]
I've also noticed if I comment out line 147 of Dashlet.php:

Html::tag('p', null, $this->getSummary())

then the page displays the title and icons but not the summary of each item.

![capture-icinga](https://user-images.githubusercontent.com/36084927/36504945-1333d068-1720-11e8-80ab-3f0f6fc549bb.JPG)

**Comment by Thomas-Gelf** [comment]
Ok, this one looks better - we're getting closer. Please add this line, reload the page and post the output:

```patch
     public function getSummary()
     {
         $result = '';
         if (! empty($this->requiredStats)) {
+            if (false === current($this->requiredStats)) { var_dump($this); exit; }
             $result .= $this->statSummary(current($this->requiredStats));
```

Thanks,
Thomas

**Comment by bmccorkle** [comment]
Okay, Here's the output displayed...

object(Icinga\Module\Director\Dashboard\Dashlet\HostObjectDashlet)#134 (13) { ["icon":protected]=> string(4) "host" ["requiredStats":protected]=> array(2) { [0]=> string(4) "host" [1]=> string(9) "hostgroup" } ["tag":protected]=> string(2) "li" ["sectionName":protected]=> NULL ["supportsLegacyConfig":protected]=> NULL ["db":protected]=> object(Icinga\Module\Director\Db)#112 (7) { ["modules":protected]=> array(0) { } ["settings":protected]=> object(Icinga\Module\Director\Settings)#127 (5) { ["connection":protected]=> *RECURSION* ["db":protected]=> object(Zend_Db_Adapter_Pdo_Mysql)#116 (12) { ["_pdoType":protected]=> string(5) "mysql" ["_numericDataTypes":protected]=> array(16) { [0]=> int(0) [1]=> int(1) [2]=> int(2) ["INT"]=> int(0) ["INTEGER"]=> int(0) ["MEDIUMINT"]=> int(0) ["SMALLINT"]=> int(0) ["TINYINT"]=> int(0) ["BIGINT"]=> int(1) ["SERIAL"]=> int(1) ["DEC"]=> int(2) ["DECIMAL"]=> int(2) ["DOUBLE"]=> int(2) ["DOUBLE PRECISION"]=> int(2) ["FIXED"]=> int(2) ["FLOAT"]=> int(2) } ["_defaultStmtClass":protected]=> string(21) "Zend_Db_Statement_Pdo" ["_config":protected]=> array(9) { ["host"]=> string(9) "localhost" ["username"]=> string(8) "director" ["password"]=> string(26) "LWiAJZkcByaOOKuzxULJKbCRKo" ["dbname"]=> string(16) "icinga2_director" ["persistent"]=> bool(false) ["options"]=> array(3) { ["caseFolding"]=> int(2) ["autoQuoteIdentifiers"]=> bool(false) ["fetchMode"]=> int(2) } ["driver_options"]=> array(4) { [2]=> int(10) [8]=> int(2) [3]=> int(2) [1002]=> string(180) "SET SESSION SQL_MODE='STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,ANSI_QUOTES,PIPES_AS_CONCAT,NO_ENGINE_SUBSTITUTION', NAMES utf8;" } ["port"]=> int(3306) ["charset"]=> NULL } ["_fetchMode":protected]=> int(5) ["_profiler":protected]=> object(Zend_Db_Profiler)#117 (4) { ["_queryProfiles":protected]=> array(0) { } ["_enabled":protected]=> bool(false) ["_filterElapsedSecs":protected]=> NULL ["_filterTypes":protected]=> NULL } ["_defaultProfilerClass":protected]=> string(16) "Zend_Db_Profiler" ["_connection":protected]=> object(PDO)#126 (0) { } ["_caseFolding":protected]=> int(2) ["_autoQuoteIdentifiers":protected]=> bool(false) ["_allowSerialization":protected]=> bool(true) ["_autoReconnectOnUnserialize":protected]=> bool(false) } ["cache":protected]=> array(1) { ["master_zone"]=> string(18) "bsd-07.gahanna.gov" } ["defaults":protected]=> array(13) { ["default_global_zone"]=> string(15) "director-global" ["magic_apply_for"]=> string(19) "_director_apply_for" ["config_format"]=> string(2) "v2" ["override_services_varname"]=> string(21) "_override_servicevars" ["override_services_templatename"]=> string(29) "host var overrides (Director)" ["disable_all_jobs"]=> string(1) "n" ["enable_audit_log"]=> string(1) "n" ["deployment_mode_v1"]=> string(14) "active-passive" ["deployment_path_v1"]=> NULL ["activation_script_v1"]=> NULL ["self-service/agent_name"]=> string(4) "fqdn" ["self-service/transform_hostname"]=> string(1) "0" ["self-service/global_zones"]=> array(1) { [0]=> string(15) "director-global" } } ["jsonEncode":protected]=> array(2) { [0]=> string(25) "self-service/global_zones" [1]=> string(29) "self-service/installer_hashes" } } ["masterZoneName":protected]=> string(18) "bsd-07.gahanna.gov" ["config":"Icinga\Data\Db\DbConnection":private]=> object(Icinga\Data\ConfigObject)#121 (4) { ["data":protected]=> array(7) { ["type"]=> string(2) "db" ["db"]=> string(5) "mysql" ["host"]=> string(9) "localhost" ["dbname"]=> string(16) "icinga2_director" ["username"]=> string(8) "director" ["password"]=> string(26) "LWiAJZkcByaOOKuzxULJKbCRKo" ["charset"]=> string(4) "utf8" } ["result":protected]=> NULL ["count":protected]=> NULL ["keyColumn":protected]=> NULL } ["dbType":"Icinga\Data\Db\DbConnection":private]=> string(5) "mysql" ["dbAdapter":"Icinga\Data\Db\DbConnection":private]=> object(Zend_Db_Adapter_Pdo_Mysql)#116 (12) { ["_pdoType":protected]=> string(5) "mysql" ["_numericDataTypes":protected]=> array(16) { [0]=> int(0) [1]=> int(1) [2]=> int(2) ["INT"]=> int(0) ["INTEGER"]=> int(0) ["MEDIUMINT"]=> int(0) ["SMALLINT"]=> int(0) ["TINYINT"]=> int(0) ["BIGINT"]=> int(1) ["SERIAL"]=> int(1) ["DEC"]=> int(2) ["DECIMAL"]=> int(2) ["DOUBLE"]=> int(2) ["DOUBLE PRECISION"]=> int(2) ["FIXED"]=> int(2) ["FLOAT"]=> int(2) } ["_defaultStmtClass":protected]=> string(21) "Zend_Db_Statement_Pdo" ["_config":protected]=> array(9) { ["host"]=> string(9) "localhost" ["username"]=> string(8) "director" ["password"]=> string(26) "LWiAJZkcByaOOKuzxULJKbCRKo" ["dbname"]=> string(16) "icinga2_director" ["persistent"]=> bool(false) ["options"]=> array(3) { ["caseFolding"]=> int(2) ["autoQuoteIdentifiers"]=> bool(false) ["fetchMode"]=> int(2) } ["driver_options"]=> array(4) { [2]=> int(10) [8]=> int(2) [3]=> int(2) [1002]=> string(180) "SET SESSION SQL_MODE='STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,ANSI_QUOTES,PIPES_AS_CONCAT,NO_ENGINE_SUBSTITUTION', NAMES utf8;" } ["port"]=> int(3306) ["charset"]=> NULL } ["_fetchMode":protected]=> int(5) ["_profiler":protected]=> object(Zend_Db_Profiler)#117 (4) { ["_queryProfiles":protected]=> array(0) { } ["_enabled":protected]=> bool(false) ["_filterElapsedSecs":protected]=> NULL ["_filterTypes":protected]=> NULL } ["_defaultProfilerClass":protected]=> string(16) "Zend_Db_Profiler" ["_connection":protected]=> object(PDO)#126 (0) { } ["_caseFolding":protected]=> int(2) ["_autoQuoteIdentifiers":protected]=> bool(false) ["_allowSerialization":protected]=> bool(true) ["_autoReconnectOnUnserialize":protected]=> bool(false) } ["tablePrefix":"Icinga\Data\Db\DbConnection":private]=> string(0) "" } ["stats":protected]=> array(2) { ["host"]=> object(stdClass)#187 (6) { ["icinga_type"]=> string(4) "host" ["cnt_object"]=> string(1) "1" ["cnt_template"]=> string(1) "1" ["cnt_external"]=> string(1) "0" ["cnt_apply"]=> string(1) "0" ["cnt_total"]=> string(1) "2" } ["hostgroup"]=> object(stdClass)#188 (6) { ["icinga_type"]=> string(9) "hostgroup" ["cnt_object"]=> string(1) "0" ["cnt_template"]=> string(1) "0" ["cnt_external"]=> string(1) "0" ["cnt_apply"]=> string(1) "0" ["cnt_total"]=> string(1) "0" } } ["defaultAttributes":protected]=> NULL ["attributes":protected]=> NULL ["hasBeenAssembled":protected]=> bool(true) ["contentSeparator":protected]=> string(0) "" ["content":"dipl\Html\Html":private]=> array(0) { } ["contentIndex":"dipl\Html\Html":private]=> array(0) { } }

**Comment by Thomas-Gelf** [comment]
Ooops... sorry, this contained your DB password. I removed it from your comment, but still - you should change it once we're done here. Now, the output itself looks good. Now please try this one:

```patch
     public function getSummary()
     {
         $result = '';
         if (! empty($this->requiredStats)) {
+            reset($this->requiredStats);
             $result .= $this->statSummary(current($this->requiredStats));
```

**Comment by bmccorkle** [comment]
lol, I noticed that after posting, I'll make sure that gets changed.   Yes, your change seems to have worked!   I'm not big into programming, why did this seem to only affect the FreeBSD users?

![capture-icinga2](https://user-images.githubusercontent.com/36084927/36506405-8b60838e-1724-11e8-9fce-bf9c70c14924.JPG)

**Comment by Thomas-Gelf** [comment]
This is very strange... What's your PHP version? I have no idea why this shouldn't work as expected - and I cannot believe that PHP array pointers would behave differently on FreeBSD. Pushing this line would be no problem, but I'd first really prefer being able to figure out what went wrong here.

**Comment by bmccorkle** [comment]
The box is pretty new, it is running PHP 5.6.33 and Apache 2.4.29

**Comment by Thomas-Gelf** [comment]
The executed code is more or less [this](https://3v4l.org/fpjNT) - nothing special. I double-checked, the dashlet failing for you is the very first one (HostObject), it's called only once, the array is accessed only there. Very, very strange.

**Comment by Thomas-Gelf** [comment]
And, your dump shows that the array contains two values. Just, the pointer is AFTER the last element and not at it's beginning.

**Comment by Thomas-Gelf** [comment]
FreeBSD applies some [patches](https://svnweb.freebsd.org/ports/head/lang/php56/files/) to PHP, some affect lists - but I didn't find a smoking gun or so. Guess I'll implement above link and search for code occurrences looking similar. But not today, it's pretty late over here.

**Comment by bmccorkle** [comment]
Thanks Thomas.  I didn't get anything googling around myself for similar issues.  I appreciate all the help in getting this up and running.

**Comment by Thomas-Gelf** [comment]
I'll push above fix. We have other places in the code where `current()` is being used, in case you'll encounter similar issues please let me know.
