### ISSUE TITLE
CURL ERROR: Connection timed out after 3000 milliseconds

### ISSUE THREAD

**Issue by donillogit** [Icinga/icingaweb2-module-director#768]
Hi,

using the kickstart assistant to complete director installation I get this error:
CURL ERROR: Connection timed out after 3000 milliseconds

Any hints to solve this problem. I used the current versions of Ubuntu 16.04 LTS and the latest version of director from git.

Kind regards
Sebastian

**Comment by Thomas-Gelf** [comment]
Guess you either didn't create an API user, enabled the API listener (and restarted Icinga 2) - or your Director isn't able to reach your Icinga 2 for whatever reason (routing, firewall).

Cheers,
Thomas
