### ISSUE TITLE
Add ability to set enable_flapping for Hosts and Services

### ISSUE THREAD

**Issue by Tontonitch** [Icinga/icingaweb2-module-director#769]
Hello, 
Request similar to #546 , but for the enable_flapping attribute.
It would be nice to have it available for host and service definitions, especially for templates.
Would be in the "check execution" part, with attributes like "Enable event handlers", ...
Link to the doc where to find the attribute description: http://docs.icinga.org/icinga2/latest/doc/module/icinga2/chapter/object-types#objecttype-service
Regards,
Yannick

**Comment by dnsmichi** [comment]
I'd suggest to wait until icinga/icinga2#4982 is fixed.

**Comment by lazyfrosch** [comment]
duplicates #330
