### ISSUE TITLE
nrpe argumentlist problem

### ISSUE THREAD

**Issue by dgoeger** [Icinga/icingaweb2-module-director#770]
Hi,

i got a Problem with the NRPE Argumentlist.
I need a check-command like this one:
./check_nrpe -H <HOST> -c Check_DriveSize -a "warn=free<10%" "crit=free<5%"

If i deploy it with director the service like this:
![grafik](https://cloud.githubusercontent.com/assets/16332391/22645587/099ffd9e-ec68-11e6-9d5f-cde0b7af27dc.png)

the check is invalid, because the argument list is "warn=free<10% crit=free<5%".
Is there a workaround to deploy this check with director?

**Comment by mbassett** [comment]
maybe another instance of #638

**Comment by mbassett** [comment]
I would highly recommend ditching NRPE and switching to icinga agent anyhow.

**Comment by ktella** [comment]
I had a similar issue. I was able to get it working. Below is the sample config.

Example: check_mem config from nrpe.cfg
command[check_mem]=/opt/nrpe/libexec/check_mem.pl -f -C -w $ARG1$ -c $ARG2$

![nrpe](https://cloud.githubusercontent.com/assets/19876555/22842108/0de81dcc-efa2-11e6-8e18-8846a0cd23fe.png)

Arguments for some plugins work when they are given like "20 10" no quotes.

If they dont....you have to give them like 20!10

**Comment by dnsmichi** [comment]
If nrpe_arguments would be array, you can pass them as elements one by one. Though I'm not sure if the form currently supports it.

**Comment by Thomas-Gelf** [comment]
Just go to your data fields and change nrpe_arguments to be an array. As suggested by @dnsmichi, that's it. Array data fields have been documented [here](https://github.com/Icinga/icingaweb2-module-director/blob/master/doc/14-Fields-example-interfaces-array.md).
