### ISSUE TITLE
Error when deploying newly built notification

### ISSUE THREAD

**Issue by fideldidum** [Icinga/icingaweb2-module-director#771]
when i try to deploy a configured notification i get the error below. I'm no expert, although i hope to be one soon... :), but shouldn't the states be in quotes?
This happens in the latest git version and also happened with older versions.
Is it an Error I made or could circumvent?

==============Error when deploying changes========================

> critical/config: Error: Validation failed for object 'hostl!Windows CPU!Pikett Service Notification' of type 'Notification'; Attribute 'states': State filter is invalid.
Location: in [stage]/zones.d/master/notification_apply.conf: 5:5-5:40
[stage]/zones.d/master/notification_apply.conf(3): 
[stage]/zones.d/master/notification_apply.conf(4):     assign where host.vars.pikett_notification == "true"
[stage]/zones.d/master/notification_apply.conf(5):     states = [ Critical, Down, Unknown ]
                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[stage]/zones.d/master/notification_apply.conf(6):     types = [ Custom, Problem ]
[stage]/zones.d/master/notification_apply.conf(7):     users = [ "user" ]

=============================================================

below the config i want to deploy via director
note: this config was created entirely with the director.

============config===================
`
apply Notification "Pikett Service Notification" to Service {
    import "generic-director-service-notification"

    assign where host.vars.pikett_notification == "true"
    states = [ Critical, Down, Unknown ]
    types = [ Custom, Problem ]
    users = [ "Pikett" ]
}

apply Notification "Pikett Host Notification" to Host {
    import "generic-director-host-notification"

    assign where host.vars.pikett_notification == "true"
    states = [ Critical, Down, Unknown ]
    types = [ Custom, Problem ]
    users = [ "Pikett" ]
}
`
================================

**Comment by mbassett** [comment]
cannot have quotes around the true value.

#729 #739

**Comment by fideldidum** [comment]
shouldnt be a problem here, because i created a string list with true and false for testing something different. also, the error message reads:
'Notification'; Attribute 'states': State filter is invalid.
and in some icinga2 notification examples the types and states have quotes around them...

correct me if im wrong.

**Comment by mbassett** [comment]
this is how the preview tab showed up for my notification user that i have doing hipchat alerts

object User "hipchat" {
    import "Standard User Email"

    display_name = "Hipchat User"
    email = "redacted"
    enable_notifications = true
    states = [ Critical, Down, OK, Unknown, Up, Warning ]
    types = [
        Acknowledgement,
        Custom,
        DowntimeEnd,
        DowntimeRemoved,
        DowntimeStart,
        FlappingEnd,
        FlappingStart,
        Problem,
        Recovery
    ]
}

template Notification "Notify-By-Hipchat-Host" {
    command = "notify-host-by-hipchat"
    users = [ "hipchat" ]
}

**Comment by fideldidum** [comment]
thanx for the fast answer! 
ill check my notification config. if your configuration is working then ther must be a problem with how i configured mine. shall i leave this issue open and report back what the problem was or should i close it since it doesnt seem to be a bug. whats the policy here, its my first interaction with this project and with github in general... :)

**Comment by mbassett** [comment]
I'm not sure on the proper etiquette either.  However, it's usually nice to followup with what fixed your issue and a confirmation it is all working.  

I believe you can comment after an issue is closed as well.

**Comment by fideldidum** [comment]
i know have the state/type filter only set on the user level and the config deploys fine...
So you guessed right. 
Thanks for the help!
