### ISSUE TITLE
Preview of Service with variable assigned to a variable is inconsistent

### ISSUE THREAD

**Issue by widhalmt** [Icinga/icingaweb2-module-director#772]
Hi!

I have the following in a service definition:

    vars.snmp_community = host.vars.snmp_community

When I try to create this with director we figured out we have to escape the assigned variable with `$`.

    vars.snmp_community = $host.vars.snmp_community$

When clicking on `Preview` I get what I expect:

    vars.snmp_community = host.vars.snmp_community

But when I deploy the configuration, go back to the service and click `Preview` again I see the following:

    vars.snmp_community = "$host.vars.snmp_community$"

This is what Director writes into the Icinga 2 core as well. Both versions work but I'm curious why the Preview renders one time one version and another time the other.

Cheers,
Thomas

**Comment by Thomas-Gelf** [comment]
@widhalmt: while I didn't yet try to reproduce this, why are you even trying to do so? Doesn't the service already get that variable from the host without you configuring anything at all?

**Comment by widhalmt** [comment]
Now that I think of it - it definitively should. Since this was from a past project I'm not totally sure if we tried it and didn't succeed or if I was just not thinking straight.

Anyway, this should apply to assigning other variables as well. Sometimes I might have to assign some custom variables to variables used as macros.

**Comment by sahnd** [comment]
> Anyway, this should apply to assigning other variables as well. Sometimes I might have to assign some custom variables to variables used as macros.

That is what this issue is about. When I use several snmp based monitoring plugins (from ITL) I do not want to define my snmp credentials for every different variable of all the different plugins/Check command templates. I do want to define the credentials once per host/hostgroup and use them for all plugins.
With icinga-director I can do this as @widhalmt wrote, but it's a bit confusing.

**Comment by Thomas-Gelf** [comment]
This should no longer be the case, rendering should be the same in all places. When still facing such inconsistencies please let me know
