### ISSUE TITLE
director parsing $-sign

### ISSUE THREAD

**Issue by korzens** [Icinga/icingaweb2-module-director#774]
If you use a $-sign as a value in a variable, the following error occurs:
Error: Validation failed for object 'hostname!disk /var' of type 'Service'; Attribute 'vars' -> 'snmp_storage_name': Closing $ not found in macro format string '^/var$'.

The reason why I want to use a $-sign is because of the check_snmp_storage.pl check.
./check_snmp_storage.pl -H 127.0.0.1  -m ^/var$ -C public

Escaping with "\$" doesn't work either.

**Comment by mbassett** [comment]
Eh this is not a director issue.  $ in icinga/icinga2 is macro format and can only be used for macros.

$host.address$   etc.   

I know of no way to escape that character

**Comment by korzens** [comment]
I re-read the check_snmp_storage.pl help and found the parameter "-r" which helped in this case.
I close this issue
