### ISSUE TITLE
Deploy of Incinga2 Config aborts with out of memory

### ISSUE THREAD

**Issue by jvigna** [Icinga/icingaweb2-module-director#775]
I get this error when deploying a Config with just default Director setup and some host-templates created by the import functionality of Director:

`Fatal error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 130968 bytes) in /usr/share/icingaweb2/modules/director/library/Director/Objects/IcingaObject.php on line 157`

I traced the problem that over the import I could create a circular inheritance my generic-host templates imports again the generic-host template and if I go to one of the Template objects it is told to me:

![image](https://cloud.githubusercontent.com/assets/435688/22729310/80f877d8-ede2-11e6-9705-68c46bee35ee.png)

The fix is obviously to:

1. Fix my import rule to not touch the already created generic-host template
2. Fix manually the recursive inheritance by just go inside the generic-host template and save it again from the WUI

IMO that if director already knows about this recursive inheritance he should not try to resolve it in the Deploy going out of memory.

**Comment by Thomas-Gelf** [comment]
Thanks your reporting this. I can reproduce the issue, should have been introduced with 1.3.0. The `getSingleResolvedProperty()` method is looping here - and doesn't trigger loop detection. Patch is as simple as follows:

```patch
--- a/library/Director/Objects/IcingaObject.php
+++ b/library/Director/Objects/IcingaObject.php
@@ -1053,6 +1053,10 @@ abstract class IcingaObject extends DbObject implements IcingaConfigRenderer
         }
 
         /** @var IcingaObject $object */
+        if ($this->hasBeenLoadedFromDb()) {
+            $this->triggerLoopDetection();
+        }
+
         foreach (array_reverse($this->imports()->getObjects()) as $object) {
             $v = $object->getSingleResolvedProperty($key);
             if (null !== $v) {
```

I'll postpone merging this into master, until I either found a better place for fixing this or at least made sure that it has no impact on rendering performance.

Cheers,
Thomas

**Comment by Thomas-Gelf** [comment]
Did some intense testing with this. While it doesn't cost additional memory, rendering time goes up by 10-15% with large configurations. The fix would render an invalid configuration instead of stopping the rendering process, IMO this wouldn't be a big improvement. Therefore, and as the GUI shows the error and allows to clean it up, I'll postpone this.

**Comment by camskkz** [comment]
Hello, we seem to have a similar issue, dont know if I should create a new issue for it. 
When adding a new Host Template then modifying it afterwards, we can import the Host Template itself and get a php memory exceed limit.

Afterwards we cannot deploy the config nor select the host template without getting the same php memory exceed limit error.

When searching the ID of the object in the database, in the table 'icinga_host_inheritance', we can see that the host_id and the parent_host_id are the same.

To fix this issue we have to manually change the parent_host_id to another ID.

The director should not allow us to import the host template itself when modifying it.

**Comment by philomory** [comment]
I ran into the same issue as @camskkz, but with service templates. If you accidentally select in the UI that you want a service template to import itself (probably goes for any template, really), and attempt to store that config, then it is henceforth impossible to deploy the change _or_ revert the change (neither by using the "Restore former object" tool, nor by using the normal Director UI to edit the template properties).

**Comment by cstegm** [comment]
Could fix this issue by searching a row in the director table "icinga_service_inheritance" where a the value of service_id was equal to parent_service_id. I think this was causing a loop.

**Comment by cstegm** [comment]
You can find those templates easily using the following SQL statement:
`USE director; 
SELECT * 
FROM icinga_service_inheritance
WHERE service_id= parent_service_id;`

**Comment by Thomas-Gelf** [comment]
We'll address this with #1631
