### ISSUE TITLE
Wrong Detection of the Assign Function of Host Groups

### ISSUE THREAD

**Issue by Phantomi** [Icinga/icingaweb2-module-director#777]
Hey guys,

I've encounterd a Problem with the Cool Icinga Director. So I want to create a HostGroup with the Following Content:
HostGroup: Test.Local
Displayname: Test Domain
Apply where host.displayname contains Test.

So when i Deploy the Config
The follwoing Error occured:
critical/config: Error: Invalid right side argument for 'in' operator: "SERVERNAME / / Test.Local"
Location: in [stage]/zones.d/director-global/hostgroups.conf: 3:18-3:44
[stage]/zones.d/director-global/hostgroups.conf(1): object HostGroup "Test.Local" {
[stage]/zones.d/director-global/hostgroups.conf(2):     display_name = "Test"
[stage]/zones.d/director-global/hostgroups.conf(3):     assign where "Test" in host.display_name
                                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[stage]/zones.d/director-global/hostgroups.conf(4): }
[stage]/zones.d/director-global/hostgroups.conf(5): 

So i was pretty confused that in this Config he was applying the "in" instead of the "contains"

Iam pretty Shure you guys can fix this ;D

P.S. Sry for my bad englich (My native language is GERMAN so yeah ...)

**Comment by Thomas-Gelf** [comment]
Servus!

"contains" is for arrays only, sorry for the confusion. Should either be better documented or not shown where not applicable. To achieve what you want please use the "=" operator. As soon as you then use wildcards in your right-hand expression, the rendered string will change from `==` to `match(..)`. So, in your case, choose `=` and write `Test*` in the expression field. This should then render as

`assign where match("Test*", host.display_name)`

Cheers,
Thomas

**Comment by Phantomi** [comment]
Yeah! the deployment was succsessfull but i can only see the Group: Linux Hosts ...

Do i need to change things?!

**Comment by Thomas-Gelf** [comment]
Could you please go to the `Deployments` page, choose the last deployment, go to it's config and show me the related rendered hostgroup definition from `zones.d/director-global/hostgroups.conf` and a matching host definition?

**Comment by Phantomi** [comment]
object HostGroup "Test.Local" {
    display_name = "Test"
    assign where match("Test*", host.display_name)
}

**Comment by Thomas-Gelf** [comment]
> [..] and a matching host definition?

**Comment by Phantomi** [comment]
Host defenition?
Do you mean this? 

![grafik](https://cloud.githubusercontent.com/assets/22637939/22735029/3f3f29b6-edf8-11e6-9f5d-f7cf266e4e17.png)

**Comment by Thomas-Gelf** [comment]
> Could you please go to the Deployments page, choose the last deployment, go to it's config [..]

Directly there, just another file - something ending with `hosts.conf` micht be a good guess :-) The shown hosts wouldn't match, as they do not begin with Test, so it would be `*Test*` instead  of `Test*`.

**Comment by Thomas-Gelf** [comment]
Sorry, I accidentally closed this issue. Please let me know whether it works now

**Comment by Phantomi** [comment]
It dosent Work ... in the section overview i only see the Group Linux Servers :(

Here The Config files:
[zones.d/Icinga02/hosts.conf]
object Host "WIN-DIVIIFOQ5PG.Test.local" {
    import "WindowsAgent"

    display_name = "WIN2012S01 / JGR / Test.Local"
    address = "172.16.202.29"
}

object Host "WIN10W01.Test.local" {
    import "WindowsAgent"

    display_name = "Win10W01 / JGR / Test.Local"
    address = "172.16.202.43"
}

object Host "WIN2012S02.Test.local" {
    import "WindowsAgent"

    display_name = "WIN2012S02 / JGR / Test.Local"
    address = "172.16.202.40"
}

[zones.d/director-global/hostgroups.conf]
object HostGroup "Test.Local" {
    display_name = "Test"
    assign where match("*Test", host.display_name)
}

**Comment by Thomas-Gelf** [comment]
> [..] so it would be *Test* instead of Test*.

**Comment by Thomas-Gelf** [comment]
Hint: `assign where match("*Test", host.display_name)` -> this matches only names ENDING with `Test`

**Comment by Phantomi** [comment]
So iam so sorry :)

I was so confused :)

Now all things are Working properly 👍 

Thanks so much for your help :)
