### ISSUE TITLE
Custom Properties not displayed in v.1.3.0

### ISSUE THREAD

**Issue by korzens** [Icinga/icingaweb2-module-director#780]
In director v1.2.0 I added fields to a command. This Command was added to a service-template.
The service template was added to host  as a service with Host->Services->add.
But after upgrading to v1.3.0 the custom fields defined in the command aren't displayed, whereas in the preview page they're still visible.

**Comment by mbassett** [comment]
Pretty sure this has been fixed in latest master.

**Comment by korzens** [comment]
I tested the latest master and it is fixed, thank you.
