### ISSUE TITLE
failed to open stream: No such file or directory in /usr/local/www/icingaweb2/modules/director/library/Director/Test/Bootstrap.php on line 17 

### ISSUE THREAD

**Issue by merdna** [Icinga/icingaweb2-module-director#784]
OS : FreeBSD 11.0
Icinga Version: r2.6.1-1
Icingaweb2 Version 2.4.1
Director 1.3
got this :
./icingacli director test php
PHP Warning: require_once(Icinga/Application/Cli.php): failed to open stream: No such file or directory in /usr/local/www/icingaweb2/modules/director/library/Director/Test/Bootstrap.php on line 17
PHP Fatal error: require_once(): Failed opening required 'Icinga/Application/Cli.php' (include_path='.:/usr/local/share/ZendFramework/library') in /usr/local/www/icingaweb2/modules/director/library/Director/Test/Bootstrap.php on line 17
Warning: require_once(Icinga/Application/Cli.php): failed to open stream: No such file or directory in /usr/local/www/icingaweb2/modules/director/library/Director/Test/Bootstrap.php on line 17
Fatal error: require_once(): Failed opening required 'Icinga/Application/Cli.php' (include_path='.:/usr/local/share/ZendFramework/library') in /usr/local/www/icingaweb2/modules/director/library/Director/Test/Bootstrap.php on line 17
any Ideas?

**Comment by Thomas-Gelf** [comment]
Just curious, what do you want to achieve with that command? If you want to run our unit tests please check our [testing documentation](https://github.com/Icinga/icingaweb2-module-director/blob/master/doc/93-Testing.md). `icingacli director test php` is a leftover from when we called our tests that way, right now we stick to just calling `phpunit`. That old command should either be removed or turned into a wrapper for that.

**Comment by Thomas-Gelf** [comment]
No feedback so far.
