### ISSUE TITLE
"Parsing JSON result failed: Syntax error (RestApiResponse.php:88)"

### ISSUE THREAD

**Issue by merdna** [Icinga/icingaweb2-module-director#785]
OS : FreeBSD 11.0
Icinga Version: r2.6.1-1
Icingaweb2 Version 2.4.1
Director 1.3

when deploy to Icinga

**Comment by Thomas-Gelf** [comment]
Did you somehow restrict the API user created for the Director?

**Comment by dnsmichi** [comment]
Might be related: icinga/icinga2#4709

**Comment by Thomas-Gelf** [comment]
@merdna: really looks like the issue linked by @dnsmichi. In case that doesn't help please let us know!
