### ISSUE TITLE
Fixed memory limit

### ISSUE THREAD

**Issue by mwaldmueller** [Icinga/icingaweb2-module-director#789]
The memory_limit in "/usr/share/icingaweb2/modules/director/library/Director/Import/Sync.php" is currently fixed with 768M. In some (bigger) environments, it's necessary to increase the limit by hand.

Two approaches:
1. Increase fixed memory limit per default.
2. Configurable memory limit, e.g. in config.ini.

**Comment by lazyfrosch** [comment]
You can actually raise it via php.ini and Sync.php won't lower that limit.

**Comment by mwaldmueller** [comment]
Ah okay, thank you. Sorry, I haven't considered that.
That's sufficient in this case.
