### ISSUE TITLE
Commands being imported with constants in plain text

### ISSUE THREAD

**Issue by BongoEADGC6** [Icinga/icingaweb2-module-director#797]
We are using constants to keep passwords under wraps but it seems that if you import commands from the CoreAPI to the director, it will import the constant in plain text. 

Is there a suggested way to handle passwords in Icinga?

Thank you.

**Comment by Thomas-Gelf** [comment]
You could for example define your commands with the Director, and use constants in your command arguments by setting their type to "Icinga DSL" and using "return MyConstant;" as their value. This would allow you to have them only in your local configuration on every node.

**Comment by Thomas-Gelf** [comment]
Closing this one, as there is no way to import Constants as long as Icinga 2 exports only their value.
