### ISSUE TITLE
Importing hosts and services with complex vars gives strange results

### ISSUE THREAD

**Issue by xenuser** [Icinga/icingaweb2-module-director#799]
Hopefully I am reporting in the right repository. Let's say I have Icinga 2.6.1-1, Icingaweb 2.4.1-1 and the latest Director+Fileshipper modules installed.

I want to import hosts and services from CSV files, but JSON or XML would be fine, too. I tried all variants, but at the end I did not manage to achieve that my imported/generated host object looks like this:
```
object Host "testhost" {
    vars.disks["Disk C"] = {
        disk_cfree = "10%"
        disk_partitions = "C:"
        disk_wfree = "15%"
    }
}
```
Instead, my generated object looks like this:

```
object Host "testhost" {
    vars["disks['Disk C']"] = {
        disk_cfree = "10%"
        disk_partitions = "C:"
        disk_wfree = "15%"
    }
}
```

I tried to create the following CSV file and imported it via fileshipper:
```
id;service;service_template;check_command;vars_host;vars_service;check_interval;retry_interval;max_check_attempts;host;zone
3;SN-check_disk_win;generic-service-template;disk-windows;{"disks['Disk C']":{"disk_partitions":"C:","disk_wfree":"15%","disk_cfree":"10%"}};"servicevar";300;30;3;testhost;testzone

```

I also tried JSON and XML, both lead to the same result. In addition, I played around with escaping and tried many other variants of setting quotes etc,

My import source config:
* Source type is fileshipper
* Key column name is service
* Format is CSV
* Delimiter is ;
* Value enclosure is "
* Modifier: property vars_host, decoded as JSON
* Modifier: property vars_service, decoded as JSON

My sync rule config:
* Object type Host
* Update Policy Merge
* Purge No
* Property: source field ${vars_host}, destination vars
* Property: source field ${host}, destination object_name

Since I tried XML, JSON and CSV, my best guess is that the fileshipper and import mechanism is okey, but maybe the sync rule messes things up.

Any hint how to achieve what I need? Is this a bug or a layer 8 issue?

**Comment by mkayontour** [comment]
the syntax is ok like this. 
vars. is a dictionary like the disks too. 

it looks kinda strange but it should work like the other syntax.

**Comment by Thomas-Gelf** [comment]
Your JSON-encoding is not correct. To get what you want it should read like:

```json
{"disks":{"Disk C":{"disk_cfree": ... }, "Disk D": ... }}
```

**Comment by xenuser** [comment]
Thanks a lot! That looks right. I will be able to test it on Monday/Tuesday.

**Comment by xenuser** [comment]
I was able to test it, it works as expected. Thanks again for your fast help!

**Comment by Thomas-Gelf** [comment]
You're welcome!
