### ISSUE TITLE
Icinga Director und Argumente

### ISSUE THREAD

**Issue by JustinGrah** [Icinga/icingaweb2-module-director#801]
Hi Leute,
Ich habe ein kleines Problem.
Undzwar wollte ich gerne einen Open-E Server mit SNMP überwachen.
Dies ist zwar schon gelungen, aber leider nur wenn ich den Kommand dierekt in Putty ausführe.
Hier ist der Command den ich von Icinga ausführen lassen will: 
 ./check_snmp -H 172.16.202.51 -o 1.3.6.1.2.1.1.3.0 -P 2c

Ich habe schon den Kommand angelegt. Dieser geht auch. jetzt will ich das die verschiedenen Parameter mithilfe von Datenfeldern übergeben werden können. Das habe ich schon mal probehalber auspropiert mit einem Strin Datenfeld wo ich alle Parameter reingeschrieben habe.  Hier gibt Icinga mir aus, dass die Argumente nicht verabreitet werden können.

**Comment by Thomas-Gelf** [comment]
Leg dir wie wenn du das Command in Icinga 2 selbst erstellen würdest zum Commmand im Director entsprechende Arguments an. Also -H, -o, -P. Als Wert trägst du jeweils Macros ein, so wie in der manuellen Konfiguration. $address$ für -H, $snmp_oid$ für -o etc. Anschließend kannst du am Command oder am Service entsprechend Fields hinzufügen, mit schön sprechender Beschreibung.

Alle Arguments in einem String geht nicht, weil die dann aus Sicherheitsgründen gemeinsam escaped werden und für check_snmp wie ein großer Parameter aussehen.

**Comment by Phantomi** [comment]
Danke! Habe jetzt aber das Problem, das er sagt no oids Specified :( Hier ein paar screenshots von meiner Konfig

![grafik](https://cloud.githubusercontent.com/assets/22637939/23061072/b9f0ed02-f500-11e6-9216-042b72be3a9d.png)

![grafik](https://cloud.githubusercontent.com/assets/22637939/23061109/d55fade4-f500-11e6-909f-5b40471bbb56.png)

**Comment by Thomas-Gelf** [comment]
Eine OID in das entsprechende Feld (vermutlich beim Service) eingetragen?

**Comment by Phantomi** [comment]
Habe ich ja 😄

![grafik](https://cloud.githubusercontent.com/assets/22637939/23062172/0a36c10c-f505-11e6-8839-dfa040fa4a27.png)

**Comment by Thomas-Gelf** [comment]
@JustinGrah: verzeih die späte Rückmeldung. $address$ brauchst am Service nicht, das wird vom Host durchgereicht. Auch Community/Version wären ggf Felder, die häufig am Host mehr Sinn ergeben als am einzelnen Service. Aber unabhängig davon, das was du da zeigst sollte funktionieren.

Besteht das Problem immer noch, oder hast du es schon lösen können?

**Comment by Thomas-Gelf** [comment]
Closing issue as of no feedback. IMO it should work. Please feel free to re-open this or a new issue in case your problem persists.
