### ISSUE TITLE
variable overrides for applied services with "contains"-condition

### ISSUE THREAD

**Issue by vita2** [Icinga/icingaweb2-module-director#803]
hey tom,

i've built some service apply rules with a "contains item xyz in array" condition. unfortunately the services aren't visible in the hosts applied services tab so it isn't possible to add some custom overrides for the services. please could you fix the issue?

regards

```
zones.d/director-global/service_apply.conf
apply Service "nscp-local-disk-c" {
    import "nscp-local-disk"

    assign where host.vars.os == "windows" && "c" in host.vars.disks
    vars.nscp_disk_drive = [ "c" ]

    import DirectorOverrideTemplate
}
```

**Comment by Thomas-Gelf** [comment]
This should have been fixed today, could you please test the current master?

**Comment by vita2** [comment]
sure :) just tested it with the latest master but i can't see the required services

![1](https://cloud.githubusercontent.com/assets/25298055/23073473/f903c5ac-f535-11e6-91e0-d1c42c41c713.png)
![2](https://cloud.githubusercontent.com/assets/25298055/23073474/f91e41ac-f535-11e6-8f39-e5698d1acf0b.png)

**Comment by Thomas-Gelf** [comment]
Now I got it. Sorry, I misunderstood the initial comment. Looks like the resolving code seems to have problems with the "contains" operator

**Comment by Thomas-Gelf** [comment]
Guess I got this fixed, at least newly added tests are telling me so. Could you please try again?

**Comment by vita2** [comment]
thanks tom! of course i can test it again.

it works almost as it should:
![contains02](https://cloud.githubusercontent.com/assets/25298055/23545346/450a2192-fffb-11e6-80ea-7e0646eff50a.png)


by commit 5842e40fb693e0357e3016e6865af662cb5e783f the rendering and the preview of a service apply rule doesn't seem to work anymore if a "contains" rule was set. instead of the name of a host variable the word "null" is displayed:

![contains01](https://cloud.githubusercontent.com/assets/25298055/23544863/09841616-fff9-11e6-998d-af0a53bfbcc7.png)


same behavior in the configuration preview:
```
zones.d/director-global/service_apply.conf
apply Service "openmanage" {
    import "openmanage"

    assign where "omsa" in null

    import DirectorOverrideTemplate
}
```

**Comment by Thomas-Gelf** [comment]
ooops
