### ISSUE TITLE
Director Job service should survive "MySQL server has gone away"

### ISSUE THREAD

**Issue by Thomas-Gelf** [Icinga/icingaweb2-module-director#807]
Currently it keeps failing

**Comment by tobiasvdk** [comment]
Related to #438.

**Comment by Cuvo** [comment]
When running an Import Run on the director on a database with 6044 rows it works fine. When adding one more entry I get:

Storing import_source[ITIL DB] failed: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away...._

Related?

![image](https://user-images.githubusercontent.com/25362925/67010554-27ac5980-f0ee-11e9-8d0e-88eb21d3a2d3.png)

**Comment by Thomas-Gelf** [comment]
@Cuvo: thanks for pointing me to this issue. It should have been closed a while ago, as with v1.7 we easily survive the above scenario.

Your problem is not related to this. 6000 rows are no problem at all, you might want to check you DB server's log - eventually you hit a limit like [max_allowed_packet](https://dev.mysql.com/doc/refman/5.5/en/packet-too-large.html). In case this doesn't help please open a dedicated issue, we'll then dig deeper.

Cheers,
Thomas
