### ISSUE TITLE
question about inheritance of command variables

### ISSUE THREAD

**Issue by vita2** [Icinga/icingaweb2-module-director#812]
hey,

when i link certain custom fields with a service template should i see the default values of the command if the varname matches a fieldname, right?

why doesn't this work with my ping command?

i have attached some screenshots:

datafields:
![datafields](https://cloud.githubusercontent.com/assets/25298055/23213137/0e20a572-f90a-11e6-92b7-22807e4c73af.png)

command:
![command](https://cloud.githubusercontent.com/assets/25298055/23213139/0e23fb3c-f90a-11e6-84db-f8cd7db8834a.png)

service template:
![service-template-fields](https://cloud.githubusercontent.com/assets/25298055/23213136/0e1e3026-f90a-11e6-8335-e053e75ed501.png)
![service-template](https://cloud.githubusercontent.com/assets/25298055/23213138/0e21bd9a-f90a-11e6-84d6-06740c5d2e3a.png)

unfortunately the data fields remains empty :(

**Comment by mkayontour** [comment]
The values which are defined at a command aren't displayed as inherited variables. 

Only the Icinga 2 core will evaluate those macros and eventually set the default values if they don't get overridden. 
Have a look at the evaluation order of Icinga 2 at the [docs.icinga.org](https://docs.icinga.com/icinga2/latest/doc/module/icinga2/toc#!/icinga2/latest/doc/module/icinga2/chapter/monitoring-basics#macro-evaluation-order)

To display those default values would be a feature i guess.

**Comment by vita2** [comment]
the default values from the command are visible now. thank you for the fix  👍
