### ISSUE TITLE
hosts don't inherit overwritten serviceset variables from hosttemplates, only original values from serviceset

### ISSUE THREAD

**Issue by bcogel** [Icinga/icingaweb2-module-director#813]
I've defined a serviceset with several basic checks for linux system. Then I assigned this set to some hosttemplates. In one hosttemplate I overwrite some parameters (-c, -w, -i, -R ) for the disk check. 
and assign this hosttemplate to a couple of linux hosts.

These host show only the original parameters from the serviceset and the check is executed on the hosts with the parameters inherited from the original serviceset.

**Comment by bcogel** [comment]
I forgot: Director version is 1.3.1

Seems that variable inheritance works only like this: 

serviceset -> host
service -> host

And not like this: 
serviceset -> hosttemplate [-> hosttemplate] -> host
service -> hosttemplate [-> hosttemplate] -> host

I have to define several almost identical services and/or servicesets to use different values of service variables for host subsets. Or I have to overwrite the defaults for each single host...

**Comment by bcogel** [comment]
vars._override_servicevars is overwritten if I assign more than one hosttemplate to a host....
Same for hostgroups....

**Comment by Thomas-Gelf** [comment]
@bcogel: thanks, this last comment really helped to understand your issue!

**Comment by bcogel** [comment]
Sorry... sometimes you only see a strange result of a change and you don't know where to look... I've to get used to examine the preview if something weird happens after deploying in director...

**Comment by bcogel** [comment]
Can you give me a hint, when this will be fixed? We would like to switch production from Icinga 1 to Icinga 2 with director as soon as possible. At the moment I'm the only one who can keep the config of the old system up to date. For us this bug is a showstopper because we get a lot false alerts because limits and parameters are not properly inherited.

**Comment by Thomas-Gelf** [comment]
@bcogel: I pushed a fix for this, sorry for the delay. It would be great it you could let me know whether it completely fixes your use-case.

**Comment by bcogel** [comment]
On first sight it seems to work as desired. Only problem is that inherited values are not shown on all inheritance levels. But this is a separate problem for which I will open a new ticket. Together with some others...
