### ISSUE TITLE
Hostgroups can't be modified without an apply rule

### ISSUE THREAD

**Issue by Benedikt1992** [Icinga/icingaweb2-module-director#814]
After creating a hostrgoup it is not possible to change it's name without any apply rule. Since we choose the groups within the hostobject we don't have apply rules.

**Comment by Thomas-Gelf** [comment]
@Benedikt1992: could you please provide some more related details? What you're trying to achieve should just work, please go to Hosts -> Groups (the tab) -> choose your group, change the name. All related hosts should fine afterwards.

**Comment by Thomas-Gelf** [comment]
While trying to understand the linked issue I finally got it. Wasn't able to reproduce this as I misunderstood your description, and all my hostgroups already had apply rules. Will be fixed immediately.
