### ISSUE TITLE
Cannot Delete Service Templates

### ISSUE THREAD

**Issue by fideldidum** [Icinga/icingaweb2-module-director#816]
Im unable to delete service templates. I'm on the newest git version, but had the problem for some time now(at least 2-3 weeks). Everything else is pretty much working but i can not, for the life of me, find a way to delete service templates. Not in the gui and not on the cli.
Since imho, this would be a pretty big bug i hope I'm just doing something wrong/missing a step...

**Comment by log1-c** [comment]
As far as I know you can only delete service templates that are not used by any services.
If the template is used, the delete button is grey. Else the button is active and clickable

**Comment by fideldidum** [comment]
aaaaaaaand its gone......
lol. i thought i had it removed from alle references and so never really checked again.
thanx man.
