### ISSUE TITLE
clone hostgroup modify Anzeigename

### ISSUE THREAD

**Issue by tomabg** [Icinga/icingaweb2-module-director#817]
Hi,

after cloning a hostgroup it is not possible to modify the Anzeigename without setting an apply rule.
Creatings new hostgroup is possible without apply rule.
I use director 1.3.1.

BR
Thomas

**Comment by Thomas-Gelf** [comment]
@tomabg: sorry, I cannot follow you. I can perfectly clone a hostgroup and change it's "Anzeigename" afterwards.

**Comment by tomabg** [comment]
Hi Tom,

it is only possible if you assign the Hostgroup to something in my case...it says value is required and Speichern has no effect.

**Comment by Thomas-Gelf** [comment]
Could you please show me a related screenshot? I'm unable to reproduce this

**Comment by tomabg** [comment]
attached the screenshot

**Comment by Thomas-Gelf** [comment]
Now I got it. I'll close this in favor of #814 - describing the same issue. I'll immediately push a fix for this.
