### ISSUE TITLE
Two activities with same checksum - SQLSTATE[21000]: Cardinality violation

### ISSUE THREAD

**Issue by TimL20** [Icinga/icingaweb2-module-director#823]
Hi,
I installed Icinga 2.6.2 with icingaweb2 and the director 1.3.1 on ArchLinux just a view days ago to test the director. As database I use MariaDB, wich is ArchLinux default implementation of mysql.
Since yesterday I can't see the activity log and also can't deploy any configuration any more. It worked fine until yesterday.
I didn't change something big since it worked fine, just two things:
1. I created a new host.
2. I started a cronjob wich calls _icingacli director jobs run_ every 10 minutes.
I think the second thing is much more important...

The two jobs that are running with my cronjob call are a import and a sync. These two jobs import hosts of an exisisting database. The db is also just testing, there are only 12 hosts with hostname, ip and two custom vars.

The following thing is what occures:
![fehlermeldung](https://cloud.githubusercontent.com/assets/26107698/23451138/ee80ad84-fe5e-11e6-8b3d-103bdb1c3e9f.png)
(Activity log)

![fehlermeldung2](https://cloud.githubusercontent.com/assets/26107698/23451148/fa3f6d7c-fe5e-11e6-852f-78a73c678fdc.png)
(When I click on "Render config")

I found something interesting in the DB:
`SELECT config_checksum FROM director_deployment_log ORDER by id desc limit 1;`
and
`SELECT last_activity_checksum FROM director_generated_config WHERE checksum = (SELECT config_checksum FROM director_deployment_log ORDER by id desc limit 1 );`
just return one result (and I think they should). But:

```
MariaDB [director]> SELECT id FROM director_activity_log WHERE checksum = ( 
    -> SELECT last_activity_checksum FROM director_generated_config WHERE checksum = ( 
    -> SELECT config_checksum FROM director_deployment_log ORDER by id desc limit 1 ) );
+-----+
| id  |
+-----+
| 498 |
| 499 |
+-----+
2 rows in set (0.00 sec)
```

So as I understand it, there are two "activities" with the same checksum, and that makes trouble. I looked with SELECT * ... in this table; the two changes happened at the same time, and they are both caused by my cronjob call to `icingacli director jobs run` (I see that because the author of both changes is "cli").

So I'm not sure why this happened, but I think it should not...

As I said it's a test system, so I can test anything, including delete all :)

**Comment by Thomas-Gelf** [comment]
Two activities with the same checksum are allowed, so there is a bug in the query you are shown in that exception. However, there is very VERY low probability for this to happen, I didn't even experience it in a productive environment with more than a million entries in the activity log. And while it might happen, it is even less probable to meet it with two consecutive log entries.

Please show me the output of the following query:

```sql
SELECT
    id,
    object_type,
    object_name,
    old_properties,
    new_properties,
    author,
    change_time,
    LOWER(HEX(checksum)) AS checksum,
    LOWER(HEX(parent_checksum)) AS parent_checksum
  FROM director_activity_log
  WHERE id IN (497, 498, 499, 500)\G
```

In case the output shows sensible data please anonymize it. In that case however please me know whether you tweaked the result.

Thanks,
Thomas

**Comment by TimL20** [comment]
```
MariaDB [director]> SELECT
    ->     id,
    ->     object_type,
    ->     object_name,
    ->     old_properties,
    ->     new_properties,
    ->     author,
    ->     change_time,
    ->     LOWER(HEX(checksum)) AS checksum,
    ->     LOWER(HEX(parent_checksum)) AS parent_checksum
    ->   FROM director_activity_log
    ->   WHERE id IN (497, 498, 499, 500);
+-----+-------------+-----------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------+---------------------+------------------------------------------+------------------------------------------+
| id  | object_type | object_name     | old_properties                                                                                                                                                                                                             | new_properties                                                                                                                                                                                                                                 | author | change_time         | checksum                                 | parent_checksum                          |
+-----+-------------+-----------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------+---------------------+------------------------------------------+------------------------------------------+
| 497 | icinga_zone | director-global | NULL                                                                                                                                                                                                                       | {"is_global":true,"object_name":"director-global","object_type":"external_object"}                                                                                                                                                             | root   | 2017-02-28 14:11:00 | 6546ba32378ffba6947616c93228578b4be9f861 | 50a2a59d376344c54f6da9f5bf66a8ba02933a0a |
| 498 | icinga_host | 5               | {"object_name":"5","object_type":"object","display_name":"ICINGA2","address":"127.0.0.1","vars":{"Location":"Leipzig","OS":"Linux","Tests":"SSH Ping HTTP"},"imports":["generic-director-host"]}                           | {"address":"127.0.0.1","display_name":"ICINGA2","imports":["generic-director-host"],"notes":"Das ist die Testmaschiene selbst...","object_name":"5","object_type":"object","vars":{"Location":"Leipzig","OS":"Linux","Tests":"SSH Ping HTTP"}} | cli    | 2017-02-28 14:24:01 | 0d43f04ec39d4f279ac85871ce19612c56749a5e | 6546ba32378ffba6947616c93228578b4be9f861 |
| 499 | icinga_host | 5               | {"object_name":"5","object_type":"object","display_name":"ICINGA2","address":"127.0.0.1","vars":{"Location":"Leipzig","OS":"Linux","Tests":"SSH Ping HTTP"},"imports":["generic-director-host"]}                           | {"address":"127.0.0.1","display_name":"ICINGA2","imports":["generic-director-host"],"notes":"Das ist die Testmaschiene selbst...","object_name":"5","object_type":"object","vars":{"Location":"Leipzig","OS":"Linux","Tests":"SSH Ping HTTP"}} | cli    | 2017-02-28 14:24:01 | 0d43f04ec39d4f279ac85871ce19612c56749a5e | 6546ba32378ffba6947616c93228578b4be9f861 |
| 500 | icinga_host | 7               | {"object_name":"7","object_type":"object","display_name":"y4deulco0000001","address":"10.188.57.22","vars":{"Location":"Leipzig","OS":"Linux","Tests":"SSH Ping HTTP"},"imports":["Linux-Server","generic-director-host"]} | NULL                                                                                                                                                                                                                                           | cli    | 2017-02-28 14:48:01 | d11a7e79dd3b8b15c97839c326d863fe530e5d66 | 0d43f04ec39d4f279ac85871ce19612c56749a5e |
+-----+-------------+-----------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------+---------------------+------------------------------------------+------------------------------------------+
4 rows in set (0.00 sec)
```



As it's just test there are no sensible data...

**Comment by Thomas-Gelf** [comment]
That's VERY strange. 498 and 499 are completely identical, this should never happen. Is there anything special you can tell me about your MariaDB? Replication, custom tuning, proxy or similar? Something in your Syslog or MariaDB error log around 2017-02-28 14:24:01?

**Comment by Thomas-Gelf** [comment]
NB: you can fix this by running:

```sql
DELETE FROM director_activity_log WHERE id = 499;
```

But please preserve the current state with a `mysqldump` first. It would be great if you could provide me that dump, that would allow us to dig deeper into the problem while allowing you to continue with your work in the meantime. Eventually drop me a private mail, I'll then send you a link allowing you to upload the dump in a safe way.

**Comment by TimL20** [comment]
I found something, that should not be... My crontab showed this to me:
```
*/10 * * * * icingacli director jobs run
*/10 * * * * icingacli director jobs run
```

I don't know why it's there twice... But I guess that's the problem, it seems that the two calls were executed at the same time...

I already thought about fixing this by just deleting one of these two activities, but as it is a test system I thought I should understand why it happend. But thank you very much for your VERY fast help :)

**Comment by Thomas-Gelf** [comment]
That's a pretty good explanation :D I'll leave this issue open as IMO this should be fixed. Would in theory be easy to accomplish, it "just" needs to re-check log checksum consistency before committing the transaction. In case of an error the transaction should be rolled back. This is trickier than it sounds, as a sync might involve thousands of activities.

So yes, after deleting that line and the duplicate cronjob you should be fine. And please check your [jobs documentation](https://github.com/Icinga/icingaweb2-module-director/blob/master/doc/79-Jobs.md), it shows best practices of how to run jobs as a daemon. That would allow you to tweak run intervals through the GUI.

**Comment by Thomas-Gelf** [comment]
Never heard about this issue again. Now with the new background daemon it should no longer be possible to trigger this issue as shown above.
