### ISSUE TITLE
Editing hostgroups or servicegroups requires assign statement

### ISSUE THREAD

**Issue by bcogel** [Icinga/icingaweb2-module-director#825]
Director version 1.3.1

I can define a hostgroup 'test' with display name 'test' in director without any additional informations and save the entry. 

object HostGroup "test" {
    display_name = "test"
}

I can assign this hostgroup to a host or hosttemplate and it shows up in the icingaweb2 hostgroup list. 
When I want to edit the name or display name of the hostgroup, I'm unable to save the entry because director now requires an assign rule: "Value is required and can't be empty".  Same happens for servicegroups. I have to delete and recreate the group object.

I want to assign hostgroups through templates. It's easier to handle than to create a set of assignrules for a lot of strange hostnames  ;-).

**Comment by Thomas-Gelf** [comment]
This duplicates #814 and should have been fixed.

Cheers,
Thomas
