### ISSUE TITLE
Import/Sync array?

### ISSUE THREAD

**Issue by TimL20** [Icinga/icingaweb2-module-director#827]
Hi,
one of data types of a data field is array, and it works perfectly when adding values to a custom variable of type array (custom vars of a host e.g.) manually.
Now my question: is it possible to import such an array with Import and Sync rule? I tried `["...", "...", ...]` and also the same without brackets, but it didn't work. Is there any possibility to do this? It would by very nice.

**Comment by rai-n-air** [comment]
jep..:

I do it when importing Hosts.
The Hosts should have some "Roles" an I provide them via an array.
The trick is to decode the array when importing the Hosts:

Import source/Modifiers
Add property Modifier
Property*     (select the column which contains the array)
Modifier* = Decode a JSON string    

Then:
Sync Rule/Properties
Destination Field* = Custom variable
Custom variable*  = give the variable a name ...like "ROLES"
Source Column*   = the column you decodes in the Import source tab.

The Source has to be a JSON Array like this:
["ORA", "JAVA"]

It work fine for me.

good look!

**Comment by TimL20** [comment]
Thank you very much!
I have a very different use case but it works fine with the same solution.
