### ISSUE TITLE
feature request icingacli director service set list

### ISSUE THREAD

**Issue by Wintermute2k6** [Icinga/icingaweb2-module-director#828]
With the icingacli director 1.3.1 there is a show command

icingacli director service set show << for a single set>>
it would be nice to have if there would be something like 
icingacli director service set << list>> << for a list of all service sets >>

thanks in advance !

**Comment by Thomas-Gelf** [comment]
Here you go ;)

**Comment by Wintermute2k6** [comment]
thanks
