### ISSUE TITLE
Assign For with custom variables not working

### ISSUE THREAD

**Issue by friesoft** [Icinga/icingaweb2-module-director#830]
Our hosts have a array with all disks (vars.disks) imported using Director. I wanted to create a service which is executed by SSH using thresholds for warning and criticial for fine adjustment on each disk.

The config generated by director looks correct (see below) but the resulting service seems to lack the value from the disk array.

```
object Host "BAPM0" {
    import "OurLinuxHost"

    address = "172.31.15.43"
    groups = [ "linux", "sysE" ]
    vars.disks = [ "/", "/data", "/home", "/software" ]
}
```

```
template Service "Disk Mountpoint" {
    import "[Template] ssh-service (active)"

    vars.by_ssh_command = "~/libexec/check_disk.lin -p $config$ -w $disk_warn$ -c $disk_crit$"
    vars.disk_crit = 10
    vars.disk_warn = 15
}
```
```

apply Service "Disk Mountpoint " for (config in host.vars.disks) {
    import "Disk Mountpoint"

    assign where "linux" in host.groups && "sysT" in host.groups

    import DirectorOverrideTemplate
}
```

From the inspect button at the service:
```
    last_check_result: {
      active: true,
      check_source: "icinga0",
      command: [
        "/usr/lib64/nagios/plugins/check_by_ssh",
        "-C",
        "~/libexec/check_disk.lin -p  -w 15 -c 10",
        "-H",
        "172.31.15.43",
        "-l",
        "nagios",
        "-q",
        "-t",
        "60"
      ],
```
 The service names are correct as you can see in this screenshot:
![icinga2_mountpoint_apply_for](https://cloud.githubusercontent.com/assets/124109/23546136/7f94f0b4-fffe-11e6-9324-da4d82f82d3b.png)

Highlighting the problem again:
`        "~/libexec/check_disk.lin -p <MISSING> -w 15 -c 10",`

Using Director 402f0ed (one commit after 1.3.0 was tagged) and Icinga2 2.5.4

Is this an Icinga2 bug as the director config looks correct?

**Comment by Thomas-Gelf** [comment]
Please compare your configuration to the sample in our [documentation](https://github.com/Icinga/icingaweb2-module-director/blob/master/doc/15-Service-apply-for-example.md). You should add a field for your partition parameter to your applied service and use `$config$` as it's value.

**Comment by friesoft** [comment]
Before I tried to have the ssh_command in the apply-rule but this resulted in not working config:

`critical/config: Error: Error while evaluating expression: Tried to access undefined script variable 'disk_warn'`

```
apply Service "Disk Mountpoint " for (config in host.vars.disks) {
    import "Disk Mountpoint"

    assign where "linux" in host.groups && "sysT" in host.groups
    vars.by_ssh_command = "~/libexec/check_disk.lin -p " + config + " -w " + disk_warn + " -c " + disk_crit

    import DirectorOverrideTemplate
}
```

This looks more correct to be honest as we use the config variable where it is available. But then using the customvars from the import doesn't work :(

**Comment by friesoft** [comment]
Whops.. Thanks for the pointer :) Works now :)
You should get a 🥇 for your continuing and extremely fast support :)

**Comment by Thomas-Gelf** [comment]
@Thomas-Gelf proudly walks around with his new :1st_place_medal:
