### ISSUE TITLE
Endpoint name issue

### ISSUE THREAD

**Issue by lgravley** [Icinga/icingaweb2-module-director#834]
I was unable to re-establish a connection to the Endpoint "icingaMaster" (10.231.1.13:5665). When reconnecting to the configured Endpoint (icingaMaster:5665) I get an error: CURL ERROR: Could not resolve host: icingaMaster Please re-check your Icinga 2 endpoint configuration

Where do i validate my Endpoint Name?
IcingaHost is the url to the machine
Port is 5665
Api User and password can be found in /etc/icinga2/conf.d/api-users.conf

Do i need to generate an endpoint? If so where and how?

**Comment by mbassett** [comment]
looks to me like you are using a non routable name for icingamaster  
(could not resolve host)

Best practice is to set your icinga boxes up using their FQDN.

I'd start here:
https://github.com/Icinga/icingaweb2-module-director/blob/master/doc/24-Working-with-agents.md

**Comment by Thomas-Gelf** [comment]
In case using a FQDN is not an option you're required to set the `host`-property in your master's `Endpoint` definition to it's IP address, like this:

```
object Endpoint "icingaMaster" {
    host = "10.123.1.13"
}
```

Cheers,
Thomas
