### ISSUE TITLE
Notifications not Deploying

### ISSUE THREAD

**Issue by Stev-e** [Icinga/icingaweb2-module-director#841]
Hi,

**Icinga: 2.6.2
Icinga Director: 1.3.1**

I am having issues with Icinga Director; I have set up users, groups, timezones, templates and now I have created a notification but when it is deployed nothing happens. Notification template is for up/down, problem/recovery & custom.

I have tried many different if/ors to have it apply to my hosts but it doesn't apply - trying to send a custom notification as a test results in this in the icinga2.log

[2017-03-10 11:25:27 +0000] information/ExternalCommandListener: Executing external command: [1489145127] SEND_CUSTOM_HOST_NOTIFICATION;<server>;0;sh;test
[2017-03-10 11:25:27 +0000] information/Checkable: Checking for configured notifications for object '<server>'
[2017-03-10 11:25:27 +0000] information/Checkable: Checkable '<server>' does not have any notifications.

At the moment I have the notification set to deploy based on a variable set to true on the host;

![image](https://cloud.githubusercontent.com/assets/19776252/23793708/854180aa-0584-11e7-90d6-25a6facd777d.png)

I can see my user, the template and the command all present if I do icinga2 list object but it never seems to apply the actual notification?

Have I missed something?!

Cheers

**Comment by dnsmichi** [comment]
Seems that the external command omits the host name - it is an empty string.

```
SEND_CUSTOM_HOST_NOTIFICATION;;0;sh;test
```

How do you execute such a command? CLI, GUI, etc?

**Comment by Stev-e** [comment]
I omitted the server name from the output, but Github then omitted what I omitted it with! The server name is in the command output.

Can execute it through the icinga2-web gui.

thanks for replying so quick

**Comment by dnsmichi** [comment]
Ah! So you've used `<foo>` which replaces the angle brackets. Markdown tries to render that as HTML tags.

Got it, so it seems that the deployment happened but the assign where condition for the notification apply is wrong. How's `host.vars.notification` defined on your host?

**Comment by Stev-e** [comment]
That's pretty much it, Git noob unfortunately!

Field is defined as notification_enable, assigned to a specific host template which the host is importing.

  * vars
    * notification_enable = true
      % = modified in '/var/lib/icinga2/api/packages/director/ws.foo-1489144788-0/zones.d/foo/hosts.conf', lines 90:5-90:35

**Comment by dnsmichi** [comment]
I can't see that in the screenshot, but is the name of the `assign where` variable really `Host.vars.notification`? I'd change that to `host.vars.notification_enable` (note the lower case first character).

**Comment by Stev-e** [comment]
For some reason it doesn't show it properly once selected but it is the right one:

![image](https://cloud.githubusercontent.com/assets/19776252/23795065/76e59b70-058b-11e7-84c4-5194d3a63abb.png)

**Comment by dnsmichi** [comment]
Try to render the config preview and add that here please :)

**Comment by Stev-e** [comment]
OK so I've changed it to apply direct to 'name' and it has worked but it looked like this when looking for that variable;

apply Notification "11" to Host {
    import "Standard Host Notification Test"

    assign where host.vars.notification_enable == "true"
    user_groups = [ "Network Services" ]
}

I've tried it on other variables with no success

**Comment by Icinganator** [comment]
If you defined "notification_enable" as boolean custom variable, it looks like you ran into the same issue as described in issue #739 (https://github.com/Icinga/icingaweb2-module-director/issues/739).

**Comment by Thomas-Gelf** [comment]
Closing this, as a duplicate issue exists.
