### ISSUE TITLE
Audit-function - Content (author) missing

### ISSUE THREAD

**Issue by mthiel4** [Icinga/icingaweb2-module-director#849]
In the configurable ASCII-file the author is missing, e.g.:
2017-03-14T16:07:39+01:00 - INFO - (director) icinga_host[Windows 2k8r2] has been created: {"imports":["Windows"],"object_name":"Windows 2k8r2","object_type":"template"}

The information is available in the WebUI (Director-Module) :
[user123] create host "Windows 2k8r2" 	16:07:39

Please provide the appropriate information in the logfile, too. Thx.

**Comment by widhalmt** [comment]
I have some background information on this issue. If you can't reach the user, just ask me.
