### ISSUE TITLE
Skip quotes on assign statements with numeric values

### ISSUE THREAD

**Issue by mwaldmueller** [Icinga/icingaweb2-module-director#850]
<img width="426" alt="bildschirmfoto 2017-03-15 um 10 28 12" src="https://cloud.githubusercontent.com/assets/3973350/23941777/73c8d6b8-096a-11e7-8e5c-11f78272ac2b.png">
<img width="710" alt="bildschirmfoto 2017-03-15 um 10 29 38" src="https://cloud.githubusercontent.com/assets/3973350/23941778/73ccff86-096a-11e7-857b-5896cc63cdff.png">

**Comment by Thomas-Gelf** [comment]
I fear to break existing configurations when fixing this for all numeric string with any kind of filter. There will be explicit DataType-support for our filters in the future, related issues should exist. I'll now fix this for `<`, `<=`, `>` and `>=` - and leave `=` as is for now :-/
