### ISSUE TITLE
Allow cloning of external objects

### ISSUE THREAD

**Issue by widhalmt** [Icinga/icingaweb2-module-director#854]
A customer of mine uses a slightly enhanced version of a plugin which has a plugin check command in the ITL. I don't want to rebuild the whole plugin just to add 2 arguments. So allow the cloning of external objects into internal ones.

Cheers,
Thomas

**Comment by dgoetz** [comment]
This is better done by importing.
So create a new command foo_my, import foo, add arguments and fields and be happy! 😄

**Comment by widhalmt** [comment]
We had a somewhat "offline-online" discussion about the different scenarios you could use this. While importing and syncing is a great way to work around wrong or outdated ITL entries, because you can import upstream changes, cloning would allow to have some sort of fork if you create your own custom version of a plugin which might not follow upstream.

In short: I think importing is a good way to work around my problem and to work in some usecases but I still like the idea of cloning external objects into internal ones.

**Comment by Thomas-Gelf** [comment]
Makes sense to me
