### ISSUE TITLE
Applied Service is not shown in the Service List of Host

### ISSUE THREAD

**Issue by JuM1697** [Icinga/icingaweb2-module-director#855]
I automatically apply all of our services depending on different variables and everything works fine so far.
But now I have a host variable (Data type = Array) and apply a service to all hosts that have a special entry in this variable. The apply rule works like charm and the service is executed and applied to the host, BUT if you enter the host in the director overview and open up the services window for the host the new applied service is not shown (so you can't adjust parameters/variables of the services there).
But again: the service is correctly applied and runs on the host. The only problem is that you can't see if you try to edit the service in the service menu of the host using the director.

**Comment by Thomas-Gelf** [comment]
Please show the config preview for an affected host and for the related apply rule. Without my crystal ball :crystal_ball: it's otherwise hard to guess what your configuration might look like :stuck_out_tongue:

**Comment by JuM1697** [comment]
I thought the crystal ball is your usual tool ;)

hosts.conf:
object Host "mqde01admin01" {
    display_name = "_hostname_"
    address = "10.10.2.76"
    check_command = "hostalive"
    max_check_attempts = "3"
    check_interval = 1m
    retry_interval = 30s
    enable_notifications = true
    enable_active_checks = true
    enable_passive_checks = true
    enable_event_handler = false
    enable_perfdata = true
    volatile = false
    zone = "_zonename_"
    vars.disks = [ "c" ]
    vars.geolocation = "_location_"
    vars.ntp_server = "_ntp-server_"
    vars.os = "windows"
    vars["tsm-server"] = "_tsm-server_"
    vars.vCenter = "_vcenter_"
    vars.virtualcenter = "_vcenter_"
}

service_apply.conf:
apply Service "Disk C" {
    check_command = "nrpe"
    max_check_attempts = "5"
    check_interval = 5m
    retry_interval = 1m
    enable_notifications = true
    enable_active_checks = true
    enable_passive_checks = false
    enable_event_handler = false
    enable_perfdata = true
    volatile = false
    assign where "c" in host.vars.disks
    vars.nrpe_address = host.display_name
    vars.nrpe_arguments = [ "80%", "90%", "c" ]
    vars.nrpe_command = "disktest"
    vars.nrpe_no_ssl = host.vars.nrpe_no_ssl_host
    vars.nrpe_timeout = "180"

    import DirectorOverrideTemplate
}

**Comment by Thomas-Gelf** [comment]
Personal note: buy a :crystal_ball:. In the meantime, the provided information helps :) Are you using Director 1.3.1 or the latest master? Recently a few related fixes have been pushed, there used to be bugs with matching "in array"-type assign filters in user-space - but they SHOULD(:tm:) be gone.

**Comment by JuM1697** [comment]
I just re-installed the latest master just to make sure I have the correct version (still 1.3.1??) and I still have the problem

The service is still not shown in the "Applied Services" Section but is actually applied and executed...

**Comment by JuM1697** [comment]
NEVERMIND

**Comment by JuM1697** [comment]
I found my mistake... thanks a lot anyway

**Comment by Thomas-Gelf** [comment]
Great to hear that, as I haven't been able to reproduce this yet. Tests [here](https://github.com/Icinga/icingaweb2-module-director/blob/master/test/php/library/Director/Objects/HostApplyMatchesTest.php#L67) and [here](https://github.com/Icinga/icingaweb2-module-director/blob/master/test/php/library/Director/IcingaConfig/AssignRendererTest.php#L78) should (in theory) take care of this.

@JuM1697: Could you please leave us a short summary explaining what went wrong for you? Might help others stumbling over this issue.

**Comment by JuM1697** [comment]
The problem was really the latest master. I accidentally copied it to a wrong path which didn't fix the problem of course. But after I realized that, I copied it to the correct location and it worked immediately.

**Comment by Thomas-Gelf** [comment]
Cool, so you faced a problem in 1.3.1 that has been fixed in the meantime. Good to know - thank you!
