### ISSUE TITLE
Services applied as a service set using an assign rule are not displayed at host

### ISSUE THREAD

**Issue by dgoetz** [Icinga/icingaweb2-module-director#857]
Services applied as a service set using an assign rule are not displayed at host and so do not allow to override variables.

**Comment by Thomas-Gelf** [comment]
As far as I can recall this should work in the current master. Could you please check whether this is still an issue? What's confusing me right now is that this SHOULD have been fixed even before you opened this issue. At least I cannot find a related commit and "it works for me" ;-)

**Comment by dgoetz** [comment]
Yes, it was solved then by another commit. Thanks.
