### ISSUE TITLE
Export / Import config-items

### ISSUE THREAD

**Issue by mthiel4** [Icinga/icingaweb2-module-director#858]
Running Icinga2 and icinga2web with the director module in a 3-tier architecture (EVAL, INT, PROD), we need to have a method to export configuration elements like e. g. commands & servicetemplates. In the best case, each configuration item has a version, so the process to migrate the policy to a new environment is transparent for all stakeholders.

**Comment by widhalmt** [comment]
There is already an issue about import/export: [829](https://github.com/Icinga/icingaweb2-module-director/issues/829) . But this is no duplicate because the other issue wants to transfer the whole configuration and the focus of this issue are single objects.

**Comment by Thomas-Gelf** [comment]
This is nothing we can solve in a quick way, as there are lots of little ifs and whens to consider. I faced the same requirement more than once in real world and used to solve it with a partial mysqldump/re-import. I'd love to provide a generic solution for this, but please do not expect it very fast. This is a feature that will cause quite some work, while not being used by many people.

Nonetheless, it will be implemented sooner or later. We want to offer an easy way to ship "Command, Fields, Service Templates" together with check plugins. Once that has been solved we have most if not all components to tackle this issue. I like the idea with the compound version.

**Comment by Thomas-Gelf** [comment]
Please follow #1630
