### ISSUE TITLE
Feature Request: Import default datafields while kickstart

### ISSUE THREAD

**Issue by mcktr** [Icinga/icingaweb2-module-director#865]
Hi,

it would be very useful to import default datafields for custom variables of the ITL checks while kickstart. 

For example default datafields for the apt check:
![github_ticket_icinga_director](https://cloud.githubusercontent.com/assets/18580278/24160290/ac9ba000-0e61-11e7-869c-07715c08e8c8.PNG)

A import of the default datafields would save some time of configuration for the user.

**Comment by Thomas-Gelf** [comment]
Sorry @mcktr,

I have to reject this for now. The "problem" with fields is that they are often extremely customized with a lot of good hints targeting "internal users". Like "On our Oracle servers eventually consider blacklisting all disks of type XXX" or so. It's hardly possible to ship this (in a translatable way) to satisfy all the needs.

What we want to do in future is allowing for "config packages" containing for example Commands, related Service Templates and Fields. Especially for generic check commands that can be used in a lot of different variants, showing all the fields on all services using that command wouldn't be very helpful at all. So, while this feature would save you some time with your initial setup it would add quite some confusion for a lot of other users.

At the time being, Director is still a tool allowing experienced Icinga Admins who want to provide their users with a customized configuration front-end. This will change in future, as with every release we try to lower the entry barrier. One far day, Director will be the shiny tool you'll just throw there and everything will run automagically. As of today, it isn't. It requires you to dedicate some personal time.

Cheers,
Thomas
