### ISSUE TITLE
Disabled filter on hosts doesn't work

### ISSUE THREAD

**Issue by Copis** [Icinga/icingaweb2-module-director#866]
Today i wanted to review some machines previously disabled to definitively delete them on director but when i tried to filter for disabled hosts i not received any result.
I tried to set this filter like:
Disabled = Yes/yes/Y/y/True/true/0/1.... 

My environtment
Centos 7
Icinga 2.6.2
director 1.3.1
Icinga-web 2.4.1

![filter](https://cloud.githubusercontent.com/assets/410017/24195826/93f52f54-0efb-11e7-8167-308b58078f81.png)

**Comment by Thomas-Gelf** [comment]
I can confirm this

**Comment by Thomas-Gelf** [comment]
Does not longer apply I guess, as right now there is no such filter. Eventually we should bring them back, but for now this is "fixed"
