### ISSUE TITLE
Possible duplicates in  icinga_service

### ISSUE THREAD

**Issue by schroederjo** [Icinga/icingaweb2-module-director#868]
It is possible to create service templates with the same name, afterwards it is impossible to deploy the configuration and it is impossible to delete the second template. Is it possible to have a unique constraint on the table  icinga_service.object_name

Regards

Jörg

**Comment by Thomas-Gelf** [comment]
Unfortunately that's not possible, multiple entries with the same name are allowed for a) apply rules and b) service objects as long as their host_id differs. All of them sit in the same table. So no chance to get uniqueness guaranteed by the database in that table. Fixing this will require for some dedicated checks in "userspace", parts of this should already have been implemented. Still, there will be no guarantee that way, no protection against eventual race conditions. In the long run I'd love to split those different object types to have them in different tables.

To get your setup running again please chose one of those services in the GUI and rename it. That should work fine, afterwards it can be deleted.

I'll close this issue as it is already covered in #364.
