### ISSUE TITLE
Delete data field from apply rule options

### ISSUE THREAD

**Issue by JuM1697** [Icinga/icingaweb2-module-director#870]
Hi!

this isn't really an issue it's more kind of a question:
I defined a data field using the director. I used it a little bit but then deleted it again after some time. But now everytime I create an apply rule the old data field is still shown there as an option. How can I delete that one? 

Thanks for help

**Comment by Thomas-Gelf** [comment]
Guess there are still objects using variables based on that data field. I'd suggest to re-create such field, delete it again and to confirm your desire to delete all related custom vars.

Cheers,
Thomas

**Comment by Thomas-Gelf** [comment]
NB: in case this doesn't help please feel free to re-open this issue ;-)
