### ISSUE TITLE
import of xml-file lead to a php fatal error with allowed memory consumption after deployment

### ISSUE THREAD

**Issue by t-rex2** [Icinga/icingaweb2-module-director#874]
Hi guys,

I tried to import the following xml-file with icinga director and the icingaweb2-module "fileshipper". After running the synchronization rule in icinga director there comes the ordinary message about an outstanding activity. After deploying this new object, a php fatal error appears that the allowed memory is exceeded. From thereon the deployment functionality doesn't work anymore.

Also "tuning" the php memory settings doesn't show any effect (except the php error message shows the new php memory setting).

As a workaround I deleted the new object(s) in the director-mysql-dbs "director_activity_log" and "icinga_host". After that "dirty workaround" the deployment functionality is back. ;-)

Generally the import/synchronization functionality with icinga director is given. Because I tried successfully with csv-files and mysql-db. Therefore I expect that anything with my xml-import-settings or with the xml-import-functionality is wrong.

Below you can find my import and synchronization settings. If you have any question feel free to contact me, I'm glad to assist you. 

Cheers
Andrej

Feedback to Icinga Director: Thank you guys for this amazing project!!!

[vms_from_vcenter-server.zip](https://github.com/Icinga/icingaweb2-module-director/files/874959/vms_from_vcenter-server.zip)

######################################################
Importquelle
Quellentyp: Import from files (fileshipper)
Schlüsselspaltenname: vmName
File format: XML
Base directory: XML-Dateien fuer VM-Import aus den VCenter-Servern
File name: vms_from_vcenter-server.xml

######################################################
Synchronisationsregel
Regelname: vcenterserver - VMs aus VMware auslesen
Objekttyp: Host
Aktualisierungsrichtlinie: Zusammenführen
Bereinigen: Ja
Filterausdruck: leer gelassen
Regeleigenschaften -->  Quellenname """" Quellenfeld """" Ziel
                                       vcenterserver - VMs aus VMware auslesen """" ${vmName} """" import
                                       vcenterserver - VMs aus VMware auslesen """" ${vmName} """" display_name
                                       vcenterserver - VMs aus VMware auslesen """" ${guestOS} """" vars.os

#######################################################
Icinga Director --> Aktivitätslog --> "1 ausstehende Änderungen ausbringen"
Ergebnis = Fatal error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 130968 bytes) in /usr/share/icingaweb2/modules/director/library/Director/Data/Db/DbObject.php on line 531

**Comment by Thomas-Gelf** [comment]
Hi Andrej,

this -> `import ${vmName}` <- is where you're creating a loop. There is a loop detection in Director, but it jumps in only at the template level. What you're doing here is creating a host importing itself - Sync Rules allow you to do crazy stuff not available in the GUI, you should therefore be careful ;-)

Please import an (existing) Host template for your VMs, then sync run and deployment should be fine again.

Cheers,
Thomas

**Comment by t-rex2** [comment]
Hi Thomas,

you are right. De facto I had no import entry to an existing host template. Now it runs perfect with the following configuration:

Regeleigenschaften --> Quellenname """" Quellenfeld """" Ziel
vcenttk3 - VMs aus VMware auslesen """" ${vmName} """" display_name
vcenttk3 - VMs aus VMware auslesen """" ${guestOS} """" vars.os
vcenttk3 - VMs aus VMware auslesen """" ${vmName} """" address
vcenttk3 - VMs aus VMware auslesen """" Server (VM) """" import

Thanks a lot for your helpful information.

Best regards
Andrej

**Comment by Thomas-Gelf** [comment]
You're welcome!
