### ISSUE TITLE
Search in Variable: Syntax Error or access violation

### ISSUE THREAD

**Issue by RogerSik** [Icinga/icingaweb2-module-director#882]
Hello,

I created the data list Country and when Im searching in IcingaWeb2 for this field I get following error:
![2017-03-30 15_16_10-hosts __ icinga web](https://cloud.githubusercontent.com/assets/165814/24506067/81cdeec6-155c-11e7-9e94-43b2f10bc01a.png)

Same for Host Country Location.

![2017-03-30 15_16_28-hosts __ icinga web](https://cloud.githubusercontent.com/assets/165814/24506024/5fd222e2-155c-11e7-8a3f-f8496369bc35.png)

Outside from Icinga2 Director created variables are searchable.

**Comment by Thomas-Gelf** [comment]
Director doesn't do anything special with those variables, it renders plaintext configs and they are written to the IDO by Icinga 2. The error shown in the exception is thrown by Icinga Web 2, so I'd suggest to open a related ticket in [that tracker](https://github.com/Icinga/icingaweb2/issues). I'd love to move the ticket for you, but that's not possible on Github.

When opening the issue please mention also:
* DB schema/table encoding
* encoding setting for the IDO database resource in Icinga Web 2
* eventually your search string

Cheers,
Thomas
