### ISSUE TITLE
Kick start wizard not using new port

### ISSUE THREAD

**Issue by pcasis** [Icinga/icingaweb2-module-director#888]
Hi,

The kick start wizard seems to not using a different port from 5665 : 
![selection_087](https://cloud.githubusercontent.com/assets/25147189/24698457/048b8ede-19f1-11e7-91f1-98ffed6baf58.png)
I want to use port 8085 instead of 5665 but get this error message....

**Comment by Thomas-Gelf** [comment]
Director uses the given port and host only for the initial connection setup, then it imports the related configured Endpoint as defined in your Icinga 2 configuration. Please make sure that your Endpoint-definition reflects the correct port, then it should work fine (in theory).

**Comment by pcasis** [comment]
My bad ...
I defined the port in the API, ... not in endpoint definition ...
Sorry man ^^

**Comment by Thomas-Gelf** [comment]
Sure, but your API listener uses the Endpoint definition of the Endpoint matching the certificate used for the listener. Could you please show me those two objects from your Icinga configuration?
