### ISSUE TITLE
Check command issue

### ISSUE THREAD

**Issue by hammouni** [Icinga/icingaweb2-module-director#893]
i am running icingaweb2 with director.i need to monitor memory and other requirements.regards to many forums ,i need to dowload or create scripts that statisfy my requirement.after that i tryed to add the configuration manualy but in case of any modification on commands.conf. icinga stop running
i tried to configure with director but i get this error ."Check command 'mem' does not exist."
any idea ?
thanks

**Comment by awshew** [comment]
I have the same issue - Director does not seem to be synchronizing its check definitions to the agents.

**Comment by hammouni** [comment]
You have to add director zone template under /etc/icinga2/zone.conf .it will synchronise the configuration between different nodes

**Comment by awshew** [comment]
It was synchronizing a bunch of things, just not check_command definitions.

**Comment by Thomas-Gelf** [comment]
Did you eventually skip the [first step](https://github.com/Icinga/icingaweb2-module-director/blob/master/doc/04-Getting-started.md#define-a-new-global-zone) of the Getting Started documentation?

**Comment by awshew** [comment]
No, all steps were followed... the /var/lib/icinga2/api/zone was created, just the check_command definitions were not synchronized for some reason. It complained about simple checks, like "mem". The client is also running the icinga2 agent

**Comment by Thomas-Gelf** [comment]
Could you please show me your error? Eventually with a screenshot? Does it appear in the plugin output or in the startup log?

**Comment by awshew** [comment]
![image](https://cloud.githubusercontent.com/assets/26572445/25294849/0d8ac106-26af-11e7-925e-bc073a459b47.png)
No error per se - just seeing the aftermath of the sync and how the check fails.

**Comment by Thomas-Gelf** [comment]
Did you install the monitoring-plugins (or nagios-plugins) on that node?

**Comment by awshew** [comment]
It's actually a node running nagios (figured it was a good practice to monitor the monitoring host), so it has  nagios-plugins already

**Comment by awshew** [comment]
I just explicitly copied and pasted the check_mem.pl script from the icinga host to the nagios host (into /usr/lib64/nagios/plugins ) and gave it execute bits - still the same error. There's some underlying abstraction (the mapping between check command and the actual file being invoked) that seems to not be synchronized.

**Comment by Thomas-Gelf** [comment]
Oh, I see "mem" refers to a Perl script. It's command definition is shipped with Icinga 2 and to be found in

    /usr/share/icinga2/include/plugins-contrib.d/operating-system.conf

Does PluginContribDir in /etc/icinga2/constants.conf match the path to your check_mem.pl? There is nothing Director is going to synchronize about this.

**Comment by awshew** [comment]
both match:

root /usr/lib64/nagios/plugins # cat /etc/icinga2/constants.conf
/**
 * This file defines global constants which can be used in
 * the other configuration files.
 */

/* The directory which contains the plugins from the Monitoring Plugins project. */
const PluginDir = "/usr/lib64/nagios/plugins"

/* The directory which contains the Manubulon plugins.
 * Check the documentation, chapter "SNMP Manubulon Plugin Check Commands", for details.
 */
const ManubulonPluginDir = "/usr/lib64/nagios/plugins"

/* The directory which you use to store additional plugins which ITL provides user contributed command definitions for.
 * Check the documentation, chapter "Plugins Contribution", for details.
 */
const PluginContribDir = "/usr/lib64/nagios/plugins"

/* Our local instance name. By default this is the server's hostname as returned by `hostname --fqdn`.
 * This should be the common name from the API certificate.
 */
//const NodeName = "localhost"

/* Our local zone name. */
const ZoneName = NodeName

/* Secret key for remote node tickets */
const TicketSalt = ""

-

The contrib file points where the check_mem.pl would be too. Super strange. If this isn't something Director is supposed to manage, that's fine.

**Comment by Thomas-Gelf** [comment]
Do you have this problem with all your checks, or just mem?

**Comment by awshew** [comment]
mem, ifaces, all sorts... Found the issue:

root /etc/icinga2 # cat icinga2.conf
/** Icinga 2 Config - proposed by Icinga Director */

include "constants.conf"
include "zones.conf"
include "features-enabled/*.conf"

include <itl>
include <plugins>
// include <plugins-contrib>

Looks like director's proposed config is deliberately commenting out plugins-contrib?

**Comment by vita2** [comment]
you have to include the check_command definitions, found in ``/usr/share/icinga2/include/plugins-contrib.d/``. put the line ``include <plugins-contrib>`` in your ``icinga2.conf``

**Comment by Thomas-Gelf** [comment]
I'd have expected it to refuse to start in that case, that's strange... but sure, re-reading the error message - makes sense

**Comment by Thomas-Gelf** [comment]
> Looks like director's proposed config is deliberately commenting out plugins-contrib?

Not consciously... eventually this was the default long time ago. I'll create a dedicated issue for this.

**Comment by Thomas-Gelf** [comment]
As this issue seems to be solved for both of you, I'll close it. The related issue will be solved in one or the other way. Need to do some investigation on this first. Thanks for pointing me to this!

Cheers,
Thomas

**Comment by ultrakamish** [comment]
I have the same issue. Services and all other things synchronizes, but not the both of my CheckCommands. Config previews in Icinga Director:
```
object Host "debian" {
    address = "192.168.2.98"
    check_command = "hostalive"
    icon_image = "tux.png"
    vars.roles = [ "mongodb" ]
}
object Endpoint "debian" {
    host = "192.168.2.98"
    log_duration = 0s
}
object Zone "debian" {
    parent = "centos"                         // master node
    endpoints = [ "debian" ]
}
template Service "memory" {
    check_command = "Memory"
    max_check_attempts = "5"
    check_interval = 1m
    retry_interval = 30s
    command_endpoint = host_name
}
object CheckCommand "memory" {
    import "plugin-check-command"
    command = [ PluginDir + "/check_memory.py" ]
}
```
zones.conf:
```
object Endpoint NodeName {
}
object Zone ZoneName {
        endpoints = [ NodeName ]
}
object Zone "director-global" {global = true}

```
```
[root@centos ~]# icinga2 object list --name Memory
Object 'Memory' of type 'CheckCommand': <a lot of things, if needed, i could post them>
Object 'debian!memory' of type 'Service':  <...>
[root@centos ~]# icinga2 daemon --validate 
information/cli: Icinga application loader (version: v2.6.2)
information/cli: Loading configuration file(s).
information/ConfigItem: Committing config item(s).
information/ApiListener: My API identity: centos
warning/ApplyRule: Apply rule 'satellite-host' (in /etc/icinga2/conf.d/satellite.conf: 29:1-29:41) for type 'Dependency' does not match anywhere!
information/ConfigItem: Instantiated 1 ApiUser.
information/ConfigItem: Instantiated 1 ApiListener.
information/ConfigItem: Instantiated 3 Zones.
information/ConfigItem: Instantiated 1 FileLogger.
information/ConfigItem: Instantiated 2 Endpoints.
information/ConfigItem: Instantiated 13 Notifications.
information/ConfigItem: Instantiated 2 NotificationCommands.
information/ConfigItem: Instantiated 1 ScheduledDowntime.
information/ConfigItem: Instantiated 202 CheckCommands.
information/ConfigItem: Instantiated 1 Downtime.
information/ConfigItem: Instantiated 2 HostGroups.
information/ConfigItem: Instantiated 1 IcingaApplication.
information/ConfigItem: Instantiated 2 Hosts.
information/ConfigItem: Instantiated 1 User.
information/ConfigItem: Instantiated 1 UserGroup.
information/ConfigItem: Instantiated 3 TimePeriods.
information/ConfigItem: Instantiated 3 ServiceGroups.
information/ConfigItem: Instantiated 20 Services.
information/ConfigItem: Instantiated 1 CheckerComponent.
information/ConfigItem: Instantiated 1 ExternalCommandListener.
information/ConfigItem: Instantiated 1 GraphiteWriter.
information/ConfigItem: Instantiated 1 PerfdataWriter.
information/ConfigItem: Instantiated 1 IdoMysqlConnection.
information/ConfigItem: Instantiated 1 NotificationComponent.
information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
information/cli: Finished validating the configuration file(s).
```

On the client side:
```
root@debian:~# icinga2 object list --name Memory
<nothing!>
root@debian:~# icinga2 daemon --validate 
information/cli: Icinga application loader (version: r2.6.2-1)
information/cli: Loading configuration file(s).
information/ConfigItem: Committing config item(s).
information/ApiListener: My API identity: debian
warning/ApplyRule: Apply rule 'satellite-host' (in /etc/icinga2/conf.d/satellite.conf: 29:1-29:41) for type 'Dependency' does not match anywhere!
information/ConfigItem: Instantiated 1 ApiListener.
information/ConfigItem: Instantiated 2 Zones.
information/ConfigItem: Instantiated 1 FileLogger.
information/ConfigItem: Instantiated 2 Endpoints.
information/ConfigItem: Instantiated 2 NotificationCommands.
information/ConfigItem: Instantiated 14 Notifications.
information/ConfigItem: Instantiated 202 CheckCommands.
information/ConfigItem: Instantiated 1 Downtime.
information/ConfigItem: Instantiated 1 Host.
information/ConfigItem: Instantiated 1 IcingaApplication.
information/ConfigItem: Instantiated 2 HostGroups.
information/ConfigItem: Instantiated 1 UserGroup.
information/ConfigItem: Instantiated 1 User.
information/ConfigItem: Instantiated 13 Services.
information/ConfigItem: Instantiated 3 TimePeriods.
information/ConfigItem: Instantiated 3 ServiceGroups.
information/ConfigItem: Instantiated 1 ScheduledDowntime.
information/ConfigItem: Instantiated 1 CheckerComponent.
information/ConfigItem: Instantiated 1 ExternalCommandListener.
information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
information/cli: Finished validating the configuration file(s).
```
zones.conf:
```
/*
 * Generated by Icinga 2 node setup commands
 * on 2017-03-20 11:53:52 +0300
 */
object Endpoint "centos" {
        host = "192.168.0.71"
        port = "5665"
}
object Zone "master" {
        endpoints = [ "centos" ]
}
object Endpoint NodeName {
}
object Zone ZoneName {
        endpoints = [ NodeName ]
        parent = "master"
}
```
```
/** Icinga 2 Config - proposed by Icinga Director */
include "constants.conf"
include "zones.conf"
include "features-enabled/*.conf"
include <itl>
include <plugins>
include <plugins-contrib>
```

All other services that use default commands (defined by icinga, nor my hands or icinga director) are fine.
In icingaweb2 host is up, but service is Unknown, and "Check command 'Memory' does not exist".
As you can see, i uncommented the "include <plugins-contrib>", but this didn't help.
What should i do?...
