### ISSUE TITLE
Icinga2 configuration on slave node failed because of timeperiods.conf

### ISSUE THREAD

**Issue by shaguftahkhanam10** [Icinga/icingaweb2-module-director#900]
Hi All,

I have configured icinga2 on master node. It is running without any error.

I am also configuring icinga2 on slave node. When I installed icinga2 timeperiods.conf was not installed by default so I manually created the timeperiods.conf. but after running icinga2 it is showing error as given below.
root@slave_01:~# systemctl status icinga2.service
● icinga2.service - Icinga host/service/network monitoring system
   Loaded: loaded (/lib/systemd/system/icinga2.service; enabled)
   Active: failed (Result: exit-code) since Thu 2017-04-13 06:23:36 EDT; 42min ago
  Process: 24027 ExecStart=/usr/sbin/icinga2 daemon -e ${ICINGA2_ERROR_LOG} (code=exited, status=1/FAILURE)
  Process: 23967 ExecStartPre=/usr/lib/icinga2/prepare-dirs /usr/lib/icinga2/icinga2 (code=exited, status=0/SUCCESS)
 Main PID: 24027 (code=exited, status=1/FAILURE)

Apr 13 06:23:36 slave_01 icinga2[24027]: Location: in /etc/icinga2/conf.d/timeperiods.conf: 27:1-27:25
Apr 13 06:23:36 slave_01 icinga2[24027]: /etc/icinga2/conf.d/timeperiods.conf(25): }
Apr 13 06:23:36 slave_01 icinga2[24027]: /etc/icinga2/conf.d/timeperiods.conf(26):
Apr 13 06:23:36 slave_01 icinga2[24027]: /etc/icinga2/conf.d/timeperiods.conf(27): object TimePeriod "never" {
Apr 13 06:23:36 slave_01 icinga2[24027]: ^^^^^^^^^^^^^^^^^^^^^^^^^
Apr 13 06:23:36 slave_01 icinga2[24027]: /etc/icinga2/conf.d/timeperiods.conf(28):  import "legacy-Timeperiod"
Apr 13 06:23:36 slave_01 icinga2[24027]: /etc/icinga2/conf.d/timeperiods.conf(29):  display_name = "Icinga 2 never TimePeriod"
Apr 13 06:23:36 slave_01 icinga2[24027]: [2017-04-13 06:23:36 -0400] critical/config: 3 errors
Apr 13 06:23:36 slave_01 systemd[1]: icinga2.service: main process exited, code=exited, status=1/FAILURE
Apr 13 06:23:36 slave_01 systemd[1]: Unit icinga2.service entered failed state.

And when I ran icinga2 daemon -C it is showing this error
root@slave_01:~# icinga2 daemon -C
information/cli: Icinga application loader (version: r2.6.2-1)
information/cli: Loading configuration file(s).
information/ConfigItem: Committing config item(s).
information/ApiListener: My API identity: slave_01
critical/config: Error: Type 'TimePeriod' does not exist.
Location: in /etc/icinga2/conf.d/timeperiods.conf: 1:0-1:23
/etc/icinga2/conf.d/timeperiods.conf(1): object TimePeriod "24*7" {
                                         ^^^^^^^^^^^^^^^^^^^^^^^^
/etc/icinga2/conf.d/timeperiods.conf(2): import "legacy-Timeperiod"
/etc/icinga2/conf.d/timeperiods.conf(3):  display_name = "Icinga 2 24*7 TimePeriod"

critical/config: Error: Type 'TimePeriod' does not exist.
Location: in /etc/icinga2/conf.d/timeperiods.conf: 15:1-15:24
/etc/icinga2/conf.d/timeperiods.conf(13): }
/etc/icinga2/conf.d/timeperiods.conf(14):
/etc/icinga2/conf.d/timeperiods.conf(15): object TimePeriod "9to5" {
                                          ^^^^^^^^^^^^^^^^^^^^^^^^
/etc/icinga2/conf.d/timeperiods.conf(16): import "legacy-timeperiod"
/etc/icinga2/conf.d/timeperiods.conf(17): display_name = "Icinga 2 9to5 TimePeriod"

critical/config: Error: Type 'TimePeriod' does not exist.
Location: in /etc/icinga2/conf.d/timeperiods.conf: 27:1-27:25
/etc/icinga2/conf.d/timeperiods.conf(25): }
/etc/icinga2/conf.d/timeperiods.conf(26):
/etc/icinga2/conf.d/timeperiods.conf(27): object TimePeriod "never" {
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^
/etc/icinga2/conf.d/timeperiods.conf(28):  import "legacy-Timeperiod"
/etc/icinga2/conf.d/timeperiods.conf(29):  display_name = "Icinga 2 never TimePeriod"

critical/config: 3 errors

This is the timeperiods.conf  file of icinga2:---------------

object TimePeriod "24*7" {
import "legacy-Timeperiod"
 display_name = "Icinga 2 24*7 TimePeriod"
 ranges = {
 "monday" = "00:00-24:00"
 "tuesday" = "00:00-24:00"
 "wednesday" = "00:00-24:00"
 "thursday" = "00:00-24:00"
 "friday" = "00:00-24:00"
 "saturday" = "00:00-24:00"
 "sunday" = "00:00-24:00"
 }
}

object TimePeriod "9to5" {
import "legacy-timeperiod"
display_name = "Icinga 2 9to5 TimePeriod"
 ranges = {
 "monday"       = "09:00-17:00"
 "tuesday"      = "09:00-17:00"
"wednesday" = "09:00-17:00"
 "thursday"     = "09:00-17:00"
"friday"        = "09:00-17:00"
 }
}

object TimePeriod "never" {
 import "legacy-Timeperiod"
 display_name = "Icinga 2 never TimePeriod"
 ranges = {
 }

}

Following is the templates.conf of slave node:-----------------
/*
 * Generic template examples.
 */
/**
 * Provides default settings for hosts. By convention
 * all hosts should import this template.
 *
 * The CheckCommand object `hostalive` is provided by
 * the plugin check command templates.
 * Check the documentation for details.
 */
template Host "generic-host" {
  max_check_attempts = 3
  check_interval = 1m
  retry_interval = 30s
TimePeriod = "24*7"
  check_command = "hostalive"
}
/**
 * Provides default settings for services. By convention
 * all services should import this template.
 */
template Service "generic-service" {
  max_check_attempts = 5
  check_interval = 1m
  retry_interval = 30s
TimePeriod = "24*7"

}

/**
 * Provides default settings for users. By convention
 * all users should inherit from this template.
 */

/**
 * Provides default settings for host notifications.
 * By convention all host notifications should import
 * this template.
 */
template Notification "mail-host-notification" {
  command = "mail-host-notification"

  states = [ Up, Down ]
  types = [ Problem, Acknowledgement, Recovery, Custom,
            FlappingStart, FlappingEnd,
            DowntimeStart, DowntimeEnd, DowntimeRemoved ]

TimePeriod = "24*7"
}

/**
 * Provides default settings for service notifications.
 * By convention all service notifications should import
 * this template.
 */
template Notification "mail-service-notification" {
  command = "mail-service-notification"
  states = [ OK, Warning, Critical, Unknown ]
  types = [ Problem, Acknowledgement, Recovery, Custom,
            FlappingStart, FlappingEnd,
            DowntimeStart, DowntimeEnd, DowntimeRemoved ]

TimePeriod = "24*7"
}

Please help me with this error. I am new to icinga.

**Comment by Thomas-Gelf** [comment]
Wrong issue tracker, sorry. This is not a Director issue. It's impossible to move issues on Github, therefore please create a new dedicated issue in the [Icinga 2 issue tracker](https://github.com/Icinga/icinga2/issues).
