### ISSUE TITLE
Change the creation of Timeperiod templates and objects

### ISSUE THREAD

**Issue by mcktr** [Icinga/icingaweb2-module-director#901]
Hello,

maybe it is better to split the configuration of timeperiod templates and timeperiod objects to two own menus, similar to the notification configuration.

This keeps the default in the Director (one tab for templates and one for objects).

**Comment by Thomas-Gelf** [comment]
Absolutely makes sense to me.

**Comment by Thomas-Gelf** [comment]
Note for myself: templates are mostly pointless here, they shouldn't be required.

**Comment by Thomas-Gelf** [comment]
The reported issue should have been fixed. I'm still tempted to drop the requirement for a template here...
