### ISSUE TITLE
check_command in sync rule for services missing?

### ISSUE THREAD

**Issue by vita2** [Icinga/icingaweb2-module-director#902]
hello,

i want to import some services from a json-file with fileshipper but there isn't a destination field named check_command in the sync rule view.

how can i set the check_command value for a service? 

regards

![director-import](https://cloud.githubusercontent.com/assets/25298055/25174320/42b3c8aa-24f7-11e7-8577-9efa7d2adeae.png)

**Comment by dgoetz** [comment]
The director has a strict model of templates and objects. The check_command can only be set on the template, so you should define a template and use `Inheritance (import)` during import.

**Comment by vita2** [comment]
Tom has solved this issue with commit ddcaaa7bcf9d14a19233718937c04877aa08873e. Thanks! 🍻

**Comment by Thomas-Gelf** [comment]
You're welcome!

**Comment by Thomas-Gelf** [comment]
...and sorry for the inconvenience :disappointed:

**Comment by vita2** [comment]
don't worry :wink: this issue wasn't a big problem for me. you are doing a great job regarding icinga director. have a nice weekend 👍
