### ISSUE TITLE
Using REST API with active Kerberos 

### ISSUE THREAD

**Issue by chrkli193** [Icinga/icingaweb2-module-director#904]
Hello, we've enabled Kerberos logon for icingaweb2. Now if I want to query the REST API (i.e. Ticket request) as described in the DOCs I get no more response. Is there a way to use the REST API also with active kerberos? I think it's not directly a Director issue but maybe somebody runs the same setup

**Comment by Thomas-Gelf** [comment]
Well, in theory it should work. There is quite some hardcoded logic involved (in Icinga Web 2) when it goes to REST API request handling. So it could be that something is being "intercepted" even before the request reaches the Director. Therefore, I'm currently not sure where to look for the origin of your issue.

It would help if you could provide:

* URL, body and eventually headers of such a REST API request (or a curl call allowing me to reproduce the same action)
* HTTP error code, eventual error message and/or log entries

Thanks,
Thomas

**Comment by chrkli193** [comment]
I send the following curl command:
`curl -H 'Accept: application/json' -u '<username>:<password>' https://<icingahostfqdn>/icingaweb2/director/host/ticket?name=<hostname>`

And get the following response:

`<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>401 Unauthorized</title>
</head><body>
<h1>Unauthorized</h1>
<p>This server could not verify that you
are authorized to access the document
requested.  Either you supplied the wrong
credentials (e.g., bad password), or your
browser doesn't understand how to supply
the credentials required.</p>
<hr>
<address>Apache/2.4.18 (Ubuntu) Server at icingahostfqdn Port 443</address>
</body></html>`

**Comment by chrkli193** [comment]
This helped to solve my problem:
https://geeklabor.de/archives/203-Icinga-Web-2-Single-Sign-On.html
