### ISSUE TITLE
Service not shown because of assignment rule

### ISSUE THREAD

**Issue by chrkli193** [Icinga/icingaweb2-module-director#905]
If I create a service apply rule like this:

assign where ! (host.vars.icinga2_agent == "false") && host.vars.os == "linux" && host.vars.linux_disk == ""

The service is not shown in director Host's service tab so I cannot overwrite variables.

If I deploy this to icinga2 the rule applies to the host and the service is checked. linux_disk is an array field.

**Comment by Thomas-Gelf** [comment]
Hi @chrkli193,

honestly, I'd now have to check for an eventual inconsistency of `vars.xy == ""` (empty string, with xy being an Array) in the Director and in the Core. That might absolutely be possible. In your case, the generated rule compares a string to an Array. While IMHO this shouldn't even be allowed,  Could you show a generated config snippet of a host carrying a linux_disk? And eventually an example of a host that SHOULD match the rule, and another one that SHOULD NOT match.

Thanks,
Thomas

**Comment by chrkli193** [comment]
This one should have this service:
![mit](https://cloud.githubusercontent.com/assets/16578747/25339328/a11ad99c-2902-11e7-89e8-c9d2d7484aff.png)
and this one not:
![ohne](https://cloud.githubusercontent.com/assets/16578747/25339333/a6fb3b36-2902-11e7-917c-46670baa583c.png)

**Comment by Thomas-Gelf** [comment]
This helps, thank you!

**Comment by lazyfrosch** [comment]
I wasn't able to reproduce this with current Director. It should work.

But we just fixed a problem with the "is set" logic.

I added a similar test to #1860
