### ISSUE TITLE
Can't seem to sync usergroups/users

### ISSUE THREAD

**Issue by awshew** [Icinga/icingaweb2-module-director#906]
I have a very vanilla icinga2/icingaweb2 setup, trying to import VictorOps into Director so I can set up notification schedules within Director's scope. Following your documentation:
* I created a CoreApi import source for Usergroups (using object_name as the key) - success. I can see the only group from icinga, icingaadmins, present
* I tried to create a sync rule to merge the usergroup in, keeps throwing up "array_combine(): Both parameters should have at least 1 element" no matter how many properties I added to the rule. To be safe, I made sure all 4 properties were getting some value from the sync, and I'm still getting the same error. 
![image](https://cloud.githubusercontent.com/assets/26572445/25189569/8ad00518-24f7-11e7-8603-6722c039b5e2.png)

**Comment by Thomas-Gelf** [comment]
Unfortunately that's only the "user-friendly" message, so no stack trace is shown. I tried to push a fix that might be related, could you please give the current master a try and let me know whether it works?

**Comment by awshew** [comment]
Same error. I set icingaweb2 application logging to debug, but it isn't catching anything from this either.

**Comment by Thomas-Gelf** [comment]
Ok, thank you - I have been able to finally reproduce this

**Comment by Thomas-Gelf** [comment]
@awshew: should work right now, please let me know in case you're still facing this issue.

**Comment by awshew** [comment]
Confirmed fixed for me, thanks so much @Thomas-Gelf

**Comment by Thomas-Gelf** [comment]
You're welcome, thanks for reporting this!
