### ISSUE TITLE
Disabling single service at specific host applied from a service set

### ISSUE THREAD

**Issue by dgoetz** [Icinga/icingaweb2-module-director#907]
Similar to adjusting thresholds from a single service at specific host applied from a service set, I would like to be able to disable it.

A real world example: In my service set "Linux basic checks" a service swap is included, this set is applied on all hosts with the template "Linux Host - Agent Icinga2" which is set during automatic import from PuppetDB. But now a newly created host was created without a swap device, so the service will always be critical (and not useful at all). So disabling it would be nice, but for now I only could remove swap from the set and assign it in another way.

**Comment by Thomas-Gelf** [comment]
Related to #715. The only way to implement this is rendering an ignore/and not to the apply rule. As that would be terrible from a usability point of view, this must be implemented in a different way. For the user it should "feel" like "disabling" that specific service. This desire should be stored to a blacklist table with the capability to affect apply filters at render time.

**Comment by rajo** [comment]
+1 I"m also using templates and service sets heavily: we have a lot of different switch models which are mostly the same, but some differ in hardware specs (e.g. number of power supplys, slots the PSUs are in) or some firmware quirks. So in general, one can simply use the same templates/sets for everything, there are those exemptions from the rule, where some sort of override/disable switch at the final host element for some service would be really helpful. Else one is either stuck with false alarms or with not using those services in the template but manually adding them everywhere (and then probably forget them for some devices...)

**Comment by nunofernandes** [comment]
+1  I also require this...

**Comment by Thomas-Gelf** [comment]
Just for the records, this is what the related form with the Blacklist/Restore buttons looks like. This is a Service from a Set that has been inherited from a Host Template, you can see that a Custom Variable has been overridden:

![director_host_service_blacklist_form](https://user-images.githubusercontent.com/553008/40559532-5d799d44-6057-11e8-9488-673ad8766bbb.png)
 
Once we blacklist the Service, overrides are dropped and Config rendering changes as shown above. It's of course possible to "Restore" the Service at any time:

![director_host_service_blacklist_clicked](https://user-images.githubusercontent.com/553008/40559715-fdad0a9e-6057-11e8-833f-008a626296c3.png)

**Comment by TobiasKneidl** [comment]
Should this already work with the current master and a PostgreSQL database?

**Comment by Thomas-Gelf** [comment]
@TobiasKneidl: it should, are you facing any problems? In case you are, please open a dedicated issue

**Comment by TobiasKneidl** [comment]
@Thomas-Gelf yes, with services from a Service Set. I've created an issue #1519
