### ISSUE TITLE
Partial backup/export and import of Icinga Director DB

### ISSUE THREAD

**Issue by majales** [Icinga/icingaweb2-module-director#909]
Hi,
I'm very new to icinga2 and Icinga Director ( used nagios, icinga1 classic and thruk before). I have followed some guides on internet and successfully installed both icinga2/icingaweb2 and also Icinga director. I have already made some of the configuration which is working perfectly right now, but there are some minor things which disturbs me. I have used kickstart wizard, and it imported some basic stuff to director database, for example bunch of checks (about 200 of them) some basic groups (which are not visible) and some notification scripts, timeperiods, initial admin user and localhost of icinga2 with some basic checks. Is there any way how to start with clean icinga2 config and use the work I have already made? Some backup/export of configuration but without the director kickstart imported things?

**Comment by Thomas-Gelf** [comment]
Kickstart imports Check- and NotificationCommands, Endpoints and Zones. You could re-run Kickstart at any time via "Icinga Infrastructure -> Kickstart Wizard". It will purge Endpoints and Zones that have been removed from your local config, but it doesn't do so with Commands (might be worth a feature request).

In case you do not use any of them, you could just go to your DB and run:

```sql
DELETE FROM icinga_command WHERE object_type = 'external';
```

Next Kickstart run will re-create them. When a service (or host) template is using one of those external commands, the `DELETE` will fail. Then you either have to exclude those you need it with some `WHERE` filter or temporarily remove the command assignment from your templates.

Cheers,
Thomas

**Comment by Thomas-Gelf** [comment]
NB: partial DB exports through mysqldump combined with a restore AFTER the schema has been initialized is also fine. Just do not try to mix partial imports from a different schema version, that could end badly. I'll close this issue, but feel free to re-open it in case your question is still unanswered.
