### ISSUE TITLE
Add a Services Dashboard

### ISSUE THREAD

**Issue by Thomas-Gelf** [Icinga/icingaweb2-module-director#910]
Should reduce tabs, make navigation easier and provide access to a couple of new tables that have recently been added.

**Comment by Thomas-Gelf** [comment]
Preview:

![director_services-dashboard](https://cloud.githubusercontent.com/assets/553008/25280468/582aa622-26aa-11e7-8ad4-059d132620f1.png)

**Comment by vita2** [comment]
looks good 👍 

would it possible to integrate the amount of objects to each dashlet, like in the overview page? not really important but nice to have

**Comment by Thomas-Gelf** [comment]
Sure. Leaves less space for explanation texts, but that could be moved to the above summary

**Comment by Thomas-Gelf** [comment]
Pushed to 'next' with 2028297
