### ISSUE TITLE
Enable contrib plugins per default in Agent-Script...

### ISSUE THREAD

**Issue by Thomas-Gelf** [Icinga/icingaweb2-module-director#911]
...unless we provide a possibility to customize it. And: first figure out whether all supported Icinga versions ship this file. Related: #893

**Comment by majales** [comment]
I have faced the very same problem with one missed check when I deployed first client/agent. It was "check_mem" check, which was imported by Icinga Director by kickstart, but it was not enabled by pure icinga2 instalation on client/agent and it stated "Check command 'mem' does not exist" when I added service template and aplied it to the host. It is CentOS7 installation, both icinga master and icinga agent.

**Comment by Thomas-Gelf** [comment]
Hint: Icinga 2 default configuration has been changed with [commit 9a455f0c](https://github.com/Icinga/icinga2/commit/9a455f0c) for Icinga v2.5.0. Director supports releases >= v2.4.3 for now.

**Comment by awshew** [comment]
Can confirm we installed the rhel6 RPMs from the icinga repo directly.
```
[root@crp-mon-02 ~]# rpm -qa | grep icinga
icinga2-2.6.3-1.el6.x86_64
nano-icinga2-2.6.3-1.el6.x86_64
icingaweb2-vendor-dompdf-0.7.0-1.el6.noarch
icingaweb2-vendor-HTMLPurifier-4.8.0-1.el6.noarch
icinga2-common-2.6.3-1.el6.x86_64
icinga2-bin-2.6.3-1.el6.x86_64
vim-icinga2-2.6.3-1.el6.x86_64
icingaweb2-common-2.4.1-1.el6.noarch
icingaweb2-2.4.1-1.el6.noarch
icingacli-2.4.1-1.el6.noarch
icingaweb2-vendor-zf1-1.12.20-1.el6.noarch
icingaweb2-vendor-JShrink-1.1.0-1.el6.noarch
icingaweb2-vendor-lessphp-0.4.0-1.el6.noarch
icinga2-libs-2.6.3-1.el6.x86_64
icinga2-ido-pgsql-2.6.3-1.el6.x86_64
icingaweb2-vendor-Parsedown-1.6.0-1.el6.noarch
```

**Comment by Thomas-Gelf** [comment]
A related patch has been merged
