### ISSUE TITLE
What about two services with the same object name?

### ISSUE THREAD

**Issue by sysadmama** [Icinga/icingaweb2-module-director#913]
Hi Thomas,

I created a NRPE service template called "users", assigned it to a template - everything is working as expected.
`
template Service "users" {
    import "NRPE Queries"

    groups = [ "nrpe" ]
    vars.nrpe_command = "check_users"
}
`

Then, just for fun, I created another service template called "users", its check_command is "users". In Activity Log, this change is logged, but the whole system gets confused (I'll attach some screenshots): as you can see, when I choose the service "users", now both get active. I can't deploy[1] config as icinga2 is very sad about "previous definition", I can't delete the service "users" at is in use... Director should stop the creation if the object name already exists.

Cheers,
  Marianne

[1] Of course I can. But anyways, it's a bug ;-)

![screen shot 2017-04-25 at 11 53 53](https://cloud.githubusercontent.com/assets/11242139/25379635/fa136946-29ad-11e7-916f-ca349126cc13.jpg)

![screen shot 2017-04-25 at 11 52 09](https://cloud.githubusercontent.com/assets/11242139/25379583/cbdb582c-29ad-11e7-9d98-263bc0f0ec38.jpg)

**Comment by Thomas-Gelf** [comment]
It's a bug, duplicates #364. Rename one of them, then you should be able to delete one or the other. Not sure whether we'll fix this "in userspace" (DB can't help here) or whether this will lead to a complete hard separation of templates, apply rules and single services in the DB. Initially, a fix in the application has been targeted. But that way it's hard to get this solved in an atomic way, so one could still try to fool that logic. Currently, I'd prefer to introduce a hard cut in the DB. And in the meantime: just don't create them twice ;-)

**Comment by sysadmama** [comment]
So I'll close this one. Hard for me to find duplicates before reporting a bug (I tried!) :)
