### ISSUE TITLE
Import from icinga2 director sql database to a newly installation director database

### ISSUE THREAD

**Issue by AronNg** [Icinga/icingaweb2-module-director#915]
Hi,

I'm new here, and I'm sorry if I post this message in a wrong place.  
I have a question regarding  import director database from another director installation. I hope I could ask for some advise from the forum.

I did a research on how to import from one director sql database to another director sql database.

I have icingaweb2/director up and running on one city(A), I have created a lot of hosts, services, commands. It took me weeks to have it done.

Now, I have  a similar setup as city(A) on city(B). I have installed and configured icingaweb2/director up and running, but without any services, or hosts configured yet because I want to import them from cityA's director database.

I exported .sql of director database with mysqldum on cityA, and plan to import using director on  cityB to avoid create services, hosts, commands from the ground.

I know that I can't just import the .sql from cityA in to cityB's director database becaue of different IPaddress, hostname, and back end. I can modify the IP for hostnames manually later.

indeed, I need to create a database resource for sql file from cityA on cityB icingaweb2 installation. Then from director of cityB I will have to use the "Automation" tool to import from cityA database sources to current director database for cityB.

This is where I stuck, I don't know how to import all hosts, services, command from the data sources. 

I'm very appreciate for any hint of how to do this step.

Regards,
Aron
<img width="1278" alt="screen shot 2017-04-26 at 4 48 38 pm" src="https://cloud.githubusercontent.com/assets/28056629/25440767/adf34808-2aa0-11e7-9fbf-b5f687aa420c.png">

**Comment by Dumbaz** [comment]
It´s not a smooth solution, but you can indeed just push your sqldump into the database of your new director B.

It might be a good idea to handpick the lines you want. `icinga_host*`,  takes care of most things regarding hosts, `icinga_service*` of the services. I am not certain about commands.

Your Activity log has it´s own key, if you do not import that it won´t show up at all.

**Comment by Thomas-Gelf** [comment]
Configuration Baskets have been implemented to address this requirement. If you're still missing related features, please open dedicated feature requests.
