### ISSUE TITLE
Synchronizing Users fails to write config

### ISSUE THREAD

**Issue by awshew** [Icinga/icingaweb2-module-director#916]
So, after the sync worked and showed that Users were created, any attempt to commit the changes fails. Trying to look at the individual user changes also errors:

```
Fatal error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 523800 bytes) in /etc/icingaweb2/modules/director/library/Director/Objects/IcingaObject.php on line 563
```
I looked at the db, the icinga_user table seems to be clean:

```
icingadirector=# select * from icinga_user
icingadirector-# ;
 id |  object_name  | object_type | disabled | display_name | email | pager | enable_notifications | period_id | zone_id
----+---------------+-------------+----------+--------------+-------+-------+----------------------+-----------+---------
  1 | User Template | template    | n        |              |       |       | y                    |           |
  3 | Dummy User    | object      | n        |              |       |       |                      |           |
  4 | icingaadmin   | object      | n        |              |       |       |                      |           |
  5 | VictorOps     | object      | n        |              |       |       |                      |           |
(4 rows)
```

I can't interact in any way to remove the change either, effectively blocking any config changes from being deployed:

![image](https://cloud.githubusercontent.com/assets/26572445/25441728/0a3246c6-2a71-11e7-83a0-7c3f807a852a.png)

I can't seem to get any log of this on debug for icingaweb2. I restarted both apache and icinga2 after updating Director to the latest master.

**Comment by awshew** [comment]
Only diffs in the code/config:

```
[root@crp-mon-02 modules]# diff -r director director-20170426
diff -r director/library/Director/Import/Sync.php director-20170426/library/Director/Import/Sync.php
271,274c271,272
<             if (! empty($filterColumns)) {
<                 foreach (SyncUtils::getRootVariables($filterColumns) as $column) {
<                     $usedColumns[$column] = $column;
<                 }
---
>             foreach (SyncUtils::getRootVariables($filterColumns) as $column) {
>                 $usedColumns[$column] = $column;
diff -r director/library/Director/Import/SyncUtils.php director-20170426/library/Director/Import/SyncUtils.php
128,131d127
<         if (empty($res)) {
<             return array();
<         }
<
```

**Comment by awshew** [comment]
Deleting the 2 users (id 4 and 5) from the db and then trying to commit the changes seems to have let the config commitment move forward... I think it may have been a field mapping for inheritance that wasn't configured properly, but it still allowed the sync... just failed on some level? I checked the user_inheritance table and there was nothing there either... so i'm unsure what it was actually choking on.

**Comment by awshew** [comment]
Removing inheritance from the sync fields and just doing object name works without issue.

**Comment by Thomas-Gelf** [comment]
@awshew: any idea whether this is still an issue?

**Comment by awshew** [comment]
I'll take a look tomorrow. I've actually been making heavy use of the kickstart import to bring in "built-in" elements to work around things like this.
