### ISSUE TITLE
Failed to load icinga_zone "<fqdn>" (DbObject.php:589)

### ISSUE THREAD

**Issue by B3RN0UT** [Icinga/icingaweb2-module-director#918]
I've added yesterday the icinga director module to our working icinga2/icingaweb2 environment, but I get the following error with the kickstart wizard:
`Failed to load icinga_zone "<fqdn>" (DbObject.php:589)`

At Activity Log:
`Unable to detect your deployment endpoint. I was looking for the first endpoint configured with an assigned API user in the "master" zone.`
```
#0 /usr/share/icingaweb2/modules/director/library/Director/Db.php(163): Icinga\Module\Director\Db->getDeploymentEndpointName()
#1 /usr/share/icingaweb2/modules/director/library/Director/Web/Controller/ActionController.php(366): Icinga\Module\Director\Db->getDeploymentEndpoint()
#2 /usr/share/icingaweb2/modules/director/application/controllers/ConfigController.php(133): Icinga\Module\Director\Web\Controller\ActionController->api()
#3 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Director\Controllers\ConfigController->activitiesAction()
#4 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('activitiesActio...')
#5 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#6 /usr/share/php/Icinga/Application/Web.php(389): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#7 /usr/share/php/Icinga/Application/webrouter.php(109): Icinga\Application\Web->dispatch()
#8 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...')
#9 {main}
```
I 've entered the following values in the wizard:
**Name of the Endpoint:** fqdn same fqdn as in /etc/icinga2/pki
**Icinga host:** localhost
**Port:** 5665
**API User:** director
**Password:** pw1

Database is created with utf8 also set at icinga2 ressource.

**OS:** Debian 8
**Director:** 1.3.1 (latest master)
**Icinga2:** r2.6.3-1

**zones.conf**
```
object Endpoint NodeName {
  host = NodeName     
}


object Zone ZoneName {
	endpoints = [ NodeName ]
}

object Zone "global-templates" {
  global = true
}
```
**api-users.conf**
```
object ApiUser "root" {
  password = "<pw0>"
  permissions = [ "*" ]
}

object ApiUser "director" {
  password = "<pw1>"
  permissions = [ "*" ]
}
```
fqdn & localhost can be resolved by the system

Hopefully someone could help me out here :)

**Comment by acesuares** [comment]
I never managed to add the director-module to an existing config. I took a different approach and made a fresh icinga2/icingaweb2 install. But even there it wouldn't work or I was confused about config option. So I made virtual machine and after endless briddling, I came up with this: https://acesuares.github.io/install-icinga2-director-on-virtualbox-with-vagrant/ now with 28 easy steps!

**Comment by Thomas-Gelf** [comment]
Your shown example should always have worked, but I managed it to reproduce a similar issue leading to above error. Also, the error when going to activity log without a valid deployment endpoint should not happen.
