### ISSUE TITLE
Add the ability to deploy a single change from the activity log

### ISSUE THREAD

**Issue by mcktr** [Icinga/icingaweb2-module-director#920]
Hi,

maybe it's a good idea to add the ability to deploy a singe change from the activity log. 

Example use case:
- multiple Icinga Director users
- 1 user has the right to deploy new config
- the other users can only make changes but can not deploy the config
 
A user made multiple changes (add a host, adding services to the host). The user with the deploy rights  reviews the activity log, all seems good except the fact, that the new host didn't have the Icinga 2 Agent installed so some services would be critical/unknown. Now he can delete the services that would be critical and deploy the config or he deploy the entire config and accept that some services are critical/unknown. 

With the ability to deploy a single change he can deploy the new host for the hostalive check without getting some service down/unknown notifications or delete the config for the services. After he installed the Icinga 2 Agent on the new hosts he can deploy the services without recreate them.

Best regards

**Comment by saikrishnagaddipati** [comment]
+1 .
 It's a good to have feature. I would like to deploy my changes instead of deploying all the changes made by other users. And also i would like to deploy selected changes from my list of changes.

We are having hard time deploying all the changes made by different users.

It would be ideal if we have a feature to deploy selective changes from activity log.
Thanks

**Comment by mcktr** [comment]
I have thought about my proposal again and I think that such a feature is hard to implement, because you need to resolve all required dependencies for a change you made.

Simple example: you added a new contact for alerting, in a new host you added also you set this new contact. If you now only deploy the added host the deploying will fail, because Icinga 2 don't know about the contact you set.

Maybe a more simpler solution is an art of user based activity log and deploying, but also here we have the problem with dependencies. What if user1 made a changes that depends on something user2 did?

I think the error handling and resolving of dependencies would be very difficult to implement.

**Comment by druchoo** [comment]
+1 for same reasons as @saikrishnagaddipati. I'd also like to add the following which was discussed in the [forums](https://monitoring-portal.org/index.php?thread/42104-problem-with-workflow/).

---

What I'm looking to achieve is:
1. Have Director with all its power do imports, syncs and deploy those changes automatically
2. Ability to make other changes via GUI and/or Director API but only have those specific changes deployed when wanted. For example:
    - An AWS Lambda that add/removes hosts for AWS ASG's. Reason for this, is we'd like these added/removed as soon as they are created/destroyed.
    - User(s) modifying configs in Director GUI to add/remove services, update templates, etc to prepare for upcoming changes to infrastructure. These would not necessarily need to be deployed immediately.

From the Director description, I thought what I'm trying to do is what was stated:

> Icinga Director has been designed to make Icinga 2 configuration handling easy. It tries to target two main audiences:
> - Users with the desire to completely automate their datacenter
> - Sysops willing to grant their "point & click" users a lot of flexibility

It would be nice if pending changes were similar to a git repo. Running config would be master and changes from each user (automated or person) were a branch. The user could then merge only their changes to the running configs.

**Comment by Thomas-Gelf** [comment]
@druchoo: it's perfectly possible to combine both worlds, so above statement stands. Otherwise please point me to where we are making false promises. I'll immediately correct it.

What you're asking for is creating completely distinct branches in the DB. To resolve merge conflicts between user branches and more. Well, building a DB-based GIT. With much more complexity in some places, as referential integrity, inheritance and caching tables are a thing here. As you're asking for this like it was a self-evident feature: have you ever seen something similar before?

**Comment by druchoo** [comment]
Hey @Thomas-Gelf, please don't get me wrong, I'm not saying anyone made false claims. I'm just having a problem when there are changes from multiple entities. It seemed this feature would resolve my problem and added my specific use case for clarity. And, no about the "git" feature. I don't know of anything like that. I was just saying that conceptually if changes worked this way that would be great.

Is there a better way to handle this?

Thanks for reviewing.

**Comment by druchoo** [comment]
Hi @Thomas-Gelf, I couldn't think of it before but the Grafana [Dashboard Version History](http://docs.grafana.org/reference/dashboard_history/) ([PR #8472](https://github.com/grafana/grafana/pull/8472)) that was introduced in [4.4.0](https://github.com/grafana/grafana/blob/master/CHANGELOG.md#440-2017-07-04) is similar to what I was trying to describe.

**Comment by Thomas-Gelf** [comment]
Then Director should provide all you need since it's very first versions. You have a history of all deployments and you can re-deploy any former version at any time.

**Comment by druchoo** [comment]
Fair enough. Is there a way to discard pending changes after reverting to a previous deployment?

**Comment by Thomas-Gelf** [comment]
No.

**Comment by Thomas-Gelf** [comment]
I'll close this issue, won't happen any time soon. Deploying "just a single change" as initially requested will not work without real "branches", #528 should address part of this. Rolling back to any previous deployment won't happen, as this could eventually mean rolling back a few hundred thousand or even a million single changes in some environments I'm aware of. Also, this change must then create new activity log entries allowing one to once again revert everything that has been modified by that big undo action. No way to implement this in an efficient way for large environments.

Also, it would then be impossible to guarantee that the reverted configuration would be rendered like it used to at the time being. That old config could have been generated by a previous version of Director. So, the current way of preserving the formerly rendered config is the only way to give this guarantee.

Rolling back just five changes as shown in the Grafana example should already be possible by clicking revert five single times. Reverting multiple changes at once will be implemented sooner or later, depends on Director being able to roll back every kind of change - which is not the case right now.
