### ISSUE TITLE
Setting "Run on agent" explicitly to "No" is ignored when inheriting a setting of "Yes"

### ISSUE THREAD

**Issue by awshew** [Icinga/icingaweb2-module-director#921]
It looks like the boolean "Run on agent" for Service definitions doesn't actually set anything on "No" - it's assuming the global default for icinga will be true (run on master)... but if you override this global default with another default service template and inherit it, there's no explicit config generated to force it back to being run on the master. 

Example:

Rendered config of /zones.d/director-global/service_templates.conf:
```
template Service "Default Service Settings (Agent)" {
    max_check_attempts = "3"
    check_interval = 5m
    retry_interval = 5m
    enable_notifications = true
    enable_active_checks = true
    enable_passive_checks = true
    enable_event_handler = true
    enable_perfdata = true
    volatile = false
    command_endpoint = host_name
}

template Service "CPU Utilization" {
    import "Default Service Settings (Agent)"

    check_command = "load"
}

template Service "Disk Utilization" {
    import "Default Service Settings (Agent)"

    check_command = "disk"
}

template Service "Memory Utilization" {
    import "Default Service Settings (Agent)"

    check_command = "mem"
    vars.mem_critical = "95"
    vars.mem_used = true
    vars.mem_warning = "80"
}

template Service "Process Count" {
    import "Default Service Settings (Agent)"

    check_command = "procs"
    vars.procs_nokthreads = true
}

template Service "Swap Utilization" {
    import "Default Service Settings (Agent)"

    check_command = "swap"
}

template Service "User Sessions" {
    import "Default Service Settings (Agent)"

    check_command = "users"
}

template Service "Uptime" {
    import "Default Service Settings (Agent)"

    check_command = "check_uptime_rhel"
}
```

But the GUI clearly shows I overrode the command_endpoint with the "Run on agent" boolean set to "No":

![image](https://cloud.githubusercontent.com/assets/26572445/25632813/1703d92e-2f43-11e7-902e-eacabda1c815.png)

**Comment by awshew** [comment]
The workaround was to clone the Default set I have and just toggle the boolean there (and then inherit it to the checks that need it), so it's not blocking me... but I think this is still a bug since the lowest-level object's setting should trump all inherited values.

**Comment by ultrakamish** [comment]
Same issue. Had service template with "Run on agent: Yes" and service (ping) that inherited that template and had "Run on agent: No", but checks was still on agent, not on master. When i cloned all other template variables, checks was from master (as i wanted). 

As i understand, the matter in 'command_endpoint' attribute of service object, that with "Run on agent: Yes" has the string name of endpoint, but when "Run on agent: No", it becomes an empty string.
But this thing could not be overwritten manually from Director.
