### ISSUE TITLE
Synchronisation of notifications

### ISSUE THREAD

**Issue by widhalmt** [Icinga/icingaweb2-module-director#925]
A customer of mine wants to synchronise notification objects just like other objects.

Please add notification objects to the list of syncable objects.

If you need more informations on this I can connect you to the user who needs this feature.

Cheers,
Thomas

**Comment by lazyfrosch** [comment]
Syncing can be tricky for `apply`.

Can you share some details about what kind of notifications should be synced?

**Comment by rattacresh** [comment]
We'd like to migrate from our in-house monitoring system to icinga2+director. Currently, we have  database tables (which we are ready to change as needed) for checks (=services) and notifications; the notifications are similar to a icinga2 notification objects (ie., in which time periods to notify whom how often with what delay for which states etc.).

Don't consider this high priority, we can generate the desired objects with the fileshipper. It would just be cool to have director sync such notification objects. And of course also notification apply rules, the same way as service apply rules can be synced.

**Comment by chas0rde** [comment]
Hello
we would also like to use this. Our use case would e.g. be:

1. Users get synced via external source (e.g. LDAP or Active Directory)
2. Based on users configuration notifications are created (relating templates maybe)

e.g.: user is imported and for each user in the director DB a notification should be created with predefined apply conditions like: email != ""

I agree with @lazyfrosch that apply might be a tricky part here
