### ISSUE TITLE
Notifications fail with TimePeriod set

### ISSUE THREAD

**Issue by AndyFriar** [Icinga/icingaweb2-module-director#926]
Reinstall today using latest build, all notifications fail when setting a timeperiod even if it's 24x7x365

Notification was applied to zone

CentOS7

**Comment by Thomas-Gelf** [comment]
Please define 'fail'

**Comment by AndyFriar** [comment]
https://en.wikipedia.org/wiki/Failure

"Failure is the state or condition of not meeting a desirable or intended objective, and may be viewed as the opposite of success."

In all seriousness, emails don't send. "Forced" functions correctly.

Create the same notification template / rule but without a timeperiod and mail sends correctly

**Comment by Thomas-Gelf** [comment]
Please show some relevant parts of the rendered configuration, the Timeperiod in use, the Notification - and the filename they have been rendered to.

**Comment by Thomas-Gelf** [comment]
> "Failure is the state or condition of not meeting a desirable or intended objective, and may be viewed as the opposite of success."

NB: in case the failure is huuuge, googling for a [miserable failure](https://en.wikipedia.org/wiki/Miserable_failure) used to help finding the _right_ party ;-)

**Comment by AndyFriar** [comment]
Timeperiod Template
![image](https://cloud.githubusercontent.com/assets/16238839/25784342/eaeb088e-3362-11e7-9c53-e8aa4988d930.png)

I'm sure you can guess the other time periods

Timeperiod
![image](https://cloud.githubusercontent.com/assets/16238839/25784347/100a3504-3363-11e7-88a0-86da867d808d.png)

Notifcation Template

![image](https://cloud.githubusercontent.com/assets/16238839/25784355/492b1042-3363-11e7-8e6b-1b056d73def8.png)

Notifcation
![image](https://cloud.githubusercontent.com/assets/16238839/25784358/61e82408-3363-11e7-8ae9-1482adee1b2a.png)

Lack of email
![image](https://cloud.githubusercontent.com/assets/16238839/25784377/a161fe92-3363-11e7-969a-86a3cb6921f3.png)

Forced

![image](https://cloud.githubusercontent.com/assets/16238839/25784389/dadae42c-3363-11e7-9c10-98a5c9ddcb87.png)

**Comment by AndyFriar** [comment]
Working Notify template

![image](https://cloud.githubusercontent.com/assets/16238839/25784401/0fe9ca0c-3364-11e7-9ee1-0fc5d5b110ed.png)

![image](https://cloud.githubusercontent.com/assets/16238839/25784418/6faf1244-3364-11e7-9c1f-541add328896.png)

![image](https://cloud.githubusercontent.com/assets/16238839/25784420/789e8cae-3364-11e7-9d20-8a4f06789a8a.png)

![image](https://cloud.githubusercontent.com/assets/16238839/25784422/9c7fea64-3364-11e7-9014-aff9c3e4b933.png)

**Comment by Thomas-Gelf** [comment]
Guess here we have the problem:

![image](https://cloud.githubusercontent.com/assets/16238839/25784347/100a3504-3363-11e7-88a0-86da867d808d.png)

While no `ranges` property means _everything_, an empty `ranges` dictionary means _no time range at all_, so this period will never match.

**Comment by Thomas-Gelf** [comment]
NB: I see you are importing "tmp247". In case that one has some (7?) ranges this behavior might be confusing. An empty `ranges = {}` rarely used to be very helpful, it is just there for compatibility reasons, guess we cannot change this. But we could set the operator to `+=` instead of `=` for all the ranges, that could solve your potential inheritance problem.

This should IMO be fixed, or even better re-evaluated together with the includes/excludes attributes introduced in Icinga after this feature has been made available in the Director.

For now you have to clone the Timeperiod, sorry for that. Guess that would fix your issue.

**Comment by AndyFriar** [comment]
Still happens on other ranges
![image](https://cloud.githubusercontent.com/assets/16238839/25784538/f6c25ff0-3366-11e7-8f45-47487ebb22d0.png)

If i add in the same times to the timeperiod as well as the template we get a compile error

![image](https://cloud.githubusercontent.com/assets/16238839/25784561/875fa86a-3367-11e7-8e37-829b2bdfbd91.png)

I can just work around the problem and not use timeperiods for notifications for the moment. Alas my php is terrible else i'd help

**Comment by Thomas-Gelf** [comment]
You have to define one period per day, it has to look like this:

```
template TimePeriod "24x7" {
    import "legacy-timeperiod"
    import "Base Time Period"

    ranges = {
        "monday"	= "00:00-24:00"
        "tuesday"	= "00:00-24:00"
        "wednesday"	= "00:00-24:00"
        "thursday"	= "00:00-24:00"
        "friday" 	= "00:00-24:00"
        "saturday"	= "00:00-24:00"
        "sunday"	= "00:00-24:00"
    }
}
```

Cheers,
Thomas

**Comment by AndyFriar** [comment]
Yep that's sorted it, had to add to timeperiod as well as template but seems to function as intended

**Comment by AndyFriar** [comment]
Thanks

**Comment by Thomas-Gelf** [comment]
Glad to hear that. We'll tackle the issues mentioned above in #404 and #901
