### ISSUE TITLE
Can't pass backslash in argument of perfmon windows

### ISSUE THREAD

**Issue by el-wood** [Icinga/icingaweb2-module-director#927]
Hi,
I'm not strong in linux but
I try to pass \ in argument "-P' of check_perfmon and it seems to be impossible. 
if i put \ then on the windows agent side it looks as  \\ and command is failing.

How to achieve:
check_perfmon -P "\SQLAgent:Jobs(_Total)\Failed jobs"

argument $perfmon_win_counter$ passed as a field of string type

**Comment by Thomas-Gelf** [comment]
Did you try with `\\`?

**Comment by el-wood** [comment]
Yes. I got \\\\ then :)

**Comment by Thomas-Gelf** [comment]
Sorry, now I'm confused. What exactly was the problem with your initial attempt? Could you please show me some related screenshots? Command definition, filled custom variable, object preview - and the command part of an executed command as shown by "Inspect" would be great

**Comment by el-wood** [comment]
I'm trying to prepare service template and deploy it to Windows agent.

I defined field data as a string type and assigned it to a variable $perfmon_win_counter$ . Then i've made a service template and it looks now like this:

template Service "App MSSQL - Agent failed jobs" {
    import "Agent based tmpl"

    check_command = "perfmon-windows"
    vars["$perfmon_win_counter$"] = "\\SQLAgent:Jobs(_Total)\\Failed jobs"
    vars["$perfmon_win_crit$"] = "1"
}

when i used doubled \ i got:
vars["$perfmon_win_counter$"] = "\\\\SQLAgent:Jobs(_Total)\\\\Failed jobs"

My master is Ubuntu.
I've noticed also that when i use " i get \"

**Comment by Thomas-Gelf** [comment]
The variable name has to be just `perfmon_win_counter`, not `$perfmon_win_counter$` - the macro-style format (`$varname$`) is only used when referencing a variable

**Comment by el-wood** [comment]
I new in icinga, but maybe i'm referencing.. ?

**Comment by Thomas-Gelf** [comment]
This:

```
template Service "App MSSQL - Agent failed jobs" {
  import "Agent based tmpl"

  check_command = "perfmon-windows"
  vars["$perfmon_win_counter$"] = "\\SQLAgent:Jobs(_Total)\\Failed jobs"
  vars["$perfmon_win_crit$"] = "1"
}
```
...has to read like this:
```
template Service "App MSSQL - Agent failed jobs" {
  import "Agent based tmpl"

  check_command = "perfmon-windows"
  vars["perfmon_win_counter"] = "\\SQLAgent:Jobs(_Total)\\Failed jobs"
  vars["perfmon_win_crit"] = "1"
}
```
...or this:

```
template Service "App MSSQL - Agent failed jobs" {
  import "Agent based tmpl"

  check_command = "perfmon-windows"
  vars.perfmon_win_counter = "\\SQLAgent:Jobs(_Total)\\Failed jobs"
  vars.perfmon_win_crit = "1"
}
```

**Comment by el-wood** [comment]
Ok. But it does not change backslash problem.
Now i got:

template Service "App MSSQL - Agent failed jobs" {
    import "Agent based tmpl"

    check_command = "perfmon-windows"
    vars.perfmon_win_counter = "\\SQLAgent:Jobs(_Total)\\Failed jobs"
}

And i get error (the same as before) :
Error: Non-optional macro 'perfmon_win_counter' used in argument '-P' is missing.

Regards and thank You for Your help.

**Comment by Thomas-Gelf** [comment]
This error message is telling you that the argument expected for `-P` isn't there, while what you're showing should pass the given value. Are you sure that you successfully deployed the shown config and that the check has been executed again?

**Comment by el-wood** [comment]
Sorry

It's Working !!

You were right. 
I still can see two \ but check passed with no errors !!

Thank You very much !!

**Comment by Thomas-Gelf** [comment]
You're welcome! You see the two backslashes because the backslash is an escaping character and therefore also needs to be escaped.
