### ISSUE TITLE
Servicegroups require assign policy on saving

### ISSUE THREAD

**Issue by LordHepipud** [Icinga/icingaweb2-module-director#930]
Hello,

creating service groups is right now possible without problems, require however assign rules if you want to edit them afterwards.

Trying to edit the name for example results in

Value is required and can't be empty

in case no assign rules is defined. Hostgroups however work fine.

**Comment by Darkitty** [comment]
Hi,

I have the issue for hostgroup. The same message shows if I try to edit it.

Thanks :)

**Comment by dgoetz** [comment]
Would setting the following line to false be enough or are there side effects I am not aware of?
https://github.com/Icinga/icingaweb2-module-director/blob/099c53a008b0917792322c663776671de9fa0fe0/application/forms/IcingaServiceGroupForm.php#L28

**Comment by Thomas-Gelf** [comment]
@dgoetz: don't think so. Could you please prepare a related pull request?

**Comment by dgoetz** [comment]
PR is attached and checks have passed.
