### ISSUE TITLE
filter for merge only - do not create

### ISSUE THREAD

**Issue by cbnorman** [Icinga/icingaweb2-module-director#931]
I have a bit of a problem where i have 2+ data sources for my imports. one database has all the hosts i want to monitor along with base custom vars. i then have some other databases which have more hosts (including the imported ones) which contain extra details about the hosts, i dont want to import new hosts from this second data source just just merge attributes to the existing host objects. ive played around with filters on the property sync but it always seems to attempt to add new hosts from the second data source, is there anyway to stop this?

ideally there should be a merge only rule for the import rule, any ideas.

if i leave my filter expression blank i get
![image](https://cloud.githubusercontent.com/assets/10809716/25842491/1bf8def8-349c-11e7-9a5f-4bff10eae0b0.png)

i do not want this rule creating anything. i think editing the filter expression will get what i want but what ever filter i try on the modify tab it just doesnt return anything (filters out all)
![image](https://cloud.githubusercontent.com/assets/10809716/25842503/24a641f8-349c-11e7-8952-32ca99bfacec.png)
![image](https://cloud.githubusercontent.com/assets/10809716/25842518/30e73ada-349c-11e7-9630-c7ed358ad4a5.png)

here is my input source
![image](https://cloud.githubusercontent.com/assets/10809716/25842523/3b87a93e-349c-11e7-88e5-9d71b1ecd297.png)

**Comment by cbnorman** [comment]
anyone know what im missing here. bit pointless having multiple data sources if you cant filter based on existing objects?

**Comment by cbnorman** [comment]
@Thomas-Gelf do you have any suggestions here i have read a lot of your documentation on the function but cant find anything on the sync rule filter

**Comment by Thomas-Gelf** [comment]
Hi @cbnorman! If I correctly understood your issue, you are dealing with hosts from two distinct import sources, one carrying the hosts that should be imported, and the other one with all or a subset of those hosts with additional properties, together with many more hosts that should not be imported at all?

I would build this as follows:
* Create a `Data List` **Hypervisor relationships**
* Implement the `Import Source` **vi_hosts_hypervisor** as shown
* New `Sync rule` **Sync Hypervisor relationship** for the `Datalist entry` object type. Provide your list id (no dropdown yet, sorry), map `hostname` to `entry_name` and `parent` to `entry_value`
* Create the `Import Source` "All my hosts"
* Add a `Property Modifier` of type `Map` to the `hostname` column of that import source, choose your newly created `Data List` and tell it to write the result to a new column named `hypervisor`
* In the related `Sync Rule`, map `hypervisor` to `vars.hypervisor` or similar

Have fun,
Thomas

**Comment by cbnorman** [comment]
HI @Thomas-Gelf thanks for responding so quickly. i have configured a new sync rule as follows, i dont see anywhere to write in my list id, or where i would get my list id from unless its just the name.

![image](https://cloud.githubusercontent.com/assets/10809716/26058403/b1c43ee0-3975-11e7-83f1-6a5e310e90e6.png)

if i continue without it and try to add some sync properties i get the following error after selecting the hypervisor input source?
![image](https://cloud.githubusercontent.com/assets/10809716/26058465/e0577b00-3975-11e7-91ef-2f1d13ce91de.png)

**Comment by Thomas-Gelf** [comment]
Sync properties should be the right place. There have recently been issues related to the datalist entry sync, are you using a release version or the current master of the Director?

**Comment by cbnorman** [comment]
i think im running 1.3.1 based on the last git command i ran. `git checkout v1.3.1` how can i tell for sure?

**Comment by Thomas-Gelf** [comment]
The shown error appears in v1.3.1, e6e51dc fixes it and ddcaaa7 should also be applied as it fixes another little bug introduced by the former commit. The current master contains both of them.

**Comment by cbnorman** [comment]
yea defo on 1.3.1 `[root@elkmon132 director]# cat module.info
Name: Icinga Director
Version: 1.3.1
Depends: monitoring
Description: Director - Config tool for Icinga 2
 Icinga Director is a configuration tool that has been designed to make
 Icinga 2 configuration easy and understandable.
`

**Comment by cbnorman** [comment]
ok ill move to master and try agian thanks

**Comment by Thomas-Gelf** [comment]
`module.info` shows 1.3.1 also for the current master. If you don't fear the bleeding edge stuff, pull and `git checkout master` would be perfect. Eventually, as with every upgrade, dump your database first - just to be on the safe side (downgrading the DB is not supported - for a downgrade you have to restore a DB dump). But there should be nothing to worry about in the current master, it is very close to what we're going to release as 1.3.2. Currently all the "fancy" commits go to other branches as we're preparing 1.4.x.

**Comment by cbnorman** [comment]
getting further now but issue with list_id, is it just the list name, that doesnt seem to work?
![image](https://cloud.githubusercontent.com/assets/10809716/26060576/6879fd94-397d-11e7-80d3-1ef434f09aea.png)

**Comment by Thomas-Gelf** [comment]
As mentioned above, no name/dropdown yet, sorry. Go to your data lists, hover or click the list you want and grab the ID from the URL.

**Comment by Thomas-Gelf** [comment]
@cbnorman: did it work?

**Comment by cbnorman** [comment]
Hi Thomas

i updated to master this morning and it working really well, the sync is very fast. thanks so much for helping me with this i have many other syncs i can use the same logic for. one last thing... im obviously pulling these vars to do dependancies and i understand that director doesnt directly support yet so i created a new conf file and reloaded, icinga seems fine with the config but unfortunately it doesnt seem to be taking any affect. any idea what im doing wrong or would you like me to open a seperate issue?

`apply Dependency "guest_vm_to_parent_hypervisor" to Host {
  parent_host_name = host.vars.hypervisor
  assign where host.vars.contains("hypervisor")
}`

**Comment by cbnorman** [comment]
its working. had the dependancy.conf file in the wrong location, no wonder icinga2 didnt complain about it on reload. thanks for all your help
