### ISSUE TITLE
Deleting a host via Director API fails

### ISSUE THREAD

**Issue by xenuser** [Icinga/icingaweb2-module-director#933]
I wrote a little Python script which does the following things:

1. Create a new host via Director API - works
2. Trigger Director deploy via Director API - works
3. Check the satellites of the relevant Zone via API if they received the new host - works
4. Delete the new host via Director API - does not work
5. Trigger Director deploy via Director API - works

In step 4, I do the following thing:

```
        request_url = "https://%s/icingaweb2/director/host?name=monitor-icinga2-infrastructure-director-host" % (fqdn)
        headers = {
        'Accept': 'application/json',
        'X-HTTP-Method-Override': 'DELETE'
        } 

        data = {
               "object_name": "monitor-icinga2-infrastructure-director-host", "object_type": "object", "address": "127.0.0.1", "zone": arguments["--zone"], "imports": ["generic-host"]
        } 

        try:
               r = requests.post(request_url, headers=headers, auth=(user, password), data=json.dumps(data), verify=False)
        except requests.exceptions.RequestException as e:
               print e

```

I also print out the response. In this case, all I got, is a HTTP 304 code.

The log files of Icinga2 on the corresponding master show while sending the DELETE request:

```
[2017-05-15 12:44:06 +0200] information/HttpServerConnection: Request: DELETE /v1/config/stages/director/master-1494604360-0 (from [IP]:50943, user: director)
[2017-05-15 12:44:07 +0200] information/HttpServerConnection: Request: POST /v1/config/stages/director (from [IP]:50943, user: director)

```

I use similar methods when talking to the normal Icinga2 API, so normally my code works. I also tried to sen d the request above without sending the JSON data, but I receive the same result.

Am I doing something wrong? If yes, what can I improve?

**Comment by Thomas-Gelf** [comment]
You are sending a `POST` request to `director/host?name=....`, not a `DELETE` request. Director doesn't allow one to use cheats based on `X-HTTP-Method-Override`. If you want to talk to it's REST API you have to use real [HTTP methods](https://github.com/Icinga/icingaweb2-module-director/blob/master/doc/70-REST-API.md#url-scheme-and-supported-methods), not fake ones.

Given that you sent a `POST` with no body, Director applies no modification and answers with `304 Not Modified` - that's the expected behavior. The shown log line is not related to the (malformed) delete request but to the deployment request: it removes an old inactive stage and deploys a new one.

Cheers,
Thomas

**Comment by xenuser** [comment]
Oh well, this is so obvious that I didn't see it. Thanks a lot! After switching to request.delete everything went fine.

The X-HTTP-Method-Override stuff is something I kept from my code when talking to the Icinga2 API. I didn't question this part although I am working with another API..

Thanks!!

**Comment by Thomas-Gelf** [comment]
Glad to hear that it works! Let me add one additional note, just in case someone might now jump in and ask for `X-HTTP-Method-Override` support:

Short answer: **no**.

Long answer, someone who needs such a hacky workaround is in one of the following scenarios:

| Scenario | Solution |
| -------- | -------- |
| Web server with no PUT/DELETE support | Get a real web server |
| Proxy server with no PUT/DELETE support | Get a real proxy server or circumvent it when talking to the REST API |
| Web server forbids PUT/DELETE | If that's your admins policy, you have to deal with that |
| Proxy, ALG or similar forbids PUT/DELETE | If that's your admins policy you have to live with that |

Supporting all related hacky `X-*` headers would mean that sooner or later someone might ask for support for:

* `X-HTTP-Method` (Microsoft)
* `X-HTTP-Method-Override` (Google/GData)
* `X-METHOD-OVERRIDE` (IBM)

All of them in a case insensitive way. I'm strictly against doing so, especially seen from a security point of view. Someone might ask for "Better browser support allowing me to play with the API", and as soon as then someone weakens the restriction allowing such headers only for POST requests we might have introduced a security hole.

Given all that: **no**. No one asked yet, but I just wanted to state this anyways ;-)
