### ISSUE TITLE
Sync Rule did not accept boolean value from csv source for destination disabeld for host object

### ISSUE THREAD

**Issue by xtruthx** [Icinga/icingaweb2-module-director#937]
Servus.

Description:
A field from .csv source which contain a boolean value "True" or "true" (same for "false") is not accepted by the directors syncrule. This was recognised while trying to import the value for the directors object host field "disabled".

System:
OS: RHEL7
Webserver: Apache2 (actual version)
PHP: 5.4.16
Icinga Web 2 Version: 2.4.1
Director Version:  	1.3.1
Fileshipper Version: Release Tag  1.0.0

Import field was recognised correctly as shown in the preview:
![imported_field](https://cloud.githubusercontent.com/assets/2736347/26155597/fe2fbd46-3b13-11e7-9a91-95335c4de932.PNG)

Error in the Sync Rule:
![wtf_boolean](https://cloud.githubusercontent.com/assets/2736347/26155633/1ed26bb6-3b14-11e7-96ad-f7dafa54bd2f.PNG)

**Comment by Thomas-Gelf** [comment]
There is no "boolean" value when your data source is a CSV file. Internal boolean properties like "disabled" also accept values like y/n and 1/0, but it would be best if your data source could provide a "real" boolean. You can use the `Property Modifier` named **Convert to a boolean value** to accomplish this.

Cheers,
Thomas

**Comment by xtruthx** [comment]
Hi Thomas,
ok thanks. I did not try a single character like "y" or "n". Thats works fine. And your suggested modifier would be the best.
Sorry for superfluous noise.

Cheers,
truth

**Comment by Thomas-Gelf** [comment]
Don't worry, you're welcome!
