### ISSUE TITLE
Fields not available, dashboard not working

### ISSUE THREAD

**Issue by plfiumi** [Icinga/icingaweb2-module-director#938]
Hi, I have the following exception:

```
Fatal error: Uncaught Error: Call to undefined method Icinga\Data\Db\DbQuery::union() in /usr/share/icingaweb2/modules/director/library/Director/Dashboard/Dashboard.php:158
Stack trace:
#0 /usr/share/icingaweb2/modules/director/library/Director/Dashboard/Dashboard.php(130): Icinga\Module\Director\Dashboard\Dashboard->getObjectSummary(Array)
#1 /usr/share/icingaweb2/modules/director/library/Director/Dashboard/Dashboard.php(91): Icinga\Module\Director\Dashboard\Dashboard->fetchDashletSummaries()
#2 /usr/share/icingaweb2/modules/director/library/Director/Dashboard/Dashboard.php(64): Icinga\Module\Director\Dashboard\Dashboard->dashlets()
#3 /usr/share/icingaweb2/modules/director/library/Director/Dashboard/Dashboard.php(69): Icinga\Module\Director\Dashboard\Dashboard->count()
#4 /usr/share/icingaweb2/modules/director/application/controllers/DashboardController.php(33): Icinga\Module\Director\Dashboard\Dashboard->isAvailable()
#5 /usr/share/icingaweb2/modules/director/application/controllers/IndexController.php(35): Icinga\Modu in /usr/share/icingaweb2/modules/director/library/Director/Dashboard/Dashboard.php on line 158
```

(same error is described here and doesn't seem to be resolved for Ubuntu 16.x (my case)): https://github.com/Icinga/icingaweb2-module-director/issues/867), for this reason, my dashboard is not working.

**But this isn't the most annoying, I can work without dashboard, my problem is that I don't find fields customization anywhere**.

Can you help me?

Thanks in advance!

**Comment by Thomas-Gelf** [comment]
Guess the requirements are not satisfied, please check your [Icinga Web 2](https://github.com/Icinga/icingaweb2-module-director/blob/master/doc/02-Installation.md#requirements) version.

**Comment by plfiumi** [comment]
Hey Thomas! Thank you so much, even when I've installed Icinga2 yesterday for the first time, my Icinga2web version was 2.1.0, I already update it to the latest version and both dashboard and custom fields are working like a charm! ;)

**Comment by lazyfrosch** [comment]
:+1:
