### ISSUE TITLE
Provide possibility to include "inline" Icinga DSL in fields

### ISSUE THREAD

**Issue by AHeinlein** [Icinga/icingaweb2-module-director#939]
As discussed in [this thread]( https://monitoring-portal.org/index.php?thread/40670-datetime-object-im-director-verwenden-wie-geht-das/) (german), I would like to see a feature to include Icinga DSL snippets inline in fields, like 
FieldXY = "foobar-" + DateTime().format("%Y.%m.%d")

**Comment by Thomas-Gelf** [comment]
From a config tools perspective I still see some problems with the DSL when it goes to replication, database persistence and run-time changes. Sooner or later we'll tackle them in Icinga in one way or the other. In the meantime apart from some special cases there is no support for DSL in custom vars / fields in the Director.

But you can usually easily work around this by putting your DSL into command arguments, using DSL there works fine. You might want to have a look at the screen-shots in [this issue](https://github.com/Icinga/icingaweb2-module-director/issues/496) to get an idea of what this can be used for.
