### ISSUE TITLE
Can't select all zones in "cluster zones" drop down menu 

### ISSUE THREAD

**Issue by NeverUsedID** [Icinga/icingaweb2-module-director#940]
If i want to execute a special check on a windows agent i cant select the zone of the agent in the "cluster zone" drop down menu. 

Is there a way to execute checks on other Agent based Hosts ?

I can create the zone manually, but than i have another problem:
At the moment  (i think) its not possible to execute single service checks on another host, because i can't set the endpoint for a service (only the zone).

I want to use that, because i have some windows PowerCLi checks to be executed on a Windowsserver, but i want to add the Service to the Linux VCenter host.

**Comment by Thomas-Gelf** [comment]
@NeverUsedID: just choose "Run on Agent" in the related Service Template.
