### ISSUE TITLE
Improve form element description behavior

### ISSUE THREAD

**Issue by Thomas-Gelf** [Icinga/icingaweb2-module-director#943]
We have a lot of description texts, sometimes very detailed. The current approach shows the description directly below the element, slowly fading it out to avoid jumping elements when switching between them. Just, they jump once faded out. This is no problem for people navigating forms with their keyboard, but irritating for mouse-users.

A better solution might be to move the description to the bottom of the current container.

**Comment by Thomas-Gelf** [comment]
Preview:

![director_new-form-element-description](https://cloud.githubusercontent.com/assets/553008/26267470/9a0d532c-3cea-11e7-8818-195b8bc8841d.png)

**Comment by friesoft** [comment]
This isn't really intuitive and also doesn't really work if you open all collapsible sections. Most of our collegues are searching through them by opening everything - with the Info Text at the bottom it quickly gets out of sight.
At least thats what it looks like from the screenshot :)
Maybe just Mouse over Infos?

**Comment by Thomas-Gelf** [comment]
Don't worry, it doesn't get out of sight - it stays stick at the bottom. And when doing so it adjusts the bottom padding of the form accordingly, so there is always enough space to show every element when scrolling down, even while showing form field descriptions.

Mouse over isn't mobile friendly, and some users can't keep their mouse still. It's often a lot of text to show. Reading documentation is hard, short pieces of text are easier to grasp. Not sure whether we should adapt all parts of the Keep-Trump-focused-Pattern, like writing sentences in a way mentioning the user's name on every second line ;-)

Still, I consider those description being important. They target a) Icinga Admins and b) their users. Those users are tweaking thresholds or adding hosts just from time to time. Good admins do not provide a "disk_partition_regex" field, but a field saying "Partitions" with a description like "Use this to eventually filter the monitored partitions. The format is a Regular Expression, so you might want to use something like `^/mnt/*|/backup|/tmp$`". I know, explaining regex to John Doe is hard, but one could at least try ;-) I've seen so many people writing Wiki pages full of text, explaining every parameter, and providing related links with every service. The Director way is more like "Show related information where it fits". No need to explain 30 command arguments, when the current service template just asks for 3 fields.

I do not want users to call me asking "what should I write into disk_partition_regex"? Just requiring me to ask them "Did you hover the question mark?". Said all this, this information should IMO always be there, immediately, without requiring interaction. Just wanted to explain my thoughts in that relation. Other opinions or ideas are welcome!

**Comment by Thomas-Gelf** [comment]
Has been pushed to `next`.
