### ISSUE TITLE
Order of array elements changes for service custom var when deleting one element

### ISSUE THREAD

**Issue by dgoetz** [Icinga/icingaweb2-module-director#949]
I have multiple services using NRPE and requiring nrpe_arguments in a specific order, so I created one, cloned and modified it. Some require one argument less, so I deleted the last argument which resulted in argument order changed from my ordering to alpha-numeric ordering.

**Comment by Thomas-Gelf** [comment]
Not sure whether I can follow you. Could you show me a related before/action/after example?

**Comment by dgoetz** [comment]
Not the real one, but an example I could create on my demo system.

Ordering before:
![Before](https://cloud.githubusercontent.com/assets/3658213/26348602/7ef6136a-3fad-11e7-9bb8-76da8d695a57.png)

I simply click the X next to 5.

Ordering after:
![After](https://cloud.githubusercontent.com/assets/3658213/26348677/c1261c76-3fad-11e7-825b-5cebda940d82.png)

**Comment by Thomas-Gelf** [comment]
Ok, got it - thanks!

**Comment by Thomas-Gelf** [comment]
Hi @dgoetz,

thanks for reporting this. I recently fixed a similar issue, and did some tests right now: it should now work as expected. In case it doesn't, please let me know!

Cheers,
Thomas
