### ISSUE TITLE
Allow for $config$ in assignment filters in Apply For rules

### ISSUE THREAD

**Issue by psi-4ward** [Icinga/icingaweb2-module-director#951]
The apply wizard is very limiting, I'd like to do:

```
apply Service "Certificate " for (config in host.vars.http_service_urls) {
    import "cert check"

    assign where config contains "https"
    vars.http_url = config

    import DirectorOverrideTemplate
}
```

So would be cool if there is a _freetext_ option.

**Comment by Thomas-Gelf** [comment]
Sorry, no free text here. Sure it would sometimes be a quick solution for some problems, but it is in no way worth the cost it would imply, it would basically break most principles Director has been built on. If I correctly understand your example all you need is 'config' showing up in the list of filterable properties once using `apply for`, right? That would be possible to implement.

And please note that your example wouldn't work. The operator "contains" is not what it looks like, it equals 'contains' in Icinga DSL and is in this context useful only to check for Array membership. If you want to match all strings starting with https please use `=` as an operator and `https*` as the right-hand expression.

**Comment by psi-4ward** [comment]
Ah yes, for this example $config$ in left-hand dropdown would solve this. Thanks.

**Comment by Thomas-Gelf** [comment]
Should work fine
