### ISSUE TITLE
icingacli director: Cannot read enabled modules. Config directory "/etc/icingaweb2" is not readable

### ISSUE THREAD

**Issue by Aleksey-Maksimov** [Icinga/icingaweb2-module-director#952]
icingacli director: Cannot read enabled modules. Config directory "/etc/icingaweb2" is not readable

Hello

I create Check-Plugin for using with Icinga Director cli: https://github.com/Aleksey-Maksimov/Icinga2/blob/master/scripts/snmp_vars_discovery.sh
If I run the plugin manually from root console, everything works well:

```
# /usr/lib/nagios/plugins/snmp_vars_discovery.sh -H ups10.holding.com -P 1 -C public

Host 'ups10.holding.com' has been modified
Host 'ups10.holding.com' has been modified
<output truncated>
Host 'ups10.holding.com' has been modified
Host 'ups10.holding.com' has been modified
Config 'ae9aeb0e6bdf970d36b74f82dc8e4743be675c17' has been deployed
```

In Icinga Director I have added a new Command "snmp-vars-discovery".
Output from "Preview" tab in Director:

```
object CheckCommand "snmp-vars-discovery" {
    import "plugin-check-command"
    command = [ PluginDir + "/snmp_vars_discovery.sh" ]
    arguments += {
        "--authpassword" = "$snmpv3_authpwd$"
        "--authproto" = "$snmpv3_authprot$"
        "--community" = "$snmp_community$"
        "--hostaddr" = "$address$"
        "--hostname" = {
            required = true
            value = "$host.name$"
        }
        "--privpasswd" = "$snmpv3_privpwd$"
        "--privproto" = "$snmpv3_privprot$"
        "--protocol" = {
            required = true
            value = "$snmp_version$"
        }
        "--seclevel" = "$snmpv3_seclevel$"
        "--secname" = "$snmpv3_user$"
    }
}

```
Then I added a new Service "SNMP Discovery". 
Output from "Preview" tab in Director:

```
template Service "SNMP Discovery" {
    check_command = "snmp-vars-discovery"
    max_check_attempts = "1"
    check_period = "Always"
    check_interval = 1m
    enable_notifications = false
    enable_active_checks = true
    enable_passive_checks = false
    enable_event_handler = false
    enable_perfdata = false
    volatile = false
}

```
Then I assigned the Service "SNMP Discovery" to the my host "ups10.holding.com" in Icinga Director and run "Check now".
As a result, I got error:

```
last_check_result: {
      active: true,
      check_source: "MON20.holding.com",
      command: [
        "/usr/lib/nagios/plugins/snmp_vars_discovery.sh",
        "--community",
        "public",
        "--hostaddr",
        "10.10.10.10",
        "--hostname",
        "ups10.holding.com",
        "--protocol",
        "1"
      ],
      execution_end: 1495639120.558057,
      execution_start: 1495639117.290358,
      exit_status: 3,
      output: "ERROR: Cannot read enabled modules. Config directory \"/etc/icingaweb2\" is not readable
ERROR: Cannot read enabled modules. Config directory \"/etc/icingaweb2\" is not readable
ERROR: Cannot read enabled modules. Config directory \"/etc/icingaweb2\" is not readable
<output truncated>
ERROR: Cannot read enabled modules. Config directory \"/etc/icingaweb2\" is not readable
ERROR: Cannot read enabled modules. Config directory \"/etc/icingaweb2\" is not readable",
      performance_data: [],
      schedule_end: 1495639120.558188,
      schedule_start: 1495639117,
      state: 3,
      type: "CheckResult",
      vars_after: {
        attempt: 1,
        reachable: true,
        state: 3,
        state_type: 1
      },
      vars_before: {
        attempt: 1,
        reachable: true,
        state: 3,
        state_type: 1
      }
    },

```

In Icinga Log (/var/log/icinga2/icinga2.log) just one event:

`[2017-05-24 18:18:37 +0300] information/ExternalCommandListener: Executing external command: [1495639117] SCHEDULE_FORCED_SVC_CHECK;ups10.holding.com;SNMP Discovery;1495639117`

The permissions for "/etc/icingaweb2" installed since the deployment and I have not changed:

```
# ls -la /etc/icingaweb2
total 40
drwxrws---   4 root     icingaweb2 4096 Mar  5 19:54 .
drwxr-xr-x 112 root     root       4096 Apr 28 17:32 ..
-rw-rw----   1 www-data icingaweb2  120 Mar  5 21:19 authentication.ini
-rw-rw----   1 www-data icingaweb2  259 Apr 18 08:10 config.ini
drwxr-s---   2 www-data icingaweb2 4096 Apr 26 22:40 enabledModules
-rw-rw----   1 www-data icingaweb2  268 Mar 30 11:01 groups.ini
drwxrws---   7 root     icingaweb2 4096 Apr  7 16:06 modules
-rw-rw----   1 www-data icingaweb2  845 Mar 29 20:48 resources.ini
-rw-r-----   1 root     icingaweb2  126 Mar  5 19:54 roles.back-ini
-rw-rw----   1 www-data icingaweb2 2185 Apr 27 09:00 roles.ini

```

My Environment:

Debian GNU/Linux 8.7 (jessie)
Icinga r2.6.3-1
IcingaWeb 2.4.1
Director 1.3.1

---

What am I doing wrong?

**Comment by Thomas-Gelf** [comment]
Your Icinga user (could be `nagios` when using official Debian packages) must either be a member of the `icingaweb2` group to be allowed to access `/etc/icingaweb2` or have a separate (eventually differing) configuration in another directory, exported as ICINGWEB_CONFIGDIR to the shell (or defined in your script).

Apart from that, your intention is to use a check plugin to feed Director with "inventory" data and let it trigger deployments when something changes, correct? While this might work I'd suggest to base at least part of this on the Director Import/Sync/Job automation components. That would allow you to define rules like "Deploy only during business hours and only when something changed and no other deployment took place within the last X minutes" - just to give you an example.

ImportSource is a hook, so you could have your very own code in your very own Icinga Web 2 module in an upgrade safe way. You could alternatively also just let you plugin fill text files (CSV, JSON, YAML, XML) and let the fileshipper import that file once a minute. An import job does nothing if the source didn't change, so don't worry about short intervals. It would still spend less resources than many parallel checks running for different hosts I guess.

But that's just a suggestion. Your approach is curious, as it wasn't meant to be used that way - but that doesn't mean that it is wrong. Please let me know whether and how it worked for you!

**Comment by Aleksey-Maksimov** [comment]
Hello, Thomas.

Thanks for the tip about "usermod -a -G icingaweb2 nagios"
Now my plugin works as intended.

icingacli director - intelligent command, and it does not update the Configuration in case if the variable values have not changed. Besides, I do not plan to use the "SNMP Discovery" Service call very often. For example, the Service will check for update SNMP properties once a week. In this configuration, there is one advantage - web-console operator (non-administrator) can invoke the update Configuration at any time on url "Check now".

I plan to soon write some articles/screencasts about configuring SNMP Probe/Trap/Discovery in Icinga Director in my Russian Blog. I'll provide a link to these articles then, if it's interesting.

Thanks again. Good luck.

**Comment by Thomas-Gelf** [comment]
You're welcome, glad that you like it. And sure, please let me have the link to those articles once you published them!

**Comment by Aleksey-Maksimov** [comment]
Hello, Thomas.

I just posted an article (screencast) about the plugin:  [Icinga плагин snmp_vars_discovery для инвентаризации расширенного набора свойств Хостов по данным, полученным по SNMP (для использования с Icinga Director)](https://blog.it-kb.ru/2017/11/05/icinga-plugin-snmp_vars_discovery-for-inventory-of-extended-host-properties-obtained-via-snmp-for-use-with-icinga-director-and-icingacli)

**Comment by ant0nwax** [comment]
Thanks Aleksey!

This seems to be the only resource for icinga2, traps and director, and I searched for quite a while, returning to GitHub for my last search :)

It is late today, but I am happy I found a webpage, translation to English works quite well, so I will try to implement the solution from your blog it-kb ru these days/weeks... if you like to add some update since your article is from 2017, maybe you know some latest improvements or things to consider...

Wish you a good day

**Comment by Aleksey-Maksimov** [comment]
Thanks ant0nwax. You can find all my notes about my experience with Icinga here: https://wiki.it-kb.ru/icinga

**Comment by ant0nwax** [comment]
Hi Aleksey

I maybe misunderstood something ?

My Question to @all:
How can I use Icinga2 as TrapHost AND configure this in Director...
Aleksey, after installing your plugin I have realized that it is only limited to your technology and not a trap host functionality but a discover...

You wrote this: SNMP Probe/Trap/Discovery 

and I am keen on the Trap and not the Discovery :)

Is it possible to use this with Director?

**Comment by ant0nwax** [comment]
Okay I think I found the correct link now, its not the link you posted here but this link:

https://translate.googleusercontent.com/translate_c?depth=1&rurl=translate.google.com&sl=ru&sp=nmt4&tl=en&u=https://blog.it-kb.ru/2017/08/23/deploy-and-configure-icinga-2-on-debian-8-part-13-2-snmp-trap-monitoring-of-network-devices-as-apc-eaton-ups-nmc-in-icinga-director/&xid=17259,15700021,15700043,15700186,15700190,15700256,15700259,15700262,15700265&usg=ALkJrhigu8hdpiqevnhCrgzehpWf2ui5eg
