### ISSUE TITLE
User without permissions can view/change objects

### ISSUE THREAD

**Issue by tobiasvdk** [Icinga/icingaweb2-module-director#956]
I have the following role configuration:
```
[view-only]
users = "monitorwebui"
permissions = "module/doc, module/generictts, module/grafana, module/icinga2-doc, module/monitoring"
```

But the user "monitorwebui" can view and change host, user and notifications objects.
![director_permissions_monitorwebui](https://cloud.githubusercontent.com/assets/3541433/26555021/7cbb07c8-4493-11e7-8371-c12523df87ab.png)

I'm using icingaweb2 2.4.1 (also latest master - af81006bceeffc6f592d10c311795d9507d240c2) and director (1c028801bc059146b3e20cca104f10ef043066ba).

**Comment by lazyfrosch** [comment]
That sounds odd, a user would need to have at least the permission "module/director". If not he gets blocked by Icinga Web 2 itself.

Here is a test with Icinga Web 2.4.1, and director master.

User guest only has the role "Guests", which only permission is "module/doc"

![bildschirmfoto von 2017-05-29 18-52-37](https://cloud.githubusercontent.com/assets/121874/26557247/0e6905d8-44a0-11e7-84d0-c092afddd0ee.png)

**Comment by tobiasvdk** [comment]
I have to dig deeper later ... maybe the user is part of a group with more permissions.

**Comment by tobiasvdk** [comment]
Works correctly. User was member of another group with more priviledges.
