### ISSUE TITLE
Check command 'file_age' does not exist, but exists

### ISSUE THREAD

**Issue by vittel1** [Icinga/icingaweb2-module-director#957]
Hi,

i want to test the 'check_file_age' command on my Ubuntu-Client. Icinga-Agent is installed on it. Disk,SWAP and Load works but file_age not. The state of the check is Unknown with the output "Check command 'file_age' does not exist.". But I do not find the error. Can someone help?

Service Definition on Director:
```
template Service "Linux-FileAge" {
    check_command = "file_age"
    max_check_attempts = "5"
    check_interval = 1m
    retry_interval = 1m
    command_endpoint = host_name
    vars.file_age_file = "/var/log/icinga2/icinga2.log"
}
```
Apply-Rule on Director:
```
apply Service "Linux-FileAge" {
    import "Linux-FileAge"

    assign where host.name == "hostname"

    import DirectorOverrideTemplate
}
```
PlugIn on remote Icinga-Client is installed:
```
ls /usr/lib/nagios/plugins | grep file_age
check_file_age
```
Config is synced to the client as well
```

/var/lib/icinga2/api/zones/director-global/director# cat service_templates.conf | grep file_age
    check_command = "file_age"
    vars.file_age_file = "/var/log/icinga2/icinga2.log"
```
Constants.conf on remote Icinga-Client
`
/* The directory which contains the plugins from the Monitoring Plugins project. */
const PluginDir = "/usr/lib/nagios/plugins"
`

**Comment by lazyfrosch** [comment]
Is the ITL included on your client?

Thats the line `include <plugins>` in the `icinga2.conf` there.

You can test this with the CLI tool on the agent:

```
icinga2 object list --type checkcommand --name file_age
```

**Comment by vittel1** [comment]
icinga2.conf looks like this
```
include "constants.conf"
include "zones.conf"
include "features-enabled/*.conf"

include <itl>
include <plugins>
```
The result of this command is empty:
`icinga2 object list --type checkcommand --name file_age`

It looks like the command is not declared in this config file:
`vim /usr/share/icinga2/include/command-plugins.conf`

Why not? Can I add is manually or will it be overwritten sometimes?

**Comment by lazyfrosch** [comment]
`file_age` has been added with Icinga 2.5.0, so probably you should update the agent.

https://github.com/Icinga/icinga2/commit/c999badd143d171649cbf3a2e4b1da76906d239f

**Comment by vittel1** [comment]
Oh yes...You're right...It seems that the offical Ubuntu repo is not up to date.
Add the Icinga-Repo 
`add-apt-repository ppa:formorer/icinga`
and now it is working...

Thanks for your help!
