### ISSUE TITLE
Cluster Zone setting from service template ignored when trying to force service into "Master" zone.

### ISSUE THREAD

**Issue by mdetrano** [Icinga/icingaweb2-module-director#961]
I noticed that if a service template is set to use a specific Cluster Zone, and the zone chosen is recognized by Director as the "Master" zone, then the zone chosen is ignored and the service ends up in the hosts's zone.

Occasionally, it is useful to run a service check from a parent zone but still associate the service with a host in the child zone.

The attached patch seems to fix the issue....services that don't inherit any zone from a service template use the associated host's zone, but if a zone is given that's the zone that will be used instead. (I can also submit this as a pull request if it is easier to work with it that way).

[service_zone_fix.txt](https://github.com/Icinga/icingaweb2-module-director/files/1058870/service_zone_fix.txt)

**Comment by Thomas-Gelf** [comment]
Thanks @mdetrano, in the current master this should be fixed in a slightly different way.
