### ISSUE TITLE
BUG: director REST API creates invalid objects

### ISSUE THREAD

**Issue by Wintermute2k6** [Icinga/icingaweb2-module-director#962]
Lets create an service which imports an non-existing template as an example: 

icingacli director service create --object_type object --object_name testobject --host host.without.a.name --imports nonexistingtemplate

Leads to the following correct output on the commandline:

ERROR: Icinga\Exception\NotFoundError in /usr/share/icingaweb2/modules/director/library/Director/Data/Db/DbObject.php:583 with message: Failed to load icinga_service for host_id IS NULL AND service_set_id IS NULL AND object_name = 'nonexistingtemplate'

But sadly doesn't stop the creation process as it can be seen in the activity log of the director.
![screen](https://user-images.githubusercontent.com/7203835/26923420-58dc4842-4c42-11e7-8b04-9b85e6efaf71.jpg)

There is no check that prevents this from happening.

**Comment by Thomas-Gelf** [comment]
Confirmed.

**Comment by Thomas-Gelf** [comment]
@Wintermute2k6: this should no longer be possible with the latest master. Can you confirm this?

**Comment by Wintermute2k6** [comment]
I have to test it today and then i can confirm it 😊


________________________________
