### ISSUE TITLE
at install passwords are imported from conf.d/api-users.conf

### ISSUE THREAD

**Issue by hboetes** [Icinga/icingaweb2-module-director#964]
OK I get it, api user accounts are imported during the setup. I just noticed director stopped working after I changed the password for user foreman so I started digging and found: 

```
mysql> select * from icinga_apiuser;
+----+-------------+-----------------+----------+----------+-----------+-------------+
| id | object_name | object_type     | disabled | password | client_dn | permissions |
+----+-------------+-----------------+----------+----------+-----------+-------------+
|  1 | foreman     | external_object | n        | secret3  | NULL      | NULL        |
|  2 | director    | external_object | n        | secret6  | NULL      | NULL        |
+----+-------------+-----------------+----------+----------+-----------+-------------+
2 rows in set (0.00 sec)
```

That's the passwords I used during test setup.

I think you can do better here and ask the user for a user:password combination or at least inform the user of what you're doing.

**Comment by Thomas-Gelf** [comment]
@hboetes:
> api user accounts are imported during the setup

Nope, they shouldn't. Kickstart wizard asks you for a username/password combination, and that's...

> I think you can do better here and ask the user for a user:password combination [..]

...the behavior you're asking for, isn't it?

Regards,
Thomas
