### ISSUE TITLE
Check execution parameters in host objects

### ISSUE THREAD

**Issue by paolozuliani** [Icinga/icingaweb2-module-director#966]
When a service template is assigned to a host it is not possible to change (actually the controls are not available) the check execution parameters. This approach implies that a new service template must be created for each different check execution requirement, even if the service is the same. It would be better and simpler if the check execution parameters could be changed at host level.

@bizzam : have you already advised this issue?

**Comment by Thomas-Gelf** [comment]
Hi @paolozuliani,

could the solution shown for #899 be what you're looking for? It would still require you to define the choices once for your Hosts and once for your Services. But from then on it would be as simple as shown in the given example (last screen-shot). It is already working here and will be released with v1.4.0. That release will come with a lot more useful tooling (like #894 and #895) that will make working with single services a pleasure.

Allowing to set check and retry intervals on every single object is something that would be technically easy, but I'm strictly against doing so. It would allow even users with lower privileges to (accidentally) DDoS your systems.

Regards,
Thomas

**Comment by paolozuliani** [comment]
Thank you, @Thomas-Gelf. As far as I understand I can define some sets of "check execution" profiles and apply them to a single service on a single host. That would be fine.

@bizzam: risolto.

**Comment by Thomas-Gelf** [comment]
@paolozuliani: exactly. Glad that you like the approach, so I'll close this issue in favor of #899. By the way, I had a longer phone call with a customer requiring exactly this feature (among others) this afternoon, hung up a couple of minutes ago. Together we tested this feature on one of their stage system, worked fine for them. So I guess you could expect this to be implemented very soon.

I'm probably going to clean the code up and check it into our official `next` branch within this week, together with a whole bunch of other changes. They should close quite some issues pinned for the v1.4.0 release. Afterwards there shouldn't be left much hindering us from scheduling a date for v1.4.0.
