### ISSUE TITLE
How to import arguments with property modifiers

### ISSUE THREAD

**Issue by maelig** [Icinga/icingaweb2-module-director#968]
I created a sql source from automation that queries the services of a nagios database. However, I can not change the service arguments with "**Modifiers**". I tried several methods (regex, split, replace) that you propose but without success. The arguments on nagios are separated by "**!**" As in the following example:

`!java!activemq.jar!activemq!1:1!1:1`

Expected result :

Service "check proc ActiveMQ" {
import "generic-service-nrpe"
    host_name = "hostname"
    check_command = "nrpe_check_proc_cmd_arg_owner"
    vars.ARG1 = "java"
    vars.ARG2 = "apache-activemq"
    vars.ARG3 = "activemq"
    vars.ARG4 = "1:1"
    vars.ARG5 = "1:1"
}

Do you know the method of doing it?

Thanks for your help.

## Your Environment

* Director version : 1.3.1
* Icinga Web 2 version : 2.4.1-1
* Icinga 2 version : 2.6.2-1
* Operating System and version: Ubuntu trusty

**Comment by lazyfrosch** [comment]
You would have to write and provide a special modifier with any module to achieve that.

Can't think of a useful generic way to that. Also because we recommend to use the Icinga 2 ITL commands.

**Comment by maelig** [comment]
Thanks for your feedback. 
I found the solution with "Modifiers" en declaring for each argument : 

- Target property : ARG1

- Regular expression based replacement : 
`/^\!\'*([\w\,\%\.\:\/]*)\'*\!*\'*[\w\,\%\.\:\/]*\'*\!*\'*[\w\,\%\.\:\/]*\'*\!*\'*[\w\,\%\.\:\/]*\'*\!*\'*[\w\,\%\.\:\/]*\'*\!*\'*[\w\,\%\.\:\/]*\'*/`

- Replacement
`\1`

Then I used the properties on sync rule by customizing the variables of each argument.

**Comment by Thomas-Gelf** [comment]
@maelig: glad that it works. However - doesn't look like something I'd love to maintain with lots of parameters :laughing: In case you want to get a more generic solution for this: could you please open a related feature request? I could imagine an "Extract Nagios/Icinga 1.x ARGs" modifier, allowing one to specify the desired "position" (ARG1/2/3...). Optionally, as many people used to define `!foo!bar!-s ome -o ther -p aram` this could optionally also offer to "extract `-p` from $ARG3$".

**Comment by maelig** [comment]
@Thomas-Gelf :  I open a related feature request #972.

Thanks.
