### ISSUE TITLE
external check command 'swap' does not import properly

### ISSUE THREAD

**Issue by NickThrew** [Icinga/icingaweb2-module-director#970]
Unsure why this happens but, for some reason the external command 'swap' does not show proper in director:

```bash
object CheckCommand "swap" {
    import "plugin-check-command"
    command = [ PluginDir + "/check_swap" ]
    timeout = 1m
    arguments += {
        "-a" = {
            description = "Conduct comparisons for all swap partitions, one by one"
            set_if = "$swap_allswaps$"
        }
        "-c" = {{
           ** /* Unable to fetch function body through API */ **
        }}
        "-n" = {
            description = "Resulting state when there is no swap regardless of thresholds. Possible values are \"ok\", \"warning\", \"critical\", \"unknown\". Defaults to \"critical\""
            value = "$swap_noswap$"
        }
        "-w" = {{
            ** /* Unable to fetch function body through API */ **
        }}
    }
    vars.swap_allswaps = false
    vars.swap_cfree = 25
    vars.swap_integer = true
    vars.swap_wfree = 50
}
```
Looking at these lines: 
```bash
/* Unable to fetch function body through API */
```

This is throwing off my ability to "piggyback" off of this command (I could write a new one sure and I have) but I just didn't know if this was a bug or specific to my environment.

I did confirm that everything, specifically the swap command, looks perfect in /usr/share/icinga2/include/command-plugins.conf

## Host environment

* Director version (System - About):

> Name	director
State	enabled disable
Version	1.3.1
Git commit	4d240976a3e1ffe1eb9555fa23067da4aed25a58
Description	Director - Config tool for Icinga 2
Icinga Director is a configuration tool that has been designed to make Icinga 2 configuration easy and understandable.
Dependencies	monitoring
Permissions	director/api: Allow to access the director API
director/audit: Allow to access the full audit log
director/showconfig: Allow to show configuration (could contain sensitive information)
director/deploy: Allow to deploy configuration
director/hosts: Allow to configure hosts
director/users: Allow to configure users
director/notifications: Allow to configure notifications
director/inspect: Allow to inspect objects through the Icinga 2 API (could contain sensitive information)
director/*: Allow unrestricted access to Icinga Director

* Icinga Web 2 version and modules (System - About):

>Version
2.4.1
Git commit
d74124bd12f53d13b5a6ea5408e9783cc5190d1e
Git commit date
2017-01-18
Copyright
© 2013-2017 The Icinga Project

* Icinga 2 version (`icinga2 --version`):

>icinga2 - The Icinga 2 network monitoring daemon (version: v2.6.3)
Copyright (c) 2012-2017 Icinga Development Team (https://www.icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Application information:
  Installation root: /usr
  Sysconf directory: /etc
  Run directory: /run
  Local state directory: /var
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

* Operating System and version:

>System information:
  Platform: CentOS Linux
  Platform version: 7 (Core)
  Kernel: Linux
  Kernel version: 3.10.0-514.21.1.el7.x86_64
  Architecture: x86_64
Build information:
  Compiler: GNU 4.8.5
  Build host: unknown

* Webserver, PHP versions:

>PHP 5.4.16 (cli) (built: Nov  6 2016 00:29:02)
Copyright (c) 1997-2013 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2013 Zend Technologies

>Server version: Apache/2.4.6 (CentOS)
Server built:   Apr 12 2017 21:03:28

**Comment by TechnoTaff** [comment]
I'm also getting this when importing by_ssh.
