### ISSUE TITLE
Unable to render existing config with kernel 3.10.0-514.21.2 CentOS7

### ISSUE THREAD

**Issue by knerhood** [Icinga/icingaweb2-module-director#973]
## Expected Behavior
A successful render of a config within director

## Current Behavior
When trying to render a config after updating to the latest kernel, I now get a failure in the Startup log `execvp: Argument list too long`  even after backing out all changes in director. Note that Icinga 

I implemented the steps as defined in [https://www.icinga.com/2017/06/20/advisory-for-latest-security-updates-on-rhel-7/](https://www.icinga.com/2017/06/20/advisory-for-latest-security-updates-on-rhel-7/) to get Icinga to start.

Also related to [Icinga Issue #5367](https://github.com/Icinga/icinga2/issues/5367)

## Steps to Reproduce (for bugs)
1. On CentOS update to kernel-3.10.0-514.21.2.el7.x86_64
2. Implement work around above to get Icinga to start
3. Attempt to render and/or deploy config

## Context
To be able to make changes in director and have them deploy to Icinga while being fully patched from a security perspective

## Your Environment

* Director version (System - About): 1.3.1
* Icinga Web 2 version and modules (System - About): 2.4.1
* Icinga 2 version (`icinga2 --version`): I get execvp: Argument list too long
* Operating System and version: CentOS 7
* Webserver, PHP versions: Apache, PHP 5.4.16

**Comment by Thomas-Gelf** [comment]
Hi @knerhood,

thanks for reporting this! However, as you already wrote - Director rendered and shipped it's config, so there isn't much he can do about this afterwards. The issue you're facing is already being addressed in the Icinga 2 issue tracker as [issue #5367](https://github.com/Icinga/icinga2/issues/5367). Hopefully they'll ship another kernel release soon, in the meantime you can use the workaround shown in the linked issue.

Regards,
Thomas
