### ISSUE TITLE
Re-Creating existing host over Director API causes '500 internal server error'

### ISSUE THREAD

**Issue by LordHepipud** [Icinga/icingaweb2-module-director#977]
Creating a host object over the Director API works fine unless the object is not exiting within the Director.

Example:

URL: https://localhost/icingaweb2/director/host
Method: PUT
JSON: 
```
{
"object_name":"demo.localhost",
"object_type":"object",
"vars":{"os":"Windows"},
"imports":["Icinga Agent"],
"address":"demo.localhost",
"display_name":"demo.localhost"
}
```

## Expected Behavior

The webservice should return '304 Not Modified'

## Current Behavior

The webservices returns '500 Internal Server Error'

## Steps to Reproduce (for bugs)

1. Create a host object within the Icinga Director
2. Try to Re-Create the host over the Icinga Director API

## Context

The Icinga 2 PowerShell module is right now simply throwing an exception because of the 500 error. The JSON responds 

```
{
    "error": "Trying to recreate icinga_host (ws-cstein-mobile.int.netways.de)"
}
```

Is not received because of the error, making it hard for users to understand if this is a real issue or if the host is simply already added.

## Your Environment

* Director version (System - About): 1.3.1
* Icinga Web 2 version and modules (System - About): 2.4.1
* Icinga 2 version (`icinga2 --version`): r2.6.3-1
* Operating System and version: Debian GNU/Linux 8.8 (jessie)
* Webserver, PHP versions: Apache/2.4.10 (Debian), PHP 5.6.30-0+deb8u1

**Comment by Thomas-Gelf** [comment]
Thanks for reporting this. This should give 4xx as it is clearly a user error, not a server error. Possible variants: 422, 409, 400. The error message itself sounds good to me.

**Comment by Thomas-Gelf** [comment]
Tested in `next`, also with the new powershell module. Works fine.
