### ISSUE TITLE
Property-modifier "convert to a Boolean" case sensitive

### ISSUE THREAD

**Issue by swizzly** [Icinga/icingaweb2-module-director#980]
Currently, property modifier "convert to a Boolean" is case sensitive. Values like "FALSE" or "TRUE" are not converted to booleans, only lower case words e.g. "false" or "true" are accepted. 
Could you please make the property modifier case insensitive?

**Comment by Thomas-Gelf** [comment]
Hi @swizzly,

the modifier should already be case insensitive. While the [valid strings](https://github.com/Icinga/icingaweb2-module-director/blob/master/library/Director/PropertyModifier/PropertyModifierMakeBoolean.php#L11) show a lowercased list, also your input is [lowercased](https://github.com/Icinga/icingaweb2-module-director/blob/master/library/Director/PropertyModifier/PropertyModifierMakeBoolean.php#L65) before comparing them. Are you sure it doesn't work?

**Comment by swizzly** [comment]
Ok, the problem is not with the case sensitiveness, but rather Import Preview doesn't show Booleans correctly --> new Ticket https://github.com/Icinga/icingaweb2-module-director/issues/981
