### ISSUE TITLE
Import Preview doesn't show booleans correctly

### ISSUE THREAD

**Issue by swizzly** [Icinga/icingaweb2-module-director#981]
In Import Preview the false boolean values are not displayed correctly, they are empty instead of "0", while true values are shown correctly as "1".
Please fix it.

**Comment by Thomas-Gelf** [comment]
Thanks for reporting this, will be fixed!

**Comment by tobiasvdk** [comment]
Looks like an duplicate of #602.

**Comment by Thomas-Gelf** [comment]
Thanks @tobiasvdk, fixed for #602.
