### ISSUE TITLE
Plain config file shipping: Director doesn't see shipped objects

### ISSUE THREAD

**Issue by xenuser** [Icinga/icingaweb2-module-director#982]
Hi there!

I use Fileshipper and Director to configure my Icinga2 installation.
Objects shipped via "Plain config file shipping" (https://github.com/Icinga/icingaweb2-module-fileshipper/blob/master/doc/04-FileShipping.md) are deployed correctly (I see them via icinga2 object list), but Director is not aware of those objects.

## Expected Behavior
When I run "render config" and "deploy" and "kickstart wizard", I expect to see the deployed checkcommand within Director -> Commands.

## Current Behavior
I do not see the shipped checkcommand within Director -> Commands.
The consequence is that if I want to use the checkcommand within a service I Imported via Fileshipper and CSV, I receive an error message ("command unknown" or something like that).

## Steps to Reproduce (for bugs)

Example directories.ini:

```
[conf_direct]
source = /srv/mon/direct-shipping
target = zones.d

```

Example config file (/srv/mon/direct-shipping/demo-global/commands/CS-windows_check_data.conf ):

```
object CheckCommand "CS-windows_check_date" {
  import "plugin-check-command"
  command = ["powershell.exe" ]
  arguments = {
        "-command" = {
                value = "CS-windows_check_date.ps1"
                order = -1
                }
        "-f" = {
                order = 1
                value = "$args_path$"
                description = "Mandatory: File or Folder to check"
                required = true
                }
        "-w" = {
                order = 11
                value = "$args_exit_warn$"
                description = "Mandatory: Warning threshold"
                }
        "-c" = {
                order = 12
                value = "$args_exit_crit$"
                description = "Mandatory: Critical threshold"
                }
        "-t" = {
                order = 13
                value = "$args_exit_timerange$"
                description = "Optional: time range | d=Days (default) | h=Hours | m=Minutes | s=Seconds"
                }
        "-l" = {
                order = 21
                value = "$args_logfile$"
                description = "Optional: Logfile"
                }

";exit" = {
                value = "$$LASTEXITCODE"
                order = 99
                }
        }
}
```

Now click "render config", "deploy" and "kickstart wizard" within Icingaweb2/Director and click on Director -> Commands.

## Context
Some config is shipped via Fileshipper -> CSV import, some config is shipped via "Plain config file shipping". It seems like they do not work together since Director seems to be unaware of the objects being shipped by "Plain config file shipping".

## Your Environment
* Director version (System - About): 1.3.0
* Icinga Web 2 version and modules (System - About):  2.6.3.1
* Icinga 2 version (`icinga2 --version`): 2.4.1
* Operating System and version: Ubuntu 16.04
* Webserver, PHP versions: Apache2, PHP 7.0

**Comment by xenuser** [comment]
Looking at the code, I believe that the following part is responsible for the described behavior:

```
    public function getObjects($name, $pluraltype, $attrs = array(), $ignorePackage = null)
    {
        $name = strtolower($name);
        $params = (object) array(
        );
        if ($ignorePackage) {
            $params->filter = 'obj.package!="' . $ignorePackage . '"';
        }
```

(CoreApi.php)

When I comment the if-clause, Director will know about the recently shipped checkcommand definition.

I also think that I know why this code was placed and that this problem can't be solved easily.  Still, I would like to know what the thoughts of the devs are regarding this topic.

**Comment by Thomas-Gelf** [comment]
From the README:

> That's what this part of fileshipper has been designed for. It allows you to tell Director to deploy additional config files without even trying to understand them.

No chance to get them into Director that way, at least not as he deploys everything to the very same package. We could eventually add the possibility to deploy fileshipper-provided objects to a dedicated package, this would allow us to then later import Commands from the core.

But may I ask why you are shipping commands that way? I see no good reason for this. The "plain config file" part of the fileshipper is mainly for objects you are NOT able to define with the Director, your command doesn't look to fall into that category.

**Comment by xenuser** [comment]
First of all: Thank you for your fast feedback! Appreciate it.

I thought you'd write that. The idea of having a dedicated package is great and if possible, I would like to suggest this as a feature (officially).

Regarding your question:
Of course you may ask.

In this specific case, an enterprise customer wants to enable different kinds of (technical) people to provide new Icinga2 configuration.

The not-so-technical-staff can use a self-written tool for generating mass configuration (e.g. generating 200 new windows disk services). The result will be a CSV file which will be imported via Fileshipper and deployed via Director.

Now, there are also the more-technical-skilled-guys at the customer, they write Icinga2 configuration directly.

In both cases, each config file is deployed via a Git repository, so deployment happens more-or-less automatically.

Now, in this case, a not-so-technical-guy used a new check command which was introduced by a technical-guy via Plain file shipping.

So we have two different workflows here which enable the customer to involve all kinds of people in configuring the monitoring landscape.

So far this worked out quite well, but in some cases, it doesn't.

**Comment by tmey** [comment]
It would be possible, to put the example into the Director itself. But there are some Configs, which we cant put into Director. But at this configs it would be very fine, to use the deployment-mechanismen of the director-GUI.

**Comment by Thomas-Gelf** [comment]
@tmey: Technically speaking, Icinga 2 does not have a configuration format but a DSL. So there is no way to parse and serialize a "configuration" file. Please understand that Icinga 2 is not able to serialize it's own configuration, so why should an external tool even try doing so? Sure, it would be easy to partially support this. But that would mean creating a monster that could easily get an unmaintainable mess, as more related feature request would definitively follow.

@xenuser: sorry, the explained use-case makes no sense to me. If you want to deploy plaintext config please consider doing so without the Icinga Director. You can then trigger a Kickstart run as many times as you want to teach Director about those newly deployed Commands. To me, it makes no sense to offer an Icinga Service Template inside the Director without related manually cured parameters and Custom Fields.

Everything else is abusing Director for a job it hasn't been designed for. So, in my opinion not implementing this is an attempt to protect you from yourself :laughing:.

As you correctly pointed out, Kickstart might be able to import those objects. And, even if I absolutely do not like above use-case, this could be implemented. After fetching information related to the last Deployment, Director could fetch all Commands from the Core API, even those deployed by the Director. It could use `source_location` properties to figure out whether they have been rendered or just deployed by Director - and then it could create them as "External Objects" in his database.

This way, it still would remain a two-step story, but it would probably help to address your use-case.

Thoughts?

**Comment by Thomas-Gelf** [comment]
This is kind of an exotic request and not trivial at all. We are of course always open to discussions / other opinions, and if this really matters eventually sponsoring the feature could be an option. As of this time, there are no plans on our side to implement this feature.
