### ISSUE TITLE
"show based on filter" not working with data fields of type array

### ISSUE THREAD

**Issue by Hrocc** [Icinga/icingaweb2-module-director#983]
## Expected Behavior

Show based on filter should work with arrays

## Current Behavior

error after setting a filter of datatype array:

![filter](https://user-images.githubusercontent.com/25223332/27631320-5bce4ba2-5bf8-11e7-9611-35164e63ac77.JPG)

![error](https://user-images.githubusercontent.com/25223332/27631256-3ef10376-5bf8-11e7-87c0-0cb27d5e9923.jpg)

## Steps to Reproduce (for bugs)

1. define costum date field of type array
2. add a field to host template
3. set "show based on filter" to the one defined in 1) 
4. select "contains"
5. set condition

## Context

show only relevant data fields when configuring hosts based on a data field of type array

## Your Environment

* Director version (System - About): 1.3.1 - current master
* Icinga Web 2 version and modules (System - About): 2.4.1
* Icinga 2 version (`icinga2 --version`): r2.6.3-1
* Operating System and version: Debian 8
* Webserver, PHP versions:

**Comment by mwaldmueller** [comment]
+1

# Environment
Director version (System - About): master, Git commit: 7cd307ea53c0cfc8eccb360ab1bb2b367dcace4f
Icinga Web 2 version and modules (System - About): 2.4.1
Icinga 2 version (icinga2 --version): r2.7.0-1
Operating System and version: CentOS Linux release 7.3.1611 (Core)
Webserver, PHP versions: Apache, PHP 5.4.16
