### ISSUE TITLE
Kickstart should delete old CheckCommands

### ISSUE THREAD

**Issue by mwaldmueller** [Icinga/icingaweb2-module-director#985]
The kickstart run should delete CheckCommands, that are not available any more.

**Comment by Thomas-Gelf** [comment]
Makes sense to me. It currently only purges vanished external Zones and Endpoints, but doesn't do so for commands.

**Comment by TobiasKneidl** [comment]
Can we get this in the next version?

**Comment by Thomas-Gelf** [comment]
Sure. I personally wanted to have it in v1.5.0, blocking issue was that one might get not-so-helpful error messages in case `kickstart` tries to remove Commands that are "in use". This could also be some old, disabled Service object - and therefore a perfectly valid scenario. In such case, helpful hints should be given. Afterwards, wiping unused external commands is pretty easy.

As this changes behavior I'll schedule it for v1.6.0 and not for the upcoming v1.5.2 patch release.

**Comment by Stefomat** [comment]
Is there a possible workaround to delete old, unused commands while we wait for this to be implemented?

**Comment by robpou** [comment]
I would also be interested in the last question.

**Comment by robpou** [comment]
Ok, workaround:
1. backup mysql
2. delete the corresponding commands from the director database, e.g.
> delete from icinga_command where id = 'xy' ;
3. ???
4. profit!

(and NOT from the icinga database, like I tried ca. 15 times; and not using the API like I had been trying to for an hour, since it's external objects cannot be deleted using the API)
