### ISSUE TITLE
Inspect fails when check output contains malformed characters

### ISSUE THREAD

**Issue by sysadmama** [Icinga/icingaweb2-module-director#987]
Hi Tom,

we use SNMP to check our Ricoh printers; "Unabhängiger Tonerzulieferer" seems to be a value that comes from the printer itself. At least snmpwalk gives answers like this:

```
...
iso.3.6.1.2.1.43.17.6.1.5.1.1 = STRING: "Power"
iso.3.6.1.2.1.43.17.6.1.5.1.2 = STRING: "Fehler am Drucker"
iso.3.6.1.2.1.43.17.6.1.5.1.3 = STRING: "Datenempfang"
...
```

Running the check on console:
```
...
OK - Unabh�ngiger Tonerzulieferer {30136}( 4 5 10 1 30136 1)
```

Unfortunately, it is a "malformed character" indeed, and "Inspect" stracktraces on that.
Do you see a possibility to avoid that?
![screen shot 2017-06-30 at 13 31 57](https://user-images.githubusercontent.com/11242139/27733911-dcf1bda8-5d98-11e7-9b7d-7a570f1b237f.jpg)

Cheers,
  Marianne

## Expected Behavior

It should show Inspect content.

## Current Behavior

It doesn't.

## Steps to Reproduce (for bugs)

1. Take a printer with weird software.
2. Tell him so speak German.
3. Do SNMP queries with umlaut results.

## Context

Users think the monitoring is broken always when they see stacktraces.

## Your Environment

* Director version (System - About): 1.3.1 // 4d240976a3e1ffe1eb9555fa23067da4aed25a58
* Icinga Web 2 version and modules (System - About): 2.4.0 // 7a2d8eda8dd8c37198d0e754218cdedd12e3fde4
* Icinga 2 version (`icinga2 --version`): r2.6.3-1
* Operating System and version: Ubuntu 16.04.2 LTS
* Webserver, PHP versions: apache2-2.4.18, php7-7.0.18

**Comment by Thomas-Gelf** [comment]
@sysadmama: so you're saying that the Icinga 2 API ships invalid JSON? If that's the case, any chance you could reproduce this with a simple curl call and open a dedicated issue in the icinga2 issue tracker? Something like this should never happen. Related data should either not be accepted or normalized when "entering" the core. Shipping invalid JSON with any kind of "graceful" JSON parsing is not an option at all, no matter where it appears. This it might open the door for all kinds of security issues.

**Comment by sysadmama** [comment]
Closing this, opened [that](https://github.com/Icinga/icinga2/issues/5395).
