### ISSUE TITLE
Custom Agent Port

### ISSUE THREAD

**Issue by KoffeinKaio** [Icinga/icingaweb2-module-director#995]
I'm hosting a Server 'srv2' that has no internet connection that is only reachable trough another host 'srv1'.
The srv1 already has an icinga agent running and the port 5665 is used, srv2 listens on 5666 via iptables redirect.
Now there is no way of specifiing an agent port while creating the host.

I already tried the suggestion from issue #919 to create an endpoint prior to cresting the host but icinga still wants to connect to 5665.
Also tried to edit the endpoint files of the director myself - that works for a while - until they get overwritten again.

Is it somehow possible to supply a port and optionally an ip address for the agent connection while creating the host? 
Or is there any other solution?

Icinga version: r2.6.3-1
icinga2director version: 4d240976a3e1ffe1eb9555fa23067da4aed25a58
icinga2web: 2.4.1

**Comment by Thomas-Gelf** [comment]
Hi @KoffeinKaio,

you shouldn't create config files in obscure locations but instead create those endpoint objects directly in the Director ("Infrastructure" Dashboard). You'll see that the related host preview then changes.

Cheers,
Thomas

**Comment by KoffeinKaio** [comment]
Hey @Thomas-Gelf ,

Maybe that was misleading. I created the endpoint in the director menu.

I Tried both ways:
 - first host then endpoint
- first endpoint then host

**Comment by Thomas-Gelf** [comment]
Order doesn't matter

**Comment by KoffeinKaio** [comment]
Somewhere I'm going the wrong way.
Heres what I do:
- create the Host in the director
- run the generated agent script on srv2
- setup endpoint in director
- deploy

which results in "endpoint srv2 already declared"

**Comment by Thomas-Gelf** [comment]
Please show related config snippets, endpoint, zone, host.

**Comment by KoffeinKaio** [comment]
1: create host: https://imagebin.ca/v/3T0JXCHkOorH
2: create endpoint https://imagebin.ca/v/3T0JdknEkKy7

**Config file "zones.d/t2.xxxxx.xx/endpoints.conf"**
`object Endpoint "git.xxxxx.xx" {
    host = "git.xxxxx.xx"
    port = "5666"
    log_duration = 0s
}`

**Config file "zones.d/t2.xxxxx.xx/agent_endpoints.conf"**
object Endpoint "xxxxx.xx" {
    host = "xxx.xxx.xxx.xxx"
    log_duration = 0s
}

object Endpoint "vpn.xxxxx.xx" {
    host = "xxx.xxx.xxx.xxx"
    log_duration = 0s
}

zones.conf on git.xxxxx.xx:
`/** Icinga 2 Config - proposed by Icinga Director */

// TODO: improve establish connection handling
object Endpoint "git.xxxxx.xx" {}
object Endpoint "t2.xxxxx.xx" {}
object Zone "t2.xxxxx.xx" {
  endpoints = [ "t2.xxxxx.xx" ]
  // TODO: all endpoints in master zone
}

object Zone "director-global" { global = true }

object Zone "git.xxxxx.xx" {
  parent = "t2.xxxxx.xx"
  endpoints = [ "git.xxxxx.xx" ]
}`

**Comment by Thomas-Gelf** [comment]
It's not that easy to get your XXs straight - I cannot really distinct which object refers to what. Is t2.xxxxx.xx your master zone? Do you have all endpoints connected to your master, or are there satellites? Did you configure the Endpoint object to sit in the Agents parent zone? And: no need to add a Director API user to that endpoint. In case you somehow instructed Director to deploy to the Agent you already lost the game, in that case clean up `/var/lib/icinga2/api`on the Agent.

**Comment by KoffeinKaio** [comment]
xxxxx.xx is just my domain, censored, its the same everywhere
t2 is my master, every agent host is connected to t2
the zone is always t2, its the only one

If I dont add the director user on git. the director failys to deploy with "unable to authenticate"

It seems like the director already pushed to the agent, but even if I:
1. add the host
2. add the endpoint
3. run the agent script on git.
4. deploy changes on the director

It's the same result.

**Comment by Thomas-Gelf** [comment]
Your screenshot shows that the git endpoint has a configured API user, "director". Remove that one, or Director might choose to deploy config to it. Your setup sounds simple, so please also try to do not set all those Zone properties manually. Director is not that bad at choosing the best one for you (check preview, when unsure). Usually you need to touch that property only when satellites are involved.

**Comment by KoffeinKaio** [comment]
If I add & deploy (with git. icinga agent beeing stopped) the endpoint without api user and zone it says:

> 
> information/ApiListener: My API identity: t2.xxxxx.xx
> critical/config: Error: Endpoint 'git.xxxxx.xx' does not belong to a zone.
> Location: in [stage]/zones.d/t2.xxxxx.xx/endpoints.conf: 1:0-1:28
> [stage]/zones.d/t2.xxxxx.xx/endpoints.conf(1): object Endpoint "git.xxxxx.xx" {
>                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> [stage]/zones.d/t2.xxxxx.xx/endpoints.conf(2):     host = "git.xxxxx.xx"
> [stage]/zones.d/t2.xxxxx.xx/endpoints.conf(3):     port = "5666"
> 
> critical/config: 1 error

**Comment by Thomas-Gelf** [comment]
Ouch... the endpoint itself needs a zone. Sorry for the confusion.

**Comment by KoffeinKaio** [comment]
Even if I add the t2 Zone to the endpoint its still the sam eerror "does not blong to a zone".
I cant deploy unless I add the api user too (and the connection hast to succeed).

**Comment by Thomas-Gelf** [comment]
Please clean up /var/lib/icinga2/api on git:

    rm -rf /var/lib/icinga2/api/packages
    rm -rf /var/lib/icinga2/api/zones

Unfortunately Icinga 2 is bad at cleaning up wrong/outdated config, related issues exist. So traces of old configuration attempts might influence the result you're seeing. Also, please let the Icinga master be the ONLY node with a configured Api User in Director's Endpoint list.

**Comment by KoffeinKaio** [comment]
I can do that, but as written above, the agent on git. is not even started. All errors in my last post are on t2 @ the director web interface

**Comment by Thomas-Gelf** [comment]
Please preview the Zone "git.xxxxx.xx" in the Director, it must look like this:

```
zones.d/t2.xxxxx.xx/zones.conf:

object Zone "git.xxxxx.xx" {
    parent = "t2.xxxxx.xx"
    endpoints = [ "git.xxxxx.xx" ]
}
```

**Comment by KoffeinKaio** [comment]
Well... seems like that did the trick. There was no Zone for git. auto created.
I created one with parent zone t2. and it seems to work now.

Thnak you so much for your patience, lemme buy you a coffee :)

**Comment by Thomas-Gelf** [comment]
Glad to hear that, you're welcome! And of course, coffee is always welcome!

**Comment by blessendor** [comment]
Issue must be re-opened - no way to create custom agent port with such methode, as described above - bcs Icinga2 Director will create TWO endpoints/zones with the same name ans icinga2 agent will not start. 

@KoffeinKaio how did you resolved "re-defined" error?

**Comment by blessendor** [comment]
I have tried your method with custom zone for endpoint behind NAT, but then Director generates settings with re-defined zone & endpoint with the same names but with wrong parent zone:

**Error**:


root@mail:~# cat /var/log/icinga2/startup.log
information/cli: Icinga application loader (version: r2.8.1-1)
information/cli: Loading configuration file(s).
critical/config: Error: Object 'mail.somehost.behind.nat.com' of type 'Zone' re-defined: in /etc/icinga2/zones.conf: 13:1-13:35; previous definition: in /etc/icinga2/zones.conf: 6:1-6:35
Location: in /etc/icinga2/zones.conf: 13:1-13:35
/etc/icinga2/zones.conf(11): object Zone "director-global" { global = true }
/etc/icinga2/zones.conf(12): 
/etc/icinga2/zones.conf(13): object Zone "mail.somehost.behind.nat.com" {
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/etc/icinga2/zones.conf(14):   parent = "mail.somehost.behind.nat.com"
/etc/icinga2/zones.conf(15):   endpoints = [ "mail.somehost.behind.nat.com" ]

**Config:**

root@mail:~# cat /etc/icinga2/zones.conf
```
/** Icinga 2 Config - proposed by Icinga Director */

// TODO: improve establish connection handling
object Endpoint "mail.somehost.behind.nat.com" {}
object Endpoint "icinga.masterhost.com" {}
object Zone "mail.somehost.behind.nat.com" {
  endpoints = [ "mail.somehost.behind.nat.com" ]
  // TODO: all endpoints in master zone
}

object Zone "director-global" { global = true }

object Zone "mail.somehost.behind.nat.com" {
  parent = "mail.somehost.behind.nat.com"
  endpoints = [ "mail.somehost.behind.nat.com" ]
}
```

Still need solution to monitore many icinga2 agent hosts behind NAT with one Public reachable IP and custom icinga2 agent port (forwarding), when we use top-down scheme with Director.

**Comment by blessendor** [comment]
Looks like we must don't select Cluster zone during creating new host object with icinga2 Director: leave undefined - this will apply default cluster zone name (master) or we can chose manualy master zone from drop-down list but we must DON'T chose custom created Zone with custom port here.

**Comment by sirtoobii** [comment]
Solution: #919
