### ISSUE TITLE
Correctly render numeric custom variable names

### ISSUE THREAD

**Issue by NetVicious** [Icinga/icingaweb2-module-director#996]
I'm starting with icinga2 and I created a command in icinga-director.

On the Argument tab I created one argument with a $1$ text in the value.

That value it's used later on the Fields tab for the custom fields.

icinga-director takes only the number and assigns it to the optional fields we can fill on the services later.

The problem it's when you try to deploy it. You will get one error which means icinga2 doesn't accepts custom fields which start by a number or only a number.

I tried to fix if on icinga-director but It showd me one error related with one SQL but allowed me to modify it. But the deploy continues failing.

I need to delete some rows directly from the database related with this wrong custom filels to enable another time the deploy.

## Expected Behavior
Icinga-director should not allow to establish a custom field which name starts by a number, or it's only a number. I don't know which it's the resctriction which applies on icinga2 to this.

## Current Behavior
Icinga-director doesn't shows a warning, and all the deployments got one error.
If you try to fix it from icinga-director you will get one SQL error and you should need to remove they directly on the database by hand.

## Possible Solution
Show a warning and don't allow the user to use that custom fields name.

## Your Environment
* Director version (System - About): 1.3.1
* Icinga Web 2 version and modules (System - About): 2.4.1
* Icinga 2 version (`icinga2 --version`): version: r2.6.0-1

* Operating System and version: Debian GNU/Linux 9
* Webserver, PHP versions: Apache 2.4.25-3+deb9u1, PHP 7.0.19-1

**Comment by Thomas-Gelf** [comment]
> Icinga-director should not allow to establish a custom field which name starts by a number, or it's only a number.

Makes sense.

> If you try to fix it from icinga-director you will get one SQL error

Could you please show me this error?

**Comment by NetVicious** [comment]
I'm trying to recreate it now but I don't remember how I created it.
Icinga2 doesn't likes this config:

template Service "some_check" {
    import "_Default_service"

    check_command = "check_some"
    vars.password = "pass"
    vars.user = "user"
    **vars.1 = "1"**
}

And icinga-director should not allow to create fields like that.

**Comment by Thomas-Gelf** [comment]
> And icinga-director should not allow to create fields like that.

I guess rendering it as vars["1"] = "1" would also fix the problem. While I do not like numeric-only properties at all, they should be perfectly valid in Icinga 2. Still interested in the Exception, would be great if you could reproduce that somehow.

**Comment by NetVicious** [comment]
I got it.
I have a command with one argument with value $2$
I created the field assigning a name.
I added a custom value for that field on the service template
I added a value for that field on a service which it's related with the previous service template

If I go to the command and I modify that field assigning in the field combobox a "other available field" which appears as "2 (2)" I got the next exception.

One additional problem it's there it's no transactions on the database access so the service continues with that field and there it's no way to edit that within director.

If I remember well, I needed to modify directly from the database the tables `director_datafield` and `icinga_service_var` to remove the bad fields with numbers.

```
Failed to load icinga_command_field for command_id = '205' AND datafield_id = '7'
```

```
#0 /usr/share/icingaweb2/modules/director/library/Director/Data/Db/DbObject.php(1034): Icinga\Module\Director\Data\Db\DbObject->loadFromDb()
#1 /usr/share/icingaweb2/modules/director/library/Director/Web/Form/DirectorObjectForm.php(844): Icinga\Module\Director\Data\Db\DbObject::load(Array, Object(Icinga\Module\Director\Db))
#2 /usr/share/icingaweb2/modules/director/library/Director/Web/Controller/ObjectController.php(278): Icinga\Module\Director\Web\Form\DirectorObjectForm->loadObject(Array)
#3 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Director\Web\Controller\ObjectController->fieldsAction()
#4 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('fieldsAction')
#5 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#6 /usr/share/php/Icinga/Application/Web.php(389): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#7 /usr/share/php/Icinga/Application/webrouter.php(109): Icinga\Application\Web->dispatch()
#8 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...')
#9 {main}
```

**Comment by Thomas-Gelf** [comment]
Thanks for this. I pushed a fix for the rendering issue in the meantime, will try to reproduce the exception. If we can fix this I'd prefer to continue with allowing numeric variable names - even if I would personally never use such :laughing:

**Comment by NetVicious** [comment]
No problem. I'm migrating from Nagios to Icinga and I was trying to understand how it works. I used $1$ because I thought it worked like parameters in bash. Obviously now I'm using better names for the arguments and fields ;-)

**Comment by Thomas-Gelf** [comment]
@NetVicious: rendering is fixed and tested. I tried hard to reproduce your fields-related exception with the current `next` branch, eventually it has already been fixed. Will hopefully merge `next` into `master` within this week, might eventually happen today. In case you find some time to test it and the problem persists please let me know. Will close this issue so far.
