### ISSUE TITLE
Allow setting of global zones for upcoming Powershell Integration

### ISSUE THREAD

**Issue by widhalmt** [Icinga/icingaweb2-module-director#997]
Hi,

Some of my customers are using combinations of the mandatory `director-global` zone and some other global zones like `global-templates`, `global-satellite`, `global-linux` etc.

Please add a way to define global templates which should by added by the fully automated setup routine of Director 1.4 and the Powershell module.

Cheers,
Thomas

**Comment by Thomas-Gelf** [comment]
@LordHepipud: I would suggest to add a setting named `GlobalZones`, with the according `global_zones` parameter shipped through the Self Service API. That should be an array and default to `["director-global"]. Your plaintext mode would ship it comma separated.

**Comment by LordHepipud** [comment]
Opened a referenced issue for this. I assume all of them require

`
    global = true
`

**Comment by Thomas-Gelf** [comment]
@LordHepipud: sure

**Comment by LordHepipud** [comment]
Implemented on PS-Module next branche [Commit Issue #42](https://github.com/Icinga/icinga2-powershell-module/commit/457774fb717c86cf0d751c26a389247a17c6b761)

Will be merged into master after detailed testing.

**Comment by widhalmt** [comment]
We tested the Powershell part and this works.

**Comment by Thomas-Gelf** [comment]
First shot will tell all the nodes about all global zones, and there is one central place to configure them. So, as of this writing, no way to configure different global zones for different self-service templates. Has not been asked for in this issue, but I know that you also have such requirements ;-)

We might tackle this once global zone handling and distribution has been improved in the Core itself, either through fixing current issues or by adding support for semi-global zones.

Cheers,
Thomas

**Comment by Thomas-Gelf** [comment]
@widhalmt: pushed related changes, please let me know whether this works so far.
